package com.jmr.mcx.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/***
 * \
 * @author Pritiranjan Swain
 *
 */

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * McxBeneficiary generated by hbm2java
 */
@Entity
@Table(name = "MCX_BENEFICIARY", schema = "JMR_OBDX")

public class McxBeneficiary implements java.io.Serializable {

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	private long id;

	@Column(name = "PAYYE_NAME", nullable = false, length = 100)
	private String payyeName;

	@Column(name = "ACCOUNT_NAME", nullable = false, length = 100)
	private String accountName;

	@Column(name = "BRANCH_CODE", nullable = false, length = 100)
	private String branchCode;

	@Column(name = "NICK_NAME", nullable = false, length = 100)
	private String nickName;

	@Column(name = "ACCOUNT_NUMBER", nullable = false, length = 100)
	private String accountNumber;

	@Column(name = "IS_ACTIVE", nullable = false, length = 5)
	private String isActive;

	@Temporal(TemporalType.DATE)
	@Column(name = "REGISTRATION_DATE_TIME", nullable = false, length = 7)
	private Date registrationDateTime;

	@Column(name = "SWIFT_CODE", length = 100)
	private String swiftCode;

	@Column(name = "NCC", length = 100)
	private String ncc;

	@Column(name = "PAY_MODE", nullable = false, length = 100)
	private String pMode;

	@Column(name = "BANK_NAME", nullable = false, length = 100)
	private String bankName;

	@Column(name = "CITY", nullable = false, length = 100)
	private String city;

	@Column(name = "BANK_ADDR", nullable = false, length = 100)
	private String bankAddr;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_USER_ID", nullable = false)
	private McxUser mcxUser;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_TRANSFER_VIA_TYPE_ID", nullable = false)
	private McxTransferViaType mcxTransferViaType;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REF_TRANSFER_TYPE_ID", nullable = false)
	private McxTransferType mcxTransferType;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mcxBeneficiary")
	private Set<McxTransactionData> mcxTransactionDatas = new HashSet<McxTransactionData>(0);

	public McxBeneficiary(long id, McxUser mcxUser, McxTransferViaType mcxTransferViaType,
			McxTransferType mcxTransferType, String payyeName, String accountName, String branchCode, String nickName,
			String accountNumber, String isActive, Date registrationDateTime) {
		this.id = id;
		this.mcxUser = mcxUser;
		this.mcxTransferViaType = mcxTransferViaType;
		this.mcxTransferType = mcxTransferType;
		this.payyeName = payyeName;
		this.accountName = accountName;
		this.branchCode = branchCode;
		this.nickName = nickName;
		this.accountNumber = accountNumber;
		this.isActive = isActive;
		this.registrationDateTime = registrationDateTime;
	}

	public McxBeneficiary(long id, McxUser mcxUser, McxTransferViaType mcxTransferViaType,
			McxTransferType mcxTransferType, String payyeName, String accountName, String branchCode, String nickName,
			String accountNumber, String isActive, Date registrationDateTime, String swiftCode, String ncc,
			Set<McxTransactionData> mcxTransactionDatas) {
		this.id = id;
		this.mcxUser = mcxUser;
		this.mcxTransferViaType = mcxTransferViaType;
		this.mcxTransferType = mcxTransferType;
		this.payyeName = payyeName;
		this.accountName = accountName;
		this.branchCode = branchCode;
		this.nickName = nickName;
		this.accountNumber = accountNumber;
		this.isActive = isActive;
		this.registrationDateTime = registrationDateTime;
		this.swiftCode = swiftCode;
		this.ncc = ncc;
		this.mcxTransactionDatas = mcxTransactionDatas;
	}

	// Method is for adding a new beneficiary
	public McxBeneficiary(McxUser mcxUser, McxTransferViaType mcxTransferViaType, McxTransferType mcxTransferType,
			String payyeName, String accountName, String branchCode, String nickName, String accountNumber,
			String isActive, Date registrationDateTime, String swiftCode, String ncc) {
		this.mcxUser = mcxUser;
		this.mcxTransferViaType = mcxTransferViaType;
		this.mcxTransferType = mcxTransferType;
		this.payyeName = payyeName;
		this.accountName = accountName;
		this.branchCode = branchCode;
		this.nickName = nickName;
		this.accountNumber = accountNumber;
		this.isActive = isActive;
		this.registrationDateTime = registrationDateTime;
		this.swiftCode = swiftCode;
		this.ncc = ncc;
	}

	// Method for adding new domestic beneficiary -Anju
	public McxBeneficiary(McxUser mcxUser, McxTransferViaType mcxTransferViaType, McxTransferType mcxTransferType,
			String payyeName, String accountName, String branchCode, String accountNumber, String isActive,
			Date registrationDateTime) {

		this.mcxUser = mcxUser;
		this.mcxTransferViaType = mcxTransferViaType;
		this.mcxTransferType = mcxTransferType;
		this.payyeName = payyeName;
		this.accountName = accountName;
		this.branchCode = branchCode;
		this.accountNumber = accountNumber;
		this.isActive = isActive;
		this.registrationDateTime = registrationDateTime;
		

	}
	public McxBeneficiary(McxUser mcxUser, McxTransferViaType mcxTransferViaType, McxTransferType mcxTransferType,
			String payyeName, String accountName, String branchCode, String accountNumber, String isActive,
			Date registrationDateTime, String pMode, String bankName, String city, String bankAddr) {

		this.mcxUser = mcxUser;
		this.mcxTransferViaType = mcxTransferViaType;
		this.mcxTransferType = mcxTransferType;
		this.payyeName = payyeName;
		this.accountName = accountName;
		this.branchCode = branchCode;
		this.accountNumber = accountNumber;
		this.isActive = isActive;
		this.registrationDateTime = registrationDateTime;
		this.pMode = pMode;
		this.bankName = bankName;
		this.city = city;
		this.bankAddr = bankAddr;

	}

	public McxBeneficiary() {
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public McxUser getMcxUser() {
		return this.mcxUser;
	}

	public void setMcxUser(McxUser mcxUser) {
		this.mcxUser = mcxUser;
	}

	public McxTransferViaType getMcxTransferViaType() {
		return this.mcxTransferViaType;
	}

	public void setMcxTransferViaType(McxTransferViaType mcxTransferViaType) {
		this.mcxTransferViaType = mcxTransferViaType;
	}

	public McxTransferType getMcxTransferType() {
		return this.mcxTransferType;
	}

	public void setMcxTransferType(McxTransferType mcxTransferType) {
		this.mcxTransferType = mcxTransferType;
	}

	public String getPayyeName() {
		return this.payyeName;
	}

	public void setPayyeName(String payyeName) {
		this.payyeName = payyeName;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public Date getRegistrationDateTime() {
		return this.registrationDateTime;
	}

	public void setRegistrationDateTime(Date registrationDateTime) {
		this.registrationDateTime = registrationDateTime;
	}

	public String getSwiftCode() {
		return this.swiftCode;
	}

	public void setSwiftCode(String swiftCode) {
		this.swiftCode = swiftCode;
	}

	public String getNcc() {
		return this.ncc;
	}

	public void setNcc(String ncc) {
		this.ncc = ncc;
	}

	public Set<McxTransactionData> getMcxTransactionDatas() {
		return this.mcxTransactionDatas;
	}

	public void setMcxTransactionDatas(Set<McxTransactionData> mcxTransactionDatas) {
		this.mcxTransactionDatas = mcxTransactionDatas;
	}

	public String getpMode() {
		return pMode;
	}

	public void setpMode(String pMode) {
		this.pMode = pMode;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getBankAddr() {
		return bankAddr;
	}

	public void setBankAddr(String bankAddr) {
		this.bankAddr = bankAddr;
	}

}
