package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountnicknamesId generated by hbm2java
 */
@Embeddable
public class AccountnicknamesId  implements java.io.Serializable {


     private String identity;
     private String idcust;
     private String codbranch;
     private String accttype;
     private String iduser;
     private String codacctno;

    public AccountnicknamesId() {
    }

    public AccountnicknamesId(String identity, String idcust, String codbranch, String accttype, String iduser, String codacctno) {
       this.identity = identity;
       this.idcust = idcust;
       this.codbranch = codbranch;
       this.accttype = accttype;
       this.iduser = iduser;
       this.codacctno = codacctno;
    }
   


    @Column(name="IDENTITY", nullable=false, length=5)
    public String getIdentity() {
        return this.identity;
    }
    
    public void setIdentity(String identity) {
        this.identity = identity;
    }


    @Column(name="IDCUST", nullable=false, length=10)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }


    @Column(name="CODBRANCH", nullable=false, length=5)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }


    @Column(name="ACCTTYPE", nullable=false, length=3)
    public String getAccttype() {
        return this.accttype;
    }
    
    public void setAccttype(String accttype) {
        this.accttype = accttype;
    }


    @Column(name="IDUSER", nullable=false, length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }


    @Column(name="CODACCTNO", nullable=false, length=20)
    public String getCodacctno() {
        return this.codacctno;
    }
    
    public void setCodacctno(String codacctno) {
        this.codacctno = codacctno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccountnicknamesId) ) return false;
		 AccountnicknamesId castOther = ( AccountnicknamesId ) other; 
         
		 return ( (this.getIdentity()==castOther.getIdentity()) || ( this.getIdentity()!=null && castOther.getIdentity()!=null && this.getIdentity().equals(castOther.getIdentity()) ) )
 && ( (this.getIdcust()==castOther.getIdcust()) || ( this.getIdcust()!=null && castOther.getIdcust()!=null && this.getIdcust().equals(castOther.getIdcust()) ) )
 && ( (this.getCodbranch()==castOther.getCodbranch()) || ( this.getCodbranch()!=null && castOther.getCodbranch()!=null && this.getCodbranch().equals(castOther.getCodbranch()) ) )
 && ( (this.getAccttype()==castOther.getAccttype()) || ( this.getAccttype()!=null && castOther.getAccttype()!=null && this.getAccttype().equals(castOther.getAccttype()) ) )
 && ( (this.getIduser()==castOther.getIduser()) || ( this.getIduser()!=null && castOther.getIduser()!=null && this.getIduser().equals(castOther.getIduser()) ) )
 && ( (this.getCodacctno()==castOther.getCodacctno()) || ( this.getCodacctno()!=null && castOther.getCodacctno()!=null && this.getCodacctno().equals(castOther.getCodacctno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdentity() == null ? 0 : this.getIdentity().hashCode() );
         result = 37 * result + ( getIdcust() == null ? 0 : this.getIdcust().hashCode() );
         result = 37 * result + ( getCodbranch() == null ? 0 : this.getCodbranch().hashCode() );
         result = 37 * result + ( getAccttype() == null ? 0 : this.getAccttype().hashCode() );
         result = 37 * result + ( getIduser() == null ? 0 : this.getIduser().hashCode() );
         result = 37 * result + ( getCodacctno() == null ? 0 : this.getCodacctno().hashCode() );
         return result;
   }   


}


