package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcctactivityHeader generated by hbm2java
 */
@Entity
@Table(name="ACCTACTIVITY_HEADER"
    ,schema="FCDBADMIN_RK"
)
public class AcctactivityHeader  implements java.io.Serializable {


     private AcctactivityHeaderId id;
     private String codaccttype;
     private String codtcy;
     private String nambrn;
     private Date activitytime;
     private Date txndatefrom;
     private Date txndateto;
     private Date valuedatefrom;
     private Date valuedateto;
     private BigDecimal fromamount;
     private BigDecimal toamount;
     private String referenceno;
     private BigDecimal openingbalance;
     private BigDecimal closingbalance;
     private BigDecimal debitamount;
     private BigDecimal creditamount;
     private Integer totalrecords;
     private Boolean sortorder;
     private Boolean drcrflg;
     private Short pagesize;
     private String runbalflg;
     private String namtcy;
     private Boolean sortby;
     private Byte searchby;

    public AcctactivityHeader() {
    }

	
    public AcctactivityHeader(AcctactivityHeaderId id) {
        this.id = id;
    }
    public AcctactivityHeader(AcctactivityHeaderId id, String codaccttype, String codtcy, String nambrn, Date activitytime, Date txndatefrom, Date txndateto, Date valuedatefrom, Date valuedateto, BigDecimal fromamount, BigDecimal toamount, String referenceno, BigDecimal openingbalance, BigDecimal closingbalance, BigDecimal debitamount, BigDecimal creditamount, Integer totalrecords, Boolean sortorder, Boolean drcrflg, Short pagesize, String runbalflg, String namtcy, Boolean sortby, Byte searchby) {
       this.id = id;
       this.codaccttype = codaccttype;
       this.codtcy = codtcy;
       this.nambrn = nambrn;
       this.activitytime = activitytime;
       this.txndatefrom = txndatefrom;
       this.txndateto = txndateto;
       this.valuedatefrom = valuedatefrom;
       this.valuedateto = valuedateto;
       this.fromamount = fromamount;
       this.toamount = toamount;
       this.referenceno = referenceno;
       this.openingbalance = openingbalance;
       this.closingbalance = closingbalance;
       this.debitamount = debitamount;
       this.creditamount = creditamount;
       this.totalrecords = totalrecords;
       this.sortorder = sortorder;
       this.drcrflg = drcrflg;
       this.pagesize = pagesize;
       this.runbalflg = runbalflg;
       this.namtcy = namtcy;
       this.sortby = sortby;
       this.searchby = searchby;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=30) ), 
        @AttributeOverride(name="codacctno", column=@Column(name="CODACCTNO", nullable=false, length=30) ), 
        @AttributeOverride(name="codbrn", column=@Column(name="CODBRN", nullable=false, length=5) ) } )
    public AcctactivityHeaderId getId() {
        return this.id;
    }
    
    public void setId(AcctactivityHeaderId id) {
        this.id = id;
    }

    
    @Column(name="CODACCTTYPE", length=2)
    public String getCodaccttype() {
        return this.codaccttype;
    }
    
    public void setCodaccttype(String codaccttype) {
        this.codaccttype = codaccttype;
    }

    
    @Column(name="CODTCY", length=3)
    public String getCodtcy() {
        return this.codtcy;
    }
    
    public void setCodtcy(String codtcy) {
        this.codtcy = codtcy;
    }

    
    @Column(name="NAMBRN", length=120)
    public String getNambrn() {
        return this.nambrn;
    }
    
    public void setNambrn(String nambrn) {
        this.nambrn = nambrn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTIVITYTIME", length=7)
    public Date getActivitytime() {
        return this.activitytime;
    }
    
    public void setActivitytime(Date activitytime) {
        this.activitytime = activitytime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TXNDATEFROM", length=7)
    public Date getTxndatefrom() {
        return this.txndatefrom;
    }
    
    public void setTxndatefrom(Date txndatefrom) {
        this.txndatefrom = txndatefrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TXNDATETO", length=7)
    public Date getTxndateto() {
        return this.txndateto;
    }
    
    public void setTxndateto(Date txndateto) {
        this.txndateto = txndateto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALUEDATEFROM", length=7)
    public Date getValuedatefrom() {
        return this.valuedatefrom;
    }
    
    public void setValuedatefrom(Date valuedatefrom) {
        this.valuedatefrom = valuedatefrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALUEDATETO", length=7)
    public Date getValuedateto() {
        return this.valuedateto;
    }
    
    public void setValuedateto(Date valuedateto) {
        this.valuedateto = valuedateto;
    }

    
    @Column(name="FROMAMOUNT", precision=22, scale=3)
    public BigDecimal getFromamount() {
        return this.fromamount;
    }
    
    public void setFromamount(BigDecimal fromamount) {
        this.fromamount = fromamount;
    }

    
    @Column(name="TOAMOUNT", precision=22, scale=3)
    public BigDecimal getToamount() {
        return this.toamount;
    }
    
    public void setToamount(BigDecimal toamount) {
        this.toamount = toamount;
    }

    
    @Column(name="REFERENCENO", length=100)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    
    @Column(name="OPENINGBALANCE", precision=22, scale=3)
    public BigDecimal getOpeningbalance() {
        return this.openingbalance;
    }
    
    public void setOpeningbalance(BigDecimal openingbalance) {
        this.openingbalance = openingbalance;
    }

    
    @Column(name="CLOSINGBALANCE", precision=22, scale=3)
    public BigDecimal getClosingbalance() {
        return this.closingbalance;
    }
    
    public void setClosingbalance(BigDecimal closingbalance) {
        this.closingbalance = closingbalance;
    }

    
    @Column(name="DEBITAMOUNT", precision=22, scale=3)
    public BigDecimal getDebitamount() {
        return this.debitamount;
    }
    
    public void setDebitamount(BigDecimal debitamount) {
        this.debitamount = debitamount;
    }

    
    @Column(name="CREDITAMOUNT", precision=22, scale=3)
    public BigDecimal getCreditamount() {
        return this.creditamount;
    }
    
    public void setCreditamount(BigDecimal creditamount) {
        this.creditamount = creditamount;
    }

    
    @Column(name="TOTALRECORDS", precision=5, scale=0)
    public Integer getTotalrecords() {
        return this.totalrecords;
    }
    
    public void setTotalrecords(Integer totalrecords) {
        this.totalrecords = totalrecords;
    }

    
    @Column(name="SORTORDER", precision=1, scale=0)
    public Boolean getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(Boolean sortorder) {
        this.sortorder = sortorder;
    }

    
    @Column(name="DRCRFLG", precision=1, scale=0)
    public Boolean getDrcrflg() {
        return this.drcrflg;
    }
    
    public void setDrcrflg(Boolean drcrflg) {
        this.drcrflg = drcrflg;
    }

    
    @Column(name="PAGESIZE", precision=3, scale=0)
    public Short getPagesize() {
        return this.pagesize;
    }
    
    public void setPagesize(Short pagesize) {
        this.pagesize = pagesize;
    }

    
    @Column(name="RUNBALFLG", length=1)
    public String getRunbalflg() {
        return this.runbalflg;
    }
    
    public void setRunbalflg(String runbalflg) {
        this.runbalflg = runbalflg;
    }

    
    @Column(name="NAMTCY", length=120)
    public String getNamtcy() {
        return this.namtcy;
    }
    
    public void setNamtcy(String namtcy) {
        this.namtcy = namtcy;
    }

    
    @Column(name="SORTBY", precision=1, scale=0)
    public Boolean getSortby() {
        return this.sortby;
    }
    
    public void setSortby(Boolean sortby) {
        this.sortby = sortby;
    }

    
    @Column(name="SEARCHBY", precision=2, scale=0)
    public Byte getSearchby() {
        return this.searchby;
    }
    
    public void setSearchby(Byte searchby) {
        this.searchby = searchby;
    }




}


