package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Applicationmessage generated by hbm2java
 */
@Entity
@Table(name="APPLICATIONMESSAGE"
    ,schema="FCDBADMIN_RK"
)
public class Applicationmessage  implements java.io.Serializable {


     private ApplicationmessageId id;
     private String txtmessage;
     private Character isguienabled;
     private String moduleid;
     private Character istranslatable;
     private String comments;

    public Applicationmessage() {
    }

	
    public Applicationmessage(ApplicationmessageId id) {
        this.id = id;
    }
    public Applicationmessage(ApplicationmessageId id, String txtmessage, Character isguienabled, String moduleid, Character istranslatable, String comments) {
       this.id = id;
       this.txtmessage = txtmessage;
       this.isguienabled = isguienabled;
       this.moduleid = moduleid;
       this.istranslatable = istranslatable;
       this.comments = comments;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idmessage", column=@Column(name="IDMESSAGE", nullable=false, length=20) ), 
        @AttributeOverride(name="idlang", column=@Column(name="IDLANG", nullable=false, length=3) ), 
        @AttributeOverride(name="iddevice", column=@Column(name="IDDEVICE", nullable=false, length=2) ) } )
    public ApplicationmessageId getId() {
        return this.id;
    }
    
    public void setId(ApplicationmessageId id) {
        this.id = id;
    }

    
    @Column(name="TXTMESSAGE", length=4000)
    public String getTxtmessage() {
        return this.txtmessage;
    }
    
    public void setTxtmessage(String txtmessage) {
        this.txtmessage = txtmessage;
    }

    
    @Column(name="ISGUIENABLED", length=1)
    public Character getIsguienabled() {
        return this.isguienabled;
    }
    
    public void setIsguienabled(Character isguienabled) {
        this.isguienabled = isguienabled;
    }

    
    @Column(name="MODULEID", length=20)
    public String getModuleid() {
        return this.moduleid;
    }
    
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid;
    }

    
    @Column(name="ISTRANSLATABLE", length=1)
    public Character getIstranslatable() {
        return this.istranslatable;
    }
    
    public void setIstranslatable(Character istranslatable) {
        this.istranslatable = istranslatable;
    }

    
    @Column(name="COMMENTS", length=4000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


