package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditlogdetail generated by hbm2java
 */
@Entity
@Table(name="AUDITLOGDETAIL"
    ,schema="FCDBADMIN_RK"
)
public class Auditlogdetail  implements java.io.Serializable {


     private AuditlogdetailId id;
     private String namfield;
     private String fieldvalue;
     private String description;
     private Date dattxn;

    public Auditlogdetail() {
    }

	
    public Auditlogdetail(AuditlogdetailId id) {
        this.id = id;
    }
    public Auditlogdetail(AuditlogdetailId id, String namfield, String fieldvalue, String description, Date dattxn) {
       this.id = id;
       this.namfield = namfield;
       this.fieldvalue = fieldvalue;
       this.description = description;
       this.dattxn = dattxn;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idseq", column=@Column(name="IDSEQ", nullable=false, precision=15, scale=0) ), 
        @AttributeOverride(name="numline", column=@Column(name="NUMLINE", nullable=false, precision=38, scale=0) ) } )
    public AuditlogdetailId getId() {
        return this.id;
    }
    
    public void setId(AuditlogdetailId id) {
        this.id = id;
    }

    
    @Column(name="NAMFIELD", length=30)
    public String getNamfield() {
        return this.namfield;
    }
    
    public void setNamfield(String namfield) {
        this.namfield = namfield;
    }

    
    @Column(name="FIELDVALUE")
    public String getFieldvalue() {
        return this.fieldvalue;
    }
    
    public void setFieldvalue(String fieldvalue) {
        this.fieldvalue = fieldvalue;
    }

    
    @Column(name="DESCRIPTION", length=2000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATTXN", length=7)
    public Date getDattxn() {
        return this.dattxn;
    }
    
    public void setDattxn(Date dattxn) {
        this.dattxn = dattxn;
    }




}


