package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BtadvicetemplateId generated by hbm2java
 */
@Embeddable
public class BtadvicetemplateId  implements java.io.Serializable {


     private String idbttxn;
     private String templatename;
     private String isdefault;

    public BtadvicetemplateId() {
    }

    public BtadvicetemplateId(String idbttxn, String templatename, String isdefault) {
       this.idbttxn = idbttxn;
       this.templatename = templatename;
       this.isdefault = isdefault;
    }
   


    @Column(name="IDBTTXN", nullable=false, length=2)
    public String getIdbttxn() {
        return this.idbttxn;
    }
    
    public void setIdbttxn(String idbttxn) {
        this.idbttxn = idbttxn;
    }


    @Column(name="TEMPLATENAME", nullable=false, length=35)
    public String getTemplatename() {
        return this.templatename;
    }
    
    public void setTemplatename(String templatename) {
        this.templatename = templatename;
    }


    @Column(name="ISDEFAULT", nullable=false, length=1)
    public String getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BtadvicetemplateId) ) return false;
		 BtadvicetemplateId castOther = ( BtadvicetemplateId ) other; 
         
		 return ( (this.getIdbttxn()==castOther.getIdbttxn()) || ( this.getIdbttxn()!=null && castOther.getIdbttxn()!=null && this.getIdbttxn().equals(castOther.getIdbttxn()) ) )
 && ( (this.getTemplatename()==castOther.getTemplatename()) || ( this.getTemplatename()!=null && castOther.getTemplatename()!=null && this.getTemplatename().equals(castOther.getTemplatename()) ) )
 && ( (this.getIsdefault()==castOther.getIsdefault()) || ( this.getIsdefault()!=null && castOther.getIsdefault()!=null && this.getIsdefault().equals(castOther.getIsdefault()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdbttxn() == null ? 0 : this.getIdbttxn().hashCode() );
         result = 37 * result + ( getTemplatename() == null ? 0 : this.getTemplatename().hashCode() );
         result = 37 * result + ( getIsdefault() == null ? 0 : this.getIsdefault().hashCode() );
         return result;
   }   


}


