package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Btcustreg generated by hbm2java
 */
@Entity
@Table(name="BTCUSTREG"
    ,schema="FCDBADMIN_RK"
)
public class Btcustreg  implements java.io.Serializable {


     private String btid;
     private String custgroupid;
     private Character flgcustgroup;
     private Character flgfinancial;
     private BigDecimal typepayment;
     private BigDecimal typetransaction;
     private BigDecimal typeaccount;
     private Character flgencrdecr;
     private Character flgresponsereq;
     private Character flgctrlfilereq;
     private Character flgadvicereq;
     private String tmpltadvice;
     private BigDecimal nbrcurrfiles;
     private BigDecimal priority;
     private String btiddesc;
     private Character flgactive;
     private Date datcreated;
     private Character emailusage;
     private String authlimit;
     private Character benevalidate;
     private String clientcode;
     private Character confirmreq;
     private Character chequenoexists;
     private Character s2srequired;
     private Character s2spreauthorized;
     private Character s2sresponsereq;
     private Character issignatoryrequiredincashin;
     private String s2surl;
     private String s2srevflag;
     private String specialtempid;
     private String idEntity;
     private Blob udfdata;
     private Date datedeactivate;
     private String userdeactivate;
     private BigDecimal btidlimit;
     private String s2smode;
     private Character flgemailadvicereq;
     private Character isdefaultTemplate;
     private Set<Btstep> btsteps = new HashSet<Btstep>(0);
     private Set<Btacctmap> btacctmaps = new HashSet<Btacctmap>(0);
     private Bttechinfo bttechinfo;
     private Set<Btusermap> btusermaps = new HashSet<Btusermap>(0);
     private Set<Btidcustentitymap> btidcustentitymaps = new HashSet<Btidcustentitymap>(0);
     private Btlimitauth btlimitauth;

    public Btcustreg() {
    }

	
    public Btcustreg(String btid) {
        this.btid = btid;
    }
    public Btcustreg(String btid, String custgroupid, Character flgcustgroup, Character flgfinancial, BigDecimal typepayment, BigDecimal typetransaction, BigDecimal typeaccount, Character flgencrdecr, Character flgresponsereq, Character flgctrlfilereq, Character flgadvicereq, String tmpltadvice, BigDecimal nbrcurrfiles, BigDecimal priority, String btiddesc, Character flgactive, Date datcreated, Character emailusage, String authlimit, Character benevalidate, String clientcode, Character confirmreq, Character chequenoexists, Character s2srequired, Character s2spreauthorized, Character s2sresponsereq, Character issignatoryrequiredincashin, String s2surl, String s2srevflag, String specialtempid, String idEntity, Blob udfdata, Date datedeactivate, String userdeactivate, BigDecimal btidlimit, String s2smode, Character flgemailadvicereq, Character isdefaultTemplate, Set<Btstep> btsteps, Set<Btacctmap> btacctmaps, Bttechinfo bttechinfo, Set<Btusermap> btusermaps, Set<Btidcustentitymap> btidcustentitymaps, Btlimitauth btlimitauth) {
       this.btid = btid;
       this.custgroupid = custgroupid;
       this.flgcustgroup = flgcustgroup;
       this.flgfinancial = flgfinancial;
       this.typepayment = typepayment;
       this.typetransaction = typetransaction;
       this.typeaccount = typeaccount;
       this.flgencrdecr = flgencrdecr;
       this.flgresponsereq = flgresponsereq;
       this.flgctrlfilereq = flgctrlfilereq;
       this.flgadvicereq = flgadvicereq;
       this.tmpltadvice = tmpltadvice;
       this.nbrcurrfiles = nbrcurrfiles;
       this.priority = priority;
       this.btiddesc = btiddesc;
       this.flgactive = flgactive;
       this.datcreated = datcreated;
       this.emailusage = emailusage;
       this.authlimit = authlimit;
       this.benevalidate = benevalidate;
       this.clientcode = clientcode;
       this.confirmreq = confirmreq;
       this.chequenoexists = chequenoexists;
       this.s2srequired = s2srequired;
       this.s2spreauthorized = s2spreauthorized;
       this.s2sresponsereq = s2sresponsereq;
       this.issignatoryrequiredincashin = issignatoryrequiredincashin;
       this.s2surl = s2surl;
       this.s2srevflag = s2srevflag;
       this.specialtempid = specialtempid;
       this.idEntity = idEntity;
       this.udfdata = udfdata;
       this.datedeactivate = datedeactivate;
       this.userdeactivate = userdeactivate;
       this.btidlimit = btidlimit;
       this.s2smode = s2smode;
       this.flgemailadvicereq = flgemailadvicereq;
       this.isdefaultTemplate = isdefaultTemplate;
       this.btsteps = btsteps;
       this.btacctmaps = btacctmaps;
       this.bttechinfo = bttechinfo;
       this.btusermaps = btusermaps;
       this.btidcustentitymaps = btidcustentitymaps;
       this.btlimitauth = btlimitauth;
    }
   
     @Id 

    
    @Column(name="BTID", unique=true, nullable=false, length=40)
    public String getBtid() {
        return this.btid;
    }
    
    public void setBtid(String btid) {
        this.btid = btid;
    }

    
    @Column(name="CUSTGROUPID", length=20)
    public String getCustgroupid() {
        return this.custgroupid;
    }
    
    public void setCustgroupid(String custgroupid) {
        this.custgroupid = custgroupid;
    }

    
    @Column(name="FLGCUSTGROUP", length=1)
    public Character getFlgcustgroup() {
        return this.flgcustgroup;
    }
    
    public void setFlgcustgroup(Character flgcustgroup) {
        this.flgcustgroup = flgcustgroup;
    }

    
    @Column(name="FLGFINANCIAL", length=1)
    public Character getFlgfinancial() {
        return this.flgfinancial;
    }
    
    public void setFlgfinancial(Character flgfinancial) {
        this.flgfinancial = flgfinancial;
    }

    
    @Column(name="TYPEPAYMENT", precision=22, scale=0)
    public BigDecimal getTypepayment() {
        return this.typepayment;
    }
    
    public void setTypepayment(BigDecimal typepayment) {
        this.typepayment = typepayment;
    }

    
    @Column(name="TYPETRANSACTION", precision=22, scale=0)
    public BigDecimal getTypetransaction() {
        return this.typetransaction;
    }
    
    public void setTypetransaction(BigDecimal typetransaction) {
        this.typetransaction = typetransaction;
    }

    
    @Column(name="TYPEACCOUNT", precision=22, scale=0)
    public BigDecimal getTypeaccount() {
        return this.typeaccount;
    }
    
    public void setTypeaccount(BigDecimal typeaccount) {
        this.typeaccount = typeaccount;
    }

    
    @Column(name="FLGENCRDECR", length=1)
    public Character getFlgencrdecr() {
        return this.flgencrdecr;
    }
    
    public void setFlgencrdecr(Character flgencrdecr) {
        this.flgencrdecr = flgencrdecr;
    }

    
    @Column(name="FLGRESPONSEREQ", length=1)
    public Character getFlgresponsereq() {
        return this.flgresponsereq;
    }
    
    public void setFlgresponsereq(Character flgresponsereq) {
        this.flgresponsereq = flgresponsereq;
    }

    
    @Column(name="FLGCTRLFILEREQ", length=1)
    public Character getFlgctrlfilereq() {
        return this.flgctrlfilereq;
    }
    
    public void setFlgctrlfilereq(Character flgctrlfilereq) {
        this.flgctrlfilereq = flgctrlfilereq;
    }

    
    @Column(name="FLGADVICEREQ", length=1)
    public Character getFlgadvicereq() {
        return this.flgadvicereq;
    }
    
    public void setFlgadvicereq(Character flgadvicereq) {
        this.flgadvicereq = flgadvicereq;
    }

    
    @Column(name="TMPLTADVICE", length=1000)
    public String getTmpltadvice() {
        return this.tmpltadvice;
    }
    
    public void setTmpltadvice(String tmpltadvice) {
        this.tmpltadvice = tmpltadvice;
    }

    
    @Column(name="NBRCURRFILES", precision=22, scale=0)
    public BigDecimal getNbrcurrfiles() {
        return this.nbrcurrfiles;
    }
    
    public void setNbrcurrfiles(BigDecimal nbrcurrfiles) {
        this.nbrcurrfiles = nbrcurrfiles;
    }

    
    @Column(name="PRIORITY", precision=22, scale=0)
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    
    @Column(name="BTIDDESC")
    public String getBtiddesc() {
        return this.btiddesc;
    }
    
    public void setBtiddesc(String btiddesc) {
        this.btiddesc = btiddesc;
    }

    
    @Column(name="FLGACTIVE", length=1)
    public Character getFlgactive() {
        return this.flgactive;
    }
    
    public void setFlgactive(Character flgactive) {
        this.flgactive = flgactive;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="EMAILUSAGE", length=1)
    public Character getEmailusage() {
        return this.emailusage;
    }
    
    public void setEmailusage(Character emailusage) {
        this.emailusage = emailusage;
    }

    
    @Column(name="AUTHLIMIT", length=30)
    public String getAuthlimit() {
        return this.authlimit;
    }
    
    public void setAuthlimit(String authlimit) {
        this.authlimit = authlimit;
    }

    
    @Column(name="BENEVALIDATE", length=1)
    public Character getBenevalidate() {
        return this.benevalidate;
    }
    
    public void setBenevalidate(Character benevalidate) {
        this.benevalidate = benevalidate;
    }

    
    @Column(name="CLIENTCODE", length=20)
    public String getClientcode() {
        return this.clientcode;
    }
    
    public void setClientcode(String clientcode) {
        this.clientcode = clientcode;
    }

    
    @Column(name="CONFIRMREQ", length=1)
    public Character getConfirmreq() {
        return this.confirmreq;
    }
    
    public void setConfirmreq(Character confirmreq) {
        this.confirmreq = confirmreq;
    }

    
    @Column(name="CHEQUENOEXISTS", length=1)
    public Character getChequenoexists() {
        return this.chequenoexists;
    }
    
    public void setChequenoexists(Character chequenoexists) {
        this.chequenoexists = chequenoexists;
    }

    
    @Column(name="S2SREQUIRED", length=1)
    public Character getS2srequired() {
        return this.s2srequired;
    }
    
    public void setS2srequired(Character s2srequired) {
        this.s2srequired = s2srequired;
    }

    
    @Column(name="S2SPREAUTHORIZED", length=1)
    public Character getS2spreauthorized() {
        return this.s2spreauthorized;
    }
    
    public void setS2spreauthorized(Character s2spreauthorized) {
        this.s2spreauthorized = s2spreauthorized;
    }

    
    @Column(name="S2SRESPONSEREQ", length=1)
    public Character getS2sresponsereq() {
        return this.s2sresponsereq;
    }
    
    public void setS2sresponsereq(Character s2sresponsereq) {
        this.s2sresponsereq = s2sresponsereq;
    }

    
    @Column(name="ISSIGNATORYREQUIREDINCASHIN", length=1)
    public Character getIssignatoryrequiredincashin() {
        return this.issignatoryrequiredincashin;
    }
    
    public void setIssignatoryrequiredincashin(Character issignatoryrequiredincashin) {
        this.issignatoryrequiredincashin = issignatoryrequiredincashin;
    }

    
    @Column(name="S2SURL", length=250)
    public String getS2surl() {
        return this.s2surl;
    }
    
    public void setS2surl(String s2surl) {
        this.s2surl = s2surl;
    }

    
    @Column(name="S2SREVFLAG", length=1)
    public String getS2srevflag() {
        return this.s2srevflag;
    }
    
    public void setS2srevflag(String s2srevflag) {
        this.s2srevflag = s2srevflag;
    }

    
    @Column(name="SPECIALTEMPID", length=200)
    public String getSpecialtempid() {
        return this.specialtempid;
    }
    
    public void setSpecialtempid(String specialtempid) {
        this.specialtempid = specialtempid;
    }

    
    @Column(name="ID_ENTITY", length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="UDFDATA")
    public Blob getUdfdata() {
        return this.udfdata;
    }
    
    public void setUdfdata(Blob udfdata) {
        this.udfdata = udfdata;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEDEACTIVATE", length=7)
    public Date getDatedeactivate() {
        return this.datedeactivate;
    }
    
    public void setDatedeactivate(Date datedeactivate) {
        this.datedeactivate = datedeactivate;
    }

    
    @Column(name="USERDEACTIVATE", length=20)
    public String getUserdeactivate() {
        return this.userdeactivate;
    }
    
    public void setUserdeactivate(String userdeactivate) {
        this.userdeactivate = userdeactivate;
    }

    
    @Column(name="BTIDLIMIT", precision=13)
    public BigDecimal getBtidlimit() {
        return this.btidlimit;
    }
    
    public void setBtidlimit(BigDecimal btidlimit) {
        this.btidlimit = btidlimit;
    }

    
    @Column(name="S2SMODE", length=1)
    public String getS2smode() {
        return this.s2smode;
    }
    
    public void setS2smode(String s2smode) {
        this.s2smode = s2smode;
    }

    
    @Column(name="FLGEMAILADVICEREQ", length=1)
    public Character getFlgemailadvicereq() {
        return this.flgemailadvicereq;
    }
    
    public void setFlgemailadvicereq(Character flgemailadvicereq) {
        this.flgemailadvicereq = flgemailadvicereq;
    }

    
    @Column(name="ISDEFAULT_TEMPLATE", length=1)
    public Character getIsdefaultTemplate() {
        return this.isdefaultTemplate;
    }
    
    public void setIsdefaultTemplate(Character isdefaultTemplate) {
        this.isdefaultTemplate = isdefaultTemplate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="btcustreg")
    public Set<Btstep> getBtsteps() {
        return this.btsteps;
    }
    
    public void setBtsteps(Set<Btstep> btsteps) {
        this.btsteps = btsteps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="btcustreg")
    public Set<Btacctmap> getBtacctmaps() {
        return this.btacctmaps;
    }
    
    public void setBtacctmaps(Set<Btacctmap> btacctmaps) {
        this.btacctmaps = btacctmaps;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="btcustreg")
    public Bttechinfo getBttechinfo() {
        return this.bttechinfo;
    }
    
    public void setBttechinfo(Bttechinfo bttechinfo) {
        this.bttechinfo = bttechinfo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="btcustreg")
    public Set<Btusermap> getBtusermaps() {
        return this.btusermaps;
    }
    
    public void setBtusermaps(Set<Btusermap> btusermaps) {
        this.btusermaps = btusermaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="btcustreg")
    public Set<Btidcustentitymap> getBtidcustentitymaps() {
        return this.btidcustentitymaps;
    }
    
    public void setBtidcustentitymaps(Set<Btidcustentitymap> btidcustentitymaps) {
        this.btidcustentitymaps = btidcustentitymaps;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="btcustreg")
    public Btlimitauth getBtlimitauth() {
        return this.btlimitauth;
    }
    
    public void setBtlimitauth(Btlimitauth btlimitauth) {
        this.btlimitauth = btlimitauth;
    }




}


