package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Btfinmapping generated by hbm2java
 */
@Entity
@Table(name="BTFINMAPPING"
    ,schema="FCDBADMIN_RK"
)
public class Btfinmapping  implements java.io.Serializable {


     private BtfinmappingId id;
     private String fieldname;
     private String isudf;

    public Btfinmapping() {
    }

	
    public Btfinmapping(BtfinmappingId id) {
        this.id = id;
    }
    public Btfinmapping(BtfinmappingId id, String fieldname, String isudf) {
       this.id = id;
       this.fieldname = fieldname;
       this.isudf = isudf;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false) ), 
        @AttributeOverride(name="finfield", column=@Column(name="FINFIELD", nullable=false, length=50) ) } )
    public BtfinmappingId getId() {
        return this.id;
    }
    
    public void setId(BtfinmappingId id) {
        this.id = id;
    }

    
    @Column(name="FIELDNAME", length=50)
    public String getFieldname() {
        return this.fieldname;
    }
    
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname;
    }

    
    @Column(name="ISUDF", length=1)
    public String getIsudf() {
        return this.isudf;
    }
    
    public void setIsudf(String isudf) {
        this.isudf = isudf;
    }




}


