package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Btfiledefinition generated by hbm2java
 */
@Entity
@Table(name="BTFILEDEFINITION"
    ,schema="FCDBADMIN_RK"
)
public class Btfiledefinition  implements java.io.Serializable {


     private BtfiledefinitionId id;
     private Character isbasetemplate;
     private String occfield;
     private Short minocc;
     private Short maxocc;
     private Character keepprefix;
     private Character keeppostfix;
     private Short seqno;
     private String parentid;
     private Boolean childcount;
     private String txnIdentifier;

    public Btfiledefinition() {
    }

	
    public Btfiledefinition(BtfiledefinitionId id) {
        this.id = id;
    }
    public Btfiledefinition(BtfiledefinitionId id, Character isbasetemplate, String occfield, Short minocc, Short maxocc, Character keepprefix, Character keeppostfix, Short seqno, String parentid, Boolean childcount, String txnIdentifier) {
       this.id = id;
       this.isbasetemplate = isbasetemplate;
       this.occfield = occfield;
       this.minocc = minocc;
       this.maxocc = maxocc;
       this.keepprefix = keepprefix;
       this.keeppostfix = keeppostfix;
       this.seqno = seqno;
       this.parentid = parentid;
       this.childcount = childcount;
       this.txnIdentifier = txnIdentifier;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="typetemplate", column=@Column(name="TYPETEMPLATE", nullable=false, length=1) ), 
        @AttributeOverride(name="templateid", column=@Column(name="TEMPLATEID", nullable=false, length=40) ) } )
    public BtfiledefinitionId getId() {
        return this.id;
    }
    
    public void setId(BtfiledefinitionId id) {
        this.id = id;
    }

    
    @Column(name="ISBASETEMPLATE", length=1)
    public Character getIsbasetemplate() {
        return this.isbasetemplate;
    }
    
    public void setIsbasetemplate(Character isbasetemplate) {
        this.isbasetemplate = isbasetemplate;
    }

    
    @Column(name="OCCFIELD", length=20)
    public String getOccfield() {
        return this.occfield;
    }
    
    public void setOccfield(String occfield) {
        this.occfield = occfield;
    }

    
    @Column(name="MINOCC", precision=3, scale=0)
    public Short getMinocc() {
        return this.minocc;
    }
    
    public void setMinocc(Short minocc) {
        this.minocc = minocc;
    }

    
    @Column(name="MAXOCC", precision=3, scale=0)
    public Short getMaxocc() {
        return this.maxocc;
    }
    
    public void setMaxocc(Short maxocc) {
        this.maxocc = maxocc;
    }

    
    @Column(name="KEEPPREFIX", length=1)
    public Character getKeepprefix() {
        return this.keepprefix;
    }
    
    public void setKeepprefix(Character keepprefix) {
        this.keepprefix = keepprefix;
    }

    
    @Column(name="KEEPPOSTFIX", length=1)
    public Character getKeeppostfix() {
        return this.keeppostfix;
    }
    
    public void setKeeppostfix(Character keeppostfix) {
        this.keeppostfix = keeppostfix;
    }

    
    @Column(name="SEQNO", precision=3, scale=0)
    public Short getSeqno() {
        return this.seqno;
    }
    
    public void setSeqno(Short seqno) {
        this.seqno = seqno;
    }

    
    @Column(name="PARENTID", length=40)
    public String getParentid() {
        return this.parentid;
    }
    
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    
    @Column(name="CHILDCOUNT", precision=1, scale=0)
    public Boolean getChildcount() {
        return this.childcount;
    }
    
    public void setChildcount(Boolean childcount) {
        this.childcount = childcount;
    }

    
    @Column(name="TXN_IDENTIFIER")
    public String getTxnIdentifier() {
        return this.txnIdentifier;
    }
    
    public void setTxnIdentifier(String txnIdentifier) {
        this.txnIdentifier = txnIdentifier;
    }




}


