package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Btstep generated by hbm2java
 */
@Entity
@Table(name="BTSTEP"
    ,schema="FCDBADMIN_RK"
)
public class Btstep  implements java.io.Serializable {


     private BtstepId id;
     private Btcustreg btcustreg;
     private Btstepsetup btstepsetup;
     private Character skip;

    public Btstep() {
    }

	
    public Btstep(BtstepId id, Btcustreg btcustreg, Btstepsetup btstepsetup) {
        this.id = id;
        this.btcustreg = btcustreg;
        this.btstepsetup = btstepsetup;
    }
    public Btstep(BtstepId id, Btcustreg btcustreg, Btstepsetup btstepsetup, Character skip) {
       this.id = id;
       this.btcustreg = btcustreg;
       this.btstepsetup = btstepsetup;
       this.skip = skip;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="step", column=@Column(name="STEP", nullable=false, length=20) ) } )
    public BtstepId getId() {
        return this.id;
    }
    
    public void setId(BtstepId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BTID", nullable=false, insertable=false, updatable=false)
    public Btcustreg getBtcustreg() {
        return this.btcustreg;
    }
    
    public void setBtcustreg(Btcustreg btcustreg) {
        this.btcustreg = btcustreg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STEP", nullable=false, insertable=false, updatable=false)
    public Btstepsetup getBtstepsetup() {
        return this.btstepsetup;
    }
    
    public void setBtstepsetup(Btstepsetup btstepsetup) {
        this.btstepsetup = btstepsetup;
    }

    
    @Column(name="SKIP", length=1)
    public Character getSkip() {
        return this.skip;
    }
    
    public void setSkip(Character skip) {
        this.skip = skip;
    }




}


