package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clonequeue generated by hbm2java
 */
@Entity
@Table(name="CLONEQUEUE"
    ,schema="FCDBADMIN_RK"
)
public class Clonequeue  implements java.io.Serializable {


     private String msgidentity;
     private Date msgtimestamp;
     private Blob msgdata;

    public Clonequeue() {
    }

	
    public Clonequeue(String msgidentity) {
        this.msgidentity = msgidentity;
    }
    public Clonequeue(String msgidentity, Date msgtimestamp, Blob msgdata) {
       this.msgidentity = msgidentity;
       this.msgtimestamp = msgtimestamp;
       this.msgdata = msgdata;
    }
   
     @Id 

    
    @Column(name="MSGIDENTITY", unique=true, nullable=false, length=55)
    public String getMsgidentity() {
        return this.msgidentity;
    }
    
    public void setMsgidentity(String msgidentity) {
        this.msgidentity = msgidentity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MSGTIMESTAMP", length=7)
    public Date getMsgtimestamp() {
        return this.msgtimestamp;
    }
    
    public void setMsgtimestamp(Date msgtimestamp) {
        this.msgtimestamp = msgtimestamp;
    }

    
    @Column(name="MSGDATA")
    public Blob getMsgdata() {
        return this.msgdata;
    }
    
    public void setMsgdata(Blob msgdata) {
        this.msgdata = msgdata;
    }




}


