package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactHistory generated by hbm2java
 */
@Entity
@Table(name="CONTACT_HISTORY"
    ,schema="FCDBADMIN_RK"
)
public class ContactHistory  implements java.io.Serializable {


     private BigDecimal idrecord;
     private Date dathistory;
     private String codcontact;
     private String flgdirection;
     private String codchannel;
     private String codpurpose;
     private String codsystem;
     private String codproduct;
     private String proddescription;
     private String additionalNotes;
     private String iduser;
     private String isautogen;
     private String idImagerecord;
     private String idcustomer;

    public ContactHistory() {
    }

	
    public ContactHistory(BigDecimal idrecord) {
        this.idrecord = idrecord;
    }
    public ContactHistory(BigDecimal idrecord, Date dathistory, String codcontact, String flgdirection, String codchannel, String codpurpose, String codsystem, String codproduct, String proddescription, String additionalNotes, String iduser, String isautogen, String idImagerecord, String idcustomer) {
       this.idrecord = idrecord;
       this.dathistory = dathistory;
       this.codcontact = codcontact;
       this.flgdirection = flgdirection;
       this.codchannel = codchannel;
       this.codpurpose = codpurpose;
       this.codsystem = codsystem;
       this.codproduct = codproduct;
       this.proddescription = proddescription;
       this.additionalNotes = additionalNotes;
       this.iduser = iduser;
       this.isautogen = isautogen;
       this.idImagerecord = idImagerecord;
       this.idcustomer = idcustomer;
    }
   
     @Id 

    
    @Column(name="IDRECORD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdrecord() {
        return this.idrecord;
    }
    
    public void setIdrecord(BigDecimal idrecord) {
        this.idrecord = idrecord;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATHISTORY", length=7)
    public Date getDathistory() {
        return this.dathistory;
    }
    
    public void setDathistory(Date dathistory) {
        this.dathistory = dathistory;
    }

    
    @Column(name="CODCONTACT", length=50)
    public String getCodcontact() {
        return this.codcontact;
    }
    
    public void setCodcontact(String codcontact) {
        this.codcontact = codcontact;
    }

    
    @Column(name="FLGDIRECTION", length=1)
    public String getFlgdirection() {
        return this.flgdirection;
    }
    
    public void setFlgdirection(String flgdirection) {
        this.flgdirection = flgdirection;
    }

    
    @Column(name="CODCHANNEL", length=5)
    public String getCodchannel() {
        return this.codchannel;
    }
    
    public void setCodchannel(String codchannel) {
        this.codchannel = codchannel;
    }

    
    @Column(name="CODPURPOSE", length=5)
    public String getCodpurpose() {
        return this.codpurpose;
    }
    
    public void setCodpurpose(String codpurpose) {
        this.codpurpose = codpurpose;
    }

    
    @Column(name="CODSYSTEM", length=5)
    public String getCodsystem() {
        return this.codsystem;
    }
    
    public void setCodsystem(String codsystem) {
        this.codsystem = codsystem;
    }

    
    @Column(name="CODPRODUCT", length=2)
    public String getCodproduct() {
        return this.codproduct;
    }
    
    public void setCodproduct(String codproduct) {
        this.codproduct = codproduct;
    }

    
    @Column(name="PRODDESCRIPTION", length=2000)
    public String getProddescription() {
        return this.proddescription;
    }
    
    public void setProddescription(String proddescription) {
        this.proddescription = proddescription;
    }

    
    @Column(name="ADDITIONAL_NOTES", length=2000)
    public String getAdditionalNotes() {
        return this.additionalNotes;
    }
    
    public void setAdditionalNotes(String additionalNotes) {
        this.additionalNotes = additionalNotes;
    }

    
    @Column(name="IDUSER", length=100)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="ISAUTOGEN", length=1)
    public String getIsautogen() {
        return this.isautogen;
    }
    
    public void setIsautogen(String isautogen) {
        this.isautogen = isautogen;
    }

    
    @Column(name="ID_IMAGERECORD", length=50)
    public String getIdImagerecord() {
        return this.idImagerecord;
    }
    
    public void setIdImagerecord(String idImagerecord) {
        this.idImagerecord = idImagerecord;
    }

    
    @Column(name="IDCUSTOMER", length=30)
    public String getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(String idcustomer) {
        this.idcustomer = idcustomer;
    }




}


