package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custgroupmap generated by hbm2java
 */
@Entity
@Table(name="CUSTGROUPMAP"
    ,schema="FCDBADMIN_RK"
)
public class Custgroupmap  implements java.io.Serializable {


     private CustgroupmapId id;
     private Date datassigned;
     private String makerid;
     private String checkerid;
     private Date dtime;
     private BigDecimal slno;
     private String idEntity;

    public Custgroupmap() {
    }

	
    public Custgroupmap(CustgroupmapId id) {
        this.id = id;
    }
    public Custgroupmap(CustgroupmapId id, Date datassigned, String makerid, String checkerid, Date dtime, BigDecimal slno, String idEntity) {
       this.id = id;
       this.datassigned = datassigned;
       this.makerid = makerid;
       this.checkerid = checkerid;
       this.dtime = dtime;
       this.slno = slno;
       this.idEntity = idEntity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idgroup", column=@Column(name="IDGROUP", nullable=false, length=20) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=30) ) } )
    public CustgroupmapId getId() {
        return this.id;
    }
    
    public void setId(CustgroupmapId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATASSIGNED", length=7)
    public Date getDatassigned() {
        return this.datassigned;
    }
    
    public void setDatassigned(Date datassigned) {
        this.datassigned = datassigned;
    }

    
    @Column(name="MAKERID", length=20)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    
    @Column(name="CHECKERID", length=20)
    public String getCheckerid() {
        return this.checkerid;
    }
    
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }




}


