package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Custommsgattchmap generated by hbm2java
 */
@Entity
@Table(name="CUSTOMMSGATTCHMAP"
    ,schema="FCDBADMIN_RK"
)
public class Custommsgattchmap  implements java.io.Serializable {


     private CustommsgattchmapId id;
     private Custommessages custommessages;
     private String filename;
     private Blob filecontent;
     private String contenttype;

    public Custommsgattchmap() {
    }

	
    public Custommsgattchmap(CustommsgattchmapId id, Custommessages custommessages) {
        this.id = id;
        this.custommessages = custommessages;
    }
    public Custommsgattchmap(CustommsgattchmapId id, Custommessages custommessages, String filename, Blob filecontent, String contenttype) {
       this.id = id;
       this.custommessages = custommessages;
       this.filename = filename;
       this.filecontent = filecontent;
       this.contenttype = contenttype;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idmessage", column=@Column(name="IDMESSAGE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="filerefno", column=@Column(name="FILEREFNO", nullable=false, length=35) ) } )
    public CustommsgattchmapId getId() {
        return this.id;
    }
    
    public void setId(CustommsgattchmapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMESSAGE", nullable=false, insertable=false, updatable=false)
    public Custommessages getCustommessages() {
        return this.custommessages;
    }
    
    public void setCustommessages(Custommessages custommessages) {
        this.custommessages = custommessages;
    }

    
    @Column(name="FILENAME")
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="FILECONTENT")
    public Blob getFilecontent() {
        return this.filecontent;
    }
    
    public void setFilecontent(Blob filecontent) {
        this.filecontent = filecontent;
    }

    
    @Column(name="CONTENTTYPE", length=100)
    public String getContenttype() {
        return this.contenttype;
    }
    
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype;
    }




}


