package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataDictionaryTypes generated by hbm2java
 */
@Entity
@Table(name="DATA_DICTIONARY_TYPES"
    ,schema="FCDBADMIN_RK"
)
public class DataDictionaryTypes  implements java.io.Serializable {


     private String datatype;
     private String datatypeDesc;
     private String datatypeValidator;
     private Byte poolsize;
     private String comments;
     private String baseType;
     private Set<DataDictionary> dataDictionaries = new HashSet<DataDictionary>(0);

    public DataDictionaryTypes() {
    }

	
    public DataDictionaryTypes(String datatype) {
        this.datatype = datatype;
    }
    public DataDictionaryTypes(String datatype, String datatypeDesc, String datatypeValidator, Byte poolsize, String comments, String baseType, Set<DataDictionary> dataDictionaries) {
       this.datatype = datatype;
       this.datatypeDesc = datatypeDesc;
       this.datatypeValidator = datatypeValidator;
       this.poolsize = poolsize;
       this.comments = comments;
       this.baseType = baseType;
       this.dataDictionaries = dataDictionaries;
    }
   
     @Id 

    
    @Column(name="DATATYPE", unique=true, nullable=false, length=5)
    public String getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }

    
    @Column(name="DATATYPE_DESC")
    public String getDatatypeDesc() {
        return this.datatypeDesc;
    }
    
    public void setDatatypeDesc(String datatypeDesc) {
        this.datatypeDesc = datatypeDesc;
    }

    
    @Column(name="DATATYPE_VALIDATOR")
    public String getDatatypeValidator() {
        return this.datatypeValidator;
    }
    
    public void setDatatypeValidator(String datatypeValidator) {
        this.datatypeValidator = datatypeValidator;
    }

    
    @Column(name="POOLSIZE", precision=2, scale=0)
    public Byte getPoolsize() {
        return this.poolsize;
    }
    
    public void setPoolsize(Byte poolsize) {
        this.poolsize = poolsize;
    }

    
    @Column(name="COMMENTS")
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="BASE_TYPE", length=10)
    public String getBaseType() {
        return this.baseType;
    }
    
    public void setBaseType(String baseType) {
        this.baseType = baseType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataDictionaryTypes")
    public Set<DataDictionary> getDataDictionaries() {
        return this.dataDictionaries;
    }
    
    public void setDataDictionaries(Set<DataDictionary> dataDictionaries) {
        this.dataDictionaries = dataDictionaries;
    }




}


