package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTPrelogin generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_PRELOGIN"
    ,schema="FCDBADMIN_RK"
)
public class FcatTPrelogin  implements java.io.Serializable {


     private String idreference;
     private Date datcreation;
     private Date datexpiry;
     private String iduser;
     private String idchanneluser;
     private String idEntity;
     private Blob msglogin;
     private String nammodule;

    public FcatTPrelogin() {
    }

	
    public FcatTPrelogin(String idreference) {
        this.idreference = idreference;
    }
    public FcatTPrelogin(String idreference, Date datcreation, Date datexpiry, String iduser, String idchanneluser, String idEntity, Blob msglogin, String nammodule) {
       this.idreference = idreference;
       this.datcreation = datcreation;
       this.datexpiry = datexpiry;
       this.iduser = iduser;
       this.idchanneluser = idchanneluser;
       this.idEntity = idEntity;
       this.msglogin = msglogin;
       this.nammodule = nammodule;
    }
   
     @Id 

    
    @Column(name="IDREFERENCE", unique=true, nullable=false)
    public String getIdreference() {
        return this.idreference;
    }
    
    public void setIdreference(String idreference) {
        this.idreference = idreference;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATION", length=7)
    public Date getDatcreation() {
        return this.datcreation;
    }
    
    public void setDatcreation(Date datcreation) {
        this.datcreation = datcreation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEXPIRY", length=7)
    public Date getDatexpiry() {
        return this.datexpiry;
    }
    
    public void setDatexpiry(Date datexpiry) {
        this.datexpiry = datexpiry;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="IDCHANNELUSER", length=20)
    public String getIdchanneluser() {
        return this.idchanneluser;
    }
    
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="MSGLOGIN")
    public Blob getMsglogin() {
        return this.msglogin;
    }
    
    public void setMsglogin(Blob msglogin) {
        this.msglogin = msglogin;
    }

    
    @Column(name="NAMMODULE", length=3)
    public String getNammodule() {
        return this.nammodule;
    }
    
    public void setNammodule(String nammodule) {
        this.nammodule = nammodule;
    }




}


