package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcdbComPmtIn generated by hbm2java
 */
@Entity
@Table(name="FCDB_COM_PMT_IN"
    ,schema="FCDBADMIN_RK"
)
public class FcdbComPmtIn  implements java.io.Serializable {


     private FcdbComPmtInId id;
     private String sourceCode;
     private String queue;
     private BigDecimal amount;
     private Date valueDate;
     private String ccy;
     private BigDecimal status;
     private String errReason;
     private String contractRefNo;
     private String custAcNo;
     private String custCcy;
     private String cptyAcNo;
     private String byOrderOf1;
     private String byOrderOf2;
     private String byOrderOf3;
     private String byOrderOf4;
     private String byOrderOf5;
     private String accWithInstn1;
     private String benefInstitution1;
     private String benefInstitution2;
     private String benefInstitution3;
     private String benefInstitution4;
     private String paymentDetails1;
     private String paymentDetails2;
     private String paymentDetails3;
     private String paymentDetails4;
     private String relatedRefNo;
     private Short modNo;
     private String makerId;
     private Date makerDtStamp;
     private String checkerId;
     private Date checkerDtStamp;
     private String recordStat;
     private String authStat;
     private String onceAuth;
     private String msgType;
     private String branchCode;
     private Short versionNo;
     private Short latestVersionNo;
     private String custAcBrn;
     private String udf49;
     private String udf50;
     private String endToEndId;
     private String serviceLevelCode;
     private String chargeBearer;
     private Date instructionDate;
     private String custId;
     private String custIdType;
     private String custIdValue;
     private String custIdIssuer;
     private String custOtherIdType;
     private String custBirthCity;
     private String custBirthCountry;
     private String custBankcode;
     private String cptyId;
     private String cptyIdType;
     private String cptyIdValue;
     private String cptyIdIssuer;
     private String cptyOtherIdType;
     private String cptyBirthCity;
     private String cptyBirthCountry;
     private Date settlementDate;
     private String settlementMethod;
     private String clgSystemId;
     private String ultimateDebtor;
     private String ultimateCreditor;
     private String custCtry;
     private String benefCtry;
     private String initpartyName;
     private String initpartyType;
     private String initpartyIdtype;
     private String initpartyIdvalue;
     private String initpartyOtheridType;
     private String initpartyIdissuer;
     private String initpartyDobcity;
     private String initpartyDobctry;
     private String ddSeqType;
     private String mandateId;
     private Date mandSignDate;
     private String creditorSchId;
     private String mandAmendInd;
     private String mandAmendType;
     private String orgMandateId;
     private String orgCreditorSchId;
     private String orgCreditorName;
     private String orgDebtorAcc;
     private String orgDebtorBank;
     private String localInstrumentType;
     private String localInstrumentValue;
     private String categoryPurpose;
     private String purposeType;
     private String purposeValue;
     private String elecSig;
     private String creditorSchIdType;
     private String orgCreditorSchIdType;
     private String ultDebtorAdd1;
     private String ultDebtorAdd2;
     private String ultDebtorId;
     private String ultDebtorIdType;
     private String ultDebtorIdValue;
     private String ultDebtorIdIssuer;
     private String ultDebtorOtherIdType;
     private String ultDebtorBirthCity;
     private String ultDebtorBirthCountry;
     private String ultCreditorAdd1;
     private String ultCreditorAdd2;
     private String ultCreditorId;
     private String ultCreditorIdType;
     private String ultCreditorIdValue;
     private String ultCreditorIdIssuer;
     private String ultCreditorOtherIdType;
     private String ultCreditorBirthCity;
     private String ultCreditorBirthCountry;
     private String idEntity;
     private Date datupdated;
     private String timerstatus;
     private Date timerdatetime;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private String token6;
     private String token7;
     private String token8;
     private String token9;
     private String rejOriginatorName;
     private String rejectCode;
     private String rejectDetails;

    public FcdbComPmtIn() {
    }

	
    public FcdbComPmtIn(FcdbComPmtInId id) {
        this.id = id;
    }
    public FcdbComPmtIn(FcdbComPmtInId id, String sourceCode, String queue, BigDecimal amount, Date valueDate, String ccy, BigDecimal status, String errReason, String contractRefNo, String custAcNo, String custCcy, String cptyAcNo, String byOrderOf1, String byOrderOf2, String byOrderOf3, String byOrderOf4, String byOrderOf5, String accWithInstn1, String benefInstitution1, String benefInstitution2, String benefInstitution3, String benefInstitution4, String paymentDetails1, String paymentDetails2, String paymentDetails3, String paymentDetails4, String relatedRefNo, Short modNo, String makerId, Date makerDtStamp, String checkerId, Date checkerDtStamp, String recordStat, String authStat, String onceAuth, String msgType, String branchCode, Short versionNo, Short latestVersionNo, String custAcBrn, String udf49, String udf50, String endToEndId, String serviceLevelCode, String chargeBearer, Date instructionDate, String custId, String custIdType, String custIdValue, String custIdIssuer, String custOtherIdType, String custBirthCity, String custBirthCountry, String custBankcode, String cptyId, String cptyIdType, String cptyIdValue, String cptyIdIssuer, String cptyOtherIdType, String cptyBirthCity, String cptyBirthCountry, Date settlementDate, String settlementMethod, String clgSystemId, String ultimateDebtor, String ultimateCreditor, String custCtry, String benefCtry, String initpartyName, String initpartyType, String initpartyIdtype, String initpartyIdvalue, String initpartyOtheridType, String initpartyIdissuer, String initpartyDobcity, String initpartyDobctry, String ddSeqType, String mandateId, Date mandSignDate, String creditorSchId, String mandAmendInd, String mandAmendType, String orgMandateId, String orgCreditorSchId, String orgCreditorName, String orgDebtorAcc, String orgDebtorBank, String localInstrumentType, String localInstrumentValue, String categoryPurpose, String purposeType, String purposeValue, String elecSig, String creditorSchIdType, String orgCreditorSchIdType, String ultDebtorAdd1, String ultDebtorAdd2, String ultDebtorId, String ultDebtorIdType, String ultDebtorIdValue, String ultDebtorIdIssuer, String ultDebtorOtherIdType, String ultDebtorBirthCity, String ultDebtorBirthCountry, String ultCreditorAdd1, String ultCreditorAdd2, String ultCreditorId, String ultCreditorIdType, String ultCreditorIdValue, String ultCreditorIdIssuer, String ultCreditorOtherIdType, String ultCreditorBirthCity, String ultCreditorBirthCountry, String idEntity, Date datupdated, String timerstatus, Date timerdatetime, String token1, String token2, String token3, String token4, String token5, String token6, String token7, String token8, String token9, String rejOriginatorName, String rejectCode, String rejectDetails) {
       this.id = id;
       this.sourceCode = sourceCode;
       this.queue = queue;
       this.amount = amount;
       this.valueDate = valueDate;
       this.ccy = ccy;
       this.status = status;
       this.errReason = errReason;
       this.contractRefNo = contractRefNo;
       this.custAcNo = custAcNo;
       this.custCcy = custCcy;
       this.cptyAcNo = cptyAcNo;
       this.byOrderOf1 = byOrderOf1;
       this.byOrderOf2 = byOrderOf2;
       this.byOrderOf3 = byOrderOf3;
       this.byOrderOf4 = byOrderOf4;
       this.byOrderOf5 = byOrderOf5;
       this.accWithInstn1 = accWithInstn1;
       this.benefInstitution1 = benefInstitution1;
       this.benefInstitution2 = benefInstitution2;
       this.benefInstitution3 = benefInstitution3;
       this.benefInstitution4 = benefInstitution4;
       this.paymentDetails1 = paymentDetails1;
       this.paymentDetails2 = paymentDetails2;
       this.paymentDetails3 = paymentDetails3;
       this.paymentDetails4 = paymentDetails4;
       this.relatedRefNo = relatedRefNo;
       this.modNo = modNo;
       this.makerId = makerId;
       this.makerDtStamp = makerDtStamp;
       this.checkerId = checkerId;
       this.checkerDtStamp = checkerDtStamp;
       this.recordStat = recordStat;
       this.authStat = authStat;
       this.onceAuth = onceAuth;
       this.msgType = msgType;
       this.branchCode = branchCode;
       this.versionNo = versionNo;
       this.latestVersionNo = latestVersionNo;
       this.custAcBrn = custAcBrn;
       this.udf49 = udf49;
       this.udf50 = udf50;
       this.endToEndId = endToEndId;
       this.serviceLevelCode = serviceLevelCode;
       this.chargeBearer = chargeBearer;
       this.instructionDate = instructionDate;
       this.custId = custId;
       this.custIdType = custIdType;
       this.custIdValue = custIdValue;
       this.custIdIssuer = custIdIssuer;
       this.custOtherIdType = custOtherIdType;
       this.custBirthCity = custBirthCity;
       this.custBirthCountry = custBirthCountry;
       this.custBankcode = custBankcode;
       this.cptyId = cptyId;
       this.cptyIdType = cptyIdType;
       this.cptyIdValue = cptyIdValue;
       this.cptyIdIssuer = cptyIdIssuer;
       this.cptyOtherIdType = cptyOtherIdType;
       this.cptyBirthCity = cptyBirthCity;
       this.cptyBirthCountry = cptyBirthCountry;
       this.settlementDate = settlementDate;
       this.settlementMethod = settlementMethod;
       this.clgSystemId = clgSystemId;
       this.ultimateDebtor = ultimateDebtor;
       this.ultimateCreditor = ultimateCreditor;
       this.custCtry = custCtry;
       this.benefCtry = benefCtry;
       this.initpartyName = initpartyName;
       this.initpartyType = initpartyType;
       this.initpartyIdtype = initpartyIdtype;
       this.initpartyIdvalue = initpartyIdvalue;
       this.initpartyOtheridType = initpartyOtheridType;
       this.initpartyIdissuer = initpartyIdissuer;
       this.initpartyDobcity = initpartyDobcity;
       this.initpartyDobctry = initpartyDobctry;
       this.ddSeqType = ddSeqType;
       this.mandateId = mandateId;
       this.mandSignDate = mandSignDate;
       this.creditorSchId = creditorSchId;
       this.mandAmendInd = mandAmendInd;
       this.mandAmendType = mandAmendType;
       this.orgMandateId = orgMandateId;
       this.orgCreditorSchId = orgCreditorSchId;
       this.orgCreditorName = orgCreditorName;
       this.orgDebtorAcc = orgDebtorAcc;
       this.orgDebtorBank = orgDebtorBank;
       this.localInstrumentType = localInstrumentType;
       this.localInstrumentValue = localInstrumentValue;
       this.categoryPurpose = categoryPurpose;
       this.purposeType = purposeType;
       this.purposeValue = purposeValue;
       this.elecSig = elecSig;
       this.creditorSchIdType = creditorSchIdType;
       this.orgCreditorSchIdType = orgCreditorSchIdType;
       this.ultDebtorAdd1 = ultDebtorAdd1;
       this.ultDebtorAdd2 = ultDebtorAdd2;
       this.ultDebtorId = ultDebtorId;
       this.ultDebtorIdType = ultDebtorIdType;
       this.ultDebtorIdValue = ultDebtorIdValue;
       this.ultDebtorIdIssuer = ultDebtorIdIssuer;
       this.ultDebtorOtherIdType = ultDebtorOtherIdType;
       this.ultDebtorBirthCity = ultDebtorBirthCity;
       this.ultDebtorBirthCountry = ultDebtorBirthCountry;
       this.ultCreditorAdd1 = ultCreditorAdd1;
       this.ultCreditorAdd2 = ultCreditorAdd2;
       this.ultCreditorId = ultCreditorId;
       this.ultCreditorIdType = ultCreditorIdType;
       this.ultCreditorIdValue = ultCreditorIdValue;
       this.ultCreditorIdIssuer = ultCreditorIdIssuer;
       this.ultCreditorOtherIdType = ultCreditorOtherIdType;
       this.ultCreditorBirthCity = ultCreditorBirthCity;
       this.ultCreditorBirthCountry = ultCreditorBirthCountry;
       this.idEntity = idEntity;
       this.datupdated = datupdated;
       this.timerstatus = timerstatus;
       this.timerdatetime = timerdatetime;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.token6 = token6;
       this.token7 = token7;
       this.token8 = token8;
       this.token9 = token9;
       this.rejOriginatorName = rejOriginatorName;
       this.rejectCode = rejectCode;
       this.rejectDetails = rejectDetails;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="extRefNo", column=@Column(name="EXT_REF_NO", nullable=false, length=105) ), 
        @AttributeOverride(name="fileRefNo", column=@Column(name="FILE_REF_NO", nullable=false, length=35) ) } )
    public FcdbComPmtInId getId() {
        return this.id;
    }
    
    public void setId(FcdbComPmtInId id) {
        this.id = id;
    }

    
    @Column(name="SOURCE_CODE", length=15)
    public String getSourceCode() {
        return this.sourceCode;
    }
    
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    
    @Column(name="QUEUE", length=12)
    public String getQueue() {
        return this.queue;
    }
    
    public void setQueue(String queue) {
        this.queue = queue;
    }

    
    @Column(name="AMOUNT", precision=22, scale=3)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALUE_DATE", length=7)
    public Date getValueDate() {
        return this.valueDate;
    }
    
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }

    
    @Column(name="CCY", length=3)
    public String getCcy() {
        return this.ccy;
    }
    
    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    
    @Column(name="STATUS", precision=22, scale=0)
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    
    @Column(name="ERR_REASON", length=11)
    public String getErrReason() {
        return this.errReason;
    }
    
    public void setErrReason(String errReason) {
        this.errReason = errReason;
    }

    
    @Column(name="CONTRACT_REF_NO", length=16)
    public String getContractRefNo() {
        return this.contractRefNo;
    }
    
    public void setContractRefNo(String contractRefNo) {
        this.contractRefNo = contractRefNo;
    }

    
    @Column(name="CUST_AC_NO", length=105)
    public String getCustAcNo() {
        return this.custAcNo;
    }
    
    public void setCustAcNo(String custAcNo) {
        this.custAcNo = custAcNo;
    }

    
    @Column(name="CUST_CCY", length=3)
    public String getCustCcy() {
        return this.custCcy;
    }
    
    public void setCustCcy(String custCcy) {
        this.custCcy = custCcy;
    }

    
    @Column(name="CPTY_AC_NO", length=35)
    public String getCptyAcNo() {
        return this.cptyAcNo;
    }
    
    public void setCptyAcNo(String cptyAcNo) {
        this.cptyAcNo = cptyAcNo;
    }

    
    @Column(name="BY_ORDER_OF1", length=210)
    public String getByOrderOf1() {
        return this.byOrderOf1;
    }
    
    public void setByOrderOf1(String byOrderOf1) {
        this.byOrderOf1 = byOrderOf1;
    }

    
    @Column(name="BY_ORDER_OF2", length=210)
    public String getByOrderOf2() {
        return this.byOrderOf2;
    }
    
    public void setByOrderOf2(String byOrderOf2) {
        this.byOrderOf2 = byOrderOf2;
    }

    
    @Column(name="BY_ORDER_OF3", length=210)
    public String getByOrderOf3() {
        return this.byOrderOf3;
    }
    
    public void setByOrderOf3(String byOrderOf3) {
        this.byOrderOf3 = byOrderOf3;
    }

    
    @Column(name="BY_ORDER_OF4", length=210)
    public String getByOrderOf4() {
        return this.byOrderOf4;
    }
    
    public void setByOrderOf4(String byOrderOf4) {
        this.byOrderOf4 = byOrderOf4;
    }

    
    @Column(name="BY_ORDER_OF5", length=210)
    public String getByOrderOf5() {
        return this.byOrderOf5;
    }
    
    public void setByOrderOf5(String byOrderOf5) {
        this.byOrderOf5 = byOrderOf5;
    }

    
    @Column(name="ACC_WITH_INSTN1", length=105)
    public String getAccWithInstn1() {
        return this.accWithInstn1;
    }
    
    public void setAccWithInstn1(String accWithInstn1) {
        this.accWithInstn1 = accWithInstn1;
    }

    
    @Column(name="BENEF_INSTITUTION1", length=210)
    public String getBenefInstitution1() {
        return this.benefInstitution1;
    }
    
    public void setBenefInstitution1(String benefInstitution1) {
        this.benefInstitution1 = benefInstitution1;
    }

    
    @Column(name="BENEF_INSTITUTION2", length=210)
    public String getBenefInstitution2() {
        return this.benefInstitution2;
    }
    
    public void setBenefInstitution2(String benefInstitution2) {
        this.benefInstitution2 = benefInstitution2;
    }

    
    @Column(name="BENEF_INSTITUTION3", length=210)
    public String getBenefInstitution3() {
        return this.benefInstitution3;
    }
    
    public void setBenefInstitution3(String benefInstitution3) {
        this.benefInstitution3 = benefInstitution3;
    }

    
    @Column(name="BENEF_INSTITUTION4", length=210)
    public String getBenefInstitution4() {
        return this.benefInstitution4;
    }
    
    public void setBenefInstitution4(String benefInstitution4) {
        this.benefInstitution4 = benefInstitution4;
    }

    
    @Column(name="PAYMENT_DETAILS1", length=105)
    public String getPaymentDetails1() {
        return this.paymentDetails1;
    }
    
    public void setPaymentDetails1(String paymentDetails1) {
        this.paymentDetails1 = paymentDetails1;
    }

    
    @Column(name="PAYMENT_DETAILS2", length=105)
    public String getPaymentDetails2() {
        return this.paymentDetails2;
    }
    
    public void setPaymentDetails2(String paymentDetails2) {
        this.paymentDetails2 = paymentDetails2;
    }

    
    @Column(name="PAYMENT_DETAILS3", length=105)
    public String getPaymentDetails3() {
        return this.paymentDetails3;
    }
    
    public void setPaymentDetails3(String paymentDetails3) {
        this.paymentDetails3 = paymentDetails3;
    }

    
    @Column(name="PAYMENT_DETAILS4", length=105)
    public String getPaymentDetails4() {
        return this.paymentDetails4;
    }
    
    public void setPaymentDetails4(String paymentDetails4) {
        this.paymentDetails4 = paymentDetails4;
    }

    
    @Column(name="RELATED_REF_NO", length=105)
    public String getRelatedRefNo() {
        return this.relatedRefNo;
    }
    
    public void setRelatedRefNo(String relatedRefNo) {
        this.relatedRefNo = relatedRefNo;
    }

    
    @Column(name="MOD_NO", precision=4, scale=0)
    public Short getModNo() {
        return this.modNo;
    }
    
    public void setModNo(Short modNo) {
        this.modNo = modNo;
    }

    
    @Column(name="MAKER_ID", length=12)
    public String getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(String makerId) {
        this.makerId = makerId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MAKER_DT_STAMP", length=7)
    public Date getMakerDtStamp() {
        return this.makerDtStamp;
    }
    
    public void setMakerDtStamp(Date makerDtStamp) {
        this.makerDtStamp = makerDtStamp;
    }

    
    @Column(name="CHECKER_ID", length=12)
    public String getCheckerId() {
        return this.checkerId;
    }
    
    public void setCheckerId(String checkerId) {
        this.checkerId = checkerId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CHECKER_DT_STAMP", length=7)
    public Date getCheckerDtStamp() {
        return this.checkerDtStamp;
    }
    
    public void setCheckerDtStamp(Date checkerDtStamp) {
        this.checkerDtStamp = checkerDtStamp;
    }

    
    @Column(name="RECORD_STAT", length=1)
    public String getRecordStat() {
        return this.recordStat;
    }
    
    public void setRecordStat(String recordStat) {
        this.recordStat = recordStat;
    }

    
    @Column(name="AUTH_STAT", length=1)
    public String getAuthStat() {
        return this.authStat;
    }
    
    public void setAuthStat(String authStat) {
        this.authStat = authStat;
    }

    
    @Column(name="ONCE_AUTH", length=1)
    public String getOnceAuth() {
        return this.onceAuth;
    }
    
    public void setOnceAuth(String onceAuth) {
        this.onceAuth = onceAuth;
    }

    
    @Column(name="MSG_TYPE", length=7)
    public String getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    
    @Column(name="BRANCH_CODE", length=3)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    
    @Column(name="VERSION_NO", precision=4, scale=0)
    public Short getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Short versionNo) {
        this.versionNo = versionNo;
    }

    
    @Column(name="LATEST_VERSION_NO", precision=4, scale=0)
    public Short getLatestVersionNo() {
        return this.latestVersionNo;
    }
    
    public void setLatestVersionNo(Short latestVersionNo) {
        this.latestVersionNo = latestVersionNo;
    }

    
    @Column(name="CUST_AC_BRN", length=3)
    public String getCustAcBrn() {
        return this.custAcBrn;
    }
    
    public void setCustAcBrn(String custAcBrn) {
        this.custAcBrn = custAcBrn;
    }

    
    @Column(name="UDF_49", length=35)
    public String getUdf49() {
        return this.udf49;
    }
    
    public void setUdf49(String udf49) {
        this.udf49 = udf49;
    }

    
    @Column(name="UDF_50", length=35)
    public String getUdf50() {
        return this.udf50;
    }
    
    public void setUdf50(String udf50) {
        this.udf50 = udf50;
    }

    
    @Column(name="END_TO_END_ID", length=105)
    public String getEndToEndId() {
        return this.endToEndId;
    }
    
    public void setEndToEndId(String endToEndId) {
        this.endToEndId = endToEndId;
    }

    
    @Column(name="SERVICE_LEVEL_CODE", length=4)
    public String getServiceLevelCode() {
        return this.serviceLevelCode;
    }
    
    public void setServiceLevelCode(String serviceLevelCode) {
        this.serviceLevelCode = serviceLevelCode;
    }

    
    @Column(name="CHARGE_BEARER", length=4)
    public String getChargeBearer() {
        return this.chargeBearer;
    }
    
    public void setChargeBearer(String chargeBearer) {
        this.chargeBearer = chargeBearer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSTRUCTION_DATE", length=7)
    public Date getInstructionDate() {
        return this.instructionDate;
    }
    
    public void setInstructionDate(Date instructionDate) {
        this.instructionDate = instructionDate;
    }

    
    @Column(name="CUST_ID", length=1)
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }

    
    @Column(name="CUST_ID_TYPE", length=105)
    public String getCustIdType() {
        return this.custIdType;
    }
    
    public void setCustIdType(String custIdType) {
        this.custIdType = custIdType;
    }

    
    @Column(name="CUST_ID_VALUE", length=105)
    public String getCustIdValue() {
        return this.custIdValue;
    }
    
    public void setCustIdValue(String custIdValue) {
        this.custIdValue = custIdValue;
    }

    
    @Column(name="CUST_ID_ISSUER", length=105)
    public String getCustIdIssuer() {
        return this.custIdIssuer;
    }
    
    public void setCustIdIssuer(String custIdIssuer) {
        this.custIdIssuer = custIdIssuer;
    }

    
    @Column(name="CUST_OTHER_ID_TYPE", length=105)
    public String getCustOtherIdType() {
        return this.custOtherIdType;
    }
    
    public void setCustOtherIdType(String custOtherIdType) {
        this.custOtherIdType = custOtherIdType;
    }

    
    @Column(name="CUST_BIRTH_CITY", length=105)
    public String getCustBirthCity() {
        return this.custBirthCity;
    }
    
    public void setCustBirthCity(String custBirthCity) {
        this.custBirthCity = custBirthCity;
    }

    
    @Column(name="CUST_BIRTH_COUNTRY", length=3)
    public String getCustBirthCountry() {
        return this.custBirthCountry;
    }
    
    public void setCustBirthCountry(String custBirthCountry) {
        this.custBirthCountry = custBirthCountry;
    }

    
    @Column(name="CUST_BANKCODE", length=11)
    public String getCustBankcode() {
        return this.custBankcode;
    }
    
    public void setCustBankcode(String custBankcode) {
        this.custBankcode = custBankcode;
    }

    
    @Column(name="CPTY_ID", length=1)
    public String getCptyId() {
        return this.cptyId;
    }
    
    public void setCptyId(String cptyId) {
        this.cptyId = cptyId;
    }

    
    @Column(name="CPTY_ID_TYPE", length=105)
    public String getCptyIdType() {
        return this.cptyIdType;
    }
    
    public void setCptyIdType(String cptyIdType) {
        this.cptyIdType = cptyIdType;
    }

    
    @Column(name="CPTY_ID_VALUE", length=105)
    public String getCptyIdValue() {
        return this.cptyIdValue;
    }
    
    public void setCptyIdValue(String cptyIdValue) {
        this.cptyIdValue = cptyIdValue;
    }

    
    @Column(name="CPTY_ID_ISSUER", length=105)
    public String getCptyIdIssuer() {
        return this.cptyIdIssuer;
    }
    
    public void setCptyIdIssuer(String cptyIdIssuer) {
        this.cptyIdIssuer = cptyIdIssuer;
    }

    
    @Column(name="CPTY_OTHER_ID_TYPE", length=105)
    public String getCptyOtherIdType() {
        return this.cptyOtherIdType;
    }
    
    public void setCptyOtherIdType(String cptyOtherIdType) {
        this.cptyOtherIdType = cptyOtherIdType;
    }

    
    @Column(name="CPTY_BIRTH_CITY", length=105)
    public String getCptyBirthCity() {
        return this.cptyBirthCity;
    }
    
    public void setCptyBirthCity(String cptyBirthCity) {
        this.cptyBirthCity = cptyBirthCity;
    }

    
    @Column(name="CPTY_BIRTH_COUNTRY", length=3)
    public String getCptyBirthCountry() {
        return this.cptyBirthCountry;
    }
    
    public void setCptyBirthCountry(String cptyBirthCountry) {
        this.cptyBirthCountry = cptyBirthCountry;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SETTLEMENT_DATE", length=7)
    public Date getSettlementDate() {
        return this.settlementDate;
    }
    
    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    
    @Column(name="SETTLEMENT_METHOD", length=4)
    public String getSettlementMethod() {
        return this.settlementMethod;
    }
    
    public void setSettlementMethod(String settlementMethod) {
        this.settlementMethod = settlementMethod;
    }

    
    @Column(name="CLG_SYSTEM_ID", length=35)
    public String getClgSystemId() {
        return this.clgSystemId;
    }
    
    public void setClgSystemId(String clgSystemId) {
        this.clgSystemId = clgSystemId;
    }

    
    @Column(name="ULTIMATE_DEBTOR", length=105)
    public String getUltimateDebtor() {
        return this.ultimateDebtor;
    }
    
    public void setUltimateDebtor(String ultimateDebtor) {
        this.ultimateDebtor = ultimateDebtor;
    }

    
    @Column(name="ULTIMATE_CREDITOR", length=105)
    public String getUltimateCreditor() {
        return this.ultimateCreditor;
    }
    
    public void setUltimateCreditor(String ultimateCreditor) {
        this.ultimateCreditor = ultimateCreditor;
    }

    
    @Column(name="CUST_CTRY", length=3)
    public String getCustCtry() {
        return this.custCtry;
    }
    
    public void setCustCtry(String custCtry) {
        this.custCtry = custCtry;
    }

    
    @Column(name="BENEF_CTRY", length=3)
    public String getBenefCtry() {
        return this.benefCtry;
    }
    
    public void setBenefCtry(String benefCtry) {
        this.benefCtry = benefCtry;
    }

    
    @Column(name="INITPARTY_NAME", length=70)
    public String getInitpartyName() {
        return this.initpartyName;
    }
    
    public void setInitpartyName(String initpartyName) {
        this.initpartyName = initpartyName;
    }

    
    @Column(name="INITPARTY_TYPE", length=1)
    public String getInitpartyType() {
        return this.initpartyType;
    }
    
    public void setInitpartyType(String initpartyType) {
        this.initpartyType = initpartyType;
    }

    
    @Column(name="INITPARTY_IDTYPE", length=2)
    public String getInitpartyIdtype() {
        return this.initpartyIdtype;
    }
    
    public void setInitpartyIdtype(String initpartyIdtype) {
        this.initpartyIdtype = initpartyIdtype;
    }

    
    @Column(name="INITPARTY_IDVALUE", length=35)
    public String getInitpartyIdvalue() {
        return this.initpartyIdvalue;
    }
    
    public void setInitpartyIdvalue(String initpartyIdvalue) {
        this.initpartyIdvalue = initpartyIdvalue;
    }

    
    @Column(name="INITPARTY_OTHERID_TYPE", length=35)
    public String getInitpartyOtheridType() {
        return this.initpartyOtheridType;
    }
    
    public void setInitpartyOtheridType(String initpartyOtheridType) {
        this.initpartyOtheridType = initpartyOtheridType;
    }

    
    @Column(name="INITPARTY_IDISSUER", length=35)
    public String getInitpartyIdissuer() {
        return this.initpartyIdissuer;
    }
    
    public void setInitpartyIdissuer(String initpartyIdissuer) {
        this.initpartyIdissuer = initpartyIdissuer;
    }

    
    @Column(name="INITPARTY_DOBCITY", length=35)
    public String getInitpartyDobcity() {
        return this.initpartyDobcity;
    }
    
    public void setInitpartyDobcity(String initpartyDobcity) {
        this.initpartyDobcity = initpartyDobcity;
    }

    
    @Column(name="INITPARTY_DOBCTRY", length=3)
    public String getInitpartyDobctry() {
        return this.initpartyDobctry;
    }
    
    public void setInitpartyDobctry(String initpartyDobctry) {
        this.initpartyDobctry = initpartyDobctry;
    }

    
    @Column(name="DD_SEQ_TYPE", length=4)
    public String getDdSeqType() {
        return this.ddSeqType;
    }
    
    public void setDdSeqType(String ddSeqType) {
        this.ddSeqType = ddSeqType;
    }

    
    @Column(name="MANDATE_ID", length=35)
    public String getMandateId() {
        return this.mandateId;
    }
    
    public void setMandateId(String mandateId) {
        this.mandateId = mandateId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MAND_SIGN_DATE", length=7)
    public Date getMandSignDate() {
        return this.mandSignDate;
    }
    
    public void setMandSignDate(Date mandSignDate) {
        this.mandSignDate = mandSignDate;
    }

    
    @Column(name="CREDITOR_SCH_ID", length=35)
    public String getCreditorSchId() {
        return this.creditorSchId;
    }
    
    public void setCreditorSchId(String creditorSchId) {
        this.creditorSchId = creditorSchId;
    }

    
    @Column(name="MAND_AMEND_IND", length=9)
    public String getMandAmendInd() {
        return this.mandAmendInd;
    }
    
    public void setMandAmendInd(String mandAmendInd) {
        this.mandAmendInd = mandAmendInd;
    }

    
    @Column(name="MAND_AMEND_TYPE", length=35)
    public String getMandAmendType() {
        return this.mandAmendType;
    }
    
    public void setMandAmendType(String mandAmendType) {
        this.mandAmendType = mandAmendType;
    }

    
    @Column(name="ORG_MANDATE_ID", length=35)
    public String getOrgMandateId() {
        return this.orgMandateId;
    }
    
    public void setOrgMandateId(String orgMandateId) {
        this.orgMandateId = orgMandateId;
    }

    
    @Column(name="ORG_CREDITOR_SCH_ID", length=35)
    public String getOrgCreditorSchId() {
        return this.orgCreditorSchId;
    }
    
    public void setOrgCreditorSchId(String orgCreditorSchId) {
        this.orgCreditorSchId = orgCreditorSchId;
    }

    
    @Column(name="ORG_CREDITOR_NAME", length=70)
    public String getOrgCreditorName() {
        return this.orgCreditorName;
    }
    
    public void setOrgCreditorName(String orgCreditorName) {
        this.orgCreditorName = orgCreditorName;
    }

    
    @Column(name="ORG_DEBTOR_ACC", length=105)
    public String getOrgDebtorAcc() {
        return this.orgDebtorAcc;
    }
    
    public void setOrgDebtorAcc(String orgDebtorAcc) {
        this.orgDebtorAcc = orgDebtorAcc;
    }

    
    @Column(name="ORG_DEBTOR_BANK", length=35)
    public String getOrgDebtorBank() {
        return this.orgDebtorBank;
    }
    
    public void setOrgDebtorBank(String orgDebtorBank) {
        this.orgDebtorBank = orgDebtorBank;
    }

    
    @Column(name="LOCAL_INSTRUMENT_TYPE", length=1)
    public String getLocalInstrumentType() {
        return this.localInstrumentType;
    }
    
    public void setLocalInstrumentType(String localInstrumentType) {
        this.localInstrumentType = localInstrumentType;
    }

    
    @Column(name="LOCAL_INSTRUMENT_VALUE", length=105)
    public String getLocalInstrumentValue() {
        return this.localInstrumentValue;
    }
    
    public void setLocalInstrumentValue(String localInstrumentValue) {
        this.localInstrumentValue = localInstrumentValue;
    }

    
    @Column(name="CATEGORY_PURPOSE", length=4)
    public String getCategoryPurpose() {
        return this.categoryPurpose;
    }
    
    public void setCategoryPurpose(String categoryPurpose) {
        this.categoryPurpose = categoryPurpose;
    }

    
    @Column(name="PURPOSE_TYPE", length=1)
    public String getPurposeType() {
        return this.purposeType;
    }
    
    public void setPurposeType(String purposeType) {
        this.purposeType = purposeType;
    }

    
    @Column(name="PURPOSE_VALUE", length=105)
    public String getPurposeValue() {
        return this.purposeValue;
    }
    
    public void setPurposeValue(String purposeValue) {
        this.purposeValue = purposeValue;
    }

    
    @Column(name="ELEC_SIG", length=1025)
    public String getElecSig() {
        return this.elecSig;
    }
    
    public void setElecSig(String elecSig) {
        this.elecSig = elecSig;
    }

    
    @Column(name="CREDITOR_SCH_ID_TYPE", length=105)
    public String getCreditorSchIdType() {
        return this.creditorSchIdType;
    }
    
    public void setCreditorSchIdType(String creditorSchIdType) {
        this.creditorSchIdType = creditorSchIdType;
    }

    
    @Column(name="ORG_CREDITOR_SCH_ID_TYPE", length=105)
    public String getOrgCreditorSchIdType() {
        return this.orgCreditorSchIdType;
    }
    
    public void setOrgCreditorSchIdType(String orgCreditorSchIdType) {
        this.orgCreditorSchIdType = orgCreditorSchIdType;
    }

    
    @Column(name="ULT_DEBTOR_ADD1", length=210)
    public String getUltDebtorAdd1() {
        return this.ultDebtorAdd1;
    }
    
    public void setUltDebtorAdd1(String ultDebtorAdd1) {
        this.ultDebtorAdd1 = ultDebtorAdd1;
    }

    
    @Column(name="ULT_DEBTOR_ADD2", length=210)
    public String getUltDebtorAdd2() {
        return this.ultDebtorAdd2;
    }
    
    public void setUltDebtorAdd2(String ultDebtorAdd2) {
        this.ultDebtorAdd2 = ultDebtorAdd2;
    }

    
    @Column(name="ULT_DEBTOR_ID", length=1)
    public String getUltDebtorId() {
        return this.ultDebtorId;
    }
    
    public void setUltDebtorId(String ultDebtorId) {
        this.ultDebtorId = ultDebtorId;
    }

    
    @Column(name="ULT_DEBTOR_ID_TYPE", length=105)
    public String getUltDebtorIdType() {
        return this.ultDebtorIdType;
    }
    
    public void setUltDebtorIdType(String ultDebtorIdType) {
        this.ultDebtorIdType = ultDebtorIdType;
    }

    
    @Column(name="ULT_DEBTOR_ID_VALUE", length=105)
    public String getUltDebtorIdValue() {
        return this.ultDebtorIdValue;
    }
    
    public void setUltDebtorIdValue(String ultDebtorIdValue) {
        this.ultDebtorIdValue = ultDebtorIdValue;
    }

    
    @Column(name="ULT_DEBTOR_ID_ISSUER", length=105)
    public String getUltDebtorIdIssuer() {
        return this.ultDebtorIdIssuer;
    }
    
    public void setUltDebtorIdIssuer(String ultDebtorIdIssuer) {
        this.ultDebtorIdIssuer = ultDebtorIdIssuer;
    }

    
    @Column(name="ULT_DEBTOR_OTHER_ID_TYPE", length=105)
    public String getUltDebtorOtherIdType() {
        return this.ultDebtorOtherIdType;
    }
    
    public void setUltDebtorOtherIdType(String ultDebtorOtherIdType) {
        this.ultDebtorOtherIdType = ultDebtorOtherIdType;
    }

    
    @Column(name="ULT_DEBTOR_BIRTH_CITY", length=105)
    public String getUltDebtorBirthCity() {
        return this.ultDebtorBirthCity;
    }
    
    public void setUltDebtorBirthCity(String ultDebtorBirthCity) {
        this.ultDebtorBirthCity = ultDebtorBirthCity;
    }

    
    @Column(name="ULT_DEBTOR_BIRTH_COUNTRY", length=3)
    public String getUltDebtorBirthCountry() {
        return this.ultDebtorBirthCountry;
    }
    
    public void setUltDebtorBirthCountry(String ultDebtorBirthCountry) {
        this.ultDebtorBirthCountry = ultDebtorBirthCountry;
    }

    
    @Column(name="ULT_CREDITOR_ADD1", length=210)
    public String getUltCreditorAdd1() {
        return this.ultCreditorAdd1;
    }
    
    public void setUltCreditorAdd1(String ultCreditorAdd1) {
        this.ultCreditorAdd1 = ultCreditorAdd1;
    }

    
    @Column(name="ULT_CREDITOR_ADD2", length=210)
    public String getUltCreditorAdd2() {
        return this.ultCreditorAdd2;
    }
    
    public void setUltCreditorAdd2(String ultCreditorAdd2) {
        this.ultCreditorAdd2 = ultCreditorAdd2;
    }

    
    @Column(name="ULT_CREDITOR_ID", length=1)
    public String getUltCreditorId() {
        return this.ultCreditorId;
    }
    
    public void setUltCreditorId(String ultCreditorId) {
        this.ultCreditorId = ultCreditorId;
    }

    
    @Column(name="ULT_CREDITOR_ID_TYPE", length=105)
    public String getUltCreditorIdType() {
        return this.ultCreditorIdType;
    }
    
    public void setUltCreditorIdType(String ultCreditorIdType) {
        this.ultCreditorIdType = ultCreditorIdType;
    }

    
    @Column(name="ULT_CREDITOR_ID_VALUE", length=105)
    public String getUltCreditorIdValue() {
        return this.ultCreditorIdValue;
    }
    
    public void setUltCreditorIdValue(String ultCreditorIdValue) {
        this.ultCreditorIdValue = ultCreditorIdValue;
    }

    
    @Column(name="ULT_CREDITOR_ID_ISSUER", length=105)
    public String getUltCreditorIdIssuer() {
        return this.ultCreditorIdIssuer;
    }
    
    public void setUltCreditorIdIssuer(String ultCreditorIdIssuer) {
        this.ultCreditorIdIssuer = ultCreditorIdIssuer;
    }

    
    @Column(name="ULT_CREDITOR_OTHER_ID_TYPE", length=105)
    public String getUltCreditorOtherIdType() {
        return this.ultCreditorOtherIdType;
    }
    
    public void setUltCreditorOtherIdType(String ultCreditorOtherIdType) {
        this.ultCreditorOtherIdType = ultCreditorOtherIdType;
    }

    
    @Column(name="ULT_CREDITOR_BIRTH_CITY", length=105)
    public String getUltCreditorBirthCity() {
        return this.ultCreditorBirthCity;
    }
    
    public void setUltCreditorBirthCity(String ultCreditorBirthCity) {
        this.ultCreditorBirthCity = ultCreditorBirthCity;
    }

    
    @Column(name="ULT_CREDITOR_BIRTH_COUNTRY", length=3)
    public String getUltCreditorBirthCountry() {
        return this.ultCreditorBirthCountry;
    }
    
    public void setUltCreditorBirthCountry(String ultCreditorBirthCountry) {
        this.ultCreditorBirthCountry = ultCreditorBirthCountry;
    }

    
    @Column(name="ID_ENTITY", length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPDATED", length=7)
    public Date getDatupdated() {
        return this.datupdated;
    }
    
    public void setDatupdated(Date datupdated) {
        this.datupdated = datupdated;
    }

    
    @Column(name="TIMERSTATUS", length=1)
    public String getTimerstatus() {
        return this.timerstatus;
    }
    
    public void setTimerstatus(String timerstatus) {
        this.timerstatus = timerstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TIMERDATETIME", length=7)
    public Date getTimerdatetime() {
        return this.timerdatetime;
    }
    
    public void setTimerdatetime(Date timerdatetime) {
        this.timerdatetime = timerdatetime;
    }

    
    @Column(name="TOKEN1", length=105)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=105)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=105)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4", length=105)
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5", length=105)
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="TOKEN6", length=105)
    public String getToken6() {
        return this.token6;
    }
    
    public void setToken6(String token6) {
        this.token6 = token6;
    }

    
    @Column(name="TOKEN7", length=105)
    public String getToken7() {
        return this.token7;
    }
    
    public void setToken7(String token7) {
        this.token7 = token7;
    }

    
    @Column(name="TOKEN8", length=105)
    public String getToken8() {
        return this.token8;
    }
    
    public void setToken8(String token8) {
        this.token8 = token8;
    }

    
    @Column(name="TOKEN9", length=105)
    public String getToken9() {
        return this.token9;
    }
    
    public void setToken9(String token9) {
        this.token9 = token9;
    }

    
    @Column(name="REJ_ORIGINATOR_NAME", length=210)
    public String getRejOriginatorName() {
        return this.rejOriginatorName;
    }
    
    public void setRejOriginatorName(String rejOriginatorName) {
        this.rejOriginatorName = rejOriginatorName;
    }

    
    @Column(name="REJECT_CODE", length=4)
    public String getRejectCode() {
        return this.rejectCode;
    }
    
    public void setRejectCode(String rejectCode) {
        this.rejectCode = rejectCode;
    }

    
    @Column(name="REJECT_DETAILS", length=35)
    public String getRejectDetails() {
        return this.rejectDetails;
    }
    
    public void setRejectDetails(String rejectDetails) {
        this.rejectDetails = rejectDetails;
    }




}


