package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HostProductList generated by hbm2java
 */
@Entity
@Table(name="HOST_PRODUCT_LIST"
    ,schema="FCDBADMIN_RK"
)
public class HostProductList  implements java.io.Serializable {


     private HostProductListId id;
     private String namproduct;
     private BigDecimal codccy;
     private String namccy;
     private Character typprod;
     private Date datexpiry;
     private Character depttermunit;
     private String productcategory;
     private String typeuser;

    public HostProductList() {
    }

	
    public HostProductList(HostProductListId id) {
        this.id = id;
    }
    public HostProductList(HostProductListId id, String namproduct, BigDecimal codccy, String namccy, Character typprod, Date datexpiry, Character depttermunit, String productcategory, String typeuser) {
       this.id = id;
       this.namproduct = namproduct;
       this.codccy = codccy;
       this.namccy = namccy;
       this.typprod = typprod;
       this.datexpiry = datexpiry;
       this.depttermunit = depttermunit;
       this.productcategory = productcategory;
       this.typeuser = typeuser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codproduct", column=@Column(name="CODPRODUCT", nullable=false, length=10) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ) } )
    public HostProductListId getId() {
        return this.id;
    }
    
    public void setId(HostProductListId id) {
        this.id = id;
    }

    
    @Column(name="NAMPRODUCT", length=100)
    public String getNamproduct() {
        return this.namproduct;
    }
    
    public void setNamproduct(String namproduct) {
        this.namproduct = namproduct;
    }

    
    @Column(name="CODCCY", precision=22, scale=0)
    public BigDecimal getCodccy() {
        return this.codccy;
    }
    
    public void setCodccy(BigDecimal codccy) {
        this.codccy = codccy;
    }

    
    @Column(name="NAMCCY", length=15)
    public String getNamccy() {
        return this.namccy;
    }
    
    public void setNamccy(String namccy) {
        this.namccy = namccy;
    }

    
    @Column(name="TYPPROD", length=1)
    public Character getTypprod() {
        return this.typprod;
    }
    
    public void setTypprod(Character typprod) {
        this.typprod = typprod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEXPIRY", length=7)
    public Date getDatexpiry() {
        return this.datexpiry;
    }
    
    public void setDatexpiry(Date datexpiry) {
        this.datexpiry = datexpiry;
    }

    
    @Column(name="DEPTTERMUNIT", length=1)
    public Character getDepttermunit() {
        return this.depttermunit;
    }
    
    public void setDepttermunit(Character depttermunit) {
        this.depttermunit = depttermunit;
    }

    
    @Column(name="PRODUCTCATEGORY", length=3)
    public String getProductcategory() {
        return this.productcategory;
    }
    
    public void setProductcategory(String productcategory) {
        this.productcategory = productcategory;
    }

    
    @Column(name="TYPEUSER", length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }




}


