package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IsMstfundfamily generated by hbm2java
 */
@Entity
@Table(name="IS_MSTFUNDFAMILY"
    ,schema="FCDBADMIN_RK"
)
public class IsMstfundfamily  implements java.io.Serializable {


     private IsMstfundfamilyId id;
     private String namfamily;
     private Set<IsMstfund> isMstfunds = new HashSet<IsMstfund>(0);

    public IsMstfundfamily() {
    }

	
    public IsMstfundfamily(IsMstfundfamilyId id) {
        this.id = id;
    }
    public IsMstfundfamily(IsMstfundfamilyId id, String namfamily, Set<IsMstfund> isMstfunds) {
       this.id = id;
       this.namfamily = namfamily;
       this.isMstfunds = isMstfunds;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="codfamily", column=@Column(name="CODFAMILY", nullable=false, length=25) ), 
        @AttributeOverride(name="idamc", column=@Column(name="IDAMC", nullable=false, length=8) ) } )
    public IsMstfundfamilyId getId() {
        return this.id;
    }
    
    public void setId(IsMstfundfamilyId id) {
        this.id = id;
    }

    
    @Column(name="NAMFAMILY", length=30)
    public String getNamfamily() {
        return this.namfamily;
    }
    
    public void setNamfamily(String namfamily) {
        this.namfamily = namfamily;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="isMstfundfamily")
    public Set<IsMstfund> getIsMstfunds() {
        return this.isMstfunds;
    }
    
    public void setIsMstfunds(Set<IsMstfund> isMstfunds) {
        this.isMstfunds = isMstfunds;
    }




}


