package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IsMstfund generated by hbm2java
 */
@Entity
@Table(name="IS_MSTFUND"
    ,schema="FCDBADMIN_RK"
)
public class IsMstfund  implements java.io.Serializable {


     private IsMstfundId id;
     private Mstentity mstentity;
     private IsMstfundfamily isMstfundfamily;
     private Long numseq;
     private String namfund;
     private String codcurrbase;
     private String codfundtype;
     private String codassetmix;
     private String codobjective;
     private String namticker;
     private String codscrip;
     private BigDecimal numnav;
     private Character switchflag;
     private String isin;
     private String namamc;
     private Character navflag;
     private String idcustodian;
     private Set<IsMstfundtxn> isMstfundtxns = new HashSet<IsMstfundtxn>(0);
     private Set<IsMstproduct> isMstproducts = new HashSet<IsMstproduct>(0);
     private Set<IsMstfundcurr> isMstfundcurrs = new HashSet<IsMstfundcurr>(0);
     private Set<IsMstfundtpr> isMstfundtprs = new HashSet<IsMstfundtpr>(0);

    public IsMstfund() {
    }

	
    public IsMstfund(IsMstfundId id, Mstentity mstentity, IsMstfundfamily isMstfundfamily) {
        this.id = id;
        this.mstentity = mstentity;
        this.isMstfundfamily = isMstfundfamily;
    }
    public IsMstfund(IsMstfundId id, Mstentity mstentity, IsMstfundfamily isMstfundfamily, Long numseq, String namfund, String codcurrbase, String codfundtype, String codassetmix, String codobjective, String namticker, String codscrip, BigDecimal numnav, Character switchflag, String isin, String namamc, Character navflag, String idcustodian, Set<IsMstfundtxn> isMstfundtxns, Set<IsMstproduct> isMstproducts, Set<IsMstfundcurr> isMstfundcurrs, Set<IsMstfundtpr> isMstfundtprs) {
       this.id = id;
       this.mstentity = mstentity;
       this.isMstfundfamily = isMstfundfamily;
       this.numseq = numseq;
       this.namfund = namfund;
       this.codcurrbase = codcurrbase;
       this.codfundtype = codfundtype;
       this.codassetmix = codassetmix;
       this.codobjective = codobjective;
       this.namticker = namticker;
       this.codscrip = codscrip;
       this.numnav = numnav;
       this.switchflag = switchflag;
       this.isin = isin;
       this.namamc = namamc;
       this.navflag = navflag;
       this.idcustodian = idcustodian;
       this.isMstfundtxns = isMstfundtxns;
       this.isMstproducts = isMstproducts;
       this.isMstfundcurrs = isMstfundcurrs;
       this.isMstfundtprs = isMstfundtprs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ) } )
    public IsMstfundId getId() {
        return this.id;
    }
    
    public void setId(IsMstfundId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY",  insertable=false, updatable=false), 
        @JoinColumn(name="CODFAMILY", referencedColumnName="CODFAMILY", insertable=false, updatable=false), 
        @JoinColumn(name="IDAMC", referencedColumnName="IDAMC", insertable=false, updatable=false) } )
    public IsMstfundfamily getIsMstfundfamily() {
        return this.isMstfundfamily;
    }
    
    public void setIsMstfundfamily(IsMstfundfamily isMstfundfamily) {
        this.isMstfundfamily = isMstfundfamily;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }

    
    @Column(name="NAMFUND", length=100)
    public String getNamfund() {
        return this.namfund;
    }
    
    public void setNamfund(String namfund) {
        this.namfund = namfund;
    }

    
    @Column(name="CODCURRBASE", length=3)
    public String getCodcurrbase() {
        return this.codcurrbase;
    }
    
    public void setCodcurrbase(String codcurrbase) {
        this.codcurrbase = codcurrbase;
    }

    
    @Column(name="CODFUNDTYPE", length=25)
    public String getCodfundtype() {
        return this.codfundtype;
    }
    
    public void setCodfundtype(String codfundtype) {
        this.codfundtype = codfundtype;
    }

    
    @Column(name="CODASSETMIX", length=25)
    public String getCodassetmix() {
        return this.codassetmix;
    }
    
    public void setCodassetmix(String codassetmix) {
        this.codassetmix = codassetmix;
    }

    
    @Column(name="CODOBJECTIVE", length=25)
    public String getCodobjective() {
        return this.codobjective;
    }
    
    public void setCodobjective(String codobjective) {
        this.codobjective = codobjective;
    }

    
    @Column(name="NAMTICKER", length=15)
    public String getNamticker() {
        return this.namticker;
    }
    
    public void setNamticker(String namticker) {
        this.namticker = namticker;
    }

    
    @Column(name="CODSCRIP", length=25)
    public String getCodscrip() {
        return this.codscrip;
    }
    
    public void setCodscrip(String codscrip) {
        this.codscrip = codscrip;
    }

    
    @Column(name="NUMNAV", scale=4)
    public BigDecimal getNumnav() {
        return this.numnav;
    }
    
    public void setNumnav(BigDecimal numnav) {
        this.numnav = numnav;
    }

    
    @Column(name="SWITCHFLAG", length=1)
    public Character getSwitchflag() {
        return this.switchflag;
    }
    
    public void setSwitchflag(Character switchflag) {
        this.switchflag = switchflag;
    }

    
    @Column(name="ISIN", length=25)
    public String getIsin() {
        return this.isin;
    }
    
    public void setIsin(String isin) {
        this.isin = isin;
    }

    
    @Column(name="NAMAMC", length=100)
    public String getNamamc() {
        return this.namamc;
    }
    
    public void setNamamc(String namamc) {
        this.namamc = namamc;
    }

    
    @Column(name="NAVFLAG", length=1)
    public Character getNavflag() {
        return this.navflag;
    }
    
    public void setNavflag(Character navflag) {
        this.navflag = navflag;
    }

    
    @Column(name="IDCUSTODIAN", length=25)
    public String getIdcustodian() {
        return this.idcustodian;
    }
    
    public void setIdcustodian(String idcustodian) {
        this.idcustodian = idcustodian;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="isMstfund")
    public Set<IsMstfundtxn> getIsMstfundtxns() {
        return this.isMstfundtxns;
    }
    
    public void setIsMstfundtxns(Set<IsMstfundtxn> isMstfundtxns) {
        this.isMstfundtxns = isMstfundtxns;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="isMstfund")
    public Set<IsMstproduct> getIsMstproducts() {
        return this.isMstproducts;
    }
    
    public void setIsMstproducts(Set<IsMstproduct> isMstproducts) {
        this.isMstproducts = isMstproducts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="isMstfund")
    public Set<IsMstfundcurr> getIsMstfundcurrs() {
        return this.isMstfundcurrs;
    }
    
    public void setIsMstfundcurrs(Set<IsMstfundcurr> isMstfundcurrs) {
        this.isMstfundcurrs = isMstfundcurrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="isMstfund")
    public Set<IsMstfundtpr> getIsMstfundtprs() {
        return this.isMstfundtprs;
    }
    
    public void setIsMstfundtprs(Set<IsMstfundtpr> isMstfundtprs) {
        this.isMstfundtprs = isMstfundtprs;
    }




}


