package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsMstuserportfolio generated by hbm2java
 */
@Entity
@Table(name="IS_MSTUSERPORTFOLIO"
    ,schema="FCDBADMIN_RK"
)
public class IsMstuserportfolio  implements java.io.Serializable {


     private IsMstuserportfolioId id;
     private Mstentity mstentity;
     private BigDecimal numtotalholding;
     private BigDecimal numholdingoutsidelockin;
     private BigDecimal valinfundcurr;
     private BigDecimal valinuhccy;
     private String uhccy;
     private BigDecimal blockedunits;
     private BigDecimal provisionalunits;
     private BigDecimal issuedbal;
     private BigDecimal unissuedbal;
     private BigDecimal sellableunits;
     private BigDecimal currentnav;
     private Long numseq;

    public IsMstuserportfolio() {
    }

	
    public IsMstuserportfolio(IsMstuserportfolioId id, Mstentity mstentity) {
        this.id = id;
        this.mstentity = mstentity;
    }
    public IsMstuserportfolio(IsMstuserportfolioId id, Mstentity mstentity, BigDecimal numtotalholding, BigDecimal numholdingoutsidelockin, BigDecimal valinfundcurr, BigDecimal valinuhccy, String uhccy, BigDecimal blockedunits, BigDecimal provisionalunits, BigDecimal issuedbal, BigDecimal unissuedbal, BigDecimal sellableunits, BigDecimal currentnav, Long numseq) {
       this.id = id;
       this.mstentity = mstentity;
       this.numtotalholding = numtotalholding;
       this.numholdingoutsidelockin = numholdingoutsidelockin;
       this.valinfundcurr = valinfundcurr;
       this.valinuhccy = valinuhccy;
       this.uhccy = uhccy;
       this.blockedunits = blockedunits;
       this.provisionalunits = provisionalunits;
       this.issuedbal = issuedbal;
       this.unissuedbal = unissuedbal;
       this.sellableunits = sellableunits;
       this.currentnav = currentnav;
       this.numseq = numseq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false) ), 
        @AttributeOverride(name="iduh", column=@Column(name="IDUH", nullable=false, length=16) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ) } )
    public IsMstuserportfolioId getId() {
        return this.id;
    }
    
    public void setId(IsMstuserportfolioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

    
    @Column(name="NUMTOTALHOLDING", precision=20, scale=6)
    public BigDecimal getNumtotalholding() {
        return this.numtotalholding;
    }
    
    public void setNumtotalholding(BigDecimal numtotalholding) {
        this.numtotalholding = numtotalholding;
    }

    
    @Column(name="NUMHOLDINGOUTSIDELOCKIN", precision=20, scale=6)
    public BigDecimal getNumholdingoutsidelockin() {
        return this.numholdingoutsidelockin;
    }
    
    public void setNumholdingoutsidelockin(BigDecimal numholdingoutsidelockin) {
        this.numholdingoutsidelockin = numholdingoutsidelockin;
    }

    
    @Column(name="VALINFUNDCURR", precision=20, scale=6)
    public BigDecimal getValinfundcurr() {
        return this.valinfundcurr;
    }
    
    public void setValinfundcurr(BigDecimal valinfundcurr) {
        this.valinfundcurr = valinfundcurr;
    }

    
    @Column(name="VALINUHCCY", precision=20, scale=6)
    public BigDecimal getValinuhccy() {
        return this.valinuhccy;
    }
    
    public void setValinuhccy(BigDecimal valinuhccy) {
        this.valinuhccy = valinuhccy;
    }

    
    @Column(name="UHCCY", length=3)
    public String getUhccy() {
        return this.uhccy;
    }
    
    public void setUhccy(String uhccy) {
        this.uhccy = uhccy;
    }

    
    @Column(name="BLOCKEDUNITS", precision=20, scale=6)
    public BigDecimal getBlockedunits() {
        return this.blockedunits;
    }
    
    public void setBlockedunits(BigDecimal blockedunits) {
        this.blockedunits = blockedunits;
    }

    
    @Column(name="PROVISIONALUNITS", precision=20, scale=6)
    public BigDecimal getProvisionalunits() {
        return this.provisionalunits;
    }
    
    public void setProvisionalunits(BigDecimal provisionalunits) {
        this.provisionalunits = provisionalunits;
    }

    
    @Column(name="ISSUEDBAL", precision=20, scale=6)
    public BigDecimal getIssuedbal() {
        return this.issuedbal;
    }
    
    public void setIssuedbal(BigDecimal issuedbal) {
        this.issuedbal = issuedbal;
    }

    
    @Column(name="UNISSUEDBAL", precision=20, scale=6)
    public BigDecimal getUnissuedbal() {
        return this.unissuedbal;
    }
    
    public void setUnissuedbal(BigDecimal unissuedbal) {
        this.unissuedbal = unissuedbal;
    }

    
    @Column(name="SELLABLEUNITS", precision=20, scale=6)
    public BigDecimal getSellableunits() {
        return this.sellableunits;
    }
    
    public void setSellableunits(BigDecimal sellableunits) {
        this.sellableunits = sellableunits;
    }

    
    @Column(name="CURRENTNAV", precision=18, scale=6)
    public BigDecimal getCurrentnav() {
        return this.currentnav;
    }
    
    public void setCurrentnav(BigDecimal currentnav) {
        this.currentnav = currentnav;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }




}


