package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsMstfundtpr generated by hbm2java
 */
@Entity
@Table(name="IS_MSTFUNDTPR"
    ,schema="FCDBADMIN_RK"
)
public class IsMstfundtpr  implements java.io.Serializable {


     private IsMstfundtprId id;
     private IsMstfund isMstfund;
     private Long numseq;
     private Character grossamt;
     private Character grossunit;
     private Character netamt;
     private Character netunit;
     private BigDecimal minsitxnamt;
     private BigDecimal maxsitxnamt;
     private Long minsitxnunits;
     private Long maxsitxnunits;
     private Long paymentlag;
     private Character flgtxnsuspended;
     private Long minsiholdingamt;
     private Long minsiholdingunit;
     private Long minsiholdingapplyfor;
     private Long minsiholdindicator;
     private String txndescription;
     private String txnsigenday;
     private String txnsifrequency;
     private Character txnsigencycle;
     private Character txnenforcesi;

    public IsMstfundtpr() {
    }

	
    public IsMstfundtpr(IsMstfundtprId id, IsMstfund isMstfund) {
        this.id = id;
        this.isMstfund = isMstfund;
    }
    public IsMstfundtpr(IsMstfundtprId id, IsMstfund isMstfund, Long numseq, Character grossamt, Character grossunit, Character netamt, Character netunit, BigDecimal minsitxnamt, BigDecimal maxsitxnamt, Long minsitxnunits, Long maxsitxnunits, Long paymentlag, Character flgtxnsuspended, Long minsiholdingamt, Long minsiholdingunit, Long minsiholdingapplyfor, Long minsiholdindicator, String txndescription, String txnsigenday, String txnsifrequency, Character txnsigencycle, Character txnenforcesi) {
       this.id = id;
       this.isMstfund = isMstfund;
       this.numseq = numseq;
       this.grossamt = grossamt;
       this.grossunit = grossunit;
       this.netamt = netamt;
       this.netunit = netunit;
       this.minsitxnamt = minsitxnamt;
       this.maxsitxnamt = maxsitxnamt;
       this.minsitxnunits = minsitxnunits;
       this.maxsitxnunits = maxsitxnunits;
       this.paymentlag = paymentlag;
       this.flgtxnsuspended = flgtxnsuspended;
       this.minsiholdingamt = minsiholdingamt;
       this.minsiholdingunit = minsiholdingunit;
       this.minsiholdingapplyfor = minsiholdingapplyfor;
       this.minsiholdindicator = minsiholdindicator;
       this.txndescription = txndescription;
       this.txnsigenday = txnsigenday;
       this.txnsifrequency = txnsifrequency;
       this.txnsigencycle = txnsigencycle;
       this.txnenforcesi = txnenforcesi;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ), 
        @AttributeOverride(name="txntype", column=@Column(name="TXNTYPE", nullable=false, length=10) ) } )
    public IsMstfundtprId getId() {
        return this.id;
    }
    
    public void setId(IsMstfundtprId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDFUND", referencedColumnName="IDFUND", nullable=false, insertable=false, updatable=false) } )
    public IsMstfund getIsMstfund() {
        return this.isMstfund;
    }
    
    public void setIsMstfund(IsMstfund isMstfund) {
        this.isMstfund = isMstfund;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }

    
    @Column(name="GROSSAMT", length=1)
    public Character getGrossamt() {
        return this.grossamt;
    }
    
    public void setGrossamt(Character grossamt) {
        this.grossamt = grossamt;
    }

    
    @Column(name="GROSSUNIT", length=1)
    public Character getGrossunit() {
        return this.grossunit;
    }
    
    public void setGrossunit(Character grossunit) {
        this.grossunit = grossunit;
    }

    
    @Column(name="NETAMT", length=1)
    public Character getNetamt() {
        return this.netamt;
    }
    
    public void setNetamt(Character netamt) {
        this.netamt = netamt;
    }

    
    @Column(name="NETUNIT", length=1)
    public Character getNetunit() {
        return this.netunit;
    }
    
    public void setNetunit(Character netunit) {
        this.netunit = netunit;
    }

    
    @Column(name="MINSITXNAMT", precision=18, scale=3)
    public BigDecimal getMinsitxnamt() {
        return this.minsitxnamt;
    }
    
    public void setMinsitxnamt(BigDecimal minsitxnamt) {
        this.minsitxnamt = minsitxnamt;
    }

    
    @Column(name="MAXSITXNAMT", precision=18, scale=3)
    public BigDecimal getMaxsitxnamt() {
        return this.maxsitxnamt;
    }
    
    public void setMaxsitxnamt(BigDecimal maxsitxnamt) {
        this.maxsitxnamt = maxsitxnamt;
    }

    
    @Column(name="MINSITXNUNITS", precision=18, scale=0)
    public Long getMinsitxnunits() {
        return this.minsitxnunits;
    }
    
    public void setMinsitxnunits(Long minsitxnunits) {
        this.minsitxnunits = minsitxnunits;
    }

    
    @Column(name="MAXSITXNUNITS", precision=18, scale=0)
    public Long getMaxsitxnunits() {
        return this.maxsitxnunits;
    }
    
    public void setMaxsitxnunits(Long maxsitxnunits) {
        this.maxsitxnunits = maxsitxnunits;
    }

    
    @Column(name="PAYMENTLAG", precision=18, scale=0)
    public Long getPaymentlag() {
        return this.paymentlag;
    }
    
    public void setPaymentlag(Long paymentlag) {
        this.paymentlag = paymentlag;
    }

    
    @Column(name="FLGTXNSUSPENDED", length=1)
    public Character getFlgtxnsuspended() {
        return this.flgtxnsuspended;
    }
    
    public void setFlgtxnsuspended(Character flgtxnsuspended) {
        this.flgtxnsuspended = flgtxnsuspended;
    }

    
    @Column(name="MINSIHOLDINGAMT", precision=18, scale=0)
    public Long getMinsiholdingamt() {
        return this.minsiholdingamt;
    }
    
    public void setMinsiholdingamt(Long minsiholdingamt) {
        this.minsiholdingamt = minsiholdingamt;
    }

    
    @Column(name="MINSIHOLDINGUNIT", precision=18, scale=0)
    public Long getMinsiholdingunit() {
        return this.minsiholdingunit;
    }
    
    public void setMinsiholdingunit(Long minsiholdingunit) {
        this.minsiholdingunit = minsiholdingunit;
    }

    
    @Column(name="MINSIHOLDINGAPPLYFOR", precision=18, scale=0)
    public Long getMinsiholdingapplyfor() {
        return this.minsiholdingapplyfor;
    }
    
    public void setMinsiholdingapplyfor(Long minsiholdingapplyfor) {
        this.minsiholdingapplyfor = minsiholdingapplyfor;
    }

    
    @Column(name="MINSIHOLDINDICATOR", precision=18, scale=0)
    public Long getMinsiholdindicator() {
        return this.minsiholdindicator;
    }
    
    public void setMinsiholdindicator(Long minsiholdindicator) {
        this.minsiholdindicator = minsiholdindicator;
    }

    
    @Column(name="TXNDESCRIPTION")
    public String getTxndescription() {
        return this.txndescription;
    }
    
    public void setTxndescription(String txndescription) {
        this.txndescription = txndescription;
    }

    
    @Column(name="TXNSIGENDAY", length=15)
    public String getTxnsigenday() {
        return this.txnsigenday;
    }
    
    public void setTxnsigenday(String txnsigenday) {
        this.txnsigenday = txnsigenday;
    }

    
    @Column(name="TXNSIFREQUENCY", length=15)
    public String getTxnsifrequency() {
        return this.txnsifrequency;
    }
    
    public void setTxnsifrequency(String txnsifrequency) {
        this.txnsifrequency = txnsifrequency;
    }

    
    @Column(name="TXNSIGENCYCLE", length=1)
    public Character getTxnsigencycle() {
        return this.txnsigencycle;
    }
    
    public void setTxnsigencycle(Character txnsigencycle) {
        this.txnsigencycle = txnsigencycle;
    }

    
    @Column(name="TXNENFORCESI", length=1)
    public Character getTxnenforcesi() {
        return this.txnenforcesi;
    }
    
    public void setTxnenforcesi(Character txnenforcesi) {
        this.txnenforcesi = txnenforcesi;
    }




}


