package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsMstfundcurr generated by hbm2java
 */
@Entity
@Table(name="IS_MSTFUNDCURR"
    ,schema="FCDBADMIN_RK"
)
public class IsMstfundcurr  implements java.io.Serializable {


     private IsMstfundcurrId id;
     private IsMstfund isMstfund;
     private Long numseq;

    public IsMstfundcurr() {
    }

	
    public IsMstfundcurr(IsMstfundcurrId id, IsMstfund isMstfund) {
        this.id = id;
        this.isMstfund = isMstfund;
    }
    public IsMstfundcurr(IsMstfundcurrId id, IsMstfund isMstfund, Long numseq) {
       this.id = id;
       this.isMstfund = isMstfund;
       this.numseq = numseq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ), 
        @AttributeOverride(name="codcurrtxn", column=@Column(name="CODCURRTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="txntype", column=@Column(name="TXNTYPE", nullable=false, length=10) ) } )
    public IsMstfundcurrId getId() {
        return this.id;
    }
    
    public void setId(IsMstfundcurrId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDFUND", referencedColumnName="IDFUND", nullable=false, insertable=false, updatable=false) } )
    public IsMstfund getIsMstfund() {
        return this.isMstfund;
    }
    
    public void setIsMstfund(IsMstfund isMstfund) {
        this.isMstfund = isMstfund;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }




}


