package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IsOrderstatusinquirydetails generated by hbm2java
 */
@Entity
@Table(name="IS_ORDERSTATUSINQUIRYDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class IsOrderstatusinquirydetails  implements java.io.Serializable {


     private IsOrderstatusinquirydetailsId id;
     private Mstentity mstentity;
     private IsCustUhMap isCustUhMap;
     private String txnrefnumber;
     private String toiduh;
     private String fundbasecurr;
     private Date txndate;
     private String codtxn;
     private String txnsubtype;
     private String namfundshort;
     private String namfundfull;
     private String txnmode;
     private BigDecimal txnccyamt;
     private String codcurrtxn;
     private String status;
     private Date datealloted;
     private BigDecimal exchangerate;
     private BigDecimal amtinmfcurr;
     private String txnunits;
     private BigDecimal unitpriceinmfcurr;
     private BigDecimal loadinmfcurr;
     private BigDecimal taxinmfcurr;
     private BigDecimal netamtinmfcurr;
     private BigDecimal netamtintrancurr;
     private String reason;
     private Long percentapplied;
     private String loiapplicability;
     private String flgcompleted;
     private String transbranchcode;
     private String transaccno;
     private String transacctype;
     private String transrefno;
     private String transacccurr;
     private String accholdername;
     private String tprefno;
     private String tpaddress1;
     private String tpaddress2;
     private String tpaddress3;
     private String tpzip;
     private String tpstate;
     private String tpusstate;
     private String tpcountry;
     private String tpbicode;
     private String deliveryoption;
     private String deliverytype;
     private String paymentmode;
     private String subpaymentmode;
     private String chequeno;
     private String chequedate;
     private String clearingdate;
     private String draweebankid;
     private Character paytype;
     private Long numseq;
     private String makerid;
     private Date settlementdate;

    public IsOrderstatusinquirydetails() {
    }

	
    public IsOrderstatusinquirydetails(IsOrderstatusinquirydetailsId id, Mstentity mstentity, IsCustUhMap isCustUhMap) {
        this.id = id;
        this.mstentity = mstentity;
        this.isCustUhMap = isCustUhMap;
    }
    public IsOrderstatusinquirydetails(IsOrderstatusinquirydetailsId id, Mstentity mstentity, IsCustUhMap isCustUhMap, String txnrefnumber, String toiduh, String fundbasecurr, Date txndate, String codtxn, String txnsubtype, String namfundshort, String namfundfull, String txnmode, BigDecimal txnccyamt, String codcurrtxn, String status, Date datealloted, BigDecimal exchangerate, BigDecimal amtinmfcurr, String txnunits, BigDecimal unitpriceinmfcurr, BigDecimal loadinmfcurr, BigDecimal taxinmfcurr, BigDecimal netamtinmfcurr, BigDecimal netamtintrancurr, String reason, Long percentapplied, String loiapplicability, String flgcompleted, String transbranchcode, String transaccno, String transacctype, String transrefno, String transacccurr, String accholdername, String tprefno, String tpaddress1, String tpaddress2, String tpaddress3, String tpzip, String tpstate, String tpusstate, String tpcountry, String tpbicode, String deliveryoption, String deliverytype, String paymentmode, String subpaymentmode, String chequeno, String chequedate, String clearingdate, String draweebankid, Character paytype, Long numseq, String makerid, Date settlementdate) {
       this.id = id;
       this.mstentity = mstentity;
       this.isCustUhMap = isCustUhMap;
       this.txnrefnumber = txnrefnumber;
       this.toiduh = toiduh;
       this.fundbasecurr = fundbasecurr;
       this.txndate = txndate;
       this.codtxn = codtxn;
       this.txnsubtype = txnsubtype;
       this.namfundshort = namfundshort;
       this.namfundfull = namfundfull;
       this.txnmode = txnmode;
       this.txnccyamt = txnccyamt;
       this.codcurrtxn = codcurrtxn;
       this.status = status;
       this.datealloted = datealloted;
       this.exchangerate = exchangerate;
       this.amtinmfcurr = amtinmfcurr;
       this.txnunits = txnunits;
       this.unitpriceinmfcurr = unitpriceinmfcurr;
       this.loadinmfcurr = loadinmfcurr;
       this.taxinmfcurr = taxinmfcurr;
       this.netamtinmfcurr = netamtinmfcurr;
       this.netamtintrancurr = netamtintrancurr;
       this.reason = reason;
       this.percentapplied = percentapplied;
       this.loiapplicability = loiapplicability;
       this.flgcompleted = flgcompleted;
       this.transbranchcode = transbranchcode;
       this.transaccno = transaccno;
       this.transacctype = transacctype;
       this.transrefno = transrefno;
       this.transacccurr = transacccurr;
       this.accholdername = accholdername;
       this.tprefno = tprefno;
       this.tpaddress1 = tpaddress1;
       this.tpaddress2 = tpaddress2;
       this.tpaddress3 = tpaddress3;
       this.tpzip = tpzip;
       this.tpstate = tpstate;
       this.tpusstate = tpusstate;
       this.tpcountry = tpcountry;
       this.tpbicode = tpbicode;
       this.deliveryoption = deliveryoption;
       this.deliverytype = deliverytype;
       this.paymentmode = paymentmode;
       this.subpaymentmode = subpaymentmode;
       this.chequeno = chequeno;
       this.chequedate = chequedate;
       this.clearingdate = clearingdate;
       this.draweebankid = draweebankid;
       this.paytype = paytype;
       this.numseq = numseq;
       this.makerid = makerid;
       this.settlementdate = settlementdate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="txnnumber", column=@Column(name="TXNNUMBER", nullable=false, length=25) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false) ), 
        @AttributeOverride(name="iduh", column=@Column(name="IDUH", nullable=false, length=16) ) } )
    public IsOrderstatusinquirydetailsId getId() {
        return this.id;
    }
    
    public void setId(IsOrderstatusinquirydetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDCUST", referencedColumnName="IDCUST", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDUH", referencedColumnName="IDUH", nullable=false, insertable=false, updatable=false) } )
    public IsCustUhMap getIsCustUhMap() {
        return this.isCustUhMap;
    }
    
    public void setIsCustUhMap(IsCustUhMap isCustUhMap) {
        this.isCustUhMap = isCustUhMap;
    }

    
    @Column(name="TXNREFNUMBER", length=25)
    public String getTxnrefnumber() {
        return this.txnrefnumber;
    }
    
    public void setTxnrefnumber(String txnrefnumber) {
        this.txnrefnumber = txnrefnumber;
    }

    
    @Column(name="TOIDUH", length=16)
    public String getToiduh() {
        return this.toiduh;
    }
    
    public void setToiduh(String toiduh) {
        this.toiduh = toiduh;
    }

    
    @Column(name="FUNDBASECURR", length=3)
    public String getFundbasecurr() {
        return this.fundbasecurr;
    }
    
    public void setFundbasecurr(String fundbasecurr) {
        this.fundbasecurr = fundbasecurr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TXNDATE", length=7)
    public Date getTxndate() {
        return this.txndate;
    }
    
    public void setTxndate(Date txndate) {
        this.txndate = txndate;
    }

    
    @Column(name="CODTXN", length=15)
    public String getCodtxn() {
        return this.codtxn;
    }
    
    public void setCodtxn(String codtxn) {
        this.codtxn = codtxn;
    }

    
    @Column(name="TXNSUBTYPE", length=15)
    public String getTxnsubtype() {
        return this.txnsubtype;
    }
    
    public void setTxnsubtype(String txnsubtype) {
        this.txnsubtype = txnsubtype;
    }

    
    @Column(name="NAMFUNDSHORT", length=50)
    public String getNamfundshort() {
        return this.namfundshort;
    }
    
    public void setNamfundshort(String namfundshort) {
        this.namfundshort = namfundshort;
    }

    
    @Column(name="NAMFUNDFULL", length=100)
    public String getNamfundfull() {
        return this.namfundfull;
    }
    
    public void setNamfundfull(String namfundfull) {
        this.namfundfull = namfundfull;
    }

    
    @Column(name="TXNMODE", length=4)
    public String getTxnmode() {
        return this.txnmode;
    }
    
    public void setTxnmode(String txnmode) {
        this.txnmode = txnmode;
    }

    
    @Column(name="TXNCCYAMT", precision=20, scale=6)
    public BigDecimal getTxnccyamt() {
        return this.txnccyamt;
    }
    
    public void setTxnccyamt(BigDecimal txnccyamt) {
        this.txnccyamt = txnccyamt;
    }

    
    @Column(name="CODCURRTXN", length=3)
    public String getCodcurrtxn() {
        return this.codcurrtxn;
    }
    
    public void setCodcurrtxn(String codcurrtxn) {
        this.codcurrtxn = codcurrtxn;
    }

    
    @Column(name="STATUS", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEALLOTED", length=7)
    public Date getDatealloted() {
        return this.datealloted;
    }
    
    public void setDatealloted(Date datealloted) {
        this.datealloted = datealloted;
    }

    
    @Column(name="EXCHANGERATE", precision=20, scale=6)
    public BigDecimal getExchangerate() {
        return this.exchangerate;
    }
    
    public void setExchangerate(BigDecimal exchangerate) {
        this.exchangerate = exchangerate;
    }

    
    @Column(name="AMTINMFCURR", precision=20, scale=6)
    public BigDecimal getAmtinmfcurr() {
        return this.amtinmfcurr;
    }
    
    public void setAmtinmfcurr(BigDecimal amtinmfcurr) {
        this.amtinmfcurr = amtinmfcurr;
    }

    
    @Column(name="TXNUNITS", length=10)
    public String getTxnunits() {
        return this.txnunits;
    }
    
    public void setTxnunits(String txnunits) {
        this.txnunits = txnunits;
    }

    
    @Column(name="UNITPRICEINMFCURR", precision=20, scale=6)
    public BigDecimal getUnitpriceinmfcurr() {
        return this.unitpriceinmfcurr;
    }
    
    public void setUnitpriceinmfcurr(BigDecimal unitpriceinmfcurr) {
        this.unitpriceinmfcurr = unitpriceinmfcurr;
    }

    
    @Column(name="LOADINMFCURR", precision=20, scale=6)
    public BigDecimal getLoadinmfcurr() {
        return this.loadinmfcurr;
    }
    
    public void setLoadinmfcurr(BigDecimal loadinmfcurr) {
        this.loadinmfcurr = loadinmfcurr;
    }

    
    @Column(name="TAXINMFCURR", precision=20, scale=6)
    public BigDecimal getTaxinmfcurr() {
        return this.taxinmfcurr;
    }
    
    public void setTaxinmfcurr(BigDecimal taxinmfcurr) {
        this.taxinmfcurr = taxinmfcurr;
    }

    
    @Column(name="NETAMTINMFCURR", precision=20, scale=6)
    public BigDecimal getNetamtinmfcurr() {
        return this.netamtinmfcurr;
    }
    
    public void setNetamtinmfcurr(BigDecimal netamtinmfcurr) {
        this.netamtinmfcurr = netamtinmfcurr;
    }

    
    @Column(name="NETAMTINTRANCURR", precision=20, scale=6)
    public BigDecimal getNetamtintrancurr() {
        return this.netamtintrancurr;
    }
    
    public void setNetamtintrancurr(BigDecimal netamtintrancurr) {
        this.netamtintrancurr = netamtintrancurr;
    }

    
    @Column(name="REASON", length=10)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="PERCENTAPPLIED", precision=18, scale=0)
    public Long getPercentapplied() {
        return this.percentapplied;
    }
    
    public void setPercentapplied(Long percentapplied) {
        this.percentapplied = percentapplied;
    }

    
    @Column(name="LOIAPPLICABILITY", length=10)
    public String getLoiapplicability() {
        return this.loiapplicability;
    }
    
    public void setLoiapplicability(String loiapplicability) {
        this.loiapplicability = loiapplicability;
    }

    
    @Column(name="FLGCOMPLETED", length=10)
    public String getFlgcompleted() {
        return this.flgcompleted;
    }
    
    public void setFlgcompleted(String flgcompleted) {
        this.flgcompleted = flgcompleted;
    }

    
    @Column(name="TRANSBRANCHCODE", length=25)
    public String getTransbranchcode() {
        return this.transbranchcode;
    }
    
    public void setTransbranchcode(String transbranchcode) {
        this.transbranchcode = transbranchcode;
    }

    
    @Column(name="TRANSACCNO", length=20)
    public String getTransaccno() {
        return this.transaccno;
    }
    
    public void setTransaccno(String transaccno) {
        this.transaccno = transaccno;
    }

    
    @Column(name="TRANSACCTYPE", length=25)
    public String getTransacctype() {
        return this.transacctype;
    }
    
    public void setTransacctype(String transacctype) {
        this.transacctype = transacctype;
    }

    
    @Column(name="TRANSREFNO", length=25)
    public String getTransrefno() {
        return this.transrefno;
    }
    
    public void setTransrefno(String transrefno) {
        this.transrefno = transrefno;
    }

    
    @Column(name="TRANSACCCURR", length=3)
    public String getTransacccurr() {
        return this.transacccurr;
    }
    
    public void setTransacccurr(String transacccurr) {
        this.transacccurr = transacccurr;
    }

    
    @Column(name="ACCHOLDERNAME", length=50)
    public String getAccholdername() {
        return this.accholdername;
    }
    
    public void setAccholdername(String accholdername) {
        this.accholdername = accholdername;
    }

    
    @Column(name="TPREFNO")
    public String getTprefno() {
        return this.tprefno;
    }
    
    public void setTprefno(String tprefno) {
        this.tprefno = tprefno;
    }

    
    @Column(name="TPADDRESS1", length=50)
    public String getTpaddress1() {
        return this.tpaddress1;
    }
    
    public void setTpaddress1(String tpaddress1) {
        this.tpaddress1 = tpaddress1;
    }

    
    @Column(name="TPADDRESS2", length=50)
    public String getTpaddress2() {
        return this.tpaddress2;
    }
    
    public void setTpaddress2(String tpaddress2) {
        this.tpaddress2 = tpaddress2;
    }

    
    @Column(name="TPADDRESS3", length=50)
    public String getTpaddress3() {
        return this.tpaddress3;
    }
    
    public void setTpaddress3(String tpaddress3) {
        this.tpaddress3 = tpaddress3;
    }

    
    @Column(name="TPZIP", length=10)
    public String getTpzip() {
        return this.tpzip;
    }
    
    public void setTpzip(String tpzip) {
        this.tpzip = tpzip;
    }

    
    @Column(name="TPSTATE", length=25)
    public String getTpstate() {
        return this.tpstate;
    }
    
    public void setTpstate(String tpstate) {
        this.tpstate = tpstate;
    }

    
    @Column(name="TPUSSTATE", length=25)
    public String getTpusstate() {
        return this.tpusstate;
    }
    
    public void setTpusstate(String tpusstate) {
        this.tpusstate = tpusstate;
    }

    
    @Column(name="TPCOUNTRY", length=25)
    public String getTpcountry() {
        return this.tpcountry;
    }
    
    public void setTpcountry(String tpcountry) {
        this.tpcountry = tpcountry;
    }

    
    @Column(name="TPBICODE", length=20)
    public String getTpbicode() {
        return this.tpbicode;
    }
    
    public void setTpbicode(String tpbicode) {
        this.tpbicode = tpbicode;
    }

    
    @Column(name="DELIVERYOPTION", length=15)
    public String getDeliveryoption() {
        return this.deliveryoption;
    }
    
    public void setDeliveryoption(String deliveryoption) {
        this.deliveryoption = deliveryoption;
    }

    
    @Column(name="DELIVERYTYPE", length=15)
    public String getDeliverytype() {
        return this.deliverytype;
    }
    
    public void setDeliverytype(String deliverytype) {
        this.deliverytype = deliverytype;
    }

    
    @Column(name="PAYMENTMODE", length=15)
    public String getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(String paymentmode) {
        this.paymentmode = paymentmode;
    }

    
    @Column(name="SUBPAYMENTMODE", length=15)
    public String getSubpaymentmode() {
        return this.subpaymentmode;
    }
    
    public void setSubpaymentmode(String subpaymentmode) {
        this.subpaymentmode = subpaymentmode;
    }

    
    @Column(name="CHEQUENO", length=16)
    public String getChequeno() {
        return this.chequeno;
    }
    
    public void setChequeno(String chequeno) {
        this.chequeno = chequeno;
    }

    
    @Column(name="CHEQUEDATE", length=10)
    public String getChequedate() {
        return this.chequedate;
    }
    
    public void setChequedate(String chequedate) {
        this.chequedate = chequedate;
    }

    
    @Column(name="CLEARINGDATE", length=10)
    public String getClearingdate() {
        return this.clearingdate;
    }
    
    public void setClearingdate(String clearingdate) {
        this.clearingdate = clearingdate;
    }

    
    @Column(name="DRAWEEBANKID", length=25)
    public String getDraweebankid() {
        return this.draweebankid;
    }
    
    public void setDraweebankid(String draweebankid) {
        this.draweebankid = draweebankid;
    }

    
    @Column(name="PAYTYPE", length=1)
    public Character getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(Character paytype) {
        this.paytype = paytype;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }

    
    @Column(name="MAKERID", length=30)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SETTLEMENTDATE", length=7)
    public Date getSettlementdate() {
        return this.settlementdate;
    }
    
    public void setSettlementdate(Date settlementdate) {
        this.settlementdate = settlementdate;
    }




}


