package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mailmessageattach generated by hbm2java
 */
@Entity
@Table(name="MAILMESSAGEATTACH"
    ,schema="FCDBADMIN_RK"
)
public class Mailmessageattach  implements java.io.Serializable {


     private MailmessageattachId id;
     private FcatTCommunications fcatTCommunications;
     private String filename;
     private Blob filecontent;
     private String contenttype;
     private BigDecimal filesize;
     private String iscompressed;

    public Mailmessageattach() {
    }

	
    public Mailmessageattach(MailmessageattachId id, FcatTCommunications fcatTCommunications) {
        this.id = id;
        this.fcatTCommunications = fcatTCommunications;
    }
    public Mailmessageattach(MailmessageattachId id, FcatTCommunications fcatTCommunications, String filename, Blob filecontent, String contenttype, BigDecimal filesize, String iscompressed) {
       this.id = id;
       this.fcatTCommunications = fcatTCommunications;
       this.filename = filename;
       this.filecontent = filecontent;
       this.contenttype = contenttype;
       this.filesize = filesize;
       this.iscompressed = iscompressed;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idmessage", column=@Column(name="IDMESSAGE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="filerefno", column=@Column(name="FILEREFNO", nullable=false, length=35) ) } )
    public MailmessageattachId getId() {
        return this.id;
    }
    
    public void setId(MailmessageattachId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMESSAGE", nullable=false, insertable=false, updatable=false)
    public FcatTCommunications getFcatTCommunications() {
        return this.fcatTCommunications;
    }
    
    public void setFcatTCommunications(FcatTCommunications fcatTCommunications) {
        this.fcatTCommunications = fcatTCommunications;
    }

    
    @Column(name="FILENAME")
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="FILECONTENT")
    public Blob getFilecontent() {
        return this.filecontent;
    }
    
    public void setFilecontent(Blob filecontent) {
        this.filecontent = filecontent;
    }

    
    @Column(name="CONTENTTYPE", length=100)
    public String getContenttype() {
        return this.contenttype;
    }
    
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype;
    }

    
    @Column(name="FILESIZE", precision=22, scale=0)
    public BigDecimal getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(BigDecimal filesize) {
        this.filesize = filesize;
    }

    
    @Column(name="ISCOMPRESSED", length=1)
    public String getIscompressed() {
        return this.iscompressed;
    }
    
    public void setIscompressed(String iscompressed) {
        this.iscompressed = iscompressed;
    }




}


