package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Mobileenablertxnlist generated by hbm2java
 */
@Entity
@Table(name="MOBILEENABLERTXNLIST"
    ,schema="FCDBADMIN_RK"
)
public class Mobileenablertxnlist  implements java.io.Serializable {


     private MobileenablertxnlistId id;
     private Mstusertypetxn mstusertypetxn;
     private String tgtappidtxn;
     private String tgtidchannel;
     private String isenabled;
     private String txndescription;
     private Set<Mobileenablerfieldmap> mobileenablerfieldmaps = new HashSet<Mobileenablerfieldmap>(0);

    public Mobileenablertxnlist() {
    }

	
    public Mobileenablertxnlist(Mstusertypetxn mstusertypetxn) {
        this.mstusertypetxn = mstusertypetxn;
    }
    public Mobileenablertxnlist(Mstusertypetxn mstusertypetxn, String tgtappidtxn, String tgtidchannel, String isenabled, String txndescription, Set<Mobileenablerfieldmap> mobileenablerfieldmaps) {
       this.mstusertypetxn = mstusertypetxn;
       this.tgtappidtxn = tgtappidtxn;
       this.tgtidchannel = tgtidchannel;
       this.isenabled = isenabled;
       this.txndescription = txndescription;
       this.mobileenablerfieldmaps = mobileenablerfieldmaps;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="fcdbidchannel", column=@Column(name="FCDBIDCHANNEL", nullable=false, length=3) ), 
        @AttributeOverride(name="fcdbidtxn", column=@Column(name="FCDBIDTXN", nullable=false, length=3) ) } )
    public MobileenablertxnlistId getId() {
        return this.id;
    }
    
    public void setId(MobileenablertxnlistId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Mstusertypetxn getMstusertypetxn() {
        return this.mstusertypetxn;
    }
    
    public void setMstusertypetxn(Mstusertypetxn mstusertypetxn) {
        this.mstusertypetxn = mstusertypetxn;
    }

    
    @Column(name="TGTAPPIDTXN", length=3)
    public String getTgtappidtxn() {
        return this.tgtappidtxn;
    }
    
    public void setTgtappidtxn(String tgtappidtxn) {
        this.tgtappidtxn = tgtappidtxn;
    }

    
    @Column(name="TGTIDCHANNEL", length=2)
    public String getTgtidchannel() {
        return this.tgtidchannel;
    }
    
    public void setTgtidchannel(String tgtidchannel) {
        this.tgtidchannel = tgtidchannel;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="TXNDESCRIPTION", length=100)
    public String getTxndescription() {
        return this.txndescription;
    }
    
    public void setTxndescription(String txndescription) {
        this.txndescription = txndescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mobileenablertxnlist")
    public Set<Mobileenablerfieldmap> getMobileenablerfieldmaps() {
        return this.mobileenablerfieldmaps;
    }
    
    public void setMobileenablerfieldmaps(Set<Mobileenablerfieldmap> mobileenablerfieldmaps) {
        this.mobileenablerfieldmaps = mobileenablerfieldmaps;
    }




}


