package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mobileenablerfieldmap generated by hbm2java
 */
@Entity
@Table(name="MOBILEENABLERFIELDMAP"
    ,schema="FCDBADMIN_RK"
)
public class Mobileenablerfieldmap  implements java.io.Serializable {


     private MobileenablerfieldmapId id;
     private Mstentityuserchannel mstentityuserchannel;
     private Mobileenablertxnlist mobileenablertxnlist;
     private String fcdbfieldname;
     private String tgtfielddefaultvalue;

    public Mobileenablerfieldmap() {
    }

	
    public Mobileenablerfieldmap(MobileenablerfieldmapId id, Mstentityuserchannel mstentityuserchannel, Mobileenablertxnlist mobileenablertxnlist) {
        this.id = id;
        this.mstentityuserchannel = mstentityuserchannel;
        this.mobileenablertxnlist = mobileenablertxnlist;
    }
    public Mobileenablerfieldmap(MobileenablerfieldmapId id, Mstentityuserchannel mstentityuserchannel, Mobileenablertxnlist mobileenablertxnlist, String fcdbfieldname, String tgtfielddefaultvalue) {
       this.id = id;
       this.mstentityuserchannel = mstentityuserchannel;
       this.mobileenablertxnlist = mobileenablertxnlist;
       this.fcdbfieldname = fcdbfieldname;
       this.tgtfielddefaultvalue = tgtfielddefaultvalue;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="fcdbidtxn", column=@Column(name="FCDBIDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="fcdbidrequest", column=@Column(name="FCDBIDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=50) ), 
        @AttributeOverride(name="tgtappfieldname", column=@Column(name="TGTAPPFIELDNAME", nullable=false, length=100) ) } )
    public MobileenablerfieldmapId getId() {
        return this.id;
    }
    
    public void setId(MobileenablerfieldmapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="USERTYPE", referencedColumnName="TYPEUSER", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDCHANNEL", referencedColumnName="IDCHANNEL", nullable=false, insertable=false, updatable=false) } )
    public Mstentityuserchannel getMstentityuserchannel() {
        return this.mstentityuserchannel;
    }
    
    public void setMstentityuserchannel(Mstentityuserchannel mstentityuserchannel) {
        this.mstentityuserchannel = mstentityuserchannel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="USERTYPE", referencedColumnName="USERTYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDCHANNEL", referencedColumnName="FCDBIDCHANNEL", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FCDBIDTXN", referencedColumnName="FCDBIDTXN", nullable=false, insertable=false, updatable=false) } )
    public Mobileenablertxnlist getMobileenablertxnlist() {
        return this.mobileenablertxnlist;
    }
    
    public void setMobileenablertxnlist(Mobileenablertxnlist mobileenablertxnlist) {
        this.mobileenablertxnlist = mobileenablertxnlist;
    }

    
    @Column(name="FCDBFIELDNAME", length=100)
    public String getFcdbfieldname() {
        return this.fcdbfieldname;
    }
    
    public void setFcdbfieldname(String fcdbfieldname) {
        this.fcdbfieldname = fcdbfieldname;
    }

    
    @Column(name="TGTFIELDDEFAULTVALUE", length=100)
    public String getTgtfielddefaultvalue() {
        return this.tgtfielddefaultvalue;
    }
    
    public void setTgtfielddefaultvalue(String tgtfielddefaultvalue) {
        this.tgtfielddefaultvalue = tgtfielddefaultvalue;
    }




}


