package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mobileenablerreturncodemap generated by hbm2java
 */
@Entity
@Table(name="MOBILEENABLERRETURNCODEMAP"
    ,schema="FCDBADMIN_RK"
)
public class Mobileenablerreturncodemap  implements java.io.Serializable {


     private MobileenablerreturncodemapId id;
     private Mstentity mstentity;
     private Short fcdbreturncode;
     private String fcdbreturncodedesc;
     private String tgtappreturncodedesc;

    public Mobileenablerreturncodemap() {
    }

	
    public Mobileenablerreturncodemap(MobileenablerreturncodemapId id, Mstentity mstentity) {
        this.id = id;
        this.mstentity = mstentity;
    }
    public Mobileenablerreturncodemap(MobileenablerreturncodemapId id, Mstentity mstentity, Short fcdbreturncode, String fcdbreturncodedesc, String tgtappreturncodedesc) {
       this.id = id;
       this.mstentity = mstentity;
       this.fcdbreturncode = fcdbreturncode;
       this.fcdbreturncodedesc = fcdbreturncodedesc;
       this.tgtappreturncodedesc = tgtappreturncodedesc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="tgtappreturncode", column=@Column(name="TGTAPPRETURNCODE", nullable=false, precision=3, scale=0) ) } )
    public MobileenablerreturncodemapId getId() {
        return this.id;
    }
    
    public void setId(MobileenablerreturncodemapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

    
    @Column(name="FCDBRETURNCODE", precision=3, scale=0)
    public Short getFcdbreturncode() {
        return this.fcdbreturncode;
    }
    
    public void setFcdbreturncode(Short fcdbreturncode) {
        this.fcdbreturncode = fcdbreturncode;
    }

    
    @Column(name="FCDBRETURNCODEDESC", length=500)
    public String getFcdbreturncodedesc() {
        return this.fcdbreturncodedesc;
    }
    
    public void setFcdbreturncodedesc(String fcdbreturncodedesc) {
        this.fcdbreturncodedesc = fcdbreturncodedesc;
    }

    
    @Column(name="TGTAPPRETURNCODEDESC", length=500)
    public String getTgtappreturncodedesc() {
        return this.tgtappreturncodedesc;
    }
    
    public void setTgtappreturncodedesc(String tgtappreturncodedesc) {
        this.tgtappreturncodedesc = tgtappreturncodedesc;
    }




}


