package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstbiller generated by hbm2java
 */
@Entity
@Table(name="MSTBILLER"
    ,schema="FCDBADMIN_RK"
)
public class Mstbiller  implements java.io.Serializable {


     private MstbillerId id;
     private String billernickname;
     private Serializable registrationdate;
     private String billername;
     private String statbiller;
     private Serializable deletiondate;
     private String idEntity;
     private String refIdEntity;
     private String billercustid;

    public Mstbiller() {
    }

	
    public Mstbiller(MstbillerId id) {
        this.id = id;
    }
    public Mstbiller(MstbillerId id, String billernickname, Serializable registrationdate, String billername, String statbiller, Serializable deletiondate, String idEntity, String refIdEntity, String billercustid) {
       this.id = id;
       this.billernickname = billernickname;
       this.registrationdate = registrationdate;
       this.billername = billername;
       this.statbiller = statbiller;
       this.deletiondate = deletiondate;
       this.idEntity = idEntity;
       this.refIdEntity = refIdEntity;
       this.billercustid = billercustid;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=16) ), 
        @AttributeOverride(name="idbiller", column=@Column(name="IDBILLER", nullable=false, length=35) ), 
        @AttributeOverride(name="acctno", column=@Column(name="ACCTNO", nullable=false, length=20) ), 
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ) } )
    public MstbillerId getId() {
        return this.id;
    }
    
    public void setId(MstbillerId id) {
        this.id = id;
    }

    
    @Column(name="BILLERNICKNAME", length=20)
    public String getBillernickname() {
        return this.billernickname;
    }
    
    public void setBillernickname(String billernickname) {
        this.billernickname = billernickname;
    }

    
    @Column(name="REGISTRATIONDATE")
    public Serializable getRegistrationdate() {
        return this.registrationdate;
    }
    
    public void setRegistrationdate(Serializable registrationdate) {
        this.registrationdate = registrationdate;
    }

    
    @Column(name="BILLERNAME", length=200)
    public String getBillername() {
        return this.billername;
    }
    
    public void setBillername(String billername) {
        this.billername = billername;
    }

    
    @Column(name="STATBILLER", length=1)
    public String getStatbiller() {
        return this.statbiller;
    }
    
    public void setStatbiller(String statbiller) {
        this.statbiller = statbiller;
    }

    
    @Column(name="DELETIONDATE")
    public Serializable getDeletiondate() {
        return this.deletiondate;
    }
    
    public void setDeletiondate(Serializable deletiondate) {
        this.deletiondate = deletiondate;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="REF_ID_ENTITY", length=5)
    public String getRefIdEntity() {
        return this.refIdEntity;
    }
    
    public void setRefIdEntity(String refIdEntity) {
        this.refIdEntity = refIdEntity;
    }

    
    @Column(name="BILLERCUSTID", length=20)
    public String getBillercustid() {
        return this.billercustid;
    }
    
    public void setBillercustid(String billercustid) {
        this.billercustid = billercustid;
    }




}


