package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstbeneficiarytemplate generated by hbm2java
 */
@Entity
@Table(name="MSTBENEFICIARYTEMPLATE"
    ,schema="FCDBADMIN_RK"
)
public class Mstbeneficiarytemplate  implements java.io.Serializable {


     private MstbeneficiarytemplateId id;
     private Mstbeneficiary mstbeneficiary;
     private Blob templateData;
     private Date datCreation;
     private BigDecimal countUse;
     private Date datModified;
     private Date datLastInUsed;
     private BigDecimal stateBit;
     private String templateName;
     private Character templateType;
     private String beneAcctno;
     private String templateTxn;
     private String txncurrency;
     private BigDecimal fromamount;
     private BigDecimal toamount;
     private String idEntity;

    public Mstbeneficiarytemplate() {
    }

	
    public Mstbeneficiarytemplate(MstbeneficiarytemplateId id, Mstbeneficiary mstbeneficiary) {
        this.id = id;
        this.mstbeneficiary = mstbeneficiary;
    }
    public Mstbeneficiarytemplate(MstbeneficiarytemplateId id, Mstbeneficiary mstbeneficiary, Blob templateData, Date datCreation, BigDecimal countUse, Date datModified, Date datLastInUsed, BigDecimal stateBit, String templateName, Character templateType, String beneAcctno, String templateTxn, String txncurrency, BigDecimal fromamount, BigDecimal toamount, String idEntity) {
       this.id = id;
       this.mstbeneficiary = mstbeneficiary;
       this.templateData = templateData;
       this.datCreation = datCreation;
       this.countUse = countUse;
       this.datModified = datModified;
       this.datLastInUsed = datLastInUsed;
       this.stateBit = stateBit;
       this.templateName = templateName;
       this.templateType = templateType;
       this.beneAcctno = beneAcctno;
       this.templateTxn = templateTxn;
       this.txncurrency = txncurrency;
       this.fromamount = fromamount;
       this.toamount = toamount;
       this.idEntity = idEntity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="custId", column=@Column(name="CUST_ID", nullable=false, length=30) ), 
        @AttributeOverride(name="beneName", column=@Column(name="BENE_NAME", nullable=false, length=100) ), 
        @AttributeOverride(name="templateId", column=@Column(name="TEMPLATE_ID", nullable=false, precision=30, scale=0) ) } )
    public MstbeneficiarytemplateId getId() {
        return this.id;
    }
    
    public void setId(MstbeneficiarytemplateId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="USER_ID", referencedColumnName="USER_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="CUST_ID", referencedColumnName="CUST_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BENE_NAME", referencedColumnName="BENE_NAME", nullable=false, insertable=false, updatable=false) } )
    public Mstbeneficiary getMstbeneficiary() {
        return this.mstbeneficiary;
    }
    
    public void setMstbeneficiary(Mstbeneficiary mstbeneficiary) {
        this.mstbeneficiary = mstbeneficiary;
    }

    
    @Column(name="TEMPLATE_DATA")
    public Blob getTemplateData() {
        return this.templateData;
    }
    
    public void setTemplateData(Blob templateData) {
        this.templateData = templateData;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_CREATION", length=7)
    public Date getDatCreation() {
        return this.datCreation;
    }
    
    public void setDatCreation(Date datCreation) {
        this.datCreation = datCreation;
    }

    
    @Column(name="COUNT_USE", precision=30, scale=0)
    public BigDecimal getCountUse() {
        return this.countUse;
    }
    
    public void setCountUse(BigDecimal countUse) {
        this.countUse = countUse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_MODIFIED", length=7)
    public Date getDatModified() {
        return this.datModified;
    }
    
    public void setDatModified(Date datModified) {
        this.datModified = datModified;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_LAST_IN_USED", length=7)
    public Date getDatLastInUsed() {
        return this.datLastInUsed;
    }
    
    public void setDatLastInUsed(Date datLastInUsed) {
        this.datLastInUsed = datLastInUsed;
    }

    
    @Column(name="STATE_BIT", precision=22, scale=0)
    public BigDecimal getStateBit() {
        return this.stateBit;
    }
    
    public void setStateBit(BigDecimal stateBit) {
        this.stateBit = stateBit;
    }

    
    @Column(name="TEMPLATE_NAME", length=50)
    public String getTemplateName() {
        return this.templateName;
    }
    
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    
    @Column(name="TEMPLATE_TYPE", length=1)
    public Character getTemplateType() {
        return this.templateType;
    }
    
    public void setTemplateType(Character templateType) {
        this.templateType = templateType;
    }

    
    @Column(name="BENE_ACCTNO", length=30)
    public String getBeneAcctno() {
        return this.beneAcctno;
    }
    
    public void setBeneAcctno(String beneAcctno) {
        this.beneAcctno = beneAcctno;
    }

    
    @Column(name="TEMPLATE_TXN", length=10)
    public String getTemplateTxn() {
        return this.templateTxn;
    }
    
    public void setTemplateTxn(String templateTxn) {
        this.templateTxn = templateTxn;
    }

    
    @Column(name="TXNCURRENCY", length=3)
    public String getTxncurrency() {
        return this.txncurrency;
    }
    
    public void setTxncurrency(String txncurrency) {
        this.txncurrency = txncurrency;
    }

    
    @Column(name="FROMAMOUNT", precision=22, scale=0)
    public BigDecimal getFromamount() {
        return this.fromamount;
    }
    
    public void setFromamount(BigDecimal fromamount) {
        this.fromamount = fromamount;
    }

    
    @Column(name="TOAMOUNT", precision=22, scale=0)
    public BigDecimal getToamount() {
        return this.toamount;
    }
    
    public void setToamount(BigDecimal toamount) {
        this.toamount = toamount;
    }

    
    @Column(name="ID_ENTITY", length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }




}


