package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstchannelaccstatmatrix generated by hbm2java
 */
@Entity
@Table(name="MSTCHANNELACCSTATMATRIX"
    ,schema="FCDBADMIN_RK"
)
public class Mstchannelaccstatmatrix  implements java.io.Serializable {


     private MstchannelaccstatmatrixId id;
     private String acctstatus;

    public Mstchannelaccstatmatrix() {
    }

	
    public Mstchannelaccstatmatrix(MstchannelaccstatmatrixId id) {
        this.id = id;
    }
    public Mstchannelaccstatmatrix(MstchannelaccstatmatrixId id, String acctstatus) {
       this.id = id;
       this.acctstatus = acctstatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=5) ), 
        @AttributeOverride(name="accttype", column=@Column(name="ACCTTYPE", nullable=false, length=2) ) } )
    public MstchannelaccstatmatrixId getId() {
        return this.id;
    }
    
    public void setId(MstchannelaccstatmatrixId id) {
        this.id = id;
    }

    
    @Column(name="ACCTSTATUS", length=4000)
    public String getAcctstatus() {
        return this.acctstatus;
    }
    
    public void setAcctstatus(String acctstatus) {
        this.acctstatus = acctstatus;
    }




}


