package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstcustomerprofile generated by hbm2java
 */
@Entity
@Table(name="MSTCUSTOMERPROFILE"
    ,schema="FCDBADMIN_RK"
)
public class Mstcustomerprofile  implements java.io.Serializable {


     private MstcustomerprofileId id;
     private String namcompany;
     private Character isfaxnotificationallowed;
     private Character isbulkduplication;
     private String typeauth;
     private Character accountingentrysetup;
     private BigDecimal spotdealmaxamt;
     private BigDecimal dailycumulativeamt;
     private String spotcurrency;
     private Date datcreated;
     private String createdby;
     private Date datmodified;
     private String modifiedby;
     private Blob preauthacctdetails;
     private Character status;
     private Blob rolelist;
     private Blob udfdata;
     private BigDecimal refNo;
     private Character flgsingle;
     private BigDecimal graceperiod;
     private String theme;
     private String customerlogo;
     private BigDecimal nbrUsersAllowed;
     private BigDecimal nbrRoleAllowed;
     private Character enableCorpadmin;
     private String typecust;
     private String isinitalsoauth;
     private BigDecimal forwarddealmaxamt;
     private BigDecimal fwddailycumulativeamt;
     private Long maxnospotdeal;
     private Long maxnoofforwarddeal;
     private Character isallowcombinspotfwd;
     private Character showintermediarybankdetail;
     private Integer customeruserlimit;
     private Integer customercumulativelimit;
     private String custalertsubs;
     private Character haslinkedcustforalerts;
     private String s2sipaddress;

    public Mstcustomerprofile() {
    }

	
    public Mstcustomerprofile(MstcustomerprofileId id) {
        this.id = id;
    }
    public Mstcustomerprofile(MstcustomerprofileId id, String namcompany, Character isfaxnotificationallowed, Character isbulkduplication, String typeauth, Character accountingentrysetup, BigDecimal spotdealmaxamt, BigDecimal dailycumulativeamt, String spotcurrency, Date datcreated, String createdby, Date datmodified, String modifiedby, Blob preauthacctdetails, Character status, Blob rolelist, Blob udfdata, BigDecimal refNo, Character flgsingle, BigDecimal graceperiod, String theme, String customerlogo, BigDecimal nbrUsersAllowed, BigDecimal nbrRoleAllowed, Character enableCorpadmin, String typecust, String isinitalsoauth, BigDecimal forwarddealmaxamt, BigDecimal fwddailycumulativeamt, Long maxnospotdeal, Long maxnoofforwarddeal, Character isallowcombinspotfwd, Character showintermediarybankdetail, Integer customeruserlimit, Integer customercumulativelimit, String custalertsubs, Character haslinkedcustforalerts, String s2sipaddress) {
       this.id = id;
       this.namcompany = namcompany;
       this.isfaxnotificationallowed = isfaxnotificationallowed;
       this.isbulkduplication = isbulkduplication;
       this.typeauth = typeauth;
       this.accountingentrysetup = accountingentrysetup;
       this.spotdealmaxamt = spotdealmaxamt;
       this.dailycumulativeamt = dailycumulativeamt;
       this.spotcurrency = spotcurrency;
       this.datcreated = datcreated;
       this.createdby = createdby;
       this.datmodified = datmodified;
       this.modifiedby = modifiedby;
       this.preauthacctdetails = preauthacctdetails;
       this.status = status;
       this.rolelist = rolelist;
       this.udfdata = udfdata;
       this.refNo = refNo;
       this.flgsingle = flgsingle;
       this.graceperiod = graceperiod;
       this.theme = theme;
       this.customerlogo = customerlogo;
       this.nbrUsersAllowed = nbrUsersAllowed;
       this.nbrRoleAllowed = nbrRoleAllowed;
       this.enableCorpadmin = enableCorpadmin;
       this.typecust = typecust;
       this.isinitalsoauth = isinitalsoauth;
       this.forwarddealmaxamt = forwarddealmaxamt;
       this.fwddailycumulativeamt = fwddailycumulativeamt;
       this.maxnospotdeal = maxnospotdeal;
       this.maxnoofforwarddeal = maxnoofforwarddeal;
       this.isallowcombinspotfwd = isallowcombinspotfwd;
       this.showintermediarybankdetail = showintermediarybankdetail;
       this.customeruserlimit = customeruserlimit;
       this.customercumulativelimit = customercumulativelimit;
       this.custalertsubs = custalertsubs;
       this.haslinkedcustforalerts = haslinkedcustforalerts;
       this.s2sipaddress = s2sipaddress;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCust", column=@Column(name="ID_CUST", nullable=false, length=20) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ) } )
    public MstcustomerprofileId getId() {
        return this.id;
    }
    
    public void setId(MstcustomerprofileId id) {
        this.id = id;
    }

    
    @Column(name="NAMCOMPANY", length=105)
    public String getNamcompany() {
        return this.namcompany;
    }
    
    public void setNamcompany(String namcompany) {
        this.namcompany = namcompany;
    }

    
    @Column(name="ISFAXNOTIFICATIONALLOWED", length=1)
    public Character getIsfaxnotificationallowed() {
        return this.isfaxnotificationallowed;
    }
    
    public void setIsfaxnotificationallowed(Character isfaxnotificationallowed) {
        this.isfaxnotificationallowed = isfaxnotificationallowed;
    }

    
    @Column(name="ISBULKDUPLICATION", length=1)
    public Character getIsbulkduplication() {
        return this.isbulkduplication;
    }
    
    public void setIsbulkduplication(Character isbulkduplication) {
        this.isbulkduplication = isbulkduplication;
    }

    
    @Column(name="TYPEAUTH", length=30)
    public String getTypeauth() {
        return this.typeauth;
    }
    
    public void setTypeauth(String typeauth) {
        this.typeauth = typeauth;
    }

    
    @Column(name="ACCOUNTINGENTRYSETUP", length=1)
    public Character getAccountingentrysetup() {
        return this.accountingentrysetup;
    }
    
    public void setAccountingentrysetup(Character accountingentrysetup) {
        this.accountingentrysetup = accountingentrysetup;
    }

    
    @Column(name="SPOTDEALMAXAMT", precision=15)
    public BigDecimal getSpotdealmaxamt() {
        return this.spotdealmaxamt;
    }
    
    public void setSpotdealmaxamt(BigDecimal spotdealmaxamt) {
        this.spotdealmaxamt = spotdealmaxamt;
    }

    
    @Column(name="DAILYCUMULATIVEAMT", precision=15)
    public BigDecimal getDailycumulativeamt() {
        return this.dailycumulativeamt;
    }
    
    public void setDailycumulativeamt(BigDecimal dailycumulativeamt) {
        this.dailycumulativeamt = dailycumulativeamt;
    }

    
    @Column(name="SPOTCURRENCY", length=3)
    public String getSpotcurrency() {
        return this.spotcurrency;
    }
    
    public void setSpotcurrency(String spotcurrency) {
        this.spotcurrency = spotcurrency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="CREATEDBY", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMODIFIED", length=7)
    public Date getDatmodified() {
        return this.datmodified;
    }
    
    public void setDatmodified(Date datmodified) {
        this.datmodified = datmodified;
    }

    
    @Column(name="MODIFIEDBY", length=20)
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }

    
    @Column(name="PREAUTHACCTDETAILS")
    public Blob getPreauthacctdetails() {
        return this.preauthacctdetails;
    }
    
    public void setPreauthacctdetails(Blob preauthacctdetails) {
        this.preauthacctdetails = preauthacctdetails;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="ROLELIST")
    public Blob getRolelist() {
        return this.rolelist;
    }
    
    public void setRolelist(Blob rolelist) {
        this.rolelist = rolelist;
    }

    
    @Column(name="UDFDATA")
    public Blob getUdfdata() {
        return this.udfdata;
    }
    
    public void setUdfdata(Blob udfdata) {
        this.udfdata = udfdata;
    }

    
    @Column(name="REF_NO", precision=22, scale=0)
    public BigDecimal getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(BigDecimal refNo) {
        this.refNo = refNo;
    }

    
    @Column(name="FLGSINGLE", length=1)
    public Character getFlgsingle() {
        return this.flgsingle;
    }
    
    public void setFlgsingle(Character flgsingle) {
        this.flgsingle = flgsingle;
    }

    
    @Column(name="GRACEPERIOD", precision=22, scale=0)
    public BigDecimal getGraceperiod() {
        return this.graceperiod;
    }
    
    public void setGraceperiod(BigDecimal graceperiod) {
        this.graceperiod = graceperiod;
    }

    
    @Column(name="THEME")
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }

    
    @Column(name="CUSTOMERLOGO")
    public String getCustomerlogo() {
        return this.customerlogo;
    }
    
    public void setCustomerlogo(String customerlogo) {
        this.customerlogo = customerlogo;
    }

    
    @Column(name="NBR_USERS_ALLOWED", precision=22, scale=0)
    public BigDecimal getNbrUsersAllowed() {
        return this.nbrUsersAllowed;
    }
    
    public void setNbrUsersAllowed(BigDecimal nbrUsersAllowed) {
        this.nbrUsersAllowed = nbrUsersAllowed;
    }

    
    @Column(name="NBR_ROLE_ALLOWED", precision=22, scale=0)
    public BigDecimal getNbrRoleAllowed() {
        return this.nbrRoleAllowed;
    }
    
    public void setNbrRoleAllowed(BigDecimal nbrRoleAllowed) {
        this.nbrRoleAllowed = nbrRoleAllowed;
    }

    
    @Column(name="ENABLE_CORPADMIN", length=1)
    public Character getEnableCorpadmin() {
        return this.enableCorpadmin;
    }
    
    public void setEnableCorpadmin(Character enableCorpadmin) {
        this.enableCorpadmin = enableCorpadmin;
    }

    
    @Column(name="TYPECUST", length=1)
    public String getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(String typecust) {
        this.typecust = typecust;
    }

    
    @Column(name="ISINITALSOAUTH", length=1)
    public String getIsinitalsoauth() {
        return this.isinitalsoauth;
    }
    
    public void setIsinitalsoauth(String isinitalsoauth) {
        this.isinitalsoauth = isinitalsoauth;
    }

    
    @Column(name="FORWARDDEALMAXAMT", precision=15)
    public BigDecimal getForwarddealmaxamt() {
        return this.forwarddealmaxamt;
    }
    
    public void setForwarddealmaxamt(BigDecimal forwarddealmaxamt) {
        this.forwarddealmaxamt = forwarddealmaxamt;
    }

    
    @Column(name="FWDDAILYCUMULATIVEAMT", precision=15)
    public BigDecimal getFwddailycumulativeamt() {
        return this.fwddailycumulativeamt;
    }
    
    public void setFwddailycumulativeamt(BigDecimal fwddailycumulativeamt) {
        this.fwddailycumulativeamt = fwddailycumulativeamt;
    }

    
    @Column(name="MAXNOSPOTDEAL", precision=15, scale=0)
    public Long getMaxnospotdeal() {
        return this.maxnospotdeal;
    }
    
    public void setMaxnospotdeal(Long maxnospotdeal) {
        this.maxnospotdeal = maxnospotdeal;
    }

    
    @Column(name="MAXNOOFFORWARDDEAL", precision=15, scale=0)
    public Long getMaxnoofforwarddeal() {
        return this.maxnoofforwarddeal;
    }
    
    public void setMaxnoofforwarddeal(Long maxnoofforwarddeal) {
        this.maxnoofforwarddeal = maxnoofforwarddeal;
    }

    
    @Column(name="ISALLOWCOMBINSPOTFWD", length=1)
    public Character getIsallowcombinspotfwd() {
        return this.isallowcombinspotfwd;
    }
    
    public void setIsallowcombinspotfwd(Character isallowcombinspotfwd) {
        this.isallowcombinspotfwd = isallowcombinspotfwd;
    }

    
    @Column(name="SHOWINTERMEDIARYBANKDETAIL", length=1)
    public Character getShowintermediarybankdetail() {
        return this.showintermediarybankdetail;
    }
    
    public void setShowintermediarybankdetail(Character showintermediarybankdetail) {
        this.showintermediarybankdetail = showintermediarybankdetail;
    }

    
    @Column(name="CUSTOMERUSERLIMIT", precision=5, scale=0)
    public Integer getCustomeruserlimit() {
        return this.customeruserlimit;
    }
    
    public void setCustomeruserlimit(Integer customeruserlimit) {
        this.customeruserlimit = customeruserlimit;
    }

    
    @Column(name="CUSTOMERCUMULATIVELIMIT", precision=5, scale=0)
    public Integer getCustomercumulativelimit() {
        return this.customercumulativelimit;
    }
    
    public void setCustomercumulativelimit(Integer customercumulativelimit) {
        this.customercumulativelimit = customercumulativelimit;
    }

    
    @Column(name="CUSTALERTSUBS", length=2)
    public String getCustalertsubs() {
        return this.custalertsubs;
    }
    
    public void setCustalertsubs(String custalertsubs) {
        this.custalertsubs = custalertsubs;
    }

    
    @Column(name="HASLINKEDCUSTFORALERTS", length=1)
    public Character getHaslinkedcustforalerts() {
        return this.haslinkedcustforalerts;
    }
    
    public void setHaslinkedcustforalerts(Character haslinkedcustforalerts) {
        this.haslinkedcustforalerts = haslinkedcustforalerts;
    }

    
    @Column(name="S2SIPADDRESS", length=100)
    public String getS2sipaddress() {
        return this.s2sipaddress;
    }
    
    public void setS2sipaddress(String s2sipaddress) {
        this.s2sipaddress = s2sipaddress;
    }




}


