package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstcusttypesId generated by hbm2java
 */
@Embeddable
public class MstcusttypesId  implements java.io.Serializable {


     private String idEntity;
     private char typecust;
     private String refIdEntity;

    public MstcusttypesId() {
    }

    public MstcusttypesId(String idEntity, char typecust, String refIdEntity) {
       this.idEntity = idEntity;
       this.typecust = typecust;
       this.refIdEntity = refIdEntity;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="TYPECUST", nullable=false, length=1)
    public char getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(char typecust) {
        this.typecust = typecust;
    }


    @Column(name="REF_ID_ENTITY", nullable=false, length=4)
    public String getRefIdEntity() {
        return this.refIdEntity;
    }
    
    public void setRefIdEntity(String refIdEntity) {
        this.refIdEntity = refIdEntity;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstcusttypesId) ) return false;
		 MstcusttypesId castOther = ( MstcusttypesId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && (this.getTypecust()==castOther.getTypecust())
 && ( (this.getRefIdEntity()==castOther.getRefIdEntity()) || ( this.getRefIdEntity()!=null && castOther.getRefIdEntity()!=null && this.getRefIdEntity().equals(castOther.getRefIdEntity()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + this.getTypecust();
         result = 37 * result + ( getRefIdEntity() == null ? 0 : this.getRefIdEntity().hashCode() );
         return result;
   }   


}


