package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstentityuseralerts generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYUSERALERTS"
    ,schema="FCDBADMIN_RK"
)
public class Mstentityuseralerts  implements java.io.Serializable {


     private MstentityuseralertsId id;
     private String objmapping;
     private String registrationclass;
     private Character isenabled;

    public Mstentityuseralerts() {
    }

	
    public Mstentityuseralerts(MstentityuseralertsId id) {
        this.id = id;
    }
    public Mstentityuseralerts(MstentityuseralertsId id, String objmapping, String registrationclass, Character isenabled) {
       this.id = id;
       this.objmapping = objmapping;
       this.registrationclass = registrationclass;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idalert", column=@Column(name="IDALERT", nullable=false, length=50) ) } )
    public MstentityuseralertsId getId() {
        return this.id;
    }
    
    public void setId(MstentityuseralertsId id) {
        this.id = id;
    }

    
    @Column(name="OBJMAPPING", length=50)
    public String getObjmapping() {
        return this.objmapping;
    }
    
    public void setObjmapping(String objmapping) {
        this.objmapping = objmapping;
    }

    
    @Column(name="REGISTRATIONCLASS")
    public String getRegistrationclass() {
        return this.registrationclass;
    }
    
    public void setRegistrationclass(String registrationclass) {
        this.registrationclass = registrationclass;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }




}


