package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstflatgroup generated by hbm2java
 */
@Entity
@Table(name="MSTFLATGROUP"
    ,schema="FCDBADMIN_RK"
)
public class Mstflatgroup  implements java.io.Serializable {


     private MstflatgroupId id;
     private Mstflatrecord mstflatrecord;
     private String namgroup;
     private BigDecimal numocc;
     private BigDecimal idoccfield;
     private Set<Mstflatgroupfield> mstflatgroupfields = new HashSet<Mstflatgroupfield>(0);

    public Mstflatgroup() {
    }

	
    public Mstflatgroup(MstflatgroupId id, Mstflatrecord mstflatrecord) {
        this.id = id;
        this.mstflatrecord = mstflatrecord;
    }
    public Mstflatgroup(MstflatgroupId id, Mstflatrecord mstflatrecord, String namgroup, BigDecimal numocc, BigDecimal idoccfield, Set<Mstflatgroupfield> mstflatgroupfields) {
       this.id = id;
       this.mstflatrecord = mstflatrecord;
       this.namgroup = namgroup;
       this.numocc = numocc;
       this.idoccfield = idoccfield;
       this.mstflatgroupfields = mstflatgroupfields;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idrecord", column=@Column(name="IDRECORD", nullable=false, length=10) ), 
        @AttributeOverride(name="idgroup", column=@Column(name="IDGROUP", nullable=false, precision=22, scale=0) ) } )
    public MstflatgroupId getId() {
        return this.id;
    }
    
    public void setId(MstflatgroupId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IDAPP", referencedColumnName="IDAPP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDRECORD", referencedColumnName="IDRECORD", nullable=false, insertable=false, updatable=false) } )
    public Mstflatrecord getMstflatrecord() {
        return this.mstflatrecord;
    }
    
    public void setMstflatrecord(Mstflatrecord mstflatrecord) {
        this.mstflatrecord = mstflatrecord;
    }

    
    @Column(name="NAMGROUP", length=30)
    public String getNamgroup() {
        return this.namgroup;
    }
    
    public void setNamgroup(String namgroup) {
        this.namgroup = namgroup;
    }

    
    @Column(name="NUMOCC", precision=22, scale=0)
    public BigDecimal getNumocc() {
        return this.numocc;
    }
    
    public void setNumocc(BigDecimal numocc) {
        this.numocc = numocc;
    }

    
    @Column(name="IDOCCFIELD", precision=22, scale=0)
    public BigDecimal getIdoccfield() {
        return this.idoccfield;
    }
    
    public void setIdoccfield(BigDecimal idoccfield) {
        this.idoccfield = idoccfield;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstflatgroup")
    public Set<Mstflatgroupfield> getMstflatgroupfields() {
        return this.mstflatgroupfields;
    }
    
    public void setMstflatgroupfields(Set<Mstflatgroupfield> mstflatgroupfields) {
        this.mstflatgroupfields = mstflatgroupfields;
    }




}


