package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MsthostchainId generated by hbm2java
 */
@Embeddable
public class MsthostchainId  implements java.io.Serializable {


     private String idrequest;
     private String refIdrequest;
     private String idEntity;

    public MsthostchainId() {
    }

    public MsthostchainId(String idrequest, String refIdrequest, String idEntity) {
       this.idrequest = idrequest;
       this.refIdrequest = refIdrequest;
       this.idEntity = idEntity;
    }
   


    @Column(name="IDREQUEST", nullable=false, length=20)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }


    @Column(name="REF_IDREQUEST", nullable=false, length=20)
    public String getRefIdrequest() {
        return this.refIdrequest;
    }
    
    public void setRefIdrequest(String refIdrequest) {
        this.refIdrequest = refIdrequest;
    }


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsthostchainId) ) return false;
		 MsthostchainId castOther = ( MsthostchainId ) other; 
         
		 return ( (this.getIdrequest()==castOther.getIdrequest()) || ( this.getIdrequest()!=null && castOther.getIdrequest()!=null && this.getIdrequest().equals(castOther.getIdrequest()) ) )
 && ( (this.getRefIdrequest()==castOther.getRefIdrequest()) || ( this.getRefIdrequest()!=null && castOther.getRefIdrequest()!=null && this.getRefIdrequest().equals(castOther.getRefIdrequest()) ) )
 && ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdrequest() == null ? 0 : this.getIdrequest().hashCode() );
         result = 37 * result + ( getRefIdrequest() == null ? 0 : this.getRefIdrequest().hashCode() );
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         return result;
   }   


}


