package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Msthandoffs generated by hbm2java
 */
@Entity
@Table(name="MSTHANDOFFS"
    ,schema="FCDBADMIN_RK"
)
public class Msthandoffs  implements java.io.Serializable {


     private MsthandoffsId id;
     private String handoffdesc;
     private String handoffclass;
     private Character isenabled;
     private String idtemplate;
     private String connpoolprefix;
     private String propertiesstr;

    public Msthandoffs() {
    }

	
    public Msthandoffs(MsthandoffsId id) {
        this.id = id;
    }
    public Msthandoffs(MsthandoffsId id, String handoffdesc, String handoffclass, Character isenabled, String idtemplate, String connpoolprefix, String propertiesstr) {
       this.id = id;
       this.handoffdesc = handoffdesc;
       this.handoffclass = handoffclass;
       this.isenabled = isenabled;
       this.idtemplate = idtemplate;
       this.connpoolprefix = connpoolprefix;
       this.propertiesstr = propertiesstr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="handofftype", column=@Column(name="HANDOFFTYPE", nullable=false, length=50) ), 
        @AttributeOverride(name="flginout", column=@Column(name="FLGINOUT", nullable=false, length=1) ) } )
    public MsthandoffsId getId() {
        return this.id;
    }
    
    public void setId(MsthandoffsId id) {
        this.id = id;
    }

    
    @Column(name="HANDOFFDESC")
    public String getHandoffdesc() {
        return this.handoffdesc;
    }
    
    public void setHandoffdesc(String handoffdesc) {
        this.handoffdesc = handoffdesc;
    }

    
    @Column(name="HANDOFFCLASS")
    public String getHandoffclass() {
        return this.handoffclass;
    }
    
    public void setHandoffclass(String handoffclass) {
        this.handoffclass = handoffclass;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="IDTEMPLATE")
    public String getIdtemplate() {
        return this.idtemplate;
    }
    
    public void setIdtemplate(String idtemplate) {
        this.idtemplate = idtemplate;
    }

    
    @Column(name="CONNPOOLPREFIX", length=50)
    public String getConnpoolprefix() {
        return this.connpoolprefix;
    }
    
    public void setConnpoolprefix(String connpoolprefix) {
        this.connpoolprefix = connpoolprefix;
    }

    
    @Column(name="PROPERTIESSTR", length=2000)
    public String getPropertiesstr() {
        return this.propertiesstr;
    }
    
    public void setPropertiesstr(String propertiesstr) {
        this.propertiesstr = propertiesstr;
    }




}


