package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Msthostsystems generated by hbm2java
 */
@Entity
@Table(name="MSTHOSTSYSTEMS"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"TYPEHOST", "TYPESYSTEM"}) 
)
public class Msthostsystems  implements java.io.Serializable {


     private MsthostsystemsId id;
     private String description;
     private String typehost;
     private String hostname;
     private Character enable;

    public Msthostsystems() {
    }

	
    public Msthostsystems(MsthostsystemsId id) {
        this.id = id;
    }
    public Msthostsystems(MsthostsystemsId id, String description, String typehost, String hostname, Character enable) {
       this.id = id;
       this.description = description;
       this.typehost = typehost;
       this.hostname = hostname;
       this.enable = enable;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idhost", column=@Column(name="IDHOST", nullable=false, length=30) ), 
        @AttributeOverride(name="typesystem", column=@Column(name="TYPESYSTEM", nullable=false, length=1) ) } )
    public MsthostsystemsId getId() {
        return this.id;
    }
    
    public void setId(MsthostsystemsId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="TYPEHOST", length=5)
    public String getTypehost() {
        return this.typehost;
    }
    
    public void setTypehost(String typehost) {
        this.typehost = typehost;
    }

    
    @Column(name="HOSTNAME", length=100)
    public String getHostname() {
        return this.hostname;
    }
    
    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    
    @Column(name="ENABLE", length=1)
    public Character getEnable() {
        return this.enable;
    }
    
    public void setEnable(Character enable) {
        this.enable = enable;
    }




}


