package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Msthostappdatamap generated by hbm2java
 */
@Entity
@Table(name="MSTHOSTAPPDATAMAP"
    ,schema="FCDBADMIN_RK"
)
public class Msthostappdatamap  implements java.io.Serializable {


     private MsthostappdatamapId id;
     private String appval;
     private String loadflag;

    public Msthostappdatamap() {
    }

	
    public Msthostappdatamap(MsthostappdatamapId id) {
        this.id = id;
    }
    public Msthostappdatamap(MsthostappdatamapId id, String appval, String loadflag) {
       this.id = id;
       this.appval = appval;
       this.loadflag = loadflag;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="dataname", column=@Column(name="DATANAME", nullable=false, length=50) ), 
        @AttributeOverride(name="hostval", column=@Column(name="HOSTVAL", nullable=false, length=50) ) } )
    public MsthostappdatamapId getId() {
        return this.id;
    }
    
    public void setId(MsthostappdatamapId id) {
        this.id = id;
    }

    
    @Column(name="APPVAL", length=50)
    public String getAppval() {
        return this.appval;
    }
    
    public void setAppval(String appval) {
        this.appval = appval;
    }

    
    @Column(name="LOADFLAG", length=1)
    public String getLoadflag() {
        return this.loadflag;
    }
    
    public void setLoadflag(String loadflag) {
        this.loadflag = loadflag;
    }




}


