package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mstlist generated by hbm2java
 */
@Entity
@Table(name="MSTLIST"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"NAMLIST", "ID_ENTITY", "TYPEUSER", "IDCUSTGROUP"}) 
)
public class Mstlist  implements java.io.Serializable {


     private BigDecimal idlist;
     private String namlist;
     private String idEntity;
     private String typeuser;
     private String idcustgroup;
     private Character iscustomer;
     private Character status;
     private Character typelist;
     private Date issuedate;
     private Date expirydate;

    public Mstlist() {
    }

	
    public Mstlist(BigDecimal idlist) {
        this.idlist = idlist;
    }
    public Mstlist(BigDecimal idlist, String namlist, String idEntity, String typeuser, String idcustgroup, Character iscustomer, Character status, Character typelist, Date issuedate, Date expirydate) {
       this.idlist = idlist;
       this.namlist = namlist;
       this.idEntity = idEntity;
       this.typeuser = typeuser;
       this.idcustgroup = idcustgroup;
       this.iscustomer = iscustomer;
       this.status = status;
       this.typelist = typelist;
       this.issuedate = issuedate;
       this.expirydate = expirydate;
    }
   
     @Id 

    
    @Column(name="IDLIST", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdlist() {
        return this.idlist;
    }
    
    public void setIdlist(BigDecimal idlist) {
        this.idlist = idlist;
    }

    
    @Column(name="NAMLIST", length=20)
    public String getNamlist() {
        return this.namlist;
    }
    
    public void setNamlist(String namlist) {
        this.namlist = namlist;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="TYPEUSER", length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }

    
    @Column(name="IDCUSTGROUP", length=20)
    public String getIdcustgroup() {
        return this.idcustgroup;
    }
    
    public void setIdcustgroup(String idcustgroup) {
        this.idcustgroup = idcustgroup;
    }

    
    @Column(name="ISCUSTOMER", length=1)
    public Character getIscustomer() {
        return this.iscustomer;
    }
    
    public void setIscustomer(Character iscustomer) {
        this.iscustomer = iscustomer;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="TYPELIST", length=1)
    public Character getTypelist() {
        return this.typelist;
    }
    
    public void setTypelist(Character typelist) {
        this.typelist = typelist;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUEDATE", length=7)
    public Date getIssuedate() {
        return this.issuedate;
    }
    
    public void setIssuedate(Date issuedate) {
        this.issuedate = issuedate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRYDATE", length=7)
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }




}


