package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mstpreferences generated by hbm2java
 */
@Entity
@Table(name="MSTPREFERENCES"
    ,schema="FCDBADMIN_RK"
)
public class Mstpreferences  implements java.io.Serializable {


     private short idpref;
     private String description;

    public Mstpreferences() {
    }

	
    public Mstpreferences(short idpref) {
        this.idpref = idpref;
    }
    public Mstpreferences(short idpref, String description) {
       this.idpref = idpref;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="IDPREF", unique=true, nullable=false, precision=3, scale=0)
    public short getIdpref() {
        return this.idpref;
    }
    
    public void setIdpref(short idpref) {
        this.idpref = idpref;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


