package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Mstprecision generated by hbm2java
 */
@Entity
@Table(name="MSTPRECISION"
    ,schema="FCDBADMIN_RK"
)
public class Mstprecision  implements java.io.Serializable {


     private String codcurr;
     private Lkpcurrency lkpcurrency;
     private BigDecimal numscale;

    public Mstprecision() {
    }

	
    public Mstprecision(Lkpcurrency lkpcurrency) {
        this.lkpcurrency = lkpcurrency;
    }
    public Mstprecision(Lkpcurrency lkpcurrency, BigDecimal numscale) {
       this.lkpcurrency = lkpcurrency;
       this.numscale = numscale;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="lkpcurrency"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="CODCURR", unique=true, nullable=false, length=3)
    public String getCodcurr() {
        return this.codcurr;
    }
    
    public void setCodcurr(String codcurr) {
        this.codcurr = codcurr;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Lkpcurrency getLkpcurrency() {
        return this.lkpcurrency;
    }
    
    public void setLkpcurrency(Lkpcurrency lkpcurrency) {
        this.lkpcurrency = lkpcurrency;
    }

    
    @Column(name="NUMSCALE", precision=38, scale=0)
    public BigDecimal getNumscale() {
        return this.numscale;
    }
    
    public void setNumscale(BigDecimal numscale) {
        this.numscale = numscale;
    }




}


