package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstproductmap generated by hbm2java
 */
@Entity
@Table(name="MSTPRODUCTMAP"
    ,schema="FCDBADMIN_RK"
)
public class Mstproductmap  implements java.io.Serializable {


     private MstproductmapId id;
     private String prodcode;
     private String description;
     private Character loadflag;
     private Character isaccpackenabled;

    public Mstproductmap() {
    }

	
    public Mstproductmap(MstproductmapId id) {
        this.id = id;
    }
    public Mstproductmap(MstproductmapId id, String prodcode, String description, Character loadflag, Character isaccpackenabled) {
       this.id = id;
       this.prodcode = prodcode;
       this.description = description;
       this.loadflag = loadflag;
       this.isaccpackenabled = isaccpackenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="identity", column=@Column(name="IDENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="txntype", column=@Column(name="TXNTYPE", nullable=false, length=10) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="tag", column=@Column(name="TAG", nullable=false, length=50) ), 
        @AttributeOverride(name="iddevice", column=@Column(name="IDDEVICE", nullable=false, length=2) ) } )
    public MstproductmapId getId() {
        return this.id;
    }
    
    public void setId(MstproductmapId id) {
        this.id = id;
    }

    
    @Column(name="PRODCODE", length=100)
    public String getProdcode() {
        return this.prodcode;
    }
    
    public void setProdcode(String prodcode) {
        this.prodcode = prodcode;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LOADFLAG", length=1)
    public Character getLoadflag() {
        return this.loadflag;
    }
    
    public void setLoadflag(Character loadflag) {
        this.loadflag = loadflag;
    }

    
    @Column(name="ISACCPACKENABLED", length=1)
    public Character getIsaccpackenabled() {
        return this.isaccpackenabled;
    }
    
    public void setIsaccpackenabled(Character isaccpackenabled) {
        this.isaccpackenabled = isaccpackenabled;
    }




}


