package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstreport generated by hbm2java
 */
@Entity
@Table(name="MSTREPORT"
    ,schema="FCDBADMIN_RK"
)
public class Mstreport  implements java.io.Serializable {


     private String idreport;
     private String idapp;
     private String idengine;
     private String reportdesc;
     private String reportconfig;
     private String dataextractorclass;
     private String typereport;
     private String custgroupid;
     private String idformat;
     private String tasktype;
     private String idlang;
     private Character flgcustgroup;
     private Date datcreated;
     private Date datmodified;
     private String isdeleted;
     private Set<Txnreport> txnreports = new HashSet<Txnreport>(0);

    public Mstreport() {
    }

	
    public Mstreport(String idreport) {
        this.idreport = idreport;
    }
    public Mstreport(String idreport, String idapp, String idengine, String reportdesc, String reportconfig, String dataextractorclass, String typereport, String custgroupid, String idformat, String tasktype, String idlang, Character flgcustgroup, Date datcreated, Date datmodified, String isdeleted, Set<Txnreport> txnreports) {
       this.idreport = idreport;
       this.idapp = idapp;
       this.idengine = idengine;
       this.reportdesc = reportdesc;
       this.reportconfig = reportconfig;
       this.dataextractorclass = dataextractorclass;
       this.typereport = typereport;
       this.custgroupid = custgroupid;
       this.idformat = idformat;
       this.tasktype = tasktype;
       this.idlang = idlang;
       this.flgcustgroup = flgcustgroup;
       this.datcreated = datcreated;
       this.datmodified = datmodified;
       this.isdeleted = isdeleted;
       this.txnreports = txnreports;
    }
   
     @Id 

    
    @Column(name="IDREPORT", unique=true, nullable=false, length=20)
    public String getIdreport() {
        return this.idreport;
    }
    
    public void setIdreport(String idreport) {
        this.idreport = idreport;
    }

    
    @Column(name="IDAPP", length=2)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }

    
    @Column(name="IDENGINE", length=10)
    public String getIdengine() {
        return this.idengine;
    }
    
    public void setIdengine(String idengine) {
        this.idengine = idengine;
    }

    
    @Column(name="REPORTDESC", length=100)
    public String getReportdesc() {
        return this.reportdesc;
    }
    
    public void setReportdesc(String reportdesc) {
        this.reportdesc = reportdesc;
    }

    
    @Column(name="REPORTCONFIG", length=100)
    public String getReportconfig() {
        return this.reportconfig;
    }
    
    public void setReportconfig(String reportconfig) {
        this.reportconfig = reportconfig;
    }

    
    @Column(name="DATAEXTRACTORCLASS", length=250)
    public String getDataextractorclass() {
        return this.dataextractorclass;
    }
    
    public void setDataextractorclass(String dataextractorclass) {
        this.dataextractorclass = dataextractorclass;
    }

    
    @Column(name="TYPEREPORT", length=100)
    public String getTypereport() {
        return this.typereport;
    }
    
    public void setTypereport(String typereport) {
        this.typereport = typereport;
    }

    
    @Column(name="CUSTGROUPID", length=20)
    public String getCustgroupid() {
        return this.custgroupid;
    }
    
    public void setCustgroupid(String custgroupid) {
        this.custgroupid = custgroupid;
    }

    
    @Column(name="IDFORMAT", length=10)
    public String getIdformat() {
        return this.idformat;
    }
    
    public void setIdformat(String idformat) {
        this.idformat = idformat;
    }

    
    @Column(name="TASKTYPE", length=20)
    public String getTasktype() {
        return this.tasktype;
    }
    
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype;
    }

    
    @Column(name="IDLANG", length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }

    
    @Column(name="FLGCUSTGROUP", length=1)
    public Character getFlgcustgroup() {
        return this.flgcustgroup;
    }
    
    public void setFlgcustgroup(Character flgcustgroup) {
        this.flgcustgroup = flgcustgroup;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMODIFIED", length=7)
    public Date getDatmodified() {
        return this.datmodified;
    }
    
    public void setDatmodified(Date datmodified) {
        this.datmodified = datmodified;
    }

    
    @Column(name="ISDELETED", length=1)
    public String getIsdeleted() {
        return this.isdeleted;
    }
    
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstreport")
    public Set<Txnreport> getTxnreports() {
        return this.txnreports;
    }
    
    public void setTxnreports(Set<Txnreport> txnreports) {
        this.txnreports = txnreports;
    }




}


