package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mstrole generated by hbm2java
 */
@Entity
@Table(name="MSTROLE"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="IDROLE") 
)
public class Mstrole  implements java.io.Serializable {


     private MstroleId id;
     private Mstentity mstentity;
     private String description;
     private Date datcreated;
     private Date datlastupdated;
     private Character isdefault;
     private Character iscustomeronly;
     private String createdby;
     private String modifiedby;
     private String idcust;
     private Character typecust;

    public Mstrole() {
    }

	
    public Mstrole(MstroleId id, Mstentity mstentity) {
        this.id = id;
        this.mstentity = mstentity;
    }
    public Mstrole(MstroleId id, Mstentity mstentity, String description, Date datcreated, Date datlastupdated, Character isdefault, Character iscustomeronly, String createdby, String modifiedby, String idcust, Character typecust) {
       this.id = id;
       this.mstentity = mstentity;
       this.description = description;
       this.datcreated = datcreated;
       this.datlastupdated = datlastupdated;
       this.isdefault = isdefault;
       this.iscustomeronly = iscustomeronly;
       this.createdby = createdby;
       this.modifiedby = modifiedby;
       this.idcust = idcust;
       this.typecust = typecust;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrole", column=@Column(name="IDROLE", unique=true, nullable=false, length=20) ) } )
    public MstroleId getId() {
        return this.id;
    }
    
    public void setId(MstroleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTUPDATED", length=7)
    public Date getDatlastupdated() {
        return this.datlastupdated;
    }
    
    public void setDatlastupdated(Date datlastupdated) {
        this.datlastupdated = datlastupdated;
    }

    
    @Column(name="ISDEFAULT", length=1)
    public Character getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(Character isdefault) {
        this.isdefault = isdefault;
    }

    
    @Column(name="ISCUSTOMERONLY", length=1)
    public Character getIscustomeronly() {
        return this.iscustomeronly;
    }
    
    public void setIscustomeronly(Character iscustomeronly) {
        this.iscustomeronly = iscustomeronly;
    }

    
    @Column(name="CREATEDBY", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="MODIFIEDBY", length=20)
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }

    
    @Column(name="IDCUST", length=20)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }

    
    @Column(name="TYPECUST", length=1)
    public Character getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(Character typecust) {
        this.typecust = typecust;
    }




}


