package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstrelationmatrix generated by hbm2java
 */
@Entity
@Table(name="MSTRELATIONMATRIX"
    ,schema="FCDBADMIN_RK"
)
public class Mstrelationmatrix  implements java.io.Serializable {


     private MstrelationmatrixId id;
     private Mstrelationship mstrelationship;

    public Mstrelationmatrix() {
    }

    public Mstrelationmatrix(MstrelationmatrixId id, Mstrelationship mstrelationship) {
       this.id = id;
       this.mstrelationship = mstrelationship;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrelationship", column=@Column(name="IDRELATIONSHIP", nullable=false, length=4) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MstrelationmatrixId getId() {
        return this.id;
    }
    
    public void setId(MstrelationmatrixId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", insertable=false, updatable=false), 
        @JoinColumn(name="IDRELATIONSHIP", referencedColumnName="IDRELATIONSHIP",  insertable=false, updatable=false) } )
    public Mstrelationship getMstrelationship() {
        return this.mstrelationship;
    }
    
    public void setMstrelationship(Mstrelationship mstrelationship) {
        this.mstrelationship = mstrelationship;
    }




}


