package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstrelationshipId generated by hbm2java
 */
@Embeddable
public class MstrelationshipId  implements java.io.Serializable {


     private String idEntity;
     private String idrelationship;

    public MstrelationshipId() {
    }

    public MstrelationshipId(String idEntity, String idrelationship) {
       this.idEntity = idEntity;
       this.idrelationship = idrelationship;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="IDRELATIONSHIP", nullable=false, length=4)
    public String getIdrelationship() {
        return this.idrelationship;
    }
    
    public void setIdrelationship(String idrelationship) {
        this.idrelationship = idrelationship;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstrelationshipId) ) return false;
		 MstrelationshipId castOther = ( MstrelationshipId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getIdrelationship()==castOther.getIdrelationship()) || ( this.getIdrelationship()!=null && castOther.getIdrelationship()!=null && this.getIdrelationship().equals(castOther.getIdrelationship()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getIdrelationship() == null ? 0 : this.getIdrelationship().hashCode() );
         return result;
   }   


}


