package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstserver generated by hbm2java
 */
@Entity
@Table(name="MSTSERVER"
    ,schema="FCDBADMIN_RK"
)
public class Mstserver  implements java.io.Serializable {


     private String idserver;
     private Character typserver;
     private String description;
     private String namqreader;
     private String qreaderprefix;
     private Set<Usermenu> usermenus = new HashSet<Usermenu>(0);
     private Set<Application> applications = new HashSet<Application>(0);

    public Mstserver() {
    }

	
    public Mstserver(String idserver) {
        this.idserver = idserver;
    }
    public Mstserver(String idserver, Character typserver, String description, String namqreader, String qreaderprefix, Set<Usermenu> usermenus, Set<Application> applications) {
       this.idserver = idserver;
       this.typserver = typserver;
       this.description = description;
       this.namqreader = namqreader;
       this.qreaderprefix = qreaderprefix;
       this.usermenus = usermenus;
       this.applications = applications;
    }
   
     @Id 

    
    @Column(name="IDSERVER", unique=true, nullable=false, length=2)
    public String getIdserver() {
        return this.idserver;
    }
    
    public void setIdserver(String idserver) {
        this.idserver = idserver;
    }

    
    @Column(name="TYPSERVER", length=1)
    public Character getTypserver() {
        return this.typserver;
    }
    
    public void setTypserver(Character typserver) {
        this.typserver = typserver;
    }

    
    @Column(name="DESCRIPTION", length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="NAMQREADER", length=100)
    public String getNamqreader() {
        return this.namqreader;
    }
    
    public void setNamqreader(String namqreader) {
        this.namqreader = namqreader;
    }

    
    @Column(name="QREADERPREFIX", length=20)
    public String getQreaderprefix() {
        return this.qreaderprefix;
    }
    
    public void setQreaderprefix(String qreaderprefix) {
        this.qreaderprefix = qreaderprefix;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstserver")
    public Set<Usermenu> getUsermenus() {
        return this.usermenus;
    }
    
    public void setUsermenus(Set<Usermenu> usermenus) {
        this.usermenus = usermenus;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="WEBTOAPP", schema="FCDBADMIN_RK", joinColumns = { 
        @JoinColumn(name="IDSERVER", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDAPP", nullable=false, updatable=false) })
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }




}


