package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstservices generated by hbm2java
 */
@Entity
@Table(name="MSTSERVICES"
    ,schema="FCDBADMIN_RK"
)
public class Mstservices  implements java.io.Serializable {


     private MstservicesId id;
     private String interface_;
     private String endpoint;
     private String isenabled;
     private String ismultiphase;
     private String isrollbackonly;
     private String customHelper;
     private String nammethod;
     private String namtxncontext;
     private String isapi;
     private String isauditrequired;
     private String authdtomapper;
     private String txnauthdtomapper;
     private BigDecimal validationversion;
     private String extendedresponsehandler;

    public Mstservices() {
    }

	
    public Mstservices(MstservicesId id) {
        this.id = id;
    }
    public Mstservices(MstservicesId id, String interface_, String endpoint, String isenabled, String ismultiphase, String isrollbackonly, String customHelper, String nammethod, String namtxncontext, String isapi, String isauditrequired, String authdtomapper, String txnauthdtomapper, BigDecimal validationversion, String extendedresponsehandler) {
       this.id = id;
       this.interface_ = interface_;
       this.endpoint = endpoint;
       this.isenabled = isenabled;
       this.ismultiphase = ismultiphase;
       this.isrollbackonly = isrollbackonly;
       this.customHelper = customHelper;
       this.nammethod = nammethod;
       this.namtxncontext = namtxncontext;
       this.isapi = isapi;
       this.isauditrequired = isauditrequired;
       this.authdtomapper = authdtomapper;
       this.txnauthdtomapper = txnauthdtomapper;
       this.validationversion = validationversion;
       this.extendedresponsehandler = extendedresponsehandler;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="namservice", column=@Column(name="NAMSERVICE", nullable=false) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", nullable=false, precision=22, scale=0) ) } )
    public MstservicesId getId() {
        return this.id;
    }
    
    public void setId(MstservicesId id) {
        this.id = id;
    }

    
    @Column(name="INTERFACE")
    public String getInterface_() {
        return this.interface_;
    }
    
    public void setInterface_(String interface_) {
        this.interface_ = interface_;
    }

    
    @Column(name="ENDPOINT")
    public String getEndpoint() {
        return this.endpoint;
    }
    
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="ISMULTIPHASE", length=1)
    public String getIsmultiphase() {
        return this.ismultiphase;
    }
    
    public void setIsmultiphase(String ismultiphase) {
        this.ismultiphase = ismultiphase;
    }

    
    @Column(name="ISROLLBACKONLY", length=1)
    public String getIsrollbackonly() {
        return this.isrollbackonly;
    }
    
    public void setIsrollbackonly(String isrollbackonly) {
        this.isrollbackonly = isrollbackonly;
    }

    
    @Column(name="CUSTOM_HELPER")
    public String getCustomHelper() {
        return this.customHelper;
    }
    
    public void setCustomHelper(String customHelper) {
        this.customHelper = customHelper;
    }

    
    @Column(name="NAMMETHOD")
    public String getNammethod() {
        return this.nammethod;
    }
    
    public void setNammethod(String nammethod) {
        this.nammethod = nammethod;
    }

    
    @Column(name="NAMTXNCONTEXT")
    public String getNamtxncontext() {
        return this.namtxncontext;
    }
    
    public void setNamtxncontext(String namtxncontext) {
        this.namtxncontext = namtxncontext;
    }

    
    @Column(name="ISAPI", length=1)
    public String getIsapi() {
        return this.isapi;
    }
    
    public void setIsapi(String isapi) {
        this.isapi = isapi;
    }

    
    @Column(name="ISAUDITREQUIRED", length=1)
    public String getIsauditrequired() {
        return this.isauditrequired;
    }
    
    public void setIsauditrequired(String isauditrequired) {
        this.isauditrequired = isauditrequired;
    }

    
    @Column(name="AUTHDTOMAPPER")
    public String getAuthdtomapper() {
        return this.authdtomapper;
    }
    
    public void setAuthdtomapper(String authdtomapper) {
        this.authdtomapper = authdtomapper;
    }

    
    @Column(name="TXNAUTHDTOMAPPER")
    public String getTxnauthdtomapper() {
        return this.txnauthdtomapper;
    }
    
    public void setTxnauthdtomapper(String txnauthdtomapper) {
        this.txnauthdtomapper = txnauthdtomapper;
    }

    
    @Column(name="VALIDATIONVERSION", precision=22, scale=0)
    public BigDecimal getValidationversion() {
        return this.validationversion;
    }
    
    public void setValidationversion(BigDecimal validationversion) {
        this.validationversion = validationversion;
    }

    
    @Column(name="EXTENDEDRESPONSEHANDLER")
    public String getExtendedresponsehandler() {
        return this.extendedresponsehandler;
    }
    
    public void setExtendedresponsehandler(String extendedresponsehandler) {
        this.extendedresponsehandler = extendedresponsehandler;
    }




}


