package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Msttimer generated by hbm2java
 */
@Entity
@Table(name="MSTTIMER"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="IDTIMER") 
)
public class Msttimer  implements java.io.Serializable {


     private MsttimerId id;
     private String description;
     private Long timerduration;
     private Character status;
     private Character timermode;
     private Character enabled;
     private Date lastregistered;
     private Date lastexecutionstarted;
     private Date lastexecutionstopped;
     private Date creationdate;
     private Boolean timertype;
     private Date expirationdate;
     private String handoffclass;
     private Character flginout;
     private String connpoolprefix;
     private String handofftype;
     private Integer jvmid;

    public Msttimer() {
    }

	
    public Msttimer(MsttimerId id) {
        this.id = id;
    }
    public Msttimer(MsttimerId id, String description, Long timerduration, Character status, Character timermode, Character enabled, Date lastregistered, Date lastexecutionstarted, Date lastexecutionstopped, Date creationdate, Boolean timertype, Date expirationdate, String handoffclass, Character flginout, String connpoolprefix, String handofftype, Integer jvmid) {
       this.id = id;
       this.description = description;
       this.timerduration = timerduration;
       this.status = status;
       this.timermode = timermode;
       this.enabled = enabled;
       this.lastregistered = lastregistered;
       this.lastexecutionstarted = lastexecutionstarted;
       this.lastexecutionstopped = lastexecutionstopped;
       this.creationdate = creationdate;
       this.timertype = timertype;
       this.expirationdate = expirationdate;
       this.handoffclass = handoffclass;
       this.flginout = flginout;
       this.connpoolprefix = connpoolprefix;
       this.handofftype = handofftype;
       this.jvmid = jvmid;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idtimer", column=@Column(name="IDTIMER", unique=true, nullable=false, precision=15, scale=0) ), 
        @AttributeOverride(name="jndiname", column=@Column(name="JNDINAME", nullable=false, length=10) ) } )
    public MsttimerId getId() {
        return this.id;
    }
    
    public void setId(MsttimerId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="TIMERDURATION", precision=18, scale=0)
    public Long getTimerduration() {
        return this.timerduration;
    }
    
    public void setTimerduration(Long timerduration) {
        this.timerduration = timerduration;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="TIMERMODE", length=1)
    public Character getTimermode() {
        return this.timermode;
    }
    
    public void setTimermode(Character timermode) {
        this.timermode = timermode;
    }

    
    @Column(name="ENABLED", length=1)
    public Character getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Character enabled) {
        this.enabled = enabled;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTREGISTERED", length=7)
    public Date getLastregistered() {
        return this.lastregistered;
    }
    
    public void setLastregistered(Date lastregistered) {
        this.lastregistered = lastregistered;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTEXECUTIONSTARTED", length=7)
    public Date getLastexecutionstarted() {
        return this.lastexecutionstarted;
    }
    
    public void setLastexecutionstarted(Date lastexecutionstarted) {
        this.lastexecutionstarted = lastexecutionstarted;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTEXECUTIONSTOPPED", length=7)
    public Date getLastexecutionstopped() {
        return this.lastexecutionstopped;
    }
    
    public void setLastexecutionstopped(Date lastexecutionstopped) {
        this.lastexecutionstopped = lastexecutionstopped;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATIONDATE", length=7)
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    
    @Column(name="TIMERTYPE", precision=1, scale=0)
    public Boolean getTimertype() {
        return this.timertype;
    }
    
    public void setTimertype(Boolean timertype) {
        this.timertype = timertype;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRATIONDATE", length=7)
    public Date getExpirationdate() {
        return this.expirationdate;
    }
    
    public void setExpirationdate(Date expirationdate) {
        this.expirationdate = expirationdate;
    }

    
    @Column(name="HANDOFFCLASS")
    public String getHandoffclass() {
        return this.handoffclass;
    }
    
    public void setHandoffclass(String handoffclass) {
        this.handoffclass = handoffclass;
    }

    
    @Column(name="FLGINOUT", length=1)
    public Character getFlginout() {
        return this.flginout;
    }
    
    public void setFlginout(Character flginout) {
        this.flginout = flginout;
    }

    
    @Column(name="CONNPOOLPREFIX", length=50)
    public String getConnpoolprefix() {
        return this.connpoolprefix;
    }
    
    public void setConnpoolprefix(String connpoolprefix) {
        this.connpoolprefix = connpoolprefix;
    }

    
    @Column(name="HANDOFFTYPE", length=50)
    public String getHandofftype() {
        return this.handofftype;
    }
    
    public void setHandofftype(String handofftype) {
        this.handofftype = handofftype;
    }

    
    @Column(name="JVMID", precision=9, scale=0)
    public Integer getJvmid() {
        return this.jvmid;
    }
    
    public void setJvmid(Integer jvmid) {
        this.jvmid = jvmid;
    }




}


