package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mstuidownloadparams generated by hbm2java
 */
@Entity
@Table(name="MSTUIDOWNLOADPARAMS"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "TYPEUSER", "IDTXN", "IDPARAM", "IDREQUEST", "PARAMSEQ", "IDCHANNEL"}) 
)
public class Mstuidownloadparams  implements java.io.Serializable {


     private MstuidownloadparamsId id;
     private BigDecimal paramseq;
     private String typeparam;
     private String isenabled;
     private String isfixed;
     private String nampath;
     private String islink;
     private String namfunction;
     private String argfunction;
     private String align;
     private BigDecimal fieldlength;
     private String dynamicnampath;
     private String refidparam;
     private String adtnlParams;
     private Character typefield;

    public Mstuidownloadparams() {
    }

	
    public Mstuidownloadparams(MstuidownloadparamsId id) {
        this.id = id;
    }
    public Mstuidownloadparams(MstuidownloadparamsId id, BigDecimal paramseq, String typeparam, String isenabled, String isfixed, String nampath, String islink, String namfunction, String argfunction, String align, BigDecimal fieldlength, String dynamicnampath, String refidparam, String adtnlParams, Character typefield) {
       this.id = id;
       this.paramseq = paramseq;
       this.typeparam = typeparam;
       this.isenabled = isenabled;
       this.isfixed = isfixed;
       this.nampath = nampath;
       this.islink = islink;
       this.namfunction = namfunction;
       this.argfunction = argfunction;
       this.align = align;
       this.fieldlength = fieldlength;
       this.dynamicnampath = dynamicnampath;
       this.refidparam = refidparam;
       this.adtnlParams = adtnlParams;
       this.typefield = typefield;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="idparam", column=@Column(name="IDPARAM", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=50) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="namparam", column=@Column(name="NAMPARAM", nullable=false, length=50) ) } )
    public MstuidownloadparamsId getId() {
        return this.id;
    }
    
    public void setId(MstuidownloadparamsId id) {
        this.id = id;
    }

    
    @Column(name="PARAMSEQ", precision=22, scale=0)
    public BigDecimal getParamseq() {
        return this.paramseq;
    }
    
    public void setParamseq(BigDecimal paramseq) {
        this.paramseq = paramseq;
    }

    
    @Column(name="TYPEPARAM", length=2)
    public String getTypeparam() {
        return this.typeparam;
    }
    
    public void setTypeparam(String typeparam) {
        this.typeparam = typeparam;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="ISFIXED", length=1)
    public String getIsfixed() {
        return this.isfixed;
    }
    
    public void setIsfixed(String isfixed) {
        this.isfixed = isfixed;
    }

    
    @Column(name="NAMPATH", length=500)
    public String getNampath() {
        return this.nampath;
    }
    
    public void setNampath(String nampath) {
        this.nampath = nampath;
    }

    
    @Column(name="ISLINK", length=1)
    public String getIslink() {
        return this.islink;
    }
    
    public void setIslink(String islink) {
        this.islink = islink;
    }

    
    @Column(name="NAMFUNCTION")
    public String getNamfunction() {
        return this.namfunction;
    }
    
    public void setNamfunction(String namfunction) {
        this.namfunction = namfunction;
    }

    
    @Column(name="ARGFUNCTION")
    public String getArgfunction() {
        return this.argfunction;
    }
    
    public void setArgfunction(String argfunction) {
        this.argfunction = argfunction;
    }

    
    @Column(name="ALIGN", length=1)
    public String getAlign() {
        return this.align;
    }
    
    public void setAlign(String align) {
        this.align = align;
    }

    
    @Column(name="FIELDLENGTH", precision=22, scale=0)
    public BigDecimal getFieldlength() {
        return this.fieldlength;
    }
    
    public void setFieldlength(BigDecimal fieldlength) {
        this.fieldlength = fieldlength;
    }

    
    @Column(name="DYNAMICNAMPATH")
    public String getDynamicnampath() {
        return this.dynamicnampath;
    }
    
    public void setDynamicnampath(String dynamicnampath) {
        this.dynamicnampath = dynamicnampath;
    }

    
    @Column(name="REFIDPARAM", length=100)
    public String getRefidparam() {
        return this.refidparam;
    }
    
    public void setRefidparam(String refidparam) {
        this.refidparam = refidparam;
    }

    
    @Column(name="ADTNL_PARAMS", length=4000)
    public String getAdtnlParams() {
        return this.adtnlParams;
    }
    
    public void setAdtnlParams(String adtnlParams) {
        this.adtnlParams = adtnlParams;
    }

    
    @Column(name="TYPEFIELD", length=1)
    public Character getTypefield() {
        return this.typefield;
    }
    
    public void setTypefield(Character typefield) {
        this.typefield = typefield;
    }




}


