package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstusertypes generated by hbm2java
 */
@Entity
@Table(name="MSTUSERTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstusertypes  implements java.io.Serializable {


     private String typeuser;
     private Mstbaseusertypes mstbaseusertypes;
     private String description;
     private String isenabled;
     private String hasmultcust;
     private String flginternaltype;
     private String hascustid;
     private Character lookuptype;
     private Set<Mststatusgroupmap> mststatusgroupmaps = new HashSet<Mststatusgroupmap>(0);
     private Set<Udfgrouptemplatemap> udfgrouptemplatemaps = new HashSet<Udfgrouptemplatemap>(0);
     private Set<Mobileenablerusertypemap> mobileenablerusertypemaps = new HashSet<Mobileenablerusertypemap>(0);
     private Set<OrigProdcateg> origProdcategs = new HashSet<OrigProdcateg>(0);
     private Set<Mstsecurityquestions> mstsecurityquestionses = new HashSet<Mstsecurityquestions>(0);
     private Set<Mstmailsubject> mstmailsubjects = new HashSet<Mstmailsubject>(0);
     private Set<Mstentityusertypes> mstentityusertypeses = new HashSet<Mstentityusertypes>(0);
     private Set<Mstusertypetxn> mstusertypetxns = new HashSet<Mstusertypetxn>(0);
     private Set<Mstaccttypes> mstaccttypeses = new HashSet<Mstaccttypes>(0);
     private Set<Mstentityusertypelang> mstentityusertypelangs = new HashSet<Mstentityusertypelang>(0);

    public Mstusertypes() {
    }

	
    public Mstusertypes(String typeuser) {
        this.typeuser = typeuser;
    }
    public Mstusertypes(String typeuser, Mstbaseusertypes mstbaseusertypes, String description, String isenabled, String hasmultcust, String flginternaltype, String hascustid, Character lookuptype, Set<Mststatusgroupmap> mststatusgroupmaps, Set<Udfgrouptemplatemap> udfgrouptemplatemaps, Set<Mobileenablerusertypemap> mobileenablerusertypemaps, Set<OrigProdcateg> origProdcategs, Set<Mstsecurityquestions> mstsecurityquestionses, Set<Mstmailsubject> mstmailsubjects, Set<Mstentityusertypes> mstentityusertypeses, Set<Mstusertypetxn> mstusertypetxns, Set<Mstaccttypes> mstaccttypeses, Set<Mstentityusertypelang> mstentityusertypelangs) {
       this.typeuser = typeuser;
       this.mstbaseusertypes = mstbaseusertypes;
       this.description = description;
       this.isenabled = isenabled;
       this.hasmultcust = hasmultcust;
       this.flginternaltype = flginternaltype;
       this.hascustid = hascustid;
       this.lookuptype = lookuptype;
       this.mststatusgroupmaps = mststatusgroupmaps;
       this.udfgrouptemplatemaps = udfgrouptemplatemaps;
       this.mobileenablerusertypemaps = mobileenablerusertypemaps;
       this.origProdcategs = origProdcategs;
       this.mstsecurityquestionses = mstsecurityquestionses;
       this.mstmailsubjects = mstmailsubjects;
       this.mstentityusertypeses = mstentityusertypeses;
       this.mstusertypetxns = mstusertypetxns;
       this.mstaccttypeses = mstaccttypeses;
       this.mstentityusertypelangs = mstentityusertypelangs;
    }
   
     @Id 

    
    @Column(name="TYPEUSER", unique=true, nullable=false, length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BASEUSERTYPE")
    public Mstbaseusertypes getMstbaseusertypes() {
        return this.mstbaseusertypes;
    }
    
    public void setMstbaseusertypes(Mstbaseusertypes mstbaseusertypes) {
        this.mstbaseusertypes = mstbaseusertypes;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="HASMULTCUST", length=1)
    public String getHasmultcust() {
        return this.hasmultcust;
    }
    
    public void setHasmultcust(String hasmultcust) {
        this.hasmultcust = hasmultcust;
    }

    
    @Column(name="FLGINTERNALTYPE", length=1)
    public String getFlginternaltype() {
        return this.flginternaltype;
    }
    
    public void setFlginternaltype(String flginternaltype) {
        this.flginternaltype = flginternaltype;
    }

    
    @Column(name="HASCUSTID", length=1)
    public String getHascustid() {
        return this.hascustid;
    }
    
    public void setHascustid(String hascustid) {
        this.hascustid = hascustid;
    }

    
    @Column(name="LOOKUPTYPE", length=1)
    public Character getLookuptype() {
        return this.lookuptype;
    }
    
    public void setLookuptype(Character lookuptype) {
        this.lookuptype = lookuptype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mststatusgroupmap> getMststatusgroupmaps() {
        return this.mststatusgroupmaps;
    }
    
    public void setMststatusgroupmaps(Set<Mststatusgroupmap> mststatusgroupmaps) {
        this.mststatusgroupmaps = mststatusgroupmaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Udfgrouptemplatemap> getUdfgrouptemplatemaps() {
        return this.udfgrouptemplatemaps;
    }
    
    public void setUdfgrouptemplatemaps(Set<Udfgrouptemplatemap> udfgrouptemplatemaps) {
        this.udfgrouptemplatemaps = udfgrouptemplatemaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mobileenablerusertypemap> getMobileenablerusertypemaps() {
        return this.mobileenablerusertypemaps;
    }
    
    public void setMobileenablerusertypemaps(Set<Mobileenablerusertypemap> mobileenablerusertypemaps) {
        this.mobileenablerusertypemaps = mobileenablerusertypemaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<OrigProdcateg> getOrigProdcategs() {
        return this.origProdcategs;
    }
    
    public void setOrigProdcategs(Set<OrigProdcateg> origProdcategs) {
        this.origProdcategs = origProdcategs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mstsecurityquestions> getMstsecurityquestionses() {
        return this.mstsecurityquestionses;
    }
    
    public void setMstsecurityquestionses(Set<Mstsecurityquestions> mstsecurityquestionses) {
        this.mstsecurityquestionses = mstsecurityquestionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mstmailsubject> getMstmailsubjects() {
        return this.mstmailsubjects;
    }
    
    public void setMstmailsubjects(Set<Mstmailsubject> mstmailsubjects) {
        this.mstmailsubjects = mstmailsubjects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mstentityusertypes> getMstentityusertypeses() {
        return this.mstentityusertypeses;
    }
    
    public void setMstentityusertypeses(Set<Mstentityusertypes> mstentityusertypeses) {
        this.mstentityusertypeses = mstentityusertypeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mstusertypetxn> getMstusertypetxns() {
        return this.mstusertypetxns;
    }
    
    public void setMstusertypetxns(Set<Mstusertypetxn> mstusertypetxns) {
        this.mstusertypetxns = mstusertypetxns;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mstaccttypes> getMstaccttypeses() {
        return this.mstaccttypeses;
    }
    
    public void setMstaccttypeses(Set<Mstaccttypes> mstaccttypeses) {
        this.mstaccttypeses = mstaccttypeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstusertypes")
    public Set<Mstentityusertypelang> getMstentityusertypelangs() {
        return this.mstentityusertypelangs;
    }
    
    public void setMstentityusertypelangs(Set<Mstentityusertypelang> mstentityusertypelangs) {
        this.mstentityusertypelangs = mstentityusertypelangs;
    }




}


