package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstudfgroupId generated by hbm2java
 */
@Embeddable
public class MstudfgroupId  implements java.io.Serializable {


     private String idrequest;
     private String idgroup;
     private String idudf;

    public MstudfgroupId() {
    }

    public MstudfgroupId(String idrequest, String idgroup, String idudf) {
       this.idrequest = idrequest;
       this.idgroup = idgroup;
       this.idudf = idudf;
    }
   


    @Column(name="IDREQUEST", nullable=false, length=20)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }


    @Column(name="IDGROUP", nullable=false, length=40)
    public String getIdgroup() {
        return this.idgroup;
    }
    
    public void setIdgroup(String idgroup) {
        this.idgroup = idgroup;
    }


    @Column(name="IDUDF", nullable=false, length=40)
    public String getIdudf() {
        return this.idudf;
    }
    
    public void setIdudf(String idudf) {
        this.idudf = idudf;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstudfgroupId) ) return false;
		 MstudfgroupId castOther = ( MstudfgroupId ) other; 
         
		 return ( (this.getIdrequest()==castOther.getIdrequest()) || ( this.getIdrequest()!=null && castOther.getIdrequest()!=null && this.getIdrequest().equals(castOther.getIdrequest()) ) )
 && ( (this.getIdgroup()==castOther.getIdgroup()) || ( this.getIdgroup()!=null && castOther.getIdgroup()!=null && this.getIdgroup().equals(castOther.getIdgroup()) ) )
 && ( (this.getIdudf()==castOther.getIdudf()) || ( this.getIdudf()!=null && castOther.getIdudf()!=null && this.getIdudf().equals(castOther.getIdudf()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdrequest() == null ? 0 : this.getIdrequest().hashCode() );
         result = 37 * result + ( getIdgroup() == null ? 0 : this.getIdgroup().hashCode() );
         result = 37 * result + ( getIdudf() == null ? 0 : this.getIdudf().hashCode() );
         return result;
   }   


}


