package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstuseragenttxnId generated by hbm2java
 */
@Embeddable
public class MstuseragenttxnId  implements java.io.Serializable {


     private String idEntity;
     private String usertype;
     private String idchannel;
     private String iduseragent;
     private String idtxn;

    public MstuseragenttxnId() {
    }

    public MstuseragenttxnId(String idEntity, String usertype, String idchannel, String iduseragent, String idtxn) {
       this.idEntity = idEntity;
       this.usertype = usertype;
       this.idchannel = idchannel;
       this.iduseragent = iduseragent;
       this.idtxn = idtxn;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="USERTYPE", nullable=false, length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }


    @Column(name="IDCHANNEL", nullable=false, length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }


    @Column(name="IDUSERAGENT", nullable=false, length=10)
    public String getIduseragent() {
        return this.iduseragent;
    }
    
    public void setIduseragent(String iduseragent) {
        this.iduseragent = iduseragent;
    }


    @Column(name="IDTXN", nullable=false, length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstuseragenttxnId) ) return false;
		 MstuseragenttxnId castOther = ( MstuseragenttxnId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getUsertype()==castOther.getUsertype()) || ( this.getUsertype()!=null && castOther.getUsertype()!=null && this.getUsertype().equals(castOther.getUsertype()) ) )
 && ( (this.getIdchannel()==castOther.getIdchannel()) || ( this.getIdchannel()!=null && castOther.getIdchannel()!=null && this.getIdchannel().equals(castOther.getIdchannel()) ) )
 && ( (this.getIduseragent()==castOther.getIduseragent()) || ( this.getIduseragent()!=null && castOther.getIduseragent()!=null && this.getIduseragent().equals(castOther.getIduseragent()) ) )
 && ( (this.getIdtxn()==castOther.getIdtxn()) || ( this.getIdtxn()!=null && castOther.getIdtxn()!=null && this.getIdtxn().equals(castOther.getIdtxn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getUsertype() == null ? 0 : this.getUsertype().hashCode() );
         result = 37 * result + ( getIdchannel() == null ? 0 : this.getIdchannel().hashCode() );
         result = 37 * result + ( getIduseragent() == null ? 0 : this.getIduseragent().hashCode() );
         result = 37 * result + ( getIdtxn() == null ? 0 : this.getIdtxn().hashCode() );
         return result;
   }   


}


