package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstuidownload generated by hbm2java
 */
@Entity
@Table(name="MSTUIDOWNLOAD"
    ,schema="FCDBADMIN_RK"
)
public class Mstuidownload  implements java.io.Serializable {


     private MstuidownloadId id;
     private String typedownload;
     private String typeformat;
     private String path;
     private BigDecimal recordsperpage;
     private String sortcolumn;
     private String sortorder;
     private String adtnlParams;

    public Mstuidownload() {
    }

	
    public Mstuidownload(MstuidownloadId id) {
        this.id = id;
    }
    public Mstuidownload(MstuidownloadId id, String typedownload, String typeformat, String path, BigDecimal recordsperpage, String sortcolumn, String sortorder, String adtnlParams) {
       this.id = id;
       this.typedownload = typedownload;
       this.typeformat = typeformat;
       this.path = path;
       this.recordsperpage = recordsperpage;
       this.sortcolumn = sortcolumn;
       this.sortorder = sortorder;
       this.adtnlParams = adtnlParams;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=50) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ) } )
    public MstuidownloadId getId() {
        return this.id;
    }
    
    public void setId(MstuidownloadId id) {
        this.id = id;
    }

    
    @Column(name="TYPEDOWNLOAD", length=50)
    public String getTypedownload() {
        return this.typedownload;
    }
    
    public void setTypedownload(String typedownload) {
        this.typedownload = typedownload;
    }

    
    @Column(name="TYPEFORMAT", length=50)
    public String getTypeformat() {
        return this.typeformat;
    }
    
    public void setTypeformat(String typeformat) {
        this.typeformat = typeformat;
    }

    
    @Column(name="PATH")
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="RECORDSPERPAGE", precision=22, scale=0)
    public BigDecimal getRecordsperpage() {
        return this.recordsperpage;
    }
    
    public void setRecordsperpage(BigDecimal recordsperpage) {
        this.recordsperpage = recordsperpage;
    }

    
    @Column(name="SORTCOLUMN")
    public String getSortcolumn() {
        return this.sortcolumn;
    }
    
    public void setSortcolumn(String sortcolumn) {
        this.sortcolumn = sortcolumn;
    }

    
    @Column(name="SORTORDER")
    public String getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(String sortorder) {
        this.sortorder = sortorder;
    }

    
    @Column(name="ADTNL_PARAMS", length=4000)
    public String getAdtnlParams() {
        return this.adtnlParams;
    }
    
    public void setAdtnlParams(String adtnlParams) {
        this.adtnlParams = adtnlParams;
    }




}


