package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstwidgetId generated by hbm2java
 */
@Embeddable
public class MstwidgetId  implements java.io.Serializable {


     private String idEntity;
     private String usertype;
     private String idchannel;
     private String dashboardid;
     private String idtxn;
     private String idrequest;

    public MstwidgetId() {
    }

    public MstwidgetId(String idEntity, String usertype, String idchannel, String dashboardid, String idtxn, String idrequest) {
       this.idEntity = idEntity;
       this.usertype = usertype;
       this.idchannel = idchannel;
       this.dashboardid = dashboardid;
       this.idtxn = idtxn;
       this.idrequest = idrequest;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="USERTYPE", nullable=false, length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }


    @Column(name="IDCHANNEL", nullable=false, length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }


    @Column(name="DASHBOARDID", nullable=false, length=2)
    public String getDashboardid() {
        return this.dashboardid;
    }
    
    public void setDashboardid(String dashboardid) {
        this.dashboardid = dashboardid;
    }


    @Column(name="IDTXN", nullable=false, length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }


    @Column(name="IDREQUEST", nullable=false, length=8)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstwidgetId) ) return false;
		 MstwidgetId castOther = ( MstwidgetId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getUsertype()==castOther.getUsertype()) || ( this.getUsertype()!=null && castOther.getUsertype()!=null && this.getUsertype().equals(castOther.getUsertype()) ) )
 && ( (this.getIdchannel()==castOther.getIdchannel()) || ( this.getIdchannel()!=null && castOther.getIdchannel()!=null && this.getIdchannel().equals(castOther.getIdchannel()) ) )
 && ( (this.getDashboardid()==castOther.getDashboardid()) || ( this.getDashboardid()!=null && castOther.getDashboardid()!=null && this.getDashboardid().equals(castOther.getDashboardid()) ) )
 && ( (this.getIdtxn()==castOther.getIdtxn()) || ( this.getIdtxn()!=null && castOther.getIdtxn()!=null && this.getIdtxn().equals(castOther.getIdtxn()) ) )
 && ( (this.getIdrequest()==castOther.getIdrequest()) || ( this.getIdrequest()!=null && castOther.getIdrequest()!=null && this.getIdrequest().equals(castOther.getIdrequest()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getUsertype() == null ? 0 : this.getUsertype().hashCode() );
         result = 37 * result + ( getIdchannel() == null ? 0 : this.getIdchannel().hashCode() );
         result = 37 * result + ( getDashboardid() == null ? 0 : this.getDashboardid().hashCode() );
         result = 37 * result + ( getIdtxn() == null ? 0 : this.getIdtxn().hashCode() );
         result = 37 * result + ( getIdrequest() == null ? 0 : this.getIdrequest().hashCode() );
         return result;
   }   


}


