package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrigApplication generated by hbm2java
 */
@Entity
@Table(name="ORIG_APPLICATION"
    ,schema="FCDBADMIN_RK"
)
public class OrigApplication  implements java.io.Serializable {


     private String idfcatref;
     private Mstworkflow mstworkflow;
     private String iduser;
     private String idEntity;
     private String usertype;
     private String prodcategcode;
     private String prodcode;
     private BigDecimal status;
     private Date creationdate;
     private BigDecimal coapplicants;
     private String lockedby;
     private Serializable lockdatetime;
     private String idinteraction;
     private Character typprocess;
     private Date updationdate;
     private String remarks;
     private String proddesc;
     private String prodcategdesc;
     private String hostrefnumber;
     private Character initiatedBy;
     private Character completedBy;
     private String hostaccoutnbr;
     private String idchannel;
     private Date submittedon;
     private Set<OrigApplicationdetails> origApplicationdetailses = new HashSet<OrigApplicationdetails>(0);
     private Set<OrigApplicationShare> origApplicationShares = new HashSet<OrigApplicationShare>(0);
     private Set<OrigUploaddocs> origUploaddocses = new HashSet<OrigUploaddocs>(0);
     private Set<OrigApplicantdetails> origApplicantdetailses = new HashSet<OrigApplicantdetails>(0);

    public OrigApplication() {
    }

	
    public OrigApplication(String idfcatref) {
        this.idfcatref = idfcatref;
    }
    public OrigApplication(String idfcatref, Mstworkflow mstworkflow, String iduser, String idEntity, String usertype, String prodcategcode, String prodcode, BigDecimal status, Date creationdate, BigDecimal coapplicants, String lockedby, Serializable lockdatetime, String idinteraction, Character typprocess, Date updationdate, String remarks, String proddesc, String prodcategdesc, String hostrefnumber, Character initiatedBy, Character completedBy, String hostaccoutnbr, String idchannel, Date submittedon, Set<OrigApplicationdetails> origApplicationdetailses, Set<OrigApplicationShare> origApplicationShares, Set<OrigUploaddocs> origUploaddocses, Set<OrigApplicantdetails> origApplicantdetailses) {
       this.idfcatref = idfcatref;
       this.mstworkflow = mstworkflow;
       this.iduser = iduser;
       this.idEntity = idEntity;
       this.usertype = usertype;
       this.prodcategcode = prodcategcode;
       this.prodcode = prodcode;
       this.status = status;
       this.creationdate = creationdate;
       this.coapplicants = coapplicants;
       this.lockedby = lockedby;
       this.lockdatetime = lockdatetime;
       this.idinteraction = idinteraction;
       this.typprocess = typprocess;
       this.updationdate = updationdate;
       this.remarks = remarks;
       this.proddesc = proddesc;
       this.prodcategdesc = prodcategdesc;
       this.hostrefnumber = hostrefnumber;
       this.initiatedBy = initiatedBy;
       this.completedBy = completedBy;
       this.hostaccoutnbr = hostaccoutnbr;
       this.idchannel = idchannel;
       this.submittedon = submittedon;
       this.origApplicationdetailses = origApplicationdetailses;
       this.origApplicationShares = origApplicationShares;
       this.origUploaddocses = origUploaddocses;
       this.origApplicantdetailses = origApplicantdetailses;
    }
   
     @Id 

    
    @Column(name="IDFCATREF", unique=true, nullable=false, length=35)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IDWORKFLOW", referencedColumnName="IDWORKFLOW"), 
        @JoinColumn(name="WFVERSION", referencedColumnName="VERSION") } )
    public Mstworkflow getMstworkflow() {
        return this.mstworkflow;
    }
    
    public void setMstworkflow(Mstworkflow mstworkflow) {
        this.mstworkflow = mstworkflow;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="USERTYPE", length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    
    @Column(name="PRODCATEGCODE", length=10)
    public String getProdcategcode() {
        return this.prodcategcode;
    }
    
    public void setProdcategcode(String prodcategcode) {
        this.prodcategcode = prodcategcode;
    }

    
    @Column(name="PRODCODE", length=10)
    public String getProdcode() {
        return this.prodcode;
    }
    
    public void setProdcode(String prodcode) {
        this.prodcode = prodcode;
    }

    
    @Column(name="STATUS", precision=22, scale=0)
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATIONDATE", length=7)
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    
    @Column(name="COAPPLICANTS", precision=22, scale=0)
    public BigDecimal getCoapplicants() {
        return this.coapplicants;
    }
    
    public void setCoapplicants(BigDecimal coapplicants) {
        this.coapplicants = coapplicants;
    }

    
    @Column(name="LOCKEDBY", length=20)
    public String getLockedby() {
        return this.lockedby;
    }
    
    public void setLockedby(String lockedby) {
        this.lockedby = lockedby;
    }

    
    @Column(name="LOCKDATETIME")
    public Serializable getLockdatetime() {
        return this.lockdatetime;
    }
    
    public void setLockdatetime(Serializable lockdatetime) {
        this.lockdatetime = lockdatetime;
    }

    
    @Column(name="IDINTERACTION", length=20)
    public String getIdinteraction() {
        return this.idinteraction;
    }
    
    public void setIdinteraction(String idinteraction) {
        this.idinteraction = idinteraction;
    }

    
    @Column(name="TYPPROCESS", length=1)
    public Character getTypprocess() {
        return this.typprocess;
    }
    
    public void setTypprocess(Character typprocess) {
        this.typprocess = typprocess;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATIONDATE", length=7)
    public Date getUpdationdate() {
        return this.updationdate;
    }
    
    public void setUpdationdate(Date updationdate) {
        this.updationdate = updationdate;
    }

    
    @Column(name="REMARKS", length=500)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="PRODDESC")
    public String getProddesc() {
        return this.proddesc;
    }
    
    public void setProddesc(String proddesc) {
        this.proddesc = proddesc;
    }

    
    @Column(name="PRODCATEGDESC")
    public String getProdcategdesc() {
        return this.prodcategdesc;
    }
    
    public void setProdcategdesc(String prodcategdesc) {
        this.prodcategdesc = prodcategdesc;
    }

    
    @Column(name="HOSTREFNUMBER", length=100)
    public String getHostrefnumber() {
        return this.hostrefnumber;
    }
    
    public void setHostrefnumber(String hostrefnumber) {
        this.hostrefnumber = hostrefnumber;
    }

    
    @Column(name="INITIATED_BY", length=1)
    public Character getInitiatedBy() {
        return this.initiatedBy;
    }
    
    public void setInitiatedBy(Character initiatedBy) {
        this.initiatedBy = initiatedBy;
    }

    
    @Column(name="COMPLETED_BY", length=1)
    public Character getCompletedBy() {
        return this.completedBy;
    }
    
    public void setCompletedBy(Character completedBy) {
        this.completedBy = completedBy;
    }

    
    @Column(name="HOSTACCOUTNBR", length=20)
    public String getHostaccoutnbr() {
        return this.hostaccoutnbr;
    }
    
    public void setHostaccoutnbr(String hostaccoutnbr) {
        this.hostaccoutnbr = hostaccoutnbr;
    }

    
    @Column(name="IDCHANNEL", length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SUBMITTEDON", length=7)
    public Date getSubmittedon() {
        return this.submittedon;
    }
    
    public void setSubmittedon(Date submittedon) {
        this.submittedon = submittedon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="origApplication")
    public Set<OrigApplicationdetails> getOrigApplicationdetailses() {
        return this.origApplicationdetailses;
    }
    
    public void setOrigApplicationdetailses(Set<OrigApplicationdetails> origApplicationdetailses) {
        this.origApplicationdetailses = origApplicationdetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="origApplication")
    public Set<OrigApplicationShare> getOrigApplicationShares() {
        return this.origApplicationShares;
    }
    
    public void setOrigApplicationShares(Set<OrigApplicationShare> origApplicationShares) {
        this.origApplicationShares = origApplicationShares;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="origApplication")
    public Set<OrigUploaddocs> getOrigUploaddocses() {
        return this.origUploaddocses;
    }
    
    public void setOrigUploaddocses(Set<OrigUploaddocs> origUploaddocses) {
        this.origUploaddocses = origUploaddocses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="origApplication")
    public Set<OrigApplicantdetails> getOrigApplicantdetailses() {
        return this.origApplicantdetailses;
    }
    
    public void setOrigApplicantdetailses(Set<OrigApplicantdetails> origApplicantdetailses) {
        this.origApplicantdetailses = origApplicantdetailses;
    }




}


