package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrigProdcateg generated by hbm2java
 */
@Entity
@Table(name="ORIG_PRODCATEG"
    ,schema="FCDBADMIN_RK"
)
public class OrigProdcateg  implements java.io.Serializable {


     private OrigProdcategId id;
     private Mstentity mstentity;
     private Mstusertypes mstusertypes;
     private Character requiredcust;
     private Set<OrigProducts> origProductses = new HashSet<OrigProducts>(0);

    public OrigProdcateg() {
    }

	
    public OrigProdcateg(OrigProdcategId id, Mstentity mstentity, Mstusertypes mstusertypes) {
        this.id = id;
        this.mstentity = mstentity;
        this.mstusertypes = mstusertypes;
    }
    public OrigProdcateg(OrigProdcategId id, Mstentity mstentity, Mstusertypes mstusertypes, Character requiredcust, Set<OrigProducts> origProductses) {
       this.id = id;
       this.mstentity = mstentity;
       this.mstusertypes = mstusertypes;
       this.requiredcust = requiredcust;
       this.origProductses = origProductses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="prodcategcode", column=@Column(name="PRODCATEGCODE", nullable=false, length=10) ) } )
    public OrigProdcategId getId() {
        return this.id;
    }
    
    public void setId(OrigProdcategId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERTYPE", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }

    
    @Column(name="REQUIREDCUST", length=1)
    public Character getRequiredcust() {
        return this.requiredcust;
    }
    
    public void setRequiredcust(Character requiredcust) {
        this.requiredcust = requiredcust;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="origProdcateg")
    public Set<OrigProducts> getOrigProductses() {
        return this.origProductses;
    }
    
    public void setOrigProductses(Set<OrigProducts> origProductses) {
        this.origProductses = origProductses;
    }




}


