package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrigStatusFlow generated by hbm2java
 */
@Entity
@Table(name="ORIG_STATUS_FLOW"
    ,schema="FCDBADMIN_RK"
)
public class OrigStatusFlow  implements java.io.Serializable {


     private OrigStatusFlowId id;
     private OrigStatus origStatusByCodstatus;
     private OrigStatus origStatusByNextstatus;
     private String actiondesc;
     private String appActor;
     private String idSuccMsg;

    public OrigStatusFlow() {
    }

	
    public OrigStatusFlow(OrigStatusFlowId id, OrigStatus origStatusByCodstatus) {
        this.id = id;
        this.origStatusByCodstatus = origStatusByCodstatus;
    }
    public OrigStatusFlow(OrigStatusFlowId id, OrigStatus origStatusByCodstatus, OrigStatus origStatusByNextstatus, String actiondesc, String appActor, String idSuccMsg) {
       this.id = id;
       this.origStatusByCodstatus = origStatusByCodstatus;
       this.origStatusByNextstatus = origStatusByNextstatus;
       this.actiondesc = actiondesc;
       this.appActor = appActor;
       this.idSuccMsg = idSuccMsg;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codstatus", column=@Column(name="CODSTATUS", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="action", column=@Column(name="ACTION", nullable=false, length=2) ), 
        @AttributeOverride(name="actor", column=@Column(name="ACTOR", nullable=false, length=5) ) } )
    public OrigStatusFlowId getId() {
        return this.id;
    }
    
    public void setId(OrigStatusFlowId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODSTATUS", nullable=false, insertable=false, updatable=false)
    public OrigStatus getOrigStatusByCodstatus() {
        return this.origStatusByCodstatus;
    }
    
    public void setOrigStatusByCodstatus(OrigStatus origStatusByCodstatus) {
        this.origStatusByCodstatus = origStatusByCodstatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NEXTSTATUS")
    public OrigStatus getOrigStatusByNextstatus() {
        return this.origStatusByNextstatus;
    }
    
    public void setOrigStatusByNextstatus(OrigStatus origStatusByNextstatus) {
        this.origStatusByNextstatus = origStatusByNextstatus;
    }

    
    @Column(name="ACTIONDESC", length=100)
    public String getActiondesc() {
        return this.actiondesc;
    }
    
    public void setActiondesc(String actiondesc) {
        this.actiondesc = actiondesc;
    }

    
    @Column(name="APP_ACTOR", length=50)
    public String getAppActor() {
        return this.appActor;
    }
    
    public void setAppActor(String appActor) {
        this.appActor = appActor;
    }

    
    @Column(name="ID_SUCC_MSG", length=20)
    public String getIdSuccMsg() {
        return this.idSuccMsg;
    }
    
    public void setIdSuccMsg(String idSuccMsg) {
        this.idSuccMsg = idSuccMsg;
    }




}


