package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrigApplicationdetails generated by hbm2java
 */
@Entity
@Table(name="ORIG_APPLICATIONDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class OrigApplicationdetails  implements java.io.Serializable {


     private OrigApplicationdetailsId id;
     private OrigApplication origApplication;
     private String udfvalue;

    public OrigApplicationdetails() {
    }

	
    public OrigApplicationdetails(OrigApplicationdetailsId id, OrigApplication origApplication) {
        this.id = id;
        this.origApplication = origApplication;
    }
    public OrigApplicationdetails(OrigApplicationdetailsId id, OrigApplication origApplication, String udfvalue) {
       this.id = id;
       this.origApplication = origApplication;
       this.udfvalue = udfvalue;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idfcatref", column=@Column(name="IDFCATREF", nullable=false, length=35) ), 
        @AttributeOverride(name="udfname", column=@Column(name="UDFNAME", nullable=false, length=50) ) } )
    public OrigApplicationdetailsId getId() {
        return this.id;
    }
    
    public void setId(OrigApplicationdetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFCATREF", nullable=false, insertable=false, updatable=false)
    public OrigApplication getOrigApplication() {
        return this.origApplication;
    }
    
    public void setOrigApplication(OrigApplication origApplication) {
        this.origApplication = origApplication;
    }

    
    @Column(name="UDFVALUE")
    public String getUdfvalue() {
        return this.udfvalue;
    }
    
    public void setUdfvalue(String udfvalue) {
        this.udfvalue = udfvalue;
    }




}


