package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrigDoccategtypemap generated by hbm2java
 */
@Entity
@Table(name="ORIG_DOCCATEGTYPEMAP"
    ,schema="FCDBADMIN_RK"
)
public class OrigDoccategtypemap  implements java.io.Serializable {


     private OrigDoccategtypemapId id;

    public OrigDoccategtypemap() {
    }

    public OrigDoccategtypemap(OrigDoccategtypemapId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="prodcateg", column=@Column(name="PRODCATEG", nullable=false, length=10) ), 
        @AttributeOverride(name="prodcode", column=@Column(name="PRODCODE", nullable=false, length=10) ), 
        @AttributeOverride(name="doccateg", column=@Column(name="DOCCATEG", nullable=false, length=20) ), 
        @AttributeOverride(name="doctype", column=@Column(name="DOCTYPE", nullable=false, length=20) ) } )
    public OrigDoccategtypemapId getId() {
        return this.id;
    }
    
    public void setId(OrigDoccategtypemapId id) {
        this.id = id;
    }




}


