package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurgeDuration generated by hbm2java
 */
@Entity
@Table(name="PURGE_DURATION"
    ,schema="FCDBADMIN_RK"
)
public class PurgeDuration  implements java.io.Serializable {


     private BigDecimal seq;
     private String tabName;
     private Short duration;
     private String filtercolumn;
     private Character isArchive;
     private Character isDelete;
     private String extraCrit;
     private Date lastExecutionDate;
     private String archiveTable;
     private Date lastFailDate;
     private String failReason;

    public PurgeDuration() {
    }

	
    public PurgeDuration(BigDecimal seq) {
        this.seq = seq;
    }
    public PurgeDuration(BigDecimal seq, String tabName, Short duration, String filtercolumn, Character isArchive, Character isDelete, String extraCrit, Date lastExecutionDate, String archiveTable, Date lastFailDate, String failReason) {
       this.seq = seq;
       this.tabName = tabName;
       this.duration = duration;
       this.filtercolumn = filtercolumn;
       this.isArchive = isArchive;
       this.isDelete = isDelete;
       this.extraCrit = extraCrit;
       this.lastExecutionDate = lastExecutionDate;
       this.archiveTable = archiveTable;
       this.lastFailDate = lastFailDate;
       this.failReason = failReason;
    }
   
     @Id 

    
    @Column(name="SEQ", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getSeq() {
        return this.seq;
    }
    
    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }

    
    @Column(name="TAB_NAME", length=30)
    public String getTabName() {
        return this.tabName;
    }
    
    public void setTabName(String tabName) {
        this.tabName = tabName;
    }

    
    @Column(name="DURATION", precision=4, scale=0)
    public Short getDuration() {
        return this.duration;
    }
    
    public void setDuration(Short duration) {
        this.duration = duration;
    }

    
    @Column(name="FILTERCOLUMN")
    public String getFiltercolumn() {
        return this.filtercolumn;
    }
    
    public void setFiltercolumn(String filtercolumn) {
        this.filtercolumn = filtercolumn;
    }

    
    @Column(name="IS_ARCHIVE", length=1)
    public Character getIsArchive() {
        return this.isArchive;
    }
    
    public void setIsArchive(Character isArchive) {
        this.isArchive = isArchive;
    }

    
    @Column(name="IS_DELETE", length=1)
    public Character getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Character isDelete) {
        this.isDelete = isDelete;
    }

    
    @Column(name="EXTRA_CRIT")
    public String getExtraCrit() {
        return this.extraCrit;
    }
    
    public void setExtraCrit(String extraCrit) {
        this.extraCrit = extraCrit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_EXECUTION_DATE", length=7)
    public Date getLastExecutionDate() {
        return this.lastExecutionDate;
    }
    
    public void setLastExecutionDate(Date lastExecutionDate) {
        this.lastExecutionDate = lastExecutionDate;
    }

    
    @Column(name="ARCHIVE_TABLE", length=30)
    public String getArchiveTable() {
        return this.archiveTable;
    }
    
    public void setArchiveTable(String archiveTable) {
        this.archiveTable = archiveTable;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_FAIL_DATE", length=7)
    public Date getLastFailDate() {
        return this.lastFailDate;
    }
    
    public void setLastFailDate(Date lastFailDate) {
        this.lastFailDate = lastFailDate;
    }

    
    @Column(name="FAIL_REASON")
    public String getFailReason() {
        return this.failReason;
    }
    
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }




}


