package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Rmscontent generated by hbm2java
 */
@Entity
@Table(name="RMSCONTENT"
    ,schema="FCDBADMIN_RK"
)
public class Rmscontent  implements java.io.Serializable {


     private RmscontentId id;
     private Blob filecontent;

    public Rmscontent() {
    }

	
    public Rmscontent(RmscontentId id) {
        this.id = id;
    }
    public Rmscontent(RmscontentId id, Blob filecontent) {
       this.id = id;
       this.filecontent = filecontent;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduseragent", column=@Column(name="IDUSERAGENT", nullable=false, length=35) ), 
        @AttributeOverride(name="iddevice", column=@Column(name="IDDEVICE", nullable=false, length=35) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", nullable=false, precision=4) ) } )
    public RmscontentId getId() {
        return this.id;
    }
    
    public void setId(RmscontentId id) {
        this.id = id;
    }

    
    @Column(name="FILECONTENT")
    public Blob getFilecontent() {
        return this.filecontent;
    }
    
    public void setFilecontent(Blob filecontent) {
        this.filecontent = filecontent;
    }




}


