package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rmsfileupload generated by hbm2java
 */
@Entity
@Table(name="RMSFILEUPLOAD"
    ,schema="FCDBADMIN_RK"
)
public class Rmsfileupload  implements java.io.Serializable {


     private RmsfileuploadId id;
     private String hashcode;
     private String url;
     private BigDecimal filesize;
     private Blob filecontent;
     private String filetype;
     private String contenttype;
     private Character isencrypted;
     private Character iscompressed;
     private Date datupload;
     private String identity;
     private String usertype;
     private String idlang;
     private String theme;

    public Rmsfileupload() {
    }

	
    public Rmsfileupload(RmsfileuploadId id) {
        this.id = id;
    }
    public Rmsfileupload(RmsfileuploadId id, String hashcode, String url, BigDecimal filesize, Blob filecontent, String filetype, String contenttype, Character isencrypted, Character iscompressed, Date datupload, String identity, String usertype, String idlang, String theme) {
       this.id = id;
       this.hashcode = hashcode;
       this.url = url;
       this.filesize = filesize;
       this.filecontent = filecontent;
       this.filetype = filetype;
       this.contenttype = contenttype;
       this.isencrypted = isencrypted;
       this.iscompressed = iscompressed;
       this.datupload = datupload;
       this.identity = identity;
       this.usertype = usertype;
       this.idlang = idlang;
       this.theme = theme;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduseragent", column=@Column(name="IDUSERAGENT", nullable=false, length=35) ), 
        @AttributeOverride(name="iddevice", column=@Column(name="IDDEVICE", nullable=false, length=35) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", nullable=false, precision=4) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", nullable=false) ) } )
    public RmsfileuploadId getId() {
        return this.id;
    }
    
    public void setId(RmsfileuploadId id) {
        this.id = id;
    }

    
    @Column(name="HASHCODE", length=100)
    public String getHashcode() {
        return this.hashcode;
    }
    
    public void setHashcode(String hashcode) {
        this.hashcode = hashcode;
    }

    
    @Column(name="URL", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="FILESIZE", precision=22, scale=0)
    public BigDecimal getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(BigDecimal filesize) {
        this.filesize = filesize;
    }

    
    @Column(name="FILECONTENT")
    public Blob getFilecontent() {
        return this.filecontent;
    }
    
    public void setFilecontent(Blob filecontent) {
        this.filecontent = filecontent;
    }

    
    @Column(name="FILETYPE", length=3)
    public String getFiletype() {
        return this.filetype;
    }
    
    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    
    @Column(name="CONTENTTYPE", length=100)
    public String getContenttype() {
        return this.contenttype;
    }
    
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype;
    }

    
    @Column(name="ISENCRYPTED", length=1)
    public Character getIsencrypted() {
        return this.isencrypted;
    }
    
    public void setIsencrypted(Character isencrypted) {
        this.isencrypted = isencrypted;
    }

    
    @Column(name="ISCOMPRESSED", length=1)
    public Character getIscompressed() {
        return this.iscompressed;
    }
    
    public void setIscompressed(Character iscompressed) {
        this.iscompressed = iscompressed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPLOAD", length=7)
    public Date getDatupload() {
        return this.datupload;
    }
    
    public void setDatupload(Date datupload) {
        this.datupload = datupload;
    }

    
    @Column(name="IDENTITY", length=5)
    public String getIdentity() {
        return this.identity;
    }
    
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    
    @Column(name="USERTYPE", length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    
    @Column(name="IDLANG", length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }

    
    @Column(name="THEME", length=10)
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }




}


