package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RouterauditlogId generated by hbm2java
 */
@Embeddable
public class RouterauditlogId  implements java.io.Serializable {


     private String idinvocation;
     private BigDecimal idseq;

    public RouterauditlogId() {
    }

    public RouterauditlogId(String idinvocation, BigDecimal idseq) {
       this.idinvocation = idinvocation;
       this.idseq = idseq;
    }
   


    @Column(name="IDINVOCATION", nullable=false)
    public String getIdinvocation() {
        return this.idinvocation;
    }
    
    public void setIdinvocation(String idinvocation) {
        this.idinvocation = idinvocation;
    }


    @Column(name="IDSEQ", nullable=false, precision=22, scale=0)
    public BigDecimal getIdseq() {
        return this.idseq;
    }
    
    public void setIdseq(BigDecimal idseq) {
        this.idseq = idseq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RouterauditlogId) ) return false;
		 RouterauditlogId castOther = ( RouterauditlogId ) other; 
         
		 return ( (this.getIdinvocation()==castOther.getIdinvocation()) || ( this.getIdinvocation()!=null && castOther.getIdinvocation()!=null && this.getIdinvocation().equals(castOther.getIdinvocation()) ) )
 && ( (this.getIdseq()==castOther.getIdseq()) || ( this.getIdseq()!=null && castOther.getIdseq()!=null && this.getIdseq().equals(castOther.getIdseq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdinvocation() == null ? 0 : this.getIdinvocation().hashCode() );
         result = 37 * result + ( getIdseq() == null ? 0 : this.getIdseq().hashCode() );
         return result;
   }   


}


