package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Simulatormapping generated by hbm2java
 */
@Entity
@Table(name="SIMULATORMAPPING"
    ,schema="FCDBADMIN_RK"
)
public class Simulatormapping  implements java.io.Serializable {


     private SimulatormappingId id;
     private String evaluatexpath;
     private String simfilename;
     private String comments;

    public Simulatormapping() {
    }

	
    public Simulatormapping(SimulatormappingId id) {
        this.id = id;
    }
    public Simulatormapping(SimulatormappingId id, String evaluatexpath, String simfilename, String comments) {
       this.id = id;
       this.evaluatexpath = evaluatexpath;
       this.simfilename = simfilename;
       this.comments = comments;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="servicename", column=@Column(name="SERVICENAME", nullable=false, length=50) ), 
        @AttributeOverride(name="operationcode", column=@Column(name="OPERATIONCODE", nullable=false, length=50) ), 
        @AttributeOverride(name="priority", column=@Column(name="PRIORITY", nullable=false, precision=22, scale=0) ) } )
    public SimulatormappingId getId() {
        return this.id;
    }
    
    public void setId(SimulatormappingId id) {
        this.id = id;
    }

    
    @Column(name="EVALUATEXPATH", length=4000)
    public String getEvaluatexpath() {
        return this.evaluatexpath;
    }
    
    public void setEvaluatexpath(String evaluatexpath) {
        this.evaluatexpath = evaluatexpath;
    }

    
    @Column(name="SIMFILENAME", length=100)
    public String getSimfilename() {
        return this.simfilename;
    }
    
    public void setSimfilename(String simfilename) {
        this.simfilename = simfilename;
    }

    
    @Column(name="COMMENTS", length=4000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


