package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SwIsoCt generated by hbm2java
 */
@Entity
@Table(name="SW_ISO_CT"
    ,schema="FCDBADMIN_RK"
)
public class SwIsoCt  implements java.io.Serializable {


     private String codCountry;
     private String namCountryFull;
     private String namCountry1;
     private String namCountry2;
     private String isenabled;
     private Date datlastupdated;
     private Set<SwIsoCu> swIsoCus = new HashSet<SwIsoCu>(0);

    public SwIsoCt() {
    }

	
    public SwIsoCt(String codCountry) {
        this.codCountry = codCountry;
    }
    public SwIsoCt(String codCountry, String namCountryFull, String namCountry1, String namCountry2, String isenabled, Date datlastupdated, Set<SwIsoCu> swIsoCus) {
       this.codCountry = codCountry;
       this.namCountryFull = namCountryFull;
       this.namCountry1 = namCountry1;
       this.namCountry2 = namCountry2;
       this.isenabled = isenabled;
       this.datlastupdated = datlastupdated;
       this.swIsoCus = swIsoCus;
    }
   
     @Id 

    
    @Column(name="COD_COUNTRY", unique=true, nullable=false, length=2)
    public String getCodCountry() {
        return this.codCountry;
    }
    
    public void setCodCountry(String codCountry) {
        this.codCountry = codCountry;
    }

    
    @Column(name="NAM_COUNTRY_FULL", length=70)
    public String getNamCountryFull() {
        return this.namCountryFull;
    }
    
    public void setNamCountryFull(String namCountryFull) {
        this.namCountryFull = namCountryFull;
    }

    
    @Column(name="NAM_COUNTRY1", length=35)
    public String getNamCountry1() {
        return this.namCountry1;
    }
    
    public void setNamCountry1(String namCountry1) {
        this.namCountry1 = namCountry1;
    }

    
    @Column(name="NAM_COUNTRY2", length=35)
    public String getNamCountry2() {
        return this.namCountry2;
    }
    
    public void setNamCountry2(String namCountry2) {
        this.namCountry2 = namCountry2;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTUPDATED", length=7)
    public Date getDatlastupdated() {
        return this.datlastupdated;
    }
    
    public void setDatlastupdated(Date datlastupdated) {
        this.datlastupdated = datlastupdated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="swIsoCt")
    public Set<SwIsoCu> getSwIsoCus() {
        return this.swIsoCus;
    }
    
    public void setSwIsoCus(Set<SwIsoCu> swIsoCus) {
        this.swIsoCus = swIsoCus;
    }




}


