package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TxnDataMaster generated by hbm2java
 */
@Entity
@Table(name="TXN_DATA_MASTER"
    ,schema="FCDBADMIN_RK"
)
public class TxnDataMaster  implements java.io.Serializable {


     private String idrequest;
     private String txnDesc;
     private String customValidator;
     private String namschema;
     private Character typerequest;
     private String refrequest;
     private String comments;
     private Character isfinrequest;
     private BigDecimal totalfields;
     private BigDecimal moderequest;
     private String sepstring;
     private String encoding;
     private String prefix;
     private String postfix;
     private String terminator;
     private BigDecimal adjustment;
     private Character biztype;
     private String freetext;
     private Character islenient;
     private Set<Mstbatchrecords> mstbatchrecordses = new HashSet<Mstbatchrecords>(0);
     private Set<Batchtemplateimpl> batchtemplateimpls = new HashSet<Batchtemplateimpl>(0);

    public TxnDataMaster() {
    }

	
    public TxnDataMaster(String idrequest) {
        this.idrequest = idrequest;
    }
    public TxnDataMaster(String idrequest, String txnDesc, String customValidator, String namschema, Character typerequest, String refrequest, String comments, Character isfinrequest, BigDecimal totalfields, BigDecimal moderequest, String sepstring, String encoding, String prefix, String postfix, String terminator, BigDecimal adjustment, Character biztype, String freetext, Character islenient, Set<Mstbatchrecords> mstbatchrecordses, Set<Batchtemplateimpl> batchtemplateimpls) {
       this.idrequest = idrequest;
       this.txnDesc = txnDesc;
       this.customValidator = customValidator;
       this.namschema = namschema;
       this.typerequest = typerequest;
       this.refrequest = refrequest;
       this.comments = comments;
       this.isfinrequest = isfinrequest;
       this.totalfields = totalfields;
       this.moderequest = moderequest;
       this.sepstring = sepstring;
       this.encoding = encoding;
       this.prefix = prefix;
       this.postfix = postfix;
       this.terminator = terminator;
       this.adjustment = adjustment;
       this.biztype = biztype;
       this.freetext = freetext;
       this.islenient = islenient;
       this.mstbatchrecordses = mstbatchrecordses;
       this.batchtemplateimpls = batchtemplateimpls;
    }
   
     @Id 

    
    @Column(name="IDREQUEST", unique=true, nullable=false)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="TXN_DESC")
    public String getTxnDesc() {
        return this.txnDesc;
    }
    
    public void setTxnDesc(String txnDesc) {
        this.txnDesc = txnDesc;
    }

    
    @Column(name="CUSTOM_VALIDATOR", length=1000)
    public String getCustomValidator() {
        return this.customValidator;
    }
    
    public void setCustomValidator(String customValidator) {
        this.customValidator = customValidator;
    }

    
    @Column(name="NAMSCHEMA")
    public String getNamschema() {
        return this.namschema;
    }
    
    public void setNamschema(String namschema) {
        this.namschema = namschema;
    }

    
    @Column(name="TYPEREQUEST", length=1)
    public Character getTyperequest() {
        return this.typerequest;
    }
    
    public void setTyperequest(Character typerequest) {
        this.typerequest = typerequest;
    }

    
    @Column(name="REFREQUEST", length=2000)
    public String getRefrequest() {
        return this.refrequest;
    }
    
    public void setRefrequest(String refrequest) {
        this.refrequest = refrequest;
    }

    
    @Column(name="COMMENTS", length=4000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="ISFINREQUEST", length=1)
    public Character getIsfinrequest() {
        return this.isfinrequest;
    }
    
    public void setIsfinrequest(Character isfinrequest) {
        this.isfinrequest = isfinrequest;
    }

    
    @Column(name="TOTALFIELDS", precision=22, scale=0)
    public BigDecimal getTotalfields() {
        return this.totalfields;
    }
    
    public void setTotalfields(BigDecimal totalfields) {
        this.totalfields = totalfields;
    }

    
    @Column(name="MODEREQUEST", precision=38, scale=0)
    public BigDecimal getModerequest() {
        return this.moderequest;
    }
    
    public void setModerequest(BigDecimal moderequest) {
        this.moderequest = moderequest;
    }

    
    @Column(name="SEPSTRING", length=10)
    public String getSepstring() {
        return this.sepstring;
    }
    
    public void setSepstring(String sepstring) {
        this.sepstring = sepstring;
    }

    
    @Column(name="ENCODING", length=20)
    public String getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }

    
    @Column(name="PREFIX", length=15)
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    
    @Column(name="POSTFIX", length=10)
    public String getPostfix() {
        return this.postfix;
    }
    
    public void setPostfix(String postfix) {
        this.postfix = postfix;
    }

    
    @Column(name="TERMINATOR")
    public String getTerminator() {
        return this.terminator;
    }
    
    public void setTerminator(String terminator) {
        this.terminator = terminator;
    }

    
    @Column(name="ADJUSTMENT", precision=38, scale=0)
    public BigDecimal getAdjustment() {
        return this.adjustment;
    }
    
    public void setAdjustment(BigDecimal adjustment) {
        this.adjustment = adjustment;
    }

    
    @Column(name="BIZTYPE", length=1)
    public Character getBiztype() {
        return this.biztype;
    }
    
    public void setBiztype(Character biztype) {
        this.biztype = biztype;
    }

    
    @Column(name="FREETEXT", length=2000)
    public String getFreetext() {
        return this.freetext;
    }
    
    public void setFreetext(String freetext) {
        this.freetext = freetext;
    }

    
    @Column(name="ISLENIENT", length=1)
    public Character getIslenient() {
        return this.islenient;
    }
    
    public void setIslenient(Character islenient) {
        this.islenient = islenient;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="txnDataMaster")
    public Set<Mstbatchrecords> getMstbatchrecordses() {
        return this.mstbatchrecordses;
    }
    
    public void setMstbatchrecordses(Set<Mstbatchrecords> mstbatchrecordses) {
        this.mstbatchrecordses = mstbatchrecordses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="txnDataMaster")
    public Set<Batchtemplateimpl> getBatchtemplateimpls() {
        return this.batchtemplateimpls;
    }
    
    public void setBatchtemplateimpls(Set<Batchtemplateimpl> batchtemplateimpls) {
        this.batchtemplateimpls = batchtemplateimpls;
    }




}


