package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TxnDataEnrichment generated by hbm2java
 */
@Entity
@Table(name="TXN_DATA_ENRICHMENT"
    ,schema="FCDBADMIN_RK"
)
public class TxnDataEnrichment  implements java.io.Serializable {


     private String enname;
     private Character entype;
     private BigDecimal ennumparams;
     private String enparamfields;
     private String enjavaclass;
     private String enreplacemap;
     private String enquery;
     private String endescrption;
     private String enjavaclassdesc;
     private Character loadflag;

    public TxnDataEnrichment() {
    }

	
    public TxnDataEnrichment(String enname) {
        this.enname = enname;
    }
    public TxnDataEnrichment(String enname, Character entype, BigDecimal ennumparams, String enparamfields, String enjavaclass, String enreplacemap, String enquery, String endescrption, String enjavaclassdesc, Character loadflag) {
       this.enname = enname;
       this.entype = entype;
       this.ennumparams = ennumparams;
       this.enparamfields = enparamfields;
       this.enjavaclass = enjavaclass;
       this.enreplacemap = enreplacemap;
       this.enquery = enquery;
       this.endescrption = endescrption;
       this.enjavaclassdesc = enjavaclassdesc;
       this.loadflag = loadflag;
    }
   
     @Id 

    
    @Column(name="ENNAME", unique=true, nullable=false)
    public String getEnname() {
        return this.enname;
    }
    
    public void setEnname(String enname) {
        this.enname = enname;
    }

    
    @Column(name="ENTYPE", length=1)
    public Character getEntype() {
        return this.entype;
    }
    
    public void setEntype(Character entype) {
        this.entype = entype;
    }

    
    @Column(name="ENNUMPARAMS", precision=38, scale=0)
    public BigDecimal getEnnumparams() {
        return this.ennumparams;
    }
    
    public void setEnnumparams(BigDecimal ennumparams) {
        this.ennumparams = ennumparams;
    }

    
    @Column(name="ENPARAMFIELDS", length=2000)
    public String getEnparamfields() {
        return this.enparamfields;
    }
    
    public void setEnparamfields(String enparamfields) {
        this.enparamfields = enparamfields;
    }

    
    @Column(name="ENJAVACLASS")
    public String getEnjavaclass() {
        return this.enjavaclass;
    }
    
    public void setEnjavaclass(String enjavaclass) {
        this.enjavaclass = enjavaclass;
    }

    
    @Column(name="ENREPLACEMAP")
    public String getEnreplacemap() {
        return this.enreplacemap;
    }
    
    public void setEnreplacemap(String enreplacemap) {
        this.enreplacemap = enreplacemap;
    }

    
    @Column(name="ENQUERY", length=1000)
    public String getEnquery() {
        return this.enquery;
    }
    
    public void setEnquery(String enquery) {
        this.enquery = enquery;
    }

    
    @Column(name="ENDESCRPTION")
    public String getEndescrption() {
        return this.endescrption;
    }
    
    public void setEndescrption(String endescrption) {
        this.endescrption = endescrption;
    }

    
    @Column(name="ENJAVACLASSDESC", length=200)
    public String getEnjavaclassdesc() {
        return this.enjavaclassdesc;
    }
    
    public void setEnjavaclassdesc(String enjavaclassdesc) {
        this.enjavaclassdesc = enjavaclassdesc;
    }

    
    @Column(name="LOADFLAG", length=1)
    public Character getLoadflag() {
        return this.loadflag;
    }
    
    public void setLoadflag(Character loadflag) {
        this.loadflag = loadflag;
    }




}


