package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txninitauthdata generated by hbm2java
 */
@Entity
@Table(name="TXNINITAUTHDATA"
    ,schema="FCDBADMIN_RK"
)
public class Txninitauthdata  implements java.io.Serializable {


     private String txninitrefno;
     private String idEntity;
     private String iduser;
     private String txnsessionpin;
     private Date dataccessed;
     private Date expirydate;
     private String namservice;
     private BigDecimal versionservice;
     private Byte count;
     private Blob requestdata;
     private String idrequest;
     private Byte curtxninitflowhandler;
     private Byte secquesatmptct;
     private String secquesasked;

    public Txninitauthdata() {
    }

	
    public Txninitauthdata(String txninitrefno) {
        this.txninitrefno = txninitrefno;
    }
    public Txninitauthdata(String txninitrefno, String idEntity, String iduser, String txnsessionpin, Date dataccessed, Date expirydate, String namservice, BigDecimal versionservice, Byte count, Blob requestdata, String idrequest, Byte curtxninitflowhandler, Byte secquesatmptct, String secquesasked) {
       this.txninitrefno = txninitrefno;
       this.idEntity = idEntity;
       this.iduser = iduser;
       this.txnsessionpin = txnsessionpin;
       this.dataccessed = dataccessed;
       this.expirydate = expirydate;
       this.namservice = namservice;
       this.versionservice = versionservice;
       this.count = count;
       this.requestdata = requestdata;
       this.idrequest = idrequest;
       this.curtxninitflowhandler = curtxninitflowhandler;
       this.secquesatmptct = secquesatmptct;
       this.secquesasked = secquesasked;
    }
   
     @Id 

    
    @Column(name="TXNINITREFNO", unique=true, nullable=false, length=25)
    public String getTxninitrefno() {
        return this.txninitrefno;
    }
    
    public void setTxninitrefno(String txninitrefno) {
        this.txninitrefno = txninitrefno;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="TXNSESSIONPIN", length=4000)
    public String getTxnsessionpin() {
        return this.txnsessionpin;
    }
    
    public void setTxnsessionpin(String txnsessionpin) {
        this.txnsessionpin = txnsessionpin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATACCESSED", length=7)
    public Date getDataccessed() {
        return this.dataccessed;
    }
    
    public void setDataccessed(Date dataccessed) {
        this.dataccessed = dataccessed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRYDATE", length=7)
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    
    @Column(name="NAMSERVICE", length=4000)
    public String getNamservice() {
        return this.namservice;
    }
    
    public void setNamservice(String namservice) {
        this.namservice = namservice;
    }

    
    @Column(name="VERSIONSERVICE", precision=22, scale=0)
    public BigDecimal getVersionservice() {
        return this.versionservice;
    }
    
    public void setVersionservice(BigDecimal versionservice) {
        this.versionservice = versionservice;
    }

    
    @Column(name="COUNT", precision=2, scale=0)
    public Byte getCount() {
        return this.count;
    }
    
    public void setCount(Byte count) {
        this.count = count;
    }

    
    @Column(name="REQUESTDATA")
    public Blob getRequestdata() {
        return this.requestdata;
    }
    
    public void setRequestdata(Blob requestdata) {
        this.requestdata = requestdata;
    }

    
    @Column(name="IDREQUEST", length=8)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="CURTXNINITFLOWHANDLER", precision=2, scale=0)
    public Byte getCurtxninitflowhandler() {
        return this.curtxninitflowhandler;
    }
    
    public void setCurtxninitflowhandler(Byte curtxninitflowhandler) {
        this.curtxninitflowhandler = curtxninitflowhandler;
    }

    
    @Column(name="SECQUESATMPTCT", precision=2, scale=0)
    public Byte getSecquesatmptct() {
        return this.secquesatmptct;
    }
    
    public void setSecquesatmptct(Byte secquesatmptct) {
        this.secquesatmptct = secquesatmptct;
    }

    
    @Column(name="SECQUESASKED")
    public String getSecquesasked() {
        return this.secquesasked;
    }
    
    public void setSecquesasked(String secquesasked) {
        this.secquesasked = secquesasked;
    }




}


