package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txntasks generated by hbm2java
 */
@Entity
@Table(name="TXNTASKS"
    ,schema="FCDBADMIN_RK"
)
public class Txntasks  implements java.io.Serializable {


     private String idfcatref;
     private String tasktype;
     private String iduser;
     private Character scheduletype;
     private BigDecimal taskinterval;
     private String scheduleflags;
     private String additionalflags;
     private Date createdate;
     private Date startdate;
     private String starttime;
     private Date enddate;
     private String endtime;
     private Date nextdate;
     private Date lastdate;
     private String execcode;
     private Character status;
     private String jvmid;
     private Set<Txnreport> txnreports = new HashSet<Txnreport>(0);

    public Txntasks() {
    }

	
    public Txntasks(String idfcatref) {
        this.idfcatref = idfcatref;
    }
    public Txntasks(String idfcatref, String tasktype, String iduser, Character scheduletype, BigDecimal taskinterval, String scheduleflags, String additionalflags, Date createdate, Date startdate, String starttime, Date enddate, String endtime, Date nextdate, Date lastdate, String execcode, Character status, String jvmid, Set<Txnreport> txnreports) {
       this.idfcatref = idfcatref;
       this.tasktype = tasktype;
       this.iduser = iduser;
       this.scheduletype = scheduletype;
       this.taskinterval = taskinterval;
       this.scheduleflags = scheduleflags;
       this.additionalflags = additionalflags;
       this.createdate = createdate;
       this.startdate = startdate;
       this.starttime = starttime;
       this.enddate = enddate;
       this.endtime = endtime;
       this.nextdate = nextdate;
       this.lastdate = lastdate;
       this.execcode = execcode;
       this.status = status;
       this.jvmid = jvmid;
       this.txnreports = txnreports;
    }
   
     @Id 

    
    @Column(name="IDFCATREF", unique=true, nullable=false, length=20)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

    
    @Column(name="TASKTYPE", length=20)
    public String getTasktype() {
        return this.tasktype;
    }
    
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="SCHEDULETYPE", length=1)
    public Character getScheduletype() {
        return this.scheduletype;
    }
    
    public void setScheduletype(Character scheduletype) {
        this.scheduletype = scheduletype;
    }

    
    @Column(name="TASKINTERVAL", precision=22, scale=0)
    public BigDecimal getTaskinterval() {
        return this.taskinterval;
    }
    
    public void setTaskinterval(BigDecimal taskinterval) {
        this.taskinterval = taskinterval;
    }

    
    @Column(name="SCHEDULEFLAGS", length=100)
    public String getScheduleflags() {
        return this.scheduleflags;
    }
    
    public void setScheduleflags(String scheduleflags) {
        this.scheduleflags = scheduleflags;
    }

    
    @Column(name="ADDITIONALFLAGS", length=500)
    public String getAdditionalflags() {
        return this.additionalflags;
    }
    
    public void setAdditionalflags(String additionalflags) {
        this.additionalflags = additionalflags;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDATE", length=7)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STARTDATE", length=7)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    
    @Column(name="STARTTIME", length=15)
    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENDDATE", length=7)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    
    @Column(name="ENDTIME", length=15)
    public String getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NEXTDATE", length=7)
    public Date getNextdate() {
        return this.nextdate;
    }
    
    public void setNextdate(Date nextdate) {
        this.nextdate = nextdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTDATE", length=7)
    public Date getLastdate() {
        return this.lastdate;
    }
    
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    
    @Column(name="EXECCODE", length=10)
    public String getExeccode() {
        return this.execcode;
    }
    
    public void setExeccode(String execcode) {
        this.execcode = execcode;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="JVMID", length=20)
    public String getJvmid() {
        return this.jvmid;
    }
    
    public void setJvmid(String jvmid) {
        this.jvmid = jvmid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="txntasks")
    public Set<Txnreport> getTxnreports() {
        return this.txnreports;
    }
    
    public void setTxnreports(Set<Txnreport> txnreports) {
        this.txnreports = txnreports;
    }




}


