package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usergroupmap generated by hbm2java
 */
@Entity
@Table(name="USERGROUPMAP"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDUSER", "DTIME", "SLNO"}) 
)
public class Usergroupmap  implements java.io.Serializable {


     private String iduser;
     private String idgroup;
     private Date datassigned;
     private String makerid;
     private String checkerid;
     private Date dtime;
     private BigDecimal slno;

    public Usergroupmap() {
    }

	
    public Usergroupmap(String iduser) {
        this.iduser = iduser;
    }
    public Usergroupmap(String iduser, String idgroup, Date datassigned, String makerid, String checkerid, Date dtime, BigDecimal slno) {
       this.iduser = iduser;
       this.idgroup = idgroup;
       this.datassigned = datassigned;
       this.makerid = makerid;
       this.checkerid = checkerid;
       this.dtime = dtime;
       this.slno = slno;
    }
   
     @Id 

    
    @Column(name="IDUSER", unique=true, nullable=false, length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="IDGROUP", length=20)
    public String getIdgroup() {
        return this.idgroup;
    }
    
    public void setIdgroup(String idgroup) {
        this.idgroup = idgroup;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATASSIGNED", length=7)
    public Date getDatassigned() {
        return this.datassigned;
    }
    
    public void setDatassigned(Date datassigned) {
        this.datassigned = datassigned;
    }

    
    @Column(name="MAKERID", length=20)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    
    @Column(name="CHECKERID", length=20)
    public String getCheckerid() {
        return this.checkerid;
    }
    
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }




}


