package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WizardDependancyMap generated by hbm2java
 */
@Entity
@Table(name="WIZARD_DEPENDANCY_MAP"
    ,schema="FCDBADMIN_RK"
)
public class WizardDependancyMap  implements java.io.Serializable {


     private WizardDependancyMapId id;

    public WizardDependancyMap() {
    }

    public WizardDependancyMap(WizardDependancyMapId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="depIdrequest", column=@Column(name="DEP_IDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="depIdchannel", column=@Column(name="DEP_IDCHANNEL", nullable=false, length=2) ) } )
    public WizardDependancyMapId getId() {
        return this.id;
    }
    
    public void setId(WizardDependancyMapId id) {
        this.id = id;
    }




}


