package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Wizarddetails generated by hbm2java
 */
@Entity
@Table(name="WIZARDDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class Wizarddetails  implements java.io.Serializable {


     private WizarddetailsId id;
     private String idrequest;
     private String resIdrequest;
     private Character ismandatory;
     private String idtxn;
     private String stepVerifier;

    public Wizarddetails() {
    }

	
    public Wizarddetails(WizarddetailsId id) {
        this.id = id;
    }
    public Wizarddetails(WizarddetailsId id, String idrequest, String resIdrequest, Character ismandatory, String idtxn, String stepVerifier) {
       this.id = id;
       this.idrequest = idrequest;
       this.resIdrequest = resIdrequest;
       this.ismandatory = ismandatory;
       this.idtxn = idtxn;
       this.stepVerifier = stepVerifier;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idwizard", column=@Column(name="IDWIZARD", nullable=false, length=20) ), 
        @AttributeOverride(name="stepseq", column=@Column(name="STEPSEQ", nullable=false, precision=2, scale=0) ) } )
    public WizarddetailsId getId() {
        return this.id;
    }
    
    public void setId(WizarddetailsId id) {
        this.id = id;
    }

    
    @Column(name="IDREQUEST", length=8)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="RES_IDREQUEST", length=8)
    public String getResIdrequest() {
        return this.resIdrequest;
    }
    
    public void setResIdrequest(String resIdrequest) {
        this.resIdrequest = resIdrequest;
    }

    
    @Column(name="ISMANDATORY", length=1)
    public Character getIsmandatory() {
        return this.ismandatory;
    }
    
    public void setIsmandatory(Character ismandatory) {
        this.ismandatory = ismandatory;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="STEP_VERIFIER", length=500)
    public String getStepVerifier() {
        return this.stepVerifier;
    }
    
    public void setStepVerifier(String stepVerifier) {
        this.stepVerifier = stepVerifier;
    }




}


