package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Workflowsteps generated by hbm2java
 */
@Entity
@Table(name="WORKFLOWSTEPS"
    ,schema="FCDBADMIN_RK"
)
public class Workflowsteps  implements java.io.Serializable {


     private WorkflowstepsId id;
     private String idrequest;
     private String stepname;
     private String stepdesc;
     private String adtnlParams;
     private BigDecimal stepseq;
     private Character replicable;
     private String status;
     private Character typestep;

    public Workflowsteps() {
    }

	
    public Workflowsteps(WorkflowstepsId id) {
        this.id = id;
    }
    public Workflowsteps(WorkflowstepsId id, String idrequest, String stepname, String stepdesc, String adtnlParams, BigDecimal stepseq, Character replicable, String status, Character typestep) {
       this.id = id;
       this.idrequest = idrequest;
       this.stepname = stepname;
       this.stepdesc = stepdesc;
       this.adtnlParams = adtnlParams;
       this.stepseq = stepseq;
       this.replicable = replicable;
       this.status = status;
       this.typestep = typestep;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idworkflow", column=@Column(name="IDWORKFLOW", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idstep", column=@Column(name="IDSTEP", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ) } )
    public WorkflowstepsId getId() {
        return this.id;
    }
    
    public void setId(WorkflowstepsId id) {
        this.id = id;
    }

    
    @Column(name="IDREQUEST", length=8)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="STEPNAME", length=200)
    public String getStepname() {
        return this.stepname;
    }
    
    public void setStepname(String stepname) {
        this.stepname = stepname;
    }

    
    @Column(name="STEPDESC", length=200)
    public String getStepdesc() {
        return this.stepdesc;
    }
    
    public void setStepdesc(String stepdesc) {
        this.stepdesc = stepdesc;
    }

    
    @Column(name="ADTNL_PARAMS", length=200)
    public String getAdtnlParams() {
        return this.adtnlParams;
    }
    
    public void setAdtnlParams(String adtnlParams) {
        this.adtnlParams = adtnlParams;
    }

    
    @Column(name="STEPSEQ", precision=22, scale=0)
    public BigDecimal getStepseq() {
        return this.stepseq;
    }
    
    public void setStepseq(BigDecimal stepseq) {
        this.stepseq = stepseq;
    }

    
    @Column(name="REPLICABLE", length=1)
    public Character getReplicable() {
        return this.replicable;
    }
    
    public void setReplicable(Character replicable) {
        this.replicable = replicable;
    }

    
    @Column(name="STATUS", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="TYPESTEP", length=1)
    public Character getTypestep() {
        return this.typestep;
    }
    
    public void setTypestep(Character typestep) {
        this.typestep = typestep;
    }




}


