package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xmltemplateheader generated by hbm2java
 */
@Entity
@Table(name="XMLTEMPLATEHEADER"
    ,schema="FCDBADMIN_RK"
)
public class Xmltemplateheader  implements java.io.Serializable {


     private XmltemplateheaderId id;
     private Application application;
     private String namtemplate;
     private Set<Xmltemplatedetail> xmltemplatedetails = new HashSet<Xmltemplatedetail>(0);

    public Xmltemplateheader() {
    }

	
    public Xmltemplateheader(XmltemplateheaderId id, Application application) {
        this.id = id;
        this.application = application;
    }
    public Xmltemplateheader(XmltemplateheaderId id, Application application, String namtemplate, Set<Xmltemplatedetail> xmltemplatedetails) {
       this.id = id;
       this.application = application;
       this.namtemplate = namtemplate;
       this.xmltemplatedetails = xmltemplatedetails;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idtemplate", column=@Column(name="IDTEMPLATE", nullable=false, length=20) ) } )
    public XmltemplateheaderId getId() {
        return this.id;
    }
    
    public void setId(XmltemplateheaderId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAPP", nullable=false, insertable=false, updatable=false)
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }

    
    @Column(name="NAMTEMPLATE", length=30)
    public String getNamtemplate() {
        return this.namtemplate;
    }
    
    public void setNamtemplate(String namtemplate) {
        this.namtemplate = namtemplate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="xmltemplateheader")
    public Set<Xmltemplatedetail> getXmltemplatedetails() {
        return this.xmltemplatedetails;
    }
    
    public void setXmltemplatedetails(Set<Xmltemplatedetail> xmltemplatedetails) {
        this.xmltemplatedetails = xmltemplatedetails;
    }




}


