package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acctactivity generated by hbm2java
 */
@Entity
@Table(name="ACCTACTIVITY"
    ,schema="FCDBADMIN_RK"
)
public class Acctactivity  implements java.io.Serializable {


     private AcctactivityId id;
     private Date txndate;
     private Date valuedate;
     private String referenceno;
     private String description;
     private Character debitcredit;
     private BigDecimal amount;
     private BigDecimal balance;
     private String codtcy;
     private BigDecimal openingbalance;
     private BigDecimal dbamttxn;
     private BigDecimal cramttxn;
     private Date postingdate;
     private String txncode;
     private String swiftcode;
     private String txnmodule;
     private String userreferenceno;
     private String prodtype;
     private String txntypedesc;

    public Acctactivity() {
    }

	
    public Acctactivity(AcctactivityId id) {
        this.id = id;
    }
    public Acctactivity(AcctactivityId id, Date txndate, Date valuedate, String referenceno, String description, Character debitcredit, BigDecimal amount, BigDecimal balance, String codtcy, BigDecimal openingbalance, BigDecimal dbamttxn, BigDecimal cramttxn, Date postingdate, String txncode, String swiftcode, String txnmodule, String userreferenceno, String prodtype, String txntypedesc) {
       this.id = id;
       this.txndate = txndate;
       this.valuedate = valuedate;
       this.referenceno = referenceno;
       this.description = description;
       this.debitcredit = debitcredit;
       this.amount = amount;
       this.balance = balance;
       this.codtcy = codtcy;
       this.openingbalance = openingbalance;
       this.dbamttxn = dbamttxn;
       this.cramttxn = cramttxn;
       this.postingdate = postingdate;
       this.txncode = txncode;
       this.swiftcode = swiftcode;
       this.txnmodule = txnmodule;
       this.userreferenceno = userreferenceno;
       this.prodtype = prodtype;
       this.txntypedesc = txntypedesc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=30) ), 
        @AttributeOverride(name="codacctno", column=@Column(name="CODACCTNO", nullable=false, length=30) ), 
        @AttributeOverride(name="codaccttype", column=@Column(name="CODACCTTYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="serialno", column=@Column(name="SERIALNO", nullable=false, precision=22, scale=0) ) } )
    public AcctactivityId getId() {
        return this.id;
    }
    
    public void setId(AcctactivityId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TXNDATE", length=7)
    public Date getTxndate() {
        return this.txndate;
    }
    
    public void setTxndate(Date txndate) {
        this.txndate = txndate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALUEDATE", length=7)
    public Date getValuedate() {
        return this.valuedate;
    }
    
    public void setValuedate(Date valuedate) {
        this.valuedate = valuedate;
    }

    
    @Column(name="REFERENCENO", length=100)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="DEBITCREDIT", length=1)
    public Character getDebitcredit() {
        return this.debitcredit;
    }
    
    public void setDebitcredit(Character debitcredit) {
        this.debitcredit = debitcredit;
    }

    
    @Column(name="AMOUNT", precision=22, scale=3)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="BALANCE", precision=22, scale=3)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="CODTCY", length=3)
    public String getCodtcy() {
        return this.codtcy;
    }
    
    public void setCodtcy(String codtcy) {
        this.codtcy = codtcy;
    }

    
    @Column(name="OPENINGBALANCE", precision=22, scale=3)
    public BigDecimal getOpeningbalance() {
        return this.openingbalance;
    }
    
    public void setOpeningbalance(BigDecimal openingbalance) {
        this.openingbalance = openingbalance;
    }

    
    @Column(name="DBAMTTXN", precision=22, scale=3)
    public BigDecimal getDbamttxn() {
        return this.dbamttxn;
    }
    
    public void setDbamttxn(BigDecimal dbamttxn) {
        this.dbamttxn = dbamttxn;
    }

    
    @Column(name="CRAMTTXN", precision=22, scale=3)
    public BigDecimal getCramttxn() {
        return this.cramttxn;
    }
    
    public void setCramttxn(BigDecimal cramttxn) {
        this.cramttxn = cramttxn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="POSTINGDATE", length=7)
    public Date getPostingdate() {
        return this.postingdate;
    }
    
    public void setPostingdate(Date postingdate) {
        this.postingdate = postingdate;
    }

    
    @Column(name="TXNCODE", length=3)
    public String getTxncode() {
        return this.txncode;
    }
    
    public void setTxncode(String txncode) {
        this.txncode = txncode;
    }

    
    @Column(name="SWIFTCODE", length=3)
    public String getSwiftcode() {
        return this.swiftcode;
    }
    
    public void setSwiftcode(String swiftcode) {
        this.swiftcode = swiftcode;
    }

    
    @Column(name="TXNMODULE", length=3)
    public String getTxnmodule() {
        return this.txnmodule;
    }
    
    public void setTxnmodule(String txnmodule) {
        this.txnmodule = txnmodule;
    }

    
    @Column(name="USERREFERENCENO", length=105)
    public String getUserreferenceno() {
        return this.userreferenceno;
    }
    
    public void setUserreferenceno(String userreferenceno) {
        this.userreferenceno = userreferenceno;
    }

    
    @Column(name="PRODTYPE", length=4)
    public String getProdtype() {
        return this.prodtype;
    }
    
    public void setProdtype(String prodtype) {
        this.prodtype = prodtype;
    }

    
    @Column(name="TXNTYPEDESC", length=100)
    public String getTxntypedesc() {
        return this.txntypedesc;
    }
    
    public void setTxntypedesc(String txntypedesc) {
        this.txntypedesc = txntypedesc;
    }




}


