package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Advertisementlog generated by hbm2java
 */
@Entity
@Table(name="ADVERTISEMENTLOG"
    ,schema="FCDBADMIN_RK"
)
public class Advertisementlog  implements java.io.Serializable {


     private AdvertisementlogId id;
     private String idcust;
     private Byte viewCount;

    public Advertisementlog() {
    }

	
    public Advertisementlog(AdvertisementlogId id) {
        this.id = id;
    }
    public Advertisementlog(AdvertisementlogId id, String idcust, Byte viewCount) {
       this.id = id;
       this.idcust = idcust;
       this.viewCount = viewCount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=2000) ), 
        @AttributeOverride(name="adcode", column=@Column(name="ADCODE", nullable=false, length=20) ), 
        @AttributeOverride(name="viewDate", column=@Column(name="VIEW_DATE", nullable=false, length=7) ) } )
    public AdvertisementlogId getId() {
        return this.id;
    }
    
    public void setId(AdvertisementlogId id) {
        this.id = id;
    }

    
    @Column(name="IDCUST", length=30)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }

    
    @Column(name="VIEW_COUNT", precision=2, scale=0)
    public Byte getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(Byte viewCount) {
        this.viewCount = viewCount;
    }




}


