package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AppldataMaxlength generated by hbm2java
 */
@Entity
@Table(name="APPLDATA_MAXLENGTH"
    ,schema="FCDBADMIN_RK"
)
public class AppldataMaxlength  implements java.io.Serializable {


     private AppldataMaxlengthId id;
     private BigDecimal maxlength;

    public AppldataMaxlength() {
    }

	
    public AppldataMaxlength(AppldataMaxlengthId id) {
        this.id = id;
    }
    public AppldataMaxlength(AppldataMaxlengthId id, BigDecimal maxlength) {
       this.id = id;
       this.maxlength = maxlength;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="dataname", column=@Column(name="DATANAME", nullable=false, length=40) ), 
        @AttributeOverride(name="datavalue", column=@Column(name="DATAVALUE", nullable=false, length=100) ), 
        @AttributeOverride(name="idlang", column=@Column(name="IDLANG", nullable=false, length=3) ), 
        @AttributeOverride(name="iddevice", column=@Column(name="IDDEVICE", nullable=false, length=2) ) } )
    public AppldataMaxlengthId getId() {
        return this.id;
    }
    
    public void setId(AppldataMaxlengthId id) {
        this.id = id;
    }

    
    @Column(name="MAXLENGTH", precision=22, scale=0)
    public BigDecimal getMaxlength() {
        return this.maxlength;
    }
    
    public void setMaxlength(BigDecimal maxlength) {
        this.maxlength = maxlength;
    }




}


