package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Btalertsetup generated by hbm2java
 */
@Entity
@Table(name="BTALERTSETUP"
    ,schema="FCDBADMIN_RK"
)
public class Btalertsetup  implements java.io.Serializable {


     private BtalertsetupId id;
     private Btstepsetup btstepsetup;
     private String email;
     private String sms;

    public Btalertsetup() {
    }

	
    public Btalertsetup(BtalertsetupId id, Btstepsetup btstepsetup) {
        this.id = id;
        this.btstepsetup = btstepsetup;
    }
    public Btalertsetup(BtalertsetupId id, Btstepsetup btstepsetup, String email, String sms) {
       this.id = id;
       this.btstepsetup = btstepsetup;
       this.email = email;
       this.sms = sms;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="step", column=@Column(name="STEP", nullable=false, length=20) ) } )
    public BtalertsetupId getId() {
        return this.id;
    }
    
    public void setId(BtalertsetupId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STEP", nullable=false, insertable=false, updatable=false)
    public Btstepsetup getBtstepsetup() {
        return this.btstepsetup;
    }
    
    public void setBtstepsetup(Btstepsetup btstepsetup) {
        this.btstepsetup = btstepsetup;
    }

    
    @Column(name="EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="SMS")
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }




}


