package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Btfailedmsg generated by hbm2java
 */
@Entity
@Table(name="BTFAILEDMSG"
    ,schema="FCDBADMIN_RK"
)
public class Btfailedmsg  implements java.io.Serializable {


     private BtfailedmsgId id;
     private BigDecimal priority;
     private String logqueuname;
     private String controlmsg;
     private Date datupdated;
     private BigDecimal retrycount;
     private String recordrefno;

    public Btfailedmsg() {
    }

	
    public Btfailedmsg(BtfailedmsgId id) {
        this.id = id;
    }
    public Btfailedmsg(BtfailedmsgId id, BigDecimal priority, String logqueuname, String controlmsg, Date datupdated, BigDecimal retrycount, String recordrefno) {
       this.id = id;
       this.priority = priority;
       this.logqueuname = logqueuname;
       this.controlmsg = controlmsg;
       this.datupdated = datupdated;
       this.retrycount = retrycount;
       this.recordrefno = recordrefno;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="filerefno", column=@Column(name="FILEREFNO", nullable=false, length=35) ), 
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="currstep", column=@Column(name="CURRSTEP", nullable=false, length=20) ), 
        @AttributeOverride(name="nextstep", column=@Column(name="NEXTSTEP", nullable=false, length=20) ) } )
    public BtfailedmsgId getId() {
        return this.id;
    }
    
    public void setId(BtfailedmsgId id) {
        this.id = id;
    }

    
    @Column(name="PRIORITY", precision=38, scale=0)
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    
    @Column(name="LOGQUEUNAME", length=35)
    public String getLogqueuname() {
        return this.logqueuname;
    }
    
    public void setLogqueuname(String logqueuname) {
        this.logqueuname = logqueuname;
    }

    
    @Column(name="CONTROLMSG", length=2000)
    public String getControlmsg() {
        return this.controlmsg;
    }
    
    public void setControlmsg(String controlmsg) {
        this.controlmsg = controlmsg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPDATED", length=7)
    public Date getDatupdated() {
        return this.datupdated;
    }
    
    public void setDatupdated(Date datupdated) {
        this.datupdated = datupdated;
    }

    
    @Column(name="RETRYCOUNT", precision=38, scale=0)
    public BigDecimal getRetrycount() {
        return this.retrycount;
    }
    
    public void setRetrycount(BigDecimal retrycount) {
        this.retrycount = retrycount;
    }

    
    @Column(name="RECORDREFNO", length=35)
    public String getRecordrefno() {
        return this.recordrefno;
    }
    
    public void setRecordrefno(String recordrefno) {
        this.recordrefno = recordrefno;
    }




}


