package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BtfiledefinitionId generated by hbm2java
 */
@Embeddable
public class BtfiledefinitionId  implements java.io.Serializable {


     private String btid;
     private String typetemplate;
     private String templateid;

    public BtfiledefinitionId() {
    }

    public BtfiledefinitionId(String btid, String typetemplate, String templateid) {
       this.btid = btid;
       this.typetemplate = typetemplate;
       this.templateid = templateid;
    }
   


    @Column(name="BTID", nullable=false, length=40)
    public String getBtid() {
        return this.btid;
    }
    
    public void setBtid(String btid) {
        this.btid = btid;
    }


    @Column(name="TYPETEMPLATE", nullable=false, length=1)
    public String getTypetemplate() {
        return this.typetemplate;
    }
    
    public void setTypetemplate(String typetemplate) {
        this.typetemplate = typetemplate;
    }


    @Column(name="TEMPLATEID", nullable=false, length=40)
    public String getTemplateid() {
        return this.templateid;
    }
    
    public void setTemplateid(String templateid) {
        this.templateid = templateid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BtfiledefinitionId) ) return false;
		 BtfiledefinitionId castOther = ( BtfiledefinitionId ) other; 
         
		 return ( (this.getBtid()==castOther.getBtid()) || ( this.getBtid()!=null && castOther.getBtid()!=null && this.getBtid().equals(castOther.getBtid()) ) )
 && ( (this.getTypetemplate()==castOther.getTypetemplate()) || ( this.getTypetemplate()!=null && castOther.getTypetemplate()!=null && this.getTypetemplate().equals(castOther.getTypetemplate()) ) )
 && ( (this.getTemplateid()==castOther.getTemplateid()) || ( this.getTemplateid()!=null && castOther.getTemplateid()!=null && this.getTemplateid().equals(castOther.getTemplateid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBtid() == null ? 0 : this.getBtid().hashCode() );
         result = 37 * result + ( getTypetemplate() == null ? 0 : this.getTypetemplate().hashCode() );
         result = 37 * result + ( getTemplateid() == null ? 0 : this.getTemplateid().hashCode() );
         return result;
   }   


}


