package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bthandoffmapping generated by hbm2java
 */
@Entity
@Table(name="BTHANDOFFMAPPING"
    ,schema="FCDBADMIN_RK"
)
public class Bthandoffmapping  implements java.io.Serializable {


     private BthandoffmappingId id;
     private String idrequest;

    public Bthandoffmapping() {
    }

	
    public Bthandoffmapping(BthandoffmappingId id) {
        this.id = id;
    }
    public Bthandoffmapping(BthandoffmappingId id, String idrequest) {
       this.id = id;
       this.idrequest = idrequest;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="handofffield", column=@Column(name="HANDOFFFIELD", nullable=false, length=50) ), 
        @AttributeOverride(name="fieldname", column=@Column(name="FIELDNAME", nullable=false, length=50) ) } )
    public BthandoffmappingId getId() {
        return this.id;
    }
    
    public void setId(BthandoffmappingId id) {
        this.id = id;
    }

    
    @Column(name="IDREQUEST")
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }




}


