package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Btstepsetup generated by hbm2java
 */
@Entity
@Table(name="BTSTEPSETUP"
    ,schema="FCDBADMIN_RK"
)
public class Btstepsetup  implements java.io.Serializable {


     private String step;
     private String stepdesc;
     private Character optional;
     private BigDecimal nbrsequence;
     private String logqueuename;
     private String stepprocessor;
     private Character flgallowsel;
     private Set<Btalertsetup> btalertsetups = new HashSet<Btalertsetup>(0);
     private Set<Btstep> btsteps = new HashSet<Btstep>(0);

    public Btstepsetup() {
    }

	
    public Btstepsetup(String step) {
        this.step = step;
    }
    public Btstepsetup(String step, String stepdesc, Character optional, BigDecimal nbrsequence, String logqueuename, String stepprocessor, Character flgallowsel, Set<Btalertsetup> btalertsetups, Set<Btstep> btsteps) {
       this.step = step;
       this.stepdesc = stepdesc;
       this.optional = optional;
       this.nbrsequence = nbrsequence;
       this.logqueuename = logqueuename;
       this.stepprocessor = stepprocessor;
       this.flgallowsel = flgallowsel;
       this.btalertsetups = btalertsetups;
       this.btsteps = btsteps;
    }
   
     @Id 

    
    @Column(name="STEP", unique=true, nullable=false, length=20)
    public String getStep() {
        return this.step;
    }
    
    public void setStep(String step) {
        this.step = step;
    }

    
    @Column(name="STEPDESC")
    public String getStepdesc() {
        return this.stepdesc;
    }
    
    public void setStepdesc(String stepdesc) {
        this.stepdesc = stepdesc;
    }

    
    @Column(name="OPTIONAL", length=1)
    public Character getOptional() {
        return this.optional;
    }
    
    public void setOptional(Character optional) {
        this.optional = optional;
    }

    
    @Column(name="NBRSEQUENCE", precision=22, scale=0)
    public BigDecimal getNbrsequence() {
        return this.nbrsequence;
    }
    
    public void setNbrsequence(BigDecimal nbrsequence) {
        this.nbrsequence = nbrsequence;
    }

    
    @Column(name="LOGQUEUENAME", length=35)
    public String getLogqueuename() {
        return this.logqueuename;
    }
    
    public void setLogqueuename(String logqueuename) {
        this.logqueuename = logqueuename;
    }

    
    @Column(name="STEPPROCESSOR")
    public String getStepprocessor() {
        return this.stepprocessor;
    }
    
    public void setStepprocessor(String stepprocessor) {
        this.stepprocessor = stepprocessor;
    }

    
    @Column(name="FLGALLOWSEL", length=1)
    public Character getFlgallowsel() {
        return this.flgallowsel;
    }
    
    public void setFlgallowsel(Character flgallowsel) {
        this.flgallowsel = flgallowsel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="btstepsetup")
    public Set<Btalertsetup> getBtalertsetups() {
        return this.btalertsetups;
    }
    
    public void setBtalertsetups(Set<Btalertsetup> btalertsetups) {
        this.btalertsetups = btalertsetups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="btstepsetup")
    public Set<Btstep> getBtsteps() {
        return this.btsteps;
    }
    
    public void setBtsteps(Set<Btstep> btsteps) {
        this.btsteps = btsteps;
    }




}


