package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Bttechinfo generated by hbm2java
 */
@Entity
@Table(name="BTTECHINFO"
    ,schema="FCDBADMIN_RK"
)
public class Bttechinfo  implements java.io.Serializable {


     private String btid;
     private Btcustreg btcustreg;
     private String namuploadprocessor;
     private String nampreprocessor;
     private String namprocessor;
     private String nampostprocessor;
     private String namencryptor;
     private String namdecryptor;
     private String namadvicegen;
     private String namresponsegen;
     private String namctrlfilegen;
     private String namauthprocessor;
     private String nambasetemplate;
     private String namconvertor;

    public Bttechinfo() {
    }

	
    public Bttechinfo(Btcustreg btcustreg) {
        this.btcustreg = btcustreg;
    }
    public Bttechinfo(Btcustreg btcustreg, String namuploadprocessor, String nampreprocessor, String namprocessor, String nampostprocessor, String namencryptor, String namdecryptor, String namadvicegen, String namresponsegen, String namctrlfilegen, String namauthprocessor, String nambasetemplate, String namconvertor) {
       this.btcustreg = btcustreg;
       this.namuploadprocessor = namuploadprocessor;
       this.nampreprocessor = nampreprocessor;
       this.namprocessor = namprocessor;
       this.nampostprocessor = nampostprocessor;
       this.namencryptor = namencryptor;
       this.namdecryptor = namdecryptor;
       this.namadvicegen = namadvicegen;
       this.namresponsegen = namresponsegen;
       this.namctrlfilegen = namctrlfilegen;
       this.namauthprocessor = namauthprocessor;
       this.nambasetemplate = nambasetemplate;
       this.namconvertor = namconvertor;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="btcustreg"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="BTID", unique=true, nullable=false, length=40)
    public String getBtid() {
        return this.btid;
    }
    
    public void setBtid(String btid) {
        this.btid = btid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Btcustreg getBtcustreg() {
        return this.btcustreg;
    }
    
    public void setBtcustreg(Btcustreg btcustreg) {
        this.btcustreg = btcustreg;
    }

    
    @Column(name="NAMUPLOADPROCESSOR")
    public String getNamuploadprocessor() {
        return this.namuploadprocessor;
    }
    
    public void setNamuploadprocessor(String namuploadprocessor) {
        this.namuploadprocessor = namuploadprocessor;
    }

    
    @Column(name="NAMPREPROCESSOR")
    public String getNampreprocessor() {
        return this.nampreprocessor;
    }
    
    public void setNampreprocessor(String nampreprocessor) {
        this.nampreprocessor = nampreprocessor;
    }

    
    @Column(name="NAMPROCESSOR")
    public String getNamprocessor() {
        return this.namprocessor;
    }
    
    public void setNamprocessor(String namprocessor) {
        this.namprocessor = namprocessor;
    }

    
    @Column(name="NAMPOSTPROCESSOR")
    public String getNampostprocessor() {
        return this.nampostprocessor;
    }
    
    public void setNampostprocessor(String nampostprocessor) {
        this.nampostprocessor = nampostprocessor;
    }

    
    @Column(name="NAMENCRYPTOR")
    public String getNamencryptor() {
        return this.namencryptor;
    }
    
    public void setNamencryptor(String namencryptor) {
        this.namencryptor = namencryptor;
    }

    
    @Column(name="NAMDECRYPTOR")
    public String getNamdecryptor() {
        return this.namdecryptor;
    }
    
    public void setNamdecryptor(String namdecryptor) {
        this.namdecryptor = namdecryptor;
    }

    
    @Column(name="NAMADVICEGEN")
    public String getNamadvicegen() {
        return this.namadvicegen;
    }
    
    public void setNamadvicegen(String namadvicegen) {
        this.namadvicegen = namadvicegen;
    }

    
    @Column(name="NAMRESPONSEGEN")
    public String getNamresponsegen() {
        return this.namresponsegen;
    }
    
    public void setNamresponsegen(String namresponsegen) {
        this.namresponsegen = namresponsegen;
    }

    
    @Column(name="NAMCTRLFILEGEN")
    public String getNamctrlfilegen() {
        return this.namctrlfilegen;
    }
    
    public void setNamctrlfilegen(String namctrlfilegen) {
        this.namctrlfilegen = namctrlfilegen;
    }

    
    @Column(name="NAMAUTHPROCESSOR")
    public String getNamauthprocessor() {
        return this.namauthprocessor;
    }
    
    public void setNamauthprocessor(String namauthprocessor) {
        this.namauthprocessor = namauthprocessor;
    }

    
    @Column(name="NAMBASETEMPLATE")
    public String getNambasetemplate() {
        return this.nambasetemplate;
    }
    
    public void setNambasetemplate(String nambasetemplate) {
        this.nambasetemplate = nambasetemplate;
    }

    
    @Column(name="NAMCONVERTOR")
    public String getNamconvertor() {
        return this.namconvertor;
    }
    
    public void setNamconvertor(String namconvertor) {
        this.namconvertor = namconvertor;
    }




}


