package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Btusermap generated by hbm2java
 */
@Entity
@Table(name="BTUSERMAP"
    ,schema="FCDBADMIN_RK"
)
public class Btusermap  implements java.io.Serializable {


     private BtusermapId id;
     private Btcustreg btcustreg;
     private Mstuser mstuser;
     private String sensitivechk;

    public Btusermap() {
    }

	
    public Btusermap(BtusermapId id, Btcustreg btcustreg, Mstuser mstuser) {
        this.id = id;
        this.btcustreg = btcustreg;
        this.mstuser = mstuser;
    }
    public Btusermap(BtusermapId id, Btcustreg btcustreg, Mstuser mstuser, String sensitivechk) {
       this.id = id;
       this.btcustreg = btcustreg;
       this.mstuser = mstuser;
       this.sensitivechk = sensitivechk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userid", column=@Column(name="USERID", nullable=false, length=20) ), 
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ) } )
    public BtusermapId getId() {
        return this.id;
    }
    
    public void setId(BtusermapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BTID", nullable=false, insertable=false, updatable=false)
    public Btcustreg getBtcustreg() {
        return this.btcustreg;
    }
    
    public void setBtcustreg(Btcustreg btcustreg) {
        this.btcustreg = btcustreg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERID", nullable=false, insertable=false, updatable=false)
    public Mstuser getMstuser() {
        return this.mstuser;
    }
    
    public void setMstuser(Mstuser mstuser) {
        this.mstuser = mstuser;
    }

    
    @Column(name="SENSITIVECHK", length=1)
    public String getSensitivechk() {
        return this.sensitivechk;
    }
    
    public void setSensitivechk(String sensitivechk) {
        this.sensitivechk = sensitivechk;
    }




}


