package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BulkFtDetails generated by hbm2java
 */
@Entity
@Table(name="BULK_FT_DETAILS"
    ,schema="FCDBADMIN_RK"
)
public class BulkFtDetails  implements java.io.Serializable {


     private BulkFtDetailsId id;
     private String queue;
     private BigDecimal amount;
     private Date valueDate;
     private String ccy;
     private String status;
     private String errReason;
     private String contractRefNo;
     private String custAcNo;
     private String custCcy;
     private BigDecimal custAmt;
     private Date custValueDt;
     private String cptyAcNo;
     private String cptyCcy;
     private BigDecimal cptyAmt;
     private Date cptyValueDt;
     private BigDecimal exchRate;
     private String byOrderOf1;
     private String byOrderOf2;
     private String byOrderOf3;
     private String byOrderOf4;
     private String byOrderOf5;
     private String ourCorresp1;
     private String ourCorresp2;
     private String ourCorresp3;
     private String ourCorresp4;
     private String ourCorresp5;
     private String rcvrCorresp1;
     private String rcvrCorresp2;
     private String rcvrCorresp3;
     private String rcvrCorresp4;
     private String rcvrCorresp5;
     private String intermediary1;
     private String intermediary2;
     private String intermediary3;
     private String intermediary4;
     private String intermediary5;
     private String accWithInstn1;
     private String accWithInstn2;
     private String accWithInstn3;
     private String accWithInstn4;
     private String accWithInstn5;
     private String benefInstitution1;
     private String benefInstitution2;
     private String benefInstitution3;
     private String benefInstitution4;
     private String benefInstitution5;
     private String paymentDetails1;
     private String paymentDetails2;
     private String paymentDetails3;
     private String paymentDetails4;
     private String paymentDetails5;
     private String sndrToRcvrInfo1;
     private String sndrToRcvrInfo2;
     private String sndrToRcvrInfo3;
     private String sndrToRcvrInfo4;
     private String sndrToRcvrInfo5;
     private String bankOprnCode;
     private String instCode;
     private String relatedRefNo;
     private String rejectCode;
     private String rejectDetails;
     private String udf1;
     private String udf2;
     private String udf3;
     private String udf4;
     private String udf5;
     private String udf6;
     private String udf7;
     private String udf8;
     private String udf9;
     private String udf10;
     private String udf11;
     private String udf12;
     private String udf13;
     private String udf14;
     private String udf15;
     private String udf16;
     private String udf17;
     private Short modNo;
     private String udf18;
     private String udf19;
     private String udf20;
     private String udf21;
     private String udf22;
     private String udf23;
     private String udf24;
     private String udf25;
     private String udf26;
     private String udf27;
     private String udf28;
     private String udf29;
     private String udf30;
     private String makerId;
     private Date makerDtStamp;
     private String checkerId;
     private Date checkerDtStamp;
     private String recordStat;
     private String authStat;
     private String onceAuth;
     private String msgType;
     private String branchCode;
     private Short latestVersionNo;
     private String custAcBrn;
     private String cptyAcBrn;
     private String fileRefNo;
     private String serviceId;
     private String fileType;
     private String msgRefNo;
     private String msgName;
     private Date msgCreationDt;
     private String custReference;
     private String servLevelCode;
     private String chargeBearer;
     private String priority;
     private String consolReqd;
     private Date instructionDate;
     private String custCtry;
     private String custType;
     private String custIdtype;
     private String custIdvalue;
     private String custOtheridType;
     private String custIdissuer;
     private String custDobcity;
     private String custDobctry;
     private String custBankcode;
     private String benefCtry;
     private String cptyType;
     private String cptyIdtype;
     private String cptyIdvalue;
     private String cptyOtheridType;
     private String cptyIdissuer;
     private String cptyDobcity;
     private String cptyDobctry;
     private String initpartyName;
     private String initpartyAddress1;
     private String initpartyAddress2;
     private String initpartyCtry;
     private String initpartyType;
     private String initpartyIdtype;
     private String initpartyIdvalue;
     private String initpartyOtheridType;
     private String initpartyIdissuer;
     private String initpartyDobcity;
     private String initpartyDobctry;
     private String debtorRefparty;
     private String creditorRefparty;
     private String instgBank;
     private String instdBank;
     private String stlmntMethod;
     private String clrgSysId;
     private String stlmntAcNo;
     private String stlmntAcCcy;
     private String orgMsgName;
     private String orgMsgRefNo;
     private String rejtOrgName;
     private String rejtOrgBank;
     private String rejtRefNo;
     private String rejectCodeAdd;
     private String orgSourceRef;
     private Date orgStlmntDt;
     private BigDecimal orgStlmntAmt;
     private String orgStlmntCcy;
     private String ddSeqType;
     private String mandateId;
     private Date mandSignDate;
     private String creditorSchId;
     private String mandAmendInd;
     private String mandAmendType;
     private String orgMandateId;
     private String orgCreditorSchId;
     private String orgCreditorName;
     private String orgDebtorAcc;
     private String orgDebtorBank;
     private String chargeAccount;
     private String dbtracctIban;
     private String cdrtacctIban;
     private String orgDebtorIban;
     private String ultDebtorId;
     private String ultDebtorIdType;
     private String ultDebtorIdValue;
     private String ultDebtorOtherIdType;
     private String ultDebtorIdIssuer;
     private String ultCreditorId;
     private String ultCreditorIdType;
     private String ultCreditorIdValue;
     private String ultCreditorOtherIdType;
     private String ultCreditorIdIssuer;
     private String categoryPurpose;
     private String purposeType;
     private String purposeValue;
     private String localInstrumentType;
     private String localInstrumentValue;
     private String compCcy;
     private BigDecimal compAmt;
     private String elecSig;
     private String ultDebtorBirthCity;
     private String ultDebtorBirthCountry;
     private String ultCreditorBirthCity;
     private String ultCreditorBirthCountry;
     private String creditorSchType;
     private String creditorSchIdValue;
     private String creditorSchIdType;
     private String orgCreditorSchType;
     private String orgCreditorSchIdValue;
     private String orgCreditorSchIdType;
     private String remarks;
     private String cptyName;
     private String cptyBankcode;
     private BigDecimal processSeqNo;
     private String fileLevCustConsolReq;
     private String paymentInfoId;
     private String txnRelatedStatus;
     private String fileRecSeq;
     private String sendToHost;
     private String categoryPurposeType;

    public BulkFtDetails() {
    }

	
    public BulkFtDetails(BulkFtDetailsId id) {
        this.id = id;
    }
    public BulkFtDetails(BulkFtDetailsId id, String queue, BigDecimal amount, Date valueDate, String ccy, String status, String errReason, String contractRefNo, String custAcNo, String custCcy, BigDecimal custAmt, Date custValueDt, String cptyAcNo, String cptyCcy, BigDecimal cptyAmt, Date cptyValueDt, BigDecimal exchRate, String byOrderOf1, String byOrderOf2, String byOrderOf3, String byOrderOf4, String byOrderOf5, String ourCorresp1, String ourCorresp2, String ourCorresp3, String ourCorresp4, String ourCorresp5, String rcvrCorresp1, String rcvrCorresp2, String rcvrCorresp3, String rcvrCorresp4, String rcvrCorresp5, String intermediary1, String intermediary2, String intermediary3, String intermediary4, String intermediary5, String accWithInstn1, String accWithInstn2, String accWithInstn3, String accWithInstn4, String accWithInstn5, String benefInstitution1, String benefInstitution2, String benefInstitution3, String benefInstitution4, String benefInstitution5, String paymentDetails1, String paymentDetails2, String paymentDetails3, String paymentDetails4, String paymentDetails5, String sndrToRcvrInfo1, String sndrToRcvrInfo2, String sndrToRcvrInfo3, String sndrToRcvrInfo4, String sndrToRcvrInfo5, String bankOprnCode, String instCode, String relatedRefNo, String rejectCode, String rejectDetails, String udf1, String udf2, String udf3, String udf4, String udf5, String udf6, String udf7, String udf8, String udf9, String udf10, String udf11, String udf12, String udf13, String udf14, String udf15, String udf16, String udf17, Short modNo, String udf18, String udf19, String udf20, String udf21, String udf22, String udf23, String udf24, String udf25, String udf26, String udf27, String udf28, String udf29, String udf30, String makerId, Date makerDtStamp, String checkerId, Date checkerDtStamp, String recordStat, String authStat, String onceAuth, String msgType, String branchCode, Short latestVersionNo, String custAcBrn, String cptyAcBrn, String fileRefNo, String serviceId, String fileType, String msgRefNo, String msgName, Date msgCreationDt, String custReference, String servLevelCode, String chargeBearer, String priority, String consolReqd, Date instructionDate, String custCtry, String custType, String custIdtype, String custIdvalue, String custOtheridType, String custIdissuer, String custDobcity, String custDobctry, String custBankcode, String benefCtry, String cptyType, String cptyIdtype, String cptyIdvalue, String cptyOtheridType, String cptyIdissuer, String cptyDobcity, String cptyDobctry, String initpartyName, String initpartyAddress1, String initpartyAddress2, String initpartyCtry, String initpartyType, String initpartyIdtype, String initpartyIdvalue, String initpartyOtheridType, String initpartyIdissuer, String initpartyDobcity, String initpartyDobctry, String debtorRefparty, String creditorRefparty, String instgBank, String instdBank, String stlmntMethod, String clrgSysId, String stlmntAcNo, String stlmntAcCcy, String orgMsgName, String orgMsgRefNo, String rejtOrgName, String rejtOrgBank, String rejtRefNo, String rejectCodeAdd, String orgSourceRef, Date orgStlmntDt, BigDecimal orgStlmntAmt, String orgStlmntCcy, String ddSeqType, String mandateId, Date mandSignDate, String creditorSchId, String mandAmendInd, String mandAmendType, String orgMandateId, String orgCreditorSchId, String orgCreditorName, String orgDebtorAcc, String orgDebtorBank, String chargeAccount, String dbtracctIban, String cdrtacctIban, String orgDebtorIban, String ultDebtorId, String ultDebtorIdType, String ultDebtorIdValue, String ultDebtorOtherIdType, String ultDebtorIdIssuer, String ultCreditorId, String ultCreditorIdType, String ultCreditorIdValue, String ultCreditorOtherIdType, String ultCreditorIdIssuer, String categoryPurpose, String purposeType, String purposeValue, String localInstrumentType, String localInstrumentValue, String compCcy, BigDecimal compAmt, String elecSig, String ultDebtorBirthCity, String ultDebtorBirthCountry, String ultCreditorBirthCity, String ultCreditorBirthCountry, String creditorSchType, String creditorSchIdValue, String creditorSchIdType, String orgCreditorSchType, String orgCreditorSchIdValue, String orgCreditorSchIdType, String remarks, String cptyName, String cptyBankcode, BigDecimal processSeqNo, String fileLevCustConsolReq, String paymentInfoId, String txnRelatedStatus, String fileRecSeq, String sendToHost, String categoryPurposeType) {
       this.id = id;
       this.queue = queue;
       this.amount = amount;
       this.valueDate = valueDate;
       this.ccy = ccy;
       this.status = status;
       this.errReason = errReason;
       this.contractRefNo = contractRefNo;
       this.custAcNo = custAcNo;
       this.custCcy = custCcy;
       this.custAmt = custAmt;
       this.custValueDt = custValueDt;
       this.cptyAcNo = cptyAcNo;
       this.cptyCcy = cptyCcy;
       this.cptyAmt = cptyAmt;
       this.cptyValueDt = cptyValueDt;
       this.exchRate = exchRate;
       this.byOrderOf1 = byOrderOf1;
       this.byOrderOf2 = byOrderOf2;
       this.byOrderOf3 = byOrderOf3;
       this.byOrderOf4 = byOrderOf4;
       this.byOrderOf5 = byOrderOf5;
       this.ourCorresp1 = ourCorresp1;
       this.ourCorresp2 = ourCorresp2;
       this.ourCorresp3 = ourCorresp3;
       this.ourCorresp4 = ourCorresp4;
       this.ourCorresp5 = ourCorresp5;
       this.rcvrCorresp1 = rcvrCorresp1;
       this.rcvrCorresp2 = rcvrCorresp2;
       this.rcvrCorresp3 = rcvrCorresp3;
       this.rcvrCorresp4 = rcvrCorresp4;
       this.rcvrCorresp5 = rcvrCorresp5;
       this.intermediary1 = intermediary1;
       this.intermediary2 = intermediary2;
       this.intermediary3 = intermediary3;
       this.intermediary4 = intermediary4;
       this.intermediary5 = intermediary5;
       this.accWithInstn1 = accWithInstn1;
       this.accWithInstn2 = accWithInstn2;
       this.accWithInstn3 = accWithInstn3;
       this.accWithInstn4 = accWithInstn4;
       this.accWithInstn5 = accWithInstn5;
       this.benefInstitution1 = benefInstitution1;
       this.benefInstitution2 = benefInstitution2;
       this.benefInstitution3 = benefInstitution3;
       this.benefInstitution4 = benefInstitution4;
       this.benefInstitution5 = benefInstitution5;
       this.paymentDetails1 = paymentDetails1;
       this.paymentDetails2 = paymentDetails2;
       this.paymentDetails3 = paymentDetails3;
       this.paymentDetails4 = paymentDetails4;
       this.paymentDetails5 = paymentDetails5;
       this.sndrToRcvrInfo1 = sndrToRcvrInfo1;
       this.sndrToRcvrInfo2 = sndrToRcvrInfo2;
       this.sndrToRcvrInfo3 = sndrToRcvrInfo3;
       this.sndrToRcvrInfo4 = sndrToRcvrInfo4;
       this.sndrToRcvrInfo5 = sndrToRcvrInfo5;
       this.bankOprnCode = bankOprnCode;
       this.instCode = instCode;
       this.relatedRefNo = relatedRefNo;
       this.rejectCode = rejectCode;
       this.rejectDetails = rejectDetails;
       this.udf1 = udf1;
       this.udf2 = udf2;
       this.udf3 = udf3;
       this.udf4 = udf4;
       this.udf5 = udf5;
       this.udf6 = udf6;
       this.udf7 = udf7;
       this.udf8 = udf8;
       this.udf9 = udf9;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf13 = udf13;
       this.udf14 = udf14;
       this.udf15 = udf15;
       this.udf16 = udf16;
       this.udf17 = udf17;
       this.modNo = modNo;
       this.udf18 = udf18;
       this.udf19 = udf19;
       this.udf20 = udf20;
       this.udf21 = udf21;
       this.udf22 = udf22;
       this.udf23 = udf23;
       this.udf24 = udf24;
       this.udf25 = udf25;
       this.udf26 = udf26;
       this.udf27 = udf27;
       this.udf28 = udf28;
       this.udf29 = udf29;
       this.udf30 = udf30;
       this.makerId = makerId;
       this.makerDtStamp = makerDtStamp;
       this.checkerId = checkerId;
       this.checkerDtStamp = checkerDtStamp;
       this.recordStat = recordStat;
       this.authStat = authStat;
       this.onceAuth = onceAuth;
       this.msgType = msgType;
       this.branchCode = branchCode;
       this.latestVersionNo = latestVersionNo;
       this.custAcBrn = custAcBrn;
       this.cptyAcBrn = cptyAcBrn;
       this.fileRefNo = fileRefNo;
       this.serviceId = serviceId;
       this.fileType = fileType;
       this.msgRefNo = msgRefNo;
       this.msgName = msgName;
       this.msgCreationDt = msgCreationDt;
       this.custReference = custReference;
       this.servLevelCode = servLevelCode;
       this.chargeBearer = chargeBearer;
       this.priority = priority;
       this.consolReqd = consolReqd;
       this.instructionDate = instructionDate;
       this.custCtry = custCtry;
       this.custType = custType;
       this.custIdtype = custIdtype;
       this.custIdvalue = custIdvalue;
       this.custOtheridType = custOtheridType;
       this.custIdissuer = custIdissuer;
       this.custDobcity = custDobcity;
       this.custDobctry = custDobctry;
       this.custBankcode = custBankcode;
       this.benefCtry = benefCtry;
       this.cptyType = cptyType;
       this.cptyIdtype = cptyIdtype;
       this.cptyIdvalue = cptyIdvalue;
       this.cptyOtheridType = cptyOtheridType;
       this.cptyIdissuer = cptyIdissuer;
       this.cptyDobcity = cptyDobcity;
       this.cptyDobctry = cptyDobctry;
       this.initpartyName = initpartyName;
       this.initpartyAddress1 = initpartyAddress1;
       this.initpartyAddress2 = initpartyAddress2;
       this.initpartyCtry = initpartyCtry;
       this.initpartyType = initpartyType;
       this.initpartyIdtype = initpartyIdtype;
       this.initpartyIdvalue = initpartyIdvalue;
       this.initpartyOtheridType = initpartyOtheridType;
       this.initpartyIdissuer = initpartyIdissuer;
       this.initpartyDobcity = initpartyDobcity;
       this.initpartyDobctry = initpartyDobctry;
       this.debtorRefparty = debtorRefparty;
       this.creditorRefparty = creditorRefparty;
       this.instgBank = instgBank;
       this.instdBank = instdBank;
       this.stlmntMethod = stlmntMethod;
       this.clrgSysId = clrgSysId;
       this.stlmntAcNo = stlmntAcNo;
       this.stlmntAcCcy = stlmntAcCcy;
       this.orgMsgName = orgMsgName;
       this.orgMsgRefNo = orgMsgRefNo;
       this.rejtOrgName = rejtOrgName;
       this.rejtOrgBank = rejtOrgBank;
       this.rejtRefNo = rejtRefNo;
       this.rejectCodeAdd = rejectCodeAdd;
       this.orgSourceRef = orgSourceRef;
       this.orgStlmntDt = orgStlmntDt;
       this.orgStlmntAmt = orgStlmntAmt;
       this.orgStlmntCcy = orgStlmntCcy;
       this.ddSeqType = ddSeqType;
       this.mandateId = mandateId;
       this.mandSignDate = mandSignDate;
       this.creditorSchId = creditorSchId;
       this.mandAmendInd = mandAmendInd;
       this.mandAmendType = mandAmendType;
       this.orgMandateId = orgMandateId;
       this.orgCreditorSchId = orgCreditorSchId;
       this.orgCreditorName = orgCreditorName;
       this.orgDebtorAcc = orgDebtorAcc;
       this.orgDebtorBank = orgDebtorBank;
       this.chargeAccount = chargeAccount;
       this.dbtracctIban = dbtracctIban;
       this.cdrtacctIban = cdrtacctIban;
       this.orgDebtorIban = orgDebtorIban;
       this.ultDebtorId = ultDebtorId;
       this.ultDebtorIdType = ultDebtorIdType;
       this.ultDebtorIdValue = ultDebtorIdValue;
       this.ultDebtorOtherIdType = ultDebtorOtherIdType;
       this.ultDebtorIdIssuer = ultDebtorIdIssuer;
       this.ultCreditorId = ultCreditorId;
       this.ultCreditorIdType = ultCreditorIdType;
       this.ultCreditorIdValue = ultCreditorIdValue;
       this.ultCreditorOtherIdType = ultCreditorOtherIdType;
       this.ultCreditorIdIssuer = ultCreditorIdIssuer;
       this.categoryPurpose = categoryPurpose;
       this.purposeType = purposeType;
       this.purposeValue = purposeValue;
       this.localInstrumentType = localInstrumentType;
       this.localInstrumentValue = localInstrumentValue;
       this.compCcy = compCcy;
       this.compAmt = compAmt;
       this.elecSig = elecSig;
       this.ultDebtorBirthCity = ultDebtorBirthCity;
       this.ultDebtorBirthCountry = ultDebtorBirthCountry;
       this.ultCreditorBirthCity = ultCreditorBirthCity;
       this.ultCreditorBirthCountry = ultCreditorBirthCountry;
       this.creditorSchType = creditorSchType;
       this.creditorSchIdValue = creditorSchIdValue;
       this.creditorSchIdType = creditorSchIdType;
       this.orgCreditorSchType = orgCreditorSchType;
       this.orgCreditorSchIdValue = orgCreditorSchIdValue;
       this.orgCreditorSchIdType = orgCreditorSchIdType;
       this.remarks = remarks;
       this.cptyName = cptyName;
       this.cptyBankcode = cptyBankcode;
       this.processSeqNo = processSeqNo;
       this.fileLevCustConsolReq = fileLevCustConsolReq;
       this.paymentInfoId = paymentInfoId;
       this.txnRelatedStatus = txnRelatedStatus;
       this.fileRecSeq = fileRecSeq;
       this.sendToHost = sendToHost;
       this.categoryPurposeType = categoryPurposeType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sourceCode", column=@Column(name="SOURCE_CODE", nullable=false, length=15) ), 
        @AttributeOverride(name="extRefNo", column=@Column(name="EXT_REF_NO", nullable=false, length=35) ), 
        @AttributeOverride(name="versionNo", column=@Column(name="VERSION_NO", nullable=false, precision=4, scale=0) ) } )
    public BulkFtDetailsId getId() {
        return this.id;
    }
    
    public void setId(BulkFtDetailsId id) {
        this.id = id;
    }

    
    @Column(name="QUEUE", length=12)
    public String getQueue() {
        return this.queue;
    }
    
    public void setQueue(String queue) {
        this.queue = queue;
    }

    
    @Column(name="AMOUNT", precision=22, scale=3)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALUE_DATE", length=7)
    public Date getValueDate() {
        return this.valueDate;
    }
    
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }

    
    @Column(name="CCY", length=3)
    public String getCcy() {
        return this.ccy;
    }
    
    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="ERR_REASON", length=11)
    public String getErrReason() {
        return this.errReason;
    }
    
    public void setErrReason(String errReason) {
        this.errReason = errReason;
    }

    
    @Column(name="CONTRACT_REF_NO", length=16)
    public String getContractRefNo() {
        return this.contractRefNo;
    }
    
    public void setContractRefNo(String contractRefNo) {
        this.contractRefNo = contractRefNo;
    }

    
    @Column(name="CUST_AC_NO", length=35)
    public String getCustAcNo() {
        return this.custAcNo;
    }
    
    public void setCustAcNo(String custAcNo) {
        this.custAcNo = custAcNo;
    }

    
    @Column(name="CUST_CCY", length=3)
    public String getCustCcy() {
        return this.custCcy;
    }
    
    public void setCustCcy(String custCcy) {
        this.custCcy = custCcy;
    }

    
    @Column(name="CUST_AMT", precision=22, scale=3)
    public BigDecimal getCustAmt() {
        return this.custAmt;
    }
    
    public void setCustAmt(BigDecimal custAmt) {
        this.custAmt = custAmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CUST_VALUE_DT", length=7)
    public Date getCustValueDt() {
        return this.custValueDt;
    }
    
    public void setCustValueDt(Date custValueDt) {
        this.custValueDt = custValueDt;
    }

    
    @Column(name="CPTY_AC_NO", length=35)
    public String getCptyAcNo() {
        return this.cptyAcNo;
    }
    
    public void setCptyAcNo(String cptyAcNo) {
        this.cptyAcNo = cptyAcNo;
    }

    
    @Column(name="CPTY_CCY", length=3)
    public String getCptyCcy() {
        return this.cptyCcy;
    }
    
    public void setCptyCcy(String cptyCcy) {
        this.cptyCcy = cptyCcy;
    }

    
    @Column(name="CPTY_AMT", precision=22, scale=3)
    public BigDecimal getCptyAmt() {
        return this.cptyAmt;
    }
    
    public void setCptyAmt(BigDecimal cptyAmt) {
        this.cptyAmt = cptyAmt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CPTY_VALUE_DT", length=7)
    public Date getCptyValueDt() {
        return this.cptyValueDt;
    }
    
    public void setCptyValueDt(Date cptyValueDt) {
        this.cptyValueDt = cptyValueDt;
    }

    
    @Column(name="EXCH_RATE", precision=24, scale=12)
    public BigDecimal getExchRate() {
        return this.exchRate;
    }
    
    public void setExchRate(BigDecimal exchRate) {
        this.exchRate = exchRate;
    }

    
    @Column(name="BY_ORDER_OF1", length=210)
    public String getByOrderOf1() {
        return this.byOrderOf1;
    }
    
    public void setByOrderOf1(String byOrderOf1) {
        this.byOrderOf1 = byOrderOf1;
    }

    
    @Column(name="BY_ORDER_OF2", length=210)
    public String getByOrderOf2() {
        return this.byOrderOf2;
    }
    
    public void setByOrderOf2(String byOrderOf2) {
        this.byOrderOf2 = byOrderOf2;
    }

    
    @Column(name="BY_ORDER_OF3", length=210)
    public String getByOrderOf3() {
        return this.byOrderOf3;
    }
    
    public void setByOrderOf3(String byOrderOf3) {
        this.byOrderOf3 = byOrderOf3;
    }

    
    @Column(name="BY_ORDER_OF4", length=210)
    public String getByOrderOf4() {
        return this.byOrderOf4;
    }
    
    public void setByOrderOf4(String byOrderOf4) {
        this.byOrderOf4 = byOrderOf4;
    }

    
    @Column(name="BY_ORDER_OF5", length=210)
    public String getByOrderOf5() {
        return this.byOrderOf5;
    }
    
    public void setByOrderOf5(String byOrderOf5) {
        this.byOrderOf5 = byOrderOf5;
    }

    
    @Column(name="OUR_CORRESP1", length=105)
    public String getOurCorresp1() {
        return this.ourCorresp1;
    }
    
    public void setOurCorresp1(String ourCorresp1) {
        this.ourCorresp1 = ourCorresp1;
    }

    
    @Column(name="OUR_CORRESP2", length=105)
    public String getOurCorresp2() {
        return this.ourCorresp2;
    }
    
    public void setOurCorresp2(String ourCorresp2) {
        this.ourCorresp2 = ourCorresp2;
    }

    
    @Column(name="OUR_CORRESP3", length=105)
    public String getOurCorresp3() {
        return this.ourCorresp3;
    }
    
    public void setOurCorresp3(String ourCorresp3) {
        this.ourCorresp3 = ourCorresp3;
    }

    
    @Column(name="OUR_CORRESP4", length=105)
    public String getOurCorresp4() {
        return this.ourCorresp4;
    }
    
    public void setOurCorresp4(String ourCorresp4) {
        this.ourCorresp4 = ourCorresp4;
    }

    
    @Column(name="OUR_CORRESP5", length=105)
    public String getOurCorresp5() {
        return this.ourCorresp5;
    }
    
    public void setOurCorresp5(String ourCorresp5) {
        this.ourCorresp5 = ourCorresp5;
    }

    
    @Column(name="RCVR_CORRESP1", length=105)
    public String getRcvrCorresp1() {
        return this.rcvrCorresp1;
    }
    
    public void setRcvrCorresp1(String rcvrCorresp1) {
        this.rcvrCorresp1 = rcvrCorresp1;
    }

    
    @Column(name="RCVR_CORRESP2", length=105)
    public String getRcvrCorresp2() {
        return this.rcvrCorresp2;
    }
    
    public void setRcvrCorresp2(String rcvrCorresp2) {
        this.rcvrCorresp2 = rcvrCorresp2;
    }

    
    @Column(name="RCVR_CORRESP3", length=105)
    public String getRcvrCorresp3() {
        return this.rcvrCorresp3;
    }
    
    public void setRcvrCorresp3(String rcvrCorresp3) {
        this.rcvrCorresp3 = rcvrCorresp3;
    }

    
    @Column(name="RCVR_CORRESP4", length=105)
    public String getRcvrCorresp4() {
        return this.rcvrCorresp4;
    }
    
    public void setRcvrCorresp4(String rcvrCorresp4) {
        this.rcvrCorresp4 = rcvrCorresp4;
    }

    
    @Column(name="RCVR_CORRESP5", length=105)
    public String getRcvrCorresp5() {
        return this.rcvrCorresp5;
    }
    
    public void setRcvrCorresp5(String rcvrCorresp5) {
        this.rcvrCorresp5 = rcvrCorresp5;
    }

    
    @Column(name="INTERMEDIARY1", length=105)
    public String getIntermediary1() {
        return this.intermediary1;
    }
    
    public void setIntermediary1(String intermediary1) {
        this.intermediary1 = intermediary1;
    }

    
    @Column(name="INTERMEDIARY2", length=105)
    public String getIntermediary2() {
        return this.intermediary2;
    }
    
    public void setIntermediary2(String intermediary2) {
        this.intermediary2 = intermediary2;
    }

    
    @Column(name="INTERMEDIARY3", length=105)
    public String getIntermediary3() {
        return this.intermediary3;
    }
    
    public void setIntermediary3(String intermediary3) {
        this.intermediary3 = intermediary3;
    }

    
    @Column(name="INTERMEDIARY4", length=105)
    public String getIntermediary4() {
        return this.intermediary4;
    }
    
    public void setIntermediary4(String intermediary4) {
        this.intermediary4 = intermediary4;
    }

    
    @Column(name="INTERMEDIARY5", length=105)
    public String getIntermediary5() {
        return this.intermediary5;
    }
    
    public void setIntermediary5(String intermediary5) {
        this.intermediary5 = intermediary5;
    }

    
    @Column(name="ACC_WITH_INSTN1", length=105)
    public String getAccWithInstn1() {
        return this.accWithInstn1;
    }
    
    public void setAccWithInstn1(String accWithInstn1) {
        this.accWithInstn1 = accWithInstn1;
    }

    
    @Column(name="ACC_WITH_INSTN2", length=105)
    public String getAccWithInstn2() {
        return this.accWithInstn2;
    }
    
    public void setAccWithInstn2(String accWithInstn2) {
        this.accWithInstn2 = accWithInstn2;
    }

    
    @Column(name="ACC_WITH_INSTN3", length=105)
    public String getAccWithInstn3() {
        return this.accWithInstn3;
    }
    
    public void setAccWithInstn3(String accWithInstn3) {
        this.accWithInstn3 = accWithInstn3;
    }

    
    @Column(name="ACC_WITH_INSTN4", length=105)
    public String getAccWithInstn4() {
        return this.accWithInstn4;
    }
    
    public void setAccWithInstn4(String accWithInstn4) {
        this.accWithInstn4 = accWithInstn4;
    }

    
    @Column(name="ACC_WITH_INSTN5", length=105)
    public String getAccWithInstn5() {
        return this.accWithInstn5;
    }
    
    public void setAccWithInstn5(String accWithInstn5) {
        this.accWithInstn5 = accWithInstn5;
    }

    
    @Column(name="BENEF_INSTITUTION1", length=210)
    public String getBenefInstitution1() {
        return this.benefInstitution1;
    }
    
    public void setBenefInstitution1(String benefInstitution1) {
        this.benefInstitution1 = benefInstitution1;
    }

    
    @Column(name="BENEF_INSTITUTION2", length=210)
    public String getBenefInstitution2() {
        return this.benefInstitution2;
    }
    
    public void setBenefInstitution2(String benefInstitution2) {
        this.benefInstitution2 = benefInstitution2;
    }

    
    @Column(name="BENEF_INSTITUTION3", length=210)
    public String getBenefInstitution3() {
        return this.benefInstitution3;
    }
    
    public void setBenefInstitution3(String benefInstitution3) {
        this.benefInstitution3 = benefInstitution3;
    }

    
    @Column(name="BENEF_INSTITUTION4", length=210)
    public String getBenefInstitution4() {
        return this.benefInstitution4;
    }
    
    public void setBenefInstitution4(String benefInstitution4) {
        this.benefInstitution4 = benefInstitution4;
    }

    
    @Column(name="BENEF_INSTITUTION5", length=210)
    public String getBenefInstitution5() {
        return this.benefInstitution5;
    }
    
    public void setBenefInstitution5(String benefInstitution5) {
        this.benefInstitution5 = benefInstitution5;
    }

    
    @Column(name="PAYMENT_DETAILS1", length=105)
    public String getPaymentDetails1() {
        return this.paymentDetails1;
    }
    
    public void setPaymentDetails1(String paymentDetails1) {
        this.paymentDetails1 = paymentDetails1;
    }

    
    @Column(name="PAYMENT_DETAILS2", length=105)
    public String getPaymentDetails2() {
        return this.paymentDetails2;
    }
    
    public void setPaymentDetails2(String paymentDetails2) {
        this.paymentDetails2 = paymentDetails2;
    }

    
    @Column(name="PAYMENT_DETAILS3", length=105)
    public String getPaymentDetails3() {
        return this.paymentDetails3;
    }
    
    public void setPaymentDetails3(String paymentDetails3) {
        this.paymentDetails3 = paymentDetails3;
    }

    
    @Column(name="PAYMENT_DETAILS4", length=105)
    public String getPaymentDetails4() {
        return this.paymentDetails4;
    }
    
    public void setPaymentDetails4(String paymentDetails4) {
        this.paymentDetails4 = paymentDetails4;
    }

    
    @Column(name="PAYMENT_DETAILS5", length=105)
    public String getPaymentDetails5() {
        return this.paymentDetails5;
    }
    
    public void setPaymentDetails5(String paymentDetails5) {
        this.paymentDetails5 = paymentDetails5;
    }

    
    @Column(name="SNDR_TO_RCVR_INFO1", length=105)
    public String getSndrToRcvrInfo1() {
        return this.sndrToRcvrInfo1;
    }
    
    public void setSndrToRcvrInfo1(String sndrToRcvrInfo1) {
        this.sndrToRcvrInfo1 = sndrToRcvrInfo1;
    }

    
    @Column(name="SNDR_TO_RCVR_INFO2", length=105)
    public String getSndrToRcvrInfo2() {
        return this.sndrToRcvrInfo2;
    }
    
    public void setSndrToRcvrInfo2(String sndrToRcvrInfo2) {
        this.sndrToRcvrInfo2 = sndrToRcvrInfo2;
    }

    
    @Column(name="SNDR_TO_RCVR_INFO3", length=105)
    public String getSndrToRcvrInfo3() {
        return this.sndrToRcvrInfo3;
    }
    
    public void setSndrToRcvrInfo3(String sndrToRcvrInfo3) {
        this.sndrToRcvrInfo3 = sndrToRcvrInfo3;
    }

    
    @Column(name="SNDR_TO_RCVR_INFO4", length=105)
    public String getSndrToRcvrInfo4() {
        return this.sndrToRcvrInfo4;
    }
    
    public void setSndrToRcvrInfo4(String sndrToRcvrInfo4) {
        this.sndrToRcvrInfo4 = sndrToRcvrInfo4;
    }

    
    @Column(name="SNDR_TO_RCVR_INFO5", length=105)
    public String getSndrToRcvrInfo5() {
        return this.sndrToRcvrInfo5;
    }
    
    public void setSndrToRcvrInfo5(String sndrToRcvrInfo5) {
        this.sndrToRcvrInfo5 = sndrToRcvrInfo5;
    }

    
    @Column(name="BANK_OPRN_CODE", length=4)
    public String getBankOprnCode() {
        return this.bankOprnCode;
    }
    
    public void setBankOprnCode(String bankOprnCode) {
        this.bankOprnCode = bankOprnCode;
    }

    
    @Column(name="INST_CODE", length=35)
    public String getInstCode() {
        return this.instCode;
    }
    
    public void setInstCode(String instCode) {
        this.instCode = instCode;
    }

    
    @Column(name="RELATED_REF_NO", length=35)
    public String getRelatedRefNo() {
        return this.relatedRefNo;
    }
    
    public void setRelatedRefNo(String relatedRefNo) {
        this.relatedRefNo = relatedRefNo;
    }

    
    @Column(name="REJECT_CODE", length=4)
    public String getRejectCode() {
        return this.rejectCode;
    }
    
    public void setRejectCode(String rejectCode) {
        this.rejectCode = rejectCode;
    }

    
    @Column(name="REJECT_DETAILS", length=35)
    public String getRejectDetails() {
        return this.rejectDetails;
    }
    
    public void setRejectDetails(String rejectDetails) {
        this.rejectDetails = rejectDetails;
    }

    
    @Column(name="UDF_1", length=150)
    public String getUdf1() {
        return this.udf1;
    }
    
    public void setUdf1(String udf1) {
        this.udf1 = udf1;
    }

    
    @Column(name="UDF_2", length=150)
    public String getUdf2() {
        return this.udf2;
    }
    
    public void setUdf2(String udf2) {
        this.udf2 = udf2;
    }

    
    @Column(name="UDF_3", length=150)
    public String getUdf3() {
        return this.udf3;
    }
    
    public void setUdf3(String udf3) {
        this.udf3 = udf3;
    }

    
    @Column(name="UDF_4", length=150)
    public String getUdf4() {
        return this.udf4;
    }
    
    public void setUdf4(String udf4) {
        this.udf4 = udf4;
    }

    
    @Column(name="UDF_5", length=150)
    public String getUdf5() {
        return this.udf5;
    }
    
    public void setUdf5(String udf5) {
        this.udf5 = udf5;
    }

    
    @Column(name="UDF_6", length=150)
    public String getUdf6() {
        return this.udf6;
    }
    
    public void setUdf6(String udf6) {
        this.udf6 = udf6;
    }

    
    @Column(name="UDF_7", length=150)
    public String getUdf7() {
        return this.udf7;
    }
    
    public void setUdf7(String udf7) {
        this.udf7 = udf7;
    }

    
    @Column(name="UDF_8", length=150)
    public String getUdf8() {
        return this.udf8;
    }
    
    public void setUdf8(String udf8) {
        this.udf8 = udf8;
    }

    
    @Column(name="UDF_9", length=150)
    public String getUdf9() {
        return this.udf9;
    }
    
    public void setUdf9(String udf9) {
        this.udf9 = udf9;
    }

    
    @Column(name="UDF_10", length=150)
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }

    
    @Column(name="UDF_11", length=150)
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }

    
    @Column(name="UDF_12", length=150)
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }

    
    @Column(name="UDF_13", length=150)
    public String getUdf13() {
        return this.udf13;
    }
    
    public void setUdf13(String udf13) {
        this.udf13 = udf13;
    }

    
    @Column(name="UDF_14", length=150)
    public String getUdf14() {
        return this.udf14;
    }
    
    public void setUdf14(String udf14) {
        this.udf14 = udf14;
    }

    
    @Column(name="UDF_15", length=150)
    public String getUdf15() {
        return this.udf15;
    }
    
    public void setUdf15(String udf15) {
        this.udf15 = udf15;
    }

    
    @Column(name="UDF_16", length=150)
    public String getUdf16() {
        return this.udf16;
    }
    
    public void setUdf16(String udf16) {
        this.udf16 = udf16;
    }

    
    @Column(name="UDF_17", length=150)
    public String getUdf17() {
        return this.udf17;
    }
    
    public void setUdf17(String udf17) {
        this.udf17 = udf17;
    }

    
    @Column(name="MOD_NO", precision=4, scale=0)
    public Short getModNo() {
        return this.modNo;
    }
    
    public void setModNo(Short modNo) {
        this.modNo = modNo;
    }

    
    @Column(name="UDF_18", length=150)
    public String getUdf18() {
        return this.udf18;
    }
    
    public void setUdf18(String udf18) {
        this.udf18 = udf18;
    }

    
    @Column(name="UDF_19", length=150)
    public String getUdf19() {
        return this.udf19;
    }
    
    public void setUdf19(String udf19) {
        this.udf19 = udf19;
    }

    
    @Column(name="UDF_20", length=150)
    public String getUdf20() {
        return this.udf20;
    }
    
    public void setUdf20(String udf20) {
        this.udf20 = udf20;
    }

    
    @Column(name="UDF_21", length=150)
    public String getUdf21() {
        return this.udf21;
    }
    
    public void setUdf21(String udf21) {
        this.udf21 = udf21;
    }

    
    @Column(name="UDF_22", length=150)
    public String getUdf22() {
        return this.udf22;
    }
    
    public void setUdf22(String udf22) {
        this.udf22 = udf22;
    }

    
    @Column(name="UDF_23", length=150)
    public String getUdf23() {
        return this.udf23;
    }
    
    public void setUdf23(String udf23) {
        this.udf23 = udf23;
    }

    
    @Column(name="UDF_24", length=150)
    public String getUdf24() {
        return this.udf24;
    }
    
    public void setUdf24(String udf24) {
        this.udf24 = udf24;
    }

    
    @Column(name="UDF_25", length=150)
    public String getUdf25() {
        return this.udf25;
    }
    
    public void setUdf25(String udf25) {
        this.udf25 = udf25;
    }

    
    @Column(name="UDF_26", length=150)
    public String getUdf26() {
        return this.udf26;
    }
    
    public void setUdf26(String udf26) {
        this.udf26 = udf26;
    }

    
    @Column(name="UDF_27", length=150)
    public String getUdf27() {
        return this.udf27;
    }
    
    public void setUdf27(String udf27) {
        this.udf27 = udf27;
    }

    
    @Column(name="UDF_28", length=150)
    public String getUdf28() {
        return this.udf28;
    }
    
    public void setUdf28(String udf28) {
        this.udf28 = udf28;
    }

    
    @Column(name="UDF_29", length=150)
    public String getUdf29() {
        return this.udf29;
    }
    
    public void setUdf29(String udf29) {
        this.udf29 = udf29;
    }

    
    @Column(name="UDF_30", length=150)
    public String getUdf30() {
        return this.udf30;
    }
    
    public void setUdf30(String udf30) {
        this.udf30 = udf30;
    }

    
    @Column(name="MAKER_ID", length=12)
    public String getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(String makerId) {
        this.makerId = makerId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MAKER_DT_STAMP", length=7)
    public Date getMakerDtStamp() {
        return this.makerDtStamp;
    }
    
    public void setMakerDtStamp(Date makerDtStamp) {
        this.makerDtStamp = makerDtStamp;
    }

    
    @Column(name="CHECKER_ID", length=12)
    public String getCheckerId() {
        return this.checkerId;
    }
    
    public void setCheckerId(String checkerId) {
        this.checkerId = checkerId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CHECKER_DT_STAMP", length=7)
    public Date getCheckerDtStamp() {
        return this.checkerDtStamp;
    }
    
    public void setCheckerDtStamp(Date checkerDtStamp) {
        this.checkerDtStamp = checkerDtStamp;
    }

    
    @Column(name="RECORD_STAT", length=1)
    public String getRecordStat() {
        return this.recordStat;
    }
    
    public void setRecordStat(String recordStat) {
        this.recordStat = recordStat;
    }

    
    @Column(name="AUTH_STAT", length=1)
    public String getAuthStat() {
        return this.authStat;
    }
    
    public void setAuthStat(String authStat) {
        this.authStat = authStat;
    }

    
    @Column(name="ONCE_AUTH", length=1)
    public String getOnceAuth() {
        return this.onceAuth;
    }
    
    public void setOnceAuth(String onceAuth) {
        this.onceAuth = onceAuth;
    }

    
    @Column(name="MSG_TYPE", length=7)
    public String getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    
    @Column(name="BRANCH_CODE", length=3)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    
    @Column(name="LATEST_VERSION_NO", precision=4, scale=0)
    public Short getLatestVersionNo() {
        return this.latestVersionNo;
    }
    
    public void setLatestVersionNo(Short latestVersionNo) {
        this.latestVersionNo = latestVersionNo;
    }

    
    @Column(name="CUST_AC_BRN", length=3)
    public String getCustAcBrn() {
        return this.custAcBrn;
    }
    
    public void setCustAcBrn(String custAcBrn) {
        this.custAcBrn = custAcBrn;
    }

    
    @Column(name="CPTY_AC_BRN", length=3)
    public String getCptyAcBrn() {
        return this.cptyAcBrn;
    }
    
    public void setCptyAcBrn(String cptyAcBrn) {
        this.cptyAcBrn = cptyAcBrn;
    }

    
    @Column(name="FILE_REF_NO", length=40)
    public String getFileRefNo() {
        return this.fileRefNo;
    }
    
    public void setFileRefNo(String fileRefNo) {
        this.fileRefNo = fileRefNo;
    }

    
    @Column(name="SERVICE_ID", length=3)
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    
    @Column(name="FILE_TYPE", length=3)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    
    @Column(name="MSG_REF_NO", length=35)
    public String getMsgRefNo() {
        return this.msgRefNo;
    }
    
    public void setMsgRefNo(String msgRefNo) {
        this.msgRefNo = msgRefNo;
    }

    
    @Column(name="MSG_NAME", length=35)
    public String getMsgName() {
        return this.msgName;
    }
    
    public void setMsgName(String msgName) {
        this.msgName = msgName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MSG_CREATION_DT", length=7)
    public Date getMsgCreationDt() {
        return this.msgCreationDt;
    }
    
    public void setMsgCreationDt(Date msgCreationDt) {
        this.msgCreationDt = msgCreationDt;
    }

    
    @Column(name="CUST_REFERENCE", length=35)
    public String getCustReference() {
        return this.custReference;
    }
    
    public void setCustReference(String custReference) {
        this.custReference = custReference;
    }

    
    @Column(name="SERV_LEVEL_CODE", length=4)
    public String getServLevelCode() {
        return this.servLevelCode;
    }
    
    public void setServLevelCode(String servLevelCode) {
        this.servLevelCode = servLevelCode;
    }

    
    @Column(name="CHARGE_BEARER", length=4)
    public String getChargeBearer() {
        return this.chargeBearer;
    }
    
    public void setChargeBearer(String chargeBearer) {
        this.chargeBearer = chargeBearer;
    }

    
    @Column(name="PRIORITY", length=2)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="CONSOL_REQD", length=1)
    public String getConsolReqd() {
        return this.consolReqd;
    }
    
    public void setConsolReqd(String consolReqd) {
        this.consolReqd = consolReqd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSTRUCTION_DATE", length=7)
    public Date getInstructionDate() {
        return this.instructionDate;
    }
    
    public void setInstructionDate(Date instructionDate) {
        this.instructionDate = instructionDate;
    }

    
    @Column(name="CUST_CTRY", length=3)
    public String getCustCtry() {
        return this.custCtry;
    }
    
    public void setCustCtry(String custCtry) {
        this.custCtry = custCtry;
    }

    
    @Column(name="CUST_TYPE", length=1)
    public String getCustType() {
        return this.custType;
    }
    
    public void setCustType(String custType) {
        this.custType = custType;
    }

    
    @Column(name="CUST_IDTYPE", length=2)
    public String getCustIdtype() {
        return this.custIdtype;
    }
    
    public void setCustIdtype(String custIdtype) {
        this.custIdtype = custIdtype;
    }

    
    @Column(name="CUST_IDVALUE", length=35)
    public String getCustIdvalue() {
        return this.custIdvalue;
    }
    
    public void setCustIdvalue(String custIdvalue) {
        this.custIdvalue = custIdvalue;
    }

    
    @Column(name="CUST_OTHERID_TYPE", length=35)
    public String getCustOtheridType() {
        return this.custOtheridType;
    }
    
    public void setCustOtheridType(String custOtheridType) {
        this.custOtheridType = custOtheridType;
    }

    
    @Column(name="CUST_IDISSUER", length=35)
    public String getCustIdissuer() {
        return this.custIdissuer;
    }
    
    public void setCustIdissuer(String custIdissuer) {
        this.custIdissuer = custIdissuer;
    }

    
    @Column(name="CUST_DOBCITY", length=35)
    public String getCustDobcity() {
        return this.custDobcity;
    }
    
    public void setCustDobcity(String custDobcity) {
        this.custDobcity = custDobcity;
    }

    
    @Column(name="CUST_DOBCTRY", length=3)
    public String getCustDobctry() {
        return this.custDobctry;
    }
    
    public void setCustDobctry(String custDobctry) {
        this.custDobctry = custDobctry;
    }

    
    @Column(name="CUST_BANKCODE", length=20)
    public String getCustBankcode() {
        return this.custBankcode;
    }
    
    public void setCustBankcode(String custBankcode) {
        this.custBankcode = custBankcode;
    }

    
    @Column(name="BENEF_CTRY", length=3)
    public String getBenefCtry() {
        return this.benefCtry;
    }
    
    public void setBenefCtry(String benefCtry) {
        this.benefCtry = benefCtry;
    }

    
    @Column(name="CPTY_TYPE", length=1)
    public String getCptyType() {
        return this.cptyType;
    }
    
    public void setCptyType(String cptyType) {
        this.cptyType = cptyType;
    }

    
    @Column(name="CPTY_IDTYPE", length=2)
    public String getCptyIdtype() {
        return this.cptyIdtype;
    }
    
    public void setCptyIdtype(String cptyIdtype) {
        this.cptyIdtype = cptyIdtype;
    }

    
    @Column(name="CPTY_IDVALUE", length=35)
    public String getCptyIdvalue() {
        return this.cptyIdvalue;
    }
    
    public void setCptyIdvalue(String cptyIdvalue) {
        this.cptyIdvalue = cptyIdvalue;
    }

    
    @Column(name="CPTY_OTHERID_TYPE", length=35)
    public String getCptyOtheridType() {
        return this.cptyOtheridType;
    }
    
    public void setCptyOtheridType(String cptyOtheridType) {
        this.cptyOtheridType = cptyOtheridType;
    }

    
    @Column(name="CPTY_IDISSUER", length=35)
    public String getCptyIdissuer() {
        return this.cptyIdissuer;
    }
    
    public void setCptyIdissuer(String cptyIdissuer) {
        this.cptyIdissuer = cptyIdissuer;
    }

    
    @Column(name="CPTY_DOBCITY", length=35)
    public String getCptyDobcity() {
        return this.cptyDobcity;
    }
    
    public void setCptyDobcity(String cptyDobcity) {
        this.cptyDobcity = cptyDobcity;
    }

    
    @Column(name="CPTY_DOBCTRY", length=3)
    public String getCptyDobctry() {
        return this.cptyDobctry;
    }
    
    public void setCptyDobctry(String cptyDobctry) {
        this.cptyDobctry = cptyDobctry;
    }

    
    @Column(name="INITPARTY_NAME", length=70)
    public String getInitpartyName() {
        return this.initpartyName;
    }
    
    public void setInitpartyName(String initpartyName) {
        this.initpartyName = initpartyName;
    }

    
    @Column(name="INITPARTY_ADDRESS_1", length=70)
    public String getInitpartyAddress1() {
        return this.initpartyAddress1;
    }
    
    public void setInitpartyAddress1(String initpartyAddress1) {
        this.initpartyAddress1 = initpartyAddress1;
    }

    
    @Column(name="INITPARTY_ADDRESS_2", length=70)
    public String getInitpartyAddress2() {
        return this.initpartyAddress2;
    }
    
    public void setInitpartyAddress2(String initpartyAddress2) {
        this.initpartyAddress2 = initpartyAddress2;
    }

    
    @Column(name="INITPARTY_CTRY", length=3)
    public String getInitpartyCtry() {
        return this.initpartyCtry;
    }
    
    public void setInitpartyCtry(String initpartyCtry) {
        this.initpartyCtry = initpartyCtry;
    }

    
    @Column(name="INITPARTY_TYPE", length=1)
    public String getInitpartyType() {
        return this.initpartyType;
    }
    
    public void setInitpartyType(String initpartyType) {
        this.initpartyType = initpartyType;
    }

    
    @Column(name="INITPARTY_IDTYPE", length=2)
    public String getInitpartyIdtype() {
        return this.initpartyIdtype;
    }
    
    public void setInitpartyIdtype(String initpartyIdtype) {
        this.initpartyIdtype = initpartyIdtype;
    }

    
    @Column(name="INITPARTY_IDVALUE", length=35)
    public String getInitpartyIdvalue() {
        return this.initpartyIdvalue;
    }
    
    public void setInitpartyIdvalue(String initpartyIdvalue) {
        this.initpartyIdvalue = initpartyIdvalue;
    }

    
    @Column(name="INITPARTY_OTHERID_TYPE", length=35)
    public String getInitpartyOtheridType() {
        return this.initpartyOtheridType;
    }
    
    public void setInitpartyOtheridType(String initpartyOtheridType) {
        this.initpartyOtheridType = initpartyOtheridType;
    }

    
    @Column(name="INITPARTY_IDISSUER", length=35)
    public String getInitpartyIdissuer() {
        return this.initpartyIdissuer;
    }
    
    public void setInitpartyIdissuer(String initpartyIdissuer) {
        this.initpartyIdissuer = initpartyIdissuer;
    }

    
    @Column(name="INITPARTY_DOBCITY", length=35)
    public String getInitpartyDobcity() {
        return this.initpartyDobcity;
    }
    
    public void setInitpartyDobcity(String initpartyDobcity) {
        this.initpartyDobcity = initpartyDobcity;
    }

    
    @Column(name="INITPARTY_DOBCTRY", length=3)
    public String getInitpartyDobctry() {
        return this.initpartyDobctry;
    }
    
    public void setInitpartyDobctry(String initpartyDobctry) {
        this.initpartyDobctry = initpartyDobctry;
    }

    
    @Column(name="DEBTOR_REFPARTY", length=70)
    public String getDebtorRefparty() {
        return this.debtorRefparty;
    }
    
    public void setDebtorRefparty(String debtorRefparty) {
        this.debtorRefparty = debtorRefparty;
    }

    
    @Column(name="CREDITOR_REFPARTY", length=70)
    public String getCreditorRefparty() {
        return this.creditorRefparty;
    }
    
    public void setCreditorRefparty(String creditorRefparty) {
        this.creditorRefparty = creditorRefparty;
    }

    
    @Column(name="INSTG_BANK", length=20)
    public String getInstgBank() {
        return this.instgBank;
    }
    
    public void setInstgBank(String instgBank) {
        this.instgBank = instgBank;
    }

    
    @Column(name="INSTD_BANK", length=20)
    public String getInstdBank() {
        return this.instdBank;
    }
    
    public void setInstdBank(String instdBank) {
        this.instdBank = instdBank;
    }

    
    @Column(name="STLMNT_METHOD", length=4)
    public String getStlmntMethod() {
        return this.stlmntMethod;
    }
    
    public void setStlmntMethod(String stlmntMethod) {
        this.stlmntMethod = stlmntMethod;
    }

    
    @Column(name="CLRG_SYS_ID", length=35)
    public String getClrgSysId() {
        return this.clrgSysId;
    }
    
    public void setClrgSysId(String clrgSysId) {
        this.clrgSysId = clrgSysId;
    }

    
    @Column(name="STLMNT_AC_NO", length=20)
    public String getStlmntAcNo() {
        return this.stlmntAcNo;
    }
    
    public void setStlmntAcNo(String stlmntAcNo) {
        this.stlmntAcNo = stlmntAcNo;
    }

    
    @Column(name="STLMNT_AC_CCY", length=3)
    public String getStlmntAcCcy() {
        return this.stlmntAcCcy;
    }
    
    public void setStlmntAcCcy(String stlmntAcCcy) {
        this.stlmntAcCcy = stlmntAcCcy;
    }

    
    @Column(name="ORG_MSG_NAME", length=35)
    public String getOrgMsgName() {
        return this.orgMsgName;
    }
    
    public void setOrgMsgName(String orgMsgName) {
        this.orgMsgName = orgMsgName;
    }

    
    @Column(name="ORG_MSG_REF_NO", length=35)
    public String getOrgMsgRefNo() {
        return this.orgMsgRefNo;
    }
    
    public void setOrgMsgRefNo(String orgMsgRefNo) {
        this.orgMsgRefNo = orgMsgRefNo;
    }

    
    @Column(name="REJT_ORG_NAME", length=70)
    public String getRejtOrgName() {
        return this.rejtOrgName;
    }
    
    public void setRejtOrgName(String rejtOrgName) {
        this.rejtOrgName = rejtOrgName;
    }

    
    @Column(name="REJT_ORG_BANK", length=20)
    public String getRejtOrgBank() {
        return this.rejtOrgBank;
    }
    
    public void setRejtOrgBank(String rejtOrgBank) {
        this.rejtOrgBank = rejtOrgBank;
    }

    
    @Column(name="REJT_REF_NO", length=35)
    public String getRejtRefNo() {
        return this.rejtRefNo;
    }
    
    public void setRejtRefNo(String rejtRefNo) {
        this.rejtRefNo = rejtRefNo;
    }

    
    @Column(name="REJECT_CODE_ADD", length=35)
    public String getRejectCodeAdd() {
        return this.rejectCodeAdd;
    }
    
    public void setRejectCodeAdd(String rejectCodeAdd) {
        this.rejectCodeAdd = rejectCodeAdd;
    }

    
    @Column(name="ORG_SOURCE_REF", length=35)
    public String getOrgSourceRef() {
        return this.orgSourceRef;
    }
    
    public void setOrgSourceRef(String orgSourceRef) {
        this.orgSourceRef = orgSourceRef;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ORG_STLMNT_DT", length=7)
    public Date getOrgStlmntDt() {
        return this.orgStlmntDt;
    }
    
    public void setOrgStlmntDt(Date orgStlmntDt) {
        this.orgStlmntDt = orgStlmntDt;
    }

    
    @Column(name="ORG_STLMNT_AMT", precision=22, scale=0)
    public BigDecimal getOrgStlmntAmt() {
        return this.orgStlmntAmt;
    }
    
    public void setOrgStlmntAmt(BigDecimal orgStlmntAmt) {
        this.orgStlmntAmt = orgStlmntAmt;
    }

    
    @Column(name="ORG_STLMNT_CCY", length=3)
    public String getOrgStlmntCcy() {
        return this.orgStlmntCcy;
    }
    
    public void setOrgStlmntCcy(String orgStlmntCcy) {
        this.orgStlmntCcy = orgStlmntCcy;
    }

    
    @Column(name="DD_SEQ_TYPE", length=4)
    public String getDdSeqType() {
        return this.ddSeqType;
    }
    
    public void setDdSeqType(String ddSeqType) {
        this.ddSeqType = ddSeqType;
    }

    
    @Column(name="MANDATE_ID", length=35)
    public String getMandateId() {
        return this.mandateId;
    }
    
    public void setMandateId(String mandateId) {
        this.mandateId = mandateId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MAND_SIGN_DATE", length=7)
    public Date getMandSignDate() {
        return this.mandSignDate;
    }
    
    public void setMandSignDate(Date mandSignDate) {
        this.mandSignDate = mandSignDate;
    }

    
    @Column(name="CREDITOR_SCH_ID", length=35)
    public String getCreditorSchId() {
        return this.creditorSchId;
    }
    
    public void setCreditorSchId(String creditorSchId) {
        this.creditorSchId = creditorSchId;
    }

    
    @Column(name="MAND_AMEND_IND", length=1)
    public String getMandAmendInd() {
        return this.mandAmendInd;
    }
    
    public void setMandAmendInd(String mandAmendInd) {
        this.mandAmendInd = mandAmendInd;
    }

    
    @Column(name="MAND_AMEND_TYPE", length=35)
    public String getMandAmendType() {
        return this.mandAmendType;
    }
    
    public void setMandAmendType(String mandAmendType) {
        this.mandAmendType = mandAmendType;
    }

    
    @Column(name="ORG_MANDATE_ID", length=35)
    public String getOrgMandateId() {
        return this.orgMandateId;
    }
    
    public void setOrgMandateId(String orgMandateId) {
        this.orgMandateId = orgMandateId;
    }

    
    @Column(name="ORG_CREDITOR_SCH_ID", length=35)
    public String getOrgCreditorSchId() {
        return this.orgCreditorSchId;
    }
    
    public void setOrgCreditorSchId(String orgCreditorSchId) {
        this.orgCreditorSchId = orgCreditorSchId;
    }

    
    @Column(name="ORG_CREDITOR_NAME", length=70)
    public String getOrgCreditorName() {
        return this.orgCreditorName;
    }
    
    public void setOrgCreditorName(String orgCreditorName) {
        this.orgCreditorName = orgCreditorName;
    }

    
    @Column(name="ORG_DEBTOR_ACC", length=20)
    public String getOrgDebtorAcc() {
        return this.orgDebtorAcc;
    }
    
    public void setOrgDebtorAcc(String orgDebtorAcc) {
        this.orgDebtorAcc = orgDebtorAcc;
    }

    
    @Column(name="ORG_DEBTOR_BANK", length=11)
    public String getOrgDebtorBank() {
        return this.orgDebtorBank;
    }
    
    public void setOrgDebtorBank(String orgDebtorBank) {
        this.orgDebtorBank = orgDebtorBank;
    }

    
    @Column(name="CHARGE_ACCOUNT", length=35)
    public String getChargeAccount() {
        return this.chargeAccount;
    }
    
    public void setChargeAccount(String chargeAccount) {
        this.chargeAccount = chargeAccount;
    }

    
    @Column(name="DBTRACCT_IBAN", length=35)
    public String getDbtracctIban() {
        return this.dbtracctIban;
    }
    
    public void setDbtracctIban(String dbtracctIban) {
        this.dbtracctIban = dbtracctIban;
    }

    
    @Column(name="CDRTACCT_IBAN", length=35)
    public String getCdrtacctIban() {
        return this.cdrtacctIban;
    }
    
    public void setCdrtacctIban(String cdrtacctIban) {
        this.cdrtacctIban = cdrtacctIban;
    }

    
    @Column(name="ORG_DEBTOR_IBAN", length=35)
    public String getOrgDebtorIban() {
        return this.orgDebtorIban;
    }
    
    public void setOrgDebtorIban(String orgDebtorIban) {
        this.orgDebtorIban = orgDebtorIban;
    }

    
    @Column(name="ULT_DEBTOR_ID", length=1)
    public String getUltDebtorId() {
        return this.ultDebtorId;
    }
    
    public void setUltDebtorId(String ultDebtorId) {
        this.ultDebtorId = ultDebtorId;
    }

    
    @Column(name="ULT_DEBTOR_ID_TYPE", length=35)
    public String getUltDebtorIdType() {
        return this.ultDebtorIdType;
    }
    
    public void setUltDebtorIdType(String ultDebtorIdType) {
        this.ultDebtorIdType = ultDebtorIdType;
    }

    
    @Column(name="ULT_DEBTOR_ID_VALUE", length=35)
    public String getUltDebtorIdValue() {
        return this.ultDebtorIdValue;
    }
    
    public void setUltDebtorIdValue(String ultDebtorIdValue) {
        this.ultDebtorIdValue = ultDebtorIdValue;
    }

    
    @Column(name="ULT_DEBTOR_OTHER_ID_TYPE", length=35)
    public String getUltDebtorOtherIdType() {
        return this.ultDebtorOtherIdType;
    }
    
    public void setUltDebtorOtherIdType(String ultDebtorOtherIdType) {
        this.ultDebtorOtherIdType = ultDebtorOtherIdType;
    }

    
    @Column(name="ULT_DEBTOR_ID_ISSUER", length=35)
    public String getUltDebtorIdIssuer() {
        return this.ultDebtorIdIssuer;
    }
    
    public void setUltDebtorIdIssuer(String ultDebtorIdIssuer) {
        this.ultDebtorIdIssuer = ultDebtorIdIssuer;
    }

    
    @Column(name="ULT_CREDITOR_ID", length=1)
    public String getUltCreditorId() {
        return this.ultCreditorId;
    }
    
    public void setUltCreditorId(String ultCreditorId) {
        this.ultCreditorId = ultCreditorId;
    }

    
    @Column(name="ULT_CREDITOR_ID_TYPE", length=35)
    public String getUltCreditorIdType() {
        return this.ultCreditorIdType;
    }
    
    public void setUltCreditorIdType(String ultCreditorIdType) {
        this.ultCreditorIdType = ultCreditorIdType;
    }

    
    @Column(name="ULT_CREDITOR_ID_VALUE", length=35)
    public String getUltCreditorIdValue() {
        return this.ultCreditorIdValue;
    }
    
    public void setUltCreditorIdValue(String ultCreditorIdValue) {
        this.ultCreditorIdValue = ultCreditorIdValue;
    }

    
    @Column(name="ULT_CREDITOR_OTHER_ID_TYPE", length=35)
    public String getUltCreditorOtherIdType() {
        return this.ultCreditorOtherIdType;
    }
    
    public void setUltCreditorOtherIdType(String ultCreditorOtherIdType) {
        this.ultCreditorOtherIdType = ultCreditorOtherIdType;
    }

    
    @Column(name="ULT_CREDITOR_ID_ISSUER", length=35)
    public String getUltCreditorIdIssuer() {
        return this.ultCreditorIdIssuer;
    }
    
    public void setUltCreditorIdIssuer(String ultCreditorIdIssuer) {
        this.ultCreditorIdIssuer = ultCreditorIdIssuer;
    }

    
    @Column(name="CATEGORY_PURPOSE", length=10)
    public String getCategoryPurpose() {
        return this.categoryPurpose;
    }
    
    public void setCategoryPurpose(String categoryPurpose) {
        this.categoryPurpose = categoryPurpose;
    }

    
    @Column(name="PURPOSE_TYPE", length=1)
    public String getPurposeType() {
        return this.purposeType;
    }
    
    public void setPurposeType(String purposeType) {
        this.purposeType = purposeType;
    }

    
    @Column(name="PURPOSE_VALUE", length=35)
    public String getPurposeValue() {
        return this.purposeValue;
    }
    
    public void setPurposeValue(String purposeValue) {
        this.purposeValue = purposeValue;
    }

    
    @Column(name="LOCAL_INSTRUMENT_TYPE", length=1)
    public String getLocalInstrumentType() {
        return this.localInstrumentType;
    }
    
    public void setLocalInstrumentType(String localInstrumentType) {
        this.localInstrumentType = localInstrumentType;
    }

    
    @Column(name="LOCAL_INSTRUMENT_VALUE", length=35)
    public String getLocalInstrumentValue() {
        return this.localInstrumentValue;
    }
    
    public void setLocalInstrumentValue(String localInstrumentValue) {
        this.localInstrumentValue = localInstrumentValue;
    }

    
    @Column(name="COMP_CCY", length=3)
    public String getCompCcy() {
        return this.compCcy;
    }
    
    public void setCompCcy(String compCcy) {
        this.compCcy = compCcy;
    }

    
    @Column(name="COMP_AMT", precision=22, scale=3)
    public BigDecimal getCompAmt() {
        return this.compAmt;
    }
    
    public void setCompAmt(BigDecimal compAmt) {
        this.compAmt = compAmt;
    }

    
    @Column(name="ELEC_SIG", length=1025)
    public String getElecSig() {
        return this.elecSig;
    }
    
    public void setElecSig(String elecSig) {
        this.elecSig = elecSig;
    }

    
    @Column(name="ULT_DEBTOR_BIRTH_CITY", length=35)
    public String getUltDebtorBirthCity() {
        return this.ultDebtorBirthCity;
    }
    
    public void setUltDebtorBirthCity(String ultDebtorBirthCity) {
        this.ultDebtorBirthCity = ultDebtorBirthCity;
    }

    
    @Column(name="ULT_DEBTOR_BIRTH_COUNTRY", length=3)
    public String getUltDebtorBirthCountry() {
        return this.ultDebtorBirthCountry;
    }
    
    public void setUltDebtorBirthCountry(String ultDebtorBirthCountry) {
        this.ultDebtorBirthCountry = ultDebtorBirthCountry;
    }

    
    @Column(name="ULT_CREDITOR_BIRTH_CITY", length=35)
    public String getUltCreditorBirthCity() {
        return this.ultCreditorBirthCity;
    }
    
    public void setUltCreditorBirthCity(String ultCreditorBirthCity) {
        this.ultCreditorBirthCity = ultCreditorBirthCity;
    }

    
    @Column(name="ULT_CREDITOR_BIRTH_COUNTRY", length=3)
    public String getUltCreditorBirthCountry() {
        return this.ultCreditorBirthCountry;
    }
    
    public void setUltCreditorBirthCountry(String ultCreditorBirthCountry) {
        this.ultCreditorBirthCountry = ultCreditorBirthCountry;
    }

    
    @Column(name="CREDITOR_SCH_TYPE", length=2)
    public String getCreditorSchType() {
        return this.creditorSchType;
    }
    
    public void setCreditorSchType(String creditorSchType) {
        this.creditorSchType = creditorSchType;
    }

    
    @Column(name="CREDITOR_SCH_ID_VALUE", length=35)
    public String getCreditorSchIdValue() {
        return this.creditorSchIdValue;
    }
    
    public void setCreditorSchIdValue(String creditorSchIdValue) {
        this.creditorSchIdValue = creditorSchIdValue;
    }

    
    @Column(name="CREDITOR_SCH_ID_TYPE", length=35)
    public String getCreditorSchIdType() {
        return this.creditorSchIdType;
    }
    
    public void setCreditorSchIdType(String creditorSchIdType) {
        this.creditorSchIdType = creditorSchIdType;
    }

    
    @Column(name="ORG_CREDITOR_SCH_TYPE", length=2)
    public String getOrgCreditorSchType() {
        return this.orgCreditorSchType;
    }
    
    public void setOrgCreditorSchType(String orgCreditorSchType) {
        this.orgCreditorSchType = orgCreditorSchType;
    }

    
    @Column(name="ORG_CREDITOR_SCH_ID_VALUE", length=35)
    public String getOrgCreditorSchIdValue() {
        return this.orgCreditorSchIdValue;
    }
    
    public void setOrgCreditorSchIdValue(String orgCreditorSchIdValue) {
        this.orgCreditorSchIdValue = orgCreditorSchIdValue;
    }

    
    @Column(name="ORG_CREDITOR_SCH_ID_TYPE", length=35)
    public String getOrgCreditorSchIdType() {
        return this.orgCreditorSchIdType;
    }
    
    public void setOrgCreditorSchIdType(String orgCreditorSchIdType) {
        this.orgCreditorSchIdType = orgCreditorSchIdType;
    }

    
    @Column(name="REMARKS", length=765)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="CPTY_NAME", length=35)
    public String getCptyName() {
        return this.cptyName;
    }
    
    public void setCptyName(String cptyName) {
        this.cptyName = cptyName;
    }

    
    @Column(name="CPTY_BANKCODE", length=20)
    public String getCptyBankcode() {
        return this.cptyBankcode;
    }
    
    public void setCptyBankcode(String cptyBankcode) {
        this.cptyBankcode = cptyBankcode;
    }

    
    @Column(name="PROCESS_SEQ_NO", precision=35, scale=0)
    public BigDecimal getProcessSeqNo() {
        return this.processSeqNo;
    }
    
    public void setProcessSeqNo(BigDecimal processSeqNo) {
        this.processSeqNo = processSeqNo;
    }

    
    @Column(name="FILE_LEV_CUST_CONSOL_REQ", length=1)
    public String getFileLevCustConsolReq() {
        return this.fileLevCustConsolReq;
    }
    
    public void setFileLevCustConsolReq(String fileLevCustConsolReq) {
        this.fileLevCustConsolReq = fileLevCustConsolReq;
    }

    
    @Column(name="PAYMENT_INFO_ID", length=35)
    public String getPaymentInfoId() {
        return this.paymentInfoId;
    }
    
    public void setPaymentInfoId(String paymentInfoId) {
        this.paymentInfoId = paymentInfoId;
    }

    
    @Column(name="TXN_RELATED_STATUS", length=1)
    public String getTxnRelatedStatus() {
        return this.txnRelatedStatus;
    }
    
    public void setTxnRelatedStatus(String txnRelatedStatus) {
        this.txnRelatedStatus = txnRelatedStatus;
    }

    
    @Column(name="FILE_REC_SEQ", length=35)
    public String getFileRecSeq() {
        return this.fileRecSeq;
    }
    
    public void setFileRecSeq(String fileRecSeq) {
        this.fileRecSeq = fileRecSeq;
    }

    
    @Column(name="SEND_TO_HOST", length=1)
    public String getSendToHost() {
        return this.sendToHost;
    }
    
    public void setSendToHost(String sendToHost) {
        this.sendToHost = sendToHost;
    }

    
    @Column(name="CATEGORY_PURPOSE_TYPE", length=1)
    public String getCategoryPurposeType() {
        return this.categoryPurposeType;
    }
    
    public void setCategoryPurposeType(String categoryPurposeType) {
        this.categoryPurposeType = categoryPurposeType;
    }




}


