package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Chaseconfig generated by hbm2java
 */
@Entity
@Table(name="CHASECONFIG"
    ,schema="FCDBADMIN_RK"
)
public class Chaseconfig  implements java.io.Serializable {


     private ChaseconfigId id;
     private String idalert;
     private String nextidchase;
     private BigDecimal nextchasegap;
     private String chasehandlerclass;
     private String properties;

    public Chaseconfig() {
    }

	
    public Chaseconfig(ChaseconfigId id) {
        this.id = id;
    }
    public Chaseconfig(ChaseconfigId id, String idalert, String nextidchase, BigDecimal nextchasegap, String chasehandlerclass, String properties) {
       this.id = id;
       this.idalert = idalert;
       this.nextidchase = nextidchase;
       this.nextchasegap = nextchasegap;
       this.chasehandlerclass = chasehandlerclass;
       this.properties = properties;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idchase", column=@Column(name="IDCHASE", nullable=false, length=50) ) } )
    public ChaseconfigId getId() {
        return this.id;
    }
    
    public void setId(ChaseconfigId id) {
        this.id = id;
    }

    
    @Column(name="IDALERT", length=50)
    public String getIdalert() {
        return this.idalert;
    }
    
    public void setIdalert(String idalert) {
        this.idalert = idalert;
    }

    
    @Column(name="NEXTIDCHASE", length=50)
    public String getNextidchase() {
        return this.nextidchase;
    }
    
    public void setNextidchase(String nextidchase) {
        this.nextidchase = nextidchase;
    }

    
    @Column(name="NEXTCHASEGAP", precision=22, scale=0)
    public BigDecimal getNextchasegap() {
        return this.nextchasegap;
    }
    
    public void setNextchasegap(BigDecimal nextchasegap) {
        this.nextchasegap = nextchasegap;
    }

    
    @Column(name="CHASEHANDLERCLASS")
    public String getChasehandlerclass() {
        return this.chasehandlerclass;
    }
    
    public void setChasehandlerclass(String chasehandlerclass) {
        this.chasehandlerclass = chasehandlerclass;
    }

    
    @Column(name="PROPERTIES")
    public String getProperties() {
        return this.properties;
    }
    
    public void setProperties(String properties) {
        this.properties = properties;
    }




}


