package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CustExternalAccount generated by hbm2java
 */
@Entity
@Table(name="CUST_EXTERNAL_ACCOUNT"
    ,schema="FCDBADMIN_RK"
)
public class CustExternalAccount  implements java.io.Serializable {


     private CustExternalAccountId id;
     private Boolean verifyCount;
     private BigDecimal pennyAmt;

    public CustExternalAccount() {
    }

	
    public CustExternalAccount(CustExternalAccountId id) {
        this.id = id;
    }
    public CustExternalAccount(CustExternalAccountId id, Boolean verifyCount, BigDecimal pennyAmt) {
       this.id = id;
       this.verifyCount = verifyCount;
       this.pennyAmt = pennyAmt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=30) ), 
        @AttributeOverride(name="extAcctNo", column=@Column(name="EXT_ACCT_NO", nullable=false, length=20) ) } )
    public CustExternalAccountId getId() {
        return this.id;
    }
    
    public void setId(CustExternalAccountId id) {
        this.id = id;
    }

    
    @Column(name="VERIFY_COUNT", precision=1, scale=0)
    public Boolean getVerifyCount() {
        return this.verifyCount;
    }
    
    public void setVerifyCount(Boolean verifyCount) {
        this.verifyCount = verifyCount;
    }

    
    @Column(name="PENNY_AMT", precision=3, scale=3)
    public BigDecimal getPennyAmt() {
        return this.pennyAmt;
    }
    
    public void setPennyAmt(BigDecimal pennyAmt) {
        this.pennyAmt = pennyAmt;
    }




}


