package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DataDictionary generated by hbm2java
 */
@Entity
@Table(name="DATA_DICTIONARY"
    ,schema="FCDBADMIN_RK"
)
public class DataDictionary  implements java.io.Serializable {


     private String fieldname;
     private DataDictionaryTypes dataDictionaryTypes;
     private String fielddesc;
     private Long minlength;
     private Long maxlength;
     private String fieldformat;
     private String comments;

    public DataDictionary() {
    }

	
    public DataDictionary(String fieldname) {
        this.fieldname = fieldname;
    }
    public DataDictionary(String fieldname, DataDictionaryTypes dataDictionaryTypes, String fielddesc, Long minlength, Long maxlength, String fieldformat, String comments) {
       this.fieldname = fieldname;
       this.dataDictionaryTypes = dataDictionaryTypes;
       this.fielddesc = fielddesc;
       this.minlength = minlength;
       this.maxlength = maxlength;
       this.fieldformat = fieldformat;
       this.comments = comments;
    }
   
     @Id 

    
    @Column(name="FIELDNAME", unique=true, nullable=false)
    public String getFieldname() {
        return this.fieldname;
    }
    
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FIELDTYPE")
    public DataDictionaryTypes getDataDictionaryTypes() {
        return this.dataDictionaryTypes;
    }
    
    public void setDataDictionaryTypes(DataDictionaryTypes dataDictionaryTypes) {
        this.dataDictionaryTypes = dataDictionaryTypes;
    }

    
    @Column(name="FIELDDESC", length=100)
    public String getFielddesc() {
        return this.fielddesc;
    }
    
    public void setFielddesc(String fielddesc) {
        this.fielddesc = fielddesc;
    }

    
    @Column(name="MINLENGTH", precision=15, scale=0)
    public Long getMinlength() {
        return this.minlength;
    }
    
    public void setMinlength(Long minlength) {
        this.minlength = minlength;
    }

    
    @Column(name="MAXLENGTH", precision=15, scale=0)
    public Long getMaxlength() {
        return this.maxlength;
    }
    
    public void setMaxlength(Long maxlength) {
        this.maxlength = maxlength;
    }

    
    @Column(name="FIELDFORMAT")
    public String getFieldformat() {
        return this.fieldformat;
    }
    
    public void setFieldformat(String fieldformat) {
        this.fieldformat = fieldformat;
    }

    
    @Column(name="COMMENTS")
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


