package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Digipassdata generated by hbm2java
 */
@Entity
@Table(name="DIGIPASSDATA"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"APPLICATIONNAME", "SERIALNO"}) 
)
public class Digipassdata  implements java.io.Serializable {


     private String serialno;
     private String digipasstype;
     private String digipassmode;
     private byte[] digipassdata;
     private String dpxfilename;
     private String applicationname;
     private Character flgactive;
     private Character flgassign;
     private String makerid;
     private String checkerid;
     private Date datbatchupload;
     private Date datmanipulated;

    public Digipassdata() {
    }

	
    public Digipassdata(String serialno) {
        this.serialno = serialno;
    }
    public Digipassdata(String serialno, String digipasstype, String digipassmode, byte[] digipassdata, String dpxfilename, String applicationname, Character flgactive, Character flgassign, String makerid, String checkerid, Date datbatchupload, Date datmanipulated) {
       this.serialno = serialno;
       this.digipasstype = digipasstype;
       this.digipassmode = digipassmode;
       this.digipassdata = digipassdata;
       this.dpxfilename = dpxfilename;
       this.applicationname = applicationname;
       this.flgactive = flgactive;
       this.flgassign = flgassign;
       this.makerid = makerid;
       this.checkerid = checkerid;
       this.datbatchupload = datbatchupload;
       this.datmanipulated = datmanipulated;
    }
   
     @Id 

    
    @Column(name="SERIALNO", nullable=false, length=22)
    public String getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(String serialno) {
        this.serialno = serialno;
    }

    
    @Column(name="DIGIPASSTYPE", length=5)
    public String getDigipasstype() {
        return this.digipasstype;
    }
    
    public void setDigipasstype(String digipasstype) {
        this.digipasstype = digipasstype;
    }

    
    @Column(name="DIGIPASSMODE", length=2)
    public String getDigipassmode() {
        return this.digipassmode;
    }
    
    public void setDigipassmode(String digipassmode) {
        this.digipassmode = digipassmode;
    }

    
    @Column(name="DIGIPASSDATA")
    public byte[] getDigipassdata() {
        return this.digipassdata;
    }
    
    public void setDigipassdata(byte[] digipassdata) {
        this.digipassdata = digipassdata;
    }

    
    @Column(name="DPXFILENAME", length=200)
    public String getDpxfilename() {
        return this.dpxfilename;
    }
    
    public void setDpxfilename(String dpxfilename) {
        this.dpxfilename = dpxfilename;
    }

    
    @Column(name="APPLICATIONNAME", length=20)
    public String getApplicationname() {
        return this.applicationname;
    }
    
    public void setApplicationname(String applicationname) {
        this.applicationname = applicationname;
    }

    
    @Column(name="FLGACTIVE", length=1)
    public Character getFlgactive() {
        return this.flgactive;
    }
    
    public void setFlgactive(Character flgactive) {
        this.flgactive = flgactive;
    }

    
    @Column(name="FLGASSIGN", length=1)
    public Character getFlgassign() {
        return this.flgassign;
    }
    
    public void setFlgassign(Character flgassign) {
        this.flgassign = flgassign;
    }

    
    @Column(name="MAKERID", length=10)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    
    @Column(name="CHECKERID", length=10)
    public String getCheckerid() {
        return this.checkerid;
    }
    
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATBATCHUPLOAD", length=7)
    public Date getDatbatchupload() {
        return this.datbatchupload;
    }
    
    public void setDatbatchupload(Date datbatchupload) {
        this.datbatchupload = datbatchupload;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMANIPULATED", length=7)
    public Date getDatmanipulated() {
        return this.datmanipulated;
    }
    
    public void setDatmanipulated(Date datmanipulated) {
        this.datmanipulated = datmanipulated;
    }




}


