package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTCommunications generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_COMMUNICATIONS"
    ,schema="FCDBADMIN_RK"
)
public class FcatTCommunications  implements java.io.Serializable {


     private BigDecimal messageid;
     private Mstentity mstentityByReceiverIdEntity;
     private Mstentity mstentityBySenderIdEntity;
     private BigDecimal linkedid;
     private String senderid;
     private String senderIdChannel;
     private Character senderType;
     private String senderName;
     private String receiverid;
     private String receiverIdChannel;
     private Character receiverType;
     private String receiverName;
     private String receiverRoleid;
     private String ccIdName;
     private String ccId;
     private String ccIdEntity;
     private String subjectId;
     private String customSubject;
     private Blob message;
     private Date commDate;
     private Character isread;
     private Date expiryDate;
     private String messageType;
     private String token1;
     private String externalid;
     private Character ispurge;
     private String commuCust;
     private String hostCommuChannel;
     private Character isreplied;
     private Set<Mailmessageattach> mailmessageattaches = new HashSet<Mailmessageattach>(0);

    public FcatTCommunications() {
    }

	
    public FcatTCommunications(BigDecimal messageid) {
        this.messageid = messageid;
    }
    public FcatTCommunications(BigDecimal messageid, Mstentity mstentityByReceiverIdEntity, Mstentity mstentityBySenderIdEntity, BigDecimal linkedid, String senderid, String senderIdChannel, Character senderType, String senderName, String receiverid, String receiverIdChannel, Character receiverType, String receiverName, String receiverRoleid, String ccIdName, String ccId, String ccIdEntity, String subjectId, String customSubject, Blob message, Date commDate, Character isread, Date expiryDate, String messageType, String token1, String externalid, Character ispurge, String commuCust, String hostCommuChannel, Character isreplied, Set<Mailmessageattach> mailmessageattaches) {
       this.messageid = messageid;
       this.mstentityByReceiverIdEntity = mstentityByReceiverIdEntity;
       this.mstentityBySenderIdEntity = mstentityBySenderIdEntity;
       this.linkedid = linkedid;
       this.senderid = senderid;
       this.senderIdChannel = senderIdChannel;
       this.senderType = senderType;
       this.senderName = senderName;
       this.receiverid = receiverid;
       this.receiverIdChannel = receiverIdChannel;
       this.receiverType = receiverType;
       this.receiverName = receiverName;
       this.receiverRoleid = receiverRoleid;
       this.ccIdName = ccIdName;
       this.ccId = ccId;
       this.ccIdEntity = ccIdEntity;
       this.subjectId = subjectId;
       this.customSubject = customSubject;
       this.message = message;
       this.commDate = commDate;
       this.isread = isread;
       this.expiryDate = expiryDate;
       this.messageType = messageType;
       this.token1 = token1;
       this.externalid = externalid;
       this.ispurge = ispurge;
       this.commuCust = commuCust;
       this.hostCommuChannel = hostCommuChannel;
       this.isreplied = isreplied;
       this.mailmessageattaches = mailmessageattaches;
    }
   
     @Id 

    
    @Column(name="MESSAGEID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(BigDecimal messageid) {
        this.messageid = messageid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RECEIVER_ID_ENTITY")
    public Mstentity getMstentityByReceiverIdEntity() {
        return this.mstentityByReceiverIdEntity;
    }
    
    public void setMstentityByReceiverIdEntity(Mstentity mstentityByReceiverIdEntity) {
        this.mstentityByReceiverIdEntity = mstentityByReceiverIdEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SENDER_ID_ENTITY")
    public Mstentity getMstentityBySenderIdEntity() {
        return this.mstentityBySenderIdEntity;
    }
    
    public void setMstentityBySenderIdEntity(Mstentity mstentityBySenderIdEntity) {
        this.mstentityBySenderIdEntity = mstentityBySenderIdEntity;
    }

    
    @Column(name="LINKEDID", precision=22, scale=0)
    public BigDecimal getLinkedid() {
        return this.linkedid;
    }
    
    public void setLinkedid(BigDecimal linkedid) {
        this.linkedid = linkedid;
    }

    
    @Column(name="SENDERID", length=20)
    public String getSenderid() {
        return this.senderid;
    }
    
    public void setSenderid(String senderid) {
        this.senderid = senderid;
    }

    
    @Column(name="SENDER_ID_CHANNEL", length=4)
    public String getSenderIdChannel() {
        return this.senderIdChannel;
    }
    
    public void setSenderIdChannel(String senderIdChannel) {
        this.senderIdChannel = senderIdChannel;
    }

    
    @Column(name="SENDER_TYPE", length=1)
    public Character getSenderType() {
        return this.senderType;
    }
    
    public void setSenderType(Character senderType) {
        this.senderType = senderType;
    }

    
    @Column(name="SENDER_NAME", length=101)
    public String getSenderName() {
        return this.senderName;
    }
    
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    
    @Column(name="RECEIVERID", length=20)
    public String getReceiverid() {
        return this.receiverid;
    }
    
    public void setReceiverid(String receiverid) {
        this.receiverid = receiverid;
    }

    
    @Column(name="RECEIVER_ID_CHANNEL", length=4)
    public String getReceiverIdChannel() {
        return this.receiverIdChannel;
    }
    
    public void setReceiverIdChannel(String receiverIdChannel) {
        this.receiverIdChannel = receiverIdChannel;
    }

    
    @Column(name="RECEIVER_TYPE", length=1)
    public Character getReceiverType() {
        return this.receiverType;
    }
    
    public void setReceiverType(Character receiverType) {
        this.receiverType = receiverType;
    }

    
    @Column(name="RECEIVER_NAME", length=40)
    public String getReceiverName() {
        return this.receiverName;
    }
    
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    
    @Column(name="RECEIVER_ROLEID", length=4000)
    public String getReceiverRoleid() {
        return this.receiverRoleid;
    }
    
    public void setReceiverRoleid(String receiverRoleid) {
        this.receiverRoleid = receiverRoleid;
    }

    
    @Column(name="CC_ID_NAME", length=40)
    public String getCcIdName() {
        return this.ccIdName;
    }
    
    public void setCcIdName(String ccIdName) {
        this.ccIdName = ccIdName;
    }

    
    @Column(name="CC_ID", length=20)
    public String getCcId() {
        return this.ccId;
    }
    
    public void setCcId(String ccId) {
        this.ccId = ccId;
    }

    
    @Column(name="CC_ID_ENTITY", length=10)
    public String getCcIdEntity() {
        return this.ccIdEntity;
    }
    
    public void setCcIdEntity(String ccIdEntity) {
        this.ccIdEntity = ccIdEntity;
    }

    
    @Column(name="SUBJECT_ID", length=20)
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="CUSTOM_SUBJECT")
    public String getCustomSubject() {
        return this.customSubject;
    }
    
    public void setCustomSubject(String customSubject) {
        this.customSubject = customSubject;
    }

    
    @Column(name="MESSAGE")
    public Blob getMessage() {
        return this.message;
    }
    
    public void setMessage(Blob message) {
        this.message = message;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="COMM_DATE", length=7)
    public Date getCommDate() {
        return this.commDate;
    }
    
    public void setCommDate(Date commDate) {
        this.commDate = commDate;
    }

    
    @Column(name="ISREAD", length=1)
    public Character getIsread() {
        return this.isread;
    }
    
    public void setIsread(Character isread) {
        this.isread = isread;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRY_DATE", length=7)
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    
    @Column(name="MESSAGE_TYPE", length=4)
    public String getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    
    @Column(name="TOKEN1", length=50)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="EXTERNALID", length=20)
    public String getExternalid() {
        return this.externalid;
    }
    
    public void setExternalid(String externalid) {
        this.externalid = externalid;
    }

    
    @Column(name="ISPURGE", length=1)
    public Character getIspurge() {
        return this.ispurge;
    }
    
    public void setIspurge(Character ispurge) {
        this.ispurge = ispurge;
    }

    
    @Column(name="COMMU_CUST", length=20)
    public String getCommuCust() {
        return this.commuCust;
    }
    
    public void setCommuCust(String commuCust) {
        this.commuCust = commuCust;
    }

    
    @Column(name="HOST_COMMU_CHANNEL", length=50)
    public String getHostCommuChannel() {
        return this.hostCommuChannel;
    }
    
    public void setHostCommuChannel(String hostCommuChannel) {
        this.hostCommuChannel = hostCommuChannel;
    }

    
    @Column(name="ISREPLIED", length=1)
    public Character getIsreplied() {
        return this.isreplied;
    }
    
    public void setIsreplied(Character isreplied) {
        this.isreplied = isreplied;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fcatTCommunications")
    public Set<Mailmessageattach> getMailmessageattaches() {
        return this.mailmessageattaches;
    }
    
    public void setMailmessageattaches(Set<Mailmessageattach> mailmessageattaches) {
        this.mailmessageattaches = mailmessageattaches;
    }




}


