package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTMstfxrate generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_MSTFXRATE"
    ,schema="FCDBADMIN_RK"
)
public class FcatTMstfxrate  implements java.io.Serializable {


     private FcatTMstfxrateId id;
     private Mstcurrency mstcurrencyByFkFcatTMstfxrateCodcur;
     private Mstcurrency mstcurrencyByFk2FcatTMstfxrate;
     private Date datasof;
     private BigDecimal numbuyrate;
     private BigDecimal numsellrate;
     private BigDecimal nummidrate;
     private Integer numquotation;
     private Character codmethod;
     private Date dtime;
     private BigDecimal slno;
     private BigDecimal numchqbuyrate;
     private BigDecimal numchqsellrate;
     private BigDecimal numxferbuyrate;
     private BigDecimal numxfersellrate;
     private String namcurrfrom;
     private String namcurrto;

    public FcatTMstfxrate() {
    }

	
    public FcatTMstfxrate(FcatTMstfxrateId id, Mstcurrency mstcurrencyByFkFcatTMstfxrateCodcur, Mstcurrency mstcurrencyByFk2FcatTMstfxrate) {
        this.id = id;
        this.mstcurrencyByFkFcatTMstfxrateCodcur = mstcurrencyByFkFcatTMstfxrateCodcur;
        this.mstcurrencyByFk2FcatTMstfxrate = mstcurrencyByFk2FcatTMstfxrate;
    }
    public FcatTMstfxrate(FcatTMstfxrateId id, Mstcurrency mstcurrencyByFkFcatTMstfxrateCodcur, Mstcurrency mstcurrencyByFk2FcatTMstfxrate, Date datasof, BigDecimal numbuyrate, BigDecimal numsellrate, BigDecimal nummidrate, Integer numquotation, Character codmethod, Date dtime, BigDecimal slno, BigDecimal numchqbuyrate, BigDecimal numchqsellrate, BigDecimal numxferbuyrate, BigDecimal numxfersellrate, String namcurrfrom, String namcurrto) {
       this.id = id;
       this.mstcurrencyByFkFcatTMstfxrateCodcur = mstcurrencyByFkFcatTMstfxrateCodcur;
       this.mstcurrencyByFk2FcatTMstfxrate = mstcurrencyByFk2FcatTMstfxrate;
       this.datasof = datasof;
       this.numbuyrate = numbuyrate;
       this.numsellrate = numsellrate;
       this.nummidrate = nummidrate;
       this.numquotation = numquotation;
       this.codmethod = codmethod;
       this.dtime = dtime;
       this.slno = slno;
       this.numchqbuyrate = numchqbuyrate;
       this.numchqsellrate = numchqsellrate;
       this.numxferbuyrate = numxferbuyrate;
       this.numxfersellrate = numxfersellrate;
       this.namcurrfrom = namcurrfrom;
       this.namcurrto = namcurrto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="codcurrfrom", column=@Column(name="CODCURRFROM", nullable=false, length=3) ), 
        @AttributeOverride(name="codcurrto", column=@Column(name="CODCURRTO", nullable=false, length=3) ), 
        @AttributeOverride(name="txtratetype", column=@Column(name="TXTRATETYPE", nullable=false, length=8) ) } )
    public FcatTMstfxrateId getId() {
        return this.id;
    }
    
    public void setId(FcatTMstfxrateId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="CODCURRFROM", referencedColumnName="NAMCCYSHRT", nullable=false, insertable=false, updatable=false) } )
    public Mstcurrency getMstcurrencyByFkFcatTMstfxrateCodcur() {
        return this.mstcurrencyByFkFcatTMstfxrateCodcur;
    }
    
    public void setMstcurrencyByFkFcatTMstfxrateCodcur(Mstcurrency mstcurrencyByFkFcatTMstfxrateCodcur) {
        this.mstcurrencyByFkFcatTMstfxrateCodcur = mstcurrencyByFkFcatTMstfxrateCodcur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="CODCURRTO", referencedColumnName="NAMCCYSHRT", nullable=false, insertable=false, updatable=false) } )
    public Mstcurrency getMstcurrencyByFk2FcatTMstfxrate() {
        return this.mstcurrencyByFk2FcatTMstfxrate;
    }
    
    public void setMstcurrencyByFk2FcatTMstfxrate(Mstcurrency mstcurrencyByFk2FcatTMstfxrate) {
        this.mstcurrencyByFk2FcatTMstfxrate = mstcurrencyByFk2FcatTMstfxrate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATASOF", length=7)
    public Date getDatasof() {
        return this.datasof;
    }
    
    public void setDatasof(Date datasof) {
        this.datasof = datasof;
    }

    
    @Column(name="NUMBUYRATE", precision=24, scale=12)
    public BigDecimal getNumbuyrate() {
        return this.numbuyrate;
    }
    
    public void setNumbuyrate(BigDecimal numbuyrate) {
        this.numbuyrate = numbuyrate;
    }

    
    @Column(name="NUMSELLRATE", precision=24, scale=12)
    public BigDecimal getNumsellrate() {
        return this.numsellrate;
    }
    
    public void setNumsellrate(BigDecimal numsellrate) {
        this.numsellrate = numsellrate;
    }

    
    @Column(name="NUMMIDRATE", precision=24, scale=12)
    public BigDecimal getNummidrate() {
        return this.nummidrate;
    }
    
    public void setNummidrate(BigDecimal nummidrate) {
        this.nummidrate = nummidrate;
    }

    
    @Column(name="NUMQUOTATION", precision=9, scale=0)
    public Integer getNumquotation() {
        return this.numquotation;
    }
    
    public void setNumquotation(Integer numquotation) {
        this.numquotation = numquotation;
    }

    
    @Column(name="CODMETHOD", length=1)
    public Character getCodmethod() {
        return this.codmethod;
    }
    
    public void setCodmethod(Character codmethod) {
        this.codmethod = codmethod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    
    @Column(name="NUMCHQBUYRATE", precision=24, scale=12)
    public BigDecimal getNumchqbuyrate() {
        return this.numchqbuyrate;
    }
    
    public void setNumchqbuyrate(BigDecimal numchqbuyrate) {
        this.numchqbuyrate = numchqbuyrate;
    }

    
    @Column(name="NUMCHQSELLRATE", precision=24, scale=12)
    public BigDecimal getNumchqsellrate() {
        return this.numchqsellrate;
    }
    
    public void setNumchqsellrate(BigDecimal numchqsellrate) {
        this.numchqsellrate = numchqsellrate;
    }

    
    @Column(name="NUMXFERBUYRATE", precision=24, scale=12)
    public BigDecimal getNumxferbuyrate() {
        return this.numxferbuyrate;
    }
    
    public void setNumxferbuyrate(BigDecimal numxferbuyrate) {
        this.numxferbuyrate = numxferbuyrate;
    }

    
    @Column(name="NUMXFERSELLRATE", precision=24, scale=12)
    public BigDecimal getNumxfersellrate() {
        return this.numxfersellrate;
    }
    
    public void setNumxfersellrate(BigDecimal numxfersellrate) {
        this.numxfersellrate = numxfersellrate;
    }

    
    @Column(name="NAMCURRFROM", length=100)
    public String getNamcurrfrom() {
        return this.namcurrfrom;
    }
    
    public void setNamcurrfrom(String namcurrfrom) {
        this.namcurrfrom = namcurrfrom;
    }

    
    @Column(name="NAMCURRTO", length=100)
    public String getNamcurrto() {
        return this.namcurrto;
    }
    
    public void setNamcurrto(String namcurrto) {
        this.namcurrto = namcurrto;
    }




}


