package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HostProductListId generated by hbm2java
 */
@Embeddable
public class HostProductListId  implements java.io.Serializable {


     private String codproduct;
     private String idEntity;

    public HostProductListId() {
    }

    public HostProductListId(String codproduct, String idEntity) {
       this.codproduct = codproduct;
       this.idEntity = idEntity;
    }
   


    @Column(name="CODPRODUCT", nullable=false, length=10)
    public String getCodproduct() {
        return this.codproduct;
    }
    
    public void setCodproduct(String codproduct) {
        this.codproduct = codproduct;
    }


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HostProductListId) ) return false;
		 HostProductListId castOther = ( HostProductListId ) other; 
         
		 return ( (this.getCodproduct()==castOther.getCodproduct()) || ( this.getCodproduct()!=null && castOther.getCodproduct()!=null && this.getCodproduct().equals(castOther.getCodproduct()) ) )
 && ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodproduct() == null ? 0 : this.getCodproduct().hashCode() );
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         return result;
   }   


}


