package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Hostauditlog generated by hbm2java
 */
@Entity
@Table(name="HOSTAUDITLOG"
    ,schema="FCDBADMIN_RK"
)
public class Hostauditlog  implements java.io.Serializable {


     private long idseq;
     private Long version;
     private String idEntity;
     private String idhost;
     private String idrequest;
     private String iduser;
     private String idtxn;
     private String referenceno;
     private Blob request;
     private Blob hostRequest;
     private Blob response;
     private Blob hostResponse;
     private String errorCode;
     private String errorDesc;
     private Serializable executionStartTime;
     private Serializable executionEndTime;
     private Character status;
     private Serializable retryDate;
     private Byte retryCount;
     private String idchanneluser;
     private String iddevice;
     private Blob hostRequestData;
     private Blob hostResponseData;
     private String hostReferenceNo;
     private String idinterface;
     private String interfaceReferenceNo;

    public Hostauditlog() {
    }

	
    public Hostauditlog(long idseq) {
        this.idseq = idseq;
    }
    public Hostauditlog(long idseq, String idEntity, String idhost, String idrequest, String iduser, String idtxn, String referenceno, Blob request, Blob hostRequest, Blob response, Blob hostResponse, String errorCode, String errorDesc, Serializable executionStartTime, Serializable executionEndTime, Character status, Serializable retryDate, Byte retryCount, String idchanneluser, String iddevice, Blob hostRequestData, Blob hostResponseData, String hostReferenceNo, String idinterface, String interfaceReferenceNo) {
       this.idseq = idseq;
       this.idEntity = idEntity;
       this.idhost = idhost;
       this.idrequest = idrequest;
       this.iduser = iduser;
       this.idtxn = idtxn;
       this.referenceno = referenceno;
       this.request = request;
       this.hostRequest = hostRequest;
       this.response = response;
       this.hostResponse = hostResponse;
       this.errorCode = errorCode;
       this.errorDesc = errorDesc;
       this.executionStartTime = executionStartTime;
       this.executionEndTime = executionEndTime;
       this.status = status;
       this.retryDate = retryDate;
       this.retryCount = retryCount;
       this.idchanneluser = idchanneluser;
       this.iddevice = iddevice;
       this.hostRequestData = hostRequestData;
       this.hostResponseData = hostResponseData;
       this.hostReferenceNo = hostReferenceNo;
       this.idinterface = idinterface;
       this.interfaceReferenceNo = interfaceReferenceNo;
    }
   
     @Id 

    
    @Column(name="IDSEQ", unique=true, nullable=false, precision=12, scale=0)
    public long getIdseq() {
        return this.idseq;
    }
    
    public void setIdseq(long idseq) {
        this.idseq = idseq;
    }

    @Version
    @Column(name="VERSION", precision=12, scale=0)
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDHOST", length=5)
    public String getIdhost() {
        return this.idhost;
    }
    
    public void setIdhost(String idhost) {
        this.idhost = idhost;
    }

    
    @Column(name="IDREQUEST")
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="REFERENCENO", length=50)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    
    @Column(name="REQUEST")
    public Blob getRequest() {
        return this.request;
    }
    
    public void setRequest(Blob request) {
        this.request = request;
    }

    
    @Column(name="HOST_REQUEST")
    public Blob getHostRequest() {
        return this.hostRequest;
    }
    
    public void setHostRequest(Blob hostRequest) {
        this.hostRequest = hostRequest;
    }

    
    @Column(name="RESPONSE")
    public Blob getResponse() {
        return this.response;
    }
    
    public void setResponse(Blob response) {
        this.response = response;
    }

    
    @Column(name="HOST_RESPONSE")
    public Blob getHostResponse() {
        return this.hostResponse;
    }
    
    public void setHostResponse(Blob hostResponse) {
        this.hostResponse = hostResponse;
    }

    
    @Column(name="ERROR_CODE")
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    
    @Column(name="ERROR_DESC", length=4000)
    public String getErrorDesc() {
        return this.errorDesc;
    }
    
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc;
    }

    
    @Column(name="EXECUTION_START_TIME")
    public Serializable getExecutionStartTime() {
        return this.executionStartTime;
    }
    
    public void setExecutionStartTime(Serializable executionStartTime) {
        this.executionStartTime = executionStartTime;
    }

    
    @Column(name="EXECUTION_END_TIME")
    public Serializable getExecutionEndTime() {
        return this.executionEndTime;
    }
    
    public void setExecutionEndTime(Serializable executionEndTime) {
        this.executionEndTime = executionEndTime;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="RETRY_DATE")
    public Serializable getRetryDate() {
        return this.retryDate;
    }
    
    public void setRetryDate(Serializable retryDate) {
        this.retryDate = retryDate;
    }

    
    @Column(name="RETRY_COUNT", precision=2, scale=0)
    public Byte getRetryCount() {
        return this.retryCount;
    }
    
    public void setRetryCount(Byte retryCount) {
        this.retryCount = retryCount;
    }

    
    @Column(name="IDCHANNELUSER")
    public String getIdchanneluser() {
        return this.idchanneluser;
    }
    
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    
    @Column(name="IDDEVICE", length=2)
    public String getIddevice() {
        return this.iddevice;
    }
    
    public void setIddevice(String iddevice) {
        this.iddevice = iddevice;
    }

    
    @Column(name="HOST_REQUEST_DATA")
    public Blob getHostRequestData() {
        return this.hostRequestData;
    }
    
    public void setHostRequestData(Blob hostRequestData) {
        this.hostRequestData = hostRequestData;
    }

    
    @Column(name="HOST_RESPONSE_DATA")
    public Blob getHostResponseData() {
        return this.hostResponseData;
    }
    
    public void setHostResponseData(Blob hostResponseData) {
        this.hostResponseData = hostResponseData;
    }

    
    @Column(name="HOST_REFERENCE_NO", length=25)
    public String getHostReferenceNo() {
        return this.hostReferenceNo;
    }
    
    public void setHostReferenceNo(String hostReferenceNo) {
        this.hostReferenceNo = hostReferenceNo;
    }

    
    @Column(name="IDINTERFACE", length=20)
    public String getIdinterface() {
        return this.idinterface;
    }
    
    public void setIdinterface(String idinterface) {
        this.idinterface = idinterface;
    }

    
    @Column(name="INTERFACE_REFERENCE_NO", length=25)
    public String getInterfaceReferenceNo() {
        return this.interfaceReferenceNo;
    }
    
    public void setInterfaceReferenceNo(String interfaceReferenceNo) {
        this.interfaceReferenceNo = interfaceReferenceNo;
    }




}


