package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hostchainrequest generated by hbm2java
 */
@Entity
@Table(name="HOSTCHAINREQUEST"
    ,schema="FCDBADMIN_RK"
)
public class Hostchainrequest  implements java.io.Serializable {


     private String referenceno;
     private String idrequest;
     private Blob request;
     private Character status;
     private Date initdate;

    public Hostchainrequest() {
    }

	
    public Hostchainrequest(String referenceno) {
        this.referenceno = referenceno;
    }
    public Hostchainrequest(String referenceno, String idrequest, Blob request, Character status, Date initdate) {
       this.referenceno = referenceno;
       this.idrequest = idrequest;
       this.request = request;
       this.status = status;
       this.initdate = initdate;
    }
   
     @Id 

    
    @Column(name="REFERENCENO", unique=true, nullable=false, length=20)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    
    @Column(name="IDREQUEST", length=20)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="REQUEST")
    public Blob getRequest() {
        return this.request;
    }
    
    public void setRequest(Blob request) {
        this.request = request;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INITDATE", length=7)
    public Date getInitdate() {
        return this.initdate;
    }
    
    public void setInitdate(Date initdate) {
        this.initdate = initdate;
    }




}


