package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * I83data generated by hbm2java
 */
@Entity
@Table(name="I83DATA"
    ,schema="FCDBADMIN_RK"
)
public class I83data  implements java.io.Serializable {


     private String ver;
     private Integer numfield;
     private Character asciibitmap;
     private Integer numsignificantfield;
     private Integer numsigfield;
     private Set<I83format> i83formats = new HashSet<I83format>(0);
     private Set<I83field> i83fields = new HashSet<I83field>(0);

    public I83data() {
    }

	
    public I83data(String ver) {
        this.ver = ver;
    }
    public I83data(String ver, Integer numfield, Character asciibitmap, Integer numsignificantfield, Integer numsigfield, Set<I83format> i83formats, Set<I83field> i83fields) {
       this.ver = ver;
       this.numfield = numfield;
       this.asciibitmap = asciibitmap;
       this.numsignificantfield = numsignificantfield;
       this.numsigfield = numsigfield;
       this.i83formats = i83formats;
       this.i83fields = i83fields;
    }
   
     @Id 

    
    @Column(name="VER", unique=true, nullable=false, length=4)
    public String getVer() {
        return this.ver;
    }
    
    public void setVer(String ver) {
        this.ver = ver;
    }

    
    @Column(name="NUMFIELD", precision=5, scale=0)
    public Integer getNumfield() {
        return this.numfield;
    }
    
    public void setNumfield(Integer numfield) {
        this.numfield = numfield;
    }

    
    @Column(name="ASCIIBITMAP", length=1)
    public Character getAsciibitmap() {
        return this.asciibitmap;
    }
    
    public void setAsciibitmap(Character asciibitmap) {
        this.asciibitmap = asciibitmap;
    }

    
    @Column(name="NUMSIGNIFICANTFIELD", precision=5, scale=0)
    public Integer getNumsignificantfield() {
        return this.numsignificantfield;
    }
    
    public void setNumsignificantfield(Integer numsignificantfield) {
        this.numsignificantfield = numsignificantfield;
    }

    
    @Column(name="NUMSIGFIELD", precision=5, scale=0)
    public Integer getNumsigfield() {
        return this.numsigfield;
    }
    
    public void setNumsigfield(Integer numsigfield) {
        this.numsigfield = numsigfield;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="i83data")
    public Set<I83format> getI83formats() {
        return this.i83formats;
    }
    
    public void setI83formats(Set<I83format> i83formats) {
        this.i83formats = i83formats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="i83data")
    public Set<I83field> getI83fields() {
        return this.i83fields;
    }
    
    public void setI83fields(Set<I83field> i83fields) {
        this.i83fields = i83fields;
    }




}


