package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsLkptxn generated by hbm2java
 */
@Entity
@Table(name="IS_LKPTXN"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "CODTXN"}) 
)
public class IsLkptxn  implements java.io.Serializable {


     private String codtxn;
     private Mstentity mstentity;

    public IsLkptxn() {
    }

	
    public IsLkptxn(String codtxn) {
        this.codtxn = codtxn;
    }
    public IsLkptxn(String codtxn, Mstentity mstentity) {
       this.codtxn = codtxn;
       this.mstentity = mstentity;
    }
   
     @Id 

    
    @Column(name="CODTXN", unique=true, nullable=false, length=25)
    public String getCodtxn() {
        return this.codtxn;
    }
    
    public void setCodtxn(String codtxn) {
        this.codtxn = codtxn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY")
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }




}


