package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsLkppricing generated by hbm2java
 */
@Entity
@Table(name="IS_LKPPRICING"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "CODPRICING"}) 
)
public class IsLkppricing  implements java.io.Serializable {


     private String codpricing;
     private Mstentity mstentity;

    public IsLkppricing() {
    }

	
    public IsLkppricing(String codpricing) {
        this.codpricing = codpricing;
    }
    public IsLkppricing(String codpricing, Mstentity mstentity) {
       this.codpricing = codpricing;
       this.mstentity = mstentity;
    }
   
     @Id 

    
    @Column(name="CODPRICING", unique=true, nullable=false, length=25)
    public String getCodpricing() {
        return this.codpricing;
    }
    
    public void setCodpricing(String codpricing) {
        this.codpricing = codpricing;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY")
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }




}


