package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsMstsideliverydetails generated by hbm2java
 */
@Entity
@Table(name="IS_MSTSIDELIVERYDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class IsMstsideliverydetails  implements java.io.Serializable {


     private IsMstsideliverydetailsId id;
     private Mstentity mstentity;
     private String deliverytype;
     private String entityid;
     private String accountno;
     private String accountname;
     private String deladdresstype;
     private String deladdress1;
     private String deladdress2;
     private String deladdress3;
     private String deladdress4;
     private String delzipcode;
     private String delcountry;
     private String delbiccode;
     private String certificatemsg;

    public IsMstsideliverydetails() {
    }

	
    public IsMstsideliverydetails(IsMstsideliverydetailsId id, Mstentity mstentity) {
        this.id = id;
        this.mstentity = mstentity;
    }
    public IsMstsideliverydetails(IsMstsideliverydetailsId id, Mstentity mstentity, String deliverytype, String entityid, String accountno, String accountname, String deladdresstype, String deladdress1, String deladdress2, String deladdress3, String deladdress4, String delzipcode, String delcountry, String delbiccode, String certificatemsg) {
       this.id = id;
       this.mstentity = mstentity;
       this.deliverytype = deliverytype;
       this.entityid = entityid;
       this.accountno = accountno;
       this.accountname = accountname;
       this.deladdresstype = deladdresstype;
       this.deladdress1 = deladdress1;
       this.deladdress2 = deladdress2;
       this.deladdress3 = deladdress3;
       this.deladdress4 = deladdress4;
       this.delzipcode = delzipcode;
       this.delcountry = delcountry;
       this.delbiccode = delbiccode;
       this.certificatemsg = certificatemsg;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="sinumber", column=@Column(name="SINUMBER", nullable=false, length=16) ) } )
    public IsMstsideliverydetailsId getId() {
        return this.id;
    }
    
    public void setId(IsMstsideliverydetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

    
    @Column(name="DELIVERYTYPE", length=4)
    public String getDeliverytype() {
        return this.deliverytype;
    }
    
    public void setDeliverytype(String deliverytype) {
        this.deliverytype = deliverytype;
    }

    
    @Column(name="ENTITYID", length=30)
    public String getEntityid() {
        return this.entityid;
    }
    
    public void setEntityid(String entityid) {
        this.entityid = entityid;
    }

    
    @Column(name="ACCOUNTNO", length=20)
    public String getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    
    @Column(name="ACCOUNTNAME", length=50)
    public String getAccountname() {
        return this.accountname;
    }
    
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }

    
    @Column(name="DELADDRESSTYPE", length=50)
    public String getDeladdresstype() {
        return this.deladdresstype;
    }
    
    public void setDeladdresstype(String deladdresstype) {
        this.deladdresstype = deladdresstype;
    }

    
    @Column(name="DELADDRESS1", length=100)
    public String getDeladdress1() {
        return this.deladdress1;
    }
    
    public void setDeladdress1(String deladdress1) {
        this.deladdress1 = deladdress1;
    }

    
    @Column(name="DELADDRESS2", length=100)
    public String getDeladdress2() {
        return this.deladdress2;
    }
    
    public void setDeladdress2(String deladdress2) {
        this.deladdress2 = deladdress2;
    }

    
    @Column(name="DELADDRESS3", length=100)
    public String getDeladdress3() {
        return this.deladdress3;
    }
    
    public void setDeladdress3(String deladdress3) {
        this.deladdress3 = deladdress3;
    }

    
    @Column(name="DELADDRESS4", length=100)
    public String getDeladdress4() {
        return this.deladdress4;
    }
    
    public void setDeladdress4(String deladdress4) {
        this.deladdress4 = deladdress4;
    }

    
    @Column(name="DELZIPCODE", length=100)
    public String getDelzipcode() {
        return this.delzipcode;
    }
    
    public void setDelzipcode(String delzipcode) {
        this.delzipcode = delzipcode;
    }

    
    @Column(name="DELCOUNTRY", length=100)
    public String getDelcountry() {
        return this.delcountry;
    }
    
    public void setDelcountry(String delcountry) {
        this.delcountry = delcountry;
    }

    
    @Column(name="DELBICCODE", length=100)
    public String getDelbiccode() {
        return this.delbiccode;
    }
    
    public void setDelbiccode(String delbiccode) {
        this.delbiccode = delbiccode;
    }

    
    @Column(name="CERTIFICATEMSG", length=1000)
    public String getCertificatemsg() {
        return this.certificatemsg;
    }
    
    public void setCertificatemsg(String certificatemsg) {
        this.certificatemsg = certificatemsg;
    }




}


