package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsMstproduct generated by hbm2java
 */
@Entity
@Table(name="IS_MSTPRODUCT"
    ,schema="FCDBADMIN_RK"
)
public class IsMstproduct  implements java.io.Serializable {


     private IsMstproductId id;
     private IsMstfund isMstfund;
     private Long numseq;
     private String namproduct;
     private String taxable;

    public IsMstproduct() {
    }

	
    public IsMstproduct(IsMstproductId id, IsMstfund isMstfund) {
        this.id = id;
        this.isMstfund = isMstfund;
    }
    public IsMstproduct(IsMstproductId id, IsMstfund isMstfund, Long numseq, String namproduct, String taxable) {
       this.id = id;
       this.isMstfund = isMstfund;
       this.numseq = numseq;
       this.namproduct = namproduct;
       this.taxable = taxable;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idproduct", column=@Column(name="IDPRODUCT", nullable=false, length=20) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ) } )
    public IsMstproductId getId() {
        return this.id;
    }
    
    public void setId(IsMstproductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDFUND", referencedColumnName="IDFUND", nullable=false, insertable=false, updatable=false) } )
    public IsMstfund getIsMstfund() {
        return this.isMstfund;
    }
    
    public void setIsMstfund(IsMstfund isMstfund) {
        this.isMstfund = isMstfund;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }

    
    @Column(name="NAMPRODUCT", length=50)
    public String getNamproduct() {
        return this.namproduct;
    }
    
    public void setNamproduct(String namproduct) {
        this.namproduct = namproduct;
    }

    
    @Column(name="TAXABLE", length=2)
    public String getTaxable() {
        return this.taxable;
    }
    
    public void setTaxable(String taxable) {
        this.taxable = taxable;
    }




}


