package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IsMstuseraccount generated by hbm2java
 */
@Entity
@Table(name="IS_MSTUSERACCOUNT"
    ,schema="FCDBADMIN_RK"
)
public class IsMstuseraccount  implements java.io.Serializable {


     private IsMstuseraccountId id;
     private String codcurr;
     private String codbranch;
     private Character coddefaultacct;
     private Character delflg;
     private String acctholdername;
     private Character debacctflg;
     private Long numseq;

    public IsMstuseraccount() {
    }

	
    public IsMstuseraccount(IsMstuseraccountId id) {
        this.id = id;
    }
    public IsMstuseraccount(IsMstuseraccountId id, String codcurr, String codbranch, Character coddefaultacct, Character delflg, String acctholdername, Character debacctflg, Long numseq) {
       this.id = id;
       this.codcurr = codcurr;
       this.codbranch = codbranch;
       this.coddefaultacct = coddefaultacct;
       this.delflg = delflg;
       this.acctholdername = acctholdername;
       this.debacctflg = debacctflg;
       this.numseq = numseq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false) ), 
        @AttributeOverride(name="iduh", column=@Column(name="IDUH", nullable=false, length=16) ), 
        @AttributeOverride(name="namacctid", column=@Column(name="NAMACCTID", nullable=false, length=20) ), 
        @AttributeOverride(name="codbank", column=@Column(name="CODBANK", nullable=false, length=25) ), 
        @AttributeOverride(name="codaccttype", column=@Column(name="CODACCTTYPE", nullable=false, length=25) ) } )
    public IsMstuseraccountId getId() {
        return this.id;
    }
    
    public void setId(IsMstuseraccountId id) {
        this.id = id;
    }

    
    @Column(name="CODCURR", length=3)
    public String getCodcurr() {
        return this.codcurr;
    }
    
    public void setCodcurr(String codcurr) {
        this.codcurr = codcurr;
    }

    
    @Column(name="CODBRANCH", length=25)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }

    
    @Column(name="CODDEFAULTACCT", length=1)
    public Character getCoddefaultacct() {
        return this.coddefaultacct;
    }
    
    public void setCoddefaultacct(Character coddefaultacct) {
        this.coddefaultacct = coddefaultacct;
    }

    
    @Column(name="DELFLG", length=1)
    public Character getDelflg() {
        return this.delflg;
    }
    
    public void setDelflg(Character delflg) {
        this.delflg = delflg;
    }

    
    @Column(name="ACCTHOLDERNAME", length=50)
    public String getAcctholdername() {
        return this.acctholdername;
    }
    
    public void setAcctholdername(String acctholdername) {
        this.acctholdername = acctholdername;
    }

    
    @Column(name="DEBACCTFLG", length=1)
    public Character getDebacctflg() {
        return this.debacctflg;
    }
    
    public void setDebacctflg(Character debacctflg) {
        this.debacctflg = debacctflg;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }




}


