package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LctbsDocumentsTmpId generated by hbm2java
 */
@Embeddable
public class LctbsDocumentsTmpId  implements java.io.Serializable {


     private String contractRefNo;
     private BigDecimal eventSeqNo;
     private String docCode;

    public LctbsDocumentsTmpId() {
    }

    public LctbsDocumentsTmpId(String contractRefNo, BigDecimal eventSeqNo, String docCode) {
       this.contractRefNo = contractRefNo;
       this.eventSeqNo = eventSeqNo;
       this.docCode = docCode;
    }
   


    @Column(name="CONTRACT_REF_NO", nullable=false, length=16)
    public String getContractRefNo() {
        return this.contractRefNo;
    }
    
    public void setContractRefNo(String contractRefNo) {
        this.contractRefNo = contractRefNo;
    }


    @Column(name="EVENT_SEQ_NO", nullable=false, precision=22, scale=0)
    public BigDecimal getEventSeqNo() {
        return this.eventSeqNo;
    }
    
    public void setEventSeqNo(BigDecimal eventSeqNo) {
        this.eventSeqNo = eventSeqNo;
    }


    @Column(name="DOC_CODE", nullable=false, length=12)
    public String getDocCode() {
        return this.docCode;
    }
    
    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LctbsDocumentsTmpId) ) return false;
		 LctbsDocumentsTmpId castOther = ( LctbsDocumentsTmpId ) other; 
         
		 return ( (this.getContractRefNo()==castOther.getContractRefNo()) || ( this.getContractRefNo()!=null && castOther.getContractRefNo()!=null && this.getContractRefNo().equals(castOther.getContractRefNo()) ) )
 && ( (this.getEventSeqNo()==castOther.getEventSeqNo()) || ( this.getEventSeqNo()!=null && castOther.getEventSeqNo()!=null && this.getEventSeqNo().equals(castOther.getEventSeqNo()) ) )
 && ( (this.getDocCode()==castOther.getDocCode()) || ( this.getDocCode()!=null && castOther.getDocCode()!=null && this.getDocCode().equals(castOther.getDocCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getContractRefNo() == null ? 0 : this.getContractRefNo().hashCode() );
         result = 37 * result + ( getEventSeqNo() == null ? 0 : this.getEventSeqNo().hashCode() );
         result = 37 * result + ( getDocCode() == null ? 0 : this.getDocCode().hashCode() );
         return result;
   }   


}


