package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Lkpcurrency generated by hbm2java
 */
@Entity
@Table(name="LKPCURRENCY"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"CODCURRENCY", "DTIME", "SLNO"}) 
)
public class Lkpcurrency  implements java.io.Serializable {


     private String codcurrency;
     private String txtcurrdesc;
     private Date dtime;
     private BigDecimal slno;
     private Mstprecision mstprecision;

    public Lkpcurrency() {
    }

	
    public Lkpcurrency(String codcurrency) {
        this.codcurrency = codcurrency;
    }
    public Lkpcurrency(String codcurrency, String txtcurrdesc, Date dtime, BigDecimal slno, Mstprecision mstprecision) {
       this.codcurrency = codcurrency;
       this.txtcurrdesc = txtcurrdesc;
       this.dtime = dtime;
       this.slno = slno;
       this.mstprecision = mstprecision;
    }
   
     @Id 

    
    @Column(name="CODCURRENCY", unique=true, nullable=false, length=3)
    public String getCodcurrency() {
        return this.codcurrency;
    }
    
    public void setCodcurrency(String codcurrency) {
        this.codcurrency = codcurrency;
    }

    
    @Column(name="TXTCURRDESC", length=105)
    public String getTxtcurrdesc() {
        return this.txtcurrdesc;
    }
    
    public void setTxtcurrdesc(String txtcurrdesc) {
        this.txtcurrdesc = txtcurrdesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="lkpcurrency")
    public Mstprecision getMstprecision() {
        return this.mstprecision;
    }
    
    public void setMstprecision(Mstprecision mstprecision) {
        this.mstprecision = mstprecision;
    }




}


