package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MobileData generated by hbm2java
 */
@Entity
@Table(name="MOBILE_DATA"
    ,schema="FCDBADMIN_RK"
)
public class MobileData  implements java.io.Serializable {


     private BigDecimal id;
     private String operator;
     private String packages;

    public MobileData() {
    }

    public MobileData(BigDecimal id, String operator, String packages) {
       this.id = id;
       this.operator = operator;
       this.packages = packages;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="OPERATOR", nullable=false, length=30)
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }

    
    @Column(name="PACKAGES", nullable=false, length=30)
    public String getPackages() {
        return this.packages;
    }
    
    public void setPackages(String packages) {
        this.packages = packages;
    }




}


