package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mobileenableruseraccesscontrol generated by hbm2java
 */
@Entity
@Table(name="MOBILEENABLERUSERACCESSCONTROL"
    ,schema="FCDBADMIN_RK"
)
public class Mobileenableruseraccesscontrol  implements java.io.Serializable {


     private MobileenableruseraccesscontrolId id;
     private String isenabled;

    public Mobileenableruseraccesscontrol() {
    }

	
    public Mobileenableruseraccesscontrol(MobileenableruseraccesscontrolId id) {
        this.id = id;
    }
    public Mobileenableruseraccesscontrol(MobileenableruseraccesscontrolId id, String isenabled) {
       this.id = id;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=3) ), 
        @AttributeOverride(name="idchanneluser", column=@Column(name="IDCHANNELUSER", nullable=false, length=20) ) } )
    public MobileenableruseraccesscontrolId getId() {
        return this.id;
    }
    
    public void setId(MobileenableruseraccesscontrolId id) {
        this.id = id;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }




}


