package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModpropMaint generated by hbm2java
 */
@Entity
@Table(name="MODPROP_MAINT"
    ,schema="FCDBADMIN_RK"
)
public class ModpropMaint  implements java.io.Serializable {


     private String propId;
     private ModuleMaint moduleMaint;
     private String propDesc;
     private String propQuery;
     private String isenable;
     private String defaultValue;
     private Long sequenceNo;

    public ModpropMaint() {
    }

	
    public ModpropMaint(String propId) {
        this.propId = propId;
    }
    public ModpropMaint(String propId, ModuleMaint moduleMaint, String propDesc, String propQuery, String isenable, String defaultValue, Long sequenceNo) {
       this.propId = propId;
       this.moduleMaint = moduleMaint;
       this.propDesc = propDesc;
       this.propQuery = propQuery;
       this.isenable = isenable;
       this.defaultValue = defaultValue;
       this.sequenceNo = sequenceNo;
    }
   
     @Id 

    
    @Column(name="PROP_ID", unique=true, nullable=false, length=5)
    public String getPropId() {
        return this.propId;
    }
    
    public void setPropId(String propId) {
        this.propId = propId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODULE_ID")
    public ModuleMaint getModuleMaint() {
        return this.moduleMaint;
    }
    
    public void setModuleMaint(ModuleMaint moduleMaint) {
        this.moduleMaint = moduleMaint;
    }

    
    @Column(name="PROP_DESC", length=200)
    public String getPropDesc() {
        return this.propDesc;
    }
    
    public void setPropDesc(String propDesc) {
        this.propDesc = propDesc;
    }

    
    @Column(name="PROP_QUERY")
    public String getPropQuery() {
        return this.propQuery;
    }
    
    public void setPropQuery(String propQuery) {
        this.propQuery = propQuery;
    }

    
    @Column(name="ISENABLE", length=1)
    public String getIsenable() {
        return this.isenable;
    }
    
    public void setIsenable(String isenable) {
        this.isenable = isenable;
    }

    
    @Column(name="DEFAULT_VALUE", length=4000)
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    
    @Column(name="SEQUENCE_NO", precision=11, scale=0)
    public Long getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Long sequenceNo) {
        this.sequenceNo = sequenceNo;
    }




}


