package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstalertchannels generated by hbm2java
 */
@Entity
@Table(name="MSTALERTCHANNELS"
    ,schema="FCDBADMIN_RK"
)
public class Mstalertchannels  implements java.io.Serializable {


     private MstalertchannelsId id;
     private String channelgenerator;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private Date expirytime;
     private Date notifyStartTime;
     private String notifyMaxNbrRetry;
     private Long notifyRetryInterval;
     private Character isenabled;
     private String propertiesstr;
     private String idactions;
     private Character showaction;
     private String alertresource;

    public Mstalertchannels() {
    }

	
    public Mstalertchannels(MstalertchannelsId id) {
        this.id = id;
    }
    public Mstalertchannels(MstalertchannelsId id, String channelgenerator, String token1, String token2, String token3, String token4, String token5, Date expirytime, Date notifyStartTime, String notifyMaxNbrRetry, Long notifyRetryInterval, Character isenabled, String propertiesstr, String idactions, Character showaction, String alertresource) {
       this.id = id;
       this.channelgenerator = channelgenerator;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.expirytime = expirytime;
       this.notifyStartTime = notifyStartTime;
       this.notifyMaxNbrRetry = notifyMaxNbrRetry;
       this.notifyRetryInterval = notifyRetryInterval;
       this.isenabled = isenabled;
       this.propertiesstr = propertiesstr;
       this.idactions = idactions;
       this.showaction = showaction;
       this.alertresource = alertresource;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idalert", column=@Column(name="IDALERT", nullable=false, length=50) ), 
        @AttributeOverride(name="idnotifier", column=@Column(name="IDNOTIFIER", nullable=false, length=50) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ) } )
    public MstalertchannelsId getId() {
        return this.id;
    }
    
    public void setId(MstalertchannelsId id) {
        this.id = id;
    }

    
    @Column(name="CHANNELGENERATOR")
    public String getChannelgenerator() {
        return this.channelgenerator;
    }
    
    public void setChannelgenerator(String channelgenerator) {
        this.channelgenerator = channelgenerator;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3")
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4")
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5")
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRYTIME", length=7)
    public Date getExpirytime() {
        return this.expirytime;
    }
    
    public void setExpirytime(Date expirytime) {
        this.expirytime = expirytime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NOTIFY_START_TIME", length=7)
    public Date getNotifyStartTime() {
        return this.notifyStartTime;
    }
    
    public void setNotifyStartTime(Date notifyStartTime) {
        this.notifyStartTime = notifyStartTime;
    }

    
    @Column(name="NOTIFY_MAX_NBR_RETRY", length=2)
    public String getNotifyMaxNbrRetry() {
        return this.notifyMaxNbrRetry;
    }
    
    public void setNotifyMaxNbrRetry(String notifyMaxNbrRetry) {
        this.notifyMaxNbrRetry = notifyMaxNbrRetry;
    }

    
    @Column(name="NOTIFY_RETRY_INTERVAL", precision=15, scale=0)
    public Long getNotifyRetryInterval() {
        return this.notifyRetryInterval;
    }
    
    public void setNotifyRetryInterval(Long notifyRetryInterval) {
        this.notifyRetryInterval = notifyRetryInterval;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="PROPERTIESSTR")
    public String getPropertiesstr() {
        return this.propertiesstr;
    }
    
    public void setPropertiesstr(String propertiesstr) {
        this.propertiesstr = propertiesstr;
    }

    
    @Column(name="IDACTIONS", length=200)
    public String getIdactions() {
        return this.idactions;
    }
    
    public void setIdactions(String idactions) {
        this.idactions = idactions;
    }

    
    @Column(name="SHOWACTION", length=1)
    public Character getShowaction() {
        return this.showaction;
    }
    
    public void setShowaction(Character showaction) {
        this.showaction = showaction;
    }

    
    @Column(name="ALERTRESOURCE", length=50)
    public String getAlertresource() {
        return this.alertresource;
    }
    
    public void setAlertresource(String alertresource) {
        this.alertresource = alertresource;
    }




}


