package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mstats generated by hbm2java
 */
@Entity
@Table(name="MSTATS"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="IDREQUEST") 
)
public class Mstats  implements java.io.Serializable {


     private MstatsId id;
     private String typprocessor;
     private String nambean;
     private String namjndi;
     private String namxsl;
     private String transactiontype;
     private String linecomment;
     private String idrequest;
     private String reqTemplateId;
     private String respTemplateId;
     private String namContentGen;
     private String token1;
     private String token2;
     private String token3;
     private String sstemplate;
     private Character requireslogin;
     private String namexchanger;
     private Character auditrequired;
     private String audithandler;
     private String audittemplateid;
     private Character checksectoken;
     private String reqpreproc;
     private Integer txnmode;

    public Mstats() {
    }

	
    public Mstats(MstatsId id) {
        this.id = id;
    }
    public Mstats(MstatsId id, String typprocessor, String nambean, String namjndi, String namxsl, String transactiontype, String linecomment, String idrequest, String reqTemplateId, String respTemplateId, String namContentGen, String token1, String token2, String token3, String sstemplate, Character requireslogin, String namexchanger, Character auditrequired, String audithandler, String audittemplateid, Character checksectoken, String reqpreproc, Integer txnmode) {
       this.id = id;
       this.typprocessor = typprocessor;
       this.nambean = nambean;
       this.namjndi = namjndi;
       this.namxsl = namxsl;
       this.transactiontype = transactiontype;
       this.linecomment = linecomment;
       this.idrequest = idrequest;
       this.reqTemplateId = reqTemplateId;
       this.respTemplateId = respTemplateId;
       this.namContentGen = namContentGen;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.sstemplate = sstemplate;
       this.requireslogin = requireslogin;
       this.namexchanger = namexchanger;
       this.auditrequired = auditrequired;
       this.audithandler = audithandler;
       this.audittemplateid = audittemplateid;
       this.checksectoken = checksectoken;
       this.reqpreproc = reqpreproc;
       this.txnmode = txnmode;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="numsequence", column=@Column(name="NUMSEQUENCE", nullable=false, length=2) ) } )
    public MstatsId getId() {
        return this.id;
    }
    
    public void setId(MstatsId id) {
        this.id = id;
    }

    
    @Column(name="TYPPROCESSOR", length=5)
    public String getTypprocessor() {
        return this.typprocessor;
    }
    
    public void setTypprocessor(String typprocessor) {
        this.typprocessor = typprocessor;
    }

    
    @Column(name="NAMBEAN", length=100)
    public String getNambean() {
        return this.nambean;
    }
    
    public void setNambean(String nambean) {
        this.nambean = nambean;
    }

    
    @Column(name="NAMJNDI", length=50)
    public String getNamjndi() {
        return this.namjndi;
    }
    
    public void setNamjndi(String namjndi) {
        this.namjndi = namjndi;
    }

    
    @Column(name="NAMXSL", length=100)
    public String getNamxsl() {
        return this.namxsl;
    }
    
    public void setNamxsl(String namxsl) {
        this.namxsl = namxsl;
    }

    
    @Column(name="TRANSACTIONTYPE", length=5)
    public String getTransactiontype() {
        return this.transactiontype;
    }
    
    public void setTransactiontype(String transactiontype) {
        this.transactiontype = transactiontype;
    }

    
    @Column(name="LINECOMMENT", length=80)
    public String getLinecomment() {
        return this.linecomment;
    }
    
    public void setLinecomment(String linecomment) {
        this.linecomment = linecomment;
    }

    
    @Column(name="IDREQUEST", unique=true, length=10)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="REQ_TEMPLATE_ID", length=10)
    public String getReqTemplateId() {
        return this.reqTemplateId;
    }
    
    public void setReqTemplateId(String reqTemplateId) {
        this.reqTemplateId = reqTemplateId;
    }

    
    @Column(name="RESP_TEMPLATE_ID", length=10)
    public String getRespTemplateId() {
        return this.respTemplateId;
    }
    
    public void setRespTemplateId(String respTemplateId) {
        this.respTemplateId = respTemplateId;
    }

    
    @Column(name="NAM_CONTENT_GEN", length=100)
    public String getNamContentGen() {
        return this.namContentGen;
    }
    
    public void setNamContentGen(String namContentGen) {
        this.namContentGen = namContentGen;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3")
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="SSTEMPLATE", length=10)
    public String getSstemplate() {
        return this.sstemplate;
    }
    
    public void setSstemplate(String sstemplate) {
        this.sstemplate = sstemplate;
    }

    
    @Column(name="REQUIRESLOGIN", length=1)
    public Character getRequireslogin() {
        return this.requireslogin;
    }
    
    public void setRequireslogin(Character requireslogin) {
        this.requireslogin = requireslogin;
    }

    
    @Column(name="NAMEXCHANGER", length=100)
    public String getNamexchanger() {
        return this.namexchanger;
    }
    
    public void setNamexchanger(String namexchanger) {
        this.namexchanger = namexchanger;
    }

    
    @Column(name="AUDITREQUIRED", length=1)
    public Character getAuditrequired() {
        return this.auditrequired;
    }
    
    public void setAuditrequired(Character auditrequired) {
        this.auditrequired = auditrequired;
    }

    
    @Column(name="AUDITHANDLER", length=100)
    public String getAudithandler() {
        return this.audithandler;
    }
    
    public void setAudithandler(String audithandler) {
        this.audithandler = audithandler;
    }

    
    @Column(name="AUDITTEMPLATEID", length=10)
    public String getAudittemplateid() {
        return this.audittemplateid;
    }
    
    public void setAudittemplateid(String audittemplateid) {
        this.audittemplateid = audittemplateid;
    }

    
    @Column(name="CHECKSECTOKEN", length=1)
    public Character getChecksectoken() {
        return this.checksectoken;
    }
    
    public void setChecksectoken(Character checksectoken) {
        this.checksectoken = checksectoken;
    }

    
    @Column(name="REQPREPROC", length=100)
    public String getReqpreproc() {
        return this.reqpreproc;
    }
    
    public void setReqpreproc(String reqpreproc) {
        this.reqpreproc = reqpreproc;
    }

    
    @Column(name="TXNMODE", precision=5, scale=0)
    public Integer getTxnmode() {
        return this.txnmode;
    }
    
    public void setTxnmode(Integer txnmode) {
        this.txnmode = txnmode;
    }




}


