package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstalertnotifier generated by hbm2java
 */
@Entity
@Table(name="MSTALERTNOTIFIER"
    ,schema="FCDBADMIN_RK"
)
public class Mstalertnotifier  implements java.io.Serializable {


     private String idnotifier;
     private String notifierclass;
     private Byte notifierinstances;
     private String propertiesstr;
     private String description;
     private Set<Mstalertprofilechannel> mstalertprofilechannels = new HashSet<Mstalertprofilechannel>(0);

    public Mstalertnotifier() {
    }

	
    public Mstalertnotifier(String idnotifier) {
        this.idnotifier = idnotifier;
    }
    public Mstalertnotifier(String idnotifier, String notifierclass, Byte notifierinstances, String propertiesstr, String description, Set<Mstalertprofilechannel> mstalertprofilechannels) {
       this.idnotifier = idnotifier;
       this.notifierclass = notifierclass;
       this.notifierinstances = notifierinstances;
       this.propertiesstr = propertiesstr;
       this.description = description;
       this.mstalertprofilechannels = mstalertprofilechannels;
    }
   
     @Id 

    
    @Column(name="IDNOTIFIER", unique=true, nullable=false, length=50)
    public String getIdnotifier() {
        return this.idnotifier;
    }
    
    public void setIdnotifier(String idnotifier) {
        this.idnotifier = idnotifier;
    }

    
    @Column(name="NOTIFIERCLASS")
    public String getNotifierclass() {
        return this.notifierclass;
    }
    
    public void setNotifierclass(String notifierclass) {
        this.notifierclass = notifierclass;
    }

    
    @Column(name="NOTIFIERINSTANCES", precision=2, scale=0)
    public Byte getNotifierinstances() {
        return this.notifierinstances;
    }
    
    public void setNotifierinstances(Byte notifierinstances) {
        this.notifierinstances = notifierinstances;
    }

    
    @Column(name="PROPERTIESSTR", length=2000)
    public String getPropertiesstr() {
        return this.propertiesstr;
    }
    
    public void setPropertiesstr(String propertiesstr) {
        this.propertiesstr = propertiesstr;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstalertnotifier")
    public Set<Mstalertprofilechannel> getMstalertprofilechannels() {
        return this.mstalertprofilechannels;
    }
    
    public void setMstalertprofilechannels(Set<Mstalertprofilechannel> mstalertprofilechannels) {
        this.mstalertprofilechannels = mstalertprofilechannels;
    }




}


