package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstbillerhistoryId generated by hbm2java
 */
@Embeddable
public class MstbillerhistoryId  implements java.io.Serializable {


     private String iduser;
     private String idcust;
     private String idbiller;
     private String acctno;

    public MstbillerhistoryId() {
    }

    public MstbillerhistoryId(String iduser, String idcust, String idbiller, String acctno) {
       this.iduser = iduser;
       this.idcust = idcust;
       this.idbiller = idbiller;
       this.acctno = acctno;
    }
   


    @Column(name="IDUSER", nullable=false, length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }


    @Column(name="IDCUST", nullable=false, length=16)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }


    @Column(name="IDBILLER", nullable=false, length=16)
    public String getIdbiller() {
        return this.idbiller;
    }
    
    public void setIdbiller(String idbiller) {
        this.idbiller = idbiller;
    }


    @Column(name="ACCTNO", nullable=false, length=20)
    public String getAcctno() {
        return this.acctno;
    }
    
    public void setAcctno(String acctno) {
        this.acctno = acctno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbillerhistoryId) ) return false;
		 MstbillerhistoryId castOther = ( MstbillerhistoryId ) other; 
         
		 return ( (this.getIduser()==castOther.getIduser()) || ( this.getIduser()!=null && castOther.getIduser()!=null && this.getIduser().equals(castOther.getIduser()) ) )
 && ( (this.getIdcust()==castOther.getIdcust()) || ( this.getIdcust()!=null && castOther.getIdcust()!=null && this.getIdcust().equals(castOther.getIdcust()) ) )
 && ( (this.getIdbiller()==castOther.getIdbiller()) || ( this.getIdbiller()!=null && castOther.getIdbiller()!=null && this.getIdbiller().equals(castOther.getIdbiller()) ) )
 && ( (this.getAcctno()==castOther.getAcctno()) || ( this.getAcctno()!=null && castOther.getAcctno()!=null && this.getAcctno().equals(castOther.getAcctno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIduser() == null ? 0 : this.getIduser().hashCode() );
         result = 37 * result + ( getIdcust() == null ? 0 : this.getIdcust().hashCode() );
         result = 37 * result + ( getIdbiller() == null ? 0 : this.getIdbiller().hashCode() );
         result = 37 * result + ( getAcctno() == null ? 0 : this.getAcctno().hashCode() );
         return result;
   }   


}


