package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstcontactpurpose generated by hbm2java
 */
@Entity
@Table(name="MSTCONTACTPURPOSE"
    ,schema="FCDBADMIN_RK"
)
public class Mstcontactpurpose  implements java.io.Serializable {


     private MstcontactpurposeId id;
     private Mstcontacttypes mstcontacttypes;
     private String description;
     private Character isenabled;

    public Mstcontactpurpose() {
    }

	
    public Mstcontactpurpose(MstcontactpurposeId id, Mstcontacttypes mstcontacttypes) {
        this.id = id;
        this.mstcontacttypes = mstcontacttypes;
    }
    public Mstcontactpurpose(MstcontactpurposeId id, Mstcontacttypes mstcontacttypes, String description, Character isenabled) {
       this.id = id;
       this.mstcontacttypes = mstcontacttypes;
       this.description = description;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idpurpose", column=@Column(name="IDPURPOSE", nullable=false, length=5) ), 
        @AttributeOverride(name="idcontact", column=@Column(name="IDCONTACT", nullable=false, length=5) ) } )
    public MstcontactpurposeId getId() {
        return this.id;
    }
    
    public void setId(MstcontactpurposeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTACT", nullable=false, insertable=false, updatable=false)
    public Mstcontacttypes getMstcontacttypes() {
        return this.mstcontacttypes;
    }
    
    public void setMstcontacttypes(Mstcontacttypes mstcontacttypes) {
        this.mstcontacttypes = mstcontacttypes;
    }

    
    @Column(name="DESCRIPTION", length=40)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }




}


