package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstconnectmaster generated by hbm2java
 */
@Entity
@Table(name="MSTCONNECTMASTER"
    ,schema="FCDBADMIN_RK"
)
public class Mstconnectmaster  implements java.io.Serializable {


     private MstconnectmasterId id;
     private String description;
     private String nammaster;
     private String namworker;
     private BigDecimal status;
     private BigDecimal maxworkers;
     private String propertiesstr;
     private Long frequency;
     private Date expirationdate;
     private Long activefrequency;
     private Long inactivefrequency;

    public Mstconnectmaster() {
    }

	
    public Mstconnectmaster(MstconnectmasterId id) {
        this.id = id;
    }
    public Mstconnectmaster(MstconnectmasterId id, String description, String nammaster, String namworker, BigDecimal status, BigDecimal maxworkers, String propertiesstr, Long frequency, Date expirationdate, Long activefrequency, Long inactivefrequency) {
       this.id = id;
       this.description = description;
       this.nammaster = nammaster;
       this.namworker = namworker;
       this.status = status;
       this.maxworkers = maxworkers;
       this.propertiesstr = propertiesstr;
       this.frequency = frequency;
       this.expirationdate = expirationdate;
       this.activefrequency = activefrequency;
       this.inactivefrequency = inactivefrequency;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="daemonname", column=@Column(name="DAEMONNAME", nullable=false, length=30) ), 
        @AttributeOverride(name="nbrsequence", column=@Column(name="NBRSEQUENCE", nullable=false, precision=38, scale=0) ) } )
    public MstconnectmasterId getId() {
        return this.id;
    }
    
    public void setId(MstconnectmasterId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="NAMMASTER")
    public String getNammaster() {
        return this.nammaster;
    }
    
    public void setNammaster(String nammaster) {
        this.nammaster = nammaster;
    }

    
    @Column(name="NAMWORKER")
    public String getNamworker() {
        return this.namworker;
    }
    
    public void setNamworker(String namworker) {
        this.namworker = namworker;
    }

    
    @Column(name="STATUS", precision=38, scale=0)
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    
    @Column(name="MAXWORKERS", precision=38, scale=0)
    public BigDecimal getMaxworkers() {
        return this.maxworkers;
    }
    
    public void setMaxworkers(BigDecimal maxworkers) {
        this.maxworkers = maxworkers;
    }

    
    @Column(name="PROPERTIESSTR", length=2000)
    public String getPropertiesstr() {
        return this.propertiesstr;
    }
    
    public void setPropertiesstr(String propertiesstr) {
        this.propertiesstr = propertiesstr;
    }

    
    @Column(name="FREQUENCY", precision=18, scale=0)
    public Long getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Long frequency) {
        this.frequency = frequency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRATIONDATE", length=7)
    public Date getExpirationdate() {
        return this.expirationdate;
    }
    
    public void setExpirationdate(Date expirationdate) {
        this.expirationdate = expirationdate;
    }

    
    @Column(name="ACTIVEFREQUENCY", precision=18, scale=0)
    public Long getActivefrequency() {
        return this.activefrequency;
    }
    
    public void setActivefrequency(Long activefrequency) {
        this.activefrequency = activefrequency;
    }

    
    @Column(name="INACTIVEFREQUENCY", precision=18, scale=0)
    public Long getInactivefrequency() {
        return this.inactivefrequency;
    }
    
    public void setInactivefrequency(Long inactivefrequency) {
        this.inactivefrequency = inactivefrequency;
    }




}


