package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstcatrule generated by hbm2java
 */
@Entity
@Table(name="MSTCATRULE"
    ,schema="FCDBADMIN_RK"
)
public class Mstcatrule  implements java.io.Serializable {


     private MstcatruleId id;
     private String idacct;
     private String idcust;
     private String codtxn;
     private BigDecimal amt;
     private Character status;
     private Date datmodified;
     private Date datcreated;
     private String iduser;
     private Byte nbrauth;
     private String codbranch;
     private String fcatref;
     private BigDecimal endamt;
     private String txnmakerid;
     private String txnidcust;
     private String idEntity;
     private String ruleidcurr;
     private Character isautoauth;
     private String usertype;
     private String txnidentity;

    public Mstcatrule() {
    }

	
    public Mstcatrule(MstcatruleId id) {
        this.id = id;
    }
    public Mstcatrule(MstcatruleId id, String idacct, String idcust, String codtxn, BigDecimal amt, Character status, Date datmodified, Date datcreated, String iduser, Byte nbrauth, String codbranch, String fcatref, BigDecimal endamt, String txnmakerid, String txnidcust, String idEntity, String ruleidcurr, Character isautoauth, String usertype, String txnidentity) {
       this.id = id;
       this.idacct = idacct;
       this.idcust = idcust;
       this.codtxn = codtxn;
       this.amt = amt;
       this.status = status;
       this.datmodified = datmodified;
       this.datcreated = datcreated;
       this.iduser = iduser;
       this.nbrauth = nbrauth;
       this.codbranch = codbranch;
       this.fcatref = fcatref;
       this.endamt = endamt;
       this.txnmakerid = txnmakerid;
       this.txnidcust = txnidcust;
       this.idEntity = idEntity;
       this.ruleidcurr = ruleidcurr;
       this.isautoauth = isautoauth;
       this.usertype = usertype;
       this.txnidentity = txnidentity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcustgrp", column=@Column(name="IDCUSTGRP", nullable=false, length=20) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ) } )
    public MstcatruleId getId() {
        return this.id;
    }
    
    public void setId(MstcatruleId id) {
        this.id = id;
    }

    
    @Column(name="IDACCT", length=20)
    public String getIdacct() {
        return this.idacct;
    }
    
    public void setIdacct(String idacct) {
        this.idacct = idacct;
    }

    
    @Column(name="IDCUST", length=20)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }

    
    @Column(name="CODTXN", length=4)
    public String getCodtxn() {
        return this.codtxn;
    }
    
    public void setCodtxn(String codtxn) {
        this.codtxn = codtxn;
    }

    
    @Column(name="AMT", scale=4)
    public BigDecimal getAmt() {
        return this.amt;
    }
    
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMODIFIED", length=7)
    public Date getDatmodified() {
        return this.datmodified;
    }
    
    public void setDatmodified(Date datmodified) {
        this.datmodified = datmodified;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="NBRAUTH", precision=2, scale=0)
    public Byte getNbrauth() {
        return this.nbrauth;
    }
    
    public void setNbrauth(Byte nbrauth) {
        this.nbrauth = nbrauth;
    }

    
    @Column(name="CODBRANCH", length=20)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }

    
    @Column(name="FCATREF", length=15)
    public String getFcatref() {
        return this.fcatref;
    }
    
    public void setFcatref(String fcatref) {
        this.fcatref = fcatref;
    }

    
    @Column(name="ENDAMT", scale=4)
    public BigDecimal getEndamt() {
        return this.endamt;
    }
    
    public void setEndamt(BigDecimal endamt) {
        this.endamt = endamt;
    }

    
    @Column(name="TXNMAKERID", length=20)
    public String getTxnmakerid() {
        return this.txnmakerid;
    }
    
    public void setTxnmakerid(String txnmakerid) {
        this.txnmakerid = txnmakerid;
    }

    
    @Column(name="TXNIDCUST", length=30)
    public String getTxnidcust() {
        return this.txnidcust;
    }
    
    public void setTxnidcust(String txnidcust) {
        this.txnidcust = txnidcust;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="RULEIDCURR", length=3)
    public String getRuleidcurr() {
        return this.ruleidcurr;
    }
    
    public void setRuleidcurr(String ruleidcurr) {
        this.ruleidcurr = ruleidcurr;
    }

    
    @Column(name="ISAUTOAUTH", length=1)
    public Character getIsautoauth() {
        return this.isautoauth;
    }
    
    public void setIsautoauth(Character isautoauth) {
        this.isautoauth = isautoauth;
    }

    
    @Column(name="USERTYPE", length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    
    @Column(name="TXNIDENTITY", length=5)
    public String getTxnidentity() {
        return this.txnidentity;
    }
    
    public void setTxnidentity(String txnidentity) {
        this.txnidentity = txnidentity;
    }




}


