package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstentityusertypelang generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYUSERTYPELANG"
    ,schema="FCDBADMIN_RK"
)
public class Mstentityusertypelang  implements java.io.Serializable {


     private MstentityusertypelangId id;
     private Mstentity mstentity;
     private Mstusertypes mstusertypes;
     private Mstlang mstlang;

    public Mstentityusertypelang() {
    }

    public Mstentityusertypelang(MstentityusertypelangId id, Mstentity mstentity, Mstusertypes mstusertypes, Mstlang mstlang) {
       this.id = id;
       this.mstentity = mstentity;
       this.mstusertypes = mstusertypes;
       this.mstlang = mstlang;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idlang", column=@Column(name="IDLANG", nullable=false, length=3) ) } )
    public MstentityusertypelangId getId() {
        return this.id;
    }
    
    public void setId(MstentityusertypelangId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPEUSER", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDLANG", nullable=false, insertable=false, updatable=false)
    public Mstlang getMstlang() {
        return this.mstlang;
    }
    
    public void setMstlang(Mstlang mstlang) {
        this.mstlang = mstlang;
    }




}


