package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstentityuserchannelId generated by hbm2java
 */
@Embeddable
public class MstentityuserchannelId  implements java.io.Serializable {


     private String idEntity;
     private String typeuser;
     private String idchannel;

    public MstentityuserchannelId() {
    }

    public MstentityuserchannelId(String idEntity, String typeuser, String idchannel) {
       this.idEntity = idEntity;
       this.typeuser = typeuser;
       this.idchannel = idchannel;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="TYPEUSER", nullable=false, length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }


    @Column(name="IDCHANNEL", nullable=false, length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstentityuserchannelId) ) return false;
		 MstentityuserchannelId castOther = ( MstentityuserchannelId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getTypeuser()==castOther.getTypeuser()) || ( this.getTypeuser()!=null && castOther.getTypeuser()!=null && this.getTypeuser().equals(castOther.getTypeuser()) ) )
 && ( (this.getIdchannel()==castOther.getIdchannel()) || ( this.getIdchannel()!=null && castOther.getIdchannel()!=null && this.getIdchannel().equals(castOther.getIdchannel()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getTypeuser() == null ? 0 : this.getTypeuser().hashCode() );
         result = 37 * result + ( getIdchannel() == null ? 0 : this.getIdchannel().hashCode() );
         return result;
   }   


}


