package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstentityuserchannelgrpId generated by hbm2java
 */
@Embeddable
public class MstentityuserchannelgrpId  implements java.io.Serializable {


     private String idEntity;
     private String typeuser;
     private String idgroup;

    public MstentityuserchannelgrpId() {
    }

    public MstentityuserchannelgrpId(String idEntity, String typeuser, String idgroup) {
       this.idEntity = idEntity;
       this.typeuser = typeuser;
       this.idgroup = idgroup;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="TYPEUSER", nullable=false, length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }


    @Column(name="IDGROUP", nullable=false, length=5)
    public String getIdgroup() {
        return this.idgroup;
    }
    
    public void setIdgroup(String idgroup) {
        this.idgroup = idgroup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstentityuserchannelgrpId) ) return false;
		 MstentityuserchannelgrpId castOther = ( MstentityuserchannelgrpId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getTypeuser()==castOther.getTypeuser()) || ( this.getTypeuser()!=null && castOther.getTypeuser()!=null && this.getTypeuser().equals(castOther.getTypeuser()) ) )
 && ( (this.getIdgroup()==castOther.getIdgroup()) || ( this.getIdgroup()!=null && castOther.getIdgroup()!=null && this.getIdgroup().equals(castOther.getIdgroup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getTypeuser() == null ? 0 : this.getTypeuser().hashCode() );
         result = 37 * result + ( getIdgroup() == null ? 0 : this.getIdgroup().hashCode() );
         return result;
   }   


}


