package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstentity generated by hbm2java
 */
@Entity
@Table(name="MSTENTITY"
    ,schema="FCDBADMIN_RK"
)
public class Mstentity  implements java.io.Serializable {


     private String idEntity;
     private Mstentitytypes mstentitytypes;
     private String description;
     private String idParent;
     private BigDecimal idsort;
     private Set<IsLkpcurr> isLkpcurrs = new HashSet<IsLkpcurr>(0);
     private Set<IsMstuserportfolio> isMstuserportfolios = new HashSet<IsMstuserportfolio>(0);
     private Set<IsMstsidetails> isMstsidetailses = new HashSet<IsMstsidetails>(0);
     private Set<IsLkpload> isLkploads = new HashSet<IsLkpload>(0);
     private Set<Mstentityusertypelang> mstentityusertypelangs = new HashSet<Mstentityusertypelang>(0);
     private Set<IsDeliverydetails> isDeliverydetailses = new HashSet<IsDeliverydetails>(0);
     private Set<OrigProdcateg> origProdcategs = new HashSet<OrigProdcateg>(0);
     private Set<FcatTCommunications> fcatTCommunicationsesForReceiverIdEntity = new HashSet<FcatTCommunications>(0);
     private Set<Mstaccttypes> mstaccttypeses = new HashSet<Mstaccttypes>(0);
     private Set<IsLkpacctcode> isLkpacctcodes = new HashSet<IsLkpacctcode>(0);
     private Set<IsTxnactivitydetails> isTxnactivitydetailses = new HashSet<IsTxnactivitydetails>(0);
     private Set<IsMstsideliverydetails> isMstsideliverydetailses = new HashSet<IsMstsideliverydetails>(0);
     private Set<IsLkpscrip> isLkpscrips = new HashSet<IsLkpscrip>(0);
     private Set<Mailmessage> mailmessages = new HashSet<Mailmessage>(0);
     private Set<Mststatusgroupmap> mststatusgroupmaps = new HashSet<Mststatusgroupmap>(0);
     private Set<IsLkptxn> isLkptxns = new HashSet<IsLkptxn>(0);
     private Set<IsMstfund> isMstfunds = new HashSet<IsMstfund>(0);
     private Set<Mstchequestyles> mstchequestyleses = new HashSet<Mstchequestyles>(0);
     private Set<Mstsourcebenelinkage> mstsourcebenelinkages = new HashSet<Mstsourcebenelinkage>(0);
     private Set<Mstmailsubject> mstmailsubjects = new HashSet<Mstmailsubject>(0);
     private Set<Peerbeneacctdet> peerbeneacctdets = new HashSet<Peerbeneacctdet>(0);
     private Set<Mstsecurityquestions> mstsecurityquestionses = new HashSet<Mstsecurityquestions>(0);
     private Set<IsLimitorderdetails> isLimitorderdetailses = new HashSet<IsLimitorderdetails>(0);
     private Set<Mstentityusertypes> mstentityusertypeses = new HashSet<Mstentityusertypes>(0);
     private Set<Msthostinterface> msthostinterfaces = new HashSet<Msthostinterface>(0);
     private Set<IsLkppricing> isLkppricings = new HashSet<IsLkppricing>(0);
     private Set<FcatTCommunications> fcatTCommunicationsesForSenderIdEntity = new HashSet<FcatTCommunications>(0);
     private Set<Mstrole> mstroles = new HashSet<Mstrole>(0);
     private Set<Mobileenablerreturncodemap> mobileenablerreturncodemaps = new HashSet<Mobileenablerreturncodemap>(0);
     private Set<IsOrderstatusinquirydetails> isOrderstatusinquirydetailses = new HashSet<IsOrderstatusinquirydetails>(0);

    public Mstentity() {
    }

	
    public Mstentity(String idEntity) {
        this.idEntity = idEntity;
    }
    public Mstentity(String idEntity, Mstentitytypes mstentitytypes, String description, String idParent, BigDecimal idsort, Set<IsLkpcurr> isLkpcurrs, Set<IsMstuserportfolio> isMstuserportfolios, Set<IsMstsidetails> isMstsidetailses, Set<IsLkpload> isLkploads, Set<Mstentityusertypelang> mstentityusertypelangs, Set<IsDeliverydetails> isDeliverydetailses, Set<OrigProdcateg> origProdcategs, Set<FcatTCommunications> fcatTCommunicationsesForReceiverIdEntity, Set<Mstaccttypes> mstaccttypeses, Set<IsLkpacctcode> isLkpacctcodes, Set<IsTxnactivitydetails> isTxnactivitydetailses, Set<IsMstsideliverydetails> isMstsideliverydetailses, Set<IsLkpscrip> isLkpscrips, Set<Mailmessage> mailmessages, Set<Mststatusgroupmap> mststatusgroupmaps, Set<IsLkptxn> isLkptxns, Set<IsMstfund> isMstfunds, Set<Mstchequestyles> mstchequestyleses, Set<Mstsourcebenelinkage> mstsourcebenelinkages, Set<Mstmailsubject> mstmailsubjects, Set<Peerbeneacctdet> peerbeneacctdets, Set<Mstsecurityquestions> mstsecurityquestionses, Set<IsLimitorderdetails> isLimitorderdetailses, Set<Mstentityusertypes> mstentityusertypeses, Set<Msthostinterface> msthostinterfaces, Set<IsLkppricing> isLkppricings, Set<FcatTCommunications> fcatTCommunicationsesForSenderIdEntity, Set<Mstrole> mstroles, Set<Mobileenablerreturncodemap> mobileenablerreturncodemaps, Set<IsOrderstatusinquirydetails> isOrderstatusinquirydetailses) {
       this.idEntity = idEntity;
       this.mstentitytypes = mstentitytypes;
       this.description = description;
       this.idParent = idParent;
       this.idsort = idsort;
       this.isLkpcurrs = isLkpcurrs;
       this.isMstuserportfolios = isMstuserportfolios;
       this.isMstsidetailses = isMstsidetailses;
       this.isLkploads = isLkploads;
       this.mstentityusertypelangs = mstentityusertypelangs;
       this.isDeliverydetailses = isDeliverydetailses;
       this.origProdcategs = origProdcategs;
       this.fcatTCommunicationsesForReceiverIdEntity = fcatTCommunicationsesForReceiverIdEntity;
       this.mstaccttypeses = mstaccttypeses;
       this.isLkpacctcodes = isLkpacctcodes;
       this.isTxnactivitydetailses = isTxnactivitydetailses;
       this.isMstsideliverydetailses = isMstsideliverydetailses;
       this.isLkpscrips = isLkpscrips;
       this.mailmessages = mailmessages;
       this.mststatusgroupmaps = mststatusgroupmaps;
       this.isLkptxns = isLkptxns;
       this.isMstfunds = isMstfunds;
       this.mstchequestyleses = mstchequestyleses;
       this.mstsourcebenelinkages = mstsourcebenelinkages;
       this.mstmailsubjects = mstmailsubjects;
       this.peerbeneacctdets = peerbeneacctdets;
       this.mstsecurityquestionses = mstsecurityquestionses;
       this.isLimitorderdetailses = isLimitorderdetailses;
       this.mstentityusertypeses = mstentityusertypeses;
       this.msthostinterfaces = msthostinterfaces;
       this.isLkppricings = isLkppricings;
       this.fcatTCommunicationsesForSenderIdEntity = fcatTCommunicationsesForSenderIdEntity;
       this.mstroles = mstroles;
       this.mobileenablerreturncodemaps = mobileenablerreturncodemaps;
       this.isOrderstatusinquirydetailses = isOrderstatusinquirydetailses;
    }
   
     @Id 

    
    @Column(name="ID_ENTITY", unique=true, nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPENTITY")
    public Mstentitytypes getMstentitytypes() {
        return this.mstentitytypes;
    }
    
    public void setMstentitytypes(Mstentitytypes mstentitytypes) {
        this.mstentitytypes = mstentitytypes;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ID_PARENT", length=5)
    public String getIdParent() {
        return this.idParent;
    }
    
    public void setIdParent(String idParent) {
        this.idParent = idParent;
    }

    
    @Column(name="IDSORT", precision=22, scale=0)
    public BigDecimal getIdsort() {
        return this.idsort;
    }
    
    public void setIdsort(BigDecimal idsort) {
        this.idsort = idsort;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLkpcurr> getIsLkpcurrs() {
        return this.isLkpcurrs;
    }
    
    public void setIsLkpcurrs(Set<IsLkpcurr> isLkpcurrs) {
        this.isLkpcurrs = isLkpcurrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsMstuserportfolio> getIsMstuserportfolios() {
        return this.isMstuserportfolios;
    }
    
    public void setIsMstuserportfolios(Set<IsMstuserportfolio> isMstuserportfolios) {
        this.isMstuserportfolios = isMstuserportfolios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsMstsidetails> getIsMstsidetailses() {
        return this.isMstsidetailses;
    }
    
    public void setIsMstsidetailses(Set<IsMstsidetails> isMstsidetailses) {
        this.isMstsidetailses = isMstsidetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLkpload> getIsLkploads() {
        return this.isLkploads;
    }
    
    public void setIsLkploads(Set<IsLkpload> isLkploads) {
        this.isLkploads = isLkploads;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstentityusertypelang> getMstentityusertypelangs() {
        return this.mstentityusertypelangs;
    }
    
    public void setMstentityusertypelangs(Set<Mstentityusertypelang> mstentityusertypelangs) {
        this.mstentityusertypelangs = mstentityusertypelangs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsDeliverydetails> getIsDeliverydetailses() {
        return this.isDeliverydetailses;
    }
    
    public void setIsDeliverydetailses(Set<IsDeliverydetails> isDeliverydetailses) {
        this.isDeliverydetailses = isDeliverydetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<OrigProdcateg> getOrigProdcategs() {
        return this.origProdcategs;
    }
    
    public void setOrigProdcategs(Set<OrigProdcateg> origProdcategs) {
        this.origProdcategs = origProdcategs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentityByReceiverIdEntity")
    public Set<FcatTCommunications> getFcatTCommunicationsesForReceiverIdEntity() {
        return this.fcatTCommunicationsesForReceiverIdEntity;
    }
    
    public void setFcatTCommunicationsesForReceiverIdEntity(Set<FcatTCommunications> fcatTCommunicationsesForReceiverIdEntity) {
        this.fcatTCommunicationsesForReceiverIdEntity = fcatTCommunicationsesForReceiverIdEntity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstaccttypes> getMstaccttypeses() {
        return this.mstaccttypeses;
    }
    
    public void setMstaccttypeses(Set<Mstaccttypes> mstaccttypeses) {
        this.mstaccttypeses = mstaccttypeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLkpacctcode> getIsLkpacctcodes() {
        return this.isLkpacctcodes;
    }
    
    public void setIsLkpacctcodes(Set<IsLkpacctcode> isLkpacctcodes) {
        this.isLkpacctcodes = isLkpacctcodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsTxnactivitydetails> getIsTxnactivitydetailses() {
        return this.isTxnactivitydetailses;
    }
    
    public void setIsTxnactivitydetailses(Set<IsTxnactivitydetails> isTxnactivitydetailses) {
        this.isTxnactivitydetailses = isTxnactivitydetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsMstsideliverydetails> getIsMstsideliverydetailses() {
        return this.isMstsideliverydetailses;
    }
    
    public void setIsMstsideliverydetailses(Set<IsMstsideliverydetails> isMstsideliverydetailses) {
        this.isMstsideliverydetailses = isMstsideliverydetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLkpscrip> getIsLkpscrips() {
        return this.isLkpscrips;
    }
    
    public void setIsLkpscrips(Set<IsLkpscrip> isLkpscrips) {
        this.isLkpscrips = isLkpscrips;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mailmessage> getMailmessages() {
        return this.mailmessages;
    }
    
    public void setMailmessages(Set<Mailmessage> mailmessages) {
        this.mailmessages = mailmessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mststatusgroupmap> getMststatusgroupmaps() {
        return this.mststatusgroupmaps;
    }
    
    public void setMststatusgroupmaps(Set<Mststatusgroupmap> mststatusgroupmaps) {
        this.mststatusgroupmaps = mststatusgroupmaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLkptxn> getIsLkptxns() {
        return this.isLkptxns;
    }
    
    public void setIsLkptxns(Set<IsLkptxn> isLkptxns) {
        this.isLkptxns = isLkptxns;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsMstfund> getIsMstfunds() {
        return this.isMstfunds;
    }
    
    public void setIsMstfunds(Set<IsMstfund> isMstfunds) {
        this.isMstfunds = isMstfunds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstchequestyles> getMstchequestyleses() {
        return this.mstchequestyleses;
    }
    
    public void setMstchequestyleses(Set<Mstchequestyles> mstchequestyleses) {
        this.mstchequestyleses = mstchequestyleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstsourcebenelinkage> getMstsourcebenelinkages() {
        return this.mstsourcebenelinkages;
    }
    
    public void setMstsourcebenelinkages(Set<Mstsourcebenelinkage> mstsourcebenelinkages) {
        this.mstsourcebenelinkages = mstsourcebenelinkages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstmailsubject> getMstmailsubjects() {
        return this.mstmailsubjects;
    }
    
    public void setMstmailsubjects(Set<Mstmailsubject> mstmailsubjects) {
        this.mstmailsubjects = mstmailsubjects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Peerbeneacctdet> getPeerbeneacctdets() {
        return this.peerbeneacctdets;
    }
    
    public void setPeerbeneacctdets(Set<Peerbeneacctdet> peerbeneacctdets) {
        this.peerbeneacctdets = peerbeneacctdets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstsecurityquestions> getMstsecurityquestionses() {
        return this.mstsecurityquestionses;
    }
    
    public void setMstsecurityquestionses(Set<Mstsecurityquestions> mstsecurityquestionses) {
        this.mstsecurityquestionses = mstsecurityquestionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLimitorderdetails> getIsLimitorderdetailses() {
        return this.isLimitorderdetailses;
    }
    
    public void setIsLimitorderdetailses(Set<IsLimitorderdetails> isLimitorderdetailses) {
        this.isLimitorderdetailses = isLimitorderdetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstentityusertypes> getMstentityusertypeses() {
        return this.mstentityusertypeses;
    }
    
    public void setMstentityusertypeses(Set<Mstentityusertypes> mstentityusertypeses) {
        this.mstentityusertypeses = mstentityusertypeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Msthostinterface> getMsthostinterfaces() {
        return this.msthostinterfaces;
    }
    
    public void setMsthostinterfaces(Set<Msthostinterface> msthostinterfaces) {
        this.msthostinterfaces = msthostinterfaces;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsLkppricing> getIsLkppricings() {
        return this.isLkppricings;
    }
    
    public void setIsLkppricings(Set<IsLkppricing> isLkppricings) {
        this.isLkppricings = isLkppricings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentityBySenderIdEntity")
    public Set<FcatTCommunications> getFcatTCommunicationsesForSenderIdEntity() {
        return this.fcatTCommunicationsesForSenderIdEntity;
    }
    
    public void setFcatTCommunicationsesForSenderIdEntity(Set<FcatTCommunications> fcatTCommunicationsesForSenderIdEntity) {
        this.fcatTCommunicationsesForSenderIdEntity = fcatTCommunicationsesForSenderIdEntity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mstrole> getMstroles() {
        return this.mstroles;
    }
    
    public void setMstroles(Set<Mstrole> mstroles) {
        this.mstroles = mstroles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<Mobileenablerreturncodemap> getMobileenablerreturncodemaps() {
        return this.mobileenablerreturncodemaps;
    }
    
    public void setMobileenablerreturncodemaps(Set<Mobileenablerreturncodemap> mobileenablerreturncodemaps) {
        this.mobileenablerreturncodemaps = mobileenablerreturncodemaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentity")
    public Set<IsOrderstatusinquirydetails> getIsOrderstatusinquirydetailses() {
        return this.isOrderstatusinquirydetailses;
    }
    
    public void setIsOrderstatusinquirydetailses(Set<IsOrderstatusinquirydetails> isOrderstatusinquirydetailses) {
        this.isOrderstatusinquirydetailses = isOrderstatusinquirydetailses;
    }




}


