package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstentityuserchannelgrp generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYUSERCHANNELGRP"
    ,schema="FCDBADMIN_RK"
)
public class Mstentityuserchannelgrp  implements java.io.Serializable {


     private MstentityuserchannelgrpId id;
     private String policyidpassword;
     private String policyidtransaction;
     private String policyiduser;
     private String policycodeactivation;

    public Mstentityuserchannelgrp() {
    }

	
    public Mstentityuserchannelgrp(MstentityuserchannelgrpId id) {
        this.id = id;
    }
    public Mstentityuserchannelgrp(MstentityuserchannelgrpId id, String policyidpassword, String policyidtransaction, String policyiduser, String policycodeactivation) {
       this.id = id;
       this.policyidpassword = policyidpassword;
       this.policyidtransaction = policyidtransaction;
       this.policyiduser = policyiduser;
       this.policycodeactivation = policycodeactivation;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idgroup", column=@Column(name="IDGROUP", nullable=false, length=5) ) } )
    public MstentityuserchannelgrpId getId() {
        return this.id;
    }
    
    public void setId(MstentityuserchannelgrpId id) {
        this.id = id;
    }

    
    @Column(name="POLICYIDPASSWORD", length=50)
    public String getPolicyidpassword() {
        return this.policyidpassword;
    }
    
    public void setPolicyidpassword(String policyidpassword) {
        this.policyidpassword = policyidpassword;
    }

    
    @Column(name="POLICYIDTRANSACTION", length=50)
    public String getPolicyidtransaction() {
        return this.policyidtransaction;
    }
    
    public void setPolicyidtransaction(String policyidtransaction) {
        this.policyidtransaction = policyidtransaction;
    }

    
    @Column(name="POLICYIDUSER", length=50)
    public String getPolicyiduser() {
        return this.policyiduser;
    }
    
    public void setPolicyiduser(String policyiduser) {
        this.policyiduser = policyiduser;
    }

    
    @Column(name="POLICYCODEACTIVATION", length=50)
    public String getPolicycodeactivation() {
        return this.policycodeactivation;
    }
    
    public void setPolicycodeactivation(String policycodeactivation) {
        this.policycodeactivation = policycodeactivation;
    }




}


