package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstentityaccountaccess generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYACCOUNTACCESS"
    ,schema="FCDBADMIN_RK"
)
public class Mstentityaccountaccess  implements java.io.Serializable {


     private MstentityaccountaccessId id;
     private String lookupseq;

    public Mstentityaccountaccess() {
    }

	
    public Mstentityaccountaccess(MstentityaccountaccessId id) {
        this.id = id;
    }
    public Mstentityaccountaccess(MstentityaccountaccessId id, String lookupseq) {
       this.id = id;
       this.lookupseq = lookupseq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="typecust", column=@Column(name="TYPECUST", nullable=false, length=1) ), 
        @AttributeOverride(name="typetxn", column=@Column(name="TYPETXN", nullable=false, length=1) ) } )
    public MstentityaccountaccessId getId() {
        return this.id;
    }
    
    public void setId(MstentityaccountaccessId id) {
        this.id = id;
    }

    
    @Column(name="LOOKUPSEQ", length=3)
    public String getLookupseq() {
        return this.lookupseq;
    }
    
    public void setLookupseq(String lookupseq) {
        this.lookupseq = lookupseq;
    }




}


