package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstfxrateId generated by hbm2java
 */
@Embeddable
public class MstfxrateId  implements java.io.Serializable {


     private String idEntity;
     private String codcurrfrom;
     private String codcurrto;
     private String txtratetype;

    public MstfxrateId() {
    }

    public MstfxrateId(String idEntity, String codcurrfrom, String codcurrto, String txtratetype) {
       this.idEntity = idEntity;
       this.codcurrfrom = codcurrfrom;
       this.codcurrto = codcurrto;
       this.txtratetype = txtratetype;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="CODCURRFROM", nullable=false, length=3)
    public String getCodcurrfrom() {
        return this.codcurrfrom;
    }
    
    public void setCodcurrfrom(String codcurrfrom) {
        this.codcurrfrom = codcurrfrom;
    }


    @Column(name="CODCURRTO", nullable=false, length=3)
    public String getCodcurrto() {
        return this.codcurrto;
    }
    
    public void setCodcurrto(String codcurrto) {
        this.codcurrto = codcurrto;
    }


    @Column(name="TXTRATETYPE", nullable=false, length=8)
    public String getTxtratetype() {
        return this.txtratetype;
    }
    
    public void setTxtratetype(String txtratetype) {
        this.txtratetype = txtratetype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstfxrateId) ) return false;
		 MstfxrateId castOther = ( MstfxrateId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getCodcurrfrom()==castOther.getCodcurrfrom()) || ( this.getCodcurrfrom()!=null && castOther.getCodcurrfrom()!=null && this.getCodcurrfrom().equals(castOther.getCodcurrfrom()) ) )
 && ( (this.getCodcurrto()==castOther.getCodcurrto()) || ( this.getCodcurrto()!=null && castOther.getCodcurrto()!=null && this.getCodcurrto().equals(castOther.getCodcurrto()) ) )
 && ( (this.getTxtratetype()==castOther.getTxtratetype()) || ( this.getTxtratetype()!=null && castOther.getTxtratetype()!=null && this.getTxtratetype().equals(castOther.getTxtratetype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getCodcurrfrom() == null ? 0 : this.getCodcurrfrom().hashCode() );
         result = 37 * result + ( getCodcurrto() == null ? 0 : this.getCodcurrto().hashCode() );
         result = 37 * result + ( getTxtratetype() == null ? 0 : this.getTxtratetype().hashCode() );
         return result;
   }   


}


