package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstfilestatusupload generated by hbm2java
 */
@Entity
@Table(name="MSTFILESTATUSUPLOAD"
    ,schema="FCDBADMIN_RK"
)
public class Mstfilestatusupload  implements java.io.Serializable {


     private String filerefno;
     private Date dateupload;
     private String txtype;
     private String noofrec;
     private String status;
     private String filename;
     private Set<Filestatusuploaddet> filestatusuploaddets = new HashSet<Filestatusuploaddet>(0);

    public Mstfilestatusupload() {
    }

	
    public Mstfilestatusupload(String filerefno) {
        this.filerefno = filerefno;
    }
    public Mstfilestatusupload(String filerefno, Date dateupload, String txtype, String noofrec, String status, String filename, Set<Filestatusuploaddet> filestatusuploaddets) {
       this.filerefno = filerefno;
       this.dateupload = dateupload;
       this.txtype = txtype;
       this.noofrec = noofrec;
       this.status = status;
       this.filename = filename;
       this.filestatusuploaddets = filestatusuploaddets;
    }
   
     @Id 

    
    @Column(name="FILEREFNO", unique=true, nullable=false, length=35)
    public String getFilerefno() {
        return this.filerefno;
    }
    
    public void setFilerefno(String filerefno) {
        this.filerefno = filerefno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEUPLOAD", length=7)
    public Date getDateupload() {
        return this.dateupload;
    }
    
    public void setDateupload(Date dateupload) {
        this.dateupload = dateupload;
    }

    
    @Column(name="TXTYPE", length=10)
    public String getTxtype() {
        return this.txtype;
    }
    
    public void setTxtype(String txtype) {
        this.txtype = txtype;
    }

    
    @Column(name="NOOFREC", length=10)
    public String getNoofrec() {
        return this.noofrec;
    }
    
    public void setNoofrec(String noofrec) {
        this.noofrec = noofrec;
    }

    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="FILENAME", length=100)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstfilestatusupload")
    public Set<Filestatusuploaddet> getFilestatusuploaddets() {
        return this.filestatusuploaddets;
    }
    
    public void setFilestatusuploaddets(Set<Filestatusuploaddet> filestatusuploaddets) {
        this.filestatusuploaddets = filestatusuploaddets;
    }




}


