package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstflatrecordcomp generated by hbm2java
 */
@Entity
@Table(name="MSTFLATRECORDCOMP"
    ,schema="FCDBADMIN_RK"
)
public class Mstflatrecordcomp  implements java.io.Serializable {


     private MstflatrecordcompId id;
     private Character fgflag;
     private BigDecimal idfg;

    public Mstflatrecordcomp() {
    }

	
    public Mstflatrecordcomp(MstflatrecordcompId id) {
        this.id = id;
    }
    public Mstflatrecordcomp(MstflatrecordcompId id, Character fgflag, BigDecimal idfg) {
       this.id = id;
       this.fgflag = fgflag;
       this.idfg = idfg;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idrecord", column=@Column(name="IDRECORD", nullable=false, length=10) ), 
        @AttributeOverride(name="seqnbr", column=@Column(name="SEQNBR", nullable=false, precision=22, scale=0) ) } )
    public MstflatrecordcompId getId() {
        return this.id;
    }
    
    public void setId(MstflatrecordcompId id) {
        this.id = id;
    }

    
    @Column(name="FGFLAG", length=1)
    public Character getFgflag() {
        return this.fgflag;
    }
    
    public void setFgflag(Character fgflag) {
        this.fgflag = fgflag;
    }

    
    @Column(name="IDFG", precision=22, scale=0)
    public BigDecimal getIdfg() {
        return this.idfg;
    }
    
    public void setIdfg(BigDecimal idfg) {
        this.idfg = idfg;
    }




}


