package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstgloballimitspackage generated by hbm2java
 */
@Entity
@Table(name="MSTGLOBALLIMITSPACKAGE"
    ,schema="FCDBADMIN_RK"
)
public class Mstgloballimitspackage  implements java.io.Serializable {


     private MstgloballimitspackageId id;
     private String packageDesc;
     private Blob limits;
     private String createdby;
     private Date createdon;
     private String lastupdatedby;
     private Date lastupdatedon;
     private String isdefault;
     private String typeuser;

    public Mstgloballimitspackage() {
    }

	
    public Mstgloballimitspackage(MstgloballimitspackageId id) {
        this.id = id;
    }
    public Mstgloballimitspackage(MstgloballimitspackageId id, String packageDesc, Blob limits, String createdby, Date createdon, String lastupdatedby, Date lastupdatedon, String isdefault, String typeuser) {
       this.id = id;
       this.packageDesc = packageDesc;
       this.limits = limits;
       this.createdby = createdby;
       this.createdon = createdon;
       this.lastupdatedby = lastupdatedby;
       this.lastupdatedon = lastupdatedon;
       this.isdefault = isdefault;
       this.typeuser = typeuser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="packageId", column=@Column(name="PACKAGE_ID", nullable=false, length=50) ) } )
    public MstgloballimitspackageId getId() {
        return this.id;
    }
    
    public void setId(MstgloballimitspackageId id) {
        this.id = id;
    }

    
    @Column(name="PACKAGE_DESC", length=100)
    public String getPackageDesc() {
        return this.packageDesc;
    }
    
    public void setPackageDesc(String packageDesc) {
        this.packageDesc = packageDesc;
    }

    
    @Column(name="LIMITS")
    public Blob getLimits() {
        return this.limits;
    }
    
    public void setLimits(Blob limits) {
        this.limits = limits;
    }

    
    @Column(name="CREATEDBY", length=50)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDON", length=7)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="LASTUPDATEDBY", length=50)
    public String getLastupdatedby() {
        return this.lastupdatedby;
    }
    
    public void setLastupdatedby(String lastupdatedby) {
        this.lastupdatedby = lastupdatedby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATEDON", length=7)
    public Date getLastupdatedon() {
        return this.lastupdatedon;
    }
    
    public void setLastupdatedon(Date lastupdatedon) {
        this.lastupdatedon = lastupdatedon;
    }

    
    @Column(name="ISDEFAULT", length=1)
    public String getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault;
    }

    
    @Column(name="TYPEUSER", length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }




}


