package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mstgroup generated by hbm2java
 */
@Entity
@Table(name="MSTGROUP"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "IDGROUP", "DTIME", "SLNO"}) 
)
public class Mstgroup  implements java.io.Serializable {


     private MstgroupId id;
     private String groupdesc;
     private String token;
     private Date datcreated;
     private String makerid;
     private String checkerid;
     private Short statebit;
     private Date dtime;
     private BigDecimal slno;
     private String idparentgroup;

    public Mstgroup() {
    }

	
    public Mstgroup(MstgroupId id) {
        this.id = id;
    }
    public Mstgroup(MstgroupId id, String groupdesc, String token, Date datcreated, String makerid, String checkerid, Short statebit, Date dtime, BigDecimal slno, String idparentgroup) {
       this.id = id;
       this.groupdesc = groupdesc;
       this.token = token;
       this.datcreated = datcreated;
       this.makerid = makerid;
       this.checkerid = checkerid;
       this.statebit = statebit;
       this.dtime = dtime;
       this.slno = slno;
       this.idparentgroup = idparentgroup;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idgroup", column=@Column(name="IDGROUP", nullable=false, length=20) ) } )
    public MstgroupId getId() {
        return this.id;
    }
    
    public void setId(MstgroupId id) {
        this.id = id;
    }

    
    @Column(name="GROUPDESC", length=50)
    public String getGroupdesc() {
        return this.groupdesc;
    }
    
    public void setGroupdesc(String groupdesc) {
        this.groupdesc = groupdesc;
    }

    
    @Column(name="TOKEN", length=100)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="MAKERID", length=20)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    
    @Column(name="CHECKERID", length=20)
    public String getCheckerid() {
        return this.checkerid;
    }
    
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    
    @Column(name="STATEBIT", precision=3, scale=0)
    public Short getStatebit() {
        return this.statebit;
    }
    
    public void setStatebit(Short statebit) {
        this.statebit = statebit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    
    @Column(name="IDPARENTGROUP", length=20)
    public String getIdparentgroup() {
        return this.idparentgroup;
    }
    
    public void setIdparentgroup(String idparentgroup) {
        this.idparentgroup = idparentgroup;
    }




}


