package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Msthostrulemap generated by hbm2java
 */
@Entity
@Table(name="MSTHOSTRULEMAP"
    ,schema="FCDBADMIN_RK"
)
public class Msthostrulemap  implements java.io.Serializable {


     private MsthostrulemapId id;
     private Character isenable;

    public Msthostrulemap() {
    }

	
    public Msthostrulemap(MsthostrulemapId id) {
        this.id = id;
    }
    public Msthostrulemap(MsthostrulemapId id, Character isenable) {
       this.id = id;
       this.isenable = isenable;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idhost", column=@Column(name="IDHOST", nullable=false) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ), 
        @AttributeOverride(name="ruleversion", column=@Column(name="RULEVERSION", nullable=false, precision=4, scale=0) ) } )
    public MsthostrulemapId getId() {
        return this.id;
    }
    
    public void setId(MsthostrulemapId id) {
        this.id = id;
    }

    
    @Column(name="ISENABLE", length=1)
    public Character getIsenable() {
        return this.isenable;
    }
    
    public void setIsenable(Character isenable) {
        this.isenable = isenable;
    }




}


