package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Msthints generated by hbm2java
 */
@Entity
@Table(name="MSTHINTS"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="HINT_ID") 
)
public class Msthints  implements java.io.Serializable {


     private MsthintsId id;
     private String hintHeader;
     private String hintContents;
     private String styleClass;
     private String hintId;
     private String onloadFlag;
     private Character iscollapsed;

    public Msthints() {
    }

	
    public Msthints(MsthintsId id) {
        this.id = id;
    }
    public Msthints(MsthintsId id, String hintHeader, String hintContents, String styleClass, String hintId, String onloadFlag, Character iscollapsed) {
       this.id = id;
       this.hintHeader = hintHeader;
       this.hintContents = hintContents;
       this.styleClass = styleClass;
       this.hintId = hintId;
       this.onloadFlag = onloadFlag;
       this.iscollapsed = iscollapsed;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idChannel", column=@Column(name="ID_CHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=50) ), 
        @AttributeOverride(name="sequenceNo", column=@Column(name="SEQUENCE_NO", nullable=false, precision=22, scale=0) ) } )
    public MsthintsId getId() {
        return this.id;
    }
    
    public void setId(MsthintsId id) {
        this.id = id;
    }

    
    @Column(name="HINT_HEADER", length=500)
    public String getHintHeader() {
        return this.hintHeader;
    }
    
    public void setHintHeader(String hintHeader) {
        this.hintHeader = hintHeader;
    }

    
    @Column(name="HINT_CONTENTS", length=2000)
    public String getHintContents() {
        return this.hintContents;
    }
    
    public void setHintContents(String hintContents) {
        this.hintContents = hintContents;
    }

    
    @Column(name="STYLE_CLASS", length=50)
    public String getStyleClass() {
        return this.styleClass;
    }
    
    public void setStyleClass(String styleClass) {
        this.styleClass = styleClass;
    }

    
    @Column(name="HINT_ID", unique=true, length=50)
    public String getHintId() {
        return this.hintId;
    }
    
    public void setHintId(String hintId) {
        this.hintId = hintId;
    }

    
    @Column(name="ONLOAD_FLAG", length=10)
    public String getOnloadFlag() {
        return this.onloadFlag;
    }
    
    public void setOnloadFlag(String onloadFlag) {
        this.onloadFlag = onloadFlag;
    }

    
    @Column(name="ISCOLLAPSED", length=1)
    public Character getIscollapsed() {
        return this.iscollapsed;
    }
    
    public void setIscollapsed(Character iscollapsed) {
        this.iscollapsed = iscollapsed;
    }




}


