package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstinitauthstatus generated by hbm2java
 */
@Entity
@Table(name="MSTINITAUTHSTATUS"
    ,schema="FCDBADMIN_RK"
)
public class Mstinitauthstatus  implements java.io.Serializable {


     private MstinitauthstatusId id;
     private Mststatusconfig mststatusconfigByFlgnextstatus;
     private Mststatusconfig mststatusconfigByFlgcurrstatus;
     private String ismodulechkreqd;
     private String ispostauthreqd;
     private Short authoperation;
     private Character copytohistory;
     private Character alertrequired;
     private String chaseid;
     private String isinitalsoauth;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private String possiblenextstatus;

    public Mstinitauthstatus() {
    }

	
    public Mstinitauthstatus(MstinitauthstatusId id, Mststatusconfig mststatusconfigByFlgnextstatus, Mststatusconfig mststatusconfigByFlgcurrstatus) {
        this.id = id;
        this.mststatusconfigByFlgnextstatus = mststatusconfigByFlgnextstatus;
        this.mststatusconfigByFlgcurrstatus = mststatusconfigByFlgcurrstatus;
    }
    public Mstinitauthstatus(MstinitauthstatusId id, Mststatusconfig mststatusconfigByFlgnextstatus, Mststatusconfig mststatusconfigByFlgcurrstatus, String ismodulechkreqd, String ispostauthreqd, Short authoperation, Character copytohistory, Character alertrequired, String chaseid, String isinitalsoauth, String token1, String token2, String token3, String token4, String token5, String possiblenextstatus) {
       this.id = id;
       this.mststatusconfigByFlgnextstatus = mststatusconfigByFlgnextstatus;
       this.mststatusconfigByFlgcurrstatus = mststatusconfigByFlgcurrstatus;
       this.ismodulechkreqd = ismodulechkreqd;
       this.ispostauthreqd = ispostauthreqd;
       this.authoperation = authoperation;
       this.copytohistory = copytohistory;
       this.alertrequired = alertrequired;
       this.chaseid = chaseid;
       this.isinitalsoauth = isinitalsoauth;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.possiblenextstatus = possiblenextstatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="initauthid", column=@Column(name="INITAUTHID", nullable=false, length=30) ), 
        @AttributeOverride(name="flgcurrstatus", column=@Column(name="FLGCURRSTATUS", nullable=false, length=5) ), 
        @AttributeOverride(name="flgaction", column=@Column(name="FLGACTION", nullable=false, length=5) ), 
        @AttributeOverride(name="flgnextstatus", column=@Column(name="FLGNEXTSTATUS", nullable=false, length=5) ) } )
    public MstinitauthstatusId getId() {
        return this.id;
    }
    
    public void setId(MstinitauthstatusId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FLGNEXTSTATUS", nullable=false, insertable=false, updatable=false)
    public Mststatusconfig getMststatusconfigByFlgnextstatus() {
        return this.mststatusconfigByFlgnextstatus;
    }
    
    public void setMststatusconfigByFlgnextstatus(Mststatusconfig mststatusconfigByFlgnextstatus) {
        this.mststatusconfigByFlgnextstatus = mststatusconfigByFlgnextstatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FLGCURRSTATUS", nullable=false, insertable=false, updatable=false)
    public Mststatusconfig getMststatusconfigByFlgcurrstatus() {
        return this.mststatusconfigByFlgcurrstatus;
    }
    
    public void setMststatusconfigByFlgcurrstatus(Mststatusconfig mststatusconfigByFlgcurrstatus) {
        this.mststatusconfigByFlgcurrstatus = mststatusconfigByFlgcurrstatus;
    }

    
    @Column(name="ISMODULECHKREQD", length=1)
    public String getIsmodulechkreqd() {
        return this.ismodulechkreqd;
    }
    
    public void setIsmodulechkreqd(String ismodulechkreqd) {
        this.ismodulechkreqd = ismodulechkreqd;
    }

    
    @Column(name="ISPOSTAUTHREQD", length=1)
    public String getIspostauthreqd() {
        return this.ispostauthreqd;
    }
    
    public void setIspostauthreqd(String ispostauthreqd) {
        this.ispostauthreqd = ispostauthreqd;
    }

    
    @Column(name="AUTHOPERATION", precision=3, scale=0)
    public Short getAuthoperation() {
        return this.authoperation;
    }
    
    public void setAuthoperation(Short authoperation) {
        this.authoperation = authoperation;
    }

    
    @Column(name="COPYTOHISTORY", length=1)
    public Character getCopytohistory() {
        return this.copytohistory;
    }
    
    public void setCopytohistory(Character copytohistory) {
        this.copytohistory = copytohistory;
    }

    
    @Column(name="ALERTREQUIRED", length=1)
    public Character getAlertrequired() {
        return this.alertrequired;
    }
    
    public void setAlertrequired(Character alertrequired) {
        this.alertrequired = alertrequired;
    }

    
    @Column(name="CHASEID", length=20)
    public String getChaseid() {
        return this.chaseid;
    }
    
    public void setChaseid(String chaseid) {
        this.chaseid = chaseid;
    }

    
    @Column(name="ISINITALSOAUTH", length=1)
    public String getIsinitalsoauth() {
        return this.isinitalsoauth;
    }
    
    public void setIsinitalsoauth(String isinitalsoauth) {
        this.isinitalsoauth = isinitalsoauth;
    }

    
    @Column(name="TOKEN1", length=30)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=30)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=30)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4", length=30)
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5", length=30)
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="POSSIBLENEXTSTATUS", length=1)
    public String getPossiblenextstatus() {
        return this.possiblenextstatus;
    }
    
    public void setPossiblenextstatus(String possiblenextstatus) {
        this.possiblenextstatus = possiblenextstatus;
    }




}


