package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstlang generated by hbm2java
 */
@Entity
@Table(name="MSTLANG"
    ,schema="FCDBADMIN_RK"
)
public class Mstlang  implements java.io.Serializable {


     private String idlang;
     private String description;
     private String respencoding;
     private String xslencoding;
     private String isoLang;
     private String isoCountry;
     private String supportedRange;
     private String blockedRange;
     private String defaultDateFormat;
     private Character decimalSeprator;
     private String timeStampFormat;
     private BigDecimal seqno;
     private Set<Mstentityusertypelang> mstentityusertypelangs = new HashSet<Mstentityusertypelang>(0);

    public Mstlang() {
    }

	
    public Mstlang(String idlang) {
        this.idlang = idlang;
    }
    public Mstlang(String idlang, String description, String respencoding, String xslencoding, String isoLang, String isoCountry, String supportedRange, String blockedRange, String defaultDateFormat, Character decimalSeprator, String timeStampFormat, BigDecimal seqno, Set<Mstentityusertypelang> mstentityusertypelangs) {
       this.idlang = idlang;
       this.description = description;
       this.respencoding = respencoding;
       this.xslencoding = xslencoding;
       this.isoLang = isoLang;
       this.isoCountry = isoCountry;
       this.supportedRange = supportedRange;
       this.blockedRange = blockedRange;
       this.defaultDateFormat = defaultDateFormat;
       this.decimalSeprator = decimalSeprator;
       this.timeStampFormat = timeStampFormat;
       this.seqno = seqno;
       this.mstentityusertypelangs = mstentityusertypelangs;
    }
   
     @Id 

    
    @Column(name="IDLANG", unique=true, nullable=false, length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }

    
    @Column(name="DESCRIPTION", length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="RESPENCODING", length=50)
    public String getRespencoding() {
        return this.respencoding;
    }
    
    public void setRespencoding(String respencoding) {
        this.respencoding = respencoding;
    }

    
    @Column(name="XSLENCODING", length=50)
    public String getXslencoding() {
        return this.xslencoding;
    }
    
    public void setXslencoding(String xslencoding) {
        this.xslencoding = xslencoding;
    }

    
    @Column(name="ISO_LANG", length=2)
    public String getIsoLang() {
        return this.isoLang;
    }
    
    public void setIsoLang(String isoLang) {
        this.isoLang = isoLang;
    }

    
    @Column(name="ISO_COUNTRY", length=2)
    public String getIsoCountry() {
        return this.isoCountry;
    }
    
    public void setIsoCountry(String isoCountry) {
        this.isoCountry = isoCountry;
    }

    
    @Column(name="SUPPORTED_RANGE", length=1000)
    public String getSupportedRange() {
        return this.supportedRange;
    }
    
    public void setSupportedRange(String supportedRange) {
        this.supportedRange = supportedRange;
    }

    
    @Column(name="BLOCKED_RANGE", length=200)
    public String getBlockedRange() {
        return this.blockedRange;
    }
    
    public void setBlockedRange(String blockedRange) {
        this.blockedRange = blockedRange;
    }

    
    @Column(name="DEFAULT_DATE_FORMAT", length=15)
    public String getDefaultDateFormat() {
        return this.defaultDateFormat;
    }
    
    public void setDefaultDateFormat(String defaultDateFormat) {
        this.defaultDateFormat = defaultDateFormat;
    }

    
    @Column(name="DECIMAL_SEPRATOR", length=1)
    public Character getDecimalSeprator() {
        return this.decimalSeprator;
    }
    
    public void setDecimalSeprator(Character decimalSeprator) {
        this.decimalSeprator = decimalSeprator;
    }

    
    @Column(name="TIME_STAMP_FORMAT", length=20)
    public String getTimeStampFormat() {
        return this.timeStampFormat;
    }
    
    public void setTimeStampFormat(String timeStampFormat) {
        this.timeStampFormat = timeStampFormat;
    }

    
    @Column(name="SEQNO", precision=22, scale=0)
    public BigDecimal getSeqno() {
        return this.seqno;
    }
    
    public void setSeqno(BigDecimal seqno) {
        this.seqno = seqno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstlang")
    public Set<Mstentityusertypelang> getMstentityusertypelangs() {
        return this.mstentityusertypelangs;
    }
    
    public void setMstentityusertypelangs(Set<Mstentityusertypelang> mstentityusertypelangs) {
        this.mstentityusertypelangs = mstentityusertypelangs;
    }




}


