package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstremittancetype generated by hbm2java
 */
@Entity
@Table(name="MSTREMITTANCETYPE"
    ,schema="FCDBADMIN_RK"
)
public class Mstremittancetype  implements java.io.Serializable {


     private MstremittancetypeId id;
     private String remittanceType;
     private String isformreqd;
     private String isspotreqd;

    public Mstremittancetype() {
    }

	
    public Mstremittancetype(MstremittancetypeId id) {
        this.id = id;
    }
    public Mstremittancetype(MstremittancetypeId id, String remittanceType, String isformreqd, String isspotreqd) {
       this.id = id;
       this.remittanceType = remittanceType;
       this.isformreqd = isformreqd;
       this.isspotreqd = isspotreqd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="crUnittype", column=@Column(name="CR_UNITTYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="dbUnittype", column=@Column(name="DB_UNITTYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="crCurrtype", column=@Column(name="CR_CURRTYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="dbCurrtype", column=@Column(name="DB_CURRTYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="crossCurr", column=@Column(name="CROSS_CURR", nullable=false, length=2) ), 
        @AttributeOverride(name="custType", column=@Column(name="CUST_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="crCountry", column=@Column(name="CR_COUNTRY", nullable=false, length=2) ) } )
    public MstremittancetypeId getId() {
        return this.id;
    }
    
    public void setId(MstremittancetypeId id) {
        this.id = id;
    }

    
    @Column(name="REMITTANCE_TYPE", length=2)
    public String getRemittanceType() {
        return this.remittanceType;
    }
    
    public void setRemittanceType(String remittanceType) {
        this.remittanceType = remittanceType;
    }

    
    @Column(name="ISFORMREQD", length=2)
    public String getIsformreqd() {
        return this.isformreqd;
    }
    
    public void setIsformreqd(String isformreqd) {
        this.isformreqd = isformreqd;
    }

    
    @Column(name="ISSPOTREQD", length=2)
    public String getIsspotreqd() {
        return this.isspotreqd;
    }
    
    public void setIsspotreqd(String isspotreqd) {
        this.isspotreqd = isspotreqd;
    }




}


