package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstrouterrulefragment generated by hbm2java
 */
@Entity
@Table(name="MSTROUTERRULEFRAGMENT"
    ,schema="FCDBADMIN_RK"
)
public class Mstrouterrulefragment  implements java.io.Serializable {


     private MstrouterrulefragmentId id;
     private String namrule;
     private byte[] xmlrule;
     private Date lastupddatetime;

    public Mstrouterrulefragment() {
    }

	
    public Mstrouterrulefragment(MstrouterrulefragmentId id) {
        this.id = id;
    }
    public Mstrouterrulefragment(MstrouterrulefragmentId id, String namrule, byte[] xmlrule, Date lastupddatetime) {
       this.id = id;
       this.namrule = namrule;
       this.xmlrule = xmlrule;
       this.lastupddatetime = lastupddatetime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ruleversion", column=@Column(name="RULEVERSION", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false) ) } )
    public MstrouterrulefragmentId getId() {
        return this.id;
    }
    
    public void setId(MstrouterrulefragmentId id) {
        this.id = id;
    }

    
    @Column(name="NAMRULE")
    public String getNamrule() {
        return this.namrule;
    }
    
    public void setNamrule(String namrule) {
        this.namrule = namrule;
    }

    
    @Column(name="XMLRULE")
    public byte[] getXmlrule() {
        return this.xmlrule;
    }
    
    public void setXmlrule(byte[] xmlrule) {
        this.xmlrule = xmlrule;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDDATETIME", length=7)
    public Date getLastupddatetime() {
        return this.lastupddatetime;
    }
    
    public void setLastupddatetime(Date lastupddatetime) {
        this.lastupddatetime = lastupddatetime;
    }




}


