package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstrule generated by hbm2java
 */
@Entity
@Table(name="MSTRULE"
    ,schema="FCDBADMIN_RK"
)
public class Mstrule  implements java.io.Serializable {


     private MstruleId id;
     private Character datatype;
     private Byte startindex;
     private String name;

    public Mstrule() {
    }

	
    public Mstrule(MstruleId id) {
        this.id = id;
    }
    public Mstrule(MstruleId id, Character datatype, Byte startindex, String name) {
       this.id = id;
       this.datatype = datatype;
       this.startindex = startindex;
       this.name = name;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ) } )
    public MstruleId getId() {
        return this.id;
    }
    
    public void setId(MstruleId id) {
        this.id = id;
    }

    
    @Column(name="DATATYPE", length=1)
    public Character getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(Character datatype) {
        this.datatype = datatype;
    }

    
    @Column(name="STARTINDEX", precision=2, scale=0)
    public Byte getStartindex() {
        return this.startindex;
    }
    
    public void setStartindex(Byte startindex) {
        this.startindex = startindex;
    }

    
    @Column(name="NAME", length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


