package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstrulevariable generated by hbm2java
 */
@Entity
@Table(name="MSTRULEVARIABLE"
    ,schema="FCDBADMIN_RK"
)
public class Mstrulevariable  implements java.io.Serializable {


     private MstrulevariableId id;
     private Character datatype;
     private String name;

    public Mstrulevariable() {
    }

	
    public Mstrulevariable(MstrulevariableId id) {
        this.id = id;
    }
    public Mstrulevariable(MstrulevariableId id, Character datatype, String name) {
       this.id = id;
       this.datatype = datatype;
       this.name = name;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ), 
        @AttributeOverride(name="idindex", column=@Column(name="IDINDEX", nullable=false, precision=2, scale=0) ) } )
    public MstrulevariableId getId() {
        return this.id;
    }
    
    public void setId(MstrulevariableId id) {
        this.id = id;
    }

    
    @Column(name="DATATYPE", length=1)
    public Character getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(Character datatype) {
        this.datatype = datatype;
    }

    
    @Column(name="NAME", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


