package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Msttransaction generated by hbm2java
 */
@Entity
@Table(name="MSTTRANSACTION"
    ,schema="FCDBADMIN_RK"
)
public class Msttransaction  implements java.io.Serializable {


     private String codtransaction;
     private String appid;
     private String idtxn;
     private String scrnid;
     private String txttxndesc;
     private String idprog;
     private String sendrqtype;
     private String sendmsgtype;
     private String idserverhost;
     private String tagname;
     private BigDecimal flgamtlimits;
     private BigDecimal dailylimitamt;
     private BigDecimal txnlimitamt;
     private Set<Mstuseracct> mstuseraccts = new HashSet<Mstuseracct>(0);

    public Msttransaction() {
    }

	
    public Msttransaction(String codtransaction) {
        this.codtransaction = codtransaction;
    }
    public Msttransaction(String codtransaction, String appid, String idtxn, String scrnid, String txttxndesc, String idprog, String sendrqtype, String sendmsgtype, String idserverhost, String tagname, BigDecimal flgamtlimits, BigDecimal dailylimitamt, BigDecimal txnlimitamt, Set<Mstuseracct> mstuseraccts) {
       this.codtransaction = codtransaction;
       this.appid = appid;
       this.idtxn = idtxn;
       this.scrnid = scrnid;
       this.txttxndesc = txttxndesc;
       this.idprog = idprog;
       this.sendrqtype = sendrqtype;
       this.sendmsgtype = sendmsgtype;
       this.idserverhost = idserverhost;
       this.tagname = tagname;
       this.flgamtlimits = flgamtlimits;
       this.dailylimitamt = dailylimitamt;
       this.txnlimitamt = txnlimitamt;
       this.mstuseraccts = mstuseraccts;
    }
   
     @Id 

    
    @Column(name="CODTRANSACTION", unique=true, nullable=false, length=3)
    public String getCodtransaction() {
        return this.codtransaction;
    }
    
    public void setCodtransaction(String codtransaction) {
        this.codtransaction = codtransaction;
    }

    
    @Column(name="APPID", length=2)
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="SCRNID", length=2)
    public String getScrnid() {
        return this.scrnid;
    }
    
    public void setScrnid(String scrnid) {
        this.scrnid = scrnid;
    }

    
    @Column(name="TXTTXNDESC", length=30)
    public String getTxttxndesc() {
        return this.txttxndesc;
    }
    
    public void setTxttxndesc(String txttxndesc) {
        this.txttxndesc = txttxndesc;
    }

    
    @Column(name="IDPROG", length=39)
    public String getIdprog() {
        return this.idprog;
    }
    
    public void setIdprog(String idprog) {
        this.idprog = idprog;
    }

    
    @Column(name="SENDRQTYPE", length=2)
    public String getSendrqtype() {
        return this.sendrqtype;
    }
    
    public void setSendrqtype(String sendrqtype) {
        this.sendrqtype = sendrqtype;
    }

    
    @Column(name="SENDMSGTYPE", length=3)
    public String getSendmsgtype() {
        return this.sendmsgtype;
    }
    
    public void setSendmsgtype(String sendmsgtype) {
        this.sendmsgtype = sendmsgtype;
    }

    
    @Column(name="IDSERVERHOST", length=2)
    public String getIdserverhost() {
        return this.idserverhost;
    }
    
    public void setIdserverhost(String idserverhost) {
        this.idserverhost = idserverhost;
    }

    
    @Column(name="TAGNAME", length=30)
    public String getTagname() {
        return this.tagname;
    }
    
    public void setTagname(String tagname) {
        this.tagname = tagname;
    }

    
    @Column(name="FLGAMTLIMITS", precision=38, scale=0)
    public BigDecimal getFlgamtlimits() {
        return this.flgamtlimits;
    }
    
    public void setFlgamtlimits(BigDecimal flgamtlimits) {
        this.flgamtlimits = flgamtlimits;
    }

    
    @Column(name="DAILYLIMITAMT", scale=4)
    public BigDecimal getDailylimitamt() {
        return this.dailylimitamt;
    }
    
    public void setDailylimitamt(BigDecimal dailylimitamt) {
        this.dailylimitamt = dailylimitamt;
    }

    
    @Column(name="TXNLIMITAMT", scale=4)
    public BigDecimal getTxnlimitamt() {
        return this.txnlimitamt;
    }
    
    public void setTxnlimitamt(BigDecimal txnlimitamt) {
        this.txnlimitamt = txnlimitamt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="msttransaction")
    public Set<Mstuseracct> getMstuseraccts() {
        return this.mstuseraccts;
    }
    
    public void setMstuseraccts(Set<Mstuseracct> mstuseraccts) {
        this.mstuseraccts = mstuseraccts;
    }




}


