package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstuidownloadformats generated by hbm2java
 */
@Entity
@Table(name="MSTUIDOWNLOADFORMATS"
    ,schema="FCDBADMIN_RK"
)
public class Mstuidownloadformats  implements java.io.Serializable {


     private MstuidownloadformatsId id;
     private String formatIdrequest;

    public Mstuidownloadformats() {
    }

	
    public Mstuidownloadformats(MstuidownloadformatsId id) {
        this.id = id;
    }
    public Mstuidownloadformats(MstuidownloadformatsId id, String formatIdrequest) {
       this.id = id;
       this.formatIdrequest = formatIdrequest;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="typeformat", column=@Column(name="TYPEFORMAT", nullable=false, length=5) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MstuidownloadformatsId getId() {
        return this.id;
    }
    
    public void setId(MstuidownloadformatsId id) {
        this.id = id;
    }

    
    @Column(name="FORMAT_IDREQUEST", length=8)
    public String getFormatIdrequest() {
        return this.formatIdrequest;
    }
    
    public void setFormatIdrequest(String formatIdrequest) {
        this.formatIdrequest = formatIdrequest;
    }




}


