package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstuseracct generated by hbm2java
 */
@Entity
@Table(name="MSTUSERACCT"
    ,schema="FCDBADMIN_RK"
)
public class Mstuseracct  implements java.io.Serializable {


     private MstuseracctId id;
     private Msttransaction msttransaction;
     private String idEntity;

    public Mstuseracct() {
    }

	
    public Mstuseracct(MstuseracctId id, Msttransaction msttransaction) {
        this.id = id;
        this.msttransaction = msttransaction;
    }
    public Mstuseracct(MstuseracctId id, Msttransaction msttransaction, String idEntity) {
       this.id = id;
       this.msttransaction = msttransaction;
       this.idEntity = idEntity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=10) ), 
        @AttributeOverride(name="codtransaction", column=@Column(name="CODTRANSACTION", nullable=false, length=3) ), 
        @AttributeOverride(name="idaccount", column=@Column(name="IDACCOUNT", nullable=false, length=20) ), 
        @AttributeOverride(name="codbranch", column=@Column(name="CODBRANCH", nullable=false, length=5) ), 
        @AttributeOverride(name="idcorporate", column=@Column(name="IDCORPORATE", nullable=false, length=20) ), 
        @AttributeOverride(name="idlocation", column=@Column(name="IDLOCATION", nullable=false, length=20) ) } )
    public MstuseracctId getId() {
        return this.id;
    }
    
    public void setId(MstuseracctId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODTRANSACTION", nullable=false, insertable=false, updatable=false)
    public Msttransaction getMsttransaction() {
        return this.msttransaction;
    }
    
    public void setMsttransaction(Msttransaction msttransaction) {
        this.msttransaction = msttransaction;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }




}


