package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mstwizard generated by hbm2java
 */
@Entity
@Table(name="MSTWIZARD"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "USERTYPE", "IDCHANNEL", "IDREQUEST"}) 
)
public class Mstwizard  implements java.io.Serializable {


     private MstwizardId id;
     private String startCondition;

    public Mstwizard() {
    }

	
    public Mstwizard(MstwizardId id) {
        this.id = id;
    }
    public Mstwizard(MstwizardId id, String startCondition) {
       this.id = id;
       this.startCondition = startCondition;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idwizard", column=@Column(name="IDWIZARD", nullable=false, length=20) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ) } )
    public MstwizardId getId() {
        return this.id;
    }
    
    public void setId(MstwizardId id) {
        this.id = id;
    }

    
    @Column(name="START_CONDITION", length=500)
    public String getStartCondition() {
        return this.startCondition;
    }
    
    public void setStartCondition(String startCondition) {
        this.startCondition = startCondition;
    }




}


