package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mstwidget generated by hbm2java
 */
@Entity
@Table(name="MSTWIDGET"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "USERTYPE", "IDCHANNEL", "DASHBOARDID", "WIDGET_POS", "WIDGET_SEQ"}) 
)
public class Mstwidget  implements java.io.Serializable {


     private MstwidgetId id;
     private Character widgetPos;
     private Character widgetType;
     private Byte widgetSeq;
     private String externalInfo;
     private Character hasnavigation;
     private Character canrefresh;
     private String addtnlParams;
     private Character isenabled;
     private Character morelink;
     private Character ismandatory;
     private Boolean heightscalar;
     private Boolean widthscalar;
     private String udf1;
     private String udf2;
     private String udf3;
     private String udf4;
     private String udf5;
     private String refIdrequest;

    public Mstwidget() {
    }

	
    public Mstwidget(MstwidgetId id) {
        this.id = id;
    }
    public Mstwidget(MstwidgetId id, Character widgetPos, Character widgetType, Byte widgetSeq, String externalInfo, Character hasnavigation, Character canrefresh, String addtnlParams, Character isenabled, Character morelink, Character ismandatory, Boolean heightscalar, Boolean widthscalar, String udf1, String udf2, String udf3, String udf4, String udf5, String refIdrequest) {
       this.id = id;
       this.widgetPos = widgetPos;
       this.widgetType = widgetType;
       this.widgetSeq = widgetSeq;
       this.externalInfo = externalInfo;
       this.hasnavigation = hasnavigation;
       this.canrefresh = canrefresh;
       this.addtnlParams = addtnlParams;
       this.isenabled = isenabled;
       this.morelink = morelink;
       this.ismandatory = ismandatory;
       this.heightscalar = heightscalar;
       this.widthscalar = widthscalar;
       this.udf1 = udf1;
       this.udf2 = udf2;
       this.udf3 = udf3;
       this.udf4 = udf4;
       this.udf5 = udf5;
       this.refIdrequest = refIdrequest;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="dashboardid", column=@Column(name="DASHBOARDID", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ) } )
    public MstwidgetId getId() {
        return this.id;
    }
    
    public void setId(MstwidgetId id) {
        this.id = id;
    }

    
    @Column(name="WIDGET_POS", length=1)
    public Character getWidgetPos() {
        return this.widgetPos;
    }
    
    public void setWidgetPos(Character widgetPos) {
        this.widgetPos = widgetPos;
    }

    
    @Column(name="WIDGET_TYPE", length=1)
    public Character getWidgetType() {
        return this.widgetType;
    }
    
    public void setWidgetType(Character widgetType) {
        this.widgetType = widgetType;
    }

    
    @Column(name="WIDGET_SEQ", precision=2, scale=0)
    public Byte getWidgetSeq() {
        return this.widgetSeq;
    }
    
    public void setWidgetSeq(Byte widgetSeq) {
        this.widgetSeq = widgetSeq;
    }

    
    @Column(name="EXTERNAL_INFO", length=4000)
    public String getExternalInfo() {
        return this.externalInfo;
    }
    
    public void setExternalInfo(String externalInfo) {
        this.externalInfo = externalInfo;
    }

    
    @Column(name="HASNAVIGATION", length=1)
    public Character getHasnavigation() {
        return this.hasnavigation;
    }
    
    public void setHasnavigation(Character hasnavigation) {
        this.hasnavigation = hasnavigation;
    }

    
    @Column(name="CANREFRESH", length=1)
    public Character getCanrefresh() {
        return this.canrefresh;
    }
    
    public void setCanrefresh(Character canrefresh) {
        this.canrefresh = canrefresh;
    }

    
    @Column(name="ADDTNL_PARAMS", length=4000)
    public String getAddtnlParams() {
        return this.addtnlParams;
    }
    
    public void setAddtnlParams(String addtnlParams) {
        this.addtnlParams = addtnlParams;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="MORELINK", length=1)
    public Character getMorelink() {
        return this.morelink;
    }
    
    public void setMorelink(Character morelink) {
        this.morelink = morelink;
    }

    
    @Column(name="ISMANDATORY", length=1)
    public Character getIsmandatory() {
        return this.ismandatory;
    }
    
    public void setIsmandatory(Character ismandatory) {
        this.ismandatory = ismandatory;
    }

    
    @Column(name="HEIGHTSCALAR", precision=1, scale=0)
    public Boolean getHeightscalar() {
        return this.heightscalar;
    }
    
    public void setHeightscalar(Boolean heightscalar) {
        this.heightscalar = heightscalar;
    }

    
    @Column(name="WIDTHSCALAR", precision=1, scale=0)
    public Boolean getWidthscalar() {
        return this.widthscalar;
    }
    
    public void setWidthscalar(Boolean widthscalar) {
        this.widthscalar = widthscalar;
    }

    
    @Column(name="UDF1")
    public String getUdf1() {
        return this.udf1;
    }
    
    public void setUdf1(String udf1) {
        this.udf1 = udf1;
    }

    
    @Column(name="UDF2")
    public String getUdf2() {
        return this.udf2;
    }
    
    public void setUdf2(String udf2) {
        this.udf2 = udf2;
    }

    
    @Column(name="UDF3")
    public String getUdf3() {
        return this.udf3;
    }
    
    public void setUdf3(String udf3) {
        this.udf3 = udf3;
    }

    
    @Column(name="UDF4")
    public String getUdf4() {
        return this.udf4;
    }
    
    public void setUdf4(String udf4) {
        this.udf4 = udf4;
    }

    
    @Column(name="UDF5")
    public String getUdf5() {
        return this.udf5;
    }
    
    public void setUdf5(String udf5) {
        this.udf5 = udf5;
    }

    
    @Column(name="REF_IDREQUEST", length=8)
    public String getRefIdrequest() {
        return this.refIdrequest;
    }
    
    public void setRefIdrequest(String refIdrequest) {
        this.refIdrequest = refIdrequest;
    }




}


