package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstworkflow generated by hbm2java
 */
@Entity
@Table(name="MSTWORKFLOW"
    ,schema="FCDBADMIN_RK"
)
public class Mstworkflow  implements java.io.Serializable {


     private MstworkflowId id;
     private Date datcreated;
     private Character isenabled;
     private Set<OrigApplication> origApplications = new HashSet<OrigApplication>(0);

    public Mstworkflow() {
    }

	
    public Mstworkflow(MstworkflowId id) {
        this.id = id;
    }
    public Mstworkflow(MstworkflowId id, Date datcreated, Character isenabled, Set<OrigApplication> origApplications) {
       this.id = id;
       this.datcreated = datcreated;
       this.isenabled = isenabled;
       this.origApplications = origApplications;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idworkflow", column=@Column(name="IDWORKFLOW", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", nullable=false, precision=22, scale=0) ) } )
    public MstworkflowId getId() {
        return this.id;
    }
    
    public void setId(MstworkflowId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstworkflow")
    public Set<OrigApplication> getOrigApplications() {
        return this.origApplications;
    }
    
    public void setOrigApplications(Set<OrigApplication> origApplications) {
        this.origApplications = origApplications;
    }




}


