package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Peerbeneacctdet generated by hbm2java
 */
@Entity
@Table(name="PEERBENEACCTDET"
    ,schema="FCDBADMIN_RK"
)
public class Peerbeneacctdet  implements java.io.Serializable {


     private PeerbeneacctdetId id;
     private Mstentity mstentity;
     private Mstuser mstuser;
     private String acc;
     private String bankCode;
     private Date dateAdded;
     private String branchCode;
     private String bankName;
     private Character accVerified;
     private String nettype;

    public Peerbeneacctdet() {
    }

	
    public Peerbeneacctdet(PeerbeneacctdetId id, Mstentity mstentity, Mstuser mstuser) {
        this.id = id;
        this.mstentity = mstentity;
        this.mstuser = mstuser;
    }
    public Peerbeneacctdet(PeerbeneacctdetId id, Mstentity mstentity, Mstuser mstuser, String acc, String bankCode, Date dateAdded, String branchCode, String bankName, Character accVerified, String nettype) {
       this.id = id;
       this.mstentity = mstentity;
       this.mstuser = mstuser;
       this.acc = acc;
       this.bankCode = bankCode;
       this.dateAdded = dateAdded;
       this.branchCode = branchCode;
       this.bankName = bankName;
       this.accVerified = accVerified;
       this.nettype = nettype;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="refidEntity", column=@Column(name="REFID_ENTITY", nullable=false, length=5) ) } )
    public PeerbeneacctdetId getId() {
        return this.id;
    }
    
    public void setId(PeerbeneacctdetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REFID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSER", nullable=false, insertable=false, updatable=false)
    public Mstuser getMstuser() {
        return this.mstuser;
    }
    
    public void setMstuser(Mstuser mstuser) {
        this.mstuser = mstuser;
    }

    
    @Column(name="ACC", length=30)
    public String getAcc() {
        return this.acc;
    }
    
    public void setAcc(String acc) {
        this.acc = acc;
    }

    
    @Column(name="BANK_CODE", length=20)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ADDED", length=7)
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    
    @Column(name="BRANCH_CODE", length=3)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    
    @Column(name="BANK_NAME")
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="ACC_VERIFIED", length=1)
    public Character getAccVerified() {
        return this.accVerified;
    }
    
    public void setAccVerified(Character accVerified) {
        this.accVerified = accVerified;
    }

    
    @Column(name="NETTYPE", length=10)
    public String getNettype() {
        return this.nettype;
    }
    
    public void setNettype(String nettype) {
        this.nettype = nettype;
    }




}


