package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Routerauditlog generated by hbm2java
 */
@Entity
@Table(name="ROUTERAUDITLOG"
    ,schema="FCDBADMIN_RK"
)
public class Routerauditlog  implements java.io.Serializable {


     private RouterauditlogId id;
     private Character typ;
     private Date dattxn;
     private String idrule;
     private Short ruleversion;
     private Integer idoper;
     private Blob auditxml;
     private String namoper;
     private String returncode;
     private String errorcode;
     private String errormsg;
     private String iduser;
     private String idmessage;

    public Routerauditlog() {
    }

	
    public Routerauditlog(RouterauditlogId id) {
        this.id = id;
    }
    public Routerauditlog(RouterauditlogId id, Character typ, Date dattxn, String idrule, Short ruleversion, Integer idoper, Blob auditxml, String namoper, String returncode, String errorcode, String errormsg, String iduser, String idmessage) {
       this.id = id;
       this.typ = typ;
       this.dattxn = dattxn;
       this.idrule = idrule;
       this.ruleversion = ruleversion;
       this.idoper = idoper;
       this.auditxml = auditxml;
       this.namoper = namoper;
       this.returncode = returncode;
       this.errorcode = errorcode;
       this.errormsg = errormsg;
       this.iduser = iduser;
       this.idmessage = idmessage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idinvocation", column=@Column(name="IDINVOCATION", nullable=false) ), 
        @AttributeOverride(name="idseq", column=@Column(name="IDSEQ", nullable=false, precision=22, scale=0) ) } )
    public RouterauditlogId getId() {
        return this.id;
    }
    
    public void setId(RouterauditlogId id) {
        this.id = id;
    }

    
    @Column(name="TYP", length=1)
    public Character getTyp() {
        return this.typ;
    }
    
    public void setTyp(Character typ) {
        this.typ = typ;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATTXN", length=7)
    public Date getDattxn() {
        return this.dattxn;
    }
    
    public void setDattxn(Date dattxn) {
        this.dattxn = dattxn;
    }

    
    @Column(name="IDRULE")
    public String getIdrule() {
        return this.idrule;
    }
    
    public void setIdrule(String idrule) {
        this.idrule = idrule;
    }

    
    @Column(name="RULEVERSION", precision=4, scale=0)
    public Short getRuleversion() {
        return this.ruleversion;
    }
    
    public void setRuleversion(Short ruleversion) {
        this.ruleversion = ruleversion;
    }

    
    @Column(name="IDOPER", precision=9, scale=0)
    public Integer getIdoper() {
        return this.idoper;
    }
    
    public void setIdoper(Integer idoper) {
        this.idoper = idoper;
    }

    
    @Column(name="AUDITXML")
    public Blob getAuditxml() {
        return this.auditxml;
    }
    
    public void setAuditxml(Blob auditxml) {
        this.auditxml = auditxml;
    }

    
    @Column(name="NAMOPER", length=100)
    public String getNamoper() {
        return this.namoper;
    }
    
    public void setNamoper(String namoper) {
        this.namoper = namoper;
    }

    
    @Column(name="RETURNCODE", length=5)
    public String getReturncode() {
        return this.returncode;
    }
    
    public void setReturncode(String returncode) {
        this.returncode = returncode;
    }

    
    @Column(name="ERRORCODE", length=20)
    public String getErrorcode() {
        return this.errorcode;
    }
    
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    
    @Column(name="ERRORMSG", length=1000)
    public String getErrormsg() {
        return this.errormsg;
    }
    
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="IDMESSAGE", length=50)
    public String getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(String idmessage) {
        this.idmessage = idmessage;
    }




}


