package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Screentemplate generated by hbm2java
 */
@Entity
@Table(name="SCREENTEMPLATE"
    ,schema="FCDBADMIN_RK"
)
public class Screentemplate  implements java.io.Serializable {


     private ScreentemplateId id;
     private Msthtmldatatypes msthtmldatatypesByLabeltype;
     private Msthtmldatatypes msthtmldatatypesByType;
     private String idtxn;
     private String label;
     private String labelclass;
     private String labelwidth;
     private BigDecimal labelcolspan;
     private String name;
     private String dataclass;
     private String datawidth;
     private BigDecimal datacolspan;
     private String nodevalue;
     private BigDecimal idrow;
     private BigDecimal columnid;
     private BigDecimal tableno;
     private String function;
     private String functionargs;
     private String inputsize;
     private String inputmaxlength;
     private String isudf;
     private String alt;
     private String image;
     private String defaultstaticlabels;
     private String readonly;
     private BigDecimal tabindex;
     private String mandatoryicon;
     private String ismandatory;
     private String defaultvalue;
     private BigDecimal labelrowspan;
     private BigDecimal datarowspan;
     private String rowarraynode;
     private String dynamicfunctionargs;
     private String condition;
     private BigDecimal relposx;
     private BigDecimal relposy;
     private BigDecimal relwidth;
     private BigDecimal relheight;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private BigDecimal stepnumber;
     private String rowclass;
     private String elementclass;

    public Screentemplate() {
    }

	
    public Screentemplate(ScreentemplateId id) {
        this.id = id;
    }
    public Screentemplate(ScreentemplateId id, Msthtmldatatypes msthtmldatatypesByLabeltype, Msthtmldatatypes msthtmldatatypesByType, String idtxn, String label, String labelclass, String labelwidth, BigDecimal labelcolspan, String name, String dataclass, String datawidth, BigDecimal datacolspan, String nodevalue, BigDecimal idrow, BigDecimal columnid, BigDecimal tableno, String function, String functionargs, String inputsize, String inputmaxlength, String isudf, String alt, String image, String defaultstaticlabels, String readonly, BigDecimal tabindex, String mandatoryicon, String ismandatory, String defaultvalue, BigDecimal labelrowspan, BigDecimal datarowspan, String rowarraynode, String dynamicfunctionargs, String condition, BigDecimal relposx, BigDecimal relposy, BigDecimal relwidth, BigDecimal relheight, String token1, String token2, String token3, String token4, String token5, BigDecimal stepnumber, String rowclass, String elementclass) {
       this.id = id;
       this.msthtmldatatypesByLabeltype = msthtmldatatypesByLabeltype;
       this.msthtmldatatypesByType = msthtmldatatypesByType;
       this.idtxn = idtxn;
       this.label = label;
       this.labelclass = labelclass;
       this.labelwidth = labelwidth;
       this.labelcolspan = labelcolspan;
       this.name = name;
       this.dataclass = dataclass;
       this.datawidth = datawidth;
       this.datacolspan = datacolspan;
       this.nodevalue = nodevalue;
       this.idrow = idrow;
       this.columnid = columnid;
       this.tableno = tableno;
       this.function = function;
       this.functionargs = functionargs;
       this.inputsize = inputsize;
       this.inputmaxlength = inputmaxlength;
       this.isudf = isudf;
       this.alt = alt;
       this.image = image;
       this.defaultstaticlabels = defaultstaticlabels;
       this.readonly = readonly;
       this.tabindex = tabindex;
       this.mandatoryicon = mandatoryicon;
       this.ismandatory = ismandatory;
       this.defaultvalue = defaultvalue;
       this.labelrowspan = labelrowspan;
       this.datarowspan = datarowspan;
       this.rowarraynode = rowarraynode;
       this.dynamicfunctionargs = dynamicfunctionargs;
       this.condition = condition;
       this.relposx = relposx;
       this.relposy = relposy;
       this.relwidth = relwidth;
       this.relheight = relheight;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.stepnumber = stepnumber;
       this.rowclass = rowclass;
       this.elementclass = elementclass;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="identity", column=@Column(name="IDENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, length=50) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=50) ) } )
    public ScreentemplateId getId() {
        return this.id;
    }
    
    public void setId(ScreentemplateId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LABELTYPE")
    public Msthtmldatatypes getMsthtmldatatypesByLabeltype() {
        return this.msthtmldatatypesByLabeltype;
    }
    
    public void setMsthtmldatatypesByLabeltype(Msthtmldatatypes msthtmldatatypesByLabeltype) {
        this.msthtmldatatypesByLabeltype = msthtmldatatypesByLabeltype;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE")
    public Msthtmldatatypes getMsthtmldatatypesByType() {
        return this.msthtmldatatypesByType;
    }
    
    public void setMsthtmldatatypesByType(Msthtmldatatypes msthtmldatatypesByType) {
        this.msthtmldatatypesByType = msthtmldatatypesByType;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="LABEL", length=200)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    
    @Column(name="LABELCLASS", length=200)
    public String getLabelclass() {
        return this.labelclass;
    }
    
    public void setLabelclass(String labelclass) {
        this.labelclass = labelclass;
    }

    
    @Column(name="LABELWIDTH", length=100)
    public String getLabelwidth() {
        return this.labelwidth;
    }
    
    public void setLabelwidth(String labelwidth) {
        this.labelwidth = labelwidth;
    }

    
    @Column(name="LABELCOLSPAN", precision=22, scale=0)
    public BigDecimal getLabelcolspan() {
        return this.labelcolspan;
    }
    
    public void setLabelcolspan(BigDecimal labelcolspan) {
        this.labelcolspan = labelcolspan;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DATACLASS", length=100)
    public String getDataclass() {
        return this.dataclass;
    }
    
    public void setDataclass(String dataclass) {
        this.dataclass = dataclass;
    }

    
    @Column(name="DATAWIDTH", length=50)
    public String getDatawidth() {
        return this.datawidth;
    }
    
    public void setDatawidth(String datawidth) {
        this.datawidth = datawidth;
    }

    
    @Column(name="DATACOLSPAN", precision=22, scale=0)
    public BigDecimal getDatacolspan() {
        return this.datacolspan;
    }
    
    public void setDatacolspan(BigDecimal datacolspan) {
        this.datacolspan = datacolspan;
    }

    
    @Column(name="NODEVALUE", length=4000)
    public String getNodevalue() {
        return this.nodevalue;
    }
    
    public void setNodevalue(String nodevalue) {
        this.nodevalue = nodevalue;
    }

    
    @Column(name="IDROW", precision=22, scale=0)
    public BigDecimal getIdrow() {
        return this.idrow;
    }
    
    public void setIdrow(BigDecimal idrow) {
        this.idrow = idrow;
    }

    
    @Column(name="COLUMNID", precision=22, scale=0)
    public BigDecimal getColumnid() {
        return this.columnid;
    }
    
    public void setColumnid(BigDecimal columnid) {
        this.columnid = columnid;
    }

    
    @Column(name="TABLENO", precision=22, scale=0)
    public BigDecimal getTableno() {
        return this.tableno;
    }
    
    public void setTableno(BigDecimal tableno) {
        this.tableno = tableno;
    }

    
    @Column(name="FUNCTION", length=100)
    public String getFunction() {
        return this.function;
    }
    
    public void setFunction(String function) {
        this.function = function;
    }

    
    @Column(name="FUNCTIONARGS", length=500)
    public String getFunctionargs() {
        return this.functionargs;
    }
    
    public void setFunctionargs(String functionargs) {
        this.functionargs = functionargs;
    }

    
    @Column(name="INPUTSIZE", length=3)
    public String getInputsize() {
        return this.inputsize;
    }
    
    public void setInputsize(String inputsize) {
        this.inputsize = inputsize;
    }

    
    @Column(name="INPUTMAXLENGTH", length=3)
    public String getInputmaxlength() {
        return this.inputmaxlength;
    }
    
    public void setInputmaxlength(String inputmaxlength) {
        this.inputmaxlength = inputmaxlength;
    }

    
    @Column(name="ISUDF", length=1)
    public String getIsudf() {
        return this.isudf;
    }
    
    public void setIsudf(String isudf) {
        this.isudf = isudf;
    }

    
    @Column(name="ALT", length=1000)
    public String getAlt() {
        return this.alt;
    }
    
    public void setAlt(String alt) {
        this.alt = alt;
    }

    
    @Column(name="IMAGE", length=250)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="DEFAULTSTATICLABELS", length=250)
    public String getDefaultstaticlabels() {
        return this.defaultstaticlabels;
    }
    
    public void setDefaultstaticlabels(String defaultstaticlabels) {
        this.defaultstaticlabels = defaultstaticlabels;
    }

    
    @Column(name="READONLY", length=6)
    public String getReadonly() {
        return this.readonly;
    }
    
    public void setReadonly(String readonly) {
        this.readonly = readonly;
    }

    
    @Column(name="TABINDEX", precision=22, scale=0)
    public BigDecimal getTabindex() {
        return this.tabindex;
    }
    
    public void setTabindex(BigDecimal tabindex) {
        this.tabindex = tabindex;
    }

    
    @Column(name="MANDATORYICON", length=100)
    public String getMandatoryicon() {
        return this.mandatoryicon;
    }
    
    public void setMandatoryicon(String mandatoryicon) {
        this.mandatoryicon = mandatoryicon;
    }

    
    @Column(name="ISMANDATORY", length=1)
    public String getIsmandatory() {
        return this.ismandatory;
    }
    
    public void setIsmandatory(String ismandatory) {
        this.ismandatory = ismandatory;
    }

    
    @Column(name="DEFAULTVALUE", length=1000)
    public String getDefaultvalue() {
        return this.defaultvalue;
    }
    
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    
    @Column(name="LABELROWSPAN", precision=22, scale=0)
    public BigDecimal getLabelrowspan() {
        return this.labelrowspan;
    }
    
    public void setLabelrowspan(BigDecimal labelrowspan) {
        this.labelrowspan = labelrowspan;
    }

    
    @Column(name="DATAROWSPAN", precision=22, scale=0)
    public BigDecimal getDatarowspan() {
        return this.datarowspan;
    }
    
    public void setDatarowspan(BigDecimal datarowspan) {
        this.datarowspan = datarowspan;
    }

    
    @Column(name="ROWARRAYNODE", length=1000)
    public String getRowarraynode() {
        return this.rowarraynode;
    }
    
    public void setRowarraynode(String rowarraynode) {
        this.rowarraynode = rowarraynode;
    }

    
    @Column(name="DYNAMICFUNCTIONARGS", length=1000)
    public String getDynamicfunctionargs() {
        return this.dynamicfunctionargs;
    }
    
    public void setDynamicfunctionargs(String dynamicfunctionargs) {
        this.dynamicfunctionargs = dynamicfunctionargs;
    }

    
    @Column(name="CONDITION", length=1000)
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }

    
    @Column(name="RELPOSX", precision=4, scale=3)
    public BigDecimal getRelposx() {
        return this.relposx;
    }
    
    public void setRelposx(BigDecimal relposx) {
        this.relposx = relposx;
    }

    
    @Column(name="RELPOSY", precision=4, scale=3)
    public BigDecimal getRelposy() {
        return this.relposy;
    }
    
    public void setRelposy(BigDecimal relposy) {
        this.relposy = relposy;
    }

    
    @Column(name="RELWIDTH", precision=4, scale=3)
    public BigDecimal getRelwidth() {
        return this.relwidth;
    }
    
    public void setRelwidth(BigDecimal relwidth) {
        this.relwidth = relwidth;
    }

    
    @Column(name="RELHEIGHT", precision=4, scale=3)
    public BigDecimal getRelheight() {
        return this.relheight;
    }
    
    public void setRelheight(BigDecimal relheight) {
        this.relheight = relheight;
    }

    
    @Column(name="TOKEN1", length=250)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=250)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=250)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4", length=250)
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5", length=1000)
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="STEPNUMBER", precision=22, scale=0)
    public BigDecimal getStepnumber() {
        return this.stepnumber;
    }
    
    public void setStepnumber(BigDecimal stepnumber) {
        this.stepnumber = stepnumber;
    }

    
    @Column(name="ROWCLASS", length=50)
    public String getRowclass() {
        return this.rowclass;
    }
    
    public void setRowclass(String rowclass) {
        this.rowclass = rowclass;
    }

    
    @Column(name="ELEMENTCLASS", length=50)
    public String getElementclass() {
        return this.elementclass;
    }
    
    public void setElementclass(String elementclass) {
        this.elementclass = elementclass;
    }




}


