package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ServiceRequestStatus generated by hbm2java
 */
@Entity
@Table(name="SERVICE_REQUEST_STATUS"
    ,schema="FCDBADMIN_RK"
)
public class ServiceRequestStatus  implements java.io.Serializable {


     private String status;
     private String statusDesc;

    public ServiceRequestStatus() {
    }

	
    public ServiceRequestStatus(String status) {
        this.status = status;
    }
    public ServiceRequestStatus(String status, String statusDesc) {
       this.status = status;
       this.statusDesc = statusDesc;
    }
   
     @Id 

    
    @Column(name="STATUS", unique=true, nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="STATUS_DESC", length=100)
    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }




}


