package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txndealtimer generated by hbm2java
 */
@Entity
@Table(name="TXNDEALTIMER"
    ,schema="FCDBADMIN_RK"
)
public class Txndealtimer  implements java.io.Serializable {


     private long timerseq;
     private String idEntity;
     private String idchannel;
     private String fromccy;
     private String toccy;
     private Short timer;
     private Date effectivedate;
     private Date datlastupdt;
     private Date datcreated;
     private Character disableflag;

    public Txndealtimer() {
    }

	
    public Txndealtimer(long timerseq) {
        this.timerseq = timerseq;
    }
    public Txndealtimer(long timerseq, String idEntity, String idchannel, String fromccy, String toccy, Short timer, Date effectivedate, Date datlastupdt, Date datcreated, Character disableflag) {
       this.timerseq = timerseq;
       this.idEntity = idEntity;
       this.idchannel = idchannel;
       this.fromccy = fromccy;
       this.toccy = toccy;
       this.timer = timer;
       this.effectivedate = effectivedate;
       this.datlastupdt = datlastupdt;
       this.datcreated = datcreated;
       this.disableflag = disableflag;
    }
   
     @Id 

    
    @Column(name="TIMERSEQ", unique=true, nullable=false, precision=10, scale=0)
    public long getTimerseq() {
        return this.timerseq;
    }
    
    public void setTimerseq(long timerseq) {
        this.timerseq = timerseq;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDCHANNEL", length=3)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    
    @Column(name="FROMCCY", length=3)
    public String getFromccy() {
        return this.fromccy;
    }
    
    public void setFromccy(String fromccy) {
        this.fromccy = fromccy;
    }

    
    @Column(name="TOCCY", length=3)
    public String getToccy() {
        return this.toccy;
    }
    
    public void setToccy(String toccy) {
        this.toccy = toccy;
    }

    
    @Column(name="TIMER", precision=4, scale=0)
    public Short getTimer() {
        return this.timer;
    }
    
    public void setTimer(Short timer) {
        this.timer = timer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVEDATE", length=7)
    public Date getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(Date effectivedate) {
        this.effectivedate = effectivedate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTUPDT", length=7)
    public Date getDatlastupdt() {
        return this.datlastupdt;
    }
    
    public void setDatlastupdt(Date datlastupdt) {
        this.datlastupdt = datlastupdt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="DISABLEFLAG", length=1)
    public Character getDisableflag() {
        return this.disableflag;
    }
    
    public void setDisableflag(Character disableflag) {
        this.disableflag = disableflag;
    }




}


