package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Txnreceipts generated by hbm2java
 */
@Entity
@Table(name="TXNRECEIPTS"
    ,schema="FCDBADMIN_RK"
)
public class Txnreceipts  implements java.io.Serializable {


     private TxnreceiptsId id;
     private String preprocessfile;
     private String screenreceipt;
     private String pdfreceipt;
     private String preprocessorclass;
     private String applicableStatus;
     private String applicablePrcsdTxnStatus;
     private Character showOnConfirm;
     private Character showOnInitiated;
     private Character showForAuthorizer;
     private Character showOnViewtxn;
     private Character showOnInquiry;
     private Character showForPrcsdTxnOnly;
     private String additionalParams;

    public Txnreceipts() {
    }

	
    public Txnreceipts(TxnreceiptsId id) {
        this.id = id;
    }
    public Txnreceipts(TxnreceiptsId id, String preprocessfile, String screenreceipt, String pdfreceipt, String preprocessorclass, String applicableStatus, String applicablePrcsdTxnStatus, Character showOnConfirm, Character showOnInitiated, Character showForAuthorizer, Character showOnViewtxn, Character showOnInquiry, Character showForPrcsdTxnOnly, String additionalParams) {
       this.id = id;
       this.preprocessfile = preprocessfile;
       this.screenreceipt = screenreceipt;
       this.pdfreceipt = pdfreceipt;
       this.preprocessorclass = preprocessorclass;
       this.applicableStatus = applicableStatus;
       this.applicablePrcsdTxnStatus = applicablePrcsdTxnStatus;
       this.showOnConfirm = showOnConfirm;
       this.showOnInitiated = showOnInitiated;
       this.showForAuthorizer = showForAuthorizer;
       this.showOnViewtxn = showOnViewtxn;
       this.showOnInquiry = showOnInquiry;
       this.showForPrcsdTxnOnly = showForPrcsdTxnOnly;
       this.additionalParams = additionalParams;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="identity", column=@Column(name="IDENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=50) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ) } )
    public TxnreceiptsId getId() {
        return this.id;
    }
    
    public void setId(TxnreceiptsId id) {
        this.id = id;
    }

    
    @Column(name="PREPROCESSFILE", length=50)
    public String getPreprocessfile() {
        return this.preprocessfile;
    }
    
    public void setPreprocessfile(String preprocessfile) {
        this.preprocessfile = preprocessfile;
    }

    
    @Column(name="SCREENRECEIPT", length=50)
    public String getScreenreceipt() {
        return this.screenreceipt;
    }
    
    public void setScreenreceipt(String screenreceipt) {
        this.screenreceipt = screenreceipt;
    }

    
    @Column(name="PDFRECEIPT", length=50)
    public String getPdfreceipt() {
        return this.pdfreceipt;
    }
    
    public void setPdfreceipt(String pdfreceipt) {
        this.pdfreceipt = pdfreceipt;
    }

    
    @Column(name="PREPROCESSORCLASS", length=256)
    public String getPreprocessorclass() {
        return this.preprocessorclass;
    }
    
    public void setPreprocessorclass(String preprocessorclass) {
        this.preprocessorclass = preprocessorclass;
    }

    
    @Column(name="APPLICABLE_STATUS", length=1024)
    public String getApplicableStatus() {
        return this.applicableStatus;
    }
    
    public void setApplicableStatus(String applicableStatus) {
        this.applicableStatus = applicableStatus;
    }

    
    @Column(name="APPLICABLE_PRCSD_TXN_STATUS", length=1024)
    public String getApplicablePrcsdTxnStatus() {
        return this.applicablePrcsdTxnStatus;
    }
    
    public void setApplicablePrcsdTxnStatus(String applicablePrcsdTxnStatus) {
        this.applicablePrcsdTxnStatus = applicablePrcsdTxnStatus;
    }

    
    @Column(name="SHOW_ON_CONFIRM", length=1)
    public Character getShowOnConfirm() {
        return this.showOnConfirm;
    }
    
    public void setShowOnConfirm(Character showOnConfirm) {
        this.showOnConfirm = showOnConfirm;
    }

    
    @Column(name="SHOW_ON_INITIATED", length=1)
    public Character getShowOnInitiated() {
        return this.showOnInitiated;
    }
    
    public void setShowOnInitiated(Character showOnInitiated) {
        this.showOnInitiated = showOnInitiated;
    }

    
    @Column(name="SHOW_FOR_AUTHORIZER", length=1)
    public Character getShowForAuthorizer() {
        return this.showForAuthorizer;
    }
    
    public void setShowForAuthorizer(Character showForAuthorizer) {
        this.showForAuthorizer = showForAuthorizer;
    }

    
    @Column(name="SHOW_ON_VIEWTXN", length=1)
    public Character getShowOnViewtxn() {
        return this.showOnViewtxn;
    }
    
    public void setShowOnViewtxn(Character showOnViewtxn) {
        this.showOnViewtxn = showOnViewtxn;
    }

    
    @Column(name="SHOW_ON_INQUIRY", length=1)
    public Character getShowOnInquiry() {
        return this.showOnInquiry;
    }
    
    public void setShowOnInquiry(Character showOnInquiry) {
        this.showOnInquiry = showOnInquiry;
    }

    
    @Column(name="SHOW_FOR_PRCSD_TXN_ONLY", length=1)
    public Character getShowForPrcsdTxnOnly() {
        return this.showForPrcsdTxnOnly;
    }
    
    public void setShowForPrcsdTxnOnly(Character showForPrcsdTxnOnly) {
        this.showForPrcsdTxnOnly = showForPrcsdTxnOnly;
    }

    
    @Column(name="ADDITIONAL_PARAMS", length=4000)
    public String getAdditionalParams() {
        return this.additionalParams;
    }
    
    public void setAdditionalParams(String additionalParams) {
        this.additionalParams = additionalParams;
    }




}


