package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name="USERROLE",schema="FCDBADMIN_RK")
public class Userrole  implements java.io.Serializable {
     
	private UserroleId id;

    public Userrole() {
    }

    public Userrole(UserroleId id) {
       this.id = id;
    }
   
     	@EmbeddedId
     	@AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrole", column=@Column(name="IDROLE", nullable=false, length=20) ) } )
    public UserroleId getId() {
        return this.id;
    }
    
    public void setId(UserroleId id) {
        this.id = id;
    }




}


