package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userpaginationmaster generated by hbm2java
 */
@Entity
@Table(name="USERPAGINATIONMASTER"
    ,schema="FCDBADMIN_RK"
)
public class Userpaginationmaster  implements java.io.Serializable {


     private UserpaginationmasterId id;
     private Byte recordsperpage;
     private String txnpath;
     private String sortinfo;
     private Byte defrecordsperpage;
     private Integer recordcount;

    public Userpaginationmaster() {
    }

	
    public Userpaginationmaster(UserpaginationmasterId id) {
        this.id = id;
    }
    public Userpaginationmaster(UserpaginationmasterId id, Byte recordsperpage, String txnpath, String sortinfo, Byte defrecordsperpage, Integer recordcount) {
       this.id = id;
       this.recordsperpage = recordsperpage;
       this.txnpath = txnpath;
       this.sortinfo = sortinfo;
       this.defrecordsperpage = defrecordsperpage;
       this.recordcount = recordcount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=30) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="idsession", column=@Column(name="IDSESSION", nullable=false, length=50) ) } )
    public UserpaginationmasterId getId() {
        return this.id;
    }
    
    public void setId(UserpaginationmasterId id) {
        this.id = id;
    }

    
    @Column(name="RECORDSPERPAGE", precision=2, scale=0)
    public Byte getRecordsperpage() {
        return this.recordsperpage;
    }
    
    public void setRecordsperpage(Byte recordsperpage) {
        this.recordsperpage = recordsperpage;
    }

    
    @Column(name="TXNPATH", length=4000)
    public String getTxnpath() {
        return this.txnpath;
    }
    
    public void setTxnpath(String txnpath) {
        this.txnpath = txnpath;
    }

    
    @Column(name="SORTINFO", length=100)
    public String getSortinfo() {
        return this.sortinfo;
    }
    
    public void setSortinfo(String sortinfo) {
        this.sortinfo = sortinfo;
    }

    
    @Column(name="DEFRECORDSPERPAGE", precision=2, scale=0)
    public Byte getDefrecordsperpage() {
        return this.defrecordsperpage;
    }
    
    public void setDefrecordsperpage(Byte defrecordsperpage) {
        this.defrecordsperpage = defrecordsperpage;
    }

    
    @Column(name="RECORDCOUNT", precision=9, scale=0)
    public Integer getRecordcount() {
        return this.recordcount;
    }
    
    public void setRecordcount(Integer recordcount) {
        this.recordcount = recordcount;
    }




}


