package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Usercardcifmap generated by hbm2java
 */
@Entity
@Table(name="USERCARDCIFMAP"
    ,schema="FCDBADMIN_RK"
)
public class Usercardcifmap  implements java.io.Serializable {


     private UsercardcifmapId id;

    public Usercardcifmap() {
    }

    public Usercardcifmap(UsercardcifmapId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idcif", column=@Column(name="IDCIF", nullable=false, length=30) ) } )
    public UsercardcifmapId getId() {
        return this.id;
    }
    
    public void setId(UsercardcifmapId id) {
        this.id = id;
    }




}


