package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usergoal generated by hbm2java
 */
@Entity
@Table(name="USERGOAL"
    ,schema="FCDBADMIN_RK"
)
public class Usergoal  implements java.io.Serializable {


     private String goalRefNo;
     private GoalCategories goalCategoriesByIdparentcategory;
     private GoalCategories goalCategoriesByIdcategory;
     private Mstuser mstuser;
     private String goalAccNo;
     private String goalBranch;
     private String idEntity;
     private Blob image;
     private String typeImg;
     private BigDecimal goalAmt;
     private String namgoal;
     private Date datcreated;
     private Date matdate;
     private Character status;
     private String ccy;
     private Character isthresholdcrossed;
     private Character tenortype;

    public Usergoal() {
    }

	
    public Usergoal(String goalRefNo) {
        this.goalRefNo = goalRefNo;
    }
    public Usergoal(String goalRefNo, GoalCategories goalCategoriesByIdparentcategory, GoalCategories goalCategoriesByIdcategory, Mstuser mstuser, String goalAccNo, String goalBranch, String idEntity, Blob image, String typeImg, BigDecimal goalAmt, String namgoal, Date datcreated, Date matdate, Character status, String ccy, Character isthresholdcrossed, Character tenortype) {
       this.goalRefNo = goalRefNo;
       this.goalCategoriesByIdparentcategory = goalCategoriesByIdparentcategory;
       this.goalCategoriesByIdcategory = goalCategoriesByIdcategory;
       this.mstuser = mstuser;
       this.goalAccNo = goalAccNo;
       this.goalBranch = goalBranch;
       this.idEntity = idEntity;
       this.image = image;
       this.typeImg = typeImg;
       this.goalAmt = goalAmt;
       this.namgoal = namgoal;
       this.datcreated = datcreated;
       this.matdate = matdate;
       this.status = status;
       this.ccy = ccy;
       this.isthresholdcrossed = isthresholdcrossed;
       this.tenortype = tenortype;
    }
   
     @Id 

    
    @Column(name="GOAL_REF_NO", unique=true, nullable=false, length=15)
    public String getGoalRefNo() {
        return this.goalRefNo;
    }
    
    public void setGoalRefNo(String goalRefNo) {
        this.goalRefNo = goalRefNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPARENTCATEGORY")
    public GoalCategories getGoalCategoriesByIdparentcategory() {
        return this.goalCategoriesByIdparentcategory;
    }
    
    public void setGoalCategoriesByIdparentcategory(GoalCategories goalCategoriesByIdparentcategory) {
        this.goalCategoriesByIdparentcategory = goalCategoriesByIdparentcategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCATEGORY")
    public GoalCategories getGoalCategoriesByIdcategory() {
        return this.goalCategoriesByIdcategory;
    }
    
    public void setGoalCategoriesByIdcategory(GoalCategories goalCategoriesByIdcategory) {
        this.goalCategoriesByIdcategory = goalCategoriesByIdcategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSER")
    public Mstuser getMstuser() {
        return this.mstuser;
    }
    
    public void setMstuser(Mstuser mstuser) {
        this.mstuser = mstuser;
    }

    
    @Column(name="GOAL_ACC_NO", length=30)
    public String getGoalAccNo() {
        return this.goalAccNo;
    }
    
    public void setGoalAccNo(String goalAccNo) {
        this.goalAccNo = goalAccNo;
    }

    
    @Column(name="GOAL_BRANCH", length=3)
    public String getGoalBranch() {
        return this.goalBranch;
    }
    
    public void setGoalBranch(String goalBranch) {
        this.goalBranch = goalBranch;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IMAGE")
    public Blob getImage() {
        return this.image;
    }
    
    public void setImage(Blob image) {
        this.image = image;
    }

    
    @Column(name="TYPE_IMG", length=10)
    public String getTypeImg() {
        return this.typeImg;
    }
    
    public void setTypeImg(String typeImg) {
        this.typeImg = typeImg;
    }

    
    @Column(name="GOAL_AMT", precision=22, scale=3)
    public BigDecimal getGoalAmt() {
        return this.goalAmt;
    }
    
    public void setGoalAmt(BigDecimal goalAmt) {
        this.goalAmt = goalAmt;
    }

    
    @Column(name="NAMGOAL", length=40)
    public String getNamgoal() {
        return this.namgoal;
    }
    
    public void setNamgoal(String namgoal) {
        this.namgoal = namgoal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MATDATE", length=7)
    public Date getMatdate() {
        return this.matdate;
    }
    
    public void setMatdate(Date matdate) {
        this.matdate = matdate;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="CCY", length=3)
    public String getCcy() {
        return this.ccy;
    }
    
    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    
    @Column(name="ISTHRESHOLDCROSSED", length=1)
    public Character getIsthresholdcrossed() {
        return this.isthresholdcrossed;
    }
    
    public void setIsthresholdcrossed(Character isthresholdcrossed) {
        this.isthresholdcrossed = isthresholdcrossed;
    }

    
    @Column(name="TENORTYPE", length=1)
    public Character getTenortype() {
        return this.tenortype;
    }
    
    public void setTenortype(Character tenortype) {
        this.tenortype = tenortype;
    }




}


