package com.example.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usercustacctrel generated by hbm2java
 */
@Entity
@Table(name="USERCUSTACCTREL"
    ,schema="FCDBADMIN_RK"
)
public class Usercustacctrel  implements java.io.Serializable {


     private UsercustacctrelId id;
     private Mstuser mstuser;
     private String idEntity;
     private String idrelationship;

    public Usercustacctrel() {
    }

	
    public Usercustacctrel(UsercustacctrelId id, Mstuser mstuser) {
        this.id = id;
        this.mstuser = mstuser;
    }
    public Usercustacctrel(UsercustacctrelId id, Mstuser mstuser, String idEntity, String idrelationship) {
       this.id = id;
       this.mstuser = mstuser;
       this.idEntity = idEntity;
       this.idrelationship = idrelationship;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=30) ), 
        @AttributeOverride(name="idaccount", column=@Column(name="IDACCOUNT", nullable=false, length=20) ), 
        @AttributeOverride(name="codbranch", column=@Column(name="CODBRANCH", nullable=false, length=5) ) } )
    public UsercustacctrelId getId() {
        return this.id;
    }
    
    public void setId(UsercustacctrelId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSER", nullable=false, insertable=false, updatable=false)
    public Mstuser getMstuser() {
        return this.mstuser;
    }
    
    public void setMstuser(Mstuser mstuser) {
        this.mstuser = mstuser;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDRELATIONSHIP", length=4)
    public String getIdrelationship() {
        return this.idrelationship;
    }
    
    public void setIdrelationship(String idrelationship) {
        this.idrelationship = idrelationship;
    }




}


