package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Accountnicknames generated by hbm2java
 */
@Entity
@Table(name="ACCOUNTNICKNAMES"
    ,schema="FCDBADMIN_RK"
)
public class Accountnicknames  implements java.io.Serializable {


     private AccountnicknamesId id;
     private String currencycode;
     private String nickname;
     private String isfavourite;

    public Accountnicknames() {
    }

	
    public Accountnicknames(AccountnicknamesId id) {
        this.id = id;
    }
    public Accountnicknames(AccountnicknamesId id, String currencycode, String nickname, String isfavourite) {
       this.id = id;
       this.currencycode = currencycode;
       this.nickname = nickname;
       this.isfavourite = isfavourite;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="identity", column=@Column(name="IDENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=10) ), 
        @AttributeOverride(name="codbranch", column=@Column(name="CODBRANCH", nullable=false, length=5) ), 
        @AttributeOverride(name="accttype", column=@Column(name="ACCTTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="codacctno", column=@Column(name="CODACCTNO", nullable=false, length=20) ) } )
    public AccountnicknamesId getId() {
        return this.id;
    }
    
    public void setId(AccountnicknamesId id) {
        this.id = id;
    }

    
    @Column(name="CURRENCYCODE", length=3)
    public String getCurrencycode() {
        return this.currencycode;
    }
    
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }

    
    @Column(name="NICKNAME", length=100)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    
    @Column(name="ISFAVOURITE", length=1)
    public String getIsfavourite() {
        return this.isfavourite;
    }
    
    public void setIsfavourite(String isfavourite) {
        this.isfavourite = isfavourite;
    }




}


