package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcctactivityHeaderId generated by hbm2java
 */
@Embeddable
public class AcctactivityHeaderId  implements java.io.Serializable {


     private String iduser;
     private String idcust;
     private String codacctno;
     private String codbrn;

    public AcctactivityHeaderId() {
    }

    public AcctactivityHeaderId(String iduser, String idcust, String codacctno, String codbrn) {
       this.iduser = iduser;
       this.idcust = idcust;
       this.codacctno = codacctno;
       this.codbrn = codbrn;
    }
   


    @Column(name="IDUSER", nullable=false, length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }


    @Column(name="IDCUST", nullable=false, length=30)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }


    @Column(name="CODACCTNO", nullable=false, length=30)
    public String getCodacctno() {
        return this.codacctno;
    }
    
    public void setCodacctno(String codacctno) {
        this.codacctno = codacctno;
    }


    @Column(name="CODBRN", nullable=false, length=5)
    public String getCodbrn() {
        return this.codbrn;
    }
    
    public void setCodbrn(String codbrn) {
        this.codbrn = codbrn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcctactivityHeaderId) ) return false;
		 AcctactivityHeaderId castOther = ( AcctactivityHeaderId ) other; 
         
		 return ( (this.getIduser()==castOther.getIduser()) || ( this.getIduser()!=null && castOther.getIduser()!=null && this.getIduser().equals(castOther.getIduser()) ) )
 && ( (this.getIdcust()==castOther.getIdcust()) || ( this.getIdcust()!=null && castOther.getIdcust()!=null && this.getIdcust().equals(castOther.getIdcust()) ) )
 && ( (this.getCodacctno()==castOther.getCodacctno()) || ( this.getCodacctno()!=null && castOther.getCodacctno()!=null && this.getCodacctno().equals(castOther.getCodacctno()) ) )
 && ( (this.getCodbrn()==castOther.getCodbrn()) || ( this.getCodbrn()!=null && castOther.getCodbrn()!=null && this.getCodbrn().equals(castOther.getCodbrn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIduser() == null ? 0 : this.getIduser().hashCode() );
         result = 37 * result + ( getIdcust() == null ? 0 : this.getIdcust().hashCode() );
         result = 37 * result + ( getCodacctno() == null ? 0 : this.getCodacctno().hashCode() );
         result = 37 * result + ( getCodbrn() == null ? 0 : this.getCodbrn().hashCode() );
         return result;
   }   


}


