package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Adcontent generated by hbm2java
 */
@Entity
@Table(name="ADCONTENT"
    ,schema="FCDBADMIN_RK"
)
public class Adcontent  implements java.io.Serializable {


     private AdcontentId id;
     private String addesc;
     private String adurl;
     private String imageurl;
     private String caption;
     private String type;
     private String geoLongitude;
     private String geoLatitude;
     private String adcateg;
     private String adtype;
     private String idlang;

    public Adcontent() {
    }

	
    public Adcontent(AdcontentId id) {
        this.id = id;
    }
    public Adcontent(AdcontentId id, String addesc, String adurl, String imageurl, String caption, String type, String geoLongitude, String geoLatitude, String adcateg, String adtype, String idlang) {
       this.id = id;
       this.addesc = addesc;
       this.adurl = adurl;
       this.imageurl = imageurl;
       this.caption = caption;
       this.type = type;
       this.geoLongitude = geoLongitude;
       this.geoLatitude = geoLatitude;
       this.adcateg = adcateg;
       this.adtype = adtype;
       this.idlang = idlang;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="adcode", column=@Column(name="ADCODE", nullable=false, length=20) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=200) ) } )
    public AdcontentId getId() {
        return this.id;
    }
    
    public void setId(AdcontentId id) {
        this.id = id;
    }

    
    @Column(name="ADDESC", length=500)
    public String getAddesc() {
        return this.addesc;
    }
    
    public void setAddesc(String addesc) {
        this.addesc = addesc;
    }

    
    @Column(name="ADURL", length=500)
    public String getAdurl() {
        return this.adurl;
    }
    
    public void setAdurl(String adurl) {
        this.adurl = adurl;
    }

    
    @Column(name="IMAGEURL", length=50)
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    
    @Column(name="CAPTION", length=50)
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }

    
    @Column(name="TYPE", length=1)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="GEO_LONGITUDE", length=20)
    public String getGeoLongitude() {
        return this.geoLongitude;
    }
    
    public void setGeoLongitude(String geoLongitude) {
        this.geoLongitude = geoLongitude;
    }

    
    @Column(name="GEO_LATITUDE", length=20)
    public String getGeoLatitude() {
        return this.geoLatitude;
    }
    
    public void setGeoLatitude(String geoLatitude) {
        this.geoLatitude = geoLatitude;
    }

    
    @Column(name="ADCATEG", length=2)
    public String getAdcateg() {
        return this.adcateg;
    }
    
    public void setAdcateg(String adcateg) {
        this.adcateg = adcateg;
    }

    
    @Column(name="ADTYPE", length=2)
    public String getAdtype() {
        return this.adtype;
    }
    
    public void setAdtype(String adtype) {
        this.adtype = adtype;
    }

    
    @Column(name="IDLANG", length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }




}


