package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlertMsgQueue generated by hbm2java
 */
@Entity
@Table(name="ALERT_MSG_QUEUE"
    ,schema="FCDBADMIN_RK"
)
public class AlertMsgQueue  implements java.io.Serializable {


     private long idmessage;
     private String idalert;
     private String idnotifier;
     private Date datcreated;
     private String subject;
     private String address;
     private Byte maxNbrRetry;
     private Byte nbrRetried;
     private Long retryInterval;
     private Date retryDateTime;
     private Character msgstatus;
     private Boolean msgpriority;
     private String copyaddress;
     private Date datexpiry;
     private String fromaddress;
     private String uniqueid;
     private Date datsent;
     private Blob message;
     private String idEntity;

    public AlertMsgQueue() {
    }

	
    public AlertMsgQueue(long idmessage) {
        this.idmessage = idmessage;
    }
    public AlertMsgQueue(long idmessage, String idalert, String idnotifier, Date datcreated, String subject, String address, Byte maxNbrRetry, Byte nbrRetried, Long retryInterval, Date retryDateTime, Character msgstatus, Boolean msgpriority, String copyaddress, Date datexpiry, String fromaddress, String uniqueid, Date datsent, Blob message, String idEntity) {
       this.idmessage = idmessage;
       this.idalert = idalert;
       this.idnotifier = idnotifier;
       this.datcreated = datcreated;
       this.subject = subject;
       this.address = address;
       this.maxNbrRetry = maxNbrRetry;
       this.nbrRetried = nbrRetried;
       this.retryInterval = retryInterval;
       this.retryDateTime = retryDateTime;
       this.msgstatus = msgstatus;
       this.msgpriority = msgpriority;
       this.copyaddress = copyaddress;
       this.datexpiry = datexpiry;
       this.fromaddress = fromaddress;
       this.uniqueid = uniqueid;
       this.datsent = datsent;
       this.message = message;
       this.idEntity = idEntity;
    }
   
     @Id 

    
    @Column(name="IDMESSAGE", unique=true, nullable=false, precision=18, scale=0)
    public long getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(long idmessage) {
        this.idmessage = idmessage;
    }

    
    @Column(name="IDALERT", length=50)
    public String getIdalert() {
        return this.idalert;
    }
    
    public void setIdalert(String idalert) {
        this.idalert = idalert;
    }

    
    @Column(name="IDNOTIFIER", length=50)
    public String getIdnotifier() {
        return this.idnotifier;
    }
    
    public void setIdnotifier(String idnotifier) {
        this.idnotifier = idnotifier;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="SUBJECT")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="MAX_NBR_RETRY", precision=2, scale=0)
    public Byte getMaxNbrRetry() {
        return this.maxNbrRetry;
    }
    
    public void setMaxNbrRetry(Byte maxNbrRetry) {
        this.maxNbrRetry = maxNbrRetry;
    }

    
    @Column(name="NBR_RETRIED", precision=2, scale=0)
    public Byte getNbrRetried() {
        return this.nbrRetried;
    }
    
    public void setNbrRetried(Byte nbrRetried) {
        this.nbrRetried = nbrRetried;
    }

    
    @Column(name="RETRY_INTERVAL", precision=15, scale=0)
    public Long getRetryInterval() {
        return this.retryInterval;
    }
    
    public void setRetryInterval(Long retryInterval) {
        this.retryInterval = retryInterval;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RETRY_DATE_TIME", length=7)
    public Date getRetryDateTime() {
        return this.retryDateTime;
    }
    
    public void setRetryDateTime(Date retryDateTime) {
        this.retryDateTime = retryDateTime;
    }

    
    @Column(name="MSGSTATUS", length=1)
    public Character getMsgstatus() {
        return this.msgstatus;
    }
    
    public void setMsgstatus(Character msgstatus) {
        this.msgstatus = msgstatus;
    }

    
    @Column(name="MSGPRIORITY", precision=1, scale=0)
    public Boolean getMsgpriority() {
        return this.msgpriority;
    }
    
    public void setMsgpriority(Boolean msgpriority) {
        this.msgpriority = msgpriority;
    }

    
    @Column(name="COPYADDRESS")
    public String getCopyaddress() {
        return this.copyaddress;
    }
    
    public void setCopyaddress(String copyaddress) {
        this.copyaddress = copyaddress;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEXPIRY", length=7)
    public Date getDatexpiry() {
        return this.datexpiry;
    }
    
    public void setDatexpiry(Date datexpiry) {
        this.datexpiry = datexpiry;
    }

    
    @Column(name="FROMADDRESS")
    public String getFromaddress() {
        return this.fromaddress;
    }
    
    public void setFromaddress(String fromaddress) {
        this.fromaddress = fromaddress;
    }

    
    @Column(name="UNIQUEID", length=100)
    public String getUniqueid() {
        return this.uniqueid;
    }
    
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATSENT", length=7)
    public Date getDatsent() {
        return this.datsent;
    }
    
    public void setDatsent(Date datsent) {
        this.datsent = datsent;
    }

    
    @Column(name="MESSAGE")
    public Blob getMessage() {
        return this.message;
    }
    
    public void setMessage(Blob message) {
        this.message = message;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }




}


