package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Appldata generated by hbm2java
 */
@Entity
@Table(name = "APPLDATA", schema = "FCDBADMIN_RK")
public class Appldata implements java.io.Serializable {

	private AppldataId id;
	private String valuestring;
	private Character loadflag;
	private Character istranslatable;
	private String comments;

	public Appldata() {
	}

	public Appldata(AppldataId id) {
		this.id = id;
	}

	public Appldata(AppldataId id, String valuestring, Character loadflag, Character istranslatable, String comments) {
		this.id = id;
		this.valuestring = valuestring;
		this.loadflag = loadflag;
		this.istranslatable = istranslatable;
		this.comments = comments;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idapp", column = @Column(name = "IDAPP", nullable = false, length = 2)),
			@AttributeOverride(name = "dataname", column = @Column(name = "DATANAME", nullable = false, length = 40)),
			@AttributeOverride(name = "datavalue", column = @Column(name = "DATAVALUE", nullable = false, length = 100)),
			@AttributeOverride(name = "idlang", column = @Column(name = "IDLANG", nullable = false, length = 3)),
			@AttributeOverride(name = "iddevice", column = @Column(name = "IDDEVICE", nullable = false, length = 2)) })
	public AppldataId getId() {
		return this.id;
	}

	public void setId(AppldataId id) {
		this.id = id;
	}

	@Column(name = "VALUESTRING", length = 4000)
	public String getValuestring() {
		return this.valuestring;
	}

	public void setValuestring(String valuestring) {
		this.valuestring = valuestring;
	}

	@Column(name = "LOADFLAG", length = 1)
	public Character getLoadflag() {
		return this.loadflag;
	}

	public void setLoadflag(Character loadflag) {
		this.loadflag = loadflag;
	}

	@Column(name = "ISTRANSLATABLE", length = 1)
	public Character getIstranslatable() {
		return this.istranslatable;
	}

	public void setIstranslatable(Character istranslatable) {
		this.istranslatable = istranslatable;
	}

	@Column(name = "COMMENTS", length = 4000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
