package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditlog generated by hbm2java
 */
@Entity
@Table(name="AUDITLOG"
    ,schema="FCDBADMIN_RK"
)
public class Auditlog  implements java.io.Serializable {


     private long idseq;
     private String idlang;
     private String iddevice;
     private String idapp;
     private String idtxn;
     private String numsequence;
     private String iduser;
     private Date dattxn;
     private String txndesc;
     private Boolean returncode;
     private String errorcode;
     private String auditrequest;
     private Blob auditresponse;
     private String idcust;
     private String remoteaddress;
     private String idsession;
     private Character flgprocessed;
     private String idrequest;
     private String usertype;
     private String identity;
     private String idchanneluser;
     private String idselected;
     private Date dattxnstart;
     private String idjvm;
     private String sourceaddress;
     private String hdrReferrer;
     private String hdrUseragent;
     private String hdrAcceptlang;
     private String hdrXfwdfor;
     private String hdrOs;
     private String hdrAcceptencoding;
     private String logHash;

    public Auditlog() {
    }

	
    public Auditlog(long idseq) {
        this.idseq = idseq;
    }
    public Auditlog(long idseq, String idlang, String iddevice, String idapp, String idtxn, String numsequence, String iduser, Date dattxn, String txndesc, Boolean returncode, String errorcode, String auditrequest, Blob auditresponse, String idcust, String remoteaddress, String idsession, Character flgprocessed, String idrequest, String usertype, String identity, String idchanneluser, String idselected, Date dattxnstart, String idjvm, String sourceaddress, String hdrReferrer, String hdrUseragent, String hdrAcceptlang, String hdrXfwdfor, String hdrOs, String hdrAcceptencoding, String logHash) {
       this.idseq = idseq;
       this.idlang = idlang;
       this.iddevice = iddevice;
       this.idapp = idapp;
       this.idtxn = idtxn;
       this.numsequence = numsequence;
       this.iduser = iduser;
       this.dattxn = dattxn;
       this.txndesc = txndesc;
       this.returncode = returncode;
       this.errorcode = errorcode;
       this.auditrequest = auditrequest;
       this.auditresponse = auditresponse;
       this.idcust = idcust;
       this.remoteaddress = remoteaddress;
       this.idsession = idsession;
       this.flgprocessed = flgprocessed;
       this.idrequest = idrequest;
       this.usertype = usertype;
       this.identity = identity;
       this.idchanneluser = idchanneluser;
       this.idselected = idselected;
       this.dattxnstart = dattxnstart;
       this.idjvm = idjvm;
       this.sourceaddress = sourceaddress;
       this.hdrReferrer = hdrReferrer;
       this.hdrUseragent = hdrUseragent;
       this.hdrAcceptlang = hdrAcceptlang;
       this.hdrXfwdfor = hdrXfwdfor;
       this.hdrOs = hdrOs;
       this.hdrAcceptencoding = hdrAcceptencoding;
       this.logHash = logHash;
    }
   
     @Id 

    
    @Column(name="IDSEQ", unique=true, nullable=false, precision=15, scale=0)
    public long getIdseq() {
        return this.idseq;
    }
    
    public void setIdseq(long idseq) {
        this.idseq = idseq;
    }

    
    @Column(name="IDLANG", length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }

    
    @Column(name="IDDEVICE", length=2)
    public String getIddevice() {
        return this.iddevice;
    }
    
    public void setIddevice(String iddevice) {
        this.iddevice = iddevice;
    }

    
    @Column(name="IDAPP", length=2)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="NUMSEQUENCE", length=2)
    public String getNumsequence() {
        return this.numsequence;
    }
    
    public void setNumsequence(String numsequence) {
        this.numsequence = numsequence;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATTXN", length=7)
    public Date getDattxn() {
        return this.dattxn;
    }
    
    public void setDattxn(Date dattxn) {
        this.dattxn = dattxn;
    }

    
    @Column(name="TXNDESC", length=2000)
    public String getTxndesc() {
        return this.txndesc;
    }
    
    public void setTxndesc(String txndesc) {
        this.txndesc = txndesc;
    }

    
    @Column(name="RETURNCODE", precision=1, scale=0)
    public Boolean getReturncode() {
        return this.returncode;
    }
    
    public void setReturncode(Boolean returncode) {
        this.returncode = returncode;
    }

    
    @Column(name="ERRORCODE", length=20)
    public String getErrorcode() {
        return this.errorcode;
    }
    
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    
    @Column(name="AUDITREQUEST", length=4000)
    public String getAuditrequest() {
        return this.auditrequest;
    }
    
    public void setAuditrequest(String auditrequest) {
        this.auditrequest = auditrequest;
    }

    
    @Column(name="AUDITRESPONSE")
    public Blob getAuditresponse() {
        return this.auditresponse;
    }
    
    public void setAuditresponse(Blob auditresponse) {
        this.auditresponse = auditresponse;
    }

    
    @Column(name="IDCUST", length=30)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }

    
    @Column(name="REMOTEADDRESS", length=50)
    public String getRemoteaddress() {
        return this.remoteaddress;
    }
    
    public void setRemoteaddress(String remoteaddress) {
        this.remoteaddress = remoteaddress;
    }

    
    @Column(name="IDSESSION", length=50)
    public String getIdsession() {
        return this.idsession;
    }
    
    public void setIdsession(String idsession) {
        this.idsession = idsession;
    }

    
    @Column(name="FLGPROCESSED", length=1)
    public Character getFlgprocessed() {
        return this.flgprocessed;
    }
    
    public void setFlgprocessed(Character flgprocessed) {
        this.flgprocessed = flgprocessed;
    }

    
    @Column(name="IDREQUEST", length=10)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="USERTYPE", length=5)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    
    @Column(name="IDENTITY", length=5)
    public String getIdentity() {
        return this.identity;
    }
    
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    
    @Column(name="IDCHANNELUSER")
    public String getIdchanneluser() {
        return this.idchanneluser;
    }
    
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    
    @Column(name="IDSELECTED", length=20)
    public String getIdselected() {
        return this.idselected;
    }
    
    public void setIdselected(String idselected) {
        this.idselected = idselected;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATTXNSTART", length=7)
    public Date getDattxnstart() {
        return this.dattxnstart;
    }
    
    public void setDattxnstart(Date dattxnstart) {
        this.dattxnstart = dattxnstart;
    }

    
    @Column(name="IDJVM", length=10)
    public String getIdjvm() {
        return this.idjvm;
    }
    
    public void setIdjvm(String idjvm) {
        this.idjvm = idjvm;
    }

    
    @Column(name="SOURCEADDRESS", length=50)
    public String getSourceaddress() {
        return this.sourceaddress;
    }
    
    public void setSourceaddress(String sourceaddress) {
        this.sourceaddress = sourceaddress;
    }

    
    @Column(name="HDR_REFERRER", length=2000)
    public String getHdrReferrer() {
        return this.hdrReferrer;
    }
    
    public void setHdrReferrer(String hdrReferrer) {
        this.hdrReferrer = hdrReferrer;
    }

    
    @Column(name="HDR_USERAGENT", length=2000)
    public String getHdrUseragent() {
        return this.hdrUseragent;
    }
    
    public void setHdrUseragent(String hdrUseragent) {
        this.hdrUseragent = hdrUseragent;
    }

    
    @Column(name="HDR_ACCEPTLANG", length=2000)
    public String getHdrAcceptlang() {
        return this.hdrAcceptlang;
    }
    
    public void setHdrAcceptlang(String hdrAcceptlang) {
        this.hdrAcceptlang = hdrAcceptlang;
    }

    
    @Column(name="HDR_XFWDFOR", length=2000)
    public String getHdrXfwdfor() {
        return this.hdrXfwdfor;
    }
    
    public void setHdrXfwdfor(String hdrXfwdfor) {
        this.hdrXfwdfor = hdrXfwdfor;
    }

    
    @Column(name="HDR_OS", length=2000)
    public String getHdrOs() {
        return this.hdrOs;
    }
    
    public void setHdrOs(String hdrOs) {
        this.hdrOs = hdrOs;
    }

    
    @Column(name="HDR_ACCEPTENCODING", length=2000)
    public String getHdrAcceptencoding() {
        return this.hdrAcceptencoding;
    }
    
    public void setHdrAcceptencoding(String hdrAcceptencoding) {
        this.hdrAcceptencoding = hdrAcceptencoding;
    }

    
    @Column(name="LOG_HASH", length=56)
    public String getLogHash() {
        return this.logHash;
    }
    
    public void setLogHash(String logHash) {
        this.logHash = logHash;
    }




}


