package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Batchtemplateimpl generated by hbm2java
 */
@Entity
@Table(name="BATCHTEMPLATEIMPL"
    ,schema="FCDBADMIN_RK"
)
public class Batchtemplateimpl  implements java.io.Serializable {


     private BatchtemplateimplId id;
     private TxnDataMaster txnDataMaster;
     private String token1;
     private String token2;

    public Batchtemplateimpl() {
    }

	
    public Batchtemplateimpl(BatchtemplateimplId id) {
        this.id = id;
    }
    public Batchtemplateimpl(BatchtemplateimplId id, TxnDataMaster txnDataMaster, String token1, String token2) {
       this.id = id;
       this.txnDataMaster = txnDataMaster;
       this.token1 = token1;
       this.token2 = token2;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="implementationid", column=@Column(name="IMPLEMENTATIONID", nullable=false) ), 
        @AttributeOverride(name="fieldname", column=@Column(name="FIELDNAME", nullable=false, length=50) ), 
        @AttributeOverride(name="fieldindex", column=@Column(name="FIELDINDEX", nullable=false, precision=3, scale=0) ) } )
    public BatchtemplateimplId getId() {
        return this.id;
    }
    
    public void setId(BatchtemplateimplId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREQUEST")
    public TxnDataMaster getTxnDataMaster() {
        return this.txnDataMaster;
    }
    
    public void setTxnDataMaster(TxnDataMaster txnDataMaster) {
        this.txnDataMaster = txnDataMaster;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }




}


