package com.jmr.obdx.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BeneficiaryM generated by hbm2java
 */
@Entity
@Table(name="BENEFICIARY_M"
    ,schema="JMR_OBDX"
)
public class BeneficiaryM  implements java.io.Serializable {


     private long id;
     private BranchM branchDetailsM;
/*     private RetailCustomer retailCustomer;
*/   private String   retailCustomer;
     private String payyename;
     private String accountname;
     private String nickname;
     private Long accountnumber;
     private String isactive;
     private Date registrationdate;
     private Long swiftCode;
     private Long ncc;
     private String transfervai;
     private Set<FundTransfer> fundTransfers = new HashSet<FundTransfer>(0);


    public BeneficiaryM() {
    }

	
    public BeneficiaryM(long id) {
        this.id = id;
    }
    public BeneficiaryM( BranchM branchDetailsM, String retailCustomer, String payyename, String accountname, String nickname, Long accountnumber, String isactive, Date registrationdate, Long swiftCode, Long ncc, String transfervai,Set<FundTransfer> fundTransfers) {
       this.branchDetailsM = branchDetailsM;
       this.retailCustomer = retailCustomer;
       this.payyename = payyename;
       this.accountname = accountname;
       this.nickname = nickname;
       this.accountnumber = accountnumber;
       this.isactive = isactive;
       this.registrationdate = registrationdate;
       this.swiftCode = swiftCode;
       this.ncc = ncc;
       this.transfervai = transfervai;
       this.fundTransfers = fundTransfers;

    }
    public BeneficiaryM( BranchM branchDetailsM, String retailCustomer, String payyename, String accountname, String nickname, Long accountnumber, String isactive, Date registrationdate, String transfervai) {
    	   this.branchDetailsM = branchDetailsM;
           this.retailCustomer = retailCustomer;
           this.payyename = payyename;
           this.accountname = accountname;
           this.nickname = nickname;
           this.accountnumber = accountnumber;
           this.isactive = isactive;
           this.registrationdate = registrationdate;
           this.transfervai = transfervai;
        }


	public BeneficiaryM(String accountname,Long accountnumber, BranchM branchDetailsM, String nickname, String payyename,
			String transfervai) {
	       this.accountname = accountname;
	       this.accountnumber = accountnumber;
	       this.branchDetailsM = branchDetailsM;
	       this.nickname = nickname;
	       this.payyename = payyename;
	       this.transfervai = transfervai;




	       
	}


	


	


	@Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BRANCH")
    public BranchM getBranchDetailsM() {
        return this.branchDetailsM;
    }
    
    public void setBranchDetailsM(BranchM branchDetailsM) {
        this.branchDetailsM = branchDetailsM;
    }

/*@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REF_USER_ID")*/
    
    @Column(name="REF_USER_ID", length=100)

    public String getRetailCustomer() {
        return this.retailCustomer;
    }
    
    public void setRetailCustomer(String retailCustomer) {
        this.retailCustomer = retailCustomer;
    }

    
    @Column(name="PAYYENAME", length=100)
    public String getPayyename() {
        return this.payyename;
    }
    
    public void setPayyename(String payyename) {
        this.payyename = payyename;
    }

    
    @Column(name="ACCOUNTNAME", precision=100, scale=0)
    public String getAccountname() {
        return this.accountname;
    }
    
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }

    
    @Column(name="NICKNAME", length=100)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    
    @Column(name="ACCOUNTNUMBER", precision=100, scale=0)
    public Long getAccountnumber() {
        return this.accountnumber;
    }
    
    public void setAccountnumber(Long accountnumber) {
        this.accountnumber = accountnumber;
    }

    
    @Column(name="ISACTIVE", length=100)
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    
  
    @Column(name="TRANSFER_VIA", length=100)
    public String getTransfervai() {
		return transfervai;
	}
	public void setTransfervai(String transfervai) {
		this.transfervai = transfervai;
	}


	@Temporal(TemporalType.DATE)
    @Column(name="REGISTRATIONDATE", length=7)
    public Date getRegistrationdate() {
        return this.registrationdate;
    }
    
    public void setRegistrationdate(Date registrationdate) {
        this.registrationdate = registrationdate;
    }

    
    @Column(name="SWIFT_CODE", precision=100, scale=0)
    public Long getSwiftCode() {
        return this.swiftCode;
    }
    
    public void setSwiftCode(Long swiftCode) {
        this.swiftCode = swiftCode;
    }

    
    @Column(name="NCC", precision=100, scale=0)
    public Long getNcc() {
        return this.ncc;
    }
    
    public void setNcc(Long ncc) {
        this.ncc = ncc;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="beneficiaryM")
    public Set<FundTransfer> getFundTransfers() {
        return this.fundTransfers;
    }
    
    public void setFundTransfers(Set<FundTransfer> fundTransfers) {
        this.fundTransfers = fundTransfers;
    }


}


