package com.jmr.obdx.domain;
//Generated Jun 8, 2017 3:35:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BranchDetailsM generated by hbm2java
 */
@Entity
@Table(name="BRANCH_DETAILS_M"
    ,schema="JMR_OBDX"
)
public class BranchDetailsM  implements java.io.Serializable {


     private long id;
     private TransferType transferType;
     private String name;
     private String branchCod;
     private String address;
     private long contactInfo;
     private String city;
     private String processingMode;
     private String isactive;
     private Date createdDate;

    public BranchDetailsM() {
    }

	
    public BranchDetailsM(long id) {
        this.id = id;
    }
    public BranchDetailsM(long id, TransferType transferType, String name, String branchCod, String address, long contactInfo, String city, String processingMode, String isactive, Date createdDate) {
       this.id = id;
       this.transferType = transferType;
       this.name = name;
       this.branchCod = branchCod;
       this.address = address;
       this.contactInfo = contactInfo;
       this.city = city;
       this.processingMode = processingMode;
       this.isactive = isactive;
       this.createdDate = createdDate;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REF_TRANSFER_TYPE_ID")
    public TransferType getTransferType() {
        return this.transferType;
    }
    
    public void setTransferType(TransferType transferType) {
        this.transferType = transferType;
    }

    
    @Column(name="Name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="BRANCH_COD", length=100)
    public String getBranchCod() {
        return this.branchCod;
    }
    
    public void setBranchCod(String branchCod) {
        this.branchCod = branchCod;
    }

    
    @Column(name="ADDRESS", length=1000)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CONTACT_INFO", precision=22, scale=0)
    public long getContactInfo() {
        return this.contactInfo;
    }
    
    public void setContactInfo(long contactInfo) {
        this.contactInfo = contactInfo;
    }

    
    @Column(name="CITY", length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="PROCESSING_MODE", length=10)
    public String getProcessingMode() {
        return this.processingMode;
    }
    
    public void setProcessingMode(String processingMode) {
        this.processingMode = processingMode;
    }

    
    @Column(name="ISACTIVE", length=10)
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATE", length=7)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}







