package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Btacctmap generated by hbm2java
 */
@Entity
@Table(name="BTACCTMAP"
    ,schema="FCDBADMIN_RK"
)
public class Btacctmap  implements java.io.Serializable {


     private BtacctmapId id;
     private Btcustreg btcustreg;
     private String token1;
     private String token2;
     private String codbranch;

    public Btacctmap() {
    }

	
    public Btacctmap(BtacctmapId id, Btcustreg btcustreg) {
        this.id = id;
        this.btcustreg = btcustreg;
    }
    public Btacctmap(BtacctmapId id, Btcustreg btcustreg, String token1, String token2, String codbranch) {
       this.id = id;
       this.btcustreg = btcustreg;
       this.token1 = token1;
       this.token2 = token2;
       this.codbranch = codbranch;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="idaccount", column=@Column(name="IDACCOUNT", nullable=false, length=35) ) } )
    public BtacctmapId getId() {
        return this.id;
    }
    
    public void setId(BtacctmapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BTID", nullable=false, insertable=false, updatable=false)
    public Btcustreg getBtcustreg() {
        return this.btcustreg;
    }
    
    public void setBtcustreg(Btcustreg btcustreg) {
        this.btcustreg = btcustreg;
    }

    
    @Column(name="TOKEN1", length=50)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=50)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="CODBRANCH", length=5)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }




}


