package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Btcontrolmsg generated by hbm2java
 */
@Entity
@Table(name="BTCONTROLMSG"
    ,schema="FCDBADMIN_RK"
)
public class Btcontrolmsg  implements java.io.Serializable {


     private BtcontrolmsgId id;
     private BigDecimal priority;
     private String logqueuname;
     private String controlmsg;
     private Date datupdated;
     private BigDecimal result;

    public Btcontrolmsg() {
    }

	
    public Btcontrolmsg(BtcontrolmsgId id) {
        this.id = id;
    }
    public Btcontrolmsg(BtcontrolmsgId id, BigDecimal priority, String logqueuname, String controlmsg, Date datupdated, BigDecimal result) {
       this.id = id;
       this.priority = priority;
       this.logqueuname = logqueuname;
       this.controlmsg = controlmsg;
       this.datupdated = datupdated;
       this.result = result;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="filerefno", column=@Column(name="FILEREFNO", nullable=false, length=35) ), 
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="currstep", column=@Column(name="CURRSTEP", nullable=false, length=20) ), 
        @AttributeOverride(name="nextstep", column=@Column(name="NEXTSTEP", nullable=false, length=20) ), 
        @AttributeOverride(name="recordrefno", column=@Column(name="RECORDREFNO", nullable=false, length=35) ) } )
    public BtcontrolmsgId getId() {
        return this.id;
    }
    
    public void setId(BtcontrolmsgId id) {
        this.id = id;
    }

    
    @Column(name="PRIORITY", precision=38, scale=0)
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    
    @Column(name="LOGQUEUNAME", length=35)
    public String getLogqueuname() {
        return this.logqueuname;
    }
    
    public void setLogqueuname(String logqueuname) {
        this.logqueuname = logqueuname;
    }

    
    @Column(name="CONTROLMSG", length=2000)
    public String getControlmsg() {
        return this.controlmsg;
    }
    
    public void setControlmsg(String controlmsg) {
        this.controlmsg = controlmsg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPDATED", length=7)
    public Date getDatupdated() {
        return this.datupdated;
    }
    
    public void setDatupdated(Date datupdated) {
        this.datupdated = datupdated;
    }

    
    @Column(name="RESULT", precision=38, scale=0)
    public BigDecimal getResult() {
        return this.result;
    }
    
    public void setResult(BigDecimal result) {
        this.result = result;
    }




}


