package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Btfileinfo generated by hbm2java
 */
@Entity
@Table(name="BTFILEINFO"
    ,schema="FCDBADMIN_RK"
)
public class Btfileinfo  implements java.io.Serializable {


     private String filerefno;
     private String btid;
     private String filename;
     private Date datupload;
     private Date datvalue;
     private String iduser;
     private String status;
     private BigDecimal filesize;
     private String drnarrative;
     private Date datsend;
     private String mnemonicCode;
     private BigDecimal responseresult;
     private Character iss2s;
     private Blob msg;
     private String encodingtype;
     private BigDecimal convrate;
     private String convtype;
     private String convrefno;
     private String filehashvalue;
     private String idEntity;
     private String lastCashinDownloadId;
     private Serializable lastCashinDownloadTime;
     private Blob cashinFile;

    public Btfileinfo() {
    }

	
    public Btfileinfo(String filerefno) {
        this.filerefno = filerefno;
    }
    public Btfileinfo(String filerefno, String btid, String filename, Date datupload, Date datvalue, String iduser, String status, BigDecimal filesize, String drnarrative, Date datsend, String mnemonicCode, BigDecimal responseresult, Character iss2s, Blob msg, String encodingtype, BigDecimal convrate, String convtype, String convrefno, String filehashvalue, String idEntity, String lastCashinDownloadId, Serializable lastCashinDownloadTime, Blob cashinFile) {
       this.filerefno = filerefno;
       this.btid = btid;
       this.filename = filename;
       this.datupload = datupload;
       this.datvalue = datvalue;
       this.iduser = iduser;
       this.status = status;
       this.filesize = filesize;
       this.drnarrative = drnarrative;
       this.datsend = datsend;
       this.mnemonicCode = mnemonicCode;
       this.responseresult = responseresult;
       this.iss2s = iss2s;
       this.msg = msg;
       this.encodingtype = encodingtype;
       this.convrate = convrate;
       this.convtype = convtype;
       this.convrefno = convrefno;
       this.filehashvalue = filehashvalue;
       this.idEntity = idEntity;
       this.lastCashinDownloadId = lastCashinDownloadId;
       this.lastCashinDownloadTime = lastCashinDownloadTime;
       this.cashinFile = cashinFile;
    }
   
     @Id 

    
    @Column(name="FILEREFNO", unique=true, nullable=false, length=35)
    public String getFilerefno() {
        return this.filerefno;
    }
    
    public void setFilerefno(String filerefno) {
        this.filerefno = filerefno;
    }

    
    @Column(name="BTID", length=40)
    public String getBtid() {
        return this.btid;
    }
    
    public void setBtid(String btid) {
        this.btid = btid;
    }

    
    @Column(name="FILENAME")
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPLOAD", length=7)
    public Date getDatupload() {
        return this.datupload;
    }
    
    public void setDatupload(Date datupload) {
        this.datupload = datupload;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATVALUE", length=7)
    public Date getDatvalue() {
        return this.datvalue;
    }
    
    public void setDatvalue(Date datvalue) {
        this.datvalue = datvalue;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="FILESIZE", precision=22, scale=0)
    public BigDecimal getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(BigDecimal filesize) {
        this.filesize = filesize;
    }

    
    @Column(name="DRNARRATIVE")
    public String getDrnarrative() {
        return this.drnarrative;
    }
    
    public void setDrnarrative(String drnarrative) {
        this.drnarrative = drnarrative;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATSEND", length=7)
    public Date getDatsend() {
        return this.datsend;
    }
    
    public void setDatsend(Date datsend) {
        this.datsend = datsend;
    }

    
    @Column(name="MNEMONIC_CODE", length=20)
    public String getMnemonicCode() {
        return this.mnemonicCode;
    }
    
    public void setMnemonicCode(String mnemonicCode) {
        this.mnemonicCode = mnemonicCode;
    }

    
    @Column(name="RESPONSERESULT", precision=38, scale=0)
    public BigDecimal getResponseresult() {
        return this.responseresult;
    }
    
    public void setResponseresult(BigDecimal responseresult) {
        this.responseresult = responseresult;
    }

    
    @Column(name="ISS2S", length=1)
    public Character getIss2s() {
        return this.iss2s;
    }
    
    public void setIss2s(Character iss2s) {
        this.iss2s = iss2s;
    }

    
    @Column(name="MSG")
    public Blob getMsg() {
        return this.msg;
    }
    
    public void setMsg(Blob msg) {
        this.msg = msg;
    }

    
    @Column(name="ENCODINGTYPE", length=20)
    public String getEncodingtype() {
        return this.encodingtype;
    }
    
    public void setEncodingtype(String encodingtype) {
        this.encodingtype = encodingtype;
    }

    
    @Column(name="CONVRATE", precision=22, scale=0)
    public BigDecimal getConvrate() {
        return this.convrate;
    }
    
    public void setConvrate(BigDecimal convrate) {
        this.convrate = convrate;
    }

    
    @Column(name="CONVTYPE", length=1)
    public String getConvtype() {
        return this.convtype;
    }
    
    public void setConvtype(String convtype) {
        this.convtype = convtype;
    }

    
    @Column(name="CONVREFNO", length=20)
    public String getConvrefno() {
        return this.convrefno;
    }
    
    public void setConvrefno(String convrefno) {
        this.convrefno = convrefno;
    }

    
    @Column(name="FILEHASHVALUE")
    public String getFilehashvalue() {
        return this.filehashvalue;
    }
    
    public void setFilehashvalue(String filehashvalue) {
        this.filehashvalue = filehashvalue;
    }

    
    @Column(name="ID_ENTITY", length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="LAST_CASHIN_DOWNLOAD_ID", length=35)
    public String getLastCashinDownloadId() {
        return this.lastCashinDownloadId;
    }
    
    public void setLastCashinDownloadId(String lastCashinDownloadId) {
        this.lastCashinDownloadId = lastCashinDownloadId;
    }

    
    @Column(name="LAST_CASHIN_DOWNLOAD_TIME")
    public Serializable getLastCashinDownloadTime() {
        return this.lastCashinDownloadTime;
    }
    
    public void setLastCashinDownloadTime(Serializable lastCashinDownloadTime) {
        this.lastCashinDownloadTime = lastCashinDownloadTime;
    }

    
    @Column(name="CASHIN_FILE")
    public Blob getCashinFile() {
        return this.cashinFile;
    }
    
    public void setCashinFile(Blob cashinFile) {
        this.cashinFile = cashinFile;
    }




}


