package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Btfileinfodet generated by hbm2java
 */
@Entity
@Table(name="BTFILEINFODET"
    ,schema="FCDBADMIN_RK"
)
public class Btfileinfodet  implements java.io.Serializable {


     private BtfileinfodetId id;
     private Date datupdated;
     private Blob filecontents;
     private Blob modifiedfilecontents;

    public Btfileinfodet() {
    }

	
    public Btfileinfodet(BtfileinfodetId id) {
        this.id = id;
    }
    public Btfileinfodet(BtfileinfodetId id, Date datupdated, Blob filecontents, Blob modifiedfilecontents) {
       this.id = id;
       this.datupdated = datupdated;
       this.filecontents = filecontents;
       this.modifiedfilecontents = modifiedfilecontents;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="filerefno", column=@Column(name="FILEREFNO", nullable=false, length=35) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false, length=20) ) } )
    public BtfileinfodetId getId() {
        return this.id;
    }
    
    public void setId(BtfileinfodetId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPDATED", length=7)
    public Date getDatupdated() {
        return this.datupdated;
    }
    
    public void setDatupdated(Date datupdated) {
        this.datupdated = datupdated;
    }

    
    @Column(name="FILECONTENTS")
    public Blob getFilecontents() {
        return this.filecontents;
    }
    
    public void setFilecontents(Blob filecontents) {
        this.filecontents = filecontents;
    }

    
    @Column(name="MODIFIEDFILECONTENTS")
    public Blob getModifiedfilecontents() {
        return this.modifiedfilecontents;
    }
    
    public void setModifiedfilecontents(Blob modifiedfilecontents) {
        this.modifiedfilecontents = modifiedfilecontents;
    }




}


