package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Btidextacctmap generated by hbm2java
 */
@Entity
@Table(name="BTIDEXTACCTMAP"
    ,schema="FCDBADMIN_RK"
)
public class Btidextacctmap  implements java.io.Serializable {


     private BtidextacctmapId id;
     private String namaccount;
     private String token1;
     private String token2;

    public Btidextacctmap() {
    }

	
    public Btidextacctmap(BtidextacctmapId id) {
        this.id = id;
    }
    public Btidextacctmap(BtidextacctmapId id, String namaccount, String token1, String token2) {
       this.id = id;
       this.namaccount = namaccount;
       this.token1 = token1;
       this.token2 = token2;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="idaccount", column=@Column(name="IDACCOUNT", nullable=false, length=35) ), 
        @AttributeOverride(name="nscaccount", column=@Column(name="NSCACCOUNT", nullable=false, length=11) ) } )
    public BtidextacctmapId getId() {
        return this.id;
    }
    
    public void setId(BtidextacctmapId id) {
        this.id = id;
    }

    
    @Column(name="NAMACCOUNT", length=50)
    public String getNamaccount() {
        return this.namaccount;
    }
    
    public void setNamaccount(String namaccount) {
        this.namaccount = namaccount;
    }

    
    @Column(name="TOKEN1", length=250)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=250)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }




}


