package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Btidcustentitymap generated by hbm2java
 */
@Entity
@Table(name="BTIDCUSTENTITYMAP"
    ,schema="FCDBADMIN_RK"
)
public class Btidcustentitymap  implements java.io.Serializable {


     private BtidcustentitymapId id;
     private Btcustreg btcustreg;
     private String custgroupid;
     private String idEntity;

    public Btidcustentitymap() {
    }

	
    public Btidcustentitymap(BtidcustentitymapId id, Btcustreg btcustreg) {
        this.id = id;
        this.btcustreg = btcustreg;
    }
    public Btidcustentitymap(BtidcustentitymapId id, Btcustreg btcustreg, String custgroupid, String idEntity) {
       this.id = id;
       this.btcustreg = btcustreg;
       this.custgroupid = custgroupid;
       this.idEntity = idEntity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="btid", column=@Column(name="BTID", nullable=false, length=40) ), 
        @AttributeOverride(name="refIdEntity", column=@Column(name="REF_ID_ENTITY", nullable=false, length=4) ) } )
    public BtidcustentitymapId getId() {
        return this.id;
    }
    
    public void setId(BtidcustentitymapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BTID", nullable=false, insertable=false, updatable=false)
    public Btcustreg getBtcustreg() {
        return this.btcustreg;
    }
    
    public void setBtcustreg(Btcustreg btcustreg) {
        this.btcustreg = btcustreg;
    }

    
    @Column(name="CUSTGROUPID", length=20)
    public String getCustgroupid() {
        return this.custgroupid;
    }
    
    public void setCustgroupid(String custgroupid) {
        this.custgroupid = custgroupid;
    }

    
    @Column(name="ID_ENTITY", length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }




}


