package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Btqueuesetup generated by hbm2java
 */
@Entity
@Table(name="BTQUEUESETUP"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"LOGQUEUENAME", "PRIORITY", "JVMID"}) 
)
public class Btqueuesetup  implements java.io.Serializable {


     private BtqueuesetupId id;
     private BigDecimal priority;
     private String jndiprovider;
     private String providerurl;
     private Short jvmid;

    public Btqueuesetup() {
    }

	
    public Btqueuesetup(BtqueuesetupId id) {
        this.id = id;
    }
    public Btqueuesetup(BtqueuesetupId id, BigDecimal priority, String jndiprovider, String providerurl, Short jvmid) {
       this.id = id;
       this.priority = priority;
       this.jndiprovider = jndiprovider;
       this.providerurl = providerurl;
       this.jvmid = jvmid;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="logqueuename", column=@Column(name="LOGQUEUENAME", nullable=false, length=35) ), 
        @AttributeOverride(name="queueconnfactory", column=@Column(name="QUEUECONNFACTORY", nullable=false, length=35) ), 
        @AttributeOverride(name="phyqueuename", column=@Column(name="PHYQUEUENAME", nullable=false, length=35) ) } )
    public BtqueuesetupId getId() {
        return this.id;
    }
    
    public void setId(BtqueuesetupId id) {
        this.id = id;
    }

    
    @Column(name="PRIORITY", precision=22, scale=0)
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    
    @Column(name="JNDIPROVIDER")
    public String getJndiprovider() {
        return this.jndiprovider;
    }
    
    public void setJndiprovider(String jndiprovider) {
        this.jndiprovider = jndiprovider;
    }

    
    @Column(name="PROVIDERURL")
    public String getProviderurl() {
        return this.providerurl;
    }
    
    public void setProviderurl(String providerurl) {
        this.providerurl = providerurl;
    }

    
    @Column(name="JVMID", precision=3, scale=0)
    public Short getJvmid() {
        return this.jvmid;
    }
    
    public void setJvmid(Short jvmid) {
        this.jvmid = jvmid;
    }




}


