package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bttxntype generated by hbm2java
 */
@Entity
@Table(name="BTTXNTYPE"
    ,schema="FCDBADMIN_RK"
)
public class Bttxntype  implements java.io.Serializable {


     private BttxntypeId id;
     private String beneType;
     private Character emailReqd;
     private String transTypeFlag;
     private String mnemonic;
     private String ismixed;
     private String ismixedsymbol;
     private String operationmode;
     private String paycode;
     private String hndoffrqd;
     private String loadflag;
     private String allowedIdtxns;

    public Bttxntype() {
    }

	
    public Bttxntype(BttxntypeId id) {
        this.id = id;
    }
    public Bttxntype(BttxntypeId id, String beneType, Character emailReqd, String transTypeFlag, String mnemonic, String ismixed, String ismixedsymbol, String operationmode, String paycode, String hndoffrqd, String loadflag, String allowedIdtxns) {
       this.id = id;
       this.beneType = beneType;
       this.emailReqd = emailReqd;
       this.transTypeFlag = transTypeFlag;
       this.mnemonic = mnemonic;
       this.ismixed = ismixed;
       this.ismixedsymbol = ismixedsymbol;
       this.operationmode = operationmode;
       this.paycode = paycode;
       this.hndoffrqd = hndoffrqd;
       this.loadflag = loadflag;
       this.allowedIdtxns = allowedIdtxns;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idbttxn", column=@Column(name="IDBTTXN", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="codtransaction", column=@Column(name="CODTRANSACTION", nullable=false, length=2) ) } )
    public BttxntypeId getId() {
        return this.id;
    }
    
    public void setId(BttxntypeId id) {
        this.id = id;
    }

    
    @Column(name="BENE_TYPE", length=1)
    public String getBeneType() {
        return this.beneType;
    }
    
    public void setBeneType(String beneType) {
        this.beneType = beneType;
    }

    
    @Column(name="EMAIL_REQD", length=1)
    public Character getEmailReqd() {
        return this.emailReqd;
    }
    
    public void setEmailReqd(Character emailReqd) {
        this.emailReqd = emailReqd;
    }

    
    @Column(name="TRANS_TYPE_FLAG", length=1)
    public String getTransTypeFlag() {
        return this.transTypeFlag;
    }
    
    public void setTransTypeFlag(String transTypeFlag) {
        this.transTypeFlag = transTypeFlag;
    }

    
    @Column(name="MNEMONIC", length=8)
    public String getMnemonic() {
        return this.mnemonic;
    }
    
    public void setMnemonic(String mnemonic) {
        this.mnemonic = mnemonic;
    }

    
    @Column(name="ISMIXED", length=1)
    public String getIsmixed() {
        return this.ismixed;
    }
    
    public void setIsmixed(String ismixed) {
        this.ismixed = ismixed;
    }

    
    @Column(name="ISMIXEDSYMBOL", length=10)
    public String getIsmixedsymbol() {
        return this.ismixedsymbol;
    }
    
    public void setIsmixedsymbol(String ismixedsymbol) {
        this.ismixedsymbol = ismixedsymbol;
    }

    
    @Column(name="OPERATIONMODE", length=1)
    public String getOperationmode() {
        return this.operationmode;
    }
    
    public void setOperationmode(String operationmode) {
        this.operationmode = operationmode;
    }

    
    @Column(name="PAYCODE", length=6)
    public String getPaycode() {
        return this.paycode;
    }
    
    public void setPaycode(String paycode) {
        this.paycode = paycode;
    }

    
    @Column(name="HNDOFFRQD", length=1)
    public String getHndoffrqd() {
        return this.hndoffrqd;
    }
    
    public void setHndoffrqd(String hndoffrqd) {
        this.hndoffrqd = hndoffrqd;
    }

    
    @Column(name="LOADFLAG", length=1)
    public String getLoadflag() {
        return this.loadflag;
    }
    
    public void setLoadflag(String loadflag) {
        this.loadflag = loadflag;
    }

    
    @Column(name="ALLOWED_IDTXNS", length=50)
    public String getAllowedIdtxns() {
        return this.allowedIdtxns;
    }
    
    public void setAllowedIdtxns(String allowedIdtxns) {
        this.allowedIdtxns = allowedIdtxns;
    }




}


