package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BulkFtMaster generated by hbm2java
 */
@Entity
@Table(name="BULK_FT_MASTER"
    ,schema="FCDBADMIN_RK"
)
public class BulkFtMaster  implements java.io.Serializable {


     private BulkFtMasterId id;
     private String fileType;
     private Date fileDate;
     private String receiver;
     private Date fileBusinessDate;
     private Byte fileCycle;
     private String routingInd;
     private String orgFileRef;
     private String orgFileName;
     private String fileRejctCode;
     private BigDecimal totalDdbulks;
     private BigDecimal totalRejectbulks;
     private String fileStatus;
     private String errCode;
     private String errParam;
     private String fileConsolReqd;
     private String sentToHost;

    public BulkFtMaster() {
    }

	
    public BulkFtMaster(BulkFtMasterId id) {
        this.id = id;
    }
    public BulkFtMaster(BulkFtMasterId id, String fileType, Date fileDate, String receiver, Date fileBusinessDate, Byte fileCycle, String routingInd, String orgFileRef, String orgFileName, String fileRejctCode, BigDecimal totalDdbulks, BigDecimal totalRejectbulks, String fileStatus, String errCode, String errParam, String fileConsolReqd, String sentToHost) {
       this.id = id;
       this.fileType = fileType;
       this.fileDate = fileDate;
       this.receiver = receiver;
       this.fileBusinessDate = fileBusinessDate;
       this.fileCycle = fileCycle;
       this.routingInd = routingInd;
       this.orgFileRef = orgFileRef;
       this.orgFileName = orgFileName;
       this.fileRejctCode = fileRejctCode;
       this.totalDdbulks = totalDdbulks;
       this.totalRejectbulks = totalRejectbulks;
       this.fileStatus = fileStatus;
       this.errCode = errCode;
       this.errParam = errParam;
       this.fileConsolReqd = fileConsolReqd;
       this.sentToHost = sentToHost;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="serviceType", column=@Column(name="SERVICE_TYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="fileRefNo", column=@Column(name="FILE_REF_NO", nullable=false, length=40) ), 
        @AttributeOverride(name="sender", column=@Column(name="SENDER", nullable=false, length=40) ) } )
    public BulkFtMasterId getId() {
        return this.id;
    }
    
    public void setId(BulkFtMasterId id) {
        this.id = id;
    }

    
    @Column(name="FILE_TYPE", length=3)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FILE_DATE", length=7)
    public Date getFileDate() {
        return this.fileDate;
    }
    
    public void setFileDate(Date fileDate) {
        this.fileDate = fileDate;
    }

    
    @Column(name="RECEIVER", length=11)
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FILE_BUSINESS_DATE", length=7)
    public Date getFileBusinessDate() {
        return this.fileBusinessDate;
    }
    
    public void setFileBusinessDate(Date fileBusinessDate) {
        this.fileBusinessDate = fileBusinessDate;
    }

    
    @Column(name="FILE_CYCLE", precision=2, scale=0)
    public Byte getFileCycle() {
        return this.fileCycle;
    }
    
    public void setFileCycle(Byte fileCycle) {
        this.fileCycle = fileCycle;
    }

    
    @Column(name="ROUTING_IND", length=3)
    public String getRoutingInd() {
        return this.routingInd;
    }
    
    public void setRoutingInd(String routingInd) {
        this.routingInd = routingInd;
    }

    
    @Column(name="ORG_FILE_REF", length=16)
    public String getOrgFileRef() {
        return this.orgFileRef;
    }
    
    public void setOrgFileRef(String orgFileRef) {
        this.orgFileRef = orgFileRef;
    }

    
    @Column(name="ORG_FILE_NAME", length=16)
    public String getOrgFileName() {
        return this.orgFileName;
    }
    
    public void setOrgFileName(String orgFileName) {
        this.orgFileName = orgFileName;
    }

    
    @Column(name="FILE_REJCT_CODE", length=3)
    public String getFileRejctCode() {
        return this.fileRejctCode;
    }
    
    public void setFileRejctCode(String fileRejctCode) {
        this.fileRejctCode = fileRejctCode;
    }

    
    @Column(name="TOTAL_DDBULKS", precision=22, scale=0)
    public BigDecimal getTotalDdbulks() {
        return this.totalDdbulks;
    }
    
    public void setTotalDdbulks(BigDecimal totalDdbulks) {
        this.totalDdbulks = totalDdbulks;
    }

    
    @Column(name="TOTAL_REJECTBULKS", precision=22, scale=0)
    public BigDecimal getTotalRejectbulks() {
        return this.totalRejectbulks;
    }
    
    public void setTotalRejectbulks(BigDecimal totalRejectbulks) {
        this.totalRejectbulks = totalRejectbulks;
    }

    
    @Column(name="FILE_STATUS", length=1)
    public String getFileStatus() {
        return this.fileStatus;
    }
    
    public void setFileStatus(String fileStatus) {
        this.fileStatus = fileStatus;
    }

    
    @Column(name="ERR_CODE", length=11)
    public String getErrCode() {
        return this.errCode;
    }
    
    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    
    @Column(name="ERR_PARAM")
    public String getErrParam() {
        return this.errParam;
    }
    
    public void setErrParam(String errParam) {
        this.errParam = errParam;
    }

    
    @Column(name="FILE_CONSOL_REQD", length=1)
    public String getFileConsolReqd() {
        return this.fileConsolReqd;
    }
    
    public void setFileConsolReqd(String fileConsolReqd) {
        this.fileConsolReqd = fileConsolReqd;
    }

    
    @Column(name="SENT_TO_HOST", length=1)
    public String getSentToHost() {
        return this.sentToHost;
    }
    
    public void setSentToHost(String sentToHost) {
        this.sentToHost = sentToHost;
    }




}


