package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CardStatementList generated by hbm2java
 */
@Entity
@Table(name="CARD_STATEMENT_LIST"
    ,schema="FCDBADMIN_RK"
)
public class CardStatementList  implements java.io.Serializable {


     private long idstatement;
     private String nbrcard;
     private String stmtMonth;
     private String stmtYear;
     private Date duedate;
     private BigDecimal totaldues;
     private String crdr;
     private BigDecimal minamountdue;
     private BigDecimal availamount;
     private BigDecimal pastdues;
     private BigDecimal availamtinstallments;
     private BigDecimal usedamountinstallments;
     private BigDecimal ttloutstandinginstallments;
     private String statementbilled;

    public CardStatementList() {
    }

	
    public CardStatementList(long idstatement) {
        this.idstatement = idstatement;
    }
    public CardStatementList(long idstatement, String nbrcard, String stmtMonth, String stmtYear, Date duedate, BigDecimal totaldues, String crdr, BigDecimal minamountdue, BigDecimal availamount, BigDecimal pastdues, BigDecimal availamtinstallments, BigDecimal usedamountinstallments, BigDecimal ttloutstandinginstallments, String statementbilled) {
       this.idstatement = idstatement;
       this.nbrcard = nbrcard;
       this.stmtMonth = stmtMonth;
       this.stmtYear = stmtYear;
       this.duedate = duedate;
       this.totaldues = totaldues;
       this.crdr = crdr;
       this.minamountdue = minamountdue;
       this.availamount = availamount;
       this.pastdues = pastdues;
       this.availamtinstallments = availamtinstallments;
       this.usedamountinstallments = usedamountinstallments;
       this.ttloutstandinginstallments = ttloutstandinginstallments;
       this.statementbilled = statementbilled;
    }
   
     @Id 

    
    @Column(name="IDSTATEMENT", unique=true, nullable=false, precision=10, scale=0)
    public long getIdstatement() {
        return this.idstatement;
    }
    
    public void setIdstatement(long idstatement) {
        this.idstatement = idstatement;
    }

    
    @Column(name="NBRCARD", length=16)
    public String getNbrcard() {
        return this.nbrcard;
    }
    
    public void setNbrcard(String nbrcard) {
        this.nbrcard = nbrcard;
    }

    
    @Column(name="STMT_MONTH", length=5)
    public String getStmtMonth() {
        return this.stmtMonth;
    }
    
    public void setStmtMonth(String stmtMonth) {
        this.stmtMonth = stmtMonth;
    }

    
    @Column(name="STMT_YEAR", length=5)
    public String getStmtYear() {
        return this.stmtYear;
    }
    
    public void setStmtYear(String stmtYear) {
        this.stmtYear = stmtYear;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DUEDATE", length=7)
    public Date getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    
    @Column(name="TOTALDUES", precision=20, scale=4)
    public BigDecimal getTotaldues() {
        return this.totaldues;
    }
    
    public void setTotaldues(BigDecimal totaldues) {
        this.totaldues = totaldues;
    }

    
    @Column(name="CRDR", length=2)
    public String getCrdr() {
        return this.crdr;
    }
    
    public void setCrdr(String crdr) {
        this.crdr = crdr;
    }

    
    @Column(name="MINAMOUNTDUE", precision=20, scale=4)
    public BigDecimal getMinamountdue() {
        return this.minamountdue;
    }
    
    public void setMinamountdue(BigDecimal minamountdue) {
        this.minamountdue = minamountdue;
    }

    
    @Column(name="AVAILAMOUNT", precision=20, scale=4)
    public BigDecimal getAvailamount() {
        return this.availamount;
    }
    
    public void setAvailamount(BigDecimal availamount) {
        this.availamount = availamount;
    }

    
    @Column(name="PASTDUES", precision=20, scale=4)
    public BigDecimal getPastdues() {
        return this.pastdues;
    }
    
    public void setPastdues(BigDecimal pastdues) {
        this.pastdues = pastdues;
    }

    
    @Column(name="AVAILAMTINSTALLMENTS", precision=20, scale=4)
    public BigDecimal getAvailamtinstallments() {
        return this.availamtinstallments;
    }
    
    public void setAvailamtinstallments(BigDecimal availamtinstallments) {
        this.availamtinstallments = availamtinstallments;
    }

    
    @Column(name="USEDAMOUNTINSTALLMENTS", precision=20, scale=4)
    public BigDecimal getUsedamountinstallments() {
        return this.usedamountinstallments;
    }
    
    public void setUsedamountinstallments(BigDecimal usedamountinstallments) {
        this.usedamountinstallments = usedamountinstallments;
    }

    
    @Column(name="TTLOUTSTANDINGINSTALLMENTS", precision=20, scale=4)
    public BigDecimal getTtloutstandinginstallments() {
        return this.ttloutstandinginstallments;
    }
    
    public void setTtloutstandinginstallments(BigDecimal ttloutstandinginstallments) {
        this.ttloutstandinginstallments = ttloutstandinginstallments;
    }

    
    @Column(name="STATEMENTBILLED", length=1)
    public String getStatementbilled() {
        return this.statementbilled;
    }
    
    public void setStatementbilled(String statementbilled) {
        this.statementbilled = statementbilled;
    }




}


