package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CardMonthlyInstallment generated by hbm2java
 */
@Entity
@Table(name="CARD_MONTHLY_INSTALLMENT"
    ,schema="FCDBADMIN_RK"
)
public class CardMonthlyInstallment  implements java.io.Serializable {


     private long installmentid;
     private String nbrcard;
     private String benefacctno;
     private String benefbank;
     private String benefbranch;
     private String benefdetails;
     private Date startdate;
     private Date enddate;
     private BigDecimal amount;
     private Long numinstallments;
     private Long installmentsleft;
     private BigDecimal monthlyamount;
     private BigDecimal outstandingamount;

    public CardMonthlyInstallment() {
    }

	
    public CardMonthlyInstallment(long installmentid) {
        this.installmentid = installmentid;
    }
    public CardMonthlyInstallment(long installmentid, String nbrcard, String benefacctno, String benefbank, String benefbranch, String benefdetails, Date startdate, Date enddate, BigDecimal amount, Long numinstallments, Long installmentsleft, BigDecimal monthlyamount, BigDecimal outstandingamount) {
       this.installmentid = installmentid;
       this.nbrcard = nbrcard;
       this.benefacctno = benefacctno;
       this.benefbank = benefbank;
       this.benefbranch = benefbranch;
       this.benefdetails = benefdetails;
       this.startdate = startdate;
       this.enddate = enddate;
       this.amount = amount;
       this.numinstallments = numinstallments;
       this.installmentsleft = installmentsleft;
       this.monthlyamount = monthlyamount;
       this.outstandingamount = outstandingamount;
    }
   
     @Id 

    
    @Column(name="INSTALLMENTID", unique=true, nullable=false, precision=10, scale=0)
    public long getInstallmentid() {
        return this.installmentid;
    }
    
    public void setInstallmentid(long installmentid) {
        this.installmentid = installmentid;
    }

    
    @Column(name="NBRCARD", length=16)
    public String getNbrcard() {
        return this.nbrcard;
    }
    
    public void setNbrcard(String nbrcard) {
        this.nbrcard = nbrcard;
    }

    
    @Column(name="BENEFACCTNO", length=20)
    public String getBenefacctno() {
        return this.benefacctno;
    }
    
    public void setBenefacctno(String benefacctno) {
        this.benefacctno = benefacctno;
    }

    
    @Column(name="BENEFBANK")
    public String getBenefbank() {
        return this.benefbank;
    }
    
    public void setBenefbank(String benefbank) {
        this.benefbank = benefbank;
    }

    
    @Column(name="BENEFBRANCH")
    public String getBenefbranch() {
        return this.benefbranch;
    }
    
    public void setBenefbranch(String benefbranch) {
        this.benefbranch = benefbranch;
    }

    
    @Column(name="BENEFDETAILS")
    public String getBenefdetails() {
        return this.benefdetails;
    }
    
    public void setBenefdetails(String benefdetails) {
        this.benefdetails = benefdetails;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STARTDATE", length=7)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENDDATE", length=7)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    
    @Column(name="AMOUNT", precision=20, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="NUMINSTALLMENTS", precision=10, scale=0)
    public Long getNuminstallments() {
        return this.numinstallments;
    }
    
    public void setNuminstallments(Long numinstallments) {
        this.numinstallments = numinstallments;
    }

    
    @Column(name="INSTALLMENTSLEFT", precision=10, scale=0)
    public Long getInstallmentsleft() {
        return this.installmentsleft;
    }
    
    public void setInstallmentsleft(Long installmentsleft) {
        this.installmentsleft = installmentsleft;
    }

    
    @Column(name="MONTHLYAMOUNT", precision=20, scale=4)
    public BigDecimal getMonthlyamount() {
        return this.monthlyamount;
    }
    
    public void setMonthlyamount(BigDecimal monthlyamount) {
        this.monthlyamount = monthlyamount;
    }

    
    @Column(name="OUTSTANDINGAMOUNT", precision=20, scale=4)
    public BigDecimal getOutstandingamount() {
        return this.outstandingamount;
    }
    
    public void setOutstandingamount(BigDecimal outstandingamount) {
        this.outstandingamount = outstandingamount;
    }




}


