package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CardStatementDetailsId generated by hbm2java
 */
@Embeddable
public class CardStatementDetailsId  implements java.io.Serializable {


     private long statementid;
     private long recordid;

    public CardStatementDetailsId() {
    }

    public CardStatementDetailsId(long statementid, long recordid) {
       this.statementid = statementid;
       this.recordid = recordid;
    }
   


    @Column(name="STATEMENTID", nullable=false, precision=10, scale=0)
    public long getStatementid() {
        return this.statementid;
    }
    
    public void setStatementid(long statementid) {
        this.statementid = statementid;
    }


    @Column(name="RECORDID", nullable=false, precision=10, scale=0)
    public long getRecordid() {
        return this.recordid;
    }
    
    public void setRecordid(long recordid) {
        this.recordid = recordid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CardStatementDetailsId) ) return false;
		 CardStatementDetailsId castOther = ( CardStatementDetailsId ) other; 
         
		 return (this.getStatementid()==castOther.getStatementid())
 && (this.getRecordid()==castOther.getRecordid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getStatementid();
         result = 37 * result + (int) this.getRecordid();
         return result;
   }   


}


