package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Channelatsextmapvalues generated by hbm2java
 */
@Entity
@Table(name="CHANNELATSEXTMAPVALUES"
    ,schema="FCDBADMIN_RK"
)
public class Channelatsextmapvalues  implements java.io.Serializable {


     private ChannelatsextmapvaluesId id;
     private Mstchannelatsext mstchannelatsext;
     private String idrequestmapped;

    public Channelatsextmapvalues() {
    }

	
    public Channelatsextmapvalues(ChannelatsextmapvaluesId id, Mstchannelatsext mstchannelatsext) {
        this.id = id;
        this.mstchannelatsext = mstchannelatsext;
    }
    public Channelatsextmapvalues(ChannelatsextmapvaluesId id, Mstchannelatsext mstchannelatsext, String idrequestmapped) {
       this.id = id;
       this.mstchannelatsext = mstchannelatsext;
       this.idrequestmapped = idrequestmapped;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrequestparent", column=@Column(name="IDREQUESTPARENT", nullable=false, length=50) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=10) ), 
        @AttributeOverride(name="fieldvalues", column=@Column(name="FIELDVALUES", nullable=false, length=200) ) } )
    public ChannelatsextmapvaluesId getId() {
        return this.id;
    }
    
    public void setId(ChannelatsextmapvaluesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IDCHANNEL", referencedColumnName="IDCHANNEL", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDREQUESTPARENT", referencedColumnName="IDREQUESTPARENT", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDREQUEST", referencedColumnName="IDREQUEST", nullable=false, insertable=false, updatable=false) } )
    public Mstchannelatsext getMstchannelatsext() {
        return this.mstchannelatsext;
    }
    
    public void setMstchannelatsext(Mstchannelatsext mstchannelatsext) {
        this.mstchannelatsext = mstchannelatsext;
    }

    
    @Column(name="IDREQUESTMAPPED", length=50)
    public String getIdrequestmapped() {
        return this.idrequestmapped;
    }
    
    public void setIdrequestmapped(String idrequestmapped) {
        this.idrequestmapped = idrequestmapped;
    }




}


