package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Channelatsext generated by hbm2java
 */
@Entity
@Table(name="CHANNELATSEXT"
    ,schema="FCDBADMIN_RK"
)
public class Channelatsext  implements java.io.Serializable {


     private ChannelatsextId id;
     private Character checksequence;

    public Channelatsext() {
    }

	
    public Channelatsext(ChannelatsextId id) {
        this.id = id;
    }
    public Channelatsext(ChannelatsextId id, Character checksequence) {
       this.id = id;
       this.checksequence = checksequence;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=50) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public ChannelatsextId getId() {
        return this.id;
    }
    
    public void setId(ChannelatsextId id) {
        this.id = id;
    }

    
    @Column(name="CHECKSEQUENCE", length=1)
    public Character getChecksequence() {
        return this.checksequence;
    }
    
    public void setChecksequence(Character checksequence) {
        this.checksequence = checksequence;
    }




}


