package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Complaints generated by hbm2java
 */
@Entity
@Table(name="COMPLAINTS"
    ,schema="FCDBADMIN_RK"
)
public class Complaints  implements java.io.Serializable {


     private String claimReferenceNum;
     private String resolutionNum;
     private Date claimDate;
     private String claimChannel;
     private String claimType;
     private String claimInvestigator;
     private String claimStatus;
     private String claimLoggedBy;
     private Date closureDate;
     private Date incidentDate;
     private String contactNum;
     private String productType;
     private String productName;
     private String claimCategory;
     private String claimSeverity;
     private String subject;
     private String details;
     private Date resolutionDate;
     private String createdby;
     private Date datcreated;
     private String updatedby;
     private Date lastupdatetime;
     private String idcust;

    public Complaints() {
    }

	
    public Complaints(String claimReferenceNum) {
        this.claimReferenceNum = claimReferenceNum;
    }
    public Complaints(String claimReferenceNum, String resolutionNum, Date claimDate, String claimChannel, String claimType, String claimInvestigator, String claimStatus, String claimLoggedBy, Date closureDate, Date incidentDate, String contactNum, String productType, String productName, String claimCategory, String claimSeverity, String subject, String details, Date resolutionDate, String createdby, Date datcreated, String updatedby, Date lastupdatetime, String idcust) {
       this.claimReferenceNum = claimReferenceNum;
       this.resolutionNum = resolutionNum;
       this.claimDate = claimDate;
       this.claimChannel = claimChannel;
       this.claimType = claimType;
       this.claimInvestigator = claimInvestigator;
       this.claimStatus = claimStatus;
       this.claimLoggedBy = claimLoggedBy;
       this.closureDate = closureDate;
       this.incidentDate = incidentDate;
       this.contactNum = contactNum;
       this.productType = productType;
       this.productName = productName;
       this.claimCategory = claimCategory;
       this.claimSeverity = claimSeverity;
       this.subject = subject;
       this.details = details;
       this.resolutionDate = resolutionDate;
       this.createdby = createdby;
       this.datcreated = datcreated;
       this.updatedby = updatedby;
       this.lastupdatetime = lastupdatetime;
       this.idcust = idcust;
    }
   
     @Id 

    
    @Column(name="CLAIM_REFERENCE_NUM", unique=true, nullable=false, length=20)
    public String getClaimReferenceNum() {
        return this.claimReferenceNum;
    }
    
    public void setClaimReferenceNum(String claimReferenceNum) {
        this.claimReferenceNum = claimReferenceNum;
    }

    
    @Column(name="RESOLUTION_NUM", length=5)
    public String getResolutionNum() {
        return this.resolutionNum;
    }
    
    public void setResolutionNum(String resolutionNum) {
        this.resolutionNum = resolutionNum;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CLAIM_DATE", length=7)
    public Date getClaimDate() {
        return this.claimDate;
    }
    
    public void setClaimDate(Date claimDate) {
        this.claimDate = claimDate;
    }

    
    @Column(name="CLAIM_CHANNEL", length=20)
    public String getClaimChannel() {
        return this.claimChannel;
    }
    
    public void setClaimChannel(String claimChannel) {
        this.claimChannel = claimChannel;
    }

    
    @Column(name="CLAIM_TYPE", length=20)
    public String getClaimType() {
        return this.claimType;
    }
    
    public void setClaimType(String claimType) {
        this.claimType = claimType;
    }

    
    @Column(name="CLAIM_INVESTIGATOR", length=20)
    public String getClaimInvestigator() {
        return this.claimInvestigator;
    }
    
    public void setClaimInvestigator(String claimInvestigator) {
        this.claimInvestigator = claimInvestigator;
    }

    
    @Column(name="CLAIM_STATUS", length=20)
    public String getClaimStatus() {
        return this.claimStatus;
    }
    
    public void setClaimStatus(String claimStatus) {
        this.claimStatus = claimStatus;
    }

    
    @Column(name="CLAIM_LOGGED_BY", length=50)
    public String getClaimLoggedBy() {
        return this.claimLoggedBy;
    }
    
    public void setClaimLoggedBy(String claimLoggedBy) {
        this.claimLoggedBy = claimLoggedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CLOSURE_DATE", length=7)
    public Date getClosureDate() {
        return this.closureDate;
    }
    
    public void setClosureDate(Date closureDate) {
        this.closureDate = closureDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INCIDENT_DATE", length=7)
    public Date getIncidentDate() {
        return this.incidentDate;
    }
    
    public void setIncidentDate(Date incidentDate) {
        this.incidentDate = incidentDate;
    }

    
    @Column(name="CONTACT_NUM", length=11)
    public String getContactNum() {
        return this.contactNum;
    }
    
    public void setContactNum(String contactNum) {
        this.contactNum = contactNum;
    }

    
    @Column(name="PRODUCT_TYPE", length=20)
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }

    
    @Column(name="PRODUCT_NAME", length=20)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="CLAIM_CATEGORY", length=20)
    public String getClaimCategory() {
        return this.claimCategory;
    }
    
    public void setClaimCategory(String claimCategory) {
        this.claimCategory = claimCategory;
    }

    
    @Column(name="CLAIM_SEVERITY", length=20)
    public String getClaimSeverity() {
        return this.claimSeverity;
    }
    
    public void setClaimSeverity(String claimSeverity) {
        this.claimSeverity = claimSeverity;
    }

    
    @Column(name="SUBJECT", length=40)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="DETAILS", length=1000)
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RESOLUTION_DATE", length=7)
    public Date getResolutionDate() {
        return this.resolutionDate;
    }
    
    public void setResolutionDate(Date resolutionDate) {
        this.resolutionDate = resolutionDate;
    }

    
    @Column(name="CREATEDBY", length=50)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="UPDATEDBY", length=50)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDATETIME", length=7)
    public Date getLastupdatetime() {
        return this.lastupdatetime;
    }
    
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    
    @Column(name="IDCUST", length=10)
    public String getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(String idcust) {
        this.idcust = idcust;
    }




}


