package com.jmr.obdx.domain;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CurrencyM generated by hbm2java
 */
@Entity
@Table(name="CURRENCY_M"
    ,schema="JMR_OBDX"
    , uniqueConstraints = @UniqueConstraint(columnNames="CURRENCY_TYPE") 
)
public class CurrencyM  implements java.io.Serializable {


     private long id;
     private String currencyType;
     private String currencyDesc;
     private Set<TransactionData> transactionDatas = new HashSet<TransactionData>(0);

    public CurrencyM() {
    }

	
    public CurrencyM(long id) {
        this.id = id;
    }
    public CurrencyM(String currencyType) {
        this.currencyType = currencyType;
    }
    
  
    public CurrencyM(long id, String currencyType, String currencyDesc, Set<TransactionData> transactionDatas) {
       this.id = id;
       this.currencyType = currencyType;
       this.currencyDesc = currencyDesc;
       this.transactionDatas = transactionDatas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="CURRENCY_TYPE", unique=true, length=10)
    public String getCurrencyType() {
        return this.currencyType;
    }
    
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    
    @Column(name="CURRENCY_DESC", length=50)
    public String getCurrencyDesc() {
        return this.currencyDesc;
    }
    
    public void setCurrencyDesc(String currencyDesc) {
        this.currencyDesc = currencyDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="currencyM")
    public Set<TransactionData> getTransactionDatas() {
        return this.transactionDatas;
    }
    
    public void setTransactionDatas(Set<TransactionData> transactionDatas) {
        this.transactionDatas = transactionDatas;
    }




}
