package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CustPoadecRef generated by hbm2java
 */
@Entity
@Table(name="CUST_POADEC_REF"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDCUST", "TYPECALL"}) 
)
public class CustPoadecRef  implements java.io.Serializable {


     private String referenceno;
     private Long idcust;
     private Character typecall;
     private Character relationship;
     private String nameLast1;
     private String nameFirst1;
     private String nameLast2;
     private String nameFirst2;
     private String postalCode;
     private String country;
     private String prefecture;
     private String city;
     private String blockstreet;
     private String flatname;
     private String phone1;
     private String phone2;
     private Character flgAddress;
     private Character flgIdentity;
     private Character flgDeceased;
     private Date datcreated;
     private Date datupdated;

    public CustPoadecRef() {
    }

	
    public CustPoadecRef(String referenceno) {
        this.referenceno = referenceno;
    }
    public CustPoadecRef(String referenceno, Long idcust, Character typecall, Character relationship, String nameLast1, String nameFirst1, String nameLast2, String nameFirst2, String postalCode, String country, String prefecture, String city, String blockstreet, String flatname, String phone1, String phone2, Character flgAddress, Character flgIdentity, Character flgDeceased, Date datcreated, Date datupdated) {
       this.referenceno = referenceno;
       this.idcust = idcust;
       this.typecall = typecall;
       this.relationship = relationship;
       this.nameLast1 = nameLast1;
       this.nameFirst1 = nameFirst1;
       this.nameLast2 = nameLast2;
       this.nameFirst2 = nameFirst2;
       this.postalCode = postalCode;
       this.country = country;
       this.prefecture = prefecture;
       this.city = city;
       this.blockstreet = blockstreet;
       this.flatname = flatname;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.flgAddress = flgAddress;
       this.flgIdentity = flgIdentity;
       this.flgDeceased = flgDeceased;
       this.datcreated = datcreated;
       this.datupdated = datupdated;
    }
   
     @Id 

    
    @Column(name="REFERENCENO", unique=true, nullable=false, length=15)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    
    @Column(name="IDCUST", precision=10, scale=0)
    public Long getIdcust() {
        return this.idcust;
    }
    
    public void setIdcust(Long idcust) {
        this.idcust = idcust;
    }

    
    @Column(name="TYPECALL", length=1)
    public Character getTypecall() {
        return this.typecall;
    }
    
    public void setTypecall(Character typecall) {
        this.typecall = typecall;
    }

    
    @Column(name="RELATIONSHIP", length=1)
    public Character getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(Character relationship) {
        this.relationship = relationship;
    }

    
    @Column(name="NAME_LAST1", length=762)
    public String getNameLast1() {
        return this.nameLast1;
    }
    
    public void setNameLast1(String nameLast1) {
        this.nameLast1 = nameLast1;
    }

    
    @Column(name="NAME_FIRST1", length=762)
    public String getNameFirst1() {
        return this.nameFirst1;
    }
    
    public void setNameFirst1(String nameFirst1) {
        this.nameFirst1 = nameFirst1;
    }

    
    @Column(name="NAME_LAST2", length=762)
    public String getNameLast2() {
        return this.nameLast2;
    }
    
    public void setNameLast2(String nameLast2) {
        this.nameLast2 = nameLast2;
    }

    
    @Column(name="NAME_FIRST2", length=762)
    public String getNameFirst2() {
        return this.nameFirst2;
    }
    
    public void setNameFirst2(String nameFirst2) {
        this.nameFirst2 = nameFirst2;
    }

    
    @Column(name="POSTAL_CODE", length=10)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="COUNTRY", length=105)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="PREFECTURE", length=105)
    public String getPrefecture() {
        return this.prefecture;
    }
    
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    
    @Column(name="CITY", length=105)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="BLOCKSTREET", length=105)
    public String getBlockstreet() {
        return this.blockstreet;
    }
    
    public void setBlockstreet(String blockstreet) {
        this.blockstreet = blockstreet;
    }

    
    @Column(name="FLATNAME", length=105)
    public String getFlatname() {
        return this.flatname;
    }
    
    public void setFlatname(String flatname) {
        this.flatname = flatname;
    }

    
    @Column(name="PHONE1", length=15)
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    
    @Column(name="PHONE2", length=15)
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    
    @Column(name="FLG_ADDRESS", length=1)
    public Character getFlgAddress() {
        return this.flgAddress;
    }
    
    public void setFlgAddress(Character flgAddress) {
        this.flgAddress = flgAddress;
    }

    
    @Column(name="FLG_IDENTITY", length=1)
    public Character getFlgIdentity() {
        return this.flgIdentity;
    }
    
    public void setFlgIdentity(Character flgIdentity) {
        this.flgIdentity = flgIdentity;
    }

    
    @Column(name="FLG_DECEASED", length=1)
    public Character getFlgDeceased() {
        return this.flgDeceased;
    }
    
    public void setFlgDeceased(Character flgDeceased) {
        this.flgDeceased = flgDeceased;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPDATED", length=7)
    public Date getDatupdated() {
        return this.datupdated;
    }
    
    public void setDatupdated(Date datupdated) {
        this.datupdated = datupdated;
    }




}


