package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Custommsgusermap generated by hbm2java
 */
@Entity
@Table(name="CUSTOMMSGUSERMAP"
    ,schema="FCDBADMIN_RK"
)
public class Custommsgusermap  implements java.io.Serializable {


     private CustommsgusermapId id;

    public Custommsgusermap() {
    }

    public Custommsgusermap(CustommsgusermapId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idmessage", column=@Column(name="IDMESSAGE", nullable=false, precision=22, scale=0) ) } )
    public CustommsgusermapId getId() {
        return this.id;
    }
    
    public void setId(CustommsgusermapId id) {
        this.id = id;
    }




}


