package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custommessages generated by hbm2java
 */
@Entity
@Table(name="CUSTOMMESSAGES"
    ,schema="FCDBADMIN_RK"
)
public class Custommessages  implements java.io.Serializable {


     private BigDecimal idmessage;
     private Date datcreated;
     private Date fromdate;
     private Date enddate;
     private Character iscustspecific;
     private String subject;
     private Blob message;
     private String idlang;
     private Character flgupload;
     private String token;
     private String extension;
     private String identity;
     private Character typemessage;
     private String idchannel;
     private String senderEntity;
     private String hostCommChannel;
     private Set<Custommsgattchmap> custommsgattchmaps = new HashSet<Custommsgattchmap>(0);

    public Custommessages() {
    }

	
    public Custommessages(BigDecimal idmessage) {
        this.idmessage = idmessage;
    }
    public Custommessages(BigDecimal idmessage, Date datcreated, Date fromdate, Date enddate, Character iscustspecific, String subject, Blob message, String idlang, Character flgupload, String token, String extension, String identity, Character typemessage, String idchannel, String senderEntity, String hostCommChannel, Set<Custommsgattchmap> custommsgattchmaps) {
       this.idmessage = idmessage;
       this.datcreated = datcreated;
       this.fromdate = fromdate;
       this.enddate = enddate;
       this.iscustspecific = iscustspecific;
       this.subject = subject;
       this.message = message;
       this.idlang = idlang;
       this.flgupload = flgupload;
       this.token = token;
       this.extension = extension;
       this.identity = identity;
       this.typemessage = typemessage;
       this.idchannel = idchannel;
       this.senderEntity = senderEntity;
       this.hostCommChannel = hostCommChannel;
       this.custommsgattchmaps = custommsgattchmaps;
    }
   
     @Id 

    
    @Column(name="IDMESSAGE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(BigDecimal idmessage) {
        this.idmessage = idmessage;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FROMDATE", length=7)
    public Date getFromdate() {
        return this.fromdate;
    }
    
    public void setFromdate(Date fromdate) {
        this.fromdate = fromdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENDDATE", length=7)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    
    @Column(name="ISCUSTSPECIFIC", length=1)
    public Character getIscustspecific() {
        return this.iscustspecific;
    }
    
    public void setIscustspecific(Character iscustspecific) {
        this.iscustspecific = iscustspecific;
    }

    
    @Column(name="SUBJECT", length=80)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="MESSAGE")
    public Blob getMessage() {
        return this.message;
    }
    
    public void setMessage(Blob message) {
        this.message = message;
    }

    
    @Column(name="IDLANG", length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }

    
    @Column(name="FLGUPLOAD", length=1)
    public Character getFlgupload() {
        return this.flgupload;
    }
    
    public void setFlgupload(Character flgupload) {
        this.flgupload = flgupload;
    }

    
    @Column(name="TOKEN", length=100)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    
    @Column(name="EXTENSION", length=3)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="IDENTITY", length=20)
    public String getIdentity() {
        return this.identity;
    }
    
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    
    @Column(name="TYPEMESSAGE", length=1)
    public Character getTypemessage() {
        return this.typemessage;
    }
    
    public void setTypemessage(Character typemessage) {
        this.typemessage = typemessage;
    }

    
    @Column(name="IDCHANNEL", length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    
    @Column(name="SENDER_ENTITY", length=5)
    public String getSenderEntity() {
        return this.senderEntity;
    }
    
    public void setSenderEntity(String senderEntity) {
        this.senderEntity = senderEntity;
    }

    
    @Column(name="HOST_COMM_CHANNEL", length=20)
    public String getHostCommChannel() {
        return this.hostCommChannel;
    }
    
    public void setHostCommChannel(String hostCommChannel) {
        this.hostCommChannel = hostCommChannel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="custommessages")
    public Set<Custommsgattchmap> getCustommsgattchmaps() {
        return this.custommsgattchmaps;
    }
    
    public void setCustommsgattchmaps(Set<Custommsgattchmap> custommsgattchmaps) {
        this.custommsgattchmaps = custommsgattchmaps;
    }




}


