package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustDocData generated by hbm2java
 */
@Entity
@Table(name="CUST_DOC_DATA"
    ,schema="FCDBADMIN_RK"
)
public class CustDocData  implements java.io.Serializable {


     private String iddocument;
     private String processstatus;
     private Blob docdata;
     private String idfile;
     private String idEntity;

    public CustDocData() {
    }

	
    public CustDocData(String iddocument) {
        this.iddocument = iddocument;
    }
    public CustDocData(String iddocument, String processstatus, Blob docdata, String idfile, String idEntity) {
       this.iddocument = iddocument;
       this.processstatus = processstatus;
       this.docdata = docdata;
       this.idfile = idfile;
       this.idEntity = idEntity;
    }
   
     @Id 

    
    @Column(name="IDDOCUMENT", unique=true, nullable=false, length=50)
    public String getIddocument() {
        return this.iddocument;
    }
    
    public void setIddocument(String iddocument) {
        this.iddocument = iddocument;
    }

    
    @Column(name="PROCESSSTATUS", length=2)
    public String getProcessstatus() {
        return this.processstatus;
    }
    
    public void setProcessstatus(String processstatus) {
        this.processstatus = processstatus;
    }

    
    @Column(name="DOCDATA")
    public Blob getDocdata() {
        return this.docdata;
    }
    
    public void setDocdata(Blob docdata) {
        this.docdata = docdata;
    }

    
    @Column(name="IDFILE", length=50)
    public String getIdfile() {
        return this.idfile;
    }
    
    public void setIdfile(String idfile) {
        this.idfile = idfile;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }




}


