package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTMstaccount generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_MSTACCOUNT"
    ,schema="FCDBADMIN_RK"
)
public class FcatTMstaccount  implements java.io.Serializable {


     private FcatTMstaccountId id;
     private String codaccttype;
     private String txtacctstatus;
     private String codacctcurr;
     private BigDecimal numbalance;
     private BigDecimal numopenbalance;
     private Date datlastupdated;
     private BigDecimal numavailbal;
     private BigDecimal numuncollected;
     private BigDecimal numavailcredit;
     private BigDecimal nummontovcr;
     private BigDecimal nummontovdr;
     private String acctdesc;
     private BigDecimal odlimit;
     private Date odstartdt;
     private Date odenddt;
     private BigDecimal shadowlimit;
     private BigDecimal accrdramt;
     private BigDecimal accrcramt;
     private String jointacctindicator;
     private String chqbook;
     private String overdraftFacility;
     private BigDecimal numstatebit;
     private String chkname1;
     private String chkname2;
     private String autoreorderchkreq;
     private BigDecimal autoreorderchklvl;
     private String dirtstatus;
     private Date nextcapdt;
     private String capfreq;
     private String authsignatory;
     private BigDecimal authsignlimit;
     private String salesperson;
     private String introducer;
     private String ibannumber;
     private String acctlockflag;
     private String debitacctlockflag;
     private String creditacctlockflag;
     private String crline;
     private BigDecimal availamt;
     private BigDecimal crintrate;
     private BigDecimal alwdod;
     private BigDecimal unalwdod;
     private String acfrozen;
     private Serializable dtime;
     private BigDecimal slno;
     private String add1;
     private String add2;
     private String add3;
     private String nom1;
     private String nom2;
     private String nom4;
     private String prdname;
     private String prdtype;
     private Date acctopendate;

    public FcatTMstaccount() {
    }

	
    public FcatTMstaccount(FcatTMstaccountId id) {
        this.id = id;
    }
    public FcatTMstaccount(FcatTMstaccountId id, String codaccttype, String txtacctstatus, String codacctcurr, BigDecimal numbalance, BigDecimal numopenbalance, Date datlastupdated, BigDecimal numavailbal, BigDecimal numuncollected, BigDecimal numavailcredit, BigDecimal nummontovcr, BigDecimal nummontovdr, String acctdesc, BigDecimal odlimit, Date odstartdt, Date odenddt, BigDecimal shadowlimit, BigDecimal accrdramt, BigDecimal accrcramt, String jointacctindicator, String chqbook, String overdraftFacility, BigDecimal numstatebit, String chkname1, String chkname2, String autoreorderchkreq, BigDecimal autoreorderchklvl, String dirtstatus, Date nextcapdt, String capfreq, String authsignatory, BigDecimal authsignlimit, String salesperson, String introducer, String ibannumber, String acctlockflag, String debitacctlockflag, String creditacctlockflag, String crline, BigDecimal availamt, BigDecimal crintrate, BigDecimal alwdod, BigDecimal unalwdod, String acfrozen, Serializable dtime, BigDecimal slno, String add1, String add2, String add3, String nom1, String nom2, String nom4, String prdname, String prdtype, Date acctopendate) {
       this.id = id;
       this.codaccttype = codaccttype;
       this.txtacctstatus = txtacctstatus;
       this.codacctcurr = codacctcurr;
       this.numbalance = numbalance;
       this.numopenbalance = numopenbalance;
       this.datlastupdated = datlastupdated;
       this.numavailbal = numavailbal;
       this.numuncollected = numuncollected;
       this.numavailcredit = numavailcredit;
       this.nummontovcr = nummontovcr;
       this.nummontovdr = nummontovdr;
       this.acctdesc = acctdesc;
       this.odlimit = odlimit;
       this.odstartdt = odstartdt;
       this.odenddt = odenddt;
       this.shadowlimit = shadowlimit;
       this.accrdramt = accrdramt;
       this.accrcramt = accrcramt;
       this.jointacctindicator = jointacctindicator;
       this.chqbook = chqbook;
       this.overdraftFacility = overdraftFacility;
       this.numstatebit = numstatebit;
       this.chkname1 = chkname1;
       this.chkname2 = chkname2;
       this.autoreorderchkreq = autoreorderchkreq;
       this.autoreorderchklvl = autoreorderchklvl;
       this.dirtstatus = dirtstatus;
       this.nextcapdt = nextcapdt;
       this.capfreq = capfreq;
       this.authsignatory = authsignatory;
       this.authsignlimit = authsignlimit;
       this.salesperson = salesperson;
       this.introducer = introducer;
       this.ibannumber = ibannumber;
       this.acctlockflag = acctlockflag;
       this.debitacctlockflag = debitacctlockflag;
       this.creditacctlockflag = creditacctlockflag;
       this.crline = crline;
       this.availamt = availamt;
       this.crintrate = crintrate;
       this.alwdod = alwdod;
       this.unalwdod = unalwdod;
       this.acfrozen = acfrozen;
       this.dtime = dtime;
       this.slno = slno;
       this.add1 = add1;
       this.add2 = add2;
       this.add3 = add3;
       this.nom1 = nom1;
       this.nom2 = nom2;
       this.nom4 = nom4;
       this.prdname = prdname;
       this.prdtype = prdtype;
       this.acctopendate = acctopendate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcustomer", column=@Column(name="IDCUSTOMER", nullable=false, length=50) ), 
        @AttributeOverride(name="idaccount", column=@Column(name="IDACCOUNT", nullable=false, length=50) ), 
        @AttributeOverride(name="codbranch", column=@Column(name="CODBRANCH", nullable=false, length=50) ) } )
    public FcatTMstaccountId getId() {
        return this.id;
    }
    
    public void setId(FcatTMstaccountId id) {
        this.id = id;
    }

    
    @Column(name="CODACCTTYPE", length=1)
    public String getCodaccttype() {
        return this.codaccttype;
    }
    
    public void setCodaccttype(String codaccttype) {
        this.codaccttype = codaccttype;
    }

    
    @Column(name="TXTACCTSTATUS", length=1)
    public String getTxtacctstatus() {
        return this.txtacctstatus;
    }
    
    public void setTxtacctstatus(String txtacctstatus) {
        this.txtacctstatus = txtacctstatus;
    }

    
    @Column(name="CODACCTCURR", length=3)
    public String getCodacctcurr() {
        return this.codacctcurr;
    }
    
    public void setCodacctcurr(String codacctcurr) {
        this.codacctcurr = codacctcurr;
    }

    
    @Column(name="NUMBALANCE", precision=22, scale=0)
    public BigDecimal getNumbalance() {
        return this.numbalance;
    }
    
    public void setNumbalance(BigDecimal numbalance) {
        this.numbalance = numbalance;
    }

    
    @Column(name="NUMOPENBALANCE", precision=22, scale=0)
    public BigDecimal getNumopenbalance() {
        return this.numopenbalance;
    }
    
    public void setNumopenbalance(BigDecimal numopenbalance) {
        this.numopenbalance = numopenbalance;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTUPDATED", length=7)
    public Date getDatlastupdated() {
        return this.datlastupdated;
    }
    
    public void setDatlastupdated(Date datlastupdated) {
        this.datlastupdated = datlastupdated;
    }

    
    @Column(name="NUMAVAILBAL", precision=22, scale=0)
    public BigDecimal getNumavailbal() {
        return this.numavailbal;
    }
    
    public void setNumavailbal(BigDecimal numavailbal) {
        this.numavailbal = numavailbal;
    }

    
    @Column(name="NUMUNCOLLECTED", precision=22, scale=0)
    public BigDecimal getNumuncollected() {
        return this.numuncollected;
    }
    
    public void setNumuncollected(BigDecimal numuncollected) {
        this.numuncollected = numuncollected;
    }

    
    @Column(name="NUMAVAILCREDIT", precision=22, scale=0)
    public BigDecimal getNumavailcredit() {
        return this.numavailcredit;
    }
    
    public void setNumavailcredit(BigDecimal numavailcredit) {
        this.numavailcredit = numavailcredit;
    }

    
    @Column(name="NUMMONTOVCR", precision=22, scale=0)
    public BigDecimal getNummontovcr() {
        return this.nummontovcr;
    }
    
    public void setNummontovcr(BigDecimal nummontovcr) {
        this.nummontovcr = nummontovcr;
    }

    
    @Column(name="NUMMONTOVDR", precision=22, scale=0)
    public BigDecimal getNummontovdr() {
        return this.nummontovdr;
    }
    
    public void setNummontovdr(BigDecimal nummontovdr) {
        this.nummontovdr = nummontovdr;
    }

    
    @Column(name="ACCTDESC")
    public String getAcctdesc() {
        return this.acctdesc;
    }
    
    public void setAcctdesc(String acctdesc) {
        this.acctdesc = acctdesc;
    }

    
    @Column(name="ODLIMIT", precision=22, scale=0)
    public BigDecimal getOdlimit() {
        return this.odlimit;
    }
    
    public void setOdlimit(BigDecimal odlimit) {
        this.odlimit = odlimit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ODSTARTDT", length=7)
    public Date getOdstartdt() {
        return this.odstartdt;
    }
    
    public void setOdstartdt(Date odstartdt) {
        this.odstartdt = odstartdt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ODENDDT", length=7)
    public Date getOdenddt() {
        return this.odenddt;
    }
    
    public void setOdenddt(Date odenddt) {
        this.odenddt = odenddt;
    }

    
    @Column(name="SHADOWLIMIT", precision=22, scale=0)
    public BigDecimal getShadowlimit() {
        return this.shadowlimit;
    }
    
    public void setShadowlimit(BigDecimal shadowlimit) {
        this.shadowlimit = shadowlimit;
    }

    
    @Column(name="ACCRDRAMT", precision=22, scale=0)
    public BigDecimal getAccrdramt() {
        return this.accrdramt;
    }
    
    public void setAccrdramt(BigDecimal accrdramt) {
        this.accrdramt = accrdramt;
    }

    
    @Column(name="ACCRCRAMT", precision=22, scale=0)
    public BigDecimal getAccrcramt() {
        return this.accrcramt;
    }
    
    public void setAccrcramt(BigDecimal accrcramt) {
        this.accrcramt = accrcramt;
    }

    
    @Column(name="JOINTACCTINDICATOR", length=1)
    public String getJointacctindicator() {
        return this.jointacctindicator;
    }
    
    public void setJointacctindicator(String jointacctindicator) {
        this.jointacctindicator = jointacctindicator;
    }

    
    @Column(name="CHQBOOK", length=1)
    public String getChqbook() {
        return this.chqbook;
    }
    
    public void setChqbook(String chqbook) {
        this.chqbook = chqbook;
    }

    
    @Column(name="OVERDRAFT_FACILITY", length=1)
    public String getOverdraftFacility() {
        return this.overdraftFacility;
    }
    
    public void setOverdraftFacility(String overdraftFacility) {
        this.overdraftFacility = overdraftFacility;
    }

    
    @Column(name="NUMSTATEBIT", precision=22, scale=0)
    public BigDecimal getNumstatebit() {
        return this.numstatebit;
    }
    
    public void setNumstatebit(BigDecimal numstatebit) {
        this.numstatebit = numstatebit;
    }

    
    @Column(name="CHKNAME1")
    public String getChkname1() {
        return this.chkname1;
    }
    
    public void setChkname1(String chkname1) {
        this.chkname1 = chkname1;
    }

    
    @Column(name="CHKNAME2")
    public String getChkname2() {
        return this.chkname2;
    }
    
    public void setChkname2(String chkname2) {
        this.chkname2 = chkname2;
    }

    
    @Column(name="AUTOREORDERCHKREQ", length=1)
    public String getAutoreorderchkreq() {
        return this.autoreorderchkreq;
    }
    
    public void setAutoreorderchkreq(String autoreorderchkreq) {
        this.autoreorderchkreq = autoreorderchkreq;
    }

    
    @Column(name="AUTOREORDERCHKLVL", precision=22, scale=0)
    public BigDecimal getAutoreorderchklvl() {
        return this.autoreorderchklvl;
    }
    
    public void setAutoreorderchklvl(BigDecimal autoreorderchklvl) {
        this.autoreorderchklvl = autoreorderchklvl;
    }

    
    @Column(name="DIRTSTATUS", length=1)
    public String getDirtstatus() {
        return this.dirtstatus;
    }
    
    public void setDirtstatus(String dirtstatus) {
        this.dirtstatus = dirtstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NEXTCAPDT", length=7)
    public Date getNextcapdt() {
        return this.nextcapdt;
    }
    
    public void setNextcapdt(Date nextcapdt) {
        this.nextcapdt = nextcapdt;
    }

    
    @Column(name="CAPFREQ")
    public String getCapfreq() {
        return this.capfreq;
    }
    
    public void setCapfreq(String capfreq) {
        this.capfreq = capfreq;
    }

    
    @Column(name="AUTHSIGNATORY")
    public String getAuthsignatory() {
        return this.authsignatory;
    }
    
    public void setAuthsignatory(String authsignatory) {
        this.authsignatory = authsignatory;
    }

    
    @Column(name="AUTHSIGNLIMIT", precision=22, scale=0)
    public BigDecimal getAuthsignlimit() {
        return this.authsignlimit;
    }
    
    public void setAuthsignlimit(BigDecimal authsignlimit) {
        this.authsignlimit = authsignlimit;
    }

    
    @Column(name="SALESPERSON")
    public String getSalesperson() {
        return this.salesperson;
    }
    
    public void setSalesperson(String salesperson) {
        this.salesperson = salesperson;
    }

    
    @Column(name="INTRODUCER")
    public String getIntroducer() {
        return this.introducer;
    }
    
    public void setIntroducer(String introducer) {
        this.introducer = introducer;
    }

    
    @Column(name="IBANNUMBER", length=50)
    public String getIbannumber() {
        return this.ibannumber;
    }
    
    public void setIbannumber(String ibannumber) {
        this.ibannumber = ibannumber;
    }

    
    @Column(name="ACCTLOCKFLAG", length=1)
    public String getAcctlockflag() {
        return this.acctlockflag;
    }
    
    public void setAcctlockflag(String acctlockflag) {
        this.acctlockflag = acctlockflag;
    }

    
    @Column(name="DEBITACCTLOCKFLAG", length=1)
    public String getDebitacctlockflag() {
        return this.debitacctlockflag;
    }
    
    public void setDebitacctlockflag(String debitacctlockflag) {
        this.debitacctlockflag = debitacctlockflag;
    }

    
    @Column(name="CREDITACCTLOCKFLAG", length=1)
    public String getCreditacctlockflag() {
        return this.creditacctlockflag;
    }
    
    public void setCreditacctlockflag(String creditacctlockflag) {
        this.creditacctlockflag = creditacctlockflag;
    }

    
    @Column(name="CRLINE", length=50)
    public String getCrline() {
        return this.crline;
    }
    
    public void setCrline(String crline) {
        this.crline = crline;
    }

    
    @Column(name="AVAILAMT", precision=22, scale=0)
    public BigDecimal getAvailamt() {
        return this.availamt;
    }
    
    public void setAvailamt(BigDecimal availamt) {
        this.availamt = availamt;
    }

    
    @Column(name="CRINTRATE", precision=22, scale=0)
    public BigDecimal getCrintrate() {
        return this.crintrate;
    }
    
    public void setCrintrate(BigDecimal crintrate) {
        this.crintrate = crintrate;
    }

    
    @Column(name="ALWDOD", precision=22, scale=0)
    public BigDecimal getAlwdod() {
        return this.alwdod;
    }
    
    public void setAlwdod(BigDecimal alwdod) {
        this.alwdod = alwdod;
    }

    
    @Column(name="UNALWDOD", precision=22, scale=0)
    public BigDecimal getUnalwdod() {
        return this.unalwdod;
    }
    
    public void setUnalwdod(BigDecimal unalwdod) {
        this.unalwdod = unalwdod;
    }

    
    @Column(name="ACFROZEN", length=1)
    public String getAcfrozen() {
        return this.acfrozen;
    }
    
    public void setAcfrozen(String acfrozen) {
        this.acfrozen = acfrozen;
    }

    
    @Column(name="DTIME")
    public Serializable getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Serializable dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=22, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    
    @Column(name="ADD1")
    public String getAdd1() {
        return this.add1;
    }
    
    public void setAdd1(String add1) {
        this.add1 = add1;
    }

    
    @Column(name="ADD2")
    public String getAdd2() {
        return this.add2;
    }
    
    public void setAdd2(String add2) {
        this.add2 = add2;
    }

    
    @Column(name="ADD3")
    public String getAdd3() {
        return this.add3;
    }
    
    public void setAdd3(String add3) {
        this.add3 = add3;
    }

    
    @Column(name="NOM1")
    public String getNom1() {
        return this.nom1;
    }
    
    public void setNom1(String nom1) {
        this.nom1 = nom1;
    }

    
    @Column(name="NOM2")
    public String getNom2() {
        return this.nom2;
    }
    
    public void setNom2(String nom2) {
        this.nom2 = nom2;
    }

    
    @Column(name="NOM4")
    public String getNom4() {
        return this.nom4;
    }
    
    public void setNom4(String nom4) {
        this.nom4 = nom4;
    }

    
    @Column(name="PRDNAME")
    public String getPrdname() {
        return this.prdname;
    }
    
    public void setPrdname(String prdname) {
        this.prdname = prdname;
    }

    
    @Column(name="PRDTYPE", length=1)
    public String getPrdtype() {
        return this.prdtype;
    }
    
    public void setPrdtype(String prdtype) {
        this.prdtype = prdtype;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACCTOPENDATE", length=7)
    public Date getAcctopendate() {
        return this.acctopendate;
    }
    
    public void setAcctopendate(Date acctopendate) {
        this.acctopendate = acctopendate;
    }




}


