package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTEntitydates generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_ENTITYDATES"
    ,schema="FCDBADMIN_RK"
)
public class FcatTEntitydates  implements java.io.Serializable {


     private String idEntity;
     private Date datlast;
     private Date datprocess;
     private Date datnext;

    public FcatTEntitydates() {
    }

	
    public FcatTEntitydates(String idEntity) {
        this.idEntity = idEntity;
    }
    public FcatTEntitydates(String idEntity, Date datlast, Date datprocess, Date datnext) {
       this.idEntity = idEntity;
       this.datlast = datlast;
       this.datprocess = datprocess;
       this.datnext = datnext;
    }
   
     @Id 

    
    @Column(name="ID_ENTITY", unique=true, nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLAST", length=7)
    public Date getDatlast() {
        return this.datlast;
    }
    
    public void setDatlast(Date datlast) {
        this.datlast = datlast;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATPROCESS", length=7)
    public Date getDatprocess() {
        return this.datprocess;
    }
    
    public void setDatprocess(Date datprocess) {
        this.datprocess = datprocess;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATNEXT", length=7)
    public Date getDatnext() {
        return this.datnext;
    }
    
    public void setDatnext(Date datnext) {
        this.datnext = datnext;
    }




}


