package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FcatTMstfundamc generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_MSTFUNDAMC"
    ,schema="FCDBADMIN_RK"
)
public class FcatTMstfundamc  implements java.io.Serializable {


     private String entityid;
     private String entityname;
     private Set<FcatTMstfunddtls> fcatTMstfunddtlses = new HashSet<FcatTMstfunddtls>(0);

    public FcatTMstfundamc() {
    }

	
    public FcatTMstfundamc(String entityid) {
        this.entityid = entityid;
    }
    public FcatTMstfundamc(String entityid, String entityname, Set<FcatTMstfunddtls> fcatTMstfunddtlses) {
       this.entityid = entityid;
       this.entityname = entityname;
       this.fcatTMstfunddtlses = fcatTMstfunddtlses;
    }
   
     @Id 

    
    @Column(name="ENTITYID", unique=true, nullable=false, length=12)
    public String getEntityid() {
        return this.entityid;
    }
    
    public void setEntityid(String entityid) {
        this.entityid = entityid;
    }

    
    @Column(name="ENTITYNAME", length=60)
    public String getEntityname() {
        return this.entityname;
    }
    
    public void setEntityname(String entityname) {
        this.entityname = entityname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fcatTMstfundamc")
    public Set<FcatTMstfunddtls> getFcatTMstfunddtlses() {
        return this.fcatTMstfunddtlses;
    }
    
    public void setFcatTMstfunddtlses(Set<FcatTMstfunddtls> fcatTMstfunddtlses) {
        this.fcatTMstfunddtlses = fcatTMstfunddtlses;
    }




}


