package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTBranchBusinessDates generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_BRANCH_BUSINESS_DATES"
    ,schema="FCDBADMIN_RK"
)
public class FcatTBranchBusinessDates  implements java.io.Serializable {


     private FcatTBranchBusinessDatesId id;
     private Date datlast;
     private Date datprocess;
     private Date datnext;
     private String isEodRunning;

    public FcatTBranchBusinessDates() {
    }

	
    public FcatTBranchBusinessDates(FcatTBranchBusinessDatesId id) {
        this.id = id;
    }
    public FcatTBranchBusinessDates(FcatTBranchBusinessDatesId id, Date datlast, Date datprocess, Date datnext, String isEodRunning) {
       this.id = id;
       this.datlast = datlast;
       this.datprocess = datprocess;
       this.datnext = datnext;
       this.isEodRunning = isEodRunning;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="codbank", column=@Column(name="CODBANK", nullable=false, length=3) ) } )
    public FcatTBranchBusinessDatesId getId() {
        return this.id;
    }
    
    public void setId(FcatTBranchBusinessDatesId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLAST", length=7)
    public Date getDatlast() {
        return this.datlast;
    }
    
    public void setDatlast(Date datlast) {
        this.datlast = datlast;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATPROCESS", length=7)
    public Date getDatprocess() {
        return this.datprocess;
    }
    
    public void setDatprocess(Date datprocess) {
        this.datprocess = datprocess;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATNEXT", length=7)
    public Date getDatnext() {
        return this.datnext;
    }
    
    public void setDatnext(Date datnext) {
        this.datnext = datnext;
    }

    
    @Column(name="IS_EOD_RUNNING", length=1)
    public String getIsEodRunning() {
        return this.isEodRunning;
    }
    
    public void setIsEodRunning(String isEodRunning) {
        this.isEodRunning = isEodRunning;
    }




}


