package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fcatxmltemp generated by hbm2java
 */
@Entity
@Table(name="FCATXMLTEMP"
    ,schema="FCDBADMIN_RK"
)
public class Fcatxmltemp  implements java.io.Serializable {


     private BigDecimal id;
     private String txn;
     private Blob val;
     private Date datstore;

    public Fcatxmltemp() {
    }

	
    public Fcatxmltemp(BigDecimal id) {
        this.id = id;
    }
    public Fcatxmltemp(BigDecimal id, String txn, Blob val, Date datstore) {
       this.id = id;
       this.txn = txn;
       this.val = val;
       this.datstore = datstore;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="TXN", length=8)
    public String getTxn() {
        return this.txn;
    }
    
    public void setTxn(String txn) {
        this.txn = txn;
    }

    
    @Column(name="VAL")
    public Blob getVal() {
        return this.val;
    }
    
    public void setVal(Blob val) {
        this.val = val;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATSTORE", length=7)
    public Date getDatstore() {
        return this.datstore;
    }
    
    public void setDatstore(Date datstore) {
        this.datstore = datstore;
    }




}


