package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FcatTMstfunddtls generated by hbm2java
 */
@Entity
@Table(name="FCAT_T_MSTFUNDDTLS"
    ,schema="FCDBADMIN_RK"
)
public class FcatTMstfunddtls  implements java.io.Serializable {


     private FcatTMstfunddtlsId id;
     private FcatTMstfundamc fcatTMstfundamc;
     private String fundname;
     private String fundidentificationnumber;
     private BigDecimal fundtype;
     private String fundfamily;
     private String fundbasecurrency;
     private BigDecimal maxtransactionamount;
     private BigDecimal mintransactionamount;
     private BigDecimal mintransactionunits;
     private BigDecimal maxtransactionunits;
     private BigDecimal stepamount;
     private BigDecimal stepunits;
     private Date transactioncutofftime;
     private Date maturitydate;
     private Date fundstartdate;
     private Boolean fundsuspended;
     private Boolean fundenabled;
     private BigDecimal declarednav;

    public FcatTMstfunddtls() {
    }

	
    public FcatTMstfunddtls(FcatTMstfunddtlsId id, FcatTMstfundamc fcatTMstfundamc) {
        this.id = id;
        this.fcatTMstfundamc = fcatTMstfundamc;
    }
    public FcatTMstfunddtls(FcatTMstfunddtlsId id, FcatTMstfundamc fcatTMstfundamc, String fundname, String fundidentificationnumber, BigDecimal fundtype, String fundfamily, String fundbasecurrency, BigDecimal maxtransactionamount, BigDecimal mintransactionamount, BigDecimal mintransactionunits, BigDecimal maxtransactionunits, BigDecimal stepamount, BigDecimal stepunits, Date transactioncutofftime, Date maturitydate, Date fundstartdate, Boolean fundsuspended, Boolean fundenabled, BigDecimal declarednav) {
       this.id = id;
       this.fcatTMstfundamc = fcatTMstfundamc;
       this.fundname = fundname;
       this.fundidentificationnumber = fundidentificationnumber;
       this.fundtype = fundtype;
       this.fundfamily = fundfamily;
       this.fundbasecurrency = fundbasecurrency;
       this.maxtransactionamount = maxtransactionamount;
       this.mintransactionamount = mintransactionamount;
       this.mintransactionunits = mintransactionunits;
       this.maxtransactionunits = maxtransactionunits;
       this.stepamount = stepamount;
       this.stepunits = stepunits;
       this.transactioncutofftime = transactioncutofftime;
       this.maturitydate = maturitydate;
       this.fundstartdate = fundstartdate;
       this.fundsuspended = fundsuspended;
       this.fundenabled = fundenabled;
       this.declarednav = declarednav;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="amcid", column=@Column(name="AMCID", nullable=false, length=12) ), 
        @AttributeOverride(name="fundid", column=@Column(name="FUNDID", nullable=false, length=6) ), 
        @AttributeOverride(name="transactiontype", column=@Column(name="TRANSACTIONTYPE", nullable=false, length=2) ) } )
    public FcatTMstfunddtlsId getId() {
        return this.id;
    }
    
    public void setId(FcatTMstfunddtlsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AMCID", nullable=false, insertable=false, updatable=false)
    public FcatTMstfundamc getFcatTMstfundamc() {
        return this.fcatTMstfundamc;
    }
    
    public void setFcatTMstfundamc(FcatTMstfundamc fcatTMstfundamc) {
        this.fcatTMstfundamc = fcatTMstfundamc;
    }

    
    @Column(name="FUNDNAME", length=60)
    public String getFundname() {
        return this.fundname;
    }
    
    public void setFundname(String fundname) {
        this.fundname = fundname;
    }

    
    @Column(name="FUNDIDENTIFICATIONNUMBER", length=25)
    public String getFundidentificationnumber() {
        return this.fundidentificationnumber;
    }
    
    public void setFundidentificationnumber(String fundidentificationnumber) {
        this.fundidentificationnumber = fundidentificationnumber;
    }

    
    @Column(name="FUNDTYPE", precision=38, scale=0)
    public BigDecimal getFundtype() {
        return this.fundtype;
    }
    
    public void setFundtype(BigDecimal fundtype) {
        this.fundtype = fundtype;
    }

    
    @Column(name="FUNDFAMILY", length=6)
    public String getFundfamily() {
        return this.fundfamily;
    }
    
    public void setFundfamily(String fundfamily) {
        this.fundfamily = fundfamily;
    }

    
    @Column(name="FUNDBASECURRENCY", length=3)
    public String getFundbasecurrency() {
        return this.fundbasecurrency;
    }
    
    public void setFundbasecurrency(String fundbasecurrency) {
        this.fundbasecurrency = fundbasecurrency;
    }

    
    @Column(name="MAXTRANSACTIONAMOUNT", precision=30, scale=12)
    public BigDecimal getMaxtransactionamount() {
        return this.maxtransactionamount;
    }
    
    public void setMaxtransactionamount(BigDecimal maxtransactionamount) {
        this.maxtransactionamount = maxtransactionamount;
    }

    
    @Column(name="MINTRANSACTIONAMOUNT", precision=30, scale=12)
    public BigDecimal getMintransactionamount() {
        return this.mintransactionamount;
    }
    
    public void setMintransactionamount(BigDecimal mintransactionamount) {
        this.mintransactionamount = mintransactionamount;
    }

    
    @Column(name="MINTRANSACTIONUNITS", precision=27, scale=12)
    public BigDecimal getMintransactionunits() {
        return this.mintransactionunits;
    }
    
    public void setMintransactionunits(BigDecimal mintransactionunits) {
        this.mintransactionunits = mintransactionunits;
    }

    
    @Column(name="MAXTRANSACTIONUNITS", precision=27, scale=12)
    public BigDecimal getMaxtransactionunits() {
        return this.maxtransactionunits;
    }
    
    public void setMaxtransactionunits(BigDecimal maxtransactionunits) {
        this.maxtransactionunits = maxtransactionunits;
    }

    
    @Column(name="STEPAMOUNT", precision=30, scale=12)
    public BigDecimal getStepamount() {
        return this.stepamount;
    }
    
    public void setStepamount(BigDecimal stepamount) {
        this.stepamount = stepamount;
    }

    
    @Column(name="STEPUNITS", precision=27, scale=12)
    public BigDecimal getStepunits() {
        return this.stepunits;
    }
    
    public void setStepunits(BigDecimal stepunits) {
        this.stepunits = stepunits;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRANSACTIONCUTOFFTIME", length=7)
    public Date getTransactioncutofftime() {
        return this.transactioncutofftime;
    }
    
    public void setTransactioncutofftime(Date transactioncutofftime) {
        this.transactioncutofftime = transactioncutofftime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MATURITYDATE", length=7)
    public Date getMaturitydate() {
        return this.maturitydate;
    }
    
    public void setMaturitydate(Date maturitydate) {
        this.maturitydate = maturitydate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FUNDSTARTDATE", length=7)
    public Date getFundstartdate() {
        return this.fundstartdate;
    }
    
    public void setFundstartdate(Date fundstartdate) {
        this.fundstartdate = fundstartdate;
    }

    
    @Column(name="FUNDSUSPENDED", precision=1, scale=0)
    public Boolean getFundsuspended() {
        return this.fundsuspended;
    }
    
    public void setFundsuspended(Boolean fundsuspended) {
        this.fundsuspended = fundsuspended;
    }

    
    @Column(name="FUNDENABLED", precision=1, scale=0)
    public Boolean getFundenabled() {
        return this.fundenabled;
    }
    
    public void setFundenabled(Boolean fundenabled) {
        this.fundenabled = fundenabled;
    }

    
    @Column(name="DECLAREDNAV", precision=30, scale=12)
    public BigDecimal getDeclarednav() {
        return this.declarednav;
    }
    
    public void setDeclarednav(BigDecimal declarednav) {
        this.declarednav = declarednav;
    }




}


