package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FcatTMstbranchId generated by hbm2java
 */
@Embeddable
public class FcatTMstbranchId  implements java.io.Serializable {


     private String idEntity;
     private String codbranch;

    public FcatTMstbranchId() {
    }

    public FcatTMstbranchId(String idEntity, String codbranch) {
       this.idEntity = idEntity;
       this.codbranch = codbranch;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="CODBRANCH", nullable=false, length=5)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FcatTMstbranchId) ) return false;
		 FcatTMstbranchId castOther = ( FcatTMstbranchId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getCodbranch()==castOther.getCodbranch()) || ( this.getCodbranch()!=null && castOther.getCodbranch()!=null && this.getCodbranch().equals(castOther.getCodbranch()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getCodbranch() == null ? 0 : this.getCodbranch().hashCode() );
         return result;
   }   


}


