package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoalShare generated by hbm2java
 */
@Entity
@Table(name="GOAL_SHARE"
    ,schema="FCDBADMIN_RK"
)
public class GoalShare  implements java.io.Serializable {


     private GoalShareId id;
     private String iduser;
     private String idEntity;
     private Character typeAccess;
     private Character status;
     private Date sharefrom;
     private Date shareto;
     private String securecode;

    public GoalShare() {
    }

	
    public GoalShare(GoalShareId id) {
        this.id = id;
    }
    public GoalShare(GoalShareId id, String iduser, String idEntity, Character typeAccess, Character status, Date sharefrom, Date shareto, String securecode) {
       this.id = id;
       this.iduser = iduser;
       this.idEntity = idEntity;
       this.typeAccess = typeAccess;
       this.status = status;
       this.sharefrom = sharefrom;
       this.shareto = shareto;
       this.securecode = securecode;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="goalRefNo", column=@Column(name="GOAL_REF_NO", nullable=false, length=15) ), 
        @AttributeOverride(name="typeCommChnl", column=@Column(name="TYPE_COMM_CHNL", nullable=false, length=2) ), 
        @AttributeOverride(name="idCommChnl", column=@Column(name="ID_COMM_CHNL", nullable=false) ) } )
    public GoalShareId getId() {
        return this.id;
    }
    
    public void setId(GoalShareId id) {
        this.id = id;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="TYPE_ACCESS", length=1)
    public Character getTypeAccess() {
        return this.typeAccess;
    }
    
    public void setTypeAccess(Character typeAccess) {
        this.typeAccess = typeAccess;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SHAREFROM", length=7)
    public Date getSharefrom() {
        return this.sharefrom;
    }
    
    public void setSharefrom(Date sharefrom) {
        this.sharefrom = sharefrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SHARETO", length=7)
    public Date getShareto() {
        return this.shareto;
    }
    
    public void setShareto(Date shareto) {
        this.shareto = shareto;
    }

    
    @Column(name="SECURECODE")
    public String getSecurecode() {
        return this.securecode;
    }
    
    public void setSecurecode(String securecode) {
        this.securecode = securecode;
    }




}


