package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HandoffAuditLog generated by hbm2java
 */
@Entity
@Table(name="HANDOFF_AUDIT_LOG"
    ,schema="FCDBADMIN_RK"
)
public class HandoffAuditLog  implements java.io.Serializable {


     private HandoffAuditLogId id;
     private Character recordtype;
     private byte[] handoffMsg;
     private Character msgstatus;
     private Date lastupddatetime;
     private String errmsg;
     private Long idrecord;

    public HandoffAuditLog() {
    }

	
    public HandoffAuditLog(HandoffAuditLogId id) {
        this.id = id;
    }
    public HandoffAuditLog(HandoffAuditLogId id, Character recordtype, byte[] handoffMsg, Character msgstatus, Date lastupddatetime, String errmsg, Long idrecord) {
       this.id = id;
       this.recordtype = recordtype;
       this.handoffMsg = handoffMsg;
       this.msgstatus = msgstatus;
       this.lastupddatetime = lastupddatetime;
       this.errmsg = errmsg;
       this.idrecord = idrecord;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idseq", column=@Column(name="IDSEQ", nullable=false, precision=18, scale=0) ), 
        @AttributeOverride(name="handoffname", column=@Column(name="HANDOFFNAME", nullable=false, length=50) ), 
        @AttributeOverride(name="recvddatetime", column=@Column(name="RECVDDATETIME", nullable=false, length=7) ) } )
    public HandoffAuditLogId getId() {
        return this.id;
    }
    
    public void setId(HandoffAuditLogId id) {
        this.id = id;
    }

    
    @Column(name="RECORDTYPE", length=1)
    public Character getRecordtype() {
        return this.recordtype;
    }
    
    public void setRecordtype(Character recordtype) {
        this.recordtype = recordtype;
    }

    
    @Column(name="HANDOFF_MSG")
    public byte[] getHandoffMsg() {
        return this.handoffMsg;
    }
    
    public void setHandoffMsg(byte[] handoffMsg) {
        this.handoffMsg = handoffMsg;
    }

    
    @Column(name="MSGSTATUS", length=1)
    public Character getMsgstatus() {
        return this.msgstatus;
    }
    
    public void setMsgstatus(Character msgstatus) {
        this.msgstatus = msgstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDDATETIME", length=7)
    public Date getLastupddatetime() {
        return this.lastupddatetime;
    }
    
    public void setLastupddatetime(Date lastupddatetime) {
        this.lastupddatetime = lastupddatetime;
    }

    
    @Column(name="ERRMSG", length=4000)
    public String getErrmsg() {
        return this.errmsg;
    }
    
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg;
    }

    
    @Column(name="IDRECORD", precision=18, scale=0)
    public Long getIdrecord() {
        return this.idrecord;
    }
    
    public void setIdrecord(Long idrecord) {
        this.idrecord = idrecord;
    }




}


