package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HostErrorCodes generated by hbm2java
 */
@Entity
@Table(name="HOST_ERROR_CODES"
    ,schema="FCDBADMIN_RK"
)
public class HostErrorCodes  implements java.io.Serializable {


     private HostErrorCodesId id;
     private String txterror;
     private String idmessage;
     private String isignorable;

    public HostErrorCodes() {
    }

	
    public HostErrorCodes(HostErrorCodesId id) {
        this.id = id;
    }
    public HostErrorCodes(HostErrorCodesId id, String txterror, String idmessage, String isignorable) {
       this.id = id;
       this.txterror = txterror;
       this.idmessage = idmessage;
       this.isignorable = isignorable;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idhost", column=@Column(name="IDHOST", nullable=false, length=20) ), 
        @AttributeOverride(name="coderror", column=@Column(name="CODERROR", nullable=false, length=20) ) } )
    public HostErrorCodesId getId() {
        return this.id;
    }
    
    public void setId(HostErrorCodesId id) {
        this.id = id;
    }

    
    @Column(name="TXTERROR")
    public String getTxterror() {
        return this.txterror;
    }
    
    public void setTxterror(String txterror) {
        this.txterror = txterror;
    }

    
    @Column(name="IDMESSAGE", length=20)
    public String getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(String idmessage) {
        this.idmessage = idmessage;
    }

    
    @Column(name="ISIGNORABLE", length=1)
    public String getIsignorable() {
        return this.isignorable;
    }
    
    public void setIsignorable(String isignorable) {
        this.isignorable = isignorable;
    }




}


