package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Hostudfmap generated by hbm2java
 */
@Entity
@Table(name="HOSTUDFMAP"
    ,schema="FCDBADMIN_RK"
)
public class Hostudfmap  implements java.io.Serializable {


     private HostudfmapId id;
     private String fieldName;
     private Short fieldNum;
     private Character isenabled;

    public Hostudfmap() {
    }

	
    public Hostudfmap(HostudfmapId id) {
        this.id = id;
    }
    public Hostudfmap(HostudfmapId id, String fieldName, Short fieldNum, Character isenabled) {
       this.id = id;
       this.fieldName = fieldName;
       this.fieldNum = fieldNum;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="identity", column=@Column(name="IDENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="functionId", column=@Column(name="FUNCTION_ID", nullable=false, length=8) ), 
        @AttributeOverride(name="idudf", column=@Column(name="IDUDF", nullable=false, length=25) ) } )
    public HostudfmapId getId() {
        return this.id;
    }
    
    public void setId(HostudfmapId id) {
        this.id = id;
    }

    
    @Column(name="FIELD_NAME", length=105)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    
    @Column(name="FIELD_NUM", precision=3, scale=0)
    public Short getFieldNum() {
        return this.fieldNum;
    }
    
    public void setFieldNum(Short fieldNum) {
        this.fieldNum = fieldNum;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }




}


