package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IsCustUhMap generated by hbm2java
 */
@Entity
@Table(name="IS_CUST_UH_MAP"
    ,schema="FCDBADMIN_RK"
)
public class IsCustUhMap  implements java.io.Serializable {


     private IsCustUhMapId id;
     private String codprefdividendmode;
     private String codprefredemptionmode;
     private String namuser;
     private String codcurruserpref;
     private String txtemail;
     private String namusernic;
     private String idhost;
     private String namuh;
     private Character maruyueligibility;
     private String contactaddr;
     private String acctcurr;
     private String acctfreq;
     private Long blockamt;
     private String blockcurr;
     private String codprefdeliverymode;
     private String uhcategory;
     private String investortype;
     private Character flagrestricthandoff;
     private Long numseq;
     private Date datofbirth;
     private Set<IsOrderstatusinquirydetails> isOrderstatusinquirydetailses = new HashSet<IsOrderstatusinquirydetails>(0);

    public IsCustUhMap() {
    }

	
    public IsCustUhMap(IsCustUhMapId id) {
        this.id = id;
    }
    public IsCustUhMap(IsCustUhMapId id, String codprefdividendmode, String codprefredemptionmode, String namuser, String codcurruserpref, String txtemail, String namusernic, String idhost, String namuh, Character maruyueligibility, String contactaddr, String acctcurr, String acctfreq, Long blockamt, String blockcurr, String codprefdeliverymode, String uhcategory, String investortype, Character flagrestricthandoff, Long numseq, Date datofbirth, Set<IsOrderstatusinquirydetails> isOrderstatusinquirydetailses) {
       this.id = id;
       this.codprefdividendmode = codprefdividendmode;
       this.codprefredemptionmode = codprefredemptionmode;
       this.namuser = namuser;
       this.codcurruserpref = codcurruserpref;
       this.txtemail = txtemail;
       this.namusernic = namusernic;
       this.idhost = idhost;
       this.namuh = namuh;
       this.maruyueligibility = maruyueligibility;
       this.contactaddr = contactaddr;
       this.acctcurr = acctcurr;
       this.acctfreq = acctfreq;
       this.blockamt = blockamt;
       this.blockcurr = blockcurr;
       this.codprefdeliverymode = codprefdeliverymode;
       this.uhcategory = uhcategory;
       this.investortype = investortype;
       this.flagrestricthandoff = flagrestricthandoff;
       this.numseq = numseq;
       this.datofbirth = datofbirth;
       this.isOrderstatusinquirydetailses = isOrderstatusinquirydetailses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false) ), 
        @AttributeOverride(name="iduh", column=@Column(name="IDUH", nullable=false, length=16) ) } )
    public IsCustUhMapId getId() {
        return this.id;
    }
    
    public void setId(IsCustUhMapId id) {
        this.id = id;
    }

    
    @Column(name="CODPREFDIVIDENDMODE", length=25)
    public String getCodprefdividendmode() {
        return this.codprefdividendmode;
    }
    
    public void setCodprefdividendmode(String codprefdividendmode) {
        this.codprefdividendmode = codprefdividendmode;
    }

    
    @Column(name="CODPREFREDEMPTIONMODE", length=25)
    public String getCodprefredemptionmode() {
        return this.codprefredemptionmode;
    }
    
    public void setCodprefredemptionmode(String codprefredemptionmode) {
        this.codprefredemptionmode = codprefredemptionmode;
    }

    
    @Column(name="NAMUSER", length=30)
    public String getNamuser() {
        return this.namuser;
    }
    
    public void setNamuser(String namuser) {
        this.namuser = namuser;
    }

    
    @Column(name="CODCURRUSERPREF", length=3)
    public String getCodcurruserpref() {
        return this.codcurruserpref;
    }
    
    public void setCodcurruserpref(String codcurruserpref) {
        this.codcurruserpref = codcurruserpref;
    }

    
    @Column(name="TXTEMAIL")
    public String getTxtemail() {
        return this.txtemail;
    }
    
    public void setTxtemail(String txtemail) {
        this.txtemail = txtemail;
    }

    
    @Column(name="NAMUSERNIC", length=30)
    public String getNamusernic() {
        return this.namusernic;
    }
    
    public void setNamusernic(String namusernic) {
        this.namusernic = namusernic;
    }

    
    @Column(name="IDHOST", length=2)
    public String getIdhost() {
        return this.idhost;
    }
    
    public void setIdhost(String idhost) {
        this.idhost = idhost;
    }

    
    @Column(name="NAMUH", length=25)
    public String getNamuh() {
        return this.namuh;
    }
    
    public void setNamuh(String namuh) {
        this.namuh = namuh;
    }

    
    @Column(name="MARUYUELIGIBILITY", length=1)
    public Character getMaruyueligibility() {
        return this.maruyueligibility;
    }
    
    public void setMaruyueligibility(Character maruyueligibility) {
        this.maruyueligibility = maruyueligibility;
    }

    
    @Column(name="CONTACTADDR")
    public String getContactaddr() {
        return this.contactaddr;
    }
    
    public void setContactaddr(String contactaddr) {
        this.contactaddr = contactaddr;
    }

    
    @Column(name="ACCTCURR", length=3)
    public String getAcctcurr() {
        return this.acctcurr;
    }
    
    public void setAcctcurr(String acctcurr) {
        this.acctcurr = acctcurr;
    }

    
    @Column(name="ACCTFREQ", length=1)
    public String getAcctfreq() {
        return this.acctfreq;
    }
    
    public void setAcctfreq(String acctfreq) {
        this.acctfreq = acctfreq;
    }

    
    @Column(name="BLOCKAMT", precision=13, scale=0)
    public Long getBlockamt() {
        return this.blockamt;
    }
    
    public void setBlockamt(Long blockamt) {
        this.blockamt = blockamt;
    }

    
    @Column(name="BLOCKCURR", length=3)
    public String getBlockcurr() {
        return this.blockcurr;
    }
    
    public void setBlockcurr(String blockcurr) {
        this.blockcurr = blockcurr;
    }

    
    @Column(name="CODPREFDELIVERYMODE", length=25)
    public String getCodprefdeliverymode() {
        return this.codprefdeliverymode;
    }
    
    public void setCodprefdeliverymode(String codprefdeliverymode) {
        this.codprefdeliverymode = codprefdeliverymode;
    }

    
    @Column(name="UHCATEGORY", length=30)
    public String getUhcategory() {
        return this.uhcategory;
    }
    
    public void setUhcategory(String uhcategory) {
        this.uhcategory = uhcategory;
    }

    
    @Column(name="INVESTORTYPE", length=30)
    public String getInvestortype() {
        return this.investortype;
    }
    
    public void setInvestortype(String investortype) {
        this.investortype = investortype;
    }

    
    @Column(name="FLAGRESTRICTHANDOFF", length=1)
    public Character getFlagrestricthandoff() {
        return this.flagrestricthandoff;
    }
    
    public void setFlagrestricthandoff(Character flagrestricthandoff) {
        this.flagrestricthandoff = flagrestricthandoff;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATOFBIRTH", length=7)
    public Date getDatofbirth() {
        return this.datofbirth;
    }
    
    public void setDatofbirth(Date datofbirth) {
        this.datofbirth = datofbirth;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="isCustUhMap")
    public Set<IsOrderstatusinquirydetails> getIsOrderstatusinquirydetailses() {
        return this.isOrderstatusinquirydetailses;
    }
    
    public void setIsOrderstatusinquirydetailses(Set<IsOrderstatusinquirydetails> isOrderstatusinquirydetailses) {
        this.isOrderstatusinquirydetailses = isOrderstatusinquirydetailses;
    }




}


