package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IsLimitorderdetails generated by hbm2java
 */
@Entity
@Table(name="IS_LIMITORDERDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class IsLimitorderdetails  implements java.io.Serializable {


     private IsLimitorderdetailsId id;
     private Mstentity mstentity;
     private String limitordertype;
     private String limitorderstatus;
     private Double limitprice;
     private Date limitdate;
     private Date limitstartdate;
     private Date limitenddate;
     private Date settlementdate;
     private String limitstatus;
     private Date limitgendate;
     private Long numseq;

    public IsLimitorderdetails() {
    }

	
    public IsLimitorderdetails(IsLimitorderdetailsId id, Mstentity mstentity) {
        this.id = id;
        this.mstentity = mstentity;
    }
    public IsLimitorderdetails(IsLimitorderdetailsId id, Mstentity mstentity, String limitordertype, String limitorderstatus, Double limitprice, Date limitdate, Date limitstartdate, Date limitenddate, Date settlementdate, String limitstatus, Date limitgendate, Long numseq) {
       this.id = id;
       this.mstentity = mstentity;
       this.limitordertype = limitordertype;
       this.limitorderstatus = limitorderstatus;
       this.limitprice = limitprice;
       this.limitdate = limitdate;
       this.limitstartdate = limitstartdate;
       this.limitenddate = limitenddate;
       this.settlementdate = settlementdate;
       this.limitstatus = limitstatus;
       this.limitgendate = limitgendate;
       this.numseq = numseq;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="txnnumber", column=@Column(name="TXNNUMBER", nullable=false, length=25) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false) ), 
        @AttributeOverride(name="iduh", column=@Column(name="IDUH", nullable=false, length=16) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ) } )
    public IsLimitorderdetailsId getId() {
        return this.id;
    }
    
    public void setId(IsLimitorderdetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

    
    @Column(name="LIMITORDERTYPE", length=10)
    public String getLimitordertype() {
        return this.limitordertype;
    }
    
    public void setLimitordertype(String limitordertype) {
        this.limitordertype = limitordertype;
    }

    
    @Column(name="LIMITORDERSTATUS", length=15)
    public String getLimitorderstatus() {
        return this.limitorderstatus;
    }
    
    public void setLimitorderstatus(String limitorderstatus) {
        this.limitorderstatus = limitorderstatus;
    }

    
    @Column(name="LIMITPRICE", precision=126, scale=0)
    public Double getLimitprice() {
        return this.limitprice;
    }
    
    public void setLimitprice(Double limitprice) {
        this.limitprice = limitprice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LIMITDATE", length=7)
    public Date getLimitdate() {
        return this.limitdate;
    }
    
    public void setLimitdate(Date limitdate) {
        this.limitdate = limitdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LIMITSTARTDATE", length=7)
    public Date getLimitstartdate() {
        return this.limitstartdate;
    }
    
    public void setLimitstartdate(Date limitstartdate) {
        this.limitstartdate = limitstartdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LIMITENDDATE", length=7)
    public Date getLimitenddate() {
        return this.limitenddate;
    }
    
    public void setLimitenddate(Date limitenddate) {
        this.limitenddate = limitenddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SETTLEMENTDATE", length=7)
    public Date getSettlementdate() {
        return this.settlementdate;
    }
    
    public void setSettlementdate(Date settlementdate) {
        this.settlementdate = settlementdate;
    }

    
    @Column(name="LIMITSTATUS", length=15)
    public String getLimitstatus() {
        return this.limitstatus;
    }
    
    public void setLimitstatus(String limitstatus) {
        this.limitstatus = limitstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LIMITGENDATE", length=7)
    public Date getLimitgendate() {
        return this.limitgendate;
    }
    
    public void setLimitgendate(Date limitgendate) {
        this.limitgendate = limitgendate;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }




}


