package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsLkpscrip generated by hbm2java
 */
@Entity
@Table(name="IS_LKPSCRIP"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "CODSCRIP"}) 
)
public class IsLkpscrip  implements java.io.Serializable {


     private String codscrip;
     private Mstentity mstentity;

    public IsLkpscrip() {
    }

	
    public IsLkpscrip(String codscrip) {
        this.codscrip = codscrip;
    }
    public IsLkpscrip(String codscrip, Mstentity mstentity) {
       this.codscrip = codscrip;
       this.mstentity = mstentity;
    }
   
     @Id 

    
    @Column(name="CODSCRIP", unique=true, nullable=false, length=25)
    public String getCodscrip() {
        return this.codscrip;
    }
    
    public void setCodscrip(String codscrip) {
        this.codscrip = codscrip;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY")
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }




}


