package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IsLkpcurr generated by hbm2java
 */
@Entity
@Table(name="IS_LKPCURR"
    ,schema="FCDBADMIN_RK"
)
public class IsLkpcurr  implements java.io.Serializable {


     private IsLkpcurrId id;
     private Mstentity mstentity;

    public IsLkpcurr() {
    }

    public IsLkpcurr(IsLkpcurrId id, Mstentity mstentity) {
       this.id = id;
       this.mstentity = mstentity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="codcurr", column=@Column(name="CODCURR", nullable=false, length=3) ) } )
    public IsLkpcurrId getId() {
        return this.id;
    }
    
    public void setId(IsLkpcurrId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }




}


