package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IsMstfundtxn generated by hbm2java
 */
@Entity
@Table(name="IS_MSTFUNDTXN"
    ,schema="FCDBADMIN_RK"
)
public class IsMstfundtxn  implements java.io.Serializable {


     private IsMstfundtxnId id;
     private IsMstfund isMstfund;
     private Long numseq;
     private Date datstart;
     private Date datclose;
     private String enabled;
     private BigDecimal mininvestallowed;
     private BigDecimal maxinvestallowed;
     private BigDecimal stepamt;
     private BigDecimal minunitallowed;
     private BigDecimal maxunitallowed;
     private BigDecimal stepunits;
     private Date cutofftime;

    public IsMstfundtxn() {
    }

	
    public IsMstfundtxn(IsMstfundtxnId id, IsMstfund isMstfund) {
        this.id = id;
        this.isMstfund = isMstfund;
    }
    public IsMstfundtxn(IsMstfundtxnId id, IsMstfund isMstfund, Long numseq, Date datstart, Date datclose, String enabled, BigDecimal mininvestallowed, BigDecimal maxinvestallowed, BigDecimal stepamt, BigDecimal minunitallowed, BigDecimal maxunitallowed, BigDecimal stepunits, Date cutofftime) {
       this.id = id;
       this.isMstfund = isMstfund;
       this.numseq = numseq;
       this.datstart = datstart;
       this.datclose = datclose;
       this.enabled = enabled;
       this.mininvestallowed = mininvestallowed;
       this.maxinvestallowed = maxinvestallowed;
       this.stepamt = stepamt;
       this.minunitallowed = minunitallowed;
       this.maxunitallowed = maxunitallowed;
       this.stepunits = stepunits;
       this.cutofftime = cutofftime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idfund", column=@Column(name="IDFUND", nullable=false, length=10) ), 
        @AttributeOverride(name="codtxn", column=@Column(name="CODTXN", nullable=false, length=25) ) } )
    public IsMstfundtxnId getId() {
        return this.id;
    }
    
    public void setId(IsMstfundtxnId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDFUND", referencedColumnName="IDFUND", nullable=false, insertable=false, updatable=false) } )
    public IsMstfund getIsMstfund() {
        return this.isMstfund;
    }
    
    public void setIsMstfund(IsMstfund isMstfund) {
        this.isMstfund = isMstfund;
    }

    
    @Column(name="NUMSEQ", precision=18, scale=0)
    public Long getNumseq() {
        return this.numseq;
    }
    
    public void setNumseq(Long numseq) {
        this.numseq = numseq;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATSTART", length=7)
    public Date getDatstart() {
        return this.datstart;
    }
    
    public void setDatstart(Date datstart) {
        this.datstart = datstart;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCLOSE", length=7)
    public Date getDatclose() {
        return this.datclose;
    }
    
    public void setDatclose(Date datclose) {
        this.datclose = datclose;
    }

    
    @Column(name="ENABLED", length=2)
    public String getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    
    @Column(name="MININVESTALLOWED", precision=20, scale=3)
    public BigDecimal getMininvestallowed() {
        return this.mininvestallowed;
    }
    
    public void setMininvestallowed(BigDecimal mininvestallowed) {
        this.mininvestallowed = mininvestallowed;
    }

    
    @Column(name="MAXINVESTALLOWED", precision=20, scale=3)
    public BigDecimal getMaxinvestallowed() {
        return this.maxinvestallowed;
    }
    
    public void setMaxinvestallowed(BigDecimal maxinvestallowed) {
        this.maxinvestallowed = maxinvestallowed;
    }

    
    @Column(name="STEPAMT", precision=20, scale=3)
    public BigDecimal getStepamt() {
        return this.stepamt;
    }
    
    public void setStepamt(BigDecimal stepamt) {
        this.stepamt = stepamt;
    }

    
    @Column(name="MINUNITALLOWED", precision=20, scale=0)
    public BigDecimal getMinunitallowed() {
        return this.minunitallowed;
    }
    
    public void setMinunitallowed(BigDecimal minunitallowed) {
        this.minunitallowed = minunitallowed;
    }

    
    @Column(name="MAXUNITALLOWED", precision=20, scale=0)
    public BigDecimal getMaxunitallowed() {
        return this.maxunitallowed;
    }
    
    public void setMaxunitallowed(BigDecimal maxunitallowed) {
        this.maxunitallowed = maxunitallowed;
    }

    
    @Column(name="STEPUNITS", precision=20, scale=0)
    public BigDecimal getStepunits() {
        return this.stepunits;
    }
    
    public void setStepunits(BigDecimal stepunits) {
        this.stepunits = stepunits;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CUTOFFTIME", length=7)
    public Date getCutofftime() {
        return this.cutofftime;
    }
    
    public void setCutofftime(Date cutofftime) {
        this.cutofftime = cutofftime;
    }




}


