package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IsRuleData generated by hbm2java
 */
@Entity
@Table(name="IS_RULE_DATA"
    ,schema="FCDBADMIN_RK"
)
public class IsRuleData  implements java.io.Serializable {


     private IsRuleDataId id;
     private Byte errorType;
     private String isenabled;

    public IsRuleData() {
    }

	
    public IsRuleData(IsRuleDataId id) {
        this.id = id;
    }
    public IsRuleData(IsRuleDataId id, Byte errorType, String isenabled) {
       this.id = id;
       this.errorType = errorType;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=7) ), 
        @AttributeOverride(name="numsequence", column=@Column(name="NUMSEQUENCE", nullable=false, length=2) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ), 
        @AttributeOverride(name="rulesequence", column=@Column(name="RULESEQUENCE", nullable=false, precision=2, scale=0) ) } )
    public IsRuleDataId getId() {
        return this.id;
    }
    
    public void setId(IsRuleDataId id) {
        this.id = id;
    }

    
    @Column(name="ERROR_TYPE", precision=2, scale=0)
    public Byte getErrorType() {
        return this.errorType;
    }
    
    public void setErrorType(Byte errorType) {
        this.errorType = errorType;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }




}


