package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Clob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LctbsDocumentsTmp generated by hbm2java
 */
@Entity
@Table(name="LCTBS_DOCUMENTS_TMP"
    ,schema="FCDBADMIN_RK"
)
public class LctbsDocumentsTmp  implements java.io.Serializable {


     private LctbsDocumentsTmpId id;
     private Short versionNo;
     private String eventCode;
     private Short docSlNo;
     private Character docType;
     private Clob docDescr;
     private Character docOriginal;
     private Short docCopies;
     private String noOfOriginals;
     private String docReference;

    public LctbsDocumentsTmp() {
    }

	
    public LctbsDocumentsTmp(LctbsDocumentsTmpId id) {
        this.id = id;
    }
    public LctbsDocumentsTmp(LctbsDocumentsTmpId id, Short versionNo, String eventCode, Short docSlNo, Character docType, Clob docDescr, Character docOriginal, Short docCopies, String noOfOriginals, String docReference) {
       this.id = id;
       this.versionNo = versionNo;
       this.eventCode = eventCode;
       this.docSlNo = docSlNo;
       this.docType = docType;
       this.docDescr = docDescr;
       this.docOriginal = docOriginal;
       this.docCopies = docCopies;
       this.noOfOriginals = noOfOriginals;
       this.docReference = docReference;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="contractRefNo", column=@Column(name="CONTRACT_REF_NO", nullable=false, length=16) ), 
        @AttributeOverride(name="eventSeqNo", column=@Column(name="EVENT_SEQ_NO", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="docCode", column=@Column(name="DOC_CODE", nullable=false, length=12) ) } )
    public LctbsDocumentsTmpId getId() {
        return this.id;
    }
    
    public void setId(LctbsDocumentsTmpId id) {
        this.id = id;
    }

    
    @Column(name="VERSION_NO", precision=4, scale=0)
    public Short getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Short versionNo) {
        this.versionNo = versionNo;
    }

    
    @Column(name="EVENT_CODE", length=4)
    public String getEventCode() {
        return this.eventCode;
    }
    
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode;
    }

    
    @Column(name="DOC_SL_NO", precision=4, scale=0)
    public Short getDocSlNo() {
        return this.docSlNo;
    }
    
    public void setDocSlNo(Short docSlNo) {
        this.docSlNo = docSlNo;
    }

    
    @Column(name="DOC_TYPE", length=1)
    public Character getDocType() {
        return this.docType;
    }
    
    public void setDocType(Character docType) {
        this.docType = docType;
    }

    
    @Column(name="DOC_DESCR")
    public Clob getDocDescr() {
        return this.docDescr;
    }
    
    public void setDocDescr(Clob docDescr) {
        this.docDescr = docDescr;
    }

    
    @Column(name="DOC_ORIGINAL", length=1)
    public Character getDocOriginal() {
        return this.docOriginal;
    }
    
    public void setDocOriginal(Character docOriginal) {
        this.docOriginal = docOriginal;
    }

    
    @Column(name="DOC_COPIES", precision=4, scale=0)
    public Short getDocCopies() {
        return this.docCopies;
    }
    
    public void setDocCopies(Short docCopies) {
        this.docCopies = docCopies;
    }

    
    @Column(name="NO_OF_ORIGINALS", length=5)
    public String getNoOfOriginals() {
        return this.noOfOriginals;
    }
    
    public void setNoOfOriginals(String noOfOriginals) {
        this.noOfOriginals = noOfOriginals;
    }

    
    @Column(name="DOC_REFERENCE", length=105)
    public String getDocReference() {
        return this.docReference;
    }
    
    public void setDocReference(String docReference) {
        this.docReference = docReference;
    }




}


