package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Livehelperrorconfig generated by hbm2java
 */
@Entity
@Table(name="LIVEHELPERRORCONFIG"
    ,schema="FCDBADMIN_RK"
)
public class Livehelperrorconfig  implements java.io.Serializable {


     private LivehelperrorconfigId id;
     private String idmodule;
     private Byte priority;
     private String idlang;

    public Livehelperrorconfig() {
    }

	
    public Livehelperrorconfig(LivehelperrorconfigId id) {
        this.id = id;
    }
    public Livehelperrorconfig(LivehelperrorconfigId id, String idmodule, Byte priority, String idlang) {
       this.id = id;
       this.idmodule = idmodule;
       this.priority = priority;
       this.idlang = idlang;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idmessage", column=@Column(name="IDMESSAGE", nullable=false, length=20) ) } )
    public LivehelperrorconfigId getId() {
        return this.id;
    }
    
    public void setId(LivehelperrorconfigId id) {
        this.id = id;
    }

    
    @Column(name="IDMODULE", length=10)
    public String getIdmodule() {
        return this.idmodule;
    }
    
    public void setIdmodule(String idmodule) {
        this.idmodule = idmodule;
    }

    
    @Column(name="PRIORITY", precision=2, scale=0)
    public Byte getPriority() {
        return this.priority;
    }
    
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    
    @Column(name="IDLANG", length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }




}


