package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mailmessage generated by hbm2java
 */
@Entity
@Table(name="MAILMESSAGE"
    ,schema="FCDBADMIN_RK"
)
public class Mailmessage  implements java.io.Serializable {


     private String messageid;
     private Mstentity mstentity;
     private Mstuser mstuserByRespondedby;
     private Mstuser mstuserByRecieveruserid;
     private Mstuser mstuserBySenderid;
     private String linkedid;
     private String sendername;
     private String recievername;
     private String recieverroleid;
     private String idchannel;
     private String subjectid;
     private String messagetype;
     private Blob message;
     private Date senddate;
     private String folderid;
     private Date respondeddate;
     private Character readbyuser;
     private Date expires;
     private BigDecimal statebit;
     private Character typemessage;
     private String customSubject;
     private Character iscust;

    public Mailmessage() {
    }

	
    public Mailmessage(String messageid) {
        this.messageid = messageid;
    }
    public Mailmessage(String messageid, Mstentity mstentity, Mstuser mstuserByRespondedby, Mstuser mstuserByRecieveruserid, Mstuser mstuserBySenderid, String linkedid, String sendername, String recievername, String recieverroleid, String idchannel, String subjectid, String messagetype, Blob message, Date senddate, String folderid, Date respondeddate, Character readbyuser, Date expires, BigDecimal statebit, Character typemessage, String customSubject, Character iscust) {
       this.messageid = messageid;
       this.mstentity = mstentity;
       this.mstuserByRespondedby = mstuserByRespondedby;
       this.mstuserByRecieveruserid = mstuserByRecieveruserid;
       this.mstuserBySenderid = mstuserBySenderid;
       this.linkedid = linkedid;
       this.sendername = sendername;
       this.recievername = recievername;
       this.recieverroleid = recieverroleid;
       this.idchannel = idchannel;
       this.subjectid = subjectid;
       this.messagetype = messagetype;
       this.message = message;
       this.senddate = senddate;
       this.folderid = folderid;
       this.respondeddate = respondeddate;
       this.readbyuser = readbyuser;
       this.expires = expires;
       this.statebit = statebit;
       this.typemessage = typemessage;
       this.customSubject = customSubject;
       this.iscust = iscust;
    }
   
     @Id 

    
    @Column(name="MESSAGEID", unique=true, nullable=false, length=40)
    public String getMessageid() {
        return this.messageid;
    }
    
    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY")
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESPONDEDBY")
    public Mstuser getMstuserByRespondedby() {
        return this.mstuserByRespondedby;
    }
    
    public void setMstuserByRespondedby(Mstuser mstuserByRespondedby) {
        this.mstuserByRespondedby = mstuserByRespondedby;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RECIEVERUSERID")
    public Mstuser getMstuserByRecieveruserid() {
        return this.mstuserByRecieveruserid;
    }
    
    public void setMstuserByRecieveruserid(Mstuser mstuserByRecieveruserid) {
        this.mstuserByRecieveruserid = mstuserByRecieveruserid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SENDERID")
    public Mstuser getMstuserBySenderid() {
        return this.mstuserBySenderid;
    }
    
    public void setMstuserBySenderid(Mstuser mstuserBySenderid) {
        this.mstuserBySenderid = mstuserBySenderid;
    }

    
    @Column(name="LINKEDID", length=40)
    public String getLinkedid() {
        return this.linkedid;
    }
    
    public void setLinkedid(String linkedid) {
        this.linkedid = linkedid;
    }

    
    @Column(name="SENDERNAME", length=40)
    public String getSendername() {
        return this.sendername;
    }
    
    public void setSendername(String sendername) {
        this.sendername = sendername;
    }

    
    @Column(name="RECIEVERNAME", length=40)
    public String getRecievername() {
        return this.recievername;
    }
    
    public void setRecievername(String recievername) {
        this.recievername = recievername;
    }

    
    @Column(name="RECIEVERROLEID", length=60)
    public String getRecieverroleid() {
        return this.recieverroleid;
    }
    
    public void setRecieverroleid(String recieverroleid) {
        this.recieverroleid = recieverroleid;
    }

    
    @Column(name="IDCHANNEL", length=4)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    
    @Column(name="SUBJECTID", length=20)
    public String getSubjectid() {
        return this.subjectid;
    }
    
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }

    
    @Column(name="MESSAGETYPE", length=50)
    public String getMessagetype() {
        return this.messagetype;
    }
    
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype;
    }

    
    @Column(name="MESSAGE")
    public Blob getMessage() {
        return this.message;
    }
    
    public void setMessage(Blob message) {
        this.message = message;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SENDDATE", length=7)
    public Date getSenddate() {
        return this.senddate;
    }
    
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    
    @Column(name="FOLDERID", length=10)
    public String getFolderid() {
        return this.folderid;
    }
    
    public void setFolderid(String folderid) {
        this.folderid = folderid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RESPONDEDDATE", length=7)
    public Date getRespondeddate() {
        return this.respondeddate;
    }
    
    public void setRespondeddate(Date respondeddate) {
        this.respondeddate = respondeddate;
    }

    
    @Column(name="READBYUSER", length=1)
    public Character getReadbyuser() {
        return this.readbyuser;
    }
    
    public void setReadbyuser(Character readbyuser) {
        this.readbyuser = readbyuser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRES", length=7)
    public Date getExpires() {
        return this.expires;
    }
    
    public void setExpires(Date expires) {
        this.expires = expires;
    }

    
    @Column(name="STATEBIT", precision=22, scale=0)
    public BigDecimal getStatebit() {
        return this.statebit;
    }
    
    public void setStatebit(BigDecimal statebit) {
        this.statebit = statebit;
    }

    
    @Column(name="TYPEMESSAGE", length=1)
    public Character getTypemessage() {
        return this.typemessage;
    }
    
    public void setTypemessage(Character typemessage) {
        this.typemessage = typemessage;
    }

    
    @Column(name="CUSTOM_SUBJECT")
    public String getCustomSubject() {
        return this.customSubject;
    }
    
    public void setCustomSubject(String customSubject) {
        this.customSubject = customSubject;
    }

    
    @Column(name="ISCUST", length=1)
    public Character getIscust() {
        return this.iscust;
    }
    
    public void setIscust(Character iscust) {
        this.iscust = iscust;
    }




}


