package com.jmr.obdx.domain;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * McxAuditLog generated by hbm2java
 */
@Entity
@Table(name="MCX_AUDIT_LOG"
    ,schema="JMR_OBDX"
)
public class McxAuditLog  implements java.io.Serializable {


     private long id;
     private long mcxUserM;
     private McxTransactionM mcxTransactionM;
     private String txnReferance;
     private byte [] request;
     private byte [] response;
     private String errorCode;
     private String errorDesc;
     private Date txnDate;
     private String status;
     private String hostRefNo;

    public McxAuditLog() {
    }

	
    public McxAuditLog(long id) {
        this.id = id;
    }
    public McxAuditLog( long mcxUserM, McxTransactionM mcxTransactionM, String txnReferance, byte [] request, byte [] response, String errorCode, String errorDesc, Date txnDate, String status, String hostRefNo) {
       this.id = id;
       this.mcxUserM = mcxUserM;
       this.mcxTransactionM = mcxTransactionM;
       this.txnReferance = txnReferance;
       this.request = request;
       this.response = response;
       this.errorCode = errorCode;
       this.errorDesc = errorDesc;
       this.txnDate = txnDate;
       this.status = status;
       this.hostRefNo = hostRefNo;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

/*@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER")*/
    @Column(name="ID_USER", length=150)

    public long getMcxUserM() {
        return this.mcxUserM;
    }
    
    public void setMcxUserM(long mcxUserM) {
        this.mcxUserM = mcxUserM;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TXN")
    public McxTransactionM getMcxTransactionM() {
        return this.mcxTransactionM;
    }
    
    public void setMcxTransactionM(McxTransactionM mcxTransactionM) {
        this.mcxTransactionM = mcxTransactionM;
    }

    
    @Column(name="TXN_REFERANCE", length=150)
    public String getTxnReferance() {
        return this.txnReferance;
    }
    
    public void setTxnReferance(String txnReferance) {
        this.txnReferance = txnReferance;
    }

    
    @Column(name="REQUEST", length=1000)
    public byte [] getRequest() {
        return this.request;
    }
    
    public void setRequest(byte [] request) {
        this.request = request;
    }

    
    @Column(name="RESPONSE", length=1000)
    public byte [] getResponse() {
        return this.response;
    }
    
    public void setResponse(byte [] response) {
        this.response = response;
    }

    
    @Column(name="ERROR_CODE", precision=22, scale=0)
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    
    @Column(name="ERROR_DESC", length=10)
    public String getErrorDesc() {
        return this.errorDesc;
    }
    
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TXNS_DATE", length=7)
    public Date getTxnDate() {
        return this.txnDate;
    }
    
    public void setTxnDate(Date txnDate) {
        this.txnDate = txnDate;
    }

    
    @Column(name="STATUS", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="HOST_REF_NO", length=0)
    public String getHostRefNo() {
        return this.hostRefNo;
    }
    
    public void setHostRefNo(String hostRefNo) {
        this.hostRefNo = hostRefNo;
    }




}


