package com.jmr.obdx.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * McxEntityM generated by hbm2java
 */
@Entity
@Table(name="MCX_ENTITY_M"
    ,schema="JMR_OBDX"
    , uniqueConstraints = {@UniqueConstraint(columnNames="ENTITY"), @UniqueConstraint(columnNames="DESCRIPTION")} 
)
public class McxEntityM  implements java.io.Serializable {


     private long id;
     private String entity;
     private String description;
     private Character refjmrentitymid;
     private Set<McxUserM> mcxUserMs = new HashSet<McxUserM>(0);

    public McxEntityM() {
    }

	
    public McxEntityM(long id) {
        this.id = id;
    }
    public McxEntityM(long id, String entity, String description, Character refjmrentitymid, Set<McxUserM> mcxUserMs) {
       this.id = id;
       this.entity = entity;
       this.description = description;
       this.refjmrentitymid = refjmrentitymid;
       this.mcxUserMs = mcxUserMs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="ENTITY", unique=true, length=5)
    public String getEntity() {
        return this.entity;
    }
    
    public void setEntity(String entity) {
        this.entity = entity;
    }

    
    @Column(name="DESCRIPTION", unique=true, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="REFJMRENTITYMID", length=1)
    public Character getRefjmrentitymid() {
        return this.refjmrentitymid;
    }
    
    public void setRefjmrentitymid(Character refjmrentitymid) {
        this.refjmrentitymid = refjmrentitymid;
    }



@OneToMany(fetch=FetchType.LAZY, mappedBy="mcxEntityM")
    public Set<McxUserM> getMcxUserMs() {
        return this.mcxUserMs;
    }
    
    public void setMcxUserMs(Set<McxUserM> mcxUserMs) {
        this.mcxUserMs = mcxUserMs;
    }




}


