package com.jmr.obdx.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * McxTransactionM generated by hbm2java
 */
@Entity
@Table(name="MCX_TRANSACTION_M"
    ,schema="JMR_OBDX"
)
public class McxTransactionM  implements java.io.Serializable {


     private long id;
     private String service;
     private String isactive;
     private String allowauthorization;
     private String allowinitiation;
     private String allowview;
     private String operation;
     private String prod;
     private String proddesc;
     private String modcd;
     private Set<BeneficiaryM> beneficiaryMs = new HashSet<BeneficiaryM>(0);
     private Set<TxnData> mcxTxnDatas = new HashSet<TxnData>(0);
     private Set<McxAuditLog> mcxAuditLogs = new HashSet<McxAuditLog>(0);


    public McxTransactionM() {
    }

    public McxTransactionM(String proddesc) {
    	this.proddesc = proddesc;
    }

    public McxTransactionM(long id) {
        this.id = id;
    }
    public McxTransactionM(long id, String service, String isactive, String allowauthorization, String allowinitiation, String allowview, String operation, String prod, String proddesc, String modcd, Set<BeneficiaryM> beneficiaryMs,Set<TxnData> mcxTxnDatas) {
       this.id = id;
       this.service = service;
       this.isactive = isactive;
       this.allowauthorization = allowauthorization;
       this.allowinitiation = allowinitiation;
       this.allowview = allowview;
       this.operation = operation;
       this.prod = prod;
       this.proddesc = proddesc;
       this.modcd = modcd;
       this.beneficiaryMs = beneficiaryMs;
       this.mcxTxnDatas = mcxTxnDatas;

    }
   
    
    public McxTransactionM( String service, String isactive, String allowauthorization, String allowinitiation, String allowview, String operation, String prod, String proddesc, String modcd, Set<TxnData> mcxTxnDatas, Set<McxAuditLog> mcxAuditLogs) {
        this.service = service;
        this.isactive = isactive;
        this.allowauthorization = allowauthorization;
        this.allowinitiation = allowinitiation;
        this.allowview = allowview;
        this.operation = operation;
        this.prod = prod;
        this.proddesc = proddesc;
        this.modcd = modcd;
        this.mcxTxnDatas = mcxTxnDatas;
        this.mcxAuditLogs = mcxAuditLogs;
     }
    
    @GeneratedValue(strategy = GenerationType.SEQUENCE,generator="mcx_transaction_m_seq")
    @SequenceGenerator(name ="mcx_transaction_m_seq",sequenceName="mcx_transaction_m_seq", allocationSize=1)
    @Id
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="SERVICE", length=100)
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }

    
    @Column(name="ISACTIVE", length=100)
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="ALLOWAUTHORIZATION", length=100)
    public String getAllowauthorization() {
        return this.allowauthorization;
    }
    
    public void setAllowauthorization(String allowauthorization) {
        this.allowauthorization = allowauthorization;
    }

    
    @Column(name="ALLOWINITIATION", length=100)
    public String getAllowinitiation() {
        return this.allowinitiation;
    }
    
    public void setAllowinitiation(String allowinitiation) {
        this.allowinitiation = allowinitiation;
    }

    
    @Column(name="ALLOWVIEW", length=100)
    public String getAllowview() {
        return this.allowview;
    }
    
    public void setAllowview(String allowview) {
        this.allowview = allowview;
    }

    
    @Column(name="OPERATION", length=100)
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }

    
    @Column(name="PROD", length=100)
    public String getProd() {
        return this.prod;
    }
    
    public void setProd(String prod) {
        this.prod = prod;
    }

    
    @Column(name="PRODDESC", length=100)
    public String getProddesc() {
        return this.proddesc;
    }
    
    public void setProddesc(String proddesc) {
        this.proddesc = proddesc;
    }

    
    @Column(name="MODCD", length=100)
    public String getModcd() {
        return this.modcd;
    }
    
    public void setModcd(String modcd) {
        this.modcd = modcd;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="mcxTransactionM", cascade = CascadeType.MERGE)
    public Set<BeneficiaryM> getBeneficiaryMs() {
        return this.beneficiaryMs;
    }
    
    public void setBeneficiaryMs(Set<BeneficiaryM> beneficiaryMs) {
        this.beneficiaryMs = beneficiaryMs;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="mcxTransactionM")
    public Set<McxAuditLog> getMcxAuditLogs() {
        return this.mcxAuditLogs;
    }
    
    public void setMcxAuditLogs(Set<McxAuditLog> mcxAuditLogs) {
        this.mcxAuditLogs = mcxAuditLogs;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="mcxTransactionM")
    public Set<TxnData> getMcxTxnDatas() {
        return this.mcxTxnDatas;
    }
    
    public void setMcxTxnDatas(Set<TxnData> mcxTxnDatas) {
        this.mcxTxnDatas = mcxTxnDatas;
 
    }
}