package com.jmr.obdx.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * McxUserM generated by hbm2java
 */
@Entity
@Table(name="MCX_USER_M"
    ,schema="JMR_OBDX"
    , uniqueConstraints = {@UniqueConstraint(columnNames="MOBILENUMBER"), @UniqueConstraint(columnNames="EMAILID")} 
)
public class McxUserM  implements java.io.Serializable {


     private long id;
     private McxEntityM mcxEntityM;
     private String firstname;
     private String lastname;
     private String address;
     private String city;
     private String state;
     private String country;
     private String mobilenumber;
     private String zipcode;
     private String faxnumber;
     private String emailid;
     private Long refBaseuserId;
     private String salutation;
     private Date registrationdate;
     private Date dateofbirth;
     private String phonenumber;
     private Character isactive;

    public McxUserM() {
    }

	
    public McxUserM(long id) {
        this.id = id;
    }
    public McxUserM(long id, McxEntityM mcxEntityM, String firstname, String lastname, String address, String city, String state, String country, String mobilenumber, String zipcode, String faxnumber, String emailid, Long refBaseuserId, String salutation, Date registrationdate, Date dateofbirth, String phonenumber, Character isactive) {
       this.id = id;
       this.mcxEntityM = mcxEntityM;
       this.firstname = firstname;
       this.lastname = lastname;
       this.address = address;
       this.city = city;
       this.state = state;
       this.country = country;
       this.mobilenumber = mobilenumber;
       this.zipcode = zipcode;
       this.faxnumber = faxnumber;
       this.emailid = emailid;
       this.refBaseuserId = refBaseuserId;
       this.salutation = salutation;
       this.registrationdate = registrationdate;
       this.dateofbirth = dateofbirth;
       this.phonenumber = phonenumber;
       this.isactive = isactive;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REF_ENTITY_ID")
    public McxEntityM getMcxEntityM() {
        return this.mcxEntityM;
    }
    
    public void setMcxEntityM(McxEntityM mcxEntityM) {
        this.mcxEntityM = mcxEntityM;
    }

    
    @Column(name="FIRSTNAME", length=100)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME", length=100)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="ADDRESS", length=500)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CITY", length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE", length=100)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="COUNTRY", length=100)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="MOBILENUMBER", unique=true, length=100)
    public String getMobilenumber() {
        return this.mobilenumber;
    }
    
    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber;
    }

    
    @Column(name="ZIPCODE", length=100)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    
    @Column(name="FAXNUMBER", length=100)
    public String getFaxnumber() {
        return this.faxnumber;
    }
    
    public void setFaxnumber(String faxnumber) {
        this.faxnumber = faxnumber;
    }

    
    @Column(name="EMAILID", unique=true, length=100)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    
    @Column(name="REF_BASEUSER_ID", precision=10, scale=0)
    public Long getRefBaseuserId() {
        return this.refBaseuserId;
    }
    
    public void setRefBaseuserId(Long refBaseuserId) {
        this.refBaseuserId = refBaseuserId;
    }

    
    @Column(name="SALUTATION", length=10)
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REGISTRATIONDATE", length=7)
    public Date getRegistrationdate() {
        return this.registrationdate;
    }
    
    public void setRegistrationdate(Date registrationdate) {
        this.registrationdate = registrationdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEOFBIRTH", length=7)
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    
    @Column(name="PHONENUMBER", length=100)
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    
    @Column(name="ISACTIVE", length=1)
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }






}


