package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mobileenablerusertypemap generated by hbm2java
 */
@Entity
@Table(name="MOBILEENABLERUSERTYPEMAP"
    ,schema="FCDBADMIN_RK"
)
public class Mobileenablerusertypemap  implements java.io.Serializable {


     private MobileenablerusertypemapId id;
     private Mstentityusertypes mstentityusertypes;
     private Mstusertypes mstusertypes;

    public Mobileenablerusertypemap() {
    }

	
    public Mobileenablerusertypemap(MobileenablerusertypemapId id, Mstentityusertypes mstentityusertypes) {
        this.id = id;
        this.mstentityusertypes = mstentityusertypes;
    }
    public Mobileenablerusertypemap(MobileenablerusertypemapId id, Mstentityusertypes mstentityusertypes, Mstusertypes mstusertypes) {
       this.id = id;
       this.mstentityusertypes = mstentityusertypes;
       this.mstusertypes = mstusertypes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="tgtappusertypeid", column=@Column(name="TGTAPPUSERTYPEID", nullable=false, length=50) ) } )
    public MobileenablerusertypemapId getId() {
        return this.id;
    }
    
    public void setId(MobileenablerusertypemapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY",  insertable=false, updatable=false), 
        @JoinColumn(name="FCDBUSERTYPE", referencedColumnName="TYPEUSER", insertable=false, updatable=false) } )
    public Mstentityusertypes getMstentityusertypes() {
        return this.mstentityusertypes;
    }
    
    public void setMstentityusertypes(Mstentityusertypes mstentityusertypes) {
        this.mstentityusertypes = mstentityusertypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FCDBUSERTYPE", insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }




}


