package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MobileKeywords generated by hbm2java
 */
@Entity
@Table(name="MOBILE_KEYWORDS"
    ,schema="FCDBADMIN_RK"
)
public class MobileKeywords  implements java.io.Serializable {


     private MobileKeywordsId id;
     private String value;
     private String comments;
     private Character istranslatable;

    public MobileKeywords() {
    }

	
    public MobileKeywords(MobileKeywordsId id) {
        this.id = id;
    }
    public MobileKeywords(MobileKeywordsId id, String value, String comments, Character istranslatable) {
       this.id = id;
       this.value = value;
       this.comments = comments;
       this.istranslatable = istranslatable;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mobileApplicationDevice", column=@Column(name="MOBILE_APPLICATION_DEVICE", nullable=false, length=30) ), 
        @AttributeOverride(name="fileName", column=@Column(name="FILE_NAME", nullable=false, length=50) ), 
        @AttributeOverride(name="keyword", column=@Column(name="KEYWORD", nullable=false, length=100) ), 
        @AttributeOverride(name="idlang", column=@Column(name="IDLANG", nullable=false, length=10) ) } )
    public MobileKeywordsId getId() {
        return this.id;
    }
    
    public void setId(MobileKeywordsId id) {
        this.id = id;
    }

    
    @Column(name="VALUE", length=1000)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="COMMENTS", length=4000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="ISTRANSLATABLE", length=1)
    public Character getIstranslatable() {
        return this.istranslatable;
    }
    
    public void setIstranslatable(Character istranslatable) {
        this.istranslatable = istranslatable;
    }




}


