package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstaccttypes generated by hbm2java
 */
@Entity
@Table(name="MSTACCTTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstaccttypes  implements java.io.Serializable {


     private MstaccttypesId id;
     private Mstentity mstentity;
     private Mstusertypes mstusertypes;
     private Character isproduct;
     private Character isexternal;
     private String extchannelid;
     private String description;

    public Mstaccttypes() {
    }

	
    public Mstaccttypes(MstaccttypesId id, Mstentity mstentity, Mstusertypes mstusertypes) {
        this.id = id;
        this.mstentity = mstentity;
        this.mstusertypes = mstusertypes;
    }
    public Mstaccttypes(MstaccttypesId id, Mstentity mstentity, Mstusertypes mstusertypes, Character isproduct, Character isexternal, String extchannelid, String description) {
       this.id = id;
       this.mstentity = mstentity;
       this.mstusertypes = mstusertypes;
       this.isproduct = isproduct;
       this.isexternal = isexternal;
       this.extchannelid = extchannelid;
       this.description = description;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idaccttype", column=@Column(name="IDACCTTYPE", nullable=false, length=1) ) } )
    public MstaccttypesId getId() {
        return this.id;
    }
    
    public void setId(MstaccttypesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPEUSER", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }

    
    @Column(name="ISPRODUCT", length=1)
    public Character getIsproduct() {
        return this.isproduct;
    }
    
    public void setIsproduct(Character isproduct) {
        this.isproduct = isproduct;
    }

    
    @Column(name="ISEXTERNAL", length=1)
    public Character getIsexternal() {
        return this.isexternal;
    }
    
    public void setIsexternal(Character isexternal) {
        this.isexternal = isexternal;
    }

    
    @Column(name="EXTCHANNELID", length=5)
    public String getExtchannelid() {
        return this.extchannelid;
    }
    
    public void setExtchannelid(String extchannelid) {
        this.extchannelid = extchannelid;
    }

    
    @Column(name="DESCRIPTION", length=40)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


