package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstalertadditionalparam generated by hbm2java
 */
@Entity
@Table(name="MSTALERTADDITIONALPARAM"
    ,schema="FCDBADMIN_RK"
)
public class Mstalertadditionalparam  implements java.io.Serializable {


     private MstalertadditionalparamId id;
     private String paramValues;
     private String paramDesc;
     private String validationRule;
     private String controlType;

    public Mstalertadditionalparam() {
    }

	
    public Mstalertadditionalparam(MstalertadditionalparamId id) {
        this.id = id;
    }
    public Mstalertadditionalparam(MstalertadditionalparamId id, String paramValues, String paramDesc, String validationRule, String controlType) {
       this.id = id;
       this.paramValues = paramValues;
       this.paramDesc = paramDesc;
       this.validationRule = validationRule;
       this.controlType = controlType;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="idparamType", column=@Column(name="IDPARAM_TYPE", nullable=false, length=2) ) } )
    public MstalertadditionalparamId getId() {
        return this.id;
    }
    
    public void setId(MstalertadditionalparamId id) {
        this.id = id;
    }

    
    @Column(name="PARAM_VALUES")
    public String getParamValues() {
        return this.paramValues;
    }
    
    public void setParamValues(String paramValues) {
        this.paramValues = paramValues;
    }

    
    @Column(name="PARAM_DESC", length=55)
    public String getParamDesc() {
        return this.paramDesc;
    }
    
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }

    
    @Column(name="VALIDATION_RULE")
    public String getValidationRule() {
        return this.validationRule;
    }
    
    public void setValidationRule(String validationRule) {
        this.validationRule = validationRule;
    }

    
    @Column(name="CONTROL_TYPE", length=2)
    public String getControlType() {
        return this.controlType;
    }
    
    public void setControlType(String controlType) {
        this.controlType = controlType;
    }




}


