package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstaccttypesId generated by hbm2java
 */
@Embeddable
public class MstaccttypesId  implements java.io.Serializable {


     private String idEntity;
     private String typeuser;
     private char idaccttype;

    public MstaccttypesId() {
    }

    public MstaccttypesId(String idEntity, String typeuser, char idaccttype) {
       this.idEntity = idEntity;
       this.typeuser = typeuser;
       this.idaccttype = idaccttype;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="TYPEUSER", nullable=false, length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }


    @Column(name="IDACCTTYPE", nullable=false, length=1)
    public char getIdaccttype() {
        return this.idaccttype;
    }
    
    public void setIdaccttype(char idaccttype) {
        this.idaccttype = idaccttype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstaccttypesId) ) return false;
		 MstaccttypesId castOther = ( MstaccttypesId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getTypeuser()==castOther.getTypeuser()) || ( this.getTypeuser()!=null && castOther.getTypeuser()!=null && this.getTypeuser().equals(castOther.getTypeuser()) ) )
 && (this.getIdaccttype()==castOther.getIdaccttype());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getTypeuser() == null ? 0 : this.getTypeuser().hashCode() );
         result = 37 * result + this.getIdaccttype();
         return result;
   }   


}


