package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstaction generated by hbm2java
 */
@Entity
@Table(name="MSTACTION"
    ,schema="FCDBADMIN_RK"
)
public class Mstaction  implements java.io.Serializable {


     private MstactionId id;
     private String idtxn;
     private String idrequest;
     private String idrequestOnError;
     private String actiongenerator;
     private String actionprocessor;
     private String additionalParams;

    public Mstaction() {
    }

	
    public Mstaction(MstactionId id) {
        this.id = id;
    }
    public Mstaction(MstactionId id, String idtxn, String idrequest, String idrequestOnError, String actiongenerator, String actionprocessor, String additionalParams) {
       this.id = id;
       this.idtxn = idtxn;
       this.idrequest = idrequest;
       this.idrequestOnError = idrequestOnError;
       this.actiongenerator = actiongenerator;
       this.actionprocessor = actionprocessor;
       this.additionalParams = additionalParams;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idaction", column=@Column(name="IDACTION", nullable=false, length=20) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ) } )
    public MstactionId getId() {
        return this.id;
    }
    
    public void setId(MstactionId id) {
        this.id = id;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="IDREQUEST", length=50)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="IDREQUEST_ON_ERROR", length=50)
    public String getIdrequestOnError() {
        return this.idrequestOnError;
    }
    
    public void setIdrequestOnError(String idrequestOnError) {
        this.idrequestOnError = idrequestOnError;
    }

    
    @Column(name="ACTIONGENERATOR", length=512)
    public String getActiongenerator() {
        return this.actiongenerator;
    }
    
    public void setActiongenerator(String actiongenerator) {
        this.actiongenerator = actiongenerator;
    }

    
    @Column(name="ACTIONPROCESSOR", length=512)
    public String getActionprocessor() {
        return this.actionprocessor;
    }
    
    public void setActionprocessor(String actionprocessor) {
        this.actionprocessor = actionprocessor;
    }

    
    @Column(name="ADDITIONAL_PARAMS", length=4000)
    public String getAdditionalParams() {
        return this.additionalParams;
    }
    
    public void setAdditionalParams(String additionalParams) {
        this.additionalParams = additionalParams;
    }




}


