package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstalert generated by hbm2java
 */
@Entity
@Table(name="MSTALERT"
    ,schema="FCDBADMIN_RK"
)
public class Mstalert  implements java.io.Serializable {


     private MstalertId id;
     private String description;
     private Character alerttype;
     private Character ispushalert;
     private String subject;
     private Boolean alertpriority;
     private String generatorclassname;
     private String propertiesstr;
     private Character isenabled;
     private String fromaddress;
     private String systemcode;
     private Long alertFreq;
     private Long alertCycleCount;
     private String paramAdtnlType;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private Date datCreated;
     private Date datNextRun;
     private Date datLastRun;
     private String groupCode;
     private Character isSubscribed;
     private Character onScreen;

    public Mstalert() {
    }

	
    public Mstalert(MstalertId id) {
        this.id = id;
    }
    public Mstalert(MstalertId id, String description, Character alerttype, Character ispushalert, String subject, Boolean alertpriority, String generatorclassname, String propertiesstr, Character isenabled, String fromaddress, String systemcode, Long alertFreq, Long alertCycleCount, String paramAdtnlType, String token1, String token2, String token3, String token4, Date datCreated, Date datNextRun, Date datLastRun, String groupCode, Character isSubscribed, Character onScreen) {
       this.id = id;
       this.description = description;
       this.alerttype = alerttype;
       this.ispushalert = ispushalert;
       this.subject = subject;
       this.alertpriority = alertpriority;
       this.generatorclassname = generatorclassname;
       this.propertiesstr = propertiesstr;
       this.isenabled = isenabled;
       this.fromaddress = fromaddress;
       this.systemcode = systemcode;
       this.alertFreq = alertFreq;
       this.alertCycleCount = alertCycleCount;
       this.paramAdtnlType = paramAdtnlType;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.datCreated = datCreated;
       this.datNextRun = datNextRun;
       this.datLastRun = datLastRun;
       this.groupCode = groupCode;
       this.isSubscribed = isSubscribed;
       this.onScreen = onScreen;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idalert", column=@Column(name="IDALERT", nullable=false, length=50) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ) } )
    public MstalertId getId() {
        return this.id;
    }
    
    public void setId(MstalertId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ALERTTYPE", length=1)
    public Character getAlerttype() {
        return this.alerttype;
    }
    
    public void setAlerttype(Character alerttype) {
        this.alerttype = alerttype;
    }

    
    @Column(name="ISPUSHALERT", length=1)
    public Character getIspushalert() {
        return this.ispushalert;
    }
    
    public void setIspushalert(Character ispushalert) {
        this.ispushalert = ispushalert;
    }

    
    @Column(name="SUBJECT")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="ALERTPRIORITY", precision=1, scale=0)
    public Boolean getAlertpriority() {
        return this.alertpriority;
    }
    
    public void setAlertpriority(Boolean alertpriority) {
        this.alertpriority = alertpriority;
    }

    
    @Column(name="GENERATORCLASSNAME")
    public String getGeneratorclassname() {
        return this.generatorclassname;
    }
    
    public void setGeneratorclassname(String generatorclassname) {
        this.generatorclassname = generatorclassname;
    }

    
    @Column(name="PROPERTIESSTR", length=2000)
    public String getPropertiesstr() {
        return this.propertiesstr;
    }
    
    public void setPropertiesstr(String propertiesstr) {
        this.propertiesstr = propertiesstr;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="FROMADDRESS")
    public String getFromaddress() {
        return this.fromaddress;
    }
    
    public void setFromaddress(String fromaddress) {
        this.fromaddress = fromaddress;
    }

    
    @Column(name="SYSTEMCODE")
    public String getSystemcode() {
        return this.systemcode;
    }
    
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode;
    }

    
    @Column(name="ALERT_FREQ", precision=18, scale=0)
    public Long getAlertFreq() {
        return this.alertFreq;
    }
    
    public void setAlertFreq(Long alertFreq) {
        this.alertFreq = alertFreq;
    }

    
    @Column(name="ALERT_CYCLE_COUNT", precision=18, scale=0)
    public Long getAlertCycleCount() {
        return this.alertCycleCount;
    }
    
    public void setAlertCycleCount(Long alertCycleCount) {
        this.alertCycleCount = alertCycleCount;
    }

    
    @Column(name="PARAM_ADTNL_TYPE", length=6)
    public String getParamAdtnlType() {
        return this.paramAdtnlType;
    }
    
    public void setParamAdtnlType(String paramAdtnlType) {
        this.paramAdtnlType = paramAdtnlType;
    }

    
    @Column(name="TOKEN1", length=30)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=30)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=30)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4", length=30)
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_CREATED", length=7)
    public Date getDatCreated() {
        return this.datCreated;
    }
    
    public void setDatCreated(Date datCreated) {
        this.datCreated = datCreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_NEXT_RUN", length=7)
    public Date getDatNextRun() {
        return this.datNextRun;
    }
    
    public void setDatNextRun(Date datNextRun) {
        this.datNextRun = datNextRun;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_LAST_RUN", length=7)
    public Date getDatLastRun() {
        return this.datLastRun;
    }
    
    public void setDatLastRun(Date datLastRun) {
        this.datLastRun = datLastRun;
    }

    
    @Column(name="GROUP_CODE", length=8)
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    
    @Column(name="IS_SUBSCRIBED", length=1)
    public Character getIsSubscribed() {
        return this.isSubscribed;
    }
    
    public void setIsSubscribed(Character isSubscribed) {
        this.isSubscribed = isSubscribed;
    }

    
    @Column(name="ON_SCREEN", length=1)
    public Character getOnScreen() {
        return this.onScreen;
    }
    
    public void setOnScreen(Character onScreen) {
        this.onScreen = onScreen;
    }




}


