package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstbeneficiary generated by hbm2java
 */
@Entity
@Table(name="MSTBENEFICIARY"
    ,schema="FCDBADMIN_RK"
)
public class Mstbeneficiary  implements java.io.Serializable {


     private MstbeneficiaryId id;
     private Boolean txnType;
     private String sortcode;
     private String beneAcctno;
     private String namCcyShort;
     private String beneCountry;
     private String namBank;
     private String namBrn;
     private String idCreator;
     private String swiftCode;
     private Date datCreation;
     private Blob msg;
     private String beneDesc;
     private Character custGroup;
     private BigDecimal txnLimit;
     private Boolean status;
     private String email;
     private BigDecimal dailyLimit;
     private String eftbankid;
     private String eftcityid;
     private String eftbranchid;
     private String destaccttype;
     private BigDecimal stateBit;
     private String beneId;
     private String codBank;
     private Set<Mstbeneficiarytemplate> mstbeneficiarytemplates = new HashSet<Mstbeneficiarytemplate>(0);

    public Mstbeneficiary() {
    }

	
    public Mstbeneficiary(MstbeneficiaryId id) {
        this.id = id;
    }
    public Mstbeneficiary(MstbeneficiaryId id, Boolean txnType, String sortcode, String beneAcctno, String namCcyShort, String beneCountry, String namBank, String namBrn, String idCreator, String swiftCode, Date datCreation, Blob msg, String beneDesc, Character custGroup, BigDecimal txnLimit, Boolean status, String email, BigDecimal dailyLimit, String eftbankid, String eftcityid, String eftbranchid, String destaccttype, BigDecimal stateBit, String beneId, String codBank, Set<Mstbeneficiarytemplate> mstbeneficiarytemplates) {
       this.id = id;
       this.txnType = txnType;
       this.sortcode = sortcode;
       this.beneAcctno = beneAcctno;
       this.namCcyShort = namCcyShort;
       this.beneCountry = beneCountry;
       this.namBank = namBank;
       this.namBrn = namBrn;
       this.idCreator = idCreator;
       this.swiftCode = swiftCode;
       this.datCreation = datCreation;
       this.msg = msg;
       this.beneDesc = beneDesc;
       this.custGroup = custGroup;
       this.txnLimit = txnLimit;
       this.status = status;
       this.email = email;
       this.dailyLimit = dailyLimit;
       this.eftbankid = eftbankid;
       this.eftcityid = eftcityid;
       this.eftbranchid = eftbranchid;
       this.destaccttype = destaccttype;
       this.stateBit = stateBit;
       this.beneId = beneId;
       this.codBank = codBank;
       this.mstbeneficiarytemplates = mstbeneficiarytemplates;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="custId", column=@Column(name="CUST_ID", nullable=false, length=30) ), 
        @AttributeOverride(name="beneName", column=@Column(name="BENE_NAME", nullable=false, length=100) ) } )
    public MstbeneficiaryId getId() {
        return this.id;
    }
    
    public void setId(MstbeneficiaryId id) {
        this.id = id;
    }

    
    @Column(name="TXN_TYPE", precision=1, scale=0)
    public Boolean getTxnType() {
        return this.txnType;
    }
    
    public void setTxnType(Boolean txnType) {
        this.txnType = txnType;
    }

    
    @Column(name="SORTCODE", length=25)
    public String getSortcode() {
        return this.sortcode;
    }
    
    public void setSortcode(String sortcode) {
        this.sortcode = sortcode;
    }

    
    @Column(name="BENE_ACCTNO", length=30)
    public String getBeneAcctno() {
        return this.beneAcctno;
    }
    
    public void setBeneAcctno(String beneAcctno) {
        this.beneAcctno = beneAcctno;
    }

    
    @Column(name="NAM_CCY_SHORT", length=3)
    public String getNamCcyShort() {
        return this.namCcyShort;
    }
    
    public void setNamCcyShort(String namCcyShort) {
        this.namCcyShort = namCcyShort;
    }

    
    @Column(name="BENE_COUNTRY", length=35)
    public String getBeneCountry() {
        return this.beneCountry;
    }
    
    public void setBeneCountry(String beneCountry) {
        this.beneCountry = beneCountry;
    }

    
    @Column(name="NAM_BANK", length=100)
    public String getNamBank() {
        return this.namBank;
    }
    
    public void setNamBank(String namBank) {
        this.namBank = namBank;
    }

    
    @Column(name="NAM_BRN", length=100)
    public String getNamBrn() {
        return this.namBrn;
    }
    
    public void setNamBrn(String namBrn) {
        this.namBrn = namBrn;
    }

    
    @Column(name="ID_CREATOR", length=20)
    public String getIdCreator() {
        return this.idCreator;
    }
    
    public void setIdCreator(String idCreator) {
        this.idCreator = idCreator;
    }

    
    @Column(name="SWIFT_CODE", length=11)
    public String getSwiftCode() {
        return this.swiftCode;
    }
    
    public void setSwiftCode(String swiftCode) {
        this.swiftCode = swiftCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_CREATION", length=7)
    public Date getDatCreation() {
        return this.datCreation;
    }
    
    public void setDatCreation(Date datCreation) {
        this.datCreation = datCreation;
    }

    
    @Column(name="MSG")
    public Blob getMsg() {
        return this.msg;
    }
    
    public void setMsg(Blob msg) {
        this.msg = msg;
    }

    
    @Column(name="BENE_DESC")
    public String getBeneDesc() {
        return this.beneDesc;
    }
    
    public void setBeneDesc(String beneDesc) {
        this.beneDesc = beneDesc;
    }

    
    @Column(name="CUST_GROUP", length=1)
    public Character getCustGroup() {
        return this.custGroup;
    }
    
    public void setCustGroup(Character custGroup) {
        this.custGroup = custGroup;
    }

    
    @Column(name="TXN_LIMIT", precision=22, scale=3)
    public BigDecimal getTxnLimit() {
        return this.txnLimit;
    }
    
    public void setTxnLimit(BigDecimal txnLimit) {
        this.txnLimit = txnLimit;
    }

    
    @Column(name="STATUS", precision=1, scale=0)
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="DAILY_LIMIT", precision=22, scale=3)
    public BigDecimal getDailyLimit() {
        return this.dailyLimit;
    }
    
    public void setDailyLimit(BigDecimal dailyLimit) {
        this.dailyLimit = dailyLimit;
    }

    
    @Column(name="EFTBANKID", length=9)
    public String getEftbankid() {
        return this.eftbankid;
    }
    
    public void setEftbankid(String eftbankid) {
        this.eftbankid = eftbankid;
    }

    
    @Column(name="EFTCITYID", length=9)
    public String getEftcityid() {
        return this.eftcityid;
    }
    
    public void setEftcityid(String eftcityid) {
        this.eftcityid = eftcityid;
    }

    
    @Column(name="EFTBRANCHID", length=9)
    public String getEftbranchid() {
        return this.eftbranchid;
    }
    
    public void setEftbranchid(String eftbranchid) {
        this.eftbranchid = eftbranchid;
    }

    
    @Column(name="DESTACCTTYPE", length=3)
    public String getDestaccttype() {
        return this.destaccttype;
    }
    
    public void setDestaccttype(String destaccttype) {
        this.destaccttype = destaccttype;
    }

    
    @Column(name="STATE_BIT", precision=22, scale=0)
    public BigDecimal getStateBit() {
        return this.stateBit;
    }
    
    public void setStateBit(BigDecimal stateBit) {
        this.stateBit = stateBit;
    }

    
    @Column(name="BENE_ID", length=20)
    public String getBeneId() {
        return this.beneId;
    }
    
    public void setBeneId(String beneId) {
        this.beneId = beneId;
    }

    
    @Column(name="COD_BANK", length=10)
    public String getCodBank() {
        return this.codBank;
    }
    
    public void setCodBank(String codBank) {
        this.codBank = codBank;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstbeneficiary")
    public Set<Mstbeneficiarytemplate> getMstbeneficiarytemplates() {
        return this.mstbeneficiarytemplates;
    }
    
    public void setMstbeneficiarytemplates(Set<Mstbeneficiarytemplate> mstbeneficiarytemplates) {
        this.mstbeneficiarytemplates = mstbeneficiarytemplates;
    }




}


