package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstbatchrecords generated by hbm2java
 */
@Entity
@Table(name="MSTBATCHRECORDS"
    ,schema="FCDBADMIN_RK"
)
public class Mstbatchrecords  implements java.io.Serializable {


     private MstbatchrecordsId id;
     private Mstbatchfileformats mstbatchfileformats;
     private TxnDataMaster txnDataMaster;
     private Character headerinfo;
     private Character footerinfo;
     private Character groupinfo;
     private String groupheaderidentifier;
     private String groupfooteridentifier;
     private String groupbodyidentifier;
     private String rowseparator;
     private String colseparator;
     private String fieldsep;
     private String token1;
     private String token2;

    public Mstbatchrecords() {
    }

	
    public Mstbatchrecords(MstbatchrecordsId id, Mstbatchfileformats mstbatchfileformats, TxnDataMaster txnDataMaster) {
        this.id = id;
        this.mstbatchfileformats = mstbatchfileformats;
        this.txnDataMaster = txnDataMaster;
    }
    public Mstbatchrecords(MstbatchrecordsId id, Mstbatchfileformats mstbatchfileformats, TxnDataMaster txnDataMaster, Character headerinfo, Character footerinfo, Character groupinfo, String groupheaderidentifier, String groupfooteridentifier, String groupbodyidentifier, String rowseparator, String colseparator, String fieldsep, String token1, String token2) {
       this.id = id;
       this.mstbatchfileformats = mstbatchfileformats;
       this.txnDataMaster = txnDataMaster;
       this.headerinfo = headerinfo;
       this.footerinfo = footerinfo;
       this.groupinfo = groupinfo;
       this.groupheaderidentifier = groupheaderidentifier;
       this.groupfooteridentifier = groupfooteridentifier;
       this.groupbodyidentifier = groupbodyidentifier;
       this.rowseparator = rowseparator;
       this.colseparator = colseparator;
       this.fieldsep = fieldsep;
       this.token1 = token1;
       this.token2 = token2;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false) ), 
        @AttributeOverride(name="idfiletype", column=@Column(name="IDFILETYPE", nullable=false, length=40) ) } )
    public MstbatchrecordsId getId() {
        return this.id;
    }
    
    public void setId(MstbatchrecordsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFILETYPE", nullable=false, insertable=false, updatable=false)
    public Mstbatchfileformats getMstbatchfileformats() {
        return this.mstbatchfileformats;
    }
    
    public void setMstbatchfileformats(Mstbatchfileformats mstbatchfileformats) {
        this.mstbatchfileformats = mstbatchfileformats;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREQUEST", nullable=false, insertable=false, updatable=false)
    public TxnDataMaster getTxnDataMaster() {
        return this.txnDataMaster;
    }
    
    public void setTxnDataMaster(TxnDataMaster txnDataMaster) {
        this.txnDataMaster = txnDataMaster;
    }

    
    @Column(name="HEADERINFO", length=1)
    public Character getHeaderinfo() {
        return this.headerinfo;
    }
    
    public void setHeaderinfo(Character headerinfo) {
        this.headerinfo = headerinfo;
    }

    
    @Column(name="FOOTERINFO", length=1)
    public Character getFooterinfo() {
        return this.footerinfo;
    }
    
    public void setFooterinfo(Character footerinfo) {
        this.footerinfo = footerinfo;
    }

    
    @Column(name="GROUPINFO", length=1)
    public Character getGroupinfo() {
        return this.groupinfo;
    }
    
    public void setGroupinfo(Character groupinfo) {
        this.groupinfo = groupinfo;
    }

    
    @Column(name="GROUPHEADERIDENTIFIER", length=3)
    public String getGroupheaderidentifier() {
        return this.groupheaderidentifier;
    }
    
    public void setGroupheaderidentifier(String groupheaderidentifier) {
        this.groupheaderidentifier = groupheaderidentifier;
    }

    
    @Column(name="GROUPFOOTERIDENTIFIER", length=3)
    public String getGroupfooteridentifier() {
        return this.groupfooteridentifier;
    }
    
    public void setGroupfooteridentifier(String groupfooteridentifier) {
        this.groupfooteridentifier = groupfooteridentifier;
    }

    
    @Column(name="GROUPBODYIDENTIFIER", length=3)
    public String getGroupbodyidentifier() {
        return this.groupbodyidentifier;
    }
    
    public void setGroupbodyidentifier(String groupbodyidentifier) {
        this.groupbodyidentifier = groupbodyidentifier;
    }

    
    @Column(name="ROWSEPARATOR", length=3)
    public String getRowseparator() {
        return this.rowseparator;
    }
    
    public void setRowseparator(String rowseparator) {
        this.rowseparator = rowseparator;
    }

    
    @Column(name="COLSEPARATOR", length=3)
    public String getColseparator() {
        return this.colseparator;
    }
    
    public void setColseparator(String colseparator) {
        this.colseparator = colseparator;
    }

    
    @Column(name="FIELDSEP", length=3)
    public String getFieldsep() {
        return this.fieldsep;
    }
    
    public void setFieldsep(String fieldsep) {
        this.fieldsep = fieldsep;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }




}


