package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstbaseusertypes generated by hbm2java
 */
@Entity
@Table(name="MSTBASEUSERTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstbaseusertypes  implements java.io.Serializable {


     private String baseusertype;
     private String description;
     private Set<Mstusertypes> mstusertypeses = new HashSet<Mstusertypes>(0);

    public Mstbaseusertypes() {
    }

	
    public Mstbaseusertypes(String baseusertype) {
        this.baseusertype = baseusertype;
    }
    public Mstbaseusertypes(String baseusertype, String description, Set<Mstusertypes> mstusertypeses) {
       this.baseusertype = baseusertype;
       this.description = description;
       this.mstusertypeses = mstusertypeses;
    }
   
     @Id 

    
    @Column(name="BASEUSERTYPE", unique=true, nullable=false, length=3)
    public String getBaseusertype() {
        return this.baseusertype;
    }
    
    public void setBaseusertype(String baseusertype) {
        this.baseusertype = baseusertype;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstbaseusertypes")
    public Set<Mstusertypes> getMstusertypeses() {
        return this.mstusertypeses;
    }
    
    public void setMstusertypeses(Set<Mstusertypes> mstusertypeses) {
        this.mstusertypeses = mstusertypeses;
    }




}


