package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstbranchdetails generated by hbm2java
 */
@Entity
@Table(name="MSTBRANCHDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class Mstbranchdetails  implements java.io.Serializable {


     private MstbranchdetailsId id;
     private String bankCode;
     private String branchPhone1;
     private String branchPhone2;
     private String servicesProvided1;
     private String servicesProvided2;
     private String servicesProvided3;
     private String additionalDetails1;
     private String additionalDetails2;
     private String workTimings1;
     private String workTimings2;
     private String workDays1;
     private String workDays2;

    public Mstbranchdetails() {
    }

	
    public Mstbranchdetails(MstbranchdetailsId id) {
        this.id = id;
    }
    public Mstbranchdetails(MstbranchdetailsId id, String bankCode, String branchPhone1, String branchPhone2, String servicesProvided1, String servicesProvided2, String servicesProvided3, String additionalDetails1, String additionalDetails2, String workTimings1, String workTimings2, String workDays1, String workDays2) {
       this.id = id;
       this.bankCode = bankCode;
       this.branchPhone1 = branchPhone1;
       this.branchPhone2 = branchPhone2;
       this.servicesProvided1 = servicesProvided1;
       this.servicesProvided2 = servicesProvided2;
       this.servicesProvided3 = servicesProvided3;
       this.additionalDetails1 = additionalDetails1;
       this.additionalDetails2 = additionalDetails2;
       this.workTimings1 = workTimings1;
       this.workTimings2 = workTimings2;
       this.workDays1 = workDays1;
       this.workDays2 = workDays2;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=4) ), 
        @AttributeOverride(name="branchCode", column=@Column(name="BRANCH_CODE", nullable=false, length=3) ) } )
    public MstbranchdetailsId getId() {
        return this.id;
    }
    
    public void setId(MstbranchdetailsId id) {
        this.id = id;
    }

    
    @Column(name="BANK_CODE", length=4)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="BRANCH_PHONE1", length=20)
    public String getBranchPhone1() {
        return this.branchPhone1;
    }
    
    public void setBranchPhone1(String branchPhone1) {
        this.branchPhone1 = branchPhone1;
    }

    
    @Column(name="BRANCH_PHONE2", length=20)
    public String getBranchPhone2() {
        return this.branchPhone2;
    }
    
    public void setBranchPhone2(String branchPhone2) {
        this.branchPhone2 = branchPhone2;
    }

    
    @Column(name="SERVICES_PROVIDED1", length=100)
    public String getServicesProvided1() {
        return this.servicesProvided1;
    }
    
    public void setServicesProvided1(String servicesProvided1) {
        this.servicesProvided1 = servicesProvided1;
    }

    
    @Column(name="SERVICES_PROVIDED2", length=100)
    public String getServicesProvided2() {
        return this.servicesProvided2;
    }
    
    public void setServicesProvided2(String servicesProvided2) {
        this.servicesProvided2 = servicesProvided2;
    }

    
    @Column(name="SERVICES_PROVIDED3", length=100)
    public String getServicesProvided3() {
        return this.servicesProvided3;
    }
    
    public void setServicesProvided3(String servicesProvided3) {
        this.servicesProvided3 = servicesProvided3;
    }

    
    @Column(name="ADDITIONAL_DETAILS1", length=100)
    public String getAdditionalDetails1() {
        return this.additionalDetails1;
    }
    
    public void setAdditionalDetails1(String additionalDetails1) {
        this.additionalDetails1 = additionalDetails1;
    }

    
    @Column(name="ADDITIONAL_DETAILS2", length=100)
    public String getAdditionalDetails2() {
        return this.additionalDetails2;
    }
    
    public void setAdditionalDetails2(String additionalDetails2) {
        this.additionalDetails2 = additionalDetails2;
    }

    
    @Column(name="WORK_TIMINGS1", length=100)
    public String getWorkTimings1() {
        return this.workTimings1;
    }
    
    public void setWorkTimings1(String workTimings1) {
        this.workTimings1 = workTimings1;
    }

    
    @Column(name="WORK_TIMINGS2", length=100)
    public String getWorkTimings2() {
        return this.workTimings2;
    }
    
    public void setWorkTimings2(String workTimings2) {
        this.workTimings2 = workTimings2;
    }

    
    @Column(name="WORK_DAYS1", length=100)
    public String getWorkDays1() {
        return this.workDays1;
    }
    
    public void setWorkDays1(String workDays1) {
        this.workDays1 = workDays1;
    }

    
    @Column(name="WORK_DAYS2", length=100)
    public String getWorkDays2() {
        return this.workDays2;
    }
    
    public void setWorkDays2(String workDays2) {
        this.workDays2 = workDays2;
    }




}


