package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstbatchfileformats generated by hbm2java
 */
@Entity
@Table(name="MSTBATCHFILEFORMATS"
    ,schema="FCDBADMIN_RK"
)
public class Mstbatchfileformats  implements java.io.Serializable {


     private String idfiletype;
     private String description;
     private String namconverter;
     private String extension;
     private String token1;
     private String token2;
     private String token3;
     private Set<Mstbatchrecords> mstbatchrecordses = new HashSet<Mstbatchrecords>(0);

    public Mstbatchfileformats() {
    }

	
    public Mstbatchfileformats(String idfiletype) {
        this.idfiletype = idfiletype;
    }
    public Mstbatchfileformats(String idfiletype, String description, String namconverter, String extension, String token1, String token2, String token3, Set<Mstbatchrecords> mstbatchrecordses) {
       this.idfiletype = idfiletype;
       this.description = description;
       this.namconverter = namconverter;
       this.extension = extension;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.mstbatchrecordses = mstbatchrecordses;
    }
   
     @Id 

    
    @Column(name="IDFILETYPE", unique=true, nullable=false, length=40)
    public String getIdfiletype() {
        return this.idfiletype;
    }
    
    public void setIdfiletype(String idfiletype) {
        this.idfiletype = idfiletype;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="NAMCONVERTER")
    public String getNamconverter() {
        return this.namconverter;
    }
    
    public void setNamconverter(String namconverter) {
        this.namconverter = namconverter;
    }

    
    @Column(name="EXTENSION", length=10)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3")
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstbatchfileformats")
    public Set<Mstbatchrecords> getMstbatchrecordses() {
        return this.mstbatchrecordses;
    }
    
    public void setMstbatchrecordses(Set<Mstbatchrecords> mstbatchrecordses) {
        this.mstbatchrecordses = mstbatchrecordses;
    }




}


