package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstcatruledetail generated by hbm2java
 */
@Entity
@Table(name="MSTCATRULEDETAIL"
    ,schema="FCDBADMIN_RK"
)
public class Mstcatruledetail  implements java.io.Serializable {


     private MstcatruledetailId id;
     private String islist;

    public Mstcatruledetail() {
    }

	
    public Mstcatruledetail(MstcatruledetailId id) {
        this.id = id;
    }
    public Mstcatruledetail(MstcatruledetailId id, String islist) {
       this.id = id;
       this.islist = islist;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcustgrp", column=@Column(name="IDCUSTGRP", nullable=false, length=20) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ), 
        @AttributeOverride(name="idseq", column=@Column(name="IDSEQ", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="idlist", column=@Column(name="IDLIST", nullable=false, length=15) ) } )
    public MstcatruledetailId getId() {
        return this.id;
    }
    
    public void setId(MstcatruledetailId id) {
        this.id = id;
    }

    
    @Column(name="ISLIST", length=1)
    public String getIslist() {
        return this.islist;
    }
    
    public void setIslist(String islist) {
        this.islist = islist;
    }




}


