package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstcusttypes generated by hbm2java
 */
@Entity
@Table(name="MSTCUSTTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstcusttypes  implements java.io.Serializable {


     private MstcusttypesId id;
     private String description;
     private Character isenabled;

    public Mstcusttypes() {
    }

	
    public Mstcusttypes(MstcusttypesId id) {
        this.id = id;
    }
    public Mstcusttypes(MstcusttypesId id, String description, Character isenabled) {
       this.id = id;
       this.description = description;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=4) ), 
        @AttributeOverride(name="typecust", column=@Column(name="TYPECUST", nullable=false, length=1) ), 
        @AttributeOverride(name="refIdEntity", column=@Column(name="REF_ID_ENTITY", nullable=false, length=4) ) } )
    public MstcusttypesId getId() {
        return this.id;
    }
    
    public void setId(MstcusttypesId id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }




}


