package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstcontacttypes generated by hbm2java
 */
@Entity
@Table(name="MSTCONTACTTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstcontacttypes  implements java.io.Serializable {


     private String idcontact;
     private String description;
     private Character isenabled;
     private Set<Mstcontactpurpose> mstcontactpurposes = new HashSet<Mstcontactpurpose>(0);

    public Mstcontacttypes() {
    }

	
    public Mstcontacttypes(String idcontact) {
        this.idcontact = idcontact;
    }
    public Mstcontacttypes(String idcontact, String description, Character isenabled, Set<Mstcontactpurpose> mstcontactpurposes) {
       this.idcontact = idcontact;
       this.description = description;
       this.isenabled = isenabled;
       this.mstcontactpurposes = mstcontactpurposes;
    }
   
     @Id 

    
    @Column(name="IDCONTACT", unique=true, nullable=false, length=5)
    public String getIdcontact() {
        return this.idcontact;
    }
    
    public void setIdcontact(String idcontact) {
        this.idcontact = idcontact;
    }

    
    @Column(name="DESCRIPTION", length=20)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstcontacttypes")
    public Set<Mstcontactpurpose> getMstcontactpurposes() {
        return this.mstcontactpurposes;
    }
    
    public void setMstcontactpurposes(Set<Mstcontactpurpose> mstcontactpurposes) {
        this.mstcontactpurposes = mstcontactpurposes;
    }




}


