package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstcards generated by hbm2java
 */
@Entity
@Table(name="MSTCARDS"
    ,schema="FCDBADMIN_RK"
)
public class Mstcards  implements java.io.Serializable {


     private String nbrcard;
     private String nameoncard;
     private Character typcard;
     private Character category;
     private Date issuedate;
     private Date expirydate;
     private Short checkdigit;
     private Character cardstatus;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private String company;
     private String billcycle;
     private BigDecimal creditlimit;
     private String currency;
     private BigDecimal cashlimit;
     private BigDecimal dailycashlimit;
     private BigDecimal spendinglimit;
     private BigDecimal installmentslimit;
     private Date statuschangedate;

    public Mstcards() {
    }

	
    public Mstcards(String nbrcard) {
        this.nbrcard = nbrcard;
    }
    public Mstcards(String nbrcard, String nameoncard, Character typcard, Character category, Date issuedate, Date expirydate, Short checkdigit, Character cardstatus, String token1, String token2, String token3, String token4, String token5, String company, String billcycle, BigDecimal creditlimit, String currency, BigDecimal cashlimit, BigDecimal dailycashlimit, BigDecimal spendinglimit, BigDecimal installmentslimit, Date statuschangedate) {
       this.nbrcard = nbrcard;
       this.nameoncard = nameoncard;
       this.typcard = typcard;
       this.category = category;
       this.issuedate = issuedate;
       this.expirydate = expirydate;
       this.checkdigit = checkdigit;
       this.cardstatus = cardstatus;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.company = company;
       this.billcycle = billcycle;
       this.creditlimit = creditlimit;
       this.currency = currency;
       this.cashlimit = cashlimit;
       this.dailycashlimit = dailycashlimit;
       this.spendinglimit = spendinglimit;
       this.installmentslimit = installmentslimit;
       this.statuschangedate = statuschangedate;
    }
   
     @Id 

    
    @Column(name="NBRCARD", unique=true, nullable=false, length=16)
    public String getNbrcard() {
        return this.nbrcard;
    }
    
    public void setNbrcard(String nbrcard) {
        this.nbrcard = nbrcard;
    }

    
    @Column(name="NAMEONCARD", length=100)
    public String getNameoncard() {
        return this.nameoncard;
    }
    
    public void setNameoncard(String nameoncard) {
        this.nameoncard = nameoncard;
    }

    
    @Column(name="TYPCARD", length=1)
    public Character getTypcard() {
        return this.typcard;
    }
    
    public void setTypcard(Character typcard) {
        this.typcard = typcard;
    }

    
    @Column(name="CATEGORY", length=1)
    public Character getCategory() {
        return this.category;
    }
    
    public void setCategory(Character category) {
        this.category = category;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ISSUEDATE", length=7)
    public Date getIssuedate() {
        return this.issuedate;
    }
    
    public void setIssuedate(Date issuedate) {
        this.issuedate = issuedate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRYDATE", length=7)
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    
    @Column(name="CHECKDIGIT", precision=3, scale=0)
    public Short getCheckdigit() {
        return this.checkdigit;
    }
    
    public void setCheckdigit(Short checkdigit) {
        this.checkdigit = checkdigit;
    }

    
    @Column(name="CARDSTATUS", length=1)
    public Character getCardstatus() {
        return this.cardstatus;
    }
    
    public void setCardstatus(Character cardstatus) {
        this.cardstatus = cardstatus;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3")
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4")
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5")
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="COMPANY", length=10)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="BILLCYCLE", length=50)
    public String getBillcycle() {
        return this.billcycle;
    }
    
    public void setBillcycle(String billcycle) {
        this.billcycle = billcycle;
    }

    
    @Column(name="CREDITLIMIT", precision=20, scale=4)
    public BigDecimal getCreditlimit() {
        return this.creditlimit;
    }
    
    public void setCreditlimit(BigDecimal creditlimit) {
        this.creditlimit = creditlimit;
    }

    
    @Column(name="CURRENCY", length=30)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="CASHLIMIT", precision=20, scale=4)
    public BigDecimal getCashlimit() {
        return this.cashlimit;
    }
    
    public void setCashlimit(BigDecimal cashlimit) {
        this.cashlimit = cashlimit;
    }

    
    @Column(name="DAILYCASHLIMIT", precision=20, scale=4)
    public BigDecimal getDailycashlimit() {
        return this.dailycashlimit;
    }
    
    public void setDailycashlimit(BigDecimal dailycashlimit) {
        this.dailycashlimit = dailycashlimit;
    }

    
    @Column(name="SPENDINGLIMIT", precision=20, scale=4)
    public BigDecimal getSpendinglimit() {
        return this.spendinglimit;
    }
    
    public void setSpendinglimit(BigDecimal spendinglimit) {
        this.spendinglimit = spendinglimit;
    }

    
    @Column(name="INSTALLMENTSLIMIT", precision=20, scale=4)
    public BigDecimal getInstallmentslimit() {
        return this.installmentslimit;
    }
    
    public void setInstallmentslimit(BigDecimal installmentslimit) {
        this.installmentslimit = installmentslimit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STATUSCHANGEDATE", length=7)
    public Date getStatuschangedate() {
        return this.statuschangedate;
    }
    
    public void setStatuschangedate(Date statuschangedate) {
        this.statuschangedate = statuschangedate;
    }




}


