package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mstchanneluser generated by hbm2java
 */
@Entity
@Table(name="MSTCHANNELUSER"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID_ENTITY", "IDUSER", "IDCHANNEL"}) 
)
public class Mstchanneluser  implements java.io.Serializable {


     private MstchanneluserId id;
     private Mstdevice mstdevice;
     private String idEntity;
     private String idchanneluser;
     private String password;
     private Character lockflag;
     private Date datlastsucclogin;
     private Date datlastfaillogin;
     private BigDecimal nbrfailedlogins;
     private BigDecimal nbrlogins;
     private String defaulttxn;
     private Date datsoftlastfail;
     private Character flagforcechangepwd;
     private Character isavcrequired;
     private String activationcode;
     private Date datavcgeneration;
     private BigDecimal failedattemptcnt;
     private Character flagforcechangetxnpwd;
     private String deactivationperiod;
     private BigDecimal failedgrpattemptcnt;
     private String idgroup;
     private Character flagforcechangeuid;
     private Character groupflag;
     private String lockreason;
     private Character dashboardid;
     private Character migrationRequired;

    public Mstchanneluser() {
    }

	
    public Mstchanneluser(MstchanneluserId id, Mstdevice mstdevice) {
        this.id = id;
        this.mstdevice = mstdevice;
    }
    public Mstchanneluser(MstchanneluserId id, Mstdevice mstdevice, String idEntity, String idchanneluser, String password, Character lockflag, Date datlastsucclogin, Date datlastfaillogin, BigDecimal nbrfailedlogins, BigDecimal nbrlogins, String defaulttxn, Date datsoftlastfail, Character flagforcechangepwd, Character isavcrequired, String activationcode, Date datavcgeneration, BigDecimal failedattemptcnt, Character flagforcechangetxnpwd, String deactivationperiod, BigDecimal failedgrpattemptcnt, String idgroup, Character flagforcechangeuid, Character groupflag, String lockreason, Character dashboardid, Character migrationRequired) {
       this.id = id;
       this.mstdevice = mstdevice;
       this.idEntity = idEntity;
       this.idchanneluser = idchanneluser;
       this.password = password;
       this.lockflag = lockflag;
       this.datlastsucclogin = datlastsucclogin;
       this.datlastfaillogin = datlastfaillogin;
       this.nbrfailedlogins = nbrfailedlogins;
       this.nbrlogins = nbrlogins;
       this.defaulttxn = defaulttxn;
       this.datsoftlastfail = datsoftlastfail;
       this.flagforcechangepwd = flagforcechangepwd;
       this.isavcrequired = isavcrequired;
       this.activationcode = activationcode;
       this.datavcgeneration = datavcgeneration;
       this.failedattemptcnt = failedattemptcnt;
       this.flagforcechangetxnpwd = flagforcechangetxnpwd;
       this.deactivationperiod = deactivationperiod;
       this.failedgrpattemptcnt = failedgrpattemptcnt;
       this.idgroup = idgroup;
       this.flagforcechangeuid = flagforcechangeuid;
       this.groupflag = groupflag;
       this.lockreason = lockreason;
       this.dashboardid = dashboardid;
       this.migrationRequired = migrationRequired;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ) } )
    public MstchanneluserId getId() {
        return this.id;
    }
    
    public void setId(MstchanneluserId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCHANNEL", nullable=false, insertable=false, updatable=false)
    public Mstdevice getMstdevice() {
        return this.mstdevice;
    }
    
    public void setMstdevice(Mstdevice mstdevice) {
        this.mstdevice = mstdevice;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDCHANNELUSER")
    public String getIdchanneluser() {
        return this.idchanneluser;
    }
    
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    
    @Column(name="PASSWORD", length=2000)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="LOCKFLAG", length=1)
    public Character getLockflag() {
        return this.lockflag;
    }
    
    public void setLockflag(Character lockflag) {
        this.lockflag = lockflag;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTSUCCLOGIN", length=7)
    public Date getDatlastsucclogin() {
        return this.datlastsucclogin;
    }
    
    public void setDatlastsucclogin(Date datlastsucclogin) {
        this.datlastsucclogin = datlastsucclogin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTFAILLOGIN", length=7)
    public Date getDatlastfaillogin() {
        return this.datlastfaillogin;
    }
    
    public void setDatlastfaillogin(Date datlastfaillogin) {
        this.datlastfaillogin = datlastfaillogin;
    }

    
    @Column(name="NBRFAILEDLOGINS", precision=22, scale=0)
    public BigDecimal getNbrfailedlogins() {
        return this.nbrfailedlogins;
    }
    
    public void setNbrfailedlogins(BigDecimal nbrfailedlogins) {
        this.nbrfailedlogins = nbrfailedlogins;
    }

    
    @Column(name="NBRLOGINS", precision=22, scale=0)
    public BigDecimal getNbrlogins() {
        return this.nbrlogins;
    }
    
    public void setNbrlogins(BigDecimal nbrlogins) {
        this.nbrlogins = nbrlogins;
    }

    
    @Column(name="DEFAULTTXN", length=3)
    public String getDefaulttxn() {
        return this.defaulttxn;
    }
    
    public void setDefaulttxn(String defaulttxn) {
        this.defaulttxn = defaulttxn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATSOFTLASTFAIL", length=7)
    public Date getDatsoftlastfail() {
        return this.datsoftlastfail;
    }
    
    public void setDatsoftlastfail(Date datsoftlastfail) {
        this.datsoftlastfail = datsoftlastfail;
    }

    
    @Column(name="FLAGFORCECHANGEPWD", length=1)
    public Character getFlagforcechangepwd() {
        return this.flagforcechangepwd;
    }
    
    public void setFlagforcechangepwd(Character flagforcechangepwd) {
        this.flagforcechangepwd = flagforcechangepwd;
    }

    
    @Column(name="ISAVCREQUIRED", length=1)
    public Character getIsavcrequired() {
        return this.isavcrequired;
    }
    
    public void setIsavcrequired(Character isavcrequired) {
        this.isavcrequired = isavcrequired;
    }

    
    @Column(name="ACTIVATIONCODE", length=400)
    public String getActivationcode() {
        return this.activationcode;
    }
    
    public void setActivationcode(String activationcode) {
        this.activationcode = activationcode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATAVCGENERATION", length=7)
    public Date getDatavcgeneration() {
        return this.datavcgeneration;
    }
    
    public void setDatavcgeneration(Date datavcgeneration) {
        this.datavcgeneration = datavcgeneration;
    }

    
    @Column(name="FAILEDATTEMPTCNT", precision=22, scale=0)
    public BigDecimal getFailedattemptcnt() {
        return this.failedattemptcnt;
    }
    
    public void setFailedattemptcnt(BigDecimal failedattemptcnt) {
        this.failedattemptcnt = failedattemptcnt;
    }

    
    @Column(name="FLAGFORCECHANGETXNPWD", length=1)
    public Character getFlagforcechangetxnpwd() {
        return this.flagforcechangetxnpwd;
    }
    
    public void setFlagforcechangetxnpwd(Character flagforcechangetxnpwd) {
        this.flagforcechangetxnpwd = flagforcechangetxnpwd;
    }

    
    @Column(name="DEACTIVATIONPERIOD", length=2000)
    public String getDeactivationperiod() {
        return this.deactivationperiod;
    }
    
    public void setDeactivationperiod(String deactivationperiod) {
        this.deactivationperiod = deactivationperiod;
    }

    
    @Column(name="FAILEDGRPATTEMPTCNT", precision=22, scale=0)
    public BigDecimal getFailedgrpattemptcnt() {
        return this.failedgrpattemptcnt;
    }
    
    public void setFailedgrpattemptcnt(BigDecimal failedgrpattemptcnt) {
        this.failedgrpattemptcnt = failedgrpattemptcnt;
    }

    
    @Column(name="IDGROUP", length=5)
    public String getIdgroup() {
        return this.idgroup;
    }
    
    public void setIdgroup(String idgroup) {
        this.idgroup = idgroup;
    }

    
    @Column(name="FLAGFORCECHANGEUID", length=1)
    public Character getFlagforcechangeuid() {
        return this.flagforcechangeuid;
    }
    
    public void setFlagforcechangeuid(Character flagforcechangeuid) {
        this.flagforcechangeuid = flagforcechangeuid;
    }

    
    @Column(name="GROUPFLAG", length=1)
    public Character getGroupflag() {
        return this.groupflag;
    }
    
    public void setGroupflag(Character groupflag) {
        this.groupflag = groupflag;
    }

    
    @Column(name="LOCKREASON", length=200)
    public String getLockreason() {
        return this.lockreason;
    }
    
    public void setLockreason(String lockreason) {
        this.lockreason = lockreason;
    }

    
    @Column(name="DASHBOARDID", length=1)
    public Character getDashboardid() {
        return this.dashboardid;
    }
    
    public void setDashboardid(Character dashboardid) {
        this.dashboardid = dashboardid;
    }

    
    @Column(name="MIGRATION_REQUIRED", length=1)
    public Character getMigrationRequired() {
        return this.migrationRequired;
    }
    
    public void setMigrationRequired(Character migrationRequired) {
        this.migrationRequired = migrationRequired;
    }




}


