package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstcustomer generated by hbm2java
 */
@Entity
@Table(name="MSTCUSTOMER"
    ,schema="FCDBADMIN_RK"
)
public class Mstcustomer  implements java.io.Serializable {


     private MstcustomerId id;
     private Date datCustOpen;
     private String namFirst;
     private String namLast;
     private String namMid;
     private String namFull;
     private String txtPrefecture;
     private Date datBirth;
     private String flgGender;
     private String addr1;
     private String addr2;
     private String addr3;
     private String addr4;
     private String addrCity;
     private String addrState;
     private String addrCountry;
     private String addrZip;
     private String flgKyc;
     private String txtEmail;
     private String txtResPhone;
     private String txtMobPhone;
     private String txtBusPhone;
     private String txtResFax;
     private String txtBusFax;
     private Character stmtOpt;
     private Character dupCif;
     private Character isStaff;
     private Character mktgOptEmail;
     private Character mktgOptPh;
     private Character mktgOptMail;
     private String regMedia;
     private String regChannel;
     private String namFirst2;
     private String namLast2;
     private Date datcreated;
     private String createdby;
     private Date lastupddatetime;
     private String updatedby;
     private Integer retMailCount;
     private String flgstatus;
     private String initialDepRecvd;
     private Byte wcPackStatus;
     private Date datWcPackStatus;
     private Boolean emailStatus;
     private String isSingleStep;
     private Character mktgStmtOpt;
     private Character addrKyc;
     private String prodInfo;
     private String remoteaddress;
     private String bannerId;
     private Date datDeath;
     private String poastatus;
     private String deceasedstatus;
     private Date datPoa;
     private Date datDeceased;
     private String iddocument;
     private String idchanneluser;
     private String customertype;
     private String unittype;
     private String namfull2;
     private String codbranch;
     private String securecode;
     private Character custflag;
     private String salutation;
     private String mobile;
     private Byte failedattempt;
     private Character lockflag;
     private BigDecimal salary;

    public Mstcustomer() {
    }

	
    public Mstcustomer(MstcustomerId id) {
        this.id = id;
    }
    public Mstcustomer(MstcustomerId id, Date datCustOpen, String namFirst, String namLast, String namMid, String namFull, String txtPrefecture, Date datBirth, String flgGender, String addr1, String addr2, String addr3, String addr4, String addrCity, String addrState, String addrCountry, String addrZip, String flgKyc, String txtEmail, String txtResPhone, String txtMobPhone, String txtBusPhone, String txtResFax, String txtBusFax, Character stmtOpt, Character dupCif, Character isStaff, Character mktgOptEmail, Character mktgOptPh, Character mktgOptMail, String regMedia, String regChannel, String namFirst2, String namLast2, Date datcreated, String createdby, Date lastupddatetime, String updatedby, Integer retMailCount, String flgstatus, String initialDepRecvd, Byte wcPackStatus, Date datWcPackStatus, Boolean emailStatus, String isSingleStep, Character mktgStmtOpt, Character addrKyc, String prodInfo, String remoteaddress, String bannerId, Date datDeath, String poastatus, String deceasedstatus, Date datPoa, Date datDeceased, String iddocument, String idchanneluser, String customertype, String unittype, String namfull2, String codbranch, String securecode, Character custflag, String salutation, String mobile, Byte failedattempt, Character lockflag, BigDecimal salary) {
       this.id = id;
       this.datCustOpen = datCustOpen;
       this.namFirst = namFirst;
       this.namLast = namLast;
       this.namMid = namMid;
       this.namFull = namFull;
       this.txtPrefecture = txtPrefecture;
       this.datBirth = datBirth;
       this.flgGender = flgGender;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.addr3 = addr3;
       this.addr4 = addr4;
       this.addrCity = addrCity;
       this.addrState = addrState;
       this.addrCountry = addrCountry;
       this.addrZip = addrZip;
       this.flgKyc = flgKyc;
       this.txtEmail = txtEmail;
       this.txtResPhone = txtResPhone;
       this.txtMobPhone = txtMobPhone;
       this.txtBusPhone = txtBusPhone;
       this.txtResFax = txtResFax;
       this.txtBusFax = txtBusFax;
       this.stmtOpt = stmtOpt;
       this.dupCif = dupCif;
       this.isStaff = isStaff;
       this.mktgOptEmail = mktgOptEmail;
       this.mktgOptPh = mktgOptPh;
       this.mktgOptMail = mktgOptMail;
       this.regMedia = regMedia;
       this.regChannel = regChannel;
       this.namFirst2 = namFirst2;
       this.namLast2 = namLast2;
       this.datcreated = datcreated;
       this.createdby = createdby;
       this.lastupddatetime = lastupddatetime;
       this.updatedby = updatedby;
       this.retMailCount = retMailCount;
       this.flgstatus = flgstatus;
       this.initialDepRecvd = initialDepRecvd;
       this.wcPackStatus = wcPackStatus;
       this.datWcPackStatus = datWcPackStatus;
       this.emailStatus = emailStatus;
       this.isSingleStep = isSingleStep;
       this.mktgStmtOpt = mktgStmtOpt;
       this.addrKyc = addrKyc;
       this.prodInfo = prodInfo;
       this.remoteaddress = remoteaddress;
       this.bannerId = bannerId;
       this.datDeath = datDeath;
       this.poastatus = poastatus;
       this.deceasedstatus = deceasedstatus;
       this.datPoa = datPoa;
       this.datDeceased = datDeceased;
       this.iddocument = iddocument;
       this.idchanneluser = idchanneluser;
       this.customertype = customertype;
       this.unittype = unittype;
       this.namfull2 = namfull2;
       this.codbranch = codbranch;
       this.securecode = securecode;
       this.custflag = custflag;
       this.salutation = salutation;
       this.mobile = mobile;
       this.failedattempt = failedattempt;
       this.lockflag = lockflag;
       this.salary = salary;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=20) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ) } )
    public MstcustomerId getId() {
        return this.id;
    }
    
    public void setId(MstcustomerId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_CUST_OPEN", length=7)
    public Date getDatCustOpen() {
        return this.datCustOpen;
    }
    
    public void setDatCustOpen(Date datCustOpen) {
        this.datCustOpen = datCustOpen;
    }

    
    @Column(name="NAM_FIRST", length=762)
    public String getNamFirst() {
        return this.namFirst;
    }
    
    public void setNamFirst(String namFirst) {
        this.namFirst = namFirst;
    }

    
    @Column(name="NAM_LAST", length=762)
    public String getNamLast() {
        return this.namLast;
    }
    
    public void setNamLast(String namLast) {
        this.namLast = namLast;
    }

    
    @Column(name="NAM_MID", length=762)
    public String getNamMid() {
        return this.namMid;
    }
    
    public void setNamMid(String namMid) {
        this.namMid = namMid;
    }

    
    @Column(name="NAM_FULL", length=762)
    public String getNamFull() {
        return this.namFull;
    }
    
    public void setNamFull(String namFull) {
        this.namFull = namFull;
    }

    
    @Column(name="TXT_PREFECTURE", length=105)
    public String getTxtPrefecture() {
        return this.txtPrefecture;
    }
    
    public void setTxtPrefecture(String txtPrefecture) {
        this.txtPrefecture = txtPrefecture;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_BIRTH", length=7)
    public Date getDatBirth() {
        return this.datBirth;
    }
    
    public void setDatBirth(Date datBirth) {
        this.datBirth = datBirth;
    }

    
    @Column(name="FLG_GENDER", length=1)
    public String getFlgGender() {
        return this.flgGender;
    }
    
    public void setFlgGender(String flgGender) {
        this.flgGender = flgGender;
    }

    
    @Column(name="ADDR_1", length=105)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    
    @Column(name="ADDR_2", length=105)
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }

    
    @Column(name="ADDR_3", length=105)
    public String getAddr3() {
        return this.addr3;
    }
    
    public void setAddr3(String addr3) {
        this.addr3 = addr3;
    }

    
    @Column(name="ADDR_4", length=105)
    public String getAddr4() {
        return this.addr4;
    }
    
    public void setAddr4(String addr4) {
        this.addr4 = addr4;
    }

    
    @Column(name="ADDR_CITY", length=105)
    public String getAddrCity() {
        return this.addrCity;
    }
    
    public void setAddrCity(String addrCity) {
        this.addrCity = addrCity;
    }

    
    @Column(name="ADDR_STATE", length=105)
    public String getAddrState() {
        return this.addrState;
    }
    
    public void setAddrState(String addrState) {
        this.addrState = addrState;
    }

    
    @Column(name="ADDR_COUNTRY", length=105)
    public String getAddrCountry() {
        return this.addrCountry;
    }
    
    public void setAddrCountry(String addrCountry) {
        this.addrCountry = addrCountry;
    }

    
    @Column(name="ADDR_ZIP", length=105)
    public String getAddrZip() {
        return this.addrZip;
    }
    
    public void setAddrZip(String addrZip) {
        this.addrZip = addrZip;
    }

    
    @Column(name="FLG_KYC", length=2)
    public String getFlgKyc() {
        return this.flgKyc;
    }
    
    public void setFlgKyc(String flgKyc) {
        this.flgKyc = flgKyc;
    }

    
    @Column(name="TXT_EMAIL", length=120)
    public String getTxtEmail() {
        return this.txtEmail;
    }
    
    public void setTxtEmail(String txtEmail) {
        this.txtEmail = txtEmail;
    }

    
    @Column(name="TXT_RES_PHONE", length=45)
    public String getTxtResPhone() {
        return this.txtResPhone;
    }
    
    public void setTxtResPhone(String txtResPhone) {
        this.txtResPhone = txtResPhone;
    }

    
    @Column(name="TXT_MOB_PHONE", length=45)
    public String getTxtMobPhone() {
        return this.txtMobPhone;
    }
    
    public void setTxtMobPhone(String txtMobPhone) {
        this.txtMobPhone = txtMobPhone;
    }

    
    @Column(name="TXT_BUS_PHONE", length=45)
    public String getTxtBusPhone() {
        return this.txtBusPhone;
    }
    
    public void setTxtBusPhone(String txtBusPhone) {
        this.txtBusPhone = txtBusPhone;
    }

    
    @Column(name="TXT_RES_FAX", length=45)
    public String getTxtResFax() {
        return this.txtResFax;
    }
    
    public void setTxtResFax(String txtResFax) {
        this.txtResFax = txtResFax;
    }

    
    @Column(name="TXT_BUS_FAX", length=45)
    public String getTxtBusFax() {
        return this.txtBusFax;
    }
    
    public void setTxtBusFax(String txtBusFax) {
        this.txtBusFax = txtBusFax;
    }

    
    @Column(name="STMT_OPT", length=1)
    public Character getStmtOpt() {
        return this.stmtOpt;
    }
    
    public void setStmtOpt(Character stmtOpt) {
        this.stmtOpt = stmtOpt;
    }

    
    @Column(name="DUP_CIF", length=1)
    public Character getDupCif() {
        return this.dupCif;
    }
    
    public void setDupCif(Character dupCif) {
        this.dupCif = dupCif;
    }

    
    @Column(name="IS_STAFF", length=1)
    public Character getIsStaff() {
        return this.isStaff;
    }
    
    public void setIsStaff(Character isStaff) {
        this.isStaff = isStaff;
    }

    
    @Column(name="MKTG_OPT_EMAIL", length=1)
    public Character getMktgOptEmail() {
        return this.mktgOptEmail;
    }
    
    public void setMktgOptEmail(Character mktgOptEmail) {
        this.mktgOptEmail = mktgOptEmail;
    }

    
    @Column(name="MKTG_OPT_PH", length=1)
    public Character getMktgOptPh() {
        return this.mktgOptPh;
    }
    
    public void setMktgOptPh(Character mktgOptPh) {
        this.mktgOptPh = mktgOptPh;
    }

    
    @Column(name="MKTG_OPT_MAIL", length=1)
    public Character getMktgOptMail() {
        return this.mktgOptMail;
    }
    
    public void setMktgOptMail(Character mktgOptMail) {
        this.mktgOptMail = mktgOptMail;
    }

    
    @Column(name="REG_MEDIA", length=50)
    public String getRegMedia() {
        return this.regMedia;
    }
    
    public void setRegMedia(String regMedia) {
        this.regMedia = regMedia;
    }

    
    @Column(name="REG_CHANNEL", length=50)
    public String getRegChannel() {
        return this.regChannel;
    }
    
    public void setRegChannel(String regChannel) {
        this.regChannel = regChannel;
    }

    
    @Column(name="NAM_FIRST2", length=762)
    public String getNamFirst2() {
        return this.namFirst2;
    }
    
    public void setNamFirst2(String namFirst2) {
        this.namFirst2 = namFirst2;
    }

    
    @Column(name="NAM_LAST2", length=762)
    public String getNamLast2() {
        return this.namLast2;
    }
    
    public void setNamLast2(String namLast2) {
        this.namLast2 = namLast2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="CREATEDBY", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDDATETIME", length=7)
    public Date getLastupddatetime() {
        return this.lastupddatetime;
    }
    
    public void setLastupddatetime(Date lastupddatetime) {
        this.lastupddatetime = lastupddatetime;
    }

    
    @Column(name="UPDATEDBY", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    
    @Column(name="RET_MAIL_COUNT", precision=5, scale=0)
    public Integer getRetMailCount() {
        return this.retMailCount;
    }
    
    public void setRetMailCount(Integer retMailCount) {
        this.retMailCount = retMailCount;
    }

    
    @Column(name="FLGSTATUS", length=1)
    public String getFlgstatus() {
        return this.flgstatus;
    }
    
    public void setFlgstatus(String flgstatus) {
        this.flgstatus = flgstatus;
    }

    
    @Column(name="INITIAL_DEP_RECVD", length=1)
    public String getInitialDepRecvd() {
        return this.initialDepRecvd;
    }
    
    public void setInitialDepRecvd(String initialDepRecvd) {
        this.initialDepRecvd = initialDepRecvd;
    }

    
    @Column(name="WC_PACK_STATUS", precision=2, scale=0)
    public Byte getWcPackStatus() {
        return this.wcPackStatus;
    }
    
    public void setWcPackStatus(Byte wcPackStatus) {
        this.wcPackStatus = wcPackStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_WC_PACK_STATUS", length=7)
    public Date getDatWcPackStatus() {
        return this.datWcPackStatus;
    }
    
    public void setDatWcPackStatus(Date datWcPackStatus) {
        this.datWcPackStatus = datWcPackStatus;
    }

    
    @Column(name="EMAIL_STATUS", precision=1, scale=0)
    public Boolean getEmailStatus() {
        return this.emailStatus;
    }
    
    public void setEmailStatus(Boolean emailStatus) {
        this.emailStatus = emailStatus;
    }

    
    @Column(name="IS_SINGLE_STEP", length=1)
    public String getIsSingleStep() {
        return this.isSingleStep;
    }
    
    public void setIsSingleStep(String isSingleStep) {
        this.isSingleStep = isSingleStep;
    }

    
    @Column(name="MKTG_STMT_OPT", length=1)
    public Character getMktgStmtOpt() {
        return this.mktgStmtOpt;
    }
    
    public void setMktgStmtOpt(Character mktgStmtOpt) {
        this.mktgStmtOpt = mktgStmtOpt;
    }

    
    @Column(name="ADDR_KYC", length=1)
    public Character getAddrKyc() {
        return this.addrKyc;
    }
    
    public void setAddrKyc(Character addrKyc) {
        this.addrKyc = addrKyc;
    }

    
    @Column(name="PROD_INFO", length=50)
    public String getProdInfo() {
        return this.prodInfo;
    }
    
    public void setProdInfo(String prodInfo) {
        this.prodInfo = prodInfo;
    }

    
    @Column(name="REMOTEADDRESS", length=50)
    public String getRemoteaddress() {
        return this.remoteaddress;
    }
    
    public void setRemoteaddress(String remoteaddress) {
        this.remoteaddress = remoteaddress;
    }

    
    @Column(name="BANNER_ID", length=50)
    public String getBannerId() {
        return this.bannerId;
    }
    
    public void setBannerId(String bannerId) {
        this.bannerId = bannerId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_DEATH", length=7)
    public Date getDatDeath() {
        return this.datDeath;
    }
    
    public void setDatDeath(Date datDeath) {
        this.datDeath = datDeath;
    }

    
    @Column(name="POASTATUS", length=2)
    public String getPoastatus() {
        return this.poastatus;
    }
    
    public void setPoastatus(String poastatus) {
        this.poastatus = poastatus;
    }

    
    @Column(name="DECEASEDSTATUS", length=2)
    public String getDeceasedstatus() {
        return this.deceasedstatus;
    }
    
    public void setDeceasedstatus(String deceasedstatus) {
        this.deceasedstatus = deceasedstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_POA", length=7)
    public Date getDatPoa() {
        return this.datPoa;
    }
    
    public void setDatPoa(Date datPoa) {
        this.datPoa = datPoa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DAT_DECEASED", length=7)
    public Date getDatDeceased() {
        return this.datDeceased;
    }
    
    public void setDatDeceased(Date datDeceased) {
        this.datDeceased = datDeceased;
    }

    
    @Column(name="IDDOCUMENT", length=50)
    public String getIddocument() {
        return this.iddocument;
    }
    
    public void setIddocument(String iddocument) {
        this.iddocument = iddocument;
    }

    
    @Column(name="IDCHANNELUSER", length=20)
    public String getIdchanneluser() {
        return this.idchanneluser;
    }
    
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    
    @Column(name="CUSTOMERTYPE", length=2)
    public String getCustomertype() {
        return this.customertype;
    }
    
    public void setCustomertype(String customertype) {
        this.customertype = customertype;
    }

    
    @Column(name="UNITTYPE", length=2)
    public String getUnittype() {
        return this.unittype;
    }
    
    public void setUnittype(String unittype) {
        this.unittype = unittype;
    }

    
    @Column(name="NAMFULL2", length=762)
    public String getNamfull2() {
        return this.namfull2;
    }
    
    public void setNamfull2(String namfull2) {
        this.namfull2 = namfull2;
    }

    
    @Column(name="CODBRANCH", length=5)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }

    
    @Column(name="SECURECODE", length=2000)
    public String getSecurecode() {
        return this.securecode;
    }
    
    public void setSecurecode(String securecode) {
        this.securecode = securecode;
    }

    
    @Column(name="CUSTFLAG", length=1)
    public Character getCustflag() {
        return this.custflag;
    }
    
    public void setCustflag(Character custflag) {
        this.custflag = custflag;
    }

    
    @Column(name="SALUTATION", length=20)
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    
    @Column(name="MOBILE", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="FAILEDATTEMPT", precision=2, scale=0)
    public Byte getFailedattempt() {
        return this.failedattempt;
    }
    
    public void setFailedattempt(Byte failedattempt) {
        this.failedattempt = failedattempt;
    }

    
    @Column(name="LOCKFLAG", length=1)
    public Character getLockflag() {
        return this.lockflag;
    }
    
    public void setLockflag(Character lockflag) {
        this.lockflag = lockflag;
    }

    
    @Column(name="SALARY", precision=22, scale=0)
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }




}


