package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstchannelatsext generated by hbm2java
 */
@Entity
@Table(name="MSTCHANNELATSEXT"
    ,schema="FCDBADMIN_RK"
)
public class Mstchannelatsext  implements java.io.Serializable {


     private MstchannelatsextId id;
     private String fieldnames;
     private Set<Channelatsextmapvalues> channelatsextmapvalueses = new HashSet<Channelatsextmapvalues>(0);

    public Mstchannelatsext() {
    }

	
    public Mstchannelatsext(MstchannelatsextId id) {
        this.id = id;
    }
    public Mstchannelatsext(MstchannelatsextId id, String fieldnames, Set<Channelatsextmapvalues> channelatsextmapvalueses) {
       this.id = id;
       this.fieldnames = fieldnames;
       this.channelatsextmapvalueses = channelatsextmapvalueses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idrequestparent", column=@Column(name="IDREQUESTPARENT", nullable=false, length=50) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=10) ) } )
    public MstchannelatsextId getId() {
        return this.id;
    }
    
    public void setId(MstchannelatsextId id) {
        this.id = id;
    }

    
    @Column(name="FIELDNAMES", length=100)
    public String getFieldnames() {
        return this.fieldnames;
    }
    
    public void setFieldnames(String fieldnames) {
        this.fieldnames = fieldnames;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstchannelatsext")
    public Set<Channelatsextmapvalues> getChannelatsextmapvalueses() {
        return this.channelatsextmapvalueses;
    }
    
    public void setChannelatsextmapvalueses(Set<Channelatsextmapvalues> channelatsextmapvalueses) {
        this.channelatsextmapvalueses = channelatsextmapvalueses;
    }




}


