package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstchannelats generated by hbm2java
 */
@Entity
@Table(name="MSTCHANNELATS"
    ,schema="FCDBADMIN_RK"
)
public class Mstchannelats  implements java.io.Serializable {


     private MstchannelatsId id;
     private Character typplugin;
     private Character auditrequired;
     private Character requireslogin;
     private String contentstyle;
     private String namresource;
     private String idservice;
     private String idapp;
     private Character flagpreprocess;
     private Character flagpostprocess;
     private String nameotresource;
     private String nameosresource;
     private Character isonlyvalidaterequest;
     private String idserviceEot;
     private String idserviceEos;
     private String idrequestEot;
     private Character authrequired;
     private Character txnpwdrequired;
     private Boolean flagpagination;
     private String adtnlParams;
     private Character flgorch;
     private Character isonlyauthvalidate;
     private String isgenerictemplate;
     private Character hasextendedresponse;
     private Character alertrequired;
     private String validIdrequest;
     private String token1;
     private String token2;
     private String token3;
     private Character typeRequest;
     private String auditresourcexsl;
     private String auditcontentstyle;

    public Mstchannelats() {
    }

	
    public Mstchannelats(MstchannelatsId id) {
        this.id = id;
    }
    public Mstchannelats(MstchannelatsId id, Character typplugin, Character auditrequired, Character requireslogin, String contentstyle, String namresource, String idservice, String idapp, Character flagpreprocess, Character flagpostprocess, String nameotresource, String nameosresource, Character isonlyvalidaterequest, String idserviceEot, String idserviceEos, String idrequestEot, Character authrequired, Character txnpwdrequired, Boolean flagpagination, String adtnlParams, Character flgorch, Character isonlyauthvalidate, String isgenerictemplate, Character hasextendedresponse, Character alertrequired, String validIdrequest, String token1, String token2, String token3, Character typeRequest, String auditresourcexsl, String auditcontentstyle) {
       this.id = id;
       this.typplugin = typplugin;
       this.auditrequired = auditrequired;
       this.requireslogin = requireslogin;
       this.contentstyle = contentstyle;
       this.namresource = namresource;
       this.idservice = idservice;
       this.idapp = idapp;
       this.flagpreprocess = flagpreprocess;
       this.flagpostprocess = flagpostprocess;
       this.nameotresource = nameotresource;
       this.nameosresource = nameosresource;
       this.isonlyvalidaterequest = isonlyvalidaterequest;
       this.idserviceEot = idserviceEot;
       this.idserviceEos = idserviceEos;
       this.idrequestEot = idrequestEot;
       this.authrequired = authrequired;
       this.txnpwdrequired = txnpwdrequired;
       this.flagpagination = flagpagination;
       this.adtnlParams = adtnlParams;
       this.flgorch = flgorch;
       this.isonlyauthvalidate = isonlyauthvalidate;
       this.isgenerictemplate = isgenerictemplate;
       this.hasextendedresponse = hasextendedresponse;
       this.alertrequired = alertrequired;
       this.validIdrequest = validIdrequest;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.typeRequest = typeRequest;
       this.auditresourcexsl = auditresourcexsl;
       this.auditcontentstyle = auditcontentstyle;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=50) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MstchannelatsId getId() {
        return this.id;
    }
    
    public void setId(MstchannelatsId id) {
        this.id = id;
    }

    
    @Column(name="TYPPLUGIN", length=1)
    public Character getTypplugin() {
        return this.typplugin;
    }
    
    public void setTypplugin(Character typplugin) {
        this.typplugin = typplugin;
    }

    
    @Column(name="AUDITREQUIRED", length=1)
    public Character getAuditrequired() {
        return this.auditrequired;
    }
    
    public void setAuditrequired(Character auditrequired) {
        this.auditrequired = auditrequired;
    }

    
    @Column(name="REQUIRESLOGIN", length=1)
    public Character getRequireslogin() {
        return this.requireslogin;
    }
    
    public void setRequireslogin(Character requireslogin) {
        this.requireslogin = requireslogin;
    }

    
    @Column(name="CONTENTSTYLE", length=20)
    public String getContentstyle() {
        return this.contentstyle;
    }
    
    public void setContentstyle(String contentstyle) {
        this.contentstyle = contentstyle;
    }

    
    @Column(name="NAMRESOURCE", length=50)
    public String getNamresource() {
        return this.namresource;
    }
    
    public void setNamresource(String namresource) {
        this.namresource = namresource;
    }

    
    @Column(name="IDSERVICE", length=100)
    public String getIdservice() {
        return this.idservice;
    }
    
    public void setIdservice(String idservice) {
        this.idservice = idservice;
    }

    
    @Column(name="IDAPP", length=2)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }

    
    @Column(name="FLAGPREPROCESS", length=1)
    public Character getFlagpreprocess() {
        return this.flagpreprocess;
    }
    
    public void setFlagpreprocess(Character flagpreprocess) {
        this.flagpreprocess = flagpreprocess;
    }

    
    @Column(name="FLAGPOSTPROCESS", length=1)
    public Character getFlagpostprocess() {
        return this.flagpostprocess;
    }
    
    public void setFlagpostprocess(Character flagpostprocess) {
        this.flagpostprocess = flagpostprocess;
    }

    
    @Column(name="NAMEOTRESOURCE", length=50)
    public String getNameotresource() {
        return this.nameotresource;
    }
    
    public void setNameotresource(String nameotresource) {
        this.nameotresource = nameotresource;
    }

    
    @Column(name="NAMEOSRESOURCE", length=50)
    public String getNameosresource() {
        return this.nameosresource;
    }
    
    public void setNameosresource(String nameosresource) {
        this.nameosresource = nameosresource;
    }

    
    @Column(name="ISONLYVALIDATEREQUEST", length=1)
    public Character getIsonlyvalidaterequest() {
        return this.isonlyvalidaterequest;
    }
    
    public void setIsonlyvalidaterequest(Character isonlyvalidaterequest) {
        this.isonlyvalidaterequest = isonlyvalidaterequest;
    }

    
    @Column(name="IDSERVICE_EOT", length=50)
    public String getIdserviceEot() {
        return this.idserviceEot;
    }
    
    public void setIdserviceEot(String idserviceEot) {
        this.idserviceEot = idserviceEot;
    }

    
    @Column(name="IDSERVICE_EOS", length=50)
    public String getIdserviceEos() {
        return this.idserviceEos;
    }
    
    public void setIdserviceEos(String idserviceEos) {
        this.idserviceEos = idserviceEos;
    }

    
    @Column(name="IDREQUEST_EOT", length=50)
    public String getIdrequestEot() {
        return this.idrequestEot;
    }
    
    public void setIdrequestEot(String idrequestEot) {
        this.idrequestEot = idrequestEot;
    }

    
    @Column(name="AUTHREQUIRED", length=1)
    public Character getAuthrequired() {
        return this.authrequired;
    }
    
    public void setAuthrequired(Character authrequired) {
        this.authrequired = authrequired;
    }

    
    @Column(name="TXNPWDREQUIRED", length=1)
    public Character getTxnpwdrequired() {
        return this.txnpwdrequired;
    }
    
    public void setTxnpwdrequired(Character txnpwdrequired) {
        this.txnpwdrequired = txnpwdrequired;
    }

    
    @Column(name="FLAGPAGINATION", precision=1, scale=0)
    public Boolean getFlagpagination() {
        return this.flagpagination;
    }
    
    public void setFlagpagination(Boolean flagpagination) {
        this.flagpagination = flagpagination;
    }

    
    @Column(name="ADTNL_PARAMS", length=4000)
    public String getAdtnlParams() {
        return this.adtnlParams;
    }
    
    public void setAdtnlParams(String adtnlParams) {
        this.adtnlParams = adtnlParams;
    }

    
    @Column(name="FLGORCH", length=1)
    public Character getFlgorch() {
        return this.flgorch;
    }
    
    public void setFlgorch(Character flgorch) {
        this.flgorch = flgorch;
    }

    
    @Column(name="ISONLYAUTHVALIDATE", length=1)
    public Character getIsonlyauthvalidate() {
        return this.isonlyauthvalidate;
    }
    
    public void setIsonlyauthvalidate(Character isonlyauthvalidate) {
        this.isonlyauthvalidate = isonlyauthvalidate;
    }

    
    @Column(name="ISGENERICTEMPLATE", length=1)
    public String getIsgenerictemplate() {
        return this.isgenerictemplate;
    }
    
    public void setIsgenerictemplate(String isgenerictemplate) {
        this.isgenerictemplate = isgenerictemplate;
    }

    
    @Column(name="HASEXTENDEDRESPONSE", length=1)
    public Character getHasextendedresponse() {
        return this.hasextendedresponse;
    }
    
    public void setHasextendedresponse(Character hasextendedresponse) {
        this.hasextendedresponse = hasextendedresponse;
    }

    
    @Column(name="ALERTREQUIRED", length=1)
    public Character getAlertrequired() {
        return this.alertrequired;
    }
    
    public void setAlertrequired(Character alertrequired) {
        this.alertrequired = alertrequired;
    }

    
    @Column(name="VALID_IDREQUEST", length=100)
    public String getValidIdrequest() {
        return this.validIdrequest;
    }
    
    public void setValidIdrequest(String validIdrequest) {
        this.validIdrequest = validIdrequest;
    }

    
    @Column(name="TOKEN1", length=20)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=20)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=20)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TYPE_REQUEST", length=1)
    public Character getTypeRequest() {
        return this.typeRequest;
    }
    
    public void setTypeRequest(Character typeRequest) {
        this.typeRequest = typeRequest;
    }

    
    @Column(name="AUDITRESOURCEXSL", length=50)
    public String getAuditresourcexsl() {
        return this.auditresourcexsl;
    }
    
    public void setAuditresourcexsl(String auditresourcexsl) {
        this.auditresourcexsl = auditresourcexsl;
    }

    
    @Column(name="AUDITCONTENTSTYLE", length=20)
    public String getAuditcontentstyle() {
        return this.auditcontentstyle;
    }
    
    public void setAuditcontentstyle(String auditcontentstyle) {
        this.auditcontentstyle = auditcontentstyle;
    }




}


