package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstdocumenttypes generated by hbm2java
 */
@Entity
@Table(name="MSTDOCUMENTTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstdocumenttypes  implements java.io.Serializable {


     private MstdocumenttypesId id;
     private String defaultImageType;
     private String description;
     private String typdocument;
     private Short sortorder;

    public Mstdocumenttypes() {
    }

	
    public Mstdocumenttypes(MstdocumenttypesId id) {
        this.id = id;
    }
    public Mstdocumenttypes(MstdocumenttypesId id, String defaultImageType, String description, String typdocument, Short sortorder) {
       this.id = id;
       this.defaultImageType = defaultImageType;
       this.description = description;
       this.typdocument = typdocument;
       this.sortorder = sortorder;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idtype", column=@Column(name="IDTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="iddocument", column=@Column(name="IDDOCUMENT", nullable=false, length=5) ) } )
    public MstdocumenttypesId getId() {
        return this.id;
    }
    
    public void setId(MstdocumenttypesId id) {
        this.id = id;
    }

    
    @Column(name="DEFAULT_IMAGE_TYPE", length=1)
    public String getDefaultImageType() {
        return this.defaultImageType;
    }
    
    public void setDefaultImageType(String defaultImageType) {
        this.defaultImageType = defaultImageType;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="TYPDOCUMENT", length=1)
    public String getTypdocument() {
        return this.typdocument;
    }
    
    public void setTypdocument(String typdocument) {
        this.typdocument = typdocument;
    }

    
    @Column(name="SORTORDER", precision=4, scale=0)
    public Short getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(Short sortorder) {
        this.sortorder = sortorder;
    }




}


