package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mstdevice generated by hbm2java
 */
@Entity
@Table(name="MSTDEVICE"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="IDCHANNEL") 
)
public class Mstdevice  implements java.io.Serializable {


     private String iddevice;
     private String namdevice;
     private String contenttype;
     private String idchannel;
     private Set<Mstchanneluser> mstchannelusers = new HashSet<Mstchanneluser>(0);

    public Mstdevice() {
    }

	
    public Mstdevice(String iddevice) {
        this.iddevice = iddevice;
    }
    public Mstdevice(String iddevice, String namdevice, String contenttype, String idchannel, Set<Mstchanneluser> mstchannelusers) {
       this.iddevice = iddevice;
       this.namdevice = namdevice;
       this.contenttype = contenttype;
       this.idchannel = idchannel;
       this.mstchannelusers = mstchannelusers;
    }
   
     @Id 

    
    @Column(name="IDDEVICE", unique=true, nullable=false, length=2)
    public String getIddevice() {
        return this.iddevice;
    }
    
    public void setIddevice(String iddevice) {
        this.iddevice = iddevice;
    }

    
    @Column(name="NAMDEVICE", length=30)
    public String getNamdevice() {
        return this.namdevice;
    }
    
    public void setNamdevice(String namdevice) {
        this.namdevice = namdevice;
    }

    
    @Column(name="CONTENTTYPE", length=50)
    public String getContenttype() {
        return this.contenttype;
    }
    
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype;
    }

    
    @Column(name="IDCHANNEL", unique=true, length=3)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstdevice")
    public Set<Mstchanneluser> getMstchannelusers() {
        return this.mstchannelusers;
    }
    
    public void setMstchannelusers(Set<Mstchanneluser> mstchannelusers) {
        this.mstchannelusers = mstchannelusers;
    }




}


