package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstdocumentexception generated by hbm2java
 */
@Entity
@Table(name="MSTDOCUMENTEXCEPTION"
    ,schema="FCDBADMIN_RK"
)
public class Mstdocumentexception  implements java.io.Serializable {


     private MstdocumentexceptionId id;
     private String exdescription;
     private String idfulfillment;
     private String isphonerecovery;
     private Long priority;

    public Mstdocumentexception() {
    }

	
    public Mstdocumentexception(MstdocumentexceptionId id) {
        this.id = id;
    }
    public Mstdocumentexception(MstdocumentexceptionId id, String exdescription, String idfulfillment, String isphonerecovery, Long priority) {
       this.id = id;
       this.exdescription = exdescription;
       this.idfulfillment = idfulfillment;
       this.isphonerecovery = isphonerecovery;
       this.priority = priority;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="exno", column=@Column(name="EXNO", nullable=false, length=4) ), 
        @AttributeOverride(name="iddocument", column=@Column(name="IDDOCUMENT", nullable=false, length=5) ) } )
    public MstdocumentexceptionId getId() {
        return this.id;
    }
    
    public void setId(MstdocumentexceptionId id) {
        this.id = id;
    }

    
    @Column(name="EXDESCRIPTION", length=200)
    public String getExdescription() {
        return this.exdescription;
    }
    
    public void setExdescription(String exdescription) {
        this.exdescription = exdescription;
    }

    
    @Column(name="IDFULFILLMENT", length=5)
    public String getIdfulfillment() {
        return this.idfulfillment;
    }
    
    public void setIdfulfillment(String idfulfillment) {
        this.idfulfillment = idfulfillment;
    }

    
    @Column(name="ISPHONERECOVERY", length=1)
    public String getIsphonerecovery() {
        return this.isphonerecovery;
    }
    
    public void setIsphonerecovery(String isphonerecovery) {
        this.isphonerecovery = isphonerecovery;
    }

    
    @Column(name="PRIORITY", precision=10, scale=0)
    public Long getPriority() {
        return this.priority;
    }
    
    public void setPriority(Long priority) {
        this.priority = priority;
    }




}


