package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstdashboardlayout generated by hbm2java
 */
@Entity
@Table(name="MSTDASHBOARDLAYOUT"
    ,schema="FCDBADMIN_RK"
)
public class Mstdashboardlayout  implements java.io.Serializable {


     private MstdashboardlayoutId id;
     private String idrequest;
     private String idtxn;
     private BigDecimal relposx;
     private BigDecimal relposy;
     private BigDecimal relwidth;
     private BigDecimal relheight;
     private String token1;
     private String token2;
     private String token3;
     private String cid;
     private String type;
     private String viewclass;

    public Mstdashboardlayout() {
    }

	
    public Mstdashboardlayout(MstdashboardlayoutId id) {
        this.id = id;
    }
    public Mstdashboardlayout(MstdashboardlayoutId id, String idrequest, String idtxn, BigDecimal relposx, BigDecimal relposy, BigDecimal relwidth, BigDecimal relheight, String token1, String token2, String token3, String cid, String type, String viewclass) {
       this.id = id;
       this.idrequest = idrequest;
       this.idtxn = idtxn;
       this.relposx = relposx;
       this.relposy = relposy;
       this.relwidth = relwidth;
       this.relheight = relheight;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.cid = cid;
       this.type = type;
       this.viewclass = viewclass;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=20) ), 
        @AttributeOverride(name="idseq", column=@Column(name="IDSEQ", nullable=false, precision=2, scale=0) ) } )
    public MstdashboardlayoutId getId() {
        return this.id;
    }
    
    public void setId(MstdashboardlayoutId id) {
        this.id = id;
    }

    
    @Column(name="IDREQUEST", length=8)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="RELPOSX", precision=4, scale=3)
    public BigDecimal getRelposx() {
        return this.relposx;
    }
    
    public void setRelposx(BigDecimal relposx) {
        this.relposx = relposx;
    }

    
    @Column(name="RELPOSY", precision=4, scale=3)
    public BigDecimal getRelposy() {
        return this.relposy;
    }
    
    public void setRelposy(BigDecimal relposy) {
        this.relposy = relposy;
    }

    
    @Column(name="RELWIDTH", precision=4, scale=3)
    public BigDecimal getRelwidth() {
        return this.relwidth;
    }
    
    public void setRelwidth(BigDecimal relwidth) {
        this.relwidth = relwidth;
    }

    
    @Column(name="RELHEIGHT", precision=4, scale=3)
    public BigDecimal getRelheight() {
        return this.relheight;
    }
    
    public void setRelheight(BigDecimal relheight) {
        this.relheight = relheight;
    }

    
    @Column(name="TOKEN1", length=20)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=20)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=20)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="CID", length=3)
    public String getCid() {
        return this.cid;
    }
    
    public void setCid(String cid) {
        this.cid = cid;
    }

    
    @Column(name="TYPE", length=3)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="VIEWCLASS", length=25)
    public String getViewclass() {
        return this.viewclass;
    }
    
    public void setViewclass(String viewclass) {
        this.viewclass = viewclass;
    }




}


