package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstentitytypes generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYTYPES"
    ,schema="FCDBADMIN_RK"
)
public class Mstentitytypes  implements java.io.Serializable {


     private char typentity;
     private String description;
     private Set<Mstentity> mstentities = new HashSet<Mstentity>(0);

    public Mstentitytypes() {
    }

	
    public Mstentitytypes(char typentity) {
        this.typentity = typentity;
    }
    public Mstentitytypes(char typentity, String description, Set<Mstentity> mstentities) {
       this.typentity = typentity;
       this.description = description;
       this.mstentities = mstentities;
    }
   
     @Id 

    
    @Column(name="TYPENTITY", unique=true, nullable=false, length=1)
    public char getTypentity() {
        return this.typentity;
    }
    
    public void setTypentity(char typentity) {
        this.typentity = typentity;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstentitytypes")
    public Set<Mstentity> getMstentities() {
        return this.mstentities;
    }
    
    public void setMstentities(Set<Mstentity> mstentities) {
        this.mstentities = mstentities;
    }




}


