package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstentityusertypepref generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYUSERTYPEPREF"
    ,schema="FCDBADMIN_RK"
)
public class Mstentityusertypepref  implements java.io.Serializable {


     private MstentityusertypeprefId id;
     private String isenabled;

    public Mstentityusertypepref() {
    }

	
    public Mstentityusertypepref(MstentityusertypeprefId id) {
        this.id = id;
    }
    public Mstentityusertypepref(MstentityusertypeprefId id, String isenabled) {
       this.id = id;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idpref", column=@Column(name="IDPREF", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ) } )
    public MstentityusertypeprefId getId() {
        return this.id;
    }
    
    public void setId(MstentityusertypeprefId id) {
        this.id = id;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }




}


