package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstentityuseralertsId generated by hbm2java
 */
@Embeddable
public class MstentityuseralertsId  implements java.io.Serializable {


     private String idEntity;
     private String typeuser;
     private String idalert;

    public MstentityuseralertsId() {
    }

    public MstentityuseralertsId(String idEntity, String typeuser, String idalert) {
       this.idEntity = idEntity;
       this.typeuser = typeuser;
       this.idalert = idalert;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="TYPEUSER", nullable=false, length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }


    @Column(name="IDALERT", nullable=false, length=50)
    public String getIdalert() {
        return this.idalert;
    }
    
    public void setIdalert(String idalert) {
        this.idalert = idalert;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstentityuseralertsId) ) return false;
		 MstentityuseralertsId castOther = ( MstentityuseralertsId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getTypeuser()==castOther.getTypeuser()) || ( this.getTypeuser()!=null && castOther.getTypeuser()!=null && this.getTypeuser().equals(castOther.getTypeuser()) ) )
 && ( (this.getIdalert()==castOther.getIdalert()) || ( this.getIdalert()!=null && castOther.getIdalert()!=null && this.getIdalert().equals(castOther.getIdalert()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getTypeuser() == null ? 0 : this.getTypeuser().hashCode() );
         result = 37 * result + ( getIdalert() == null ? 0 : this.getIdalert().hashCode() );
         return result;
   }   


}


