package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstentityinitauthmodules generated by hbm2java
 */
@Entity
@Table(name="MSTENTITYINITAUTHMODULES"
    ,schema="FCDBADMIN_RK"
)
public class Mstentityinitauthmodules  implements java.io.Serializable {


     private MstentityinitauthmodulesId id;
     private String idchannel;
     private String idmod;
     private BigDecimal priority;
     private String token1;
     private String token2;
     private String token3;

    public Mstentityinitauthmodules() {
    }

	
    public Mstentityinitauthmodules(MstentityinitauthmodulesId id) {
        this.id = id;
    }
    public Mstentityinitauthmodules(MstentityinitauthmodulesId id, String idchannel, String idmod, BigDecimal priority, String token1, String token2, String token3) {
       this.id = id;
       this.idchannel = idchannel;
       this.idmod = idmod;
       this.priority = priority;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="initauthid", column=@Column(name="INITAUTHID", nullable=false, length=20) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MstentityinitauthmodulesId getId() {
        return this.id;
    }
    
    public void setId(MstentityinitauthmodulesId id) {
        this.id = id;
    }

    
    @Column(name="IDCHANNEL", length=3)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    
    @Column(name="IDMOD", length=5)
    public String getIdmod() {
        return this.idmod;
    }
    
    public void setIdmod(String idmod) {
        this.idmod = idmod;
    }

    
    @Column(name="PRIORITY", precision=22, scale=0)
    public BigDecimal getPriority() {
        return this.priority;
    }
    
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3")
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }




}


