package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstflatrecordId generated by hbm2java
 */
@Embeddable
public class MstflatrecordId  implements java.io.Serializable {


     private String idapp;
     private String idrecord;

    public MstflatrecordId() {
    }

    public MstflatrecordId(String idapp, String idrecord) {
       this.idapp = idapp;
       this.idrecord = idrecord;
    }
   


    @Column(name="IDAPP", nullable=false, length=2)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }


    @Column(name="IDRECORD", nullable=false, length=10)
    public String getIdrecord() {
        return this.idrecord;
    }
    
    public void setIdrecord(String idrecord) {
        this.idrecord = idrecord;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstflatrecordId) ) return false;
		 MstflatrecordId castOther = ( MstflatrecordId ) other; 
         
		 return ( (this.getIdapp()==castOther.getIdapp()) || ( this.getIdapp()!=null && castOther.getIdapp()!=null && this.getIdapp().equals(castOther.getIdapp()) ) )
 && ( (this.getIdrecord()==castOther.getIdrecord()) || ( this.getIdrecord()!=null && castOther.getIdrecord()!=null && this.getIdrecord().equals(castOther.getIdrecord()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdapp() == null ? 0 : this.getIdapp().hashCode() );
         result = 37 * result + ( getIdrecord() == null ? 0 : this.getIdrecord().hashCode() );
         return result;
   }   


}


