package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstflatfield generated by hbm2java
 */
@Entity
@Table(name="MSTFLATFIELD"
    ,schema="FCDBADMIN_RK"
)
public class Mstflatfield  implements java.io.Serializable {


     private MstflatfieldId id;
     private Mstflatrecord mstflatrecord;
     private String namfield;
     private BigDecimal length;
     private Character fixedlenflag;
     private Character justification;
     private Character fillchar;
     private String format;
     private String delimiter;
     private Boolean prefixlen;
     private String defaultvalue;

    public Mstflatfield() {
    }

	
    public Mstflatfield(MstflatfieldId id, Mstflatrecord mstflatrecord) {
        this.id = id;
        this.mstflatrecord = mstflatrecord;
    }
    public Mstflatfield(MstflatfieldId id, Mstflatrecord mstflatrecord, String namfield, BigDecimal length, Character fixedlenflag, Character justification, Character fillchar, String format, String delimiter, Boolean prefixlen, String defaultvalue) {
       this.id = id;
       this.mstflatrecord = mstflatrecord;
       this.namfield = namfield;
       this.length = length;
       this.fixedlenflag = fixedlenflag;
       this.justification = justification;
       this.fillchar = fillchar;
       this.format = format;
       this.delimiter = delimiter;
       this.prefixlen = prefixlen;
       this.defaultvalue = defaultvalue;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idrecord", column=@Column(name="IDRECORD", nullable=false, length=10) ), 
        @AttributeOverride(name="idfield", column=@Column(name="IDFIELD", nullable=false, precision=22, scale=0) ) } )
    public MstflatfieldId getId() {
        return this.id;
    }
    
    public void setId(MstflatfieldId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IDAPP", referencedColumnName="IDAPP", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="IDRECORD", referencedColumnName="IDRECORD", nullable=false, insertable=false, updatable=false) } )
    public Mstflatrecord getMstflatrecord() {
        return this.mstflatrecord;
    }
    
    public void setMstflatrecord(Mstflatrecord mstflatrecord) {
        this.mstflatrecord = mstflatrecord;
    }

    
    @Column(name="NAMFIELD", length=30)
    public String getNamfield() {
        return this.namfield;
    }
    
    public void setNamfield(String namfield) {
        this.namfield = namfield;
    }

    
    @Column(name="LENGTH", precision=22, scale=0)
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    
    @Column(name="FIXEDLENFLAG", length=1)
    public Character getFixedlenflag() {
        return this.fixedlenflag;
    }
    
    public void setFixedlenflag(Character fixedlenflag) {
        this.fixedlenflag = fixedlenflag;
    }

    
    @Column(name="JUSTIFICATION", length=1)
    public Character getJustification() {
        return this.justification;
    }
    
    public void setJustification(Character justification) {
        this.justification = justification;
    }

    
    @Column(name="FILLCHAR", length=1)
    public Character getFillchar() {
        return this.fillchar;
    }
    
    public void setFillchar(Character fillchar) {
        this.fillchar = fillchar;
    }

    
    @Column(name="FORMAT", length=30)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="DELIMITER", length=30)
    public String getDelimiter() {
        return this.delimiter;
    }
    
    public void setDelimiter(String delimiter) {
        this.delimiter = delimiter;
    }

    
    @Column(name="PREFIXLEN", precision=1, scale=0)
    public Boolean getPrefixlen() {
        return this.prefixlen;
    }
    
    public void setPrefixlen(Boolean prefixlen) {
        this.prefixlen = prefixlen;
    }

    
    @Column(name="DEFAULTVALUE", length=50)
    public String getDefaultvalue() {
        return this.defaultvalue;
    }
    
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }




}


