package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstglobalparams generated by hbm2java
 */
@Entity
@Table(name="MSTGLOBALPARAMS"
    ,schema="FCDBADMIN_RK"
)
public class Mstglobalparams  implements java.io.Serializable {


     private MstglobalparamsId id;
     private String paramvalue;

    public Mstglobalparams() {
    }

	
    public Mstglobalparams(MstglobalparamsId id) {
        this.id = id;
    }
    public Mstglobalparams(MstglobalparamsId id, String paramvalue) {
       this.id = id;
       this.paramvalue = paramvalue;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="paramname", column=@Column(name="PARAMNAME", nullable=false, length=100) ) } )
    public MstglobalparamsId getId() {
        return this.id;
    }
    
    public void setId(MstglobalparamsId id) {
        this.id = id;
    }

    
    @Column(name="PARAMVALUE")
    public String getParamvalue() {
        return this.paramvalue;
    }
    
    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue;
    }




}


