package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MsthintsId generated by hbm2java
 */
@Embeddable
public class MsthintsId  implements java.io.Serializable {


     private String idEntity;
     private String usertype;
     private String idChannel;
     private String idrequest;
     private BigDecimal sequenceNo;

    public MsthintsId() {
    }

    public MsthintsId(String idEntity, String usertype, String idChannel, String idrequest, BigDecimal sequenceNo) {
       this.idEntity = idEntity;
       this.usertype = usertype;
       this.idChannel = idChannel;
       this.idrequest = idrequest;
       this.sequenceNo = sequenceNo;
    }
   


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="USERTYPE", nullable=false, length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }


    @Column(name="ID_CHANNEL", nullable=false, length=2)
    public String getIdChannel() {
        return this.idChannel;
    }
    
    public void setIdChannel(String idChannel) {
        this.idChannel = idChannel;
    }


    @Column(name="IDREQUEST", nullable=false, length=50)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }


    @Column(name="SEQUENCE_NO", nullable=false, precision=22, scale=0)
    public BigDecimal getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(BigDecimal sequenceNo) {
        this.sequenceNo = sequenceNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MsthintsId) ) return false;
		 MsthintsId castOther = ( MsthintsId ) other; 
         
		 return ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getUsertype()==castOther.getUsertype()) || ( this.getUsertype()!=null && castOther.getUsertype()!=null && this.getUsertype().equals(castOther.getUsertype()) ) )
 && ( (this.getIdChannel()==castOther.getIdChannel()) || ( this.getIdChannel()!=null && castOther.getIdChannel()!=null && this.getIdChannel().equals(castOther.getIdChannel()) ) )
 && ( (this.getIdrequest()==castOther.getIdrequest()) || ( this.getIdrequest()!=null && castOther.getIdrequest()!=null && this.getIdrequest().equals(castOther.getIdrequest()) ) )
 && ( (this.getSequenceNo()==castOther.getSequenceNo()) || ( this.getSequenceNo()!=null && castOther.getSequenceNo()!=null && this.getSequenceNo().equals(castOther.getSequenceNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getUsertype() == null ? 0 : this.getUsertype().hashCode() );
         result = 37 * result + ( getIdChannel() == null ? 0 : this.getIdChannel().hashCode() );
         result = 37 * result + ( getIdrequest() == null ? 0 : this.getIdrequest().hashCode() );
         result = 37 * result + ( getSequenceNo() == null ? 0 : this.getSequenceNo().hashCode() );
         return result;
   }   


}


