package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Msthtmldatatypes generated by hbm2java
 */
@Entity
@Table(name="MSTHTMLDATATYPES"
    ,schema="FCDBADMIN_RK"
)
public class Msthtmldatatypes  implements java.io.Serializable {


     private String iddata;
     private String description;
     private Set<Screentabledefinition> screentabledefinitions = new HashSet<Screentabledefinition>(0);
     private Set<Screentemplate> screentemplatesForLabeltype = new HashSet<Screentemplate>(0);
     private Set<Screentemplate> screentemplatesForType = new HashSet<Screentemplate>(0);

    public Msthtmldatatypes() {
    }

	
    public Msthtmldatatypes(String iddata) {
        this.iddata = iddata;
    }
    public Msthtmldatatypes(String iddata, String description, Set<Screentabledefinition> screentabledefinitions, Set<Screentemplate> screentemplatesForLabeltype, Set<Screentemplate> screentemplatesForType) {
       this.iddata = iddata;
       this.description = description;
       this.screentabledefinitions = screentabledefinitions;
       this.screentemplatesForLabeltype = screentemplatesForLabeltype;
       this.screentemplatesForType = screentemplatesForType;
    }
   
     @Id 

    
    @Column(name="IDDATA", unique=true, nullable=false, length=3)
    public String getIddata() {
        return this.iddata;
    }
    
    public void setIddata(String iddata) {
        this.iddata = iddata;
    }

    
    @Column(name="DESCRIPTION", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="msthtmldatatypes")
    public Set<Screentabledefinition> getScreentabledefinitions() {
        return this.screentabledefinitions;
    }
    
    public void setScreentabledefinitions(Set<Screentabledefinition> screentabledefinitions) {
        this.screentabledefinitions = screentabledefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="msthtmldatatypesByLabeltype")
    public Set<Screentemplate> getScreentemplatesForLabeltype() {
        return this.screentemplatesForLabeltype;
    }
    
    public void setScreentemplatesForLabeltype(Set<Screentemplate> screentemplatesForLabeltype) {
        this.screentemplatesForLabeltype = screentemplatesForLabeltype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="msthtmldatatypesByType")
    public Set<Screentemplate> getScreentemplatesForType() {
        return this.screentemplatesForType;
    }
    
    public void setScreentemplatesForType(Set<Screentemplate> screentemplatesForType) {
        this.screentemplatesForType = screentemplatesForType;
    }




}


