package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstinitauthstatusId generated by hbm2java
 */
@Embeddable
public class MstinitauthstatusId  implements java.io.Serializable {


     private String initauthid;
     private String flgcurrstatus;
     private String flgaction;
     private String flgnextstatus;

    public MstinitauthstatusId() {
    }

    public MstinitauthstatusId(String initauthid, String flgcurrstatus, String flgaction, String flgnextstatus) {
       this.initauthid = initauthid;
       this.flgcurrstatus = flgcurrstatus;
       this.flgaction = flgaction;
       this.flgnextstatus = flgnextstatus;
    }
   


    @Column(name="INITAUTHID", nullable=false, length=30)
    public String getInitauthid() {
        return this.initauthid;
    }
    
    public void setInitauthid(String initauthid) {
        this.initauthid = initauthid;
    }


    @Column(name="FLGCURRSTATUS", nullable=false, length=5)
    public String getFlgcurrstatus() {
        return this.flgcurrstatus;
    }
    
    public void setFlgcurrstatus(String flgcurrstatus) {
        this.flgcurrstatus = flgcurrstatus;
    }


    @Column(name="FLGACTION", nullable=false, length=5)
    public String getFlgaction() {
        return this.flgaction;
    }
    
    public void setFlgaction(String flgaction) {
        this.flgaction = flgaction;
    }


    @Column(name="FLGNEXTSTATUS", nullable=false, length=5)
    public String getFlgnextstatus() {
        return this.flgnextstatus;
    }
    
    public void setFlgnextstatus(String flgnextstatus) {
        this.flgnextstatus = flgnextstatus;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstinitauthstatusId) ) return false;
		 MstinitauthstatusId castOther = ( MstinitauthstatusId ) other; 
         
		 return ( (this.getInitauthid()==castOther.getInitauthid()) || ( this.getInitauthid()!=null && castOther.getInitauthid()!=null && this.getInitauthid().equals(castOther.getInitauthid()) ) )
 && ( (this.getFlgcurrstatus()==castOther.getFlgcurrstatus()) || ( this.getFlgcurrstatus()!=null && castOther.getFlgcurrstatus()!=null && this.getFlgcurrstatus().equals(castOther.getFlgcurrstatus()) ) )
 && ( (this.getFlgaction()==castOther.getFlgaction()) || ( this.getFlgaction()!=null && castOther.getFlgaction()!=null && this.getFlgaction().equals(castOther.getFlgaction()) ) )
 && ( (this.getFlgnextstatus()==castOther.getFlgnextstatus()) || ( this.getFlgnextstatus()!=null && castOther.getFlgnextstatus()!=null && this.getFlgnextstatus().equals(castOther.getFlgnextstatus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInitauthid() == null ? 0 : this.getInitauthid().hashCode() );
         result = 37 * result + ( getFlgcurrstatus() == null ? 0 : this.getFlgcurrstatus().hashCode() );
         result = 37 * result + ( getFlgaction() == null ? 0 : this.getFlgaction().hashCode() );
         result = 37 * result + ( getFlgnextstatus() == null ? 0 : this.getFlgnextstatus().hashCode() );
         return result;
   }   


}


