package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstmailsubject generated by hbm2java
 */
@Entity
@Table(name="MSTMAILSUBJECT"
    ,schema="FCDBADMIN_RK"
)
public class Mstmailsubject  implements java.io.Serializable {


     private MstmailsubjectId id;
     private Mstentity mstentity;
     private Mstusertypes mstusertypes;
     private String description;
     private String idapp;
     private Date datcreated;
     private String displayname;

    public Mstmailsubject() {
    }

	
    public Mstmailsubject(MstmailsubjectId id, Mstentity mstentity, Mstusertypes mstusertypes) {
        this.id = id;
        this.mstentity = mstentity;
        this.mstusertypes = mstusertypes;
    }
    public Mstmailsubject(MstmailsubjectId id, Mstentity mstentity, Mstusertypes mstusertypes, String description, String idapp, Date datcreated, String displayname) {
       this.id = id;
       this.mstentity = mstentity;
       this.mstusertypes = mstusertypes;
       this.description = description;
       this.idapp = idapp;
       this.datcreated = datcreated;
       this.displayname = displayname;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="subjectid", column=@Column(name="SUBJECTID", nullable=false, length=20) ), 
        @AttributeOverride(name="idrole", column=@Column(name="IDROLE", nullable=false, length=20) ) } )
    public MstmailsubjectId getId() {
        return this.id;
    }
    
    public void setId(MstmailsubjectId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERTYPE", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="IDAPP", length=2)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="DISPLAYNAME", length=20)
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }




}


