package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstmerchantmaster generated by hbm2java
 */
@Entity
@Table(name="MSTMERCHANTMASTER"
    ,schema="FCDBADMIN_RK"
)
public class Mstmerchantmaster  implements java.io.Serializable {


     private String codmerchant;
     private String idaccount;
     private String codbranch;
     private String idmerchant;
     private String description;
     private String staticsucurl;
     private String dynsucurl;
     private String staticfailurl;
     private String dynfailurl;
     private Short statebit;
     private Character alertreqd;
     private String idcommacct;
     private Character flgcommmode;
     private Date datcreated;
     private Date datmodified;
     private String isacctmandatory;
     private String isautoauth;
     private String accounttype;
     private String viewdetailsurl;
     private String viewchallansurl;
     private String emailid;
     private String idEntity;
     private String idcustomer;
     private String defsrcacctflag;

    public Mstmerchantmaster() {
    }

	
    public Mstmerchantmaster(String codmerchant) {
        this.codmerchant = codmerchant;
    }
    public Mstmerchantmaster(String codmerchant, String idaccount, String codbranch, String idmerchant, String description, String staticsucurl, String dynsucurl, String staticfailurl, String dynfailurl, Short statebit, Character alertreqd, String idcommacct, Character flgcommmode, Date datcreated, Date datmodified, String isacctmandatory, String isautoauth, String accounttype, String viewdetailsurl, String viewchallansurl, String emailid, String idEntity, String idcustomer, String defsrcacctflag) {
       this.codmerchant = codmerchant;
       this.idaccount = idaccount;
       this.codbranch = codbranch;
       this.idmerchant = idmerchant;
       this.description = description;
       this.staticsucurl = staticsucurl;
       this.dynsucurl = dynsucurl;
       this.staticfailurl = staticfailurl;
       this.dynfailurl = dynfailurl;
       this.statebit = statebit;
       this.alertreqd = alertreqd;
       this.idcommacct = idcommacct;
       this.flgcommmode = flgcommmode;
       this.datcreated = datcreated;
       this.datmodified = datmodified;
       this.isacctmandatory = isacctmandatory;
       this.isautoauth = isautoauth;
       this.accounttype = accounttype;
       this.viewdetailsurl = viewdetailsurl;
       this.viewchallansurl = viewchallansurl;
       this.emailid = emailid;
       this.idEntity = idEntity;
       this.idcustomer = idcustomer;
       this.defsrcacctflag = defsrcacctflag;
    }
   
     @Id 

    
    @Column(name="CODMERCHANT", unique=true, nullable=false, length=15)
    public String getCodmerchant() {
        return this.codmerchant;
    }
    
    public void setCodmerchant(String codmerchant) {
        this.codmerchant = codmerchant;
    }

    
    @Column(name="IDACCOUNT", length=16)
    public String getIdaccount() {
        return this.idaccount;
    }
    
    public void setIdaccount(String idaccount) {
        this.idaccount = idaccount;
    }

    
    @Column(name="CODBRANCH", length=5)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }

    
    @Column(name="IDMERCHANT", length=20)
    public String getIdmerchant() {
        return this.idmerchant;
    }
    
    public void setIdmerchant(String idmerchant) {
        this.idmerchant = idmerchant;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="STATICSUCURL", length=250)
    public String getStaticsucurl() {
        return this.staticsucurl;
    }
    
    public void setStaticsucurl(String staticsucurl) {
        this.staticsucurl = staticsucurl;
    }

    
    @Column(name="DYNSUCURL", length=250)
    public String getDynsucurl() {
        return this.dynsucurl;
    }
    
    public void setDynsucurl(String dynsucurl) {
        this.dynsucurl = dynsucurl;
    }

    
    @Column(name="STATICFAILURL", length=250)
    public String getStaticfailurl() {
        return this.staticfailurl;
    }
    
    public void setStaticfailurl(String staticfailurl) {
        this.staticfailurl = staticfailurl;
    }

    
    @Column(name="DYNFAILURL", length=250)
    public String getDynfailurl() {
        return this.dynfailurl;
    }
    
    public void setDynfailurl(String dynfailurl) {
        this.dynfailurl = dynfailurl;
    }

    
    @Column(name="STATEBIT", precision=3, scale=0)
    public Short getStatebit() {
        return this.statebit;
    }
    
    public void setStatebit(Short statebit) {
        this.statebit = statebit;
    }

    
    @Column(name="ALERTREQD", length=1)
    public Character getAlertreqd() {
        return this.alertreqd;
    }
    
    public void setAlertreqd(Character alertreqd) {
        this.alertreqd = alertreqd;
    }

    
    @Column(name="IDCOMMACCT", length=16)
    public String getIdcommacct() {
        return this.idcommacct;
    }
    
    public void setIdcommacct(String idcommacct) {
        this.idcommacct = idcommacct;
    }

    
    @Column(name="FLGCOMMMODE", length=1)
    public Character getFlgcommmode() {
        return this.flgcommmode;
    }
    
    public void setFlgcommmode(Character flgcommmode) {
        this.flgcommmode = flgcommmode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMODIFIED", length=7)
    public Date getDatmodified() {
        return this.datmodified;
    }
    
    public void setDatmodified(Date datmodified) {
        this.datmodified = datmodified;
    }

    
    @Column(name="ISACCTMANDATORY", length=2)
    public String getIsacctmandatory() {
        return this.isacctmandatory;
    }
    
    public void setIsacctmandatory(String isacctmandatory) {
        this.isacctmandatory = isacctmandatory;
    }

    
    @Column(name="ISAUTOAUTH", length=2)
    public String getIsautoauth() {
        return this.isautoauth;
    }
    
    public void setIsautoauth(String isautoauth) {
        this.isautoauth = isautoauth;
    }

    
    @Column(name="ACCOUNTTYPE", length=10)
    public String getAccounttype() {
        return this.accounttype;
    }
    
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype;
    }

    
    @Column(name="VIEWDETAILSURL", length=250)
    public String getViewdetailsurl() {
        return this.viewdetailsurl;
    }
    
    public void setViewdetailsurl(String viewdetailsurl) {
        this.viewdetailsurl = viewdetailsurl;
    }

    
    @Column(name="VIEWCHALLANSURL", length=250)
    public String getViewchallansurl() {
        return this.viewchallansurl;
    }
    
    public void setViewchallansurl(String viewchallansurl) {
        this.viewchallansurl = viewchallansurl;
    }

    
    @Column(name="EMAILID", length=1000)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDCUSTOMER", length=20)
    public String getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(String idcustomer) {
        this.idcustomer = idcustomer;
    }

    
    @Column(name="DEFSRCACCTFLAG", length=1)
    public String getDefsrcacctflag() {
        return this.defsrcacctflag;
    }
    
    public void setDefsrcacctflag(String defsrcacctflag) {
        this.defsrcacctflag = defsrcacctflag;
    }




}


