package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstmobdata generated by hbm2java
 */
@Entity
@Table(name="MSTMOBDATA"
    ,schema="FCDBADMIN_RK"
)
public class Mstmobdata  implements java.io.Serializable {


     private MstmobdataId id;
     private String valuestring;

    public Mstmobdata() {
    }

	
    public Mstmobdata(MstmobdataId id) {
        this.id = id;
    }
    public Mstmobdata(MstmobdataId id, String valuestring) {
       this.id = id;
       this.valuestring = valuestring;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dataname", column=@Column(name="DATANAME", nullable=false, length=50) ), 
        @AttributeOverride(name="datacode", column=@Column(name="DATACODE", nullable=false, length=100) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=100) ) } )
    public MstmobdataId getId() {
        return this.id;
    }
    
    public void setId(MstmobdataId id) {
        this.id = id;
    }

    
    @Column(name="VALUESTRING", length=4000)
    public String getValuestring() {
        return this.valuestring;
    }
    
    public void setValuestring(String valuestring) {
        this.valuestring = valuestring;
    }




}


