package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstmapcoordinates generated by hbm2java
 */
@Entity
@Table(name="MSTMAPCOORDINATES"
    ,schema="FCDBADMIN_RK"
)
public class Mstmapcoordinates  implements java.io.Serializable {


     private MstmapcoordinatesId id;

    public Mstmapcoordinates() {
    }

    public Mstmapcoordinates(MstmapcoordinatesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=4) ), 
        @AttributeOverride(name="bankCode", column=@Column(name="BANK_CODE", nullable=false, length=4) ), 
        @AttributeOverride(name="branchCode", column=@Column(name="BRANCH_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="locationtype", column=@Column(name="LOCATIONTYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="latitude", column=@Column(name="LATITUDE", nullable=false, length=32) ), 
        @AttributeOverride(name="longitude", column=@Column(name="LONGITUDE", nullable=false, length=32) ) } )
    public MstmapcoordinatesId getId() {
        return this.id;
    }
    
    public void setId(MstmapcoordinatesId id) {
        this.id = id;
    }




}


