package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mstmodules generated by hbm2java
 */
@Entity
@Table(name="MSTMODULES"
    ,schema="FCDBADMIN_RK"
)
public class Mstmodules  implements java.io.Serializable {


     private String idmod;
     private String moddesc;
     private String modclass;

    public Mstmodules() {
    }

	
    public Mstmodules(String idmod) {
        this.idmod = idmod;
    }
    public Mstmodules(String idmod, String moddesc, String modclass) {
       this.idmod = idmod;
       this.moddesc = moddesc;
       this.modclass = modclass;
    }
   
     @Id 

    
    @Column(name="IDMOD", unique=true, nullable=false, length=5)
    public String getIdmod() {
        return this.idmod;
    }
    
    public void setIdmod(String idmod) {
        this.idmod = idmod;
    }

    
    @Column(name="MODDESC")
    public String getModdesc() {
        return this.moddesc;
    }
    
    public void setModdesc(String moddesc) {
        this.moddesc = moddesc;
    }

    
    @Column(name="MODCLASS")
    public String getModclass() {
        return this.modclass;
    }
    
    public void setModclass(String modclass) {
        this.modclass = modclass;
    }




}


