package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstproperties generated by hbm2java
 */
@Entity
@Table(name="MSTPROPERTIES"
    ,schema="FCDBADMIN_RK"
)
public class Mstproperties  implements java.io.Serializable {


     private MstpropertiesId id;
     private String propvalue;
     private Character enabled;
     private Character ismodified;
     private Date dateffective;
     private Date datmodified;
     private Character isguienabled;

    public Mstproperties() {
    }

	
    public Mstproperties(MstpropertiesId id) {
        this.id = id;
    }
    public Mstproperties(MstpropertiesId id, String propvalue, Character enabled, Character ismodified, Date dateffective, Date datmodified, Character isguienabled) {
       this.id = id;
       this.propvalue = propvalue;
       this.enabled = enabled;
       this.ismodified = ismodified;
       this.dateffective = dateffective;
       this.datmodified = datmodified;
       this.isguienabled = isguienabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idserver", column=@Column(name="IDSERVER", nullable=false, length=59) ), 
        @AttributeOverride(name="propname", column=@Column(name="PROPNAME", nullable=false) ) } )
    public MstpropertiesId getId() {
        return this.id;
    }
    
    public void setId(MstpropertiesId id) {
        this.id = id;
    }

    
    @Column(name="PROPVALUE", length=4000)
    public String getPropvalue() {
        return this.propvalue;
    }
    
    public void setPropvalue(String propvalue) {
        this.propvalue = propvalue;
    }

    
    @Column(name="ENABLED", length=1)
    public Character getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Character enabled) {
        this.enabled = enabled;
    }

    
    @Column(name="ISMODIFIED", length=1)
    public Character getIsmodified() {
        return this.ismodified;
    }
    
    public void setIsmodified(Character ismodified) {
        this.ismodified = ismodified;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEFFECTIVE", length=7)
    public Date getDateffective() {
        return this.dateffective;
    }
    
    public void setDateffective(Date dateffective) {
        this.dateffective = dateffective;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMODIFIED", length=7)
    public Date getDatmodified() {
        return this.datmodified;
    }
    
    public void setDatmodified(Date datmodified) {
        this.datmodified = datmodified;
    }

    
    @Column(name="ISGUIENABLED", length=1)
    public Character getIsguienabled() {
        return this.isguienabled;
    }
    
    public void setIsguienabled(Character isguienabled) {
        this.isguienabled = isguienabled;
    }




}


