package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstquery generated by hbm2java
 */
@Entity
@Table(name="MSTQUERY"
    ,schema="FCDBADMIN_RK"
)
public class Mstquery  implements java.io.Serializable {


     private MstqueryId id;
     private String querydesc;
     private String querystr;
     private String stmttype;
     private String querytype;
     private Short maxrows;
     private Character isldbquery;
     private Short nbrparams;

    public Mstquery() {
    }

	
    public Mstquery(MstqueryId id) {
        this.id = id;
    }
    public Mstquery(MstqueryId id, String querydesc, String querystr, String stmttype, String querytype, Short maxrows, Character isldbquery, Short nbrparams) {
       this.id = id;
       this.querydesc = querydesc;
       this.querystr = querystr;
       this.stmttype = stmttype;
       this.querytype = querytype;
       this.maxrows = maxrows;
       this.isldbquery = isldbquery;
       this.nbrparams = nbrparams;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idquery", column=@Column(name="IDQUERY", nullable=false, length=50) ), 
        @AttributeOverride(name="databasetype", column=@Column(name="DATABASETYPE", nullable=false, length=50) ) } )
    public MstqueryId getId() {
        return this.id;
    }
    
    public void setId(MstqueryId id) {
        this.id = id;
    }

    
    @Column(name="QUERYDESC")
    public String getQuerydesc() {
        return this.querydesc;
    }
    
    public void setQuerydesc(String querydesc) {
        this.querydesc = querydesc;
    }

    
    @Column(name="QUERYSTR", length=4000)
    public String getQuerystr() {
        return this.querystr;
    }
    
    public void setQuerystr(String querystr) {
        this.querystr = querystr;
    }

    
    @Column(name="STMTTYPE", length=1)
    public String getStmttype() {
        return this.stmttype;
    }
    
    public void setStmttype(String stmttype) {
        this.stmttype = stmttype;
    }

    
    @Column(name="QUERYTYPE", length=1)
    public String getQuerytype() {
        return this.querytype;
    }
    
    public void setQuerytype(String querytype) {
        this.querytype = querytype;
    }

    
    @Column(name="MAXROWS", precision=4, scale=0)
    public Short getMaxrows() {
        return this.maxrows;
    }
    
    public void setMaxrows(Short maxrows) {
        this.maxrows = maxrows;
    }

    
    @Column(name="ISLDBQUERY", length=1)
    public Character getIsldbquery() {
        return this.isldbquery;
    }
    
    public void setIsldbquery(Character isldbquery) {
        this.isldbquery = isldbquery;
    }

    
    @Column(name="NBRPARAMS", precision=3, scale=0)
    public Short getNbrparams() {
        return this.nbrparams;
    }
    
    public void setNbrparams(Short nbrparams) {
        this.nbrparams = nbrparams;
    }




}


