package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstrouternickoper generated by hbm2java
 */
@Entity
@Table(name="MSTROUTERNICKOPER"
    ,schema="FCDBADMIN_RK"
)
public class Mstrouternickoper  implements java.io.Serializable {


     private String namnick;
     private String namoper;
     private Character forceReplace;
     private Set<Mstrouteroperparam> mstrouteroperparams = new HashSet<Mstrouteroperparam>(0);

    public Mstrouternickoper() {
    }

	
    public Mstrouternickoper(String namnick) {
        this.namnick = namnick;
    }
    public Mstrouternickoper(String namnick, String namoper, Character forceReplace, Set<Mstrouteroperparam> mstrouteroperparams) {
       this.namnick = namnick;
       this.namoper = namoper;
       this.forceReplace = forceReplace;
       this.mstrouteroperparams = mstrouteroperparams;
    }
   
     @Id 

    
    @Column(name="NAMNICK", unique=true, nullable=false, length=50)
    public String getNamnick() {
        return this.namnick;
    }
    
    public void setNamnick(String namnick) {
        this.namnick = namnick;
    }

    
    @Column(name="NAMOPER", length=50)
    public String getNamoper() {
        return this.namoper;
    }
    
    public void setNamoper(String namoper) {
        this.namoper = namoper;
    }

    
    @Column(name="FORCE_REPLACE", length=1)
    public Character getForceReplace() {
        return this.forceReplace;
    }
    
    public void setForceReplace(Character forceReplace) {
        this.forceReplace = forceReplace;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstrouternickoper")
    public Set<Mstrouteroperparam> getMstrouteroperparams() {
        return this.mstrouteroperparams;
    }
    
    public void setMstrouteroperparams(Set<Mstrouteroperparam> mstrouteroperparams) {
        this.mstrouteroperparams = mstrouteroperparams;
    }




}


