package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstrouterparams generated by hbm2java
 */
@Entity
@Table(name="MSTROUTERPARAMS"
    ,schema="FCDBADMIN_RK"
)
public class Mstrouterparams  implements java.io.Serializable {


     private MstrouterparamsId id;
     private String value;

    public Mstrouterparams() {
    }

	
    public Mstrouterparams(MstrouterparamsId id) {
        this.id = id;
    }
    public Mstrouterparams(MstrouterparamsId id, String value) {
       this.id = id;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false) ), 
        @AttributeOverride(name="idoperator", column=@Column(name="IDOPERATOR", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false) ) } )
    public MstrouterparamsId getId() {
        return this.id;
    }
    
    public void setId(MstrouterparamsId id) {
        this.id = id;
    }

    
    @Column(name="VALUE")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


