package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstruleexpression generated by hbm2java
 */
@Entity
@Table(name="MSTRULEEXPRESSION"
    ,schema="FCDBADMIN_RK"
)
public class Mstruleexpression  implements java.io.Serializable {


     private MstruleexpressionId id;
     private Character datatype;
     private Character operator;
     private Character optype1;
     private Byte opindex1;
     private Character optype2;
     private Byte opindex2;
     private String name;
     private Character optype3;
     private Byte opindex3;

    public Mstruleexpression() {
    }

	
    public Mstruleexpression(MstruleexpressionId id) {
        this.id = id;
    }
    public Mstruleexpression(MstruleexpressionId id, Character datatype, Character operator, Character optype1, Byte opindex1, Character optype2, Byte opindex2, String name, Character optype3, Byte opindex3) {
       this.id = id;
       this.datatype = datatype;
       this.operator = operator;
       this.optype1 = optype1;
       this.opindex1 = opindex1;
       this.optype2 = optype2;
       this.opindex2 = opindex2;
       this.name = name;
       this.optype3 = optype3;
       this.opindex3 = opindex3;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false, length=30) ), 
        @AttributeOverride(name="idindex", column=@Column(name="IDINDEX", nullable=false, precision=2, scale=0) ) } )
    public MstruleexpressionId getId() {
        return this.id;
    }
    
    public void setId(MstruleexpressionId id) {
        this.id = id;
    }

    
    @Column(name="DATATYPE", length=1)
    public Character getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(Character datatype) {
        this.datatype = datatype;
    }

    
    @Column(name="OPERATOR", length=1)
    public Character getOperator() {
        return this.operator;
    }
    
    public void setOperator(Character operator) {
        this.operator = operator;
    }

    
    @Column(name="OPTYPE1", length=1)
    public Character getOptype1() {
        return this.optype1;
    }
    
    public void setOptype1(Character optype1) {
        this.optype1 = optype1;
    }

    
    @Column(name="OPINDEX1", precision=2, scale=0)
    public Byte getOpindex1() {
        return this.opindex1;
    }
    
    public void setOpindex1(Byte opindex1) {
        this.opindex1 = opindex1;
    }

    
    @Column(name="OPTYPE2", length=1)
    public Character getOptype2() {
        return this.optype2;
    }
    
    public void setOptype2(Character optype2) {
        this.optype2 = optype2;
    }

    
    @Column(name="OPINDEX2", precision=2, scale=0)
    public Byte getOpindex2() {
        return this.opindex2;
    }
    
    public void setOpindex2(Byte opindex2) {
        this.opindex2 = opindex2;
    }

    
    @Column(name="NAME", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="OPTYPE3", length=1)
    public Character getOptype3() {
        return this.optype3;
    }
    
    public void setOptype3(Character optype3) {
        this.optype3 = optype3;
    }

    
    @Column(name="OPINDEX3", precision=2, scale=0)
    public Byte getOpindex3() {
        return this.opindex3;
    }
    
    public void setOpindex3(Byte opindex3) {
        this.opindex3 = opindex3;
    }




}


