package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstreminder generated by hbm2java
 */
@Entity
@Table(name="MSTREMINDER"
    ,schema="FCDBADMIN_RK"
)
public class Mstreminder  implements java.io.Serializable {


     private String idreminder;
     private String iduser;
     private String remindersubject;
     private String reminderdesc;
     private String reminderfreq;
     private Date startdate;
     private Date enddate;
     private String occurences;
     private Date registerdate;

    public Mstreminder() {
    }

	
    public Mstreminder(String idreminder) {
        this.idreminder = idreminder;
    }
    public Mstreminder(String idreminder, String iduser, String remindersubject, String reminderdesc, String reminderfreq, Date startdate, Date enddate, String occurences, Date registerdate) {
       this.idreminder = idreminder;
       this.iduser = iduser;
       this.remindersubject = remindersubject;
       this.reminderdesc = reminderdesc;
       this.reminderfreq = reminderfreq;
       this.startdate = startdate;
       this.enddate = enddate;
       this.occurences = occurences;
       this.registerdate = registerdate;
    }
   
     @Id 

    
    @Column(name="IDREMINDER", unique=true, nullable=false, length=20)
    public String getIdreminder() {
        return this.idreminder;
    }
    
    public void setIdreminder(String idreminder) {
        this.idreminder = idreminder;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="REMINDERSUBJECT", length=50)
    public String getRemindersubject() {
        return this.remindersubject;
    }
    
    public void setRemindersubject(String remindersubject) {
        this.remindersubject = remindersubject;
    }

    
    @Column(name="REMINDERDESC", length=100)
    public String getReminderdesc() {
        return this.reminderdesc;
    }
    
    public void setReminderdesc(String reminderdesc) {
        this.reminderdesc = reminderdesc;
    }

    
    @Column(name="REMINDERFREQ", length=2)
    public String getReminderfreq() {
        return this.reminderfreq;
    }
    
    public void setReminderfreq(String reminderfreq) {
        this.reminderfreq = reminderfreq;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STARTDATE", length=7)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENDDATE", length=7)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    
    @Column(name="OCCURENCES", length=3)
    public String getOccurences() {
        return this.occurences;
    }
    
    public void setOccurences(String occurences) {
        this.occurences = occurences;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REGISTERDATE", length=7)
    public Date getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }




}


