package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mstruleoperator generated by hbm2java
 */
@Entity
@Table(name="MSTRULEOPERATOR"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="SIGNOPERATOR") 
)
public class Mstruleoperator  implements java.io.Serializable {


     private int idoperator;
     private String typeoperator;
     private String description;
     private Character isenabled;
     private String typeoperands;
     private String signoperator;

    public Mstruleoperator() {
    }

	
    public Mstruleoperator(int idoperator) {
        this.idoperator = idoperator;
    }
    public Mstruleoperator(int idoperator, String typeoperator, String description, Character isenabled, String typeoperands, String signoperator) {
       this.idoperator = idoperator;
       this.typeoperator = typeoperator;
       this.description = description;
       this.isenabled = isenabled;
       this.typeoperands = typeoperands;
       this.signoperator = signoperator;
    }
   
     @Id 

    
    @Column(name="IDOPERATOR", unique=true, nullable=false, precision=9, scale=0)
    public int getIdoperator() {
        return this.idoperator;
    }
    
    public void setIdoperator(int idoperator) {
        this.idoperator = idoperator;
    }

    
    @Column(name="TYPEOPERATOR", length=10)
    public String getTypeoperator() {
        return this.typeoperator;
    }
    
    public void setTypeoperator(String typeoperator) {
        this.typeoperator = typeoperator;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="TYPEOPERANDS")
    public String getTypeoperands() {
        return this.typeoperands;
    }
    
    public void setTypeoperands(String typeoperands) {
        this.typeoperands = typeoperands;
    }

    
    @Column(name="SIGNOPERATOR", unique=true, length=10)
    public String getSignoperator() {
        return this.signoperator;
    }
    
    public void setSignoperator(String signoperator) {
        this.signoperator = signoperator;
    }




}


