package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstrouterrule generated by hbm2java
 */
@Entity
@Table(name="MSTROUTERRULE"
    ,schema="FCDBADMIN_RK"
)
public class Mstrouterrule  implements java.io.Serializable {


     private MstrouterruleId id;
     private String namrule;
     private byte[] xmlrule;
     private String customHandler;
     private Character isenabled;
     private String auditHandler;
     private Date lastupddatetime;
     private Integer slno;
     private Byte processingmode;
     private Byte errorHandler;
     private String allowedSeverity;
     private Byte authorization;
     private Byte compression;
     private Byte requestype;
     private Byte encryption;
     private Character repairAllowed;
     private Byte messageValidation;
     private Byte requesttype;
     private Character validationrequired;

    public Mstrouterrule() {
    }

	
    public Mstrouterrule(MstrouterruleId id) {
        this.id = id;
    }
    public Mstrouterrule(MstrouterruleId id, String namrule, byte[] xmlrule, String customHandler, Character isenabled, String auditHandler, Date lastupddatetime, Integer slno, Byte processingmode, Byte errorHandler, String allowedSeverity, Byte authorization, Byte compression, Byte requestype, Byte encryption, Character repairAllowed, Byte messageValidation, Byte requesttype, Character validationrequired) {
       this.id = id;
       this.namrule = namrule;
       this.xmlrule = xmlrule;
       this.customHandler = customHandler;
       this.isenabled = isenabled;
       this.auditHandler = auditHandler;
       this.lastupddatetime = lastupddatetime;
       this.slno = slno;
       this.processingmode = processingmode;
       this.errorHandler = errorHandler;
       this.allowedSeverity = allowedSeverity;
       this.authorization = authorization;
       this.compression = compression;
       this.requestype = requestype;
       this.encryption = encryption;
       this.repairAllowed = repairAllowed;
       this.messageValidation = messageValidation;
       this.requesttype = requesttype;
       this.validationrequired = validationrequired;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrule", column=@Column(name="IDRULE", nullable=false) ), 
        @AttributeOverride(name="ruleversion", column=@Column(name="RULEVERSION", nullable=false, precision=4, scale=0) ) } )
    public MstrouterruleId getId() {
        return this.id;
    }
    
    public void setId(MstrouterruleId id) {
        this.id = id;
    }

    
    @Column(name="NAMRULE")
    public String getNamrule() {
        return this.namrule;
    }
    
    public void setNamrule(String namrule) {
        this.namrule = namrule;
    }

    
    @Column(name="XMLRULE")
    public byte[] getXmlrule() {
        return this.xmlrule;
    }
    
    public void setXmlrule(byte[] xmlrule) {
        this.xmlrule = xmlrule;
    }

    
    @Column(name="CUSTOM_HANDLER")
    public String getCustomHandler() {
        return this.customHandler;
    }
    
    public void setCustomHandler(String customHandler) {
        this.customHandler = customHandler;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="AUDIT_HANDLER")
    public String getAuditHandler() {
        return this.auditHandler;
    }
    
    public void setAuditHandler(String auditHandler) {
        this.auditHandler = auditHandler;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTUPDDATETIME", length=7)
    public Date getLastupddatetime() {
        return this.lastupddatetime;
    }
    
    public void setLastupddatetime(Date lastupddatetime) {
        this.lastupddatetime = lastupddatetime;
    }

    
    @Column(name="SLNO", precision=8, scale=0)
    public Integer getSlno() {
        return this.slno;
    }
    
    public void setSlno(Integer slno) {
        this.slno = slno;
    }

    
    @Column(name="PROCESSINGMODE", precision=2, scale=0)
    public Byte getProcessingmode() {
        return this.processingmode;
    }
    
    public void setProcessingmode(Byte processingmode) {
        this.processingmode = processingmode;
    }

    
    @Column(name="ERROR_HANDLER", precision=2, scale=0)
    public Byte getErrorHandler() {
        return this.errorHandler;
    }
    
    public void setErrorHandler(Byte errorHandler) {
        this.errorHandler = errorHandler;
    }

    
    @Column(name="ALLOWED_SEVERITY", length=5)
    public String getAllowedSeverity() {
        return this.allowedSeverity;
    }
    
    public void setAllowedSeverity(String allowedSeverity) {
        this.allowedSeverity = allowedSeverity;
    }

    
    @Column(name="AUTHORIZATION", precision=2, scale=0)
    public Byte getAuthorization() {
        return this.authorization;
    }
    
    public void setAuthorization(Byte authorization) {
        this.authorization = authorization;
    }

    
    @Column(name="COMPRESSION", precision=2, scale=0)
    public Byte getCompression() {
        return this.compression;
    }
    
    public void setCompression(Byte compression) {
        this.compression = compression;
    }

    
    @Column(name="REQUESTYPE", precision=2, scale=0)
    public Byte getRequestype() {
        return this.requestype;
    }
    
    public void setRequestype(Byte requestype) {
        this.requestype = requestype;
    }

    
    @Column(name="ENCRYPTION", precision=2, scale=0)
    public Byte getEncryption() {
        return this.encryption;
    }
    
    public void setEncryption(Byte encryption) {
        this.encryption = encryption;
    }

    
    @Column(name="REPAIR_ALLOWED", length=1)
    public Character getRepairAllowed() {
        return this.repairAllowed;
    }
    
    public void setRepairAllowed(Character repairAllowed) {
        this.repairAllowed = repairAllowed;
    }

    
    @Column(name="MESSAGE_VALIDATION", precision=2, scale=0)
    public Byte getMessageValidation() {
        return this.messageValidation;
    }
    
    public void setMessageValidation(Byte messageValidation) {
        this.messageValidation = messageValidation;
    }

    
    @Column(name="REQUESTTYPE", precision=2, scale=0)
    public Byte getRequesttype() {
        return this.requesttype;
    }
    
    public void setRequesttype(Byte requesttype) {
        this.requesttype = requesttype;
    }

    
    @Column(name="VALIDATIONREQUIRED", length=1)
    public Character getValidationrequired() {
        return this.validationrequired;
    }
    
    public void setValidationrequired(Character validationrequired) {
        this.validationrequired = validationrequired;
    }




}


