package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstreportformats generated by hbm2java
 */
@Entity
@Table(name="MSTREPORTFORMATS"
    ,schema="FCDBADMIN_RK"
)
public class Mstreportformats  implements java.io.Serializable {


     private MstreportformatsId id;
     private String formatdesc;
     private String exporterclass;

    public Mstreportformats() {
    }

	
    public Mstreportformats(MstreportformatsId id) {
        this.id = id;
    }
    public Mstreportformats(MstreportformatsId id, String formatdesc, String exporterclass) {
       this.id = id;
       this.formatdesc = formatdesc;
       this.exporterclass = exporterclass;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idengine", column=@Column(name="IDENGINE", nullable=false, length=10) ), 
        @AttributeOverride(name="idformat", column=@Column(name="IDFORMAT", nullable=false, length=10) ) } )
    public MstreportformatsId getId() {
        return this.id;
    }
    
    public void setId(MstreportformatsId id) {
        this.id = id;
    }

    
    @Column(name="FORMATDESC", length=100)
    public String getFormatdesc() {
        return this.formatdesc;
    }
    
    public void setFormatdesc(String formatdesc) {
        this.formatdesc = formatdesc;
    }

    
    @Column(name="EXPORTERCLASS", length=200)
    public String getExporterclass() {
        return this.exporterclass;
    }
    
    public void setExporterclass(String exporterclass) {
        this.exporterclass = exporterclass;
    }




}


