package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mstservicerequest generated by hbm2java
 */
@Entity
@Table(name="MSTSERVICEREQUEST"
    ,schema="FCDBADMIN_RK"
)
public class Mstservicerequest  implements java.io.Serializable {


     private String typerequest;
     private String description;
     private String status;

    public Mstservicerequest() {
    }

	
    public Mstservicerequest(String typerequest) {
        this.typerequest = typerequest;
    }
    public Mstservicerequest(String typerequest, String description, String status) {
       this.typerequest = typerequest;
       this.description = description;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="TYPEREQUEST", unique=true, nullable=false, length=3)
    public String getTyperequest() {
        return this.typerequest;
    }
    
    public void setTyperequest(String typerequest) {
        this.typerequest = typerequest;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="STATUS")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


