package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mststatusconfig generated by hbm2java
 */
@Entity
@Table(name="MSTSTATUSCONFIG"
    ,schema="FCDBADMIN_RK"
)
public class Mststatusconfig  implements java.io.Serializable {


     private String statusCode;
     private String statusDesc;
     private String isservicecallreq;
     private String token1;
     private String token2;
     private String token3;
     private Set<Mstinitauthstatus> mstinitauthstatusesForFlgnextstatus = new HashSet<Mstinitauthstatus>(0);
     private Set<Mstinitauthstatus> mstinitauthstatusesForFlgcurrstatus = new HashSet<Mstinitauthstatus>(0);
     private Set<Mststatusgroupmap> mststatusgroupmaps = new HashSet<Mststatusgroupmap>(0);

    public Mststatusconfig() {
    }

	
    public Mststatusconfig(String statusCode) {
        this.statusCode = statusCode;
    }
    public Mststatusconfig(String statusCode, String statusDesc, String isservicecallreq, String token1, String token2, String token3, Set<Mstinitauthstatus> mstinitauthstatusesForFlgnextstatus, Set<Mstinitauthstatus> mstinitauthstatusesForFlgcurrstatus, Set<Mststatusgroupmap> mststatusgroupmaps) {
       this.statusCode = statusCode;
       this.statusDesc = statusDesc;
       this.isservicecallreq = isservicecallreq;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.mstinitauthstatusesForFlgnextstatus = mstinitauthstatusesForFlgnextstatus;
       this.mstinitauthstatusesForFlgcurrstatus = mstinitauthstatusesForFlgcurrstatus;
       this.mststatusgroupmaps = mststatusgroupmaps;
    }
   
     @Id 

    
    @Column(name="STATUS_CODE", unique=true, nullable=false, length=5)
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="STATUS_DESC", length=50)
    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    
    @Column(name="ISSERVICECALLREQ", length=1)
    public String getIsservicecallreq() {
        return this.isservicecallreq;
    }
    
    public void setIsservicecallreq(String isservicecallreq) {
        this.isservicecallreq = isservicecallreq;
    }

    
    @Column(name="TOKEN1", length=30)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=30)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=30)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mststatusconfigByFlgnextstatus")
    public Set<Mstinitauthstatus> getMstinitauthstatusesForFlgnextstatus() {
        return this.mstinitauthstatusesForFlgnextstatus;
    }
    
    public void setMstinitauthstatusesForFlgnextstatus(Set<Mstinitauthstatus> mstinitauthstatusesForFlgnextstatus) {
        this.mstinitauthstatusesForFlgnextstatus = mstinitauthstatusesForFlgnextstatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mststatusconfigByFlgcurrstatus")
    public Set<Mstinitauthstatus> getMstinitauthstatusesForFlgcurrstatus() {
        return this.mstinitauthstatusesForFlgcurrstatus;
    }
    
    public void setMstinitauthstatusesForFlgcurrstatus(Set<Mstinitauthstatus> mstinitauthstatusesForFlgcurrstatus) {
        this.mstinitauthstatusesForFlgcurrstatus = mstinitauthstatusesForFlgcurrstatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mststatusconfig")
    public Set<Mststatusgroupmap> getMststatusgroupmaps() {
        return this.mststatusgroupmaps;
    }
    
    public void setMststatusgroupmaps(Set<Mststatusgroupmap> mststatusgroupmaps) {
        this.mststatusgroupmaps = mststatusgroupmaps;
    }




}


