package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstsourcebenelinkage generated by hbm2java
 */
@Entity
@Table(name="MSTSOURCEBENELINKAGE"
    ,schema="FCDBADMIN_RK"
)
public class Mstsourcebenelinkage  implements java.io.Serializable {


     private MstsourcebenelinkageId id;
     private Mstentity mstentity;
     private String destaccount;
     private String natlclrcodetype;
     private String natlclrcode;
     private String bankname;
     private String bankadd1;
     private String bankadd2;
     private String city;
     private String benename;
     private String beneadd1;
     private String beneadd2;
     private String benecity;

    public Mstsourcebenelinkage() {
    }

	
    public Mstsourcebenelinkage(MstsourcebenelinkageId id, Mstentity mstentity) {
        this.id = id;
        this.mstentity = mstentity;
    }
    public Mstsourcebenelinkage(MstsourcebenelinkageId id, Mstentity mstentity, String destaccount, String natlclrcodetype, String natlclrcode, String bankname, String bankadd1, String bankadd2, String city, String benename, String beneadd1, String beneadd2, String benecity) {
       this.id = id;
       this.mstentity = mstentity;
       this.destaccount = destaccount;
       this.natlclrcodetype = natlclrcodetype;
       this.natlclrcode = natlclrcode;
       this.bankname = bankname;
       this.bankadd1 = bankadd1;
       this.bankadd2 = bankadd2;
       this.city = city;
       this.benename = benename;
       this.beneadd1 = beneadd1;
       this.beneadd2 = beneadd2;
       this.benecity = benecity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idcustomer", column=@Column(name="IDCUSTOMER", nullable=false, length=16) ), 
        @AttributeOverride(name="srcaccount", column=@Column(name="SRCACCOUNT", nullable=false, length=30) ), 
        @AttributeOverride(name="codbranch", column=@Column(name="CODBRANCH", nullable=false, length=5) ) } )
    public MstsourcebenelinkageId getId() {
        return this.id;
    }
    
    public void setId(MstsourcebenelinkageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

    
    @Column(name="DESTACCOUNT", length=30)
    public String getDestaccount() {
        return this.destaccount;
    }
    
    public void setDestaccount(String destaccount) {
        this.destaccount = destaccount;
    }

    
    @Column(name="NATLCLRCODETYPE", length=30)
    public String getNatlclrcodetype() {
        return this.natlclrcodetype;
    }
    
    public void setNatlclrcodetype(String natlclrcodetype) {
        this.natlclrcodetype = natlclrcodetype;
    }

    
    @Column(name="NATLCLRCODE", length=30)
    public String getNatlclrcode() {
        return this.natlclrcode;
    }
    
    public void setNatlclrcode(String natlclrcode) {
        this.natlclrcode = natlclrcode;
    }

    
    @Column(name="BANKNAME", length=50)
    public String getBankname() {
        return this.bankname;
    }
    
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    
    @Column(name="BANKADD1", length=105)
    public String getBankadd1() {
        return this.bankadd1;
    }
    
    public void setBankadd1(String bankadd1) {
        this.bankadd1 = bankadd1;
    }

    
    @Column(name="BANKADD2", length=105)
    public String getBankadd2() {
        return this.bankadd2;
    }
    
    public void setBankadd2(String bankadd2) {
        this.bankadd2 = bankadd2;
    }

    
    @Column(name="CITY", length=105)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="BENENAME", length=50)
    public String getBenename() {
        return this.benename;
    }
    
    public void setBenename(String benename) {
        this.benename = benename;
    }

    
    @Column(name="BENEADD1", length=105)
    public String getBeneadd1() {
        return this.beneadd1;
    }
    
    public void setBeneadd1(String beneadd1) {
        this.beneadd1 = beneadd1;
    }

    
    @Column(name="BENEADD2", length=105)
    public String getBeneadd2() {
        return this.beneadd2;
    }
    
    public void setBeneadd2(String beneadd2) {
        this.beneadd2 = beneadd2;
    }

    
    @Column(name="BENECITY", length=105)
    public String getBenecity() {
        return this.benecity;
    }
    
    public void setBenecity(String benecity) {
        this.benecity = benecity;
    }




}


