package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstservicesmap generated by hbm2java
 */
@Entity
@Table(name="MSTSERVICESMAP"
    ,schema="FCDBADMIN_RK"
)
public class Mstservicesmap  implements java.io.Serializable {


     private MstservicesmapId id;
     private String isenabled;

    public Mstservicesmap() {
    }

	
    public Mstservicesmap(MstservicesmapId id) {
        this.id = id;
    }
    public Mstservicesmap(MstservicesmapId id, String isenabled) {
       this.id = id;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="namservice", column=@Column(name="NAMSERVICE", nullable=false) ), 
        @AttributeOverride(name="inputversion", column=@Column(name="INPUTVERSION", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="outputversion", column=@Column(name="OUTPUTVERSION", nullable=false, precision=22, scale=0) ) } )
    public MstservicesmapId getId() {
        return this.id;
    }
    
    public void setId(MstservicesmapId id) {
        this.id = id;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }




}


