package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstsecurityquestions generated by hbm2java
 */
@Entity
@Table(name="MSTSECURITYQUESTIONS"
    ,schema="FCDBADMIN_RK"
)
public class Mstsecurityquestions  implements java.io.Serializable {


     private MstsecurityquestionsId id;
     private Mstentity mstentity;
     private Mstusertypes mstusertypes;

    public Mstsecurityquestions() {
    }

    public Mstsecurityquestions(MstsecurityquestionsId id, Mstentity mstentity, Mstusertypes mstusertypes) {
       this.id = id;
       this.mstentity = mstentity;
       this.mstusertypes = mstusertypes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="setNo", column=@Column(name="SET_NO", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="idques", column=@Column(name="IDQUES", nullable=false, length=50) ) } )
    public MstsecurityquestionsId getId() {
        return this.id;
    }
    
    public void setId(MstsecurityquestionsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPEUSER", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }




}


