package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mststatusgroupmap generated by hbm2java
 */
@Entity
@Table(name="MSTSTATUSGROUPMAP"
    ,schema="FCDBADMIN_RK"
)
public class Mststatusgroupmap  implements java.io.Serializable {


     private MststatusgroupmapId id;
     private Mstentity mstentity;
     private Mststatusconfig mststatusconfig;
     private Mstusertypes mstusertypes;
     private String statusGroup;

    public Mststatusgroupmap() {
    }

	
    public Mststatusgroupmap(MststatusgroupmapId id, Mstentity mstentity, Mststatusconfig mststatusconfig, Mstusertypes mstusertypes) {
        this.id = id;
        this.mstentity = mstentity;
        this.mststatusconfig = mststatusconfig;
        this.mstusertypes = mstusertypes;
    }
    public Mststatusgroupmap(MststatusgroupmapId id, Mstentity mstentity, Mststatusconfig mststatusconfig, Mstusertypes mstusertypes, String statusGroup) {
       this.id = id;
       this.mstentity = mstentity;
       this.mststatusconfig = mststatusconfig;
       this.mstusertypes = mstusertypes;
       this.statusGroup = statusGroup;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="statusCode", column=@Column(name="STATUS_CODE", nullable=false, length=5) ) } )
    public MststatusgroupmapId getId() {
        return this.id;
    }
    
    public void setId(MststatusgroupmapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ENTITY", nullable=false, insertable=false, updatable=false)
    public Mstentity getMstentity() {
        return this.mstentity;
    }
    
    public void setMstentity(Mstentity mstentity) {
        this.mstentity = mstentity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_CODE", nullable=false, insertable=false, updatable=false)
    public Mststatusconfig getMststatusconfig() {
        return this.mststatusconfig;
    }
    
    public void setMststatusconfig(Mststatusconfig mststatusconfig) {
        this.mststatusconfig = mststatusconfig;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERTYPE", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }

    
    @Column(name="STATUS_GROUP", length=5)
    public String getStatusGroup() {
        return this.statusGroup;
    }
    
    public void setStatusGroup(String statusGroup) {
        this.statusGroup = statusGroup;
    }




}


