package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Msttxn generated by hbm2java
 */
@Entity
@Table(name="MSTTXN"
    ,schema="FCDBADMIN_RK"
)
public class Msttxn  implements java.io.Serializable {


     private String idtxn;
     private String description;
     private String txngroup;
     private BigDecimal idseq;
     private Character flagservicerequest;
     private String gifname;
     private Character ismenutxn;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private String idproxyreqd;
     private String idapp;
     private String enabletxnblackout;
     private String limitsallowed;
     private String typecust;
     private String codtxn;
     private String idmodule;
     private Character typetxn;
     private String authparam;
     private String adtnlParams;
     private String refAccttype;
     private String proxytxnid;
     private String layoutType;
     private String allowedPrivileges;
     private String isexternal;
     private String livehelpmoduleid;
     private Set<Roletxn> roletxns = new HashSet<Roletxn>(0);

    public Msttxn() {
    }

	
    public Msttxn(String idtxn) {
        this.idtxn = idtxn;
    }
    public Msttxn(String idtxn, String description, String txngroup, BigDecimal idseq, Character flagservicerequest, String gifname, Character ismenutxn, String token1, String token2, String token3, String token4, String token5, String idproxyreqd, String idapp, String enabletxnblackout, String limitsallowed, String typecust, String codtxn, String idmodule, Character typetxn, String authparam, String adtnlParams, String refAccttype, String proxytxnid, String layoutType, String allowedPrivileges, String isexternal, String livehelpmoduleid, Set<Roletxn> roletxns) {
       this.idtxn = idtxn;
       this.description = description;
       this.txngroup = txngroup;
       this.idseq = idseq;
       this.flagservicerequest = flagservicerequest;
       this.gifname = gifname;
       this.ismenutxn = ismenutxn;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.idproxyreqd = idproxyreqd;
       this.idapp = idapp;
       this.enabletxnblackout = enabletxnblackout;
       this.limitsallowed = limitsallowed;
       this.typecust = typecust;
       this.codtxn = codtxn;
       this.idmodule = idmodule;
       this.typetxn = typetxn;
       this.authparam = authparam;
       this.adtnlParams = adtnlParams;
       this.refAccttype = refAccttype;
       this.proxytxnid = proxytxnid;
       this.layoutType = layoutType;
       this.allowedPrivileges = allowedPrivileges;
       this.isexternal = isexternal;
       this.livehelpmoduleid = livehelpmoduleid;
       this.roletxns = roletxns;
    }
   
     @Id 

    
    @Column(name="IDTXN", unique=true, nullable=false, length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="TXNGROUP", length=10)
    public String getTxngroup() {
        return this.txngroup;
    }
    
    public void setTxngroup(String txngroup) {
        this.txngroup = txngroup;
    }

    
    @Column(name="IDSEQ", precision=22, scale=0)
    public BigDecimal getIdseq() {
        return this.idseq;
    }
    
    public void setIdseq(BigDecimal idseq) {
        this.idseq = idseq;
    }

    
    @Column(name="FLAGSERVICEREQUEST", length=1)
    public Character getFlagservicerequest() {
        return this.flagservicerequest;
    }
    
    public void setFlagservicerequest(Character flagservicerequest) {
        this.flagservicerequest = flagservicerequest;
    }

    
    @Column(name="GIFNAME")
    public String getGifname() {
        return this.gifname;
    }
    
    public void setGifname(String gifname) {
        this.gifname = gifname;
    }

    
    @Column(name="ISMENUTXN", length=1)
    public Character getIsmenutxn() {
        return this.ismenutxn;
    }
    
    public void setIsmenutxn(Character ismenutxn) {
        this.ismenutxn = ismenutxn;
    }

    
    @Column(name="TOKEN1")
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2")
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3")
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4")
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5")
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="IDPROXYREQD", length=1)
    public String getIdproxyreqd() {
        return this.idproxyreqd;
    }
    
    public void setIdproxyreqd(String idproxyreqd) {
        this.idproxyreqd = idproxyreqd;
    }

    
    @Column(name="IDAPP", length=2)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }

    
    @Column(name="ENABLETXNBLACKOUT", length=1)
    public String getEnabletxnblackout() {
        return this.enabletxnblackout;
    }
    
    public void setEnabletxnblackout(String enabletxnblackout) {
        this.enabletxnblackout = enabletxnblackout;
    }

    
    @Column(name="LIMITSALLOWED", length=1)
    public String getLimitsallowed() {
        return this.limitsallowed;
    }
    
    public void setLimitsallowed(String limitsallowed) {
        this.limitsallowed = limitsallowed;
    }

    
    @Column(name="TYPECUST", length=20)
    public String getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(String typecust) {
        this.typecust = typecust;
    }

    
    @Column(name="CODTXN", length=4)
    public String getCodtxn() {
        return this.codtxn;
    }
    
    public void setCodtxn(String codtxn) {
        this.codtxn = codtxn;
    }

    
    @Column(name="IDMODULE", length=3)
    public String getIdmodule() {
        return this.idmodule;
    }
    
    public void setIdmodule(String idmodule) {
        this.idmodule = idmodule;
    }

    
    @Column(name="TYPETXN", length=1)
    public Character getTypetxn() {
        return this.typetxn;
    }
    
    public void setTypetxn(Character typetxn) {
        this.typetxn = typetxn;
    }

    
    @Column(name="AUTHPARAM", length=6)
    public String getAuthparam() {
        return this.authparam;
    }
    
    public void setAuthparam(String authparam) {
        this.authparam = authparam;
    }

    
    @Column(name="ADTNL_PARAMS", length=2000)
    public String getAdtnlParams() {
        return this.adtnlParams;
    }
    
    public void setAdtnlParams(String adtnlParams) {
        this.adtnlParams = adtnlParams;
    }

    
    @Column(name="REF_ACCTTYPE", length=10)
    public String getRefAccttype() {
        return this.refAccttype;
    }
    
    public void setRefAccttype(String refAccttype) {
        this.refAccttype = refAccttype;
    }

    
    @Column(name="PROXYTXNID", length=3)
    public String getProxytxnid() {
        return this.proxytxnid;
    }
    
    public void setProxytxnid(String proxytxnid) {
        this.proxytxnid = proxytxnid;
    }

    
    @Column(name="LAYOUT_TYPE", length=5)
    public String getLayoutType() {
        return this.layoutType;
    }
    
    public void setLayoutType(String layoutType) {
        this.layoutType = layoutType;
    }

    
    @Column(name="ALLOWED_PRIVILEGES", length=20)
    public String getAllowedPrivileges() {
        return this.allowedPrivileges;
    }
    
    public void setAllowedPrivileges(String allowedPrivileges) {
        this.allowedPrivileges = allowedPrivileges;
    }

    
    @Column(name="ISEXTERNAL", length=1)
    public String getIsexternal() {
        return this.isexternal;
    }
    
    public void setIsexternal(String isexternal) {
        this.isexternal = isexternal;
    }

    
    @Column(name="LIVEHELPMODULEID", length=10)
    public String getLivehelpmoduleid() {
        return this.livehelpmoduleid;
    }
    
    public void setLivehelpmoduleid(String livehelpmoduleid) {
        this.livehelpmoduleid = livehelpmoduleid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="msttxn")
    public Set<Roletxn> getRoletxns() {
        return this.roletxns;
    }
    
    public void setRoletxns(Set<Roletxn> roletxns) {
        this.roletxns = roletxns;
    }




}


