package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Msttablemap generated by hbm2java
 */
@Entity
@Table(name="MSTTABLEMAP"
    ,schema="FCDBADMIN_RK"
)
public class Msttablemap  implements java.io.Serializable {


     private MsttablemapId id;
     private String outputname;
     private Character isenabled;

    public Msttablemap() {
    }

	
    public Msttablemap(MsttablemapId id) {
        this.id = id;
    }
    public Msttablemap(MsttablemapId id, String outputname, Character isenabled) {
       this.id = id;
       this.outputname = outputname;
       this.isenabled = isenabled;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="typeuser", column=@Column(name="TYPEUSER", nullable=false, length=3) ), 
        @AttributeOverride(name="inputname", column=@Column(name="INPUTNAME", nullable=false, length=256) ) } )
    public MsttablemapId getId() {
        return this.id;
    }
    
    public void setId(MsttablemapId id) {
        this.id = id;
    }

    
    @Column(name="OUTPUTNAME", length=256)
    public String getOutputname() {
        return this.outputname;
    }
    
    public void setOutputname(String outputname) {
        this.outputname = outputname;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }




}


