package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Clob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Msttemplatemap generated by hbm2java
 */
@Entity
@Table(name="MSTTEMPLATEMAP"
    ,schema="FCDBADMIN_RK"
)
public class Msttemplatemap  implements java.io.Serializable {


     private MsttemplatemapId id;
     private Clob fieldmapping;

    public Msttemplatemap() {
    }

	
    public Msttemplatemap(MsttemplatemapId id) {
        this.id = id;
    }
    public Msttemplatemap(MsttemplatemapId id, Clob fieldmapping) {
       this.id = id;
       this.fieldmapping = fieldmapping;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="typetemplate", column=@Column(name="TYPETEMPLATE", nullable=false, length=2) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MsttemplatemapId getId() {
        return this.id;
    }
    
    public void setId(MsttemplatemapId id) {
        this.id = id;
    }

    
    @Column(name="FIELDMAPPING")
    public Clob getFieldmapping() {
        return this.fieldmapping;
    }
    
    public void setFieldmapping(Clob fieldmapping) {
        this.fieldmapping = fieldmapping;
    }




}


