package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Msttradelookup generated by hbm2java
 */
@Entity
@Table(name="MSTTRADELOOKUP"
    ,schema="FCDBADMIN_RK"
)
public class Msttradelookup  implements java.io.Serializable {


     private String maintenanceId;
     private String maintenanceDesc;
     private String idtxn;
     private String maintenanceType;
     private Character visibility;
     private String visibilityLevel;
     private Blob message;
     private BigDecimal makerid;
     private Date datlastmodified;

    public Msttradelookup() {
    }

	
    public Msttradelookup(String maintenanceId) {
        this.maintenanceId = maintenanceId;
    }
    public Msttradelookup(String maintenanceId, String maintenanceDesc, String idtxn, String maintenanceType, Character visibility, String visibilityLevel, Blob message, BigDecimal makerid, Date datlastmodified) {
       this.maintenanceId = maintenanceId;
       this.maintenanceDesc = maintenanceDesc;
       this.idtxn = idtxn;
       this.maintenanceType = maintenanceType;
       this.visibility = visibility;
       this.visibilityLevel = visibilityLevel;
       this.message = message;
       this.makerid = makerid;
       this.datlastmodified = datlastmodified;
    }
   
     @Id 

    
    @Column(name="MAINTENANCE_ID", unique=true, nullable=false, length=20)
    public String getMaintenanceId() {
        return this.maintenanceId;
    }
    
    public void setMaintenanceId(String maintenanceId) {
        this.maintenanceId = maintenanceId;
    }

    
    @Column(name="MAINTENANCE_DESC", length=100)
    public String getMaintenanceDesc() {
        return this.maintenanceDesc;
    }
    
    public void setMaintenanceDesc(String maintenanceDesc) {
        this.maintenanceDesc = maintenanceDesc;
    }

    
    @Column(name="IDTXN", length=100)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="MAINTENANCE_TYPE", length=5)
    public String getMaintenanceType() {
        return this.maintenanceType;
    }
    
    public void setMaintenanceType(String maintenanceType) {
        this.maintenanceType = maintenanceType;
    }

    
    @Column(name="VISIBILITY", length=1)
    public Character getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(Character visibility) {
        this.visibility = visibility;
    }

    
    @Column(name="VISIBILITY_LEVEL", length=20)
    public String getVisibilityLevel() {
        return this.visibilityLevel;
    }
    
    public void setVisibilityLevel(String visibilityLevel) {
        this.visibilityLevel = visibilityLevel;
    }

    
    @Column(name="MESSAGE")
    public Blob getMessage() {
        return this.message;
    }
    
    public void setMessage(Blob message) {
        this.message = message;
    }

    
    @Column(name="MAKERID", precision=22, scale=0)
    public BigDecimal getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(BigDecimal makerid) {
        this.makerid = makerid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTMODIFIED", length=7)
    public Date getDatlastmodified() {
        return this.datlastmodified;
    }
    
    public void setDatlastmodified(Date datlastmodified) {
        this.datlastmodified = datlastmodified;
    }




}


