package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mstudfdata generated by hbm2java
 */
@Entity
@Table(name="MSTUDFDATA"
    ,schema="FCDBADMIN_RK"
)
public class Mstudfdata  implements java.io.Serializable {


     private String idudf;
     private String idudftype;
     private String udfattributes;
     private String labeludf;
     private Character isenabled;

    public Mstudfdata() {
    }

	
    public Mstudfdata(String idudf) {
        this.idudf = idudf;
    }
    public Mstudfdata(String idudf, String idudftype, String udfattributes, String labeludf, Character isenabled) {
       this.idudf = idudf;
       this.idudftype = idudftype;
       this.udfattributes = udfattributes;
       this.labeludf = labeludf;
       this.isenabled = isenabled;
    }
   
     @Id 

    
    @Column(name="IDUDF", unique=true, nullable=false, length=40)
    public String getIdudf() {
        return this.idudf;
    }
    
    public void setIdudf(String idudf) {
        this.idudf = idudf;
    }

    
    @Column(name="IDUDFTYPE", length=10)
    public String getIdudftype() {
        return this.idudftype;
    }
    
    public void setIdudftype(String idudftype) {
        this.idudftype = idudftype;
    }

    
    @Column(name="UDFATTRIBUTES", length=1000)
    public String getUdfattributes() {
        return this.udfattributes;
    }
    
    public void setUdfattributes(String udfattributes) {
        this.udfattributes = udfattributes;
    }

    
    @Column(name="LABELUDF", length=40)
    public String getLabeludf() {
        return this.labeludf;
    }
    
    public void setLabeludf(String labeludf) {
        this.labeludf = labeludf;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }




}


