package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mstusergrouptype generated by hbm2java
 */
@Entity
@Table(name="MSTUSERGROUPTYPE"
    ,schema="FCDBADMIN_RK"
)
public class Mstusergrouptype  implements java.io.Serializable {


     private char usergrouptype;
     private String description;

    public Mstusergrouptype() {
    }

	
    public Mstusergrouptype(char usergrouptype) {
        this.usergrouptype = usergrouptype;
    }
    public Mstusergrouptype(char usergrouptype, String description) {
       this.usergrouptype = usergrouptype;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="USERGROUPTYPE", unique=true, nullable=false, length=1)
    public char getUsergrouptype() {
        return this.usergrouptype;
    }
    
    public void setUsergrouptype(char usergrouptype) {
        this.usergrouptype = usergrouptype;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


