package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Mstusertypetxn generated by hbm2java
 */
@Entity
@Table(name="MSTUSERTYPETXN"
    ,schema="FCDBADMIN_RK"
)
public class Mstusertypetxn  implements java.io.Serializable {


     private MstusertypetxnId id;
     private Mstusertypes mstusertypes;
     private String initauthid;
     private String typecust;
     private String limitsallowed;
     private String txngroup;
     private BigDecimal idseq;
     private Character flagservicerequest;
     private String gifname;
     private Character ismenutxn;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private String enabletxnblackout;
     private String initrequestid;
     private String codtxn;
     private String idmodule;
     private Character authalertrequired;
     private String refUsertype;
     private String alertparam;
     private Character isenabled;
     private Character cutoffallowed;
     private String allowedPrivileges;
     private String isexternal;
     private Character quicktask;
     private Character istool;
     private String useragentreqid;
     private Character isdefaultnav;
     private Character tooltype;
     private Character is24x7;
     private Mobileenablertxnlist mobileenablertxnlist;

    public Mstusertypetxn() {
    }

	
    public Mstusertypetxn(MstusertypetxnId id, Mstusertypes mstusertypes) {
        this.id = id;
        this.mstusertypes = mstusertypes;
    }
    public Mstusertypetxn(MstusertypetxnId id, Mstusertypes mstusertypes, String initauthid, String typecust, String limitsallowed, String txngroup, BigDecimal idseq, Character flagservicerequest, String gifname, Character ismenutxn, String token1, String token2, String token3, String token4, String token5, String enabletxnblackout, String initrequestid, String codtxn, String idmodule, Character authalertrequired, String refUsertype, String alertparam, Character isenabled, Character cutoffallowed, String allowedPrivileges, String isexternal, Character quicktask, Character istool, String useragentreqid, Character isdefaultnav, Character tooltype, Character is24x7, Mobileenablertxnlist mobileenablertxnlist) {
       this.id = id;
       this.mstusertypes = mstusertypes;
       this.initauthid = initauthid;
       this.typecust = typecust;
       this.limitsallowed = limitsallowed;
       this.txngroup = txngroup;
       this.idseq = idseq;
       this.flagservicerequest = flagservicerequest;
       this.gifname = gifname;
       this.ismenutxn = ismenutxn;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.enabletxnblackout = enabletxnblackout;
       this.initrequestid = initrequestid;
       this.codtxn = codtxn;
       this.idmodule = idmodule;
       this.authalertrequired = authalertrequired;
       this.refUsertype = refUsertype;
       this.alertparam = alertparam;
       this.isenabled = isenabled;
       this.cutoffallowed = cutoffallowed;
       this.allowedPrivileges = allowedPrivileges;
       this.isexternal = isexternal;
       this.quicktask = quicktask;
       this.istool = istool;
       this.useragentreqid = useragentreqid;
       this.isdefaultnav = isdefaultnav;
       this.tooltype = tooltype;
       this.is24x7 = is24x7;
       this.mobileenablertxnlist = mobileenablertxnlist;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=3) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MstusertypetxnId getId() {
        return this.id;
    }
    
    public void setId(MstusertypetxnId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERTYPE", nullable=false, insertable=false, updatable=false)
    public Mstusertypes getMstusertypes() {
        return this.mstusertypes;
    }
    
    public void setMstusertypes(Mstusertypes mstusertypes) {
        this.mstusertypes = mstusertypes;
    }

    
    @Column(name="INITAUTHID", length=30)
    public String getInitauthid() {
        return this.initauthid;
    }
    
    public void setInitauthid(String initauthid) {
        this.initauthid = initauthid;
    }

    
    @Column(name="TYPECUST", length=20)
    public String getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(String typecust) {
        this.typecust = typecust;
    }

    
    @Column(name="LIMITSALLOWED", length=1)
    public String getLimitsallowed() {
        return this.limitsallowed;
    }
    
    public void setLimitsallowed(String limitsallowed) {
        this.limitsallowed = limitsallowed;
    }

    
    @Column(name="TXNGROUP", length=10)
    public String getTxngroup() {
        return this.txngroup;
    }
    
    public void setTxngroup(String txngroup) {
        this.txngroup = txngroup;
    }

    
    @Column(name="IDSEQ", precision=22, scale=0)
    public BigDecimal getIdseq() {
        return this.idseq;
    }
    
    public void setIdseq(BigDecimal idseq) {
        this.idseq = idseq;
    }

    
    @Column(name="FLAGSERVICEREQUEST", length=1)
    public Character getFlagservicerequest() {
        return this.flagservicerequest;
    }
    
    public void setFlagservicerequest(Character flagservicerequest) {
        this.flagservicerequest = flagservicerequest;
    }

    
    @Column(name="GIFNAME")
    public String getGifname() {
        return this.gifname;
    }
    
    public void setGifname(String gifname) {
        this.gifname = gifname;
    }

    
    @Column(name="ISMENUTXN", length=1)
    public Character getIsmenutxn() {
        return this.ismenutxn;
    }
    
    public void setIsmenutxn(Character ismenutxn) {
        this.ismenutxn = ismenutxn;
    }

    
    @Column(name="TOKEN1", length=30)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=30)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=30)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4", length=30)
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5", length=30)
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="ENABLETXNBLACKOUT", length=1)
    public String getEnabletxnblackout() {
        return this.enabletxnblackout;
    }
    
    public void setEnabletxnblackout(String enabletxnblackout) {
        this.enabletxnblackout = enabletxnblackout;
    }

    
    @Column(name="INITREQUESTID", length=7)
    public String getInitrequestid() {
        return this.initrequestid;
    }
    
    public void setInitrequestid(String initrequestid) {
        this.initrequestid = initrequestid;
    }

    
    @Column(name="CODTXN", length=3)
    public String getCodtxn() {
        return this.codtxn;
    }
    
    public void setCodtxn(String codtxn) {
        this.codtxn = codtxn;
    }

    
    @Column(name="IDMODULE", length=10)
    public String getIdmodule() {
        return this.idmodule;
    }
    
    public void setIdmodule(String idmodule) {
        this.idmodule = idmodule;
    }

    
    @Column(name="AUTHALERTREQUIRED", length=1)
    public Character getAuthalertrequired() {
        return this.authalertrequired;
    }
    
    public void setAuthalertrequired(Character authalertrequired) {
        this.authalertrequired = authalertrequired;
    }

    
    @Column(name="REF_USERTYPE", length=225)
    public String getRefUsertype() {
        return this.refUsertype;
    }
    
    public void setRefUsertype(String refUsertype) {
        this.refUsertype = refUsertype;
    }

    
    @Column(name="ALERTPARAM", length=4000)
    public String getAlertparam() {
        return this.alertparam;
    }
    
    public void setAlertparam(String alertparam) {
        this.alertparam = alertparam;
    }

    
    @Column(name="ISENABLED", length=1)
    public Character getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(Character isenabled) {
        this.isenabled = isenabled;
    }

    
    @Column(name="CUTOFFALLOWED", length=1)
    public Character getCutoffallowed() {
        return this.cutoffallowed;
    }
    
    public void setCutoffallowed(Character cutoffallowed) {
        this.cutoffallowed = cutoffallowed;
    }

    
    @Column(name="ALLOWED_PRIVILEGES", length=20)
    public String getAllowedPrivileges() {
        return this.allowedPrivileges;
    }
    
    public void setAllowedPrivileges(String allowedPrivileges) {
        this.allowedPrivileges = allowedPrivileges;
    }

    
    @Column(name="ISEXTERNAL", length=1)
    public String getIsexternal() {
        return this.isexternal;
    }
    
    public void setIsexternal(String isexternal) {
        this.isexternal = isexternal;
    }

    
    @Column(name="QUICKTASK", length=1)
    public Character getQuicktask() {
        return this.quicktask;
    }
    
    public void setQuicktask(Character quicktask) {
        this.quicktask = quicktask;
    }

    
    @Column(name="ISTOOL", length=1)
    public Character getIstool() {
        return this.istool;
    }
    
    public void setIstool(Character istool) {
        this.istool = istool;
    }

    
    @Column(name="USERAGENTREQID", length=200)
    public String getUseragentreqid() {
        return this.useragentreqid;
    }
    
    public void setUseragentreqid(String useragentreqid) {
        this.useragentreqid = useragentreqid;
    }

    
    @Column(name="ISDEFAULTNAV", length=1)
    public Character getIsdefaultnav() {
        return this.isdefaultnav;
    }
    
    public void setIsdefaultnav(Character isdefaultnav) {
        this.isdefaultnav = isdefaultnav;
    }

    
    @Column(name="TOOLTYPE", length=1)
    public Character getTooltype() {
        return this.tooltype;
    }
    
    public void setTooltype(Character tooltype) {
        this.tooltype = tooltype;
    }

    
    @Column(name="IS24X7", length=1)
    public Character getIs24x7() {
        return this.is24x7;
    }
    
    public void setIs24x7(Character is24x7) {
        this.is24x7 = is24x7;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="mstusertypetxn")
    public Mobileenablertxnlist getMobileenablertxnlist() {
        return this.mobileenablertxnlist;
    }
    
    public void setMobileenablertxnlist(Mobileenablertxnlist mobileenablertxnlist) {
        this.mobileenablertxnlist = mobileenablertxnlist;
    }




}


