package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstuseragenttxn generated by hbm2java
 */
@Entity
@Table(name="MSTUSERAGENTTXN"
    ,schema="FCDBADMIN_RK"
)
public class Mstuseragenttxn  implements java.io.Serializable {


     private MstuseragenttxnId id;
     private String token1;
     private String token2;
     private String token3;
     private String token4;
     private String token5;
     private String txngroup;
     private String initrequestid;

    public Mstuseragenttxn() {
    }

	
    public Mstuseragenttxn(MstuseragenttxnId id) {
        this.id = id;
    }
    public Mstuseragenttxn(MstuseragenttxnId id, String token1, String token2, String token3, String token4, String token5, String txngroup, String initrequestid) {
       this.id = id;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.token4 = token4;
       this.token5 = token5;
       this.txngroup = txngroup;
       this.initrequestid = initrequestid;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="iduseragent", column=@Column(name="IDUSERAGENT", nullable=false, length=10) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ) } )
    public MstuseragenttxnId getId() {
        return this.id;
    }
    
    public void setId(MstuseragenttxnId id) {
        this.id = id;
    }

    
    @Column(name="TOKEN1", length=30)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=30)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=30)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="TOKEN4", length=30)
    public String getToken4() {
        return this.token4;
    }
    
    public void setToken4(String token4) {
        this.token4 = token4;
    }

    
    @Column(name="TOKEN5", length=30)
    public String getToken5() {
        return this.token5;
    }
    
    public void setToken5(String token5) {
        this.token5 = token5;
    }

    
    @Column(name="TXNGROUP", length=10)
    public String getTxngroup() {
        return this.txngroup;
    }
    
    public void setTxngroup(String txngroup) {
        this.txngroup = txngroup;
    }

    
    @Column(name="INITREQUESTID", length=8)
    public String getInitrequestid() {
        return this.initrequestid;
    }
    
    public void setInitrequestid(String initrequestid) {
        this.initrequestid = initrequestid;
    }




}


