package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstuserbudgetplan generated by hbm2java
 */
@Entity
@Table(name="MSTUSERBUDGETPLAN"
    ,schema="FCDBADMIN_RK"
)
public class Mstuserbudgetplan  implements java.io.Serializable {


     private MstuserbudgetplanId id;
     private String idEntity;
     private String idcustomer;
     private Date startdate;
     private Date enddate;
     private Character budgetcycle;
     private Character rolloverflag;
     private String currency;
     private Date creationDate;

    public Mstuserbudgetplan() {
    }

	
    public Mstuserbudgetplan(MstuserbudgetplanId id) {
        this.id = id;
    }
    public Mstuserbudgetplan(MstuserbudgetplanId id, String idEntity, String idcustomer, Date startdate, Date enddate, Character budgetcycle, Character rolloverflag, String currency, Date creationDate) {
       this.id = id;
       this.idEntity = idEntity;
       this.idcustomer = idcustomer;
       this.startdate = startdate;
       this.enddate = enddate;
       this.budgetcycle = budgetcycle;
       this.rolloverflag = rolloverflag;
       this.currency = currency;
       this.creationDate = creationDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idfcatref", column=@Column(name="IDFCATREF", nullable=false, length=15) ) } )
    public MstuserbudgetplanId getId() {
        return this.id;
    }
    
    public void setId(MstuserbudgetplanId id) {
        this.id = id;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDCUSTOMER", length=30)
    public String getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(String idcustomer) {
        this.idcustomer = idcustomer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="STARTDATE", length=7)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENDDATE", length=7)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    
    @Column(name="BUDGETCYCLE", length=1)
    public Character getBudgetcycle() {
        return this.budgetcycle;
    }
    
    public void setBudgetcycle(Character budgetcycle) {
        this.budgetcycle = budgetcycle;
    }

    
    @Column(name="ROLLOVERFLAG", length=1)
    public Character getRolloverflag() {
        return this.rolloverflag;
    }
    
    public void setRolloverflag(Character rolloverflag) {
        this.rolloverflag = rolloverflag;
    }

    
    @Column(name="CURRENCY", length=3)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATION_DATE", length=7)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }




}


