package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mstuser generated by hbm2java
 */
@Entity
@Table(name="MSTUSER"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames="USERSEQNBR") 
)
public class Mstuser  implements java.io.Serializable {


     private String iduser;
     private String idEntity;
     private String typeuser;
     private String nicname;
     private String salution;
     private String firstname;
     private String lastname;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String country;
     private String zip;
     private Date dob;
     private String email;
     private Character activeflag;
     private String phonenumber;
     private String faxnbr;
     private String perscss;
     private Short statebit;
     private String usercert;
     private Character certtokentype;
     private Character txnlimitflag;
     private Character accountmapflag;
     private BigDecimal userseqnbr;
     private String usertoken;
     private String securetokenid;
     private Character authreqd;
     private Date datcreated;
     private String makerid;
     private String deletecomments;
     private String idhardtoken;
     private String productname;
     private String productversion;
     private Character usergroupbasetype;
     private Character usergrouptype;
     private String serialno;
     private String idsegment;
     private String userkey;
     private String refUsertype;
     private Blob preferences;
     private Blob userdata;
     private String packageId;
     private Boolean kycstatus;
     private String operativeacctno;
     private String operativebrncode;
     private Byte nbrtncdecline;
     private Character tncstatus;
     private Serializable lasttncactiondatetime;
     private Character hascustalertsubscribed;
     private String secquescred;
     private String middlename;
     private Character gender;
     private String mothermaidenname;
     private String interests;
     private String preferredcontactmode;
     private String preferredcontactwindow;
     private Character custprofilealertsubscribed;
     private String actreason;
     private String s2sflag;
     private Set<Mailmessage> mailmessagesForRespondedby = new HashSet<Mailmessage>(0);
     private Set<Btusermap> btusermaps = new HashSet<Btusermap>(0);
     private Set<Txnfundstransfer> txnfundstransfersForIdauthorizer1 = new HashSet<Txnfundstransfer>(0);
     private Set<Txnexternalacct> txnexternalacctsForIdauthorizer = new HashSet<Txnexternalacct>(0);
     private Set<Mailmessage> mailmessagesForRecieveruserid = new HashSet<Mailmessage>(0);
     private Set<Mailmessage> mailmessagesForSenderid = new HashSet<Mailmessage>(0);
     private Set<Txnfundstransfer> txnfundstransfersForIdinitiator = new HashSet<Txnfundstransfer>(0);
     private Set<Usergoal> usergoals = new HashSet<Usergoal>(0);
     private Set<Usercontact> usercontacts = new HashSet<Usercontact>(0);
     private Set<Peerbeneacctdet> peerbeneacctdets = new HashSet<Peerbeneacctdet>(0);
     private Set<Usercustacctrel> usercustacctrels = new HashSet<Usercustacctrel>(0);
     private Set<Userreportmap> userreportmaps = new HashSet<Userreportmap>(0);
     private Set<Txnexternalacct> txnexternalacctsForIdinitiator = new HashSet<Txnexternalacct>(0);

    public Mstuser() {
    }

	
    public Mstuser(String iduser) {
        this.iduser = iduser;
    }
    public Mstuser(String iduser, String idEntity, String typeuser, String nicname, String salution, String firstname, String lastname, String address1, String address2, String city, String state, String country, String zip, Date dob, String email, Character activeflag, String phonenumber, String faxnbr, String perscss, Short statebit, String usercert, Character certtokentype, Character txnlimitflag, Character accountmapflag, BigDecimal userseqnbr, String usertoken, String securetokenid, Character authreqd, Date datcreated, String makerid, String deletecomments, String idhardtoken, String productname, String productversion, Character usergroupbasetype, Character usergrouptype, String serialno, String idsegment, String userkey, String refUsertype, Blob preferences, Blob userdata, String packageId, Boolean kycstatus, String operativeacctno, String operativebrncode, Byte nbrtncdecline, Character tncstatus, Serializable lasttncactiondatetime, Character hascustalertsubscribed, String secquescred, String middlename, Character gender, String mothermaidenname, String interests, String preferredcontactmode, String preferredcontactwindow, Character custprofilealertsubscribed, String actreason, String s2sflag, Set<Mailmessage> mailmessagesForRespondedby, Set<Btusermap> btusermaps, Set<Txnfundstransfer> txnfundstransfersForIdauthorizer1, Set<Txnexternalacct> txnexternalacctsForIdauthorizer, Set<Mailmessage> mailmessagesForRecieveruserid, Set<Mailmessage> mailmessagesForSenderid, Set<Txnfundstransfer> txnfundstransfersForIdinitiator, Set<Usergoal> usergoals, Set<Usercontact> usercontacts, Set<Peerbeneacctdet> peerbeneacctdets, Set<Usercustacctrel> usercustacctrels, Set<Userreportmap> userreportmaps, Set<Txnexternalacct> txnexternalacctsForIdinitiator) {
       this.iduser = iduser;
       this.idEntity = idEntity;
       this.typeuser = typeuser;
       this.nicname = nicname;
       this.salution = salution;
       this.firstname = firstname;
       this.lastname = lastname;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.state = state;
       this.country = country;
       this.zip = zip;
       this.dob = dob;
       this.email = email;
       this.activeflag = activeflag;
       this.phonenumber = phonenumber;
       this.faxnbr = faxnbr;
       this.perscss = perscss;
       this.statebit = statebit;
       this.usercert = usercert;
       this.certtokentype = certtokentype;
       this.txnlimitflag = txnlimitflag;
       this.accountmapflag = accountmapflag;
       this.userseqnbr = userseqnbr;
       this.usertoken = usertoken;
       this.securetokenid = securetokenid;
       this.authreqd = authreqd;
       this.datcreated = datcreated;
       this.makerid = makerid;
       this.deletecomments = deletecomments;
       this.idhardtoken = idhardtoken;
       this.productname = productname;
       this.productversion = productversion;
       this.usergroupbasetype = usergroupbasetype;
       this.usergrouptype = usergrouptype;
       this.serialno = serialno;
       this.idsegment = idsegment;
       this.userkey = userkey;
       this.refUsertype = refUsertype;
       this.preferences = preferences;
       this.userdata = userdata;
       this.packageId = packageId;
       this.kycstatus = kycstatus;
       this.operativeacctno = operativeacctno;
       this.operativebrncode = operativebrncode;
       this.nbrtncdecline = nbrtncdecline;
       this.tncstatus = tncstatus;
       this.lasttncactiondatetime = lasttncactiondatetime;
       this.hascustalertsubscribed = hascustalertsubscribed;
       this.secquescred = secquescred;
       this.middlename = middlename;
       this.gender = gender;
       this.mothermaidenname = mothermaidenname;
       this.interests = interests;
       this.preferredcontactmode = preferredcontactmode;
       this.preferredcontactwindow = preferredcontactwindow;
       this.custprofilealertsubscribed = custprofilealertsubscribed;
       this.actreason = actreason;
       this.s2sflag = s2sflag;
       this.mailmessagesForRespondedby = mailmessagesForRespondedby;
       this.btusermaps = btusermaps;
       this.txnfundstransfersForIdauthorizer1 = txnfundstransfersForIdauthorizer1;
       this.txnexternalacctsForIdauthorizer = txnexternalacctsForIdauthorizer;
       this.mailmessagesForRecieveruserid = mailmessagesForRecieveruserid;
       this.mailmessagesForSenderid = mailmessagesForSenderid;
       this.txnfundstransfersForIdinitiator = txnfundstransfersForIdinitiator;
       this.usergoals = usergoals;
       this.usercontacts = usercontacts;
       this.peerbeneacctdets = peerbeneacctdets;
       this.usercustacctrels = usercustacctrels;
       this.userreportmaps = userreportmaps;
       this.txnexternalacctsForIdinitiator = txnexternalacctsForIdinitiator;
    }
   
     @Id 

    
    @Column(name="IDUSER", unique=true, nullable=false, length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="TYPEUSER", length=3)
    public String getTypeuser() {
        return this.typeuser;
    }
    
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }

    
    @Column(name="NICNAME", length=40)
    public String getNicname() {
        return this.nicname;
    }
    
    public void setNicname(String nicname) {
        this.nicname = nicname;
    }

    
    @Column(name="SALUTION", length=20)
    public String getSalution() {
        return this.salution;
    }
    
    public void setSalution(String salution) {
        this.salution = salution;
    }

    
    @Column(name="FIRSTNAME", length=50)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME", length=50)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="ADDRESS1", length=60)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="ADDRESS2", length=60)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="CITY", length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE", length=60)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="COUNTRY", length=60)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="ZIP", length=30)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DOB", length=7)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ACTIVEFLAG", length=1)
    public Character getActiveflag() {
        return this.activeflag;
    }
    
    public void setActiveflag(Character activeflag) {
        this.activeflag = activeflag;
    }

    
    @Column(name="PHONENUMBER", length=20)
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    
    @Column(name="FAXNBR", length=20)
    public String getFaxnbr() {
        return this.faxnbr;
    }
    
    public void setFaxnbr(String faxnbr) {
        this.faxnbr = faxnbr;
    }

    
    @Column(name="PERSCSS", length=50)
    public String getPerscss() {
        return this.perscss;
    }
    
    public void setPerscss(String perscss) {
        this.perscss = perscss;
    }

    
    @Column(name="STATEBIT", precision=3, scale=0)
    public Short getStatebit() {
        return this.statebit;
    }
    
    public void setStatebit(Short statebit) {
        this.statebit = statebit;
    }

    
    @Column(name="USERCERT", length=4000)
    public String getUsercert() {
        return this.usercert;
    }
    
    public void setUsercert(String usercert) {
        this.usercert = usercert;
    }

    
    @Column(name="CERTTOKENTYPE", length=1)
    public Character getCerttokentype() {
        return this.certtokentype;
    }
    
    public void setCerttokentype(Character certtokentype) {
        this.certtokentype = certtokentype;
    }

    
    @Column(name="TXNLIMITFLAG", length=1)
    public Character getTxnlimitflag() {
        return this.txnlimitflag;
    }
    
    public void setTxnlimitflag(Character txnlimitflag) {
        this.txnlimitflag = txnlimitflag;
    }

    
    @Column(name="ACCOUNTMAPFLAG", length=1)
    public Character getAccountmapflag() {
        return this.accountmapflag;
    }
    
    public void setAccountmapflag(Character accountmapflag) {
        this.accountmapflag = accountmapflag;
    }

    
    @Column(name="USERSEQNBR", unique=true, precision=22, scale=0)
    public BigDecimal getUserseqnbr() {
        return this.userseqnbr;
    }
    
    public void setUserseqnbr(BigDecimal userseqnbr) {
        this.userseqnbr = userseqnbr;
    }

    
    @Column(name="USERTOKEN", length=100)
    public String getUsertoken() {
        return this.usertoken;
    }
    
    public void setUsertoken(String usertoken) {
        this.usertoken = usertoken;
    }

    
    @Column(name="SECURETOKENID", length=2000)
    public String getSecuretokenid() {
        return this.securetokenid;
    }
    
    public void setSecuretokenid(String securetokenid) {
        this.securetokenid = securetokenid;
    }

    
    @Column(name="AUTHREQD", length=1)
    public Character getAuthreqd() {
        return this.authreqd;
    }
    
    public void setAuthreqd(Character authreqd) {
        this.authreqd = authreqd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    
    @Column(name="MAKERID", length=20)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    
    @Column(name="DELETECOMMENTS")
    public String getDeletecomments() {
        return this.deletecomments;
    }
    
    public void setDeletecomments(String deletecomments) {
        this.deletecomments = deletecomments;
    }

    
    @Column(name="IDHARDTOKEN", length=10)
    public String getIdhardtoken() {
        return this.idhardtoken;
    }
    
    public void setIdhardtoken(String idhardtoken) {
        this.idhardtoken = idhardtoken;
    }

    
    @Column(name="PRODUCTNAME", length=50)
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    
    @Column(name="PRODUCTVERSION", length=10)
    public String getProductversion() {
        return this.productversion;
    }
    
    public void setProductversion(String productversion) {
        this.productversion = productversion;
    }

    
    @Column(name="USERGROUPBASETYPE", length=1)
    public Character getUsergroupbasetype() {
        return this.usergroupbasetype;
    }
    
    public void setUsergroupbasetype(Character usergroupbasetype) {
        this.usergroupbasetype = usergroupbasetype;
    }

    
    @Column(name="USERGROUPTYPE", length=1)
    public Character getUsergrouptype() {
        return this.usergrouptype;
    }
    
    public void setUsergrouptype(Character usergrouptype) {
        this.usergrouptype = usergrouptype;
    }

    
    @Column(name="SERIALNO", length=22)
    public String getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(String serialno) {
        this.serialno = serialno;
    }

    
    @Column(name="IDSEGMENT", length=30)
    public String getIdsegment() {
        return this.idsegment;
    }
    
    public void setIdsegment(String idsegment) {
        this.idsegment = idsegment;
    }

    
    @Column(name="USERKEY", length=18)
    public String getUserkey() {
        return this.userkey;
    }
    
    public void setUserkey(String userkey) {
        this.userkey = userkey;
    }

    
    @Column(name="REF_USERTYPE")
    public String getRefUsertype() {
        return this.refUsertype;
    }
    
    public void setRefUsertype(String refUsertype) {
        this.refUsertype = refUsertype;
    }

    
    @Column(name="PREFERENCES")
    public Blob getPreferences() {
        return this.preferences;
    }
    
    public void setPreferences(Blob preferences) {
        this.preferences = preferences;
    }

    
    @Column(name="USERDATA")
    public Blob getUserdata() {
        return this.userdata;
    }
    
    public void setUserdata(Blob userdata) {
        this.userdata = userdata;
    }

    
    @Column(name="PACKAGE_ID", length=50)
    public String getPackageId() {
        return this.packageId;
    }
    
    public void setPackageId(String packageId) {
        this.packageId = packageId;
    }

    
    @Column(name="KYCSTATUS", precision=1, scale=0)
    public Boolean getKycstatus() {
        return this.kycstatus;
    }
    
    public void setKycstatus(Boolean kycstatus) {
        this.kycstatus = kycstatus;
    }

    
    @Column(name="OPERATIVEACCTNO", length=30)
    public String getOperativeacctno() {
        return this.operativeacctno;
    }
    
    public void setOperativeacctno(String operativeacctno) {
        this.operativeacctno = operativeacctno;
    }

    
    @Column(name="OPERATIVEBRNCODE", length=5)
    public String getOperativebrncode() {
        return this.operativebrncode;
    }
    
    public void setOperativebrncode(String operativebrncode) {
        this.operativebrncode = operativebrncode;
    }

    
    @Column(name="NBRTNCDECLINE", precision=2, scale=0)
    public Byte getNbrtncdecline() {
        return this.nbrtncdecline;
    }
    
    public void setNbrtncdecline(Byte nbrtncdecline) {
        this.nbrtncdecline = nbrtncdecline;
    }

    
    @Column(name="TNCSTATUS", length=1)
    public Character getTncstatus() {
        return this.tncstatus;
    }
    
    public void setTncstatus(Character tncstatus) {
        this.tncstatus = tncstatus;
    }

    
    @Column(name="LASTTNCACTIONDATETIME")
    public Serializable getLasttncactiondatetime() {
        return this.lasttncactiondatetime;
    }
    
    public void setLasttncactiondatetime(Serializable lasttncactiondatetime) {
        this.lasttncactiondatetime = lasttncactiondatetime;
    }

    
    @Column(name="HASCUSTALERTSUBSCRIBED", length=1)
    public Character getHascustalertsubscribed() {
        return this.hascustalertsubscribed;
    }
    
    public void setHascustalertsubscribed(Character hascustalertsubscribed) {
        this.hascustalertsubscribed = hascustalertsubscribed;
    }

    
    @Column(name="SECQUESCRED", length=2000)
    public String getSecquescred() {
        return this.secquescred;
    }
    
    public void setSecquescred(String secquescred) {
        this.secquescred = secquescred;
    }

    
    @Column(name="MIDDLENAME", length=50)
    public String getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    
    @Column(name="GENDER", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="MOTHERMAIDENNAME", length=50)
    public String getMothermaidenname() {
        return this.mothermaidenname;
    }
    
    public void setMothermaidenname(String mothermaidenname) {
        this.mothermaidenname = mothermaidenname;
    }

    
    @Column(name="INTERESTS", length=200)
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }

    
    @Column(name="PREFERREDCONTACTMODE", length=10)
    public String getPreferredcontactmode() {
        return this.preferredcontactmode;
    }
    
    public void setPreferredcontactmode(String preferredcontactmode) {
        this.preferredcontactmode = preferredcontactmode;
    }

    
    @Column(name="PREFERREDCONTACTWINDOW", length=20)
    public String getPreferredcontactwindow() {
        return this.preferredcontactwindow;
    }
    
    public void setPreferredcontactwindow(String preferredcontactwindow) {
        this.preferredcontactwindow = preferredcontactwindow;
    }

    
    @Column(name="CUSTPROFILEALERTSUBSCRIBED", length=1)
    public Character getCustprofilealertsubscribed() {
        return this.custprofilealertsubscribed;
    }
    
    public void setCustprofilealertsubscribed(Character custprofilealertsubscribed) {
        this.custprofilealertsubscribed = custprofilealertsubscribed;
    }

    
    @Column(name="ACTREASON", length=200)
    public String getActreason() {
        return this.actreason;
    }
    
    public void setActreason(String actreason) {
        this.actreason = actreason;
    }

    
    @Column(name="S2SFLAG", length=1)
    public String getS2sflag() {
        return this.s2sflag;
    }
    
    public void setS2sflag(String s2sflag) {
        this.s2sflag = s2sflag;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserByRespondedby")
    public Set<Mailmessage> getMailmessagesForRespondedby() {
        return this.mailmessagesForRespondedby;
    }
    
    public void setMailmessagesForRespondedby(Set<Mailmessage> mailmessagesForRespondedby) {
        this.mailmessagesForRespondedby = mailmessagesForRespondedby;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuser")
    public Set<Btusermap> getBtusermaps() {
        return this.btusermaps;
    }
    
    public void setBtusermaps(Set<Btusermap> btusermaps) {
        this.btusermaps = btusermaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserByIdauthorizer1")
    public Set<Txnfundstransfer> getTxnfundstransfersForIdauthorizer1() {
        return this.txnfundstransfersForIdauthorizer1;
    }
    
    public void setTxnfundstransfersForIdauthorizer1(Set<Txnfundstransfer> txnfundstransfersForIdauthorizer1) {
        this.txnfundstransfersForIdauthorizer1 = txnfundstransfersForIdauthorizer1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserByIdauthorizer")
    public Set<Txnexternalacct> getTxnexternalacctsForIdauthorizer() {
        return this.txnexternalacctsForIdauthorizer;
    }
    
    public void setTxnexternalacctsForIdauthorizer(Set<Txnexternalacct> txnexternalacctsForIdauthorizer) {
        this.txnexternalacctsForIdauthorizer = txnexternalacctsForIdauthorizer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserByRecieveruserid")
    public Set<Mailmessage> getMailmessagesForRecieveruserid() {
        return this.mailmessagesForRecieveruserid;
    }
    
    public void setMailmessagesForRecieveruserid(Set<Mailmessage> mailmessagesForRecieveruserid) {
        this.mailmessagesForRecieveruserid = mailmessagesForRecieveruserid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserBySenderid")
    public Set<Mailmessage> getMailmessagesForSenderid() {
        return this.mailmessagesForSenderid;
    }
    
    public void setMailmessagesForSenderid(Set<Mailmessage> mailmessagesForSenderid) {
        this.mailmessagesForSenderid = mailmessagesForSenderid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserByIdinitiator")
    public Set<Txnfundstransfer> getTxnfundstransfersForIdinitiator() {
        return this.txnfundstransfersForIdinitiator;
    }
    
    public void setTxnfundstransfersForIdinitiator(Set<Txnfundstransfer> txnfundstransfersForIdinitiator) {
        this.txnfundstransfersForIdinitiator = txnfundstransfersForIdinitiator;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuser")
    public Set<Usergoal> getUsergoals() {
        return this.usergoals;
    }
    
    public void setUsergoals(Set<Usergoal> usergoals) {
        this.usergoals = usergoals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuser")
    public Set<Usercontact> getUsercontacts() {
        return this.usercontacts;
    }
    
    public void setUsercontacts(Set<Usercontact> usercontacts) {
        this.usercontacts = usercontacts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuser")
    public Set<Peerbeneacctdet> getPeerbeneacctdets() {
        return this.peerbeneacctdets;
    }
    
    public void setPeerbeneacctdets(Set<Peerbeneacctdet> peerbeneacctdets) {
        this.peerbeneacctdets = peerbeneacctdets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuser")
    public Set<Usercustacctrel> getUsercustacctrels() {
        return this.usercustacctrels;
    }
    
    public void setUsercustacctrels(Set<Usercustacctrel> usercustacctrels) {
        this.usercustacctrels = usercustacctrels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuser")
    public Set<Userreportmap> getUserreportmaps() {
        return this.userreportmaps;
    }
    
    public void setUserreportmaps(Set<Userreportmap> userreportmaps) {
        this.userreportmaps = userreportmaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mstuserByIdinitiator")
    public Set<Txnexternalacct> getTxnexternalacctsForIdinitiator() {
        return this.txnexternalacctsForIdinitiator;
    }
    
    public void setTxnexternalacctsForIdinitiator(Set<Txnexternalacct> txnexternalacctsForIdinitiator) {
        this.txnexternalacctsForIdinitiator = txnexternalacctsForIdinitiator;
    }




}


