package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mstusergrpbasetype generated by hbm2java
 */
@Entity
@Table(name="MSTUSERGRPBASETYPE"
    ,schema="FCDBADMIN_RK"
)
public class Mstusergrpbasetype  implements java.io.Serializable {


     private char usergroupbasetype;
     private String description;
     private Character flagpassword;
     private Character flagtxnpassword;
     private Integer sessiontimeout;

    public Mstusergrpbasetype() {
    }

	
    public Mstusergrpbasetype(char usergroupbasetype) {
        this.usergroupbasetype = usergroupbasetype;
    }
    public Mstusergrpbasetype(char usergroupbasetype, String description, Character flagpassword, Character flagtxnpassword, Integer sessiontimeout) {
       this.usergroupbasetype = usergroupbasetype;
       this.description = description;
       this.flagpassword = flagpassword;
       this.flagtxnpassword = flagtxnpassword;
       this.sessiontimeout = sessiontimeout;
    }
   
     @Id 

    
    @Column(name="USERGROUPBASETYPE", unique=true, nullable=false, length=1)
    public char getUsergroupbasetype() {
        return this.usergroupbasetype;
    }
    
    public void setUsergroupbasetype(char usergroupbasetype) {
        this.usergroupbasetype = usergroupbasetype;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="FLAGPASSWORD", length=1)
    public Character getFlagpassword() {
        return this.flagpassword;
    }
    
    public void setFlagpassword(Character flagpassword) {
        this.flagpassword = flagpassword;
    }

    
    @Column(name="FLAGTXNPASSWORD", length=1)
    public Character getFlagtxnpassword() {
        return this.flagtxnpassword;
    }
    
    public void setFlagtxnpassword(Character flagtxnpassword) {
        this.flagtxnpassword = flagtxnpassword;
    }

    
    @Column(name="SESSIONTIMEOUT", precision=5, scale=0)
    public Integer getSessiontimeout() {
        return this.sessiontimeout;
    }
    
    public void setSessiontimeout(Integer sessiontimeout) {
        this.sessiontimeout = sessiontimeout;
    }




}


