package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mstwidgetuserpref generated by hbm2java
 */
@Entity
@Table(name="MSTWIDGETUSERPREF"
    ,schema="FCDBADMIN_RK"
)
public class Mstwidgetuserpref  implements java.io.Serializable {


     private MstwidgetuserprefId id;
     private Character isselected;

    public Mstwidgetuserpref() {
    }

	
    public Mstwidgetuserpref(MstwidgetuserprefId id) {
        this.id = id;
    }
    public Mstwidgetuserpref(MstwidgetuserprefId id, Character isselected) {
       this.id = id;
       this.isselected = isselected;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="dashboardid", column=@Column(name="DASHBOARDID", nullable=false, length=1) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ) } )
    public MstwidgetuserprefId getId() {
        return this.id;
    }
    
    public void setId(MstwidgetuserprefId id) {
        this.id = id;
    }

    
    @Column(name="ISSELECTED", length=1)
    public Character getIsselected() {
        return this.isselected;
    }
    
    public void setIsselected(Character isselected) {
        this.isselected = isselected;
    }




}


