package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstwizardId generated by hbm2java
 */
@Embeddable
public class MstwizardId  implements java.io.Serializable {


     private String idwizard;
     private String idEntity;
     private String usertype;
     private String idchannel;
     private String idrequest;

    public MstwizardId() {
    }

    public MstwizardId(String idwizard, String idEntity, String usertype, String idchannel, String idrequest) {
       this.idwizard = idwizard;
       this.idEntity = idEntity;
       this.usertype = usertype;
       this.idchannel = idchannel;
       this.idrequest = idrequest;
    }
   


    @Column(name="IDWIZARD", nullable=false, length=20)
    public String getIdwizard() {
        return this.idwizard;
    }
    
    public void setIdwizard(String idwizard) {
        this.idwizard = idwizard;
    }


    @Column(name="ID_ENTITY", nullable=false, length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }


    @Column(name="USERTYPE", nullable=false, length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }


    @Column(name="IDCHANNEL", nullable=false, length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }


    @Column(name="IDREQUEST", nullable=false, length=8)
    public String getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(String idrequest) {
        this.idrequest = idrequest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstwizardId) ) return false;
		 MstwizardId castOther = ( MstwizardId ) other; 
         
		 return ( (this.getIdwizard()==castOther.getIdwizard()) || ( this.getIdwizard()!=null && castOther.getIdwizard()!=null && this.getIdwizard().equals(castOther.getIdwizard()) ) )
 && ( (this.getIdEntity()==castOther.getIdEntity()) || ( this.getIdEntity()!=null && castOther.getIdEntity()!=null && this.getIdEntity().equals(castOther.getIdEntity()) ) )
 && ( (this.getUsertype()==castOther.getUsertype()) || ( this.getUsertype()!=null && castOther.getUsertype()!=null && this.getUsertype().equals(castOther.getUsertype()) ) )
 && ( (this.getIdchannel()==castOther.getIdchannel()) || ( this.getIdchannel()!=null && castOther.getIdchannel()!=null && this.getIdchannel().equals(castOther.getIdchannel()) ) )
 && ( (this.getIdrequest()==castOther.getIdrequest()) || ( this.getIdrequest()!=null && castOther.getIdrequest()!=null && this.getIdrequest().equals(castOther.getIdrequest()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdwizard() == null ? 0 : this.getIdwizard().hashCode() );
         result = 37 * result + ( getIdEntity() == null ? 0 : this.getIdEntity().hashCode() );
         result = 37 * result + ( getUsertype() == null ? 0 : this.getUsertype().hashCode() );
         result = 37 * result + ( getIdchannel() == null ? 0 : this.getIdchannel().hashCode() );
         result = 37 * result + ( getIdrequest() == null ? 0 : this.getIdrequest().hashCode() );
         return result;
   }   


}


