package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrigStatusHandler generated by hbm2java
 */
@Entity
@Table(name="ORIG_STATUS_HANDLER"
    ,schema="FCDBADMIN_RK"
)
public class OrigStatusHandler  implements java.io.Serializable {


     private OrigStatusHandlerId id;
     private OrigStatus origStatus;
     private String service;
     private String processtype;

    public OrigStatusHandler() {
    }

	
    public OrigStatusHandler(OrigStatusHandlerId id, OrigStatus origStatus) {
        this.id = id;
        this.origStatus = origStatus;
    }
    public OrigStatusHandler(OrigStatusHandlerId id, OrigStatus origStatus, String service, String processtype) {
       this.id = id;
       this.origStatus = origStatus;
       this.service = service;
       this.processtype = processtype;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="prodcateg", column=@Column(name="PRODCATEG", nullable=false, length=10) ), 
        @AttributeOverride(name="prodcode", column=@Column(name="PRODCODE", nullable=false, length=10) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="handler", column=@Column(name="HANDLER", nullable=false) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="idworkflow", column=@Column(name="IDWORKFLOW", nullable=false, precision=22, scale=0) ) } )
    public OrigStatusHandlerId getId() {
        return this.id;
    }
    
    public void setId(OrigStatusHandlerId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false, insertable=false, updatable=false)
    public OrigStatus getOrigStatus() {
        return this.origStatus;
    }
    
    public void setOrigStatus(OrigStatus origStatus) {
        this.origStatus = origStatus;
    }

    
    @Column(name="SERVICE")
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }

    
    @Column(name="PROCESSTYPE", length=10)
    public String getProcesstype() {
        return this.processtype;
    }
    
    public void setProcesstype(String processtype) {
        this.processtype = processtype;
    }




}


