package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrigDocumentconfig generated by hbm2java
 */
@Entity
@Table(name="ORIG_DOCUMENTCONFIG"
    ,schema="FCDBADMIN_RK"
)
public class OrigDocumentconfig  implements java.io.Serializable {


     private OrigDocumentconfigId id;
     private Character ismandatory;

    public OrigDocumentconfig() {
    }

	
    public OrigDocumentconfig(OrigDocumentconfigId id) {
        this.id = id;
    }
    public OrigDocumentconfig(OrigDocumentconfigId id, Character ismandatory) {
       this.id = id;
       this.ismandatory = ismandatory;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="prodcateg", column=@Column(name="PRODCATEG", nullable=false, length=10) ), 
        @AttributeOverride(name="prodcode", column=@Column(name="PRODCODE", nullable=false, length=10) ), 
        @AttributeOverride(name="doccateg", column=@Column(name="DOCCATEG", nullable=false, length=20) ) } )
    public OrigDocumentconfigId getId() {
        return this.id;
    }
    
    public void setId(OrigDocumentconfigId id) {
        this.id = id;
    }

    
    @Column(name="ISMANDATORY", length=1)
    public Character getIsmandatory() {
        return this.ismandatory;
    }
    
    public void setIsmandatory(Character ismandatory) {
        this.ismandatory = ismandatory;
    }




}


