package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrigApplicationShare generated by hbm2java
 */
@Entity
@Table(name="ORIG_APPLICATION_SHARE"
    ,schema="FCDBADMIN_RK"
)
public class OrigApplicationShare  implements java.io.Serializable {


     private OrigApplicationShareId id;
     private OrigApplication origApplication;
     private String iduser;
     private Character typeAccess;
     private String status;
     private Date sharefrom;
     private Date shareto;
     private String securecode;
     private Blob diffblob;
     private String sharedby;

    public OrigApplicationShare() {
    }

	
    public OrigApplicationShare(OrigApplicationShareId id, OrigApplication origApplication) {
        this.id = id;
        this.origApplication = origApplication;
    }
    public OrigApplicationShare(OrigApplicationShareId id, OrigApplication origApplication, String iduser, Character typeAccess, String status, Date sharefrom, Date shareto, String securecode, Blob diffblob, String sharedby) {
       this.id = id;
       this.origApplication = origApplication;
       this.iduser = iduser;
       this.typeAccess = typeAccess;
       this.status = status;
       this.sharefrom = sharefrom;
       this.shareto = shareto;
       this.securecode = securecode;
       this.diffblob = diffblob;
       this.sharedby = sharedby;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idfcatref", column=@Column(name="IDFCATREF", nullable=false, length=35) ), 
        @AttributeOverride(name="typeCommChnl", column=@Column(name="TYPE_COMM_CHNL", nullable=false, length=2) ), 
        @AttributeOverride(name="idCommChnl", column=@Column(name="ID_COMM_CHNL", nullable=false) ) } )
    public OrigApplicationShareId getId() {
        return this.id;
    }
    
    public void setId(OrigApplicationShareId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFCATREF", nullable=false, insertable=false, updatable=false)
    public OrigApplication getOrigApplication() {
        return this.origApplication;
    }
    
    public void setOrigApplication(OrigApplication origApplication) {
        this.origApplication = origApplication;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="TYPE_ACCESS", length=1)
    public Character getTypeAccess() {
        return this.typeAccess;
    }
    
    public void setTypeAccess(Character typeAccess) {
        this.typeAccess = typeAccess;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SHAREFROM", length=7)
    public Date getSharefrom() {
        return this.sharefrom;
    }
    
    public void setSharefrom(Date sharefrom) {
        this.sharefrom = sharefrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SHARETO", length=7)
    public Date getShareto() {
        return this.shareto;
    }
    
    public void setShareto(Date shareto) {
        this.shareto = shareto;
    }

    
    @Column(name="SECURECODE")
    public String getSecurecode() {
        return this.securecode;
    }
    
    public void setSecurecode(String securecode) {
        this.securecode = securecode;
    }

    
    @Column(name="DIFFBLOB")
    public Blob getDiffblob() {
        return this.diffblob;
    }
    
    public void setDiffblob(Blob diffblob) {
        this.diffblob = diffblob;
    }

    
    @Column(name="SHAREDBY")
    public String getSharedby() {
        return this.sharedby;
    }
    
    public void setSharedby(String sharedby) {
        this.sharedby = sharedby;
    }




}


