package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrigProducts generated by hbm2java
 */
@Entity
@Table(name="ORIG_PRODUCTS"
    ,schema="FCDBADMIN_RK"
)
public class OrigProducts  implements java.io.Serializable {


     private OrigProductsId id;
     private OrigProdcateg origProdcateg;
     private BigDecimal jointholders;

    public OrigProducts() {
    }

	
    public OrigProducts(OrigProductsId id, OrigProdcateg origProdcateg) {
        this.id = id;
        this.origProdcateg = origProdcateg;
    }
    public OrigProducts(OrigProductsId id, OrigProdcateg origProdcateg, BigDecimal jointholders) {
       this.id = id;
       this.origProdcateg = origProdcateg;
       this.jointholders = jointholders;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="prodcategcode", column=@Column(name="PRODCATEGCODE", nullable=false, length=10) ), 
        @AttributeOverride(name="prodcode", column=@Column(name="PRODCODE", nullable=false, length=10) ) } )
    public OrigProductsId getId() {
        return this.id;
    }
    
    public void setId(OrigProductsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_ENTITY", referencedColumnName="ID_ENTITY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="USERTYPE", referencedColumnName="USERTYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PRODCATEGCODE", referencedColumnName="PRODCATEGCODE", nullable=false, insertable=false, updatable=false) } )
    public OrigProdcateg getOrigProdcateg() {
        return this.origProdcateg;
    }
    
    public void setOrigProdcateg(OrigProdcateg origProdcateg) {
        this.origProdcateg = origProdcateg;
    }

    
    @Column(name="JOINTHOLDERS", precision=22, scale=0)
    public BigDecimal getJointholders() {
        return this.jointholders;
    }
    
    public void setJointholders(BigDecimal jointholders) {
        this.jointholders = jointholders;
    }




}


