package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrigUploaddocs generated by hbm2java
 */
@Entity
@Table(name="ORIG_UPLOADDOCS"
    ,schema="FCDBADMIN_RK"
)
public class OrigUploaddocs  implements java.io.Serializable {


     private OrigUploaddocsId id;
     private OrigApplication origApplication;
     private String doccategory;
     private String doctype;
     private String docname;
     private BigDecimal docsize;
     private String token1;
     private String token2;
     private String token3;
     private String userrefno;

    public OrigUploaddocs() {
    }

	
    public OrigUploaddocs(OrigUploaddocsId id, OrigApplication origApplication) {
        this.id = id;
        this.origApplication = origApplication;
    }
    public OrigUploaddocs(OrigUploaddocsId id, OrigApplication origApplication, String doccategory, String doctype, String docname, BigDecimal docsize, String token1, String token2, String token3, String userrefno) {
       this.id = id;
       this.origApplication = origApplication;
       this.doccategory = doccategory;
       this.doctype = doctype;
       this.docname = docname;
       this.docsize = docsize;
       this.token1 = token1;
       this.token2 = token2;
       this.token3 = token3;
       this.userrefno = userrefno;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idfcatref", column=@Column(name="IDFCATREF", nullable=false, length=35) ), 
        @AttributeOverride(name="docref", column=@Column(name="DOCREF", nullable=false, length=35) ) } )
    public OrigUploaddocsId getId() {
        return this.id;
    }
    
    public void setId(OrigUploaddocsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFCATREF", nullable=false, insertable=false, updatable=false)
    public OrigApplication getOrigApplication() {
        return this.origApplication;
    }
    
    public void setOrigApplication(OrigApplication origApplication) {
        this.origApplication = origApplication;
    }

    
    @Column(name="DOCCATEGORY", length=50)
    public String getDoccategory() {
        return this.doccategory;
    }
    
    public void setDoccategory(String doccategory) {
        this.doccategory = doccategory;
    }

    
    @Column(name="DOCTYPE", length=50)
    public String getDoctype() {
        return this.doctype;
    }
    
    public void setDoctype(String doctype) {
        this.doctype = doctype;
    }

    
    @Column(name="DOCNAME")
    public String getDocname() {
        return this.docname;
    }
    
    public void setDocname(String docname) {
        this.docname = docname;
    }

    
    @Column(name="DOCSIZE", precision=22, scale=0)
    public BigDecimal getDocsize() {
        return this.docsize;
    }
    
    public void setDocsize(BigDecimal docsize) {
        this.docsize = docsize;
    }

    
    @Column(name="TOKEN1", length=50)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=50)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }

    
    @Column(name="TOKEN3", length=50)
    public String getToken3() {
        return this.token3;
    }
    
    public void setToken3(String token3) {
        this.token3 = token3;
    }

    
    @Column(name="USERREFNO", length=50)
    public String getUserrefno() {
        return this.userrefno;
    }
    
    public void setUserrefno(String userrefno) {
        this.userrefno = userrefno;
    }




}


