package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrigProdfeatureslov generated by hbm2java
 */
@Entity
@Table(name="ORIG_PRODFEATURESLOV"
    ,schema="FCDBADMIN_RK"
)
public class OrigProdfeatureslov  implements java.io.Serializable {


     private OrigProdfeatureslovId id;
     private Short sequenceNo;

    public OrigProdfeatureslov() {
    }

	
    public OrigProdfeatureslov(OrigProdfeatureslovId id) {
        this.id = id;
    }
    public OrigProdfeatureslov(OrigProdfeatureslovId id, Short sequenceNo) {
       this.id = id;
       this.sequenceNo = sequenceNo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="prodcateg", column=@Column(name="PRODCATEG", nullable=false, length=10) ), 
        @AttributeOverride(name="prodcode", column=@Column(name="PRODCODE", nullable=false, length=10) ), 
        @AttributeOverride(name="lovtype", column=@Column(name="LOVTYPE", nullable=false, length=20) ), 
        @AttributeOverride(name="code", column=@Column(name="CODE", nullable=false, length=10) ) } )
    public OrigProdfeatureslovId getId() {
        return this.id;
    }
    
    public void setId(OrigProdfeatureslovId id) {
        this.id = id;
    }

    
    @Column(name="SEQUENCE_NO", precision=4, scale=0)
    public Short getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(Short sequenceNo) {
        this.sequenceNo = sequenceNo;
    }




}


