package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrigApplicantdetails generated by hbm2java
 */
@Entity
@Table(name="ORIG_APPLICANTDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class OrigApplicantdetails  implements java.io.Serializable {


     private OrigApplicantdetailsId id;
     private OrigApplication origApplication;
     private String hostref;
     private String salutation;
     private String fname;
     private String mname;
     private String lname;
     private Date dob;
     private Character gender;
     private String email;
     private String mobile;
     private String phone;
     private String prefcontactmode;
     private String prefcontactwindowstart;
     private String prefcontactwindowend;
     private String personalidtype;
     private String personalidno;
     private String citizen;
     private String resaddress1;
     private String resaddress2;
     private String resaddress3;
     private String rescity;
     private String resstate;
     private String rescountry;
     private String reszipcode;
     private Character resmailsame;
     private String mailaddress1;
     private String mailaddress2;
     private String mailaddress3;
     private String mailcity;
     private String mailstate;
     private String mailcountry;
     private String mailzipcode;
     private Character emptype;
     private String institutename;
     private String designation;
     private BigDecimal income;
     private String currency;
     private Date preferContactDate;
     private String preferContactTime;
     private String idcustomer;
     private Character kycstatus;
     private BigDecimal kycfailedcount;
     private Character typecust;
     private Character maritalstatus;
     private Character tncstatus;
     private Blob udffields;
     private String placeofbirth;
     private String birthcountry;
     private String telisdcode;
     private String mobisdcode;
     private Character initiatedAs;

    public OrigApplicantdetails() {
    }

	
    public OrigApplicantdetails(OrigApplicantdetailsId id, OrigApplication origApplication) {
        this.id = id;
        this.origApplication = origApplication;
    }
    public OrigApplicantdetails(OrigApplicantdetailsId id, OrigApplication origApplication, String hostref, String salutation, String fname, String mname, String lname, Date dob, Character gender, String email, String mobile, String phone, String prefcontactmode, String prefcontactwindowstart, String prefcontactwindowend, String personalidtype, String personalidno, String citizen, String resaddress1, String resaddress2, String resaddress3, String rescity, String resstate, String rescountry, String reszipcode, Character resmailsame, String mailaddress1, String mailaddress2, String mailaddress3, String mailcity, String mailstate, String mailcountry, String mailzipcode, Character emptype, String institutename, String designation, BigDecimal income, String currency, Date preferContactDate, String preferContactTime, String idcustomer, Character kycstatus, BigDecimal kycfailedcount, Character typecust, Character maritalstatus, Character tncstatus, Blob udffields, String placeofbirth, String birthcountry, String telisdcode, String mobisdcode, Character initiatedAs) {
       this.id = id;
       this.origApplication = origApplication;
       this.hostref = hostref;
       this.salutation = salutation;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.dob = dob;
       this.gender = gender;
       this.email = email;
       this.mobile = mobile;
       this.phone = phone;
       this.prefcontactmode = prefcontactmode;
       this.prefcontactwindowstart = prefcontactwindowstart;
       this.prefcontactwindowend = prefcontactwindowend;
       this.personalidtype = personalidtype;
       this.personalidno = personalidno;
       this.citizen = citizen;
       this.resaddress1 = resaddress1;
       this.resaddress2 = resaddress2;
       this.resaddress3 = resaddress3;
       this.rescity = rescity;
       this.resstate = resstate;
       this.rescountry = rescountry;
       this.reszipcode = reszipcode;
       this.resmailsame = resmailsame;
       this.mailaddress1 = mailaddress1;
       this.mailaddress2 = mailaddress2;
       this.mailaddress3 = mailaddress3;
       this.mailcity = mailcity;
       this.mailstate = mailstate;
       this.mailcountry = mailcountry;
       this.mailzipcode = mailzipcode;
       this.emptype = emptype;
       this.institutename = institutename;
       this.designation = designation;
       this.income = income;
       this.currency = currency;
       this.preferContactDate = preferContactDate;
       this.preferContactTime = preferContactTime;
       this.idcustomer = idcustomer;
       this.kycstatus = kycstatus;
       this.kycfailedcount = kycfailedcount;
       this.typecust = typecust;
       this.maritalstatus = maritalstatus;
       this.tncstatus = tncstatus;
       this.udffields = udffields;
       this.placeofbirth = placeofbirth;
       this.birthcountry = birthcountry;
       this.telisdcode = telisdcode;
       this.mobisdcode = mobisdcode;
       this.initiatedAs = initiatedAs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idfcatref", column=@Column(name="IDFCATREF", nullable=false, length=35) ), 
        @AttributeOverride(name="typeapplicant", column=@Column(name="TYPEAPPLICANT", nullable=false, length=3) ) } )
    public OrigApplicantdetailsId getId() {
        return this.id;
    }
    
    public void setId(OrigApplicantdetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFCATREF", nullable=false, insertable=false, updatable=false)
    public OrigApplication getOrigApplication() {
        return this.origApplication;
    }
    
    public void setOrigApplication(OrigApplication origApplication) {
        this.origApplication = origApplication;
    }

    
    @Column(name="HOSTREF", length=20)
    public String getHostref() {
        return this.hostref;
    }
    
    public void setHostref(String hostref) {
        this.hostref = hostref;
    }

    
    @Column(name="SALUTATION", length=20)
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    
    @Column(name="FNAME", length=50)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }

    
    @Column(name="MNAME", length=50)
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }

    
    @Column(name="LNAME", length=50)
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DOB", length=7)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="GENDER", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="MOBILE", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="PHONE", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="PREFCONTACTMODE", length=2)
    public String getPrefcontactmode() {
        return this.prefcontactmode;
    }
    
    public void setPrefcontactmode(String prefcontactmode) {
        this.prefcontactmode = prefcontactmode;
    }

    
    @Column(name="PREFCONTACTWINDOWSTART", length=5)
    public String getPrefcontactwindowstart() {
        return this.prefcontactwindowstart;
    }
    
    public void setPrefcontactwindowstart(String prefcontactwindowstart) {
        this.prefcontactwindowstart = prefcontactwindowstart;
    }

    
    @Column(name="PREFCONTACTWINDOWEND", length=5)
    public String getPrefcontactwindowend() {
        return this.prefcontactwindowend;
    }
    
    public void setPrefcontactwindowend(String prefcontactwindowend) {
        this.prefcontactwindowend = prefcontactwindowend;
    }

    
    @Column(name="PERSONALIDTYPE", length=5)
    public String getPersonalidtype() {
        return this.personalidtype;
    }
    
    public void setPersonalidtype(String personalidtype) {
        this.personalidtype = personalidtype;
    }

    
    @Column(name="PERSONALIDNO", length=20)
    public String getPersonalidno() {
        return this.personalidno;
    }
    
    public void setPersonalidno(String personalidno) {
        this.personalidno = personalidno;
    }

    
    @Column(name="CITIZEN", length=20)
    public String getCitizen() {
        return this.citizen;
    }
    
    public void setCitizen(String citizen) {
        this.citizen = citizen;
    }

    
    @Column(name="RESADDRESS1", length=35)
    public String getResaddress1() {
        return this.resaddress1;
    }
    
    public void setResaddress1(String resaddress1) {
        this.resaddress1 = resaddress1;
    }

    
    @Column(name="RESADDRESS2", length=35)
    public String getResaddress2() {
        return this.resaddress2;
    }
    
    public void setResaddress2(String resaddress2) {
        this.resaddress2 = resaddress2;
    }

    
    @Column(name="RESADDRESS3", length=35)
    public String getResaddress3() {
        return this.resaddress3;
    }
    
    public void setResaddress3(String resaddress3) {
        this.resaddress3 = resaddress3;
    }

    
    @Column(name="RESCITY", length=35)
    public String getRescity() {
        return this.rescity;
    }
    
    public void setRescity(String rescity) {
        this.rescity = rescity;
    }

    
    @Column(name="RESSTATE", length=35)
    public String getResstate() {
        return this.resstate;
    }
    
    public void setResstate(String resstate) {
        this.resstate = resstate;
    }

    
    @Column(name="RESCOUNTRY", length=35)
    public String getRescountry() {
        return this.rescountry;
    }
    
    public void setRescountry(String rescountry) {
        this.rescountry = rescountry;
    }

    
    @Column(name="RESZIPCODE", length=30)
    public String getReszipcode() {
        return this.reszipcode;
    }
    
    public void setReszipcode(String reszipcode) {
        this.reszipcode = reszipcode;
    }

    
    @Column(name="RESMAILSAME", length=1)
    public Character getResmailsame() {
        return this.resmailsame;
    }
    
    public void setResmailsame(Character resmailsame) {
        this.resmailsame = resmailsame;
    }

    
    @Column(name="MAILADDRESS1", length=35)
    public String getMailaddress1() {
        return this.mailaddress1;
    }
    
    public void setMailaddress1(String mailaddress1) {
        this.mailaddress1 = mailaddress1;
    }

    
    @Column(name="MAILADDRESS2", length=35)
    public String getMailaddress2() {
        return this.mailaddress2;
    }
    
    public void setMailaddress2(String mailaddress2) {
        this.mailaddress2 = mailaddress2;
    }

    
    @Column(name="MAILADDRESS3", length=35)
    public String getMailaddress3() {
        return this.mailaddress3;
    }
    
    public void setMailaddress3(String mailaddress3) {
        this.mailaddress3 = mailaddress3;
    }

    
    @Column(name="MAILCITY", length=35)
    public String getMailcity() {
        return this.mailcity;
    }
    
    public void setMailcity(String mailcity) {
        this.mailcity = mailcity;
    }

    
    @Column(name="MAILSTATE", length=35)
    public String getMailstate() {
        return this.mailstate;
    }
    
    public void setMailstate(String mailstate) {
        this.mailstate = mailstate;
    }

    
    @Column(name="MAILCOUNTRY", length=35)
    public String getMailcountry() {
        return this.mailcountry;
    }
    
    public void setMailcountry(String mailcountry) {
        this.mailcountry = mailcountry;
    }

    
    @Column(name="MAILZIPCODE", length=30)
    public String getMailzipcode() {
        return this.mailzipcode;
    }
    
    public void setMailzipcode(String mailzipcode) {
        this.mailzipcode = mailzipcode;
    }

    
    @Column(name="EMPTYPE", length=1)
    public Character getEmptype() {
        return this.emptype;
    }
    
    public void setEmptype(Character emptype) {
        this.emptype = emptype;
    }

    
    @Column(name="INSTITUTENAME")
    public String getInstitutename() {
        return this.institutename;
    }
    
    public void setInstitutename(String institutename) {
        this.institutename = institutename;
    }

    
    @Column(name="DESIGNATION", length=100)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="INCOME", precision=14)
    public BigDecimal getIncome() {
        return this.income;
    }
    
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    
    @Column(name="CURRENCY", length=3)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PREFER_CONTACT_DATE", length=7)
    public Date getPreferContactDate() {
        return this.preferContactDate;
    }
    
    public void setPreferContactDate(Date preferContactDate) {
        this.preferContactDate = preferContactDate;
    }

    
    @Column(name="PREFER_CONTACT_TIME", length=14)
    public String getPreferContactTime() {
        return this.preferContactTime;
    }
    
    public void setPreferContactTime(String preferContactTime) {
        this.preferContactTime = preferContactTime;
    }

    
    @Column(name="IDCUSTOMER", length=30)
    public String getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(String idcustomer) {
        this.idcustomer = idcustomer;
    }

    
    @Column(name="KYCSTATUS", length=1)
    public Character getKycstatus() {
        return this.kycstatus;
    }
    
    public void setKycstatus(Character kycstatus) {
        this.kycstatus = kycstatus;
    }

    
    @Column(name="KYCFAILEDCOUNT", precision=22, scale=0)
    public BigDecimal getKycfailedcount() {
        return this.kycfailedcount;
    }
    
    public void setKycfailedcount(BigDecimal kycfailedcount) {
        this.kycfailedcount = kycfailedcount;
    }

    
    @Column(name="TYPECUST", length=1)
    public Character getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(Character typecust) {
        this.typecust = typecust;
    }

    
    @Column(name="MARITALSTATUS", length=1)
    public Character getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(Character maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    
    @Column(name="TNCSTATUS", length=1)
    public Character getTncstatus() {
        return this.tncstatus;
    }
    
    public void setTncstatus(Character tncstatus) {
        this.tncstatus = tncstatus;
    }

    
    @Column(name="UDFFIELDS")
    public Blob getUdffields() {
        return this.udffields;
    }
    
    public void setUdffields(Blob udffields) {
        this.udffields = udffields;
    }

    
    @Column(name="PLACEOFBIRTH", length=35)
    public String getPlaceofbirth() {
        return this.placeofbirth;
    }
    
    public void setPlaceofbirth(String placeofbirth) {
        this.placeofbirth = placeofbirth;
    }

    
    @Column(name="BIRTHCOUNTRY", length=35)
    public String getBirthcountry() {
        return this.birthcountry;
    }
    
    public void setBirthcountry(String birthcountry) {
        this.birthcountry = birthcountry;
    }

    
    @Column(name="TELISDCODE", length=3)
    public String getTelisdcode() {
        return this.telisdcode;
    }
    
    public void setTelisdcode(String telisdcode) {
        this.telisdcode = telisdcode;
    }

    
    @Column(name="MOBISDCODE", length=3)
    public String getMobisdcode() {
        return this.mobisdcode;
    }
    
    public void setMobisdcode(String mobisdcode) {
        this.mobisdcode = mobisdcode;
    }

    
    @Column(name="INITIATED_AS", length=1)
    public Character getInitiatedAs() {
        return this.initiatedAs;
    }
    
    public void setInitiatedAs(Character initiatedAs) {
        this.initiatedAs = initiatedAs;
    }




}


