package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Passwordpolicy generated by hbm2java
 */
@Entity
@Table(name="PASSWORDPOLICY"
    ,schema="FCDBADMIN_RK"
)
public class Passwordpolicy  implements java.io.Serializable {


     private String idpolicy;
     private Byte minlength;
     private Short maxlength;
     private String firstchar;
     private Byte nbrloweralpha;
     private Byte nbrupperalpha;
     private Byte nbrnumeric;
     private Byte nbrspecial;
     private String charallowed;
     private Long maxpasswordage;
     private Long minpasswordage;
     private Byte historysize;
     private Character repeathistoryallowed;
     private Long warningperiod;
     private Character ismodified;
     private Byte lockcount;
     private String makerid;
     private String checkerid;
     private Date datmodified;
     private Date dateffective;
     private Character forcedresetpasswd;
     private Long hibernationperiod;
     private String lastchar;
     private Byte repeatallowed;
     private Byte successiveallowed;
     private String customEncryptor;
     private Byte nbrrandom;
     private Long firstuseperiod;
     private String specialchar;
     private Character hasforcechangepwd;
     private Set<Mstentityuserchannel> mstentityuserchannels = new HashSet<Mstentityuserchannel>(0);

    public Passwordpolicy() {
    }

	
    public Passwordpolicy(String idpolicy) {
        this.idpolicy = idpolicy;
    }
    public Passwordpolicy(String idpolicy, Byte minlength, Short maxlength, String firstchar, Byte nbrloweralpha, Byte nbrupperalpha, Byte nbrnumeric, Byte nbrspecial, String charallowed, Long maxpasswordage, Long minpasswordage, Byte historysize, Character repeathistoryallowed, Long warningperiod, Character ismodified, Byte lockcount, String makerid, String checkerid, Date datmodified, Date dateffective, Character forcedresetpasswd, Long hibernationperiod, String lastchar, Byte repeatallowed, Byte successiveallowed, String customEncryptor, Byte nbrrandom, Long firstuseperiod, String specialchar, Character hasforcechangepwd, Set<Mstentityuserchannel> mstentityuserchannels) {
       this.idpolicy = idpolicy;
       this.minlength = minlength;
       this.maxlength = maxlength;
       this.firstchar = firstchar;
       this.nbrloweralpha = nbrloweralpha;
       this.nbrupperalpha = nbrupperalpha;
       this.nbrnumeric = nbrnumeric;
       this.nbrspecial = nbrspecial;
       this.charallowed = charallowed;
       this.maxpasswordage = maxpasswordage;
       this.minpasswordage = minpasswordage;
       this.historysize = historysize;
       this.repeathistoryallowed = repeathistoryallowed;
       this.warningperiod = warningperiod;
       this.ismodified = ismodified;
       this.lockcount = lockcount;
       this.makerid = makerid;
       this.checkerid = checkerid;
       this.datmodified = datmodified;
       this.dateffective = dateffective;
       this.forcedresetpasswd = forcedresetpasswd;
       this.hibernationperiod = hibernationperiod;
       this.lastchar = lastchar;
       this.repeatallowed = repeatallowed;
       this.successiveallowed = successiveallowed;
       this.customEncryptor = customEncryptor;
       this.nbrrandom = nbrrandom;
       this.firstuseperiod = firstuseperiod;
       this.specialchar = specialchar;
       this.hasforcechangepwd = hasforcechangepwd;
       this.mstentityuserchannels = mstentityuserchannels;
    }
   
     @Id 

    
    @Column(name="IDPOLICY", unique=true, nullable=false, length=50)
    public String getIdpolicy() {
        return this.idpolicy;
    }
    
    public void setIdpolicy(String idpolicy) {
        this.idpolicy = idpolicy;
    }

    
    @Column(name="MINLENGTH", precision=2, scale=0)
    public Byte getMinlength() {
        return this.minlength;
    }
    
    public void setMinlength(Byte minlength) {
        this.minlength = minlength;
    }

    
    @Column(name="MAXLENGTH", precision=3, scale=0)
    public Short getMaxlength() {
        return this.maxlength;
    }
    
    public void setMaxlength(Short maxlength) {
        this.maxlength = maxlength;
    }

    
    @Column(name="FIRSTCHAR", length=10)
    public String getFirstchar() {
        return this.firstchar;
    }
    
    public void setFirstchar(String firstchar) {
        this.firstchar = firstchar;
    }

    
    @Column(name="NBRLOWERALPHA", precision=2, scale=0)
    public Byte getNbrloweralpha() {
        return this.nbrloweralpha;
    }
    
    public void setNbrloweralpha(Byte nbrloweralpha) {
        this.nbrloweralpha = nbrloweralpha;
    }

    
    @Column(name="NBRUPPERALPHA", precision=2, scale=0)
    public Byte getNbrupperalpha() {
        return this.nbrupperalpha;
    }
    
    public void setNbrupperalpha(Byte nbrupperalpha) {
        this.nbrupperalpha = nbrupperalpha;
    }

    
    @Column(name="NBRNUMERIC", precision=2, scale=0)
    public Byte getNbrnumeric() {
        return this.nbrnumeric;
    }
    
    public void setNbrnumeric(Byte nbrnumeric) {
        this.nbrnumeric = nbrnumeric;
    }

    
    @Column(name="NBRSPECIAL", precision=2, scale=0)
    public Byte getNbrspecial() {
        return this.nbrspecial;
    }
    
    public void setNbrspecial(Byte nbrspecial) {
        this.nbrspecial = nbrspecial;
    }

    
    @Column(name="CHARALLOWED", length=10)
    public String getCharallowed() {
        return this.charallowed;
    }
    
    public void setCharallowed(String charallowed) {
        this.charallowed = charallowed;
    }

    
    @Column(name="MAXPASSWORDAGE", precision=15, scale=0)
    public Long getMaxpasswordage() {
        return this.maxpasswordage;
    }
    
    public void setMaxpasswordage(Long maxpasswordage) {
        this.maxpasswordage = maxpasswordage;
    }

    
    @Column(name="MINPASSWORDAGE", precision=15, scale=0)
    public Long getMinpasswordage() {
        return this.minpasswordage;
    }
    
    public void setMinpasswordage(Long minpasswordage) {
        this.minpasswordage = minpasswordage;
    }

    
    @Column(name="HISTORYSIZE", precision=2, scale=0)
    public Byte getHistorysize() {
        return this.historysize;
    }
    
    public void setHistorysize(Byte historysize) {
        this.historysize = historysize;
    }

    
    @Column(name="REPEATHISTORYALLOWED", length=1)
    public Character getRepeathistoryallowed() {
        return this.repeathistoryallowed;
    }
    
    public void setRepeathistoryallowed(Character repeathistoryallowed) {
        this.repeathistoryallowed = repeathistoryallowed;
    }

    
    @Column(name="WARNINGPERIOD", precision=15, scale=0)
    public Long getWarningperiod() {
        return this.warningperiod;
    }
    
    public void setWarningperiod(Long warningperiod) {
        this.warningperiod = warningperiod;
    }

    
    @Column(name="ISMODIFIED", length=1)
    public Character getIsmodified() {
        return this.ismodified;
    }
    
    public void setIsmodified(Character ismodified) {
        this.ismodified = ismodified;
    }

    
    @Column(name="LOCKCOUNT", precision=2, scale=0)
    public Byte getLockcount() {
        return this.lockcount;
    }
    
    public void setLockcount(Byte lockcount) {
        this.lockcount = lockcount;
    }

    
    @Column(name="MAKERID", length=50)
    public String getMakerid() {
        return this.makerid;
    }
    
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    
    @Column(name="CHECKERID", length=10)
    public String getCheckerid() {
        return this.checkerid;
    }
    
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMODIFIED", length=7)
    public Date getDatmodified() {
        return this.datmodified;
    }
    
    public void setDatmodified(Date datmodified) {
        this.datmodified = datmodified;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEFFECTIVE", length=7)
    public Date getDateffective() {
        return this.dateffective;
    }
    
    public void setDateffective(Date dateffective) {
        this.dateffective = dateffective;
    }

    
    @Column(name="FORCEDRESETPASSWD", length=1)
    public Character getForcedresetpasswd() {
        return this.forcedresetpasswd;
    }
    
    public void setForcedresetpasswd(Character forcedresetpasswd) {
        this.forcedresetpasswd = forcedresetpasswd;
    }

    
    @Column(name="HIBERNATIONPERIOD", precision=15, scale=0)
    public Long getHibernationperiod() {
        return this.hibernationperiod;
    }
    
    public void setHibernationperiod(Long hibernationperiod) {
        this.hibernationperiod = hibernationperiod;
    }

    
    @Column(name="LASTCHAR", length=10)
    public String getLastchar() {
        return this.lastchar;
    }
    
    public void setLastchar(String lastchar) {
        this.lastchar = lastchar;
    }

    
    @Column(name="REPEATALLOWED", precision=2, scale=0)
    public Byte getRepeatallowed() {
        return this.repeatallowed;
    }
    
    public void setRepeatallowed(Byte repeatallowed) {
        this.repeatallowed = repeatallowed;
    }

    
    @Column(name="SUCCESSIVEALLOWED", precision=2, scale=0)
    public Byte getSuccessiveallowed() {
        return this.successiveallowed;
    }
    
    public void setSuccessiveallowed(Byte successiveallowed) {
        this.successiveallowed = successiveallowed;
    }

    
    @Column(name="CUSTOM_ENCRYPTOR")
    public String getCustomEncryptor() {
        return this.customEncryptor;
    }
    
    public void setCustomEncryptor(String customEncryptor) {
        this.customEncryptor = customEncryptor;
    }

    
    @Column(name="NBRRANDOM", precision=2, scale=0)
    public Byte getNbrrandom() {
        return this.nbrrandom;
    }
    
    public void setNbrrandom(Byte nbrrandom) {
        this.nbrrandom = nbrrandom;
    }

    
    @Column(name="FIRSTUSEPERIOD", precision=15, scale=0)
    public Long getFirstuseperiod() {
        return this.firstuseperiod;
    }
    
    public void setFirstuseperiod(Long firstuseperiod) {
        this.firstuseperiod = firstuseperiod;
    }

    
    @Column(name="SPECIALCHAR", length=100)
    public String getSpecialchar() {
        return this.specialchar;
    }
    
    public void setSpecialchar(String specialchar) {
        this.specialchar = specialchar;
    }

    
    @Column(name="HASFORCECHANGEPWD", length=1)
    public Character getHasforcechangepwd() {
        return this.hasforcechangepwd;
    }
    
    public void setHasforcechangepwd(Character hasforcechangepwd) {
        this.hasforcechangepwd = hasforcechangepwd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="passwordpolicy")
    public Set<Mstentityuserchannel> getMstentityuserchannels() {
        return this.mstentityuserchannels;
    }
    
    public void setMstentityuserchannels(Set<Mstentityuserchannel> mstentityuserchannels) {
        this.mstentityuserchannels = mstentityuserchannels;
    }




}


