package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Passwordhistory generated by hbm2java
 */
@Entity
@Table(name="PASSWORDHISTORY"
    ,schema="FCDBADMIN_RK"
)
public class Passwordhistory  implements java.io.Serializable {


     private PasswordhistoryId id;
     private String idchannel;
     private String password;

    public Passwordhistory() {
    }

	
    public Passwordhistory(PasswordhistoryId id) {
        this.id = id;
    }
    public Passwordhistory(PasswordhistoryId id, String idchannel, String password) {
       this.id = id;
       this.idchannel = idchannel;
       this.password = password;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idchanneluser", column=@Column(name="IDCHANNELUSER", nullable=false) ), 
        @AttributeOverride(name="idgroup", column=@Column(name="IDGROUP", nullable=false, length=5) ), 
        @AttributeOverride(name="datcreation", column=@Column(name="DATCREATION", nullable=false, length=7) ) } )
    public PasswordhistoryId getId() {
        return this.id;
    }
    
    public void setId(PasswordhistoryId id) {
        this.id = id;
    }

    
    @Column(name="IDCHANNEL", length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    
    @Column(name="PASSWORD", length=2500)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


