package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Peertxnunauthdata generated by hbm2java
 */
@Entity
@Table(name="PEERTXNUNAUTHDATA"
    ,schema="FCDBADMIN_RK"
)
public class Peertxnunauthdata  implements java.io.Serializable {


     private String idfcatref;
     private Date datinit;
     private String typeContact;
     private String valContact;
     private String displayname;
     private String seccode;
     private Character status;
     private String idEntity;
     private String hostrefno;
     private Character contractStatus;

    public Peertxnunauthdata() {
    }

	
    public Peertxnunauthdata(String idfcatref) {
        this.idfcatref = idfcatref;
    }
    public Peertxnunauthdata(String idfcatref, Date datinit, String typeContact, String valContact, String displayname, String seccode, Character status, String idEntity, String hostrefno, Character contractStatus) {
       this.idfcatref = idfcatref;
       this.datinit = datinit;
       this.typeContact = typeContact;
       this.valContact = valContact;
       this.displayname = displayname;
       this.seccode = seccode;
       this.status = status;
       this.idEntity = idEntity;
       this.hostrefno = hostrefno;
       this.contractStatus = contractStatus;
    }
   
     @Id 

    
    @Column(name="IDFCATREF", unique=true, nullable=false, length=15)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATINIT", length=7)
    public Date getDatinit() {
        return this.datinit;
    }
    
    public void setDatinit(Date datinit) {
        this.datinit = datinit;
    }

    
    @Column(name="TYPE_CONTACT", length=2)
    public String getTypeContact() {
        return this.typeContact;
    }
    
    public void setTypeContact(String typeContact) {
        this.typeContact = typeContact;
    }

    
    @Column(name="VAL_CONTACT")
    public String getValContact() {
        return this.valContact;
    }
    
    public void setValContact(String valContact) {
        this.valContact = valContact;
    }

    
    @Column(name="DISPLAYNAME")
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    
    @Column(name="SECCODE")
    public String getSeccode() {
        return this.seccode;
    }
    
    public void setSeccode(String seccode) {
        this.seccode = seccode;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="ID_ENTITY", length=4)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="HOSTREFNO", length=20)
    public String getHostrefno() {
        return this.hostrefno;
    }
    
    public void setHostrefno(String hostrefno) {
        this.hostrefno = hostrefno;
    }

    
    @Column(name="CONTRACT_STATUS", length=1)
    public Character getContractStatus() {
        return this.contractStatus;
    }
    
    public void setContractStatus(Character contractStatus) {
        this.contractStatus = contractStatus;
    }




}


