package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Clob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Remittancedetails generated by hbm2java
 */
@Entity
@Table(name="REMITTANCEDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class Remittancedetails  implements java.io.Serializable {


     private RemittancedetailsId id;
     private String remittanceItem;
     private String remittanceDesc;
     private Clob idudf;
     private Character specifyOther;

    public Remittancedetails() {
    }

	
    public Remittancedetails(RemittancedetailsId id) {
        this.id = id;
    }
    public Remittancedetails(RemittancedetailsId id, String remittanceItem, String remittanceDesc, Clob idudf, Character specifyOther) {
       this.id = id;
       this.remittanceItem = remittanceItem;
       this.remittanceDesc = remittanceDesc;
       this.idudf = idudf;
       this.specifyOther = specifyOther;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="remittanceType", column=@Column(name="REMITTANCE_TYPE", nullable=false, length=2) ), 
        @AttributeOverride(name="remittanceCode", column=@Column(name="REMITTANCE_CODE", nullable=false, length=4) ) } )
    public RemittancedetailsId getId() {
        return this.id;
    }
    
    public void setId(RemittancedetailsId id) {
        this.id = id;
    }

    
    @Column(name="REMITTANCE_ITEM")
    public String getRemittanceItem() {
        return this.remittanceItem;
    }
    
    public void setRemittanceItem(String remittanceItem) {
        this.remittanceItem = remittanceItem;
    }

    
    @Column(name="REMITTANCE_DESC", length=4000)
    public String getRemittanceDesc() {
        return this.remittanceDesc;
    }
    
    public void setRemittanceDesc(String remittanceDesc) {
        this.remittanceDesc = remittanceDesc;
    }

    
    @Column(name="IDUDF")
    public Clob getIdudf() {
        return this.idudf;
    }
    
    public void setIdudf(Clob idudf) {
        this.idudf = idudf;
    }

    
    @Column(name="SPECIFY_OTHER", length=1)
    public Character getSpecifyOther() {
        return this.specifyOther;
    }
    
    public void setSpecifyOther(Character specifyOther) {
        this.specifyOther = specifyOther;
    }




}


