package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rmsversion generated by hbm2java
 */
@Entity
@Table(name="RMSVERSION"
    ,schema="FCDBADMIN_RK"
)
public class Rmsversion  implements java.io.Serializable {


     private RmsversionId id;
     private BigDecimal currversion;
     private BigDecimal oldversion;
     private Date datupload;
     private Character isappupdate;

    public Rmsversion() {
    }

	
    public Rmsversion(RmsversionId id) {
        this.id = id;
    }
    public Rmsversion(RmsversionId id, BigDecimal currversion, BigDecimal oldversion, Date datupload, Character isappupdate) {
       this.id = id;
       this.currversion = currversion;
       this.oldversion = oldversion;
       this.datupload = datupload;
       this.isappupdate = isappupdate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduseragent", column=@Column(name="IDUSERAGENT", nullable=false, length=35) ), 
        @AttributeOverride(name="iddevice", column=@Column(name="IDDEVICE", nullable=false, length=35) ) } )
    public RmsversionId getId() {
        return this.id;
    }
    
    public void setId(RmsversionId id) {
        this.id = id;
    }

    
    @Column(name="CURRVERSION", precision=4)
    public BigDecimal getCurrversion() {
        return this.currversion;
    }
    
    public void setCurrversion(BigDecimal currversion) {
        this.currversion = currversion;
    }

    
    @Column(name="OLDVERSION", precision=4)
    public BigDecimal getOldversion() {
        return this.oldversion;
    }
    
    public void setOldversion(BigDecimal oldversion) {
        this.oldversion = oldversion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUPLOAD", length=7)
    public Date getDatupload() {
        return this.datupload;
    }
    
    public void setDatupload(Date datupload) {
        this.datupload = datupload;
    }

    
    @Column(name="ISAPPUPDATE", length=1)
    public Character getIsappupdate() {
        return this.isappupdate;
    }
    
    public void setIsappupdate(Character isappupdate) {
        this.isappupdate = isappupdate;
    }




}


