package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RmsversionId generated by hbm2java
 */
@Embeddable
public class RmsversionId  implements java.io.Serializable {


     private String iduseragent;
     private String iddevice;

    public RmsversionId() {
    }

    public RmsversionId(String iduseragent, String iddevice) {
       this.iduseragent = iduseragent;
       this.iddevice = iddevice;
    }
   


    @Column(name="IDUSERAGENT", nullable=false, length=35)
    public String getIduseragent() {
        return this.iduseragent;
    }
    
    public void setIduseragent(String iduseragent) {
        this.iduseragent = iduseragent;
    }


    @Column(name="IDDEVICE", nullable=false, length=35)
    public String getIddevice() {
        return this.iddevice;
    }
    
    public void setIddevice(String iddevice) {
        this.iddevice = iddevice;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RmsversionId) ) return false;
		 RmsversionId castOther = ( RmsversionId ) other; 
         
		 return ( (this.getIduseragent()==castOther.getIduseragent()) || ( this.getIduseragent()!=null && castOther.getIduseragent()!=null && this.getIduseragent().equals(castOther.getIduseragent()) ) )
 && ( (this.getIddevice()==castOther.getIddevice()) || ( this.getIddevice()!=null && castOther.getIddevice()!=null && this.getIddevice().equals(castOther.getIddevice()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIduseragent() == null ? 0 : this.getIduseragent().hashCode() );
         result = 37 * result + ( getIddevice() == null ? 0 : this.getIddevice().hashCode() );
         return result;
   }   


}


