package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Screentabledefinition generated by hbm2java
 */
@Entity
@Table(name="SCREENTABLEDEFINITION"
    ,schema="FCDBADMIN_RK"
)
public class Screentabledefinition  implements java.io.Serializable {


     private ScreentabledefinitionId id;
     private Msthtmldatatypes msthtmldatatypes;
     private String idtxn;
     private String align;
     private String border;
     private String cellspacing;
     private String cellpadding;
     private String class_;
     private String width;
     private String caption;
     private String captionclass;
     private String captionalign;
     private BigDecimal tableseqno;
     private String parentorchild;
     private BigDecimal parenttableid;
     private String legendlabel;
     private String legendclass;
     private Character defaultdisplay;
     private String condition;
     private BigDecimal relposx;
     private BigDecimal relposy;
     private BigDecimal relwidth;
     private BigDecimal relheight;
     private Character scrollable;
     private String type;
     private Character toggleflag;
     private String toggleimage1;
     private String toggleimage2;

    public Screentabledefinition() {
    }

	
    public Screentabledefinition(ScreentabledefinitionId id) {
        this.id = id;
    }
    public Screentabledefinition(ScreentabledefinitionId id, Msthtmldatatypes msthtmldatatypes, String idtxn, String align, String border, String cellspacing, String cellpadding, String class_, String width, String caption, String captionclass, String captionalign, BigDecimal tableseqno, String parentorchild, BigDecimal parenttableid, String legendlabel, String legendclass, Character defaultdisplay, String condition, BigDecimal relposx, BigDecimal relposy, BigDecimal relwidth, BigDecimal relheight, Character scrollable, String type, Character toggleflag, String toggleimage1, String toggleimage2) {
       this.id = id;
       this.msthtmldatatypes = msthtmldatatypes;
       this.idtxn = idtxn;
       this.align = align;
       this.border = border;
       this.cellspacing = cellspacing;
       this.cellpadding = cellpadding;
       this.class_ = class_;
       this.width = width;
       this.caption = caption;
       this.captionclass = captionclass;
       this.captionalign = captionalign;
       this.tableseqno = tableseqno;
       this.parentorchild = parentorchild;
       this.parenttableid = parenttableid;
       this.legendlabel = legendlabel;
       this.legendclass = legendclass;
       this.defaultdisplay = defaultdisplay;
       this.condition = condition;
       this.relposx = relposx;
       this.relposy = relposy;
       this.relwidth = relwidth;
       this.relheight = relheight;
       this.scrollable = scrollable;
       this.type = type;
       this.toggleflag = toggleflag;
       this.toggleimage1 = toggleimage1;
       this.toggleimage2 = toggleimage2;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrequest", column=@Column(name="IDREQUEST", nullable=false, length=8) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="identity", column=@Column(name="IDENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="usertype", column=@Column(name="USERTYPE", nullable=false, length=3) ), 
        @AttributeOverride(name="idtable", column=@Column(name="IDTABLE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="useragent", column=@Column(name="USERAGENT", nullable=false, length=50) ) } )
    public ScreentabledefinitionId getId() {
        return this.id;
    }
    
    public void setId(ScreentabledefinitionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMIZEDTEMPLATEID")
    public Msthtmldatatypes getMsthtmldatatypes() {
        return this.msthtmldatatypes;
    }
    
    public void setMsthtmldatatypes(Msthtmldatatypes msthtmldatatypes) {
        this.msthtmldatatypes = msthtmldatatypes;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="ALIGN", length=10)
    public String getAlign() {
        return this.align;
    }
    
    public void setAlign(String align) {
        this.align = align;
    }

    
    @Column(name="BORDER", length=3)
    public String getBorder() {
        return this.border;
    }
    
    public void setBorder(String border) {
        this.border = border;
    }

    
    @Column(name="CELLSPACING", length=2)
    public String getCellspacing() {
        return this.cellspacing;
    }
    
    public void setCellspacing(String cellspacing) {
        this.cellspacing = cellspacing;
    }

    
    @Column(name="CELLPADDING", length=2)
    public String getCellpadding() {
        return this.cellpadding;
    }
    
    public void setCellpadding(String cellpadding) {
        this.cellpadding = cellpadding;
    }

    
    @Column(name="CLASS", length=25)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="WIDTH", length=5)
    public String getWidth() {
        return this.width;
    }
    
    public void setWidth(String width) {
        this.width = width;
    }

    
    @Column(name="CAPTION", length=250)
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }

    
    @Column(name="CAPTIONCLASS", length=25)
    public String getCaptionclass() {
        return this.captionclass;
    }
    
    public void setCaptionclass(String captionclass) {
        this.captionclass = captionclass;
    }

    
    @Column(name="CAPTIONALIGN", length=10)
    public String getCaptionalign() {
        return this.captionalign;
    }
    
    public void setCaptionalign(String captionalign) {
        this.captionalign = captionalign;
    }

    
    @Column(name="TABLESEQNO", precision=22, scale=0)
    public BigDecimal getTableseqno() {
        return this.tableseqno;
    }
    
    public void setTableseqno(BigDecimal tableseqno) {
        this.tableseqno = tableseqno;
    }

    
    @Column(name="PARENTORCHILD", length=1)
    public String getParentorchild() {
        return this.parentorchild;
    }
    
    public void setParentorchild(String parentorchild) {
        this.parentorchild = parentorchild;
    }

    
    @Column(name="PARENTTABLEID", precision=22, scale=0)
    public BigDecimal getParenttableid() {
        return this.parenttableid;
    }
    
    public void setParenttableid(BigDecimal parenttableid) {
        this.parenttableid = parenttableid;
    }

    
    @Column(name="LEGENDLABEL", length=250)
    public String getLegendlabel() {
        return this.legendlabel;
    }
    
    public void setLegendlabel(String legendlabel) {
        this.legendlabel = legendlabel;
    }

    
    @Column(name="LEGENDCLASS", length=250)
    public String getLegendclass() {
        return this.legendclass;
    }
    
    public void setLegendclass(String legendclass) {
        this.legendclass = legendclass;
    }

    
    @Column(name="DEFAULTDISPLAY", length=1)
    public Character getDefaultdisplay() {
        return this.defaultdisplay;
    }
    
    public void setDefaultdisplay(Character defaultdisplay) {
        this.defaultdisplay = defaultdisplay;
    }

    
    @Column(name="CONDITION", length=1000)
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }

    
    @Column(name="RELPOSX", precision=4, scale=3)
    public BigDecimal getRelposx() {
        return this.relposx;
    }
    
    public void setRelposx(BigDecimal relposx) {
        this.relposx = relposx;
    }

    
    @Column(name="RELPOSY", precision=4, scale=3)
    public BigDecimal getRelposy() {
        return this.relposy;
    }
    
    public void setRelposy(BigDecimal relposy) {
        this.relposy = relposy;
    }

    
    @Column(name="RELWIDTH", precision=4, scale=3)
    public BigDecimal getRelwidth() {
        return this.relwidth;
    }
    
    public void setRelwidth(BigDecimal relwidth) {
        this.relwidth = relwidth;
    }

    
    @Column(name="RELHEIGHT", precision=4, scale=3)
    public BigDecimal getRelheight() {
        return this.relheight;
    }
    
    public void setRelheight(BigDecimal relheight) {
        this.relheight = relheight;
    }

    
    @Column(name="SCROLLABLE", length=1)
    public Character getScrollable() {
        return this.scrollable;
    }
    
    public void setScrollable(Character scrollable) {
        this.scrollable = scrollable;
    }

    
    @Column(name="TYPE", length=1)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="TOGGLEFLAG", length=1)
    public Character getToggleflag() {
        return this.toggleflag;
    }
    
    public void setToggleflag(Character toggleflag) {
        this.toggleflag = toggleflag;
    }

    
    @Column(name="TOGGLEIMAGE1", length=250)
    public String getToggleimage1() {
        return this.toggleimage1;
    }
    
    public void setToggleimage1(String toggleimage1) {
        this.toggleimage1 = toggleimage1;
    }

    
    @Column(name="TOGGLEIMAGE2", length=250)
    public String getToggleimage2() {
        return this.toggleimage2;
    }
    
    public void setToggleimage2(String toggleimage2) {
        this.toggleimage2 = toggleimage2;
    }




}


