package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SwIsoCu generated by hbm2java
 */
@Entity
@Table(name="SW_ISO_CU"
    ,schema="FCDBADMIN_RK"
)
public class SwIsoCu  implements java.io.Serializable {


     private String codCurrency;
     private SwIsoCt swIsoCt;
     private String namCurrencyFull;
     private String namCurrency1;
     private String namCurrency2;
     private Boolean fractionalDigit;
     private String namCountryFull;
     private String namCountry1;
     private String namCountry2;
     private String isenabled;
     private Date datlastupdated;

    public SwIsoCu() {
    }

	
    public SwIsoCu(String codCurrency) {
        this.codCurrency = codCurrency;
    }
    public SwIsoCu(String codCurrency, SwIsoCt swIsoCt, String namCurrencyFull, String namCurrency1, String namCurrency2, Boolean fractionalDigit, String namCountryFull, String namCountry1, String namCountry2, String isenabled, Date datlastupdated) {
       this.codCurrency = codCurrency;
       this.swIsoCt = swIsoCt;
       this.namCurrencyFull = namCurrencyFull;
       this.namCurrency1 = namCurrency1;
       this.namCurrency2 = namCurrency2;
       this.fractionalDigit = fractionalDigit;
       this.namCountryFull = namCountryFull;
       this.namCountry1 = namCountry1;
       this.namCountry2 = namCountry2;
       this.isenabled = isenabled;
       this.datlastupdated = datlastupdated;
    }
   
     @Id 

    
    @Column(name="COD_CURRENCY", unique=true, nullable=false, length=3)
    public String getCodCurrency() {
        return this.codCurrency;
    }
    
    public void setCodCurrency(String codCurrency) {
        this.codCurrency = codCurrency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COD_COUNTRY")
    public SwIsoCt getSwIsoCt() {
        return this.swIsoCt;
    }
    
    public void setSwIsoCt(SwIsoCt swIsoCt) {
        this.swIsoCt = swIsoCt;
    }

    
    @Column(name="NAM_CURRENCY_FULL", length=70)
    public String getNamCurrencyFull() {
        return this.namCurrencyFull;
    }
    
    public void setNamCurrencyFull(String namCurrencyFull) {
        this.namCurrencyFull = namCurrencyFull;
    }

    
    @Column(name="NAM_CURRENCY1", length=35)
    public String getNamCurrency1() {
        return this.namCurrency1;
    }
    
    public void setNamCurrency1(String namCurrency1) {
        this.namCurrency1 = namCurrency1;
    }

    
    @Column(name="NAM_CURRENCY2", length=35)
    public String getNamCurrency2() {
        return this.namCurrency2;
    }
    
    public void setNamCurrency2(String namCurrency2) {
        this.namCurrency2 = namCurrency2;
    }

    
    @Column(name="FRACTIONAL_DIGIT", precision=1, scale=0)
    public Boolean getFractionalDigit() {
        return this.fractionalDigit;
    }
    
    public void setFractionalDigit(Boolean fractionalDigit) {
        this.fractionalDigit = fractionalDigit;
    }

    
    @Column(name="NAM_COUNTRY_FULL", length=70)
    public String getNamCountryFull() {
        return this.namCountryFull;
    }
    
    public void setNamCountryFull(String namCountryFull) {
        this.namCountryFull = namCountryFull;
    }

    
    @Column(name="NAM_COUNTRY1", length=35)
    public String getNamCountry1() {
        return this.namCountry1;
    }
    
    public void setNamCountry1(String namCountry1) {
        this.namCountry1 = namCountry1;
    }

    
    @Column(name="NAM_COUNTRY2", length=35)
    public String getNamCountry2() {
        return this.namCountry2;
    }
    
    public void setNamCountry2(String namCountry2) {
        this.namCountry2 = namCountry2;
    }

    
    @Column(name="ISENABLED", length=1)
    public String getIsenabled() {
        return this.isenabled;
    }
    
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATLASTUPDATED", length=7)
    public Date getDatlastupdated() {
        return this.datlastupdated;
    }
    
    public void setDatlastupdated(Date datlastupdated) {
        this.datlastupdated = datlastupdated;
    }




}


