package com.jmr.obdx.domain;

import java.io.Serializable;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransferType generated by hbm2java
 */
@Entity
@Table(name="TRANSFER_TYPE"
    ,schema="JMR_OBDX"
)
public class TransferType  implements java.io.Serializable {


     private long id;
     private String description;
     private Set<TransactionData> transactionDatas = new HashSet<TransactionData>(0);

    public TransferType() {
    }

	
    public TransferType(long id) {
        this.id = id;
    }
    public TransferType(long id, String description, Set<TransactionData> transactionDatas) {
       this.id = id;
       this.description = description;
       this.transactionDatas = transactionDatas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transferType")
    public Set<TransactionData> getTransactionDatas() {
        return this.transactionDatas;
    }
    
    public void setTransactionDatas(Set<TransactionData> transactionDatas) {
        this.transactionDatas = transactionDatas;
    }




}

