package com.jmr.obdx.domain;

import java.io.Serializable;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransferType generated by hbm2java
 */
@Entity
@Table(name="TRANSFER_TYPE"
    ,schema="JMR_OBDX"
)
public class TransferType  implements java.io.Serializable {


     private long id;
     private String description;
     private Set<BranchDetailsM> branchDetailsMs = new HashSet<BranchDetailsM>(0);

    public TransferType() {
    }

	
    public TransferType(long id) {
        this.id = id;
    }
    public TransferType(long id, String description,Set<BranchDetailsM> branchDetailsMs) {
       this.id = id;
       this.description = description;
       this.branchDetailsMs = branchDetailsMs;

    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




@OneToMany(fetch=FetchType.LAZY, mappedBy="transferType")
    public Set<BranchDetailsM> getBranchDetailsMs() {
        return this.branchDetailsMs;
    }
    
    public void setBranchDetailsMs(Set<BranchDetailsM> branchDetailsMs) {
        this.branchDetailsMs = branchDetailsMs;
    }


}

