package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txnactions generated by hbm2java
 */
@Entity
@Table(name="TXNACTIONS"
    ,schema="FCDBADMIN_RK"
)
public class Txnactions  implements java.io.Serializable {


     private TxnactionsId id;
     private String idaction;
     private String idfcatref;
     private String requestdata;
     private Blob requestdata2;
     private Date datcreated;
     private Date datexpiry;

    public Txnactions() {
    }

	
    public Txnactions(TxnactionsId id) {
        this.id = id;
    }
    public Txnactions(TxnactionsId id, String idaction, String idfcatref, String requestdata, Blob requestdata2, Date datcreated, Date datexpiry) {
       this.id = id;
       this.idaction = idaction;
       this.idfcatref = idfcatref;
       this.requestdata = requestdata;
       this.requestdata2 = requestdata2;
       this.datcreated = datcreated;
       this.datexpiry = datexpiry;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=256) ), 
        @AttributeOverride(name="idchannel", column=@Column(name="IDCHANNEL", nullable=false, length=2) ), 
        @AttributeOverride(name="idactionref", column=@Column(name="IDACTIONREF", nullable=false, precision=10, scale=0) ) } )
    public TxnactionsId getId() {
        return this.id;
    }
    
    public void setId(TxnactionsId id) {
        this.id = id;
    }

    
    @Column(name="IDACTION", length=20)
    public String getIdaction() {
        return this.idaction;
    }
    
    public void setIdaction(String idaction) {
        this.idaction = idaction;
    }

    
    @Column(name="IDFCATREF", length=15)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

    
    @Column(name="REQUESTDATA", length=4000)
    public String getRequestdata() {
        return this.requestdata;
    }
    
    public void setRequestdata(String requestdata) {
        this.requestdata = requestdata;
    }

    
    @Column(name="REQUESTDATA2")
    public Blob getRequestdata2() {
        return this.requestdata2;
    }
    
    public void setRequestdata2(Blob requestdata2) {
        this.requestdata2 = requestdata2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCREATED", length=7)
    public Date getDatcreated() {
        return this.datcreated;
    }
    
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEXPIRY", length=7)
    public Date getDatexpiry() {
        return this.datexpiry;
    }
    
    public void setDatexpiry(Date datexpiry) {
        this.datexpiry = datexpiry;
    }




}


