package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txnalertstatus generated by hbm2java
 */
@Entity
@Table(name="TXNALERTSTATUS"
    ,schema="FCDBADMIN_RK"
)
public class Txnalertstatus  implements java.io.Serializable {


     private TxnalertstatusId id;
     private Date sentdate;

    public Txnalertstatus() {
    }

	
    public Txnalertstatus(TxnalertstatusId id) {
        this.id = id;
    }
    public Txnalertstatus(TxnalertstatusId id, Date sentdate) {
       this.id = id;
       this.sentdate = sentdate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idfcatref", column=@Column(name="IDFCATREF", nullable=false, length=20) ), 
        @AttributeOverride(name="idalert", column=@Column(name="IDALERT", nullable=false, length=50) ), 
        @AttributeOverride(name="condition", column=@Column(name="CONDITION", nullable=false, length=50) ) } )
    public TxnalertstatusId getId() {
        return this.id;
    }
    
    public void setId(TxnalertstatusId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SENTDATE", length=7)
    public Date getSentdate() {
        return this.sentdate;
    }
    
    public void setSentdate(Date sentdate) {
        this.sentdate = sentdate;
    }




}


