package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txncutofftime generated by hbm2java
 */
@Entity
@Table(name="TXNCUTOFFTIME"
    ,schema="FCDBADMIN_RK"
)
public class Txncutofftime  implements java.io.Serializable {


     private long cutoffseq;
     private String idEntity;
     private String idtxn;
     private String usertype;
     private String idchannel;
     private Date effectivedate;

    public Txncutofftime() {
    }

	
    public Txncutofftime(long cutoffseq) {
        this.cutoffseq = cutoffseq;
    }
    public Txncutofftime(long cutoffseq, String idEntity, String idtxn, String usertype, String idchannel, Date effectivedate) {
       this.cutoffseq = cutoffseq;
       this.idEntity = idEntity;
       this.idtxn = idtxn;
       this.usertype = usertype;
       this.idchannel = idchannel;
       this.effectivedate = effectivedate;
    }
   
     @Id 

    
    @Column(name="CUTOFFSEQ", unique=true, nullable=false, precision=10, scale=0)
    public long getCutoffseq() {
        return this.cutoffseq;
    }
    
    public void setCutoffseq(long cutoffseq) {
        this.cutoffseq = cutoffseq;
    }

    
    @Column(name="ID_ENTITY", length=5)
    public String getIdEntity() {
        return this.idEntity;
    }
    
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    
    @Column(name="IDTXN", length=3)
    public String getIdtxn() {
        return this.idtxn;
    }
    
    public void setIdtxn(String idtxn) {
        this.idtxn = idtxn;
    }

    
    @Column(name="USERTYPE", length=3)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    
    @Column(name="IDCHANNEL", length=3)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVEDATE", length=7)
    public Date getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(Date effectivedate) {
        this.effectivedate = effectivedate;
    }




}


