package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Txndealtimerdetails generated by hbm2java
 */
@Entity
@Table(name="TXNDEALTIMERDETAILS"
    ,schema="FCDBADMIN_RK"
)
public class Txndealtimerdetails  implements java.io.Serializable {


     private TxndealtimerdetailsId id;
     private Short starttime;
     private Short endtime;

    public Txndealtimerdetails() {
    }

	
    public Txndealtimerdetails(TxndealtimerdetailsId id) {
        this.id = id;
    }
    public Txndealtimerdetails(TxndealtimerdetailsId id, Short starttime, Short endtime) {
       this.id = id;
       this.starttime = starttime;
       this.endtime = endtime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="timerseq", column=@Column(name="TIMERSEQ", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="workingday", column=@Column(name="WORKINGDAY", nullable=false, length=10) ) } )
    public TxndealtimerdetailsId getId() {
        return this.id;
    }
    
    public void setId(TxndealtimerdetailsId id) {
        this.id = id;
    }

    
    @Column(name="STARTTIME", precision=4, scale=0)
    public Short getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Short starttime) {
        this.starttime = starttime;
    }

    
    @Column(name="ENDTIME", precision=4, scale=0)
    public Short getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Short endtime) {
        this.endtime = endtime;
    }




}


