package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txnexternalacct generated by hbm2java
 */
@Entity
@Table(name="TXNEXTERNALACCT"
    ,schema="FCDBADMIN_RK"
)
public class Txnexternalacct  implements java.io.Serializable {


     private String idfcatref;
     private Mstuser mstuserByIdauthorizer;
     private Mstuser mstuserByIdinitiator;
     private String idcorporate;
     private String codeamode;
     private String idaccount;
     private String extacctname;
     private String codcurrency;
     private Date effstdate;
     private Date effenddate;
     private String swiftcode;
     private String codbank;
     private String nambank;
     private String codbranch;
     private String nambranch;
     private String bradd1;
     private String bradd2;
     private String bradd3;
     private String codstatus;
     private String txtreason;
     private Date datinitiation;
     private Date datauthorize;
     private String txthostref;
     private Date dathostaction;
     private String narrative;
     private Date dtime;
     private BigDecimal slno;
     private String sndrtorecvrinfo1;
     private String sndrtorecvrinfo2;
     private String sndrtorecvrinfo3;
     private String sndrtorecvrinfo4;
     private String sndrtorecvrinfo5;
     private String sndrtorecvrinfo6;
     private String benefid;
     private String status;

    public Txnexternalacct() {
    }

	
    public Txnexternalacct(String idfcatref) {
        this.idfcatref = idfcatref;
    }
    public Txnexternalacct(String idfcatref, Mstuser mstuserByIdauthorizer, Mstuser mstuserByIdinitiator, String idcorporate, String codeamode, String idaccount, String extacctname, String codcurrency, Date effstdate, Date effenddate, String swiftcode, String codbank, String nambank, String codbranch, String nambranch, String bradd1, String bradd2, String bradd3, String codstatus, String txtreason, Date datinitiation, Date datauthorize, String txthostref, Date dathostaction, String narrative, Date dtime, BigDecimal slno, String sndrtorecvrinfo1, String sndrtorecvrinfo2, String sndrtorecvrinfo3, String sndrtorecvrinfo4, String sndrtorecvrinfo5, String sndrtorecvrinfo6, String benefid, String status) {
       this.idfcatref = idfcatref;
       this.mstuserByIdauthorizer = mstuserByIdauthorizer;
       this.mstuserByIdinitiator = mstuserByIdinitiator;
       this.idcorporate = idcorporate;
       this.codeamode = codeamode;
       this.idaccount = idaccount;
       this.extacctname = extacctname;
       this.codcurrency = codcurrency;
       this.effstdate = effstdate;
       this.effenddate = effenddate;
       this.swiftcode = swiftcode;
       this.codbank = codbank;
       this.nambank = nambank;
       this.codbranch = codbranch;
       this.nambranch = nambranch;
       this.bradd1 = bradd1;
       this.bradd2 = bradd2;
       this.bradd3 = bradd3;
       this.codstatus = codstatus;
       this.txtreason = txtreason;
       this.datinitiation = datinitiation;
       this.datauthorize = datauthorize;
       this.txthostref = txthostref;
       this.dathostaction = dathostaction;
       this.narrative = narrative;
       this.dtime = dtime;
       this.slno = slno;
       this.sndrtorecvrinfo1 = sndrtorecvrinfo1;
       this.sndrtorecvrinfo2 = sndrtorecvrinfo2;
       this.sndrtorecvrinfo3 = sndrtorecvrinfo3;
       this.sndrtorecvrinfo4 = sndrtorecvrinfo4;
       this.sndrtorecvrinfo5 = sndrtorecvrinfo5;
       this.sndrtorecvrinfo6 = sndrtorecvrinfo6;
       this.benefid = benefid;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="IDFCATREF", unique=true, nullable=false, length=15)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAUTHORIZER")
    public Mstuser getMstuserByIdauthorizer() {
        return this.mstuserByIdauthorizer;
    }
    
    public void setMstuserByIdauthorizer(Mstuser mstuserByIdauthorizer) {
        this.mstuserByIdauthorizer = mstuserByIdauthorizer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINITIATOR")
    public Mstuser getMstuserByIdinitiator() {
        return this.mstuserByIdinitiator;
    }
    
    public void setMstuserByIdinitiator(Mstuser mstuserByIdinitiator) {
        this.mstuserByIdinitiator = mstuserByIdinitiator;
    }

    
    @Column(name="IDCORPORATE", length=20)
    public String getIdcorporate() {
        return this.idcorporate;
    }
    
    public void setIdcorporate(String idcorporate) {
        this.idcorporate = idcorporate;
    }

    
    @Column(name="CODEAMODE", length=3)
    public String getCodeamode() {
        return this.codeamode;
    }
    
    public void setCodeamode(String codeamode) {
        this.codeamode = codeamode;
    }

    
    @Column(name="IDACCOUNT", length=20)
    public String getIdaccount() {
        return this.idaccount;
    }
    
    public void setIdaccount(String idaccount) {
        this.idaccount = idaccount;
    }

    
    @Column(name="EXTACCTNAME")
    public String getExtacctname() {
        return this.extacctname;
    }
    
    public void setExtacctname(String extacctname) {
        this.extacctname = extacctname;
    }

    
    @Column(name="CODCURRENCY", length=3)
    public String getCodcurrency() {
        return this.codcurrency;
    }
    
    public void setCodcurrency(String codcurrency) {
        this.codcurrency = codcurrency;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFSTDATE", length=7)
    public Date getEffstdate() {
        return this.effstdate;
    }
    
    public void setEffstdate(Date effstdate) {
        this.effstdate = effstdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFENDDATE", length=7)
    public Date getEffenddate() {
        return this.effenddate;
    }
    
    public void setEffenddate(Date effenddate) {
        this.effenddate = effenddate;
    }

    
    @Column(name="SWIFTCODE", length=15)
    public String getSwiftcode() {
        return this.swiftcode;
    }
    
    public void setSwiftcode(String swiftcode) {
        this.swiftcode = swiftcode;
    }

    
    @Column(name="CODBANK", length=10)
    public String getCodbank() {
        return this.codbank;
    }
    
    public void setCodbank(String codbank) {
        this.codbank = codbank;
    }

    
    @Column(name="NAMBANK", length=100)
    public String getNambank() {
        return this.nambank;
    }
    
    public void setNambank(String nambank) {
        this.nambank = nambank;
    }

    
    @Column(name="CODBRANCH", length=10)
    public String getCodbranch() {
        return this.codbranch;
    }
    
    public void setCodbranch(String codbranch) {
        this.codbranch = codbranch;
    }

    
    @Column(name="NAMBRANCH", length=100)
    public String getNambranch() {
        return this.nambranch;
    }
    
    public void setNambranch(String nambranch) {
        this.nambranch = nambranch;
    }

    
    @Column(name="BRADD1")
    public String getBradd1() {
        return this.bradd1;
    }
    
    public void setBradd1(String bradd1) {
        this.bradd1 = bradd1;
    }

    
    @Column(name="BRADD2")
    public String getBradd2() {
        return this.bradd2;
    }
    
    public void setBradd2(String bradd2) {
        this.bradd2 = bradd2;
    }

    
    @Column(name="BRADD3")
    public String getBradd3() {
        return this.bradd3;
    }
    
    public void setBradd3(String bradd3) {
        this.bradd3 = bradd3;
    }

    
    @Column(name="CODSTATUS", length=3)
    public String getCodstatus() {
        return this.codstatus;
    }
    
    public void setCodstatus(String codstatus) {
        this.codstatus = codstatus;
    }

    
    @Column(name="TXTREASON")
    public String getTxtreason() {
        return this.txtreason;
    }
    
    public void setTxtreason(String txtreason) {
        this.txtreason = txtreason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATINITIATION", length=7)
    public Date getDatinitiation() {
        return this.datinitiation;
    }
    
    public void setDatinitiation(Date datinitiation) {
        this.datinitiation = datinitiation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATAUTHORIZE", length=7)
    public Date getDatauthorize() {
        return this.datauthorize;
    }
    
    public void setDatauthorize(Date datauthorize) {
        this.datauthorize = datauthorize;
    }

    
    @Column(name="TXTHOSTREF", length=20)
    public String getTxthostref() {
        return this.txthostref;
    }
    
    public void setTxthostref(String txthostref) {
        this.txthostref = txthostref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATHOSTACTION", length=7)
    public Date getDathostaction() {
        return this.dathostaction;
    }
    
    public void setDathostaction(Date dathostaction) {
        this.dathostaction = dathostaction;
    }

    
    @Column(name="NARRATIVE")
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    
    @Column(name="SNDRTORECVRINFO1", length=35)
    public String getSndrtorecvrinfo1() {
        return this.sndrtorecvrinfo1;
    }
    
    public void setSndrtorecvrinfo1(String sndrtorecvrinfo1) {
        this.sndrtorecvrinfo1 = sndrtorecvrinfo1;
    }

    
    @Column(name="SNDRTORECVRINFO2", length=35)
    public String getSndrtorecvrinfo2() {
        return this.sndrtorecvrinfo2;
    }
    
    public void setSndrtorecvrinfo2(String sndrtorecvrinfo2) {
        this.sndrtorecvrinfo2 = sndrtorecvrinfo2;
    }

    
    @Column(name="SNDRTORECVRINFO3", length=35)
    public String getSndrtorecvrinfo3() {
        return this.sndrtorecvrinfo3;
    }
    
    public void setSndrtorecvrinfo3(String sndrtorecvrinfo3) {
        this.sndrtorecvrinfo3 = sndrtorecvrinfo3;
    }

    
    @Column(name="SNDRTORECVRINFO4", length=35)
    public String getSndrtorecvrinfo4() {
        return this.sndrtorecvrinfo4;
    }
    
    public void setSndrtorecvrinfo4(String sndrtorecvrinfo4) {
        this.sndrtorecvrinfo4 = sndrtorecvrinfo4;
    }

    
    @Column(name="SNDRTORECVRINFO5", length=35)
    public String getSndrtorecvrinfo5() {
        return this.sndrtorecvrinfo5;
    }
    
    public void setSndrtorecvrinfo5(String sndrtorecvrinfo5) {
        this.sndrtorecvrinfo5 = sndrtorecvrinfo5;
    }

    
    @Column(name="SNDRTORECVRINFO6", length=35)
    public String getSndrtorecvrinfo6() {
        return this.sndrtorecvrinfo6;
    }
    
    public void setSndrtorecvrinfo6(String sndrtorecvrinfo6) {
        this.sndrtorecvrinfo6 = sndrtorecvrinfo6;
    }

    
    @Column(name="BENEFID", length=30)
    public String getBenefid() {
        return this.benefid;
    }
    
    public void setBenefid(String benefid) {
        this.benefid = benefid;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


