package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txnfundstransfer generated by hbm2java
 */
@Entity
@Table(name="TXNFUNDSTRANSFER"
    ,schema="FCDBADMIN_RK"
)
public class Txnfundstransfer  implements java.io.Serializable {


     private String idfcatref;
     private Mstuser mstuserByIdauthorizer1;
     private Mstuser mstuserByIdinitiator;
     private String iduserreference;
     private String idcorporate;
     private String codftmode;
     private String idlocation;
     private String codstatus;
     private Date datinitiation;
     private Date datauthorize1;
     private Date datsend;
     private String idauthorizer2;
     private String idsrcacct;
     private Date datauthorize2;
     private String codsrcbranch;
     private BigDecimal numamount;
     private String codtrncurr;
     private BigDecimal numbaseexchrate;
     private BigDecimal numbasecurrequiv;
     private BigDecimal numtrnexchrate;
     private String txtdestacct;
     private String txtdestbranch;
     private String iddestbank;
     private String txtbenname;
     private String txtbenaddress1;
     private String txtbenaddress2;
     private String txtbenaddress3;
     private String txtpaymtdetails1;
     private String txtpaymtdetails2;
     private String txtpaymtdetails3;
     private String txtpaymtdetails4;
     private String txtbankdetails1;
     private String txtbankdetails2;
     private String txtbankdetails3;
     private String txtbankdetails4;
     private String codcharge;
     private String coddelivery;
     private String txtreason;
     private String txthostref;
     private Date dathostaction;
     private BigDecimal eefcpercent;
     private String eefcccy;
     private BigDecimal eefcamount;
     private BigDecimal numstatebit;
     private Character waiveflag;
     private String destsortcode;
     private BigDecimal fxrate;
     private String narrative;
     private Date dtime;
     private BigDecimal slno;
     private String sndrtorecvrinfo1;
     private String sndrtorecvrinfo2;
     private String sndrtorecvrinfo3;
     private String sndrtorecvrinfo4;
     private String sndrtorecvrinfo5;
     private String sndrtorecvrinfo6;
     private String benefid;
     private String destbiccode;
     private String destcountrycode;
     private Long nationalclearancecode;
     private Character typnationalclearancecod;

    public Txnfundstransfer() {
    }

	
    public Txnfundstransfer(String idfcatref) {
        this.idfcatref = idfcatref;
    }
    public Txnfundstransfer(String idfcatref, Mstuser mstuserByIdauthorizer1, Mstuser mstuserByIdinitiator, String iduserreference, String idcorporate, String codftmode, String idlocation, String codstatus, Date datinitiation, Date datauthorize1, Date datsend, String idauthorizer2, String idsrcacct, Date datauthorize2, String codsrcbranch, BigDecimal numamount, String codtrncurr, BigDecimal numbaseexchrate, BigDecimal numbasecurrequiv, BigDecimal numtrnexchrate, String txtdestacct, String txtdestbranch, String iddestbank, String txtbenname, String txtbenaddress1, String txtbenaddress2, String txtbenaddress3, String txtpaymtdetails1, String txtpaymtdetails2, String txtpaymtdetails3, String txtpaymtdetails4, String txtbankdetails1, String txtbankdetails2, String txtbankdetails3, String txtbankdetails4, String codcharge, String coddelivery, String txtreason, String txthostref, Date dathostaction, BigDecimal eefcpercent, String eefcccy, BigDecimal eefcamount, BigDecimal numstatebit, Character waiveflag, String destsortcode, BigDecimal fxrate, String narrative, Date dtime, BigDecimal slno, String sndrtorecvrinfo1, String sndrtorecvrinfo2, String sndrtorecvrinfo3, String sndrtorecvrinfo4, String sndrtorecvrinfo5, String sndrtorecvrinfo6, String benefid, String destbiccode, String destcountrycode, Long nationalclearancecode, Character typnationalclearancecod) {
       this.idfcatref = idfcatref;
       this.mstuserByIdauthorizer1 = mstuserByIdauthorizer1;
       this.mstuserByIdinitiator = mstuserByIdinitiator;
       this.iduserreference = iduserreference;
       this.idcorporate = idcorporate;
       this.codftmode = codftmode;
       this.idlocation = idlocation;
       this.codstatus = codstatus;
       this.datinitiation = datinitiation;
       this.datauthorize1 = datauthorize1;
       this.datsend = datsend;
       this.idauthorizer2 = idauthorizer2;
       this.idsrcacct = idsrcacct;
       this.datauthorize2 = datauthorize2;
       this.codsrcbranch = codsrcbranch;
       this.numamount = numamount;
       this.codtrncurr = codtrncurr;
       this.numbaseexchrate = numbaseexchrate;
       this.numbasecurrequiv = numbasecurrequiv;
       this.numtrnexchrate = numtrnexchrate;
       this.txtdestacct = txtdestacct;
       this.txtdestbranch = txtdestbranch;
       this.iddestbank = iddestbank;
       this.txtbenname = txtbenname;
       this.txtbenaddress1 = txtbenaddress1;
       this.txtbenaddress2 = txtbenaddress2;
       this.txtbenaddress3 = txtbenaddress3;
       this.txtpaymtdetails1 = txtpaymtdetails1;
       this.txtpaymtdetails2 = txtpaymtdetails2;
       this.txtpaymtdetails3 = txtpaymtdetails3;
       this.txtpaymtdetails4 = txtpaymtdetails4;
       this.txtbankdetails1 = txtbankdetails1;
       this.txtbankdetails2 = txtbankdetails2;
       this.txtbankdetails3 = txtbankdetails3;
       this.txtbankdetails4 = txtbankdetails4;
       this.codcharge = codcharge;
       this.coddelivery = coddelivery;
       this.txtreason = txtreason;
       this.txthostref = txthostref;
       this.dathostaction = dathostaction;
       this.eefcpercent = eefcpercent;
       this.eefcccy = eefcccy;
       this.eefcamount = eefcamount;
       this.numstatebit = numstatebit;
       this.waiveflag = waiveflag;
       this.destsortcode = destsortcode;
       this.fxrate = fxrate;
       this.narrative = narrative;
       this.dtime = dtime;
       this.slno = slno;
       this.sndrtorecvrinfo1 = sndrtorecvrinfo1;
       this.sndrtorecvrinfo2 = sndrtorecvrinfo2;
       this.sndrtorecvrinfo3 = sndrtorecvrinfo3;
       this.sndrtorecvrinfo4 = sndrtorecvrinfo4;
       this.sndrtorecvrinfo5 = sndrtorecvrinfo5;
       this.sndrtorecvrinfo6 = sndrtorecvrinfo6;
       this.benefid = benefid;
       this.destbiccode = destbiccode;
       this.destcountrycode = destcountrycode;
       this.nationalclearancecode = nationalclearancecode;
       this.typnationalclearancecod = typnationalclearancecod;
    }
   
     @Id 

    
    @Column(name="IDFCATREF", unique=true, nullable=false, length=15)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAUTHORIZER1")
    public Mstuser getMstuserByIdauthorizer1() {
        return this.mstuserByIdauthorizer1;
    }
    
    public void setMstuserByIdauthorizer1(Mstuser mstuserByIdauthorizer1) {
        this.mstuserByIdauthorizer1 = mstuserByIdauthorizer1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDINITIATOR")
    public Mstuser getMstuserByIdinitiator() {
        return this.mstuserByIdinitiator;
    }
    
    public void setMstuserByIdinitiator(Mstuser mstuserByIdinitiator) {
        this.mstuserByIdinitiator = mstuserByIdinitiator;
    }

    
    @Column(name="IDUSERREFERENCE", length=20)
    public String getIduserreference() {
        return this.iduserreference;
    }
    
    public void setIduserreference(String iduserreference) {
        this.iduserreference = iduserreference;
    }

    
    @Column(name="IDCORPORATE", length=20)
    public String getIdcorporate() {
        return this.idcorporate;
    }
    
    public void setIdcorporate(String idcorporate) {
        this.idcorporate = idcorporate;
    }

    
    @Column(name="CODFTMODE", length=3)
    public String getCodftmode() {
        return this.codftmode;
    }
    
    public void setCodftmode(String codftmode) {
        this.codftmode = codftmode;
    }

    
    @Column(name="IDLOCATION", length=20)
    public String getIdlocation() {
        return this.idlocation;
    }
    
    public void setIdlocation(String idlocation) {
        this.idlocation = idlocation;
    }

    
    @Column(name="CODSTATUS", length=3)
    public String getCodstatus() {
        return this.codstatus;
    }
    
    public void setCodstatus(String codstatus) {
        this.codstatus = codstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATINITIATION", length=7)
    public Date getDatinitiation() {
        return this.datinitiation;
    }
    
    public void setDatinitiation(Date datinitiation) {
        this.datinitiation = datinitiation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATAUTHORIZE1", length=7)
    public Date getDatauthorize1() {
        return this.datauthorize1;
    }
    
    public void setDatauthorize1(Date datauthorize1) {
        this.datauthorize1 = datauthorize1;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATSEND", length=7)
    public Date getDatsend() {
        return this.datsend;
    }
    
    public void setDatsend(Date datsend) {
        this.datsend = datsend;
    }

    
    @Column(name="IDAUTHORIZER2", length=10)
    public String getIdauthorizer2() {
        return this.idauthorizer2;
    }
    
    public void setIdauthorizer2(String idauthorizer2) {
        this.idauthorizer2 = idauthorizer2;
    }

    
    @Column(name="IDSRCACCT", length=30)
    public String getIdsrcacct() {
        return this.idsrcacct;
    }
    
    public void setIdsrcacct(String idsrcacct) {
        this.idsrcacct = idsrcacct;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATAUTHORIZE2", length=7)
    public Date getDatauthorize2() {
        return this.datauthorize2;
    }
    
    public void setDatauthorize2(Date datauthorize2) {
        this.datauthorize2 = datauthorize2;
    }

    
    @Column(name="CODSRCBRANCH", length=5)
    public String getCodsrcbranch() {
        return this.codsrcbranch;
    }
    
    public void setCodsrcbranch(String codsrcbranch) {
        this.codsrcbranch = codsrcbranch;
    }

    
    @Column(name="NUMAMOUNT", scale=4)
    public BigDecimal getNumamount() {
        return this.numamount;
    }
    
    public void setNumamount(BigDecimal numamount) {
        this.numamount = numamount;
    }

    
    @Column(name="CODTRNCURR", length=3)
    public String getCodtrncurr() {
        return this.codtrncurr;
    }
    
    public void setCodtrncurr(String codtrncurr) {
        this.codtrncurr = codtrncurr;
    }

    
    @Column(name="NUMBASEEXCHRATE", precision=16, scale=6)
    public BigDecimal getNumbaseexchrate() {
        return this.numbaseexchrate;
    }
    
    public void setNumbaseexchrate(BigDecimal numbaseexchrate) {
        this.numbaseexchrate = numbaseexchrate;
    }

    
    @Column(name="NUMBASECURREQUIV", scale=4)
    public BigDecimal getNumbasecurrequiv() {
        return this.numbasecurrequiv;
    }
    
    public void setNumbasecurrequiv(BigDecimal numbasecurrequiv) {
        this.numbasecurrequiv = numbasecurrequiv;
    }

    
    @Column(name="NUMTRNEXCHRATE", precision=16, scale=6)
    public BigDecimal getNumtrnexchrate() {
        return this.numtrnexchrate;
    }
    
    public void setNumtrnexchrate(BigDecimal numtrnexchrate) {
        this.numtrnexchrate = numtrnexchrate;
    }

    
    @Column(name="TXTDESTACCT", length=35)
    public String getTxtdestacct() {
        return this.txtdestacct;
    }
    
    public void setTxtdestacct(String txtdestacct) {
        this.txtdestacct = txtdestacct;
    }

    
    @Column(name="TXTDESTBRANCH", length=50)
    public String getTxtdestbranch() {
        return this.txtdestbranch;
    }
    
    public void setTxtdestbranch(String txtdestbranch) {
        this.txtdestbranch = txtdestbranch;
    }

    
    @Column(name="IDDESTBANK", length=20)
    public String getIddestbank() {
        return this.iddestbank;
    }
    
    public void setIddestbank(String iddestbank) {
        this.iddestbank = iddestbank;
    }

    
    @Column(name="TXTBENNAME", length=35)
    public String getTxtbenname() {
        return this.txtbenname;
    }
    
    public void setTxtbenname(String txtbenname) {
        this.txtbenname = txtbenname;
    }

    
    @Column(name="TXTBENADDRESS1", length=35)
    public String getTxtbenaddress1() {
        return this.txtbenaddress1;
    }
    
    public void setTxtbenaddress1(String txtbenaddress1) {
        this.txtbenaddress1 = txtbenaddress1;
    }

    
    @Column(name="TXTBENADDRESS2", length=35)
    public String getTxtbenaddress2() {
        return this.txtbenaddress2;
    }
    
    public void setTxtbenaddress2(String txtbenaddress2) {
        this.txtbenaddress2 = txtbenaddress2;
    }

    
    @Column(name="TXTBENADDRESS3", length=35)
    public String getTxtbenaddress3() {
        return this.txtbenaddress3;
    }
    
    public void setTxtbenaddress3(String txtbenaddress3) {
        this.txtbenaddress3 = txtbenaddress3;
    }

    
    @Column(name="TXTPAYMTDETAILS1", length=50)
    public String getTxtpaymtdetails1() {
        return this.txtpaymtdetails1;
    }
    
    public void setTxtpaymtdetails1(String txtpaymtdetails1) {
        this.txtpaymtdetails1 = txtpaymtdetails1;
    }

    
    @Column(name="TXTPAYMTDETAILS2", length=35)
    public String getTxtpaymtdetails2() {
        return this.txtpaymtdetails2;
    }
    
    public void setTxtpaymtdetails2(String txtpaymtdetails2) {
        this.txtpaymtdetails2 = txtpaymtdetails2;
    }

    
    @Column(name="TXTPAYMTDETAILS3", length=35)
    public String getTxtpaymtdetails3() {
        return this.txtpaymtdetails3;
    }
    
    public void setTxtpaymtdetails3(String txtpaymtdetails3) {
        this.txtpaymtdetails3 = txtpaymtdetails3;
    }

    
    @Column(name="TXTPAYMTDETAILS4", length=35)
    public String getTxtpaymtdetails4() {
        return this.txtpaymtdetails4;
    }
    
    public void setTxtpaymtdetails4(String txtpaymtdetails4) {
        this.txtpaymtdetails4 = txtpaymtdetails4;
    }

    
    @Column(name="TXTBANKDETAILS1", length=35)
    public String getTxtbankdetails1() {
        return this.txtbankdetails1;
    }
    
    public void setTxtbankdetails1(String txtbankdetails1) {
        this.txtbankdetails1 = txtbankdetails1;
    }

    
    @Column(name="TXTBANKDETAILS2", length=35)
    public String getTxtbankdetails2() {
        return this.txtbankdetails2;
    }
    
    public void setTxtbankdetails2(String txtbankdetails2) {
        this.txtbankdetails2 = txtbankdetails2;
    }

    
    @Column(name="TXTBANKDETAILS3", length=35)
    public String getTxtbankdetails3() {
        return this.txtbankdetails3;
    }
    
    public void setTxtbankdetails3(String txtbankdetails3) {
        this.txtbankdetails3 = txtbankdetails3;
    }

    
    @Column(name="TXTBANKDETAILS4", length=35)
    public String getTxtbankdetails4() {
        return this.txtbankdetails4;
    }
    
    public void setTxtbankdetails4(String txtbankdetails4) {
        this.txtbankdetails4 = txtbankdetails4;
    }

    
    @Column(name="CODCHARGE", length=3)
    public String getCodcharge() {
        return this.codcharge;
    }
    
    public void setCodcharge(String codcharge) {
        this.codcharge = codcharge;
    }

    
    @Column(name="CODDELIVERY", length=5)
    public String getCoddelivery() {
        return this.coddelivery;
    }
    
    public void setCoddelivery(String coddelivery) {
        this.coddelivery = coddelivery;
    }

    
    @Column(name="TXTREASON")
    public String getTxtreason() {
        return this.txtreason;
    }
    
    public void setTxtreason(String txtreason) {
        this.txtreason = txtreason;
    }

    
    @Column(name="TXTHOSTREF", length=20)
    public String getTxthostref() {
        return this.txthostref;
    }
    
    public void setTxthostref(String txthostref) {
        this.txthostref = txthostref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATHOSTACTION", length=7)
    public Date getDathostaction() {
        return this.dathostaction;
    }
    
    public void setDathostaction(Date dathostaction) {
        this.dathostaction = dathostaction;
    }

    
    @Column(name="EEFCPERCENT", precision=10, scale=5)
    public BigDecimal getEefcpercent() {
        return this.eefcpercent;
    }
    
    public void setEefcpercent(BigDecimal eefcpercent) {
        this.eefcpercent = eefcpercent;
    }

    
    @Column(name="EEFCCCY", length=3)
    public String getEefcccy() {
        return this.eefcccy;
    }
    
    public void setEefcccy(String eefcccy) {
        this.eefcccy = eefcccy;
    }

    
    @Column(name="EEFCAMOUNT", precision=22, scale=3)
    public BigDecimal getEefcamount() {
        return this.eefcamount;
    }
    
    public void setEefcamount(BigDecimal eefcamount) {
        this.eefcamount = eefcamount;
    }

    
    @Column(name="NUMSTATEBIT", precision=38, scale=0)
    public BigDecimal getNumstatebit() {
        return this.numstatebit;
    }
    
    public void setNumstatebit(BigDecimal numstatebit) {
        this.numstatebit = numstatebit;
    }

    
    @Column(name="WAIVEFLAG", length=1)
    public Character getWaiveflag() {
        return this.waiveflag;
    }
    
    public void setWaiveflag(Character waiveflag) {
        this.waiveflag = waiveflag;
    }

    
    @Column(name="DESTSORTCODE", length=25)
    public String getDestsortcode() {
        return this.destsortcode;
    }
    
    public void setDestsortcode(String destsortcode) {
        this.destsortcode = destsortcode;
    }

    
    @Column(name="FXRATE", precision=10)
    public BigDecimal getFxrate() {
        return this.fxrate;
    }
    
    public void setFxrate(BigDecimal fxrate) {
        this.fxrate = fxrate;
    }

    
    @Column(name="NARRATIVE")
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DTIME", length=7)
    public Date getDtime() {
        return this.dtime;
    }
    
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    
    @Column(name="SLNO", precision=38, scale=0)
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    
    @Column(name="SNDRTORECVRINFO1", length=35)
    public String getSndrtorecvrinfo1() {
        return this.sndrtorecvrinfo1;
    }
    
    public void setSndrtorecvrinfo1(String sndrtorecvrinfo1) {
        this.sndrtorecvrinfo1 = sndrtorecvrinfo1;
    }

    
    @Column(name="SNDRTORECVRINFO2", length=35)
    public String getSndrtorecvrinfo2() {
        return this.sndrtorecvrinfo2;
    }
    
    public void setSndrtorecvrinfo2(String sndrtorecvrinfo2) {
        this.sndrtorecvrinfo2 = sndrtorecvrinfo2;
    }

    
    @Column(name="SNDRTORECVRINFO3", length=35)
    public String getSndrtorecvrinfo3() {
        return this.sndrtorecvrinfo3;
    }
    
    public void setSndrtorecvrinfo3(String sndrtorecvrinfo3) {
        this.sndrtorecvrinfo3 = sndrtorecvrinfo3;
    }

    
    @Column(name="SNDRTORECVRINFO4", length=35)
    public String getSndrtorecvrinfo4() {
        return this.sndrtorecvrinfo4;
    }
    
    public void setSndrtorecvrinfo4(String sndrtorecvrinfo4) {
        this.sndrtorecvrinfo4 = sndrtorecvrinfo4;
    }

    
    @Column(name="SNDRTORECVRINFO5", length=35)
    public String getSndrtorecvrinfo5() {
        return this.sndrtorecvrinfo5;
    }
    
    public void setSndrtorecvrinfo5(String sndrtorecvrinfo5) {
        this.sndrtorecvrinfo5 = sndrtorecvrinfo5;
    }

    
    @Column(name="SNDRTORECVRINFO6", length=35)
    public String getSndrtorecvrinfo6() {
        return this.sndrtorecvrinfo6;
    }
    
    public void setSndrtorecvrinfo6(String sndrtorecvrinfo6) {
        this.sndrtorecvrinfo6 = sndrtorecvrinfo6;
    }

    
    @Column(name="BENEFID", length=30)
    public String getBenefid() {
        return this.benefid;
    }
    
    public void setBenefid(String benefid) {
        this.benefid = benefid;
    }

    
    @Column(name="DESTBICCODE", length=25)
    public String getDestbiccode() {
        return this.destbiccode;
    }
    
    public void setDestbiccode(String destbiccode) {
        this.destbiccode = destbiccode;
    }

    
    @Column(name="DESTCOUNTRYCODE", length=3)
    public String getDestcountrycode() {
        return this.destcountrycode;
    }
    
    public void setDestcountrycode(String destcountrycode) {
        this.destcountrycode = destcountrycode;
    }

    
    @Column(name="NATIONALCLEARANCECODE", precision=16, scale=0)
    public Long getNationalclearancecode() {
        return this.nationalclearancecode;
    }
    
    public void setNationalclearancecode(Long nationalclearancecode) {
        this.nationalclearancecode = nationalclearancecode;
    }

    
    @Column(name="TYPNATIONALCLEARANCECOD", length=1)
    public Character getTypnationalclearancecod() {
        return this.typnationalclearancecod;
    }
    
    public void setTypnationalclearancecod(Character typnationalclearancecod) {
        this.typnationalclearancecod = typnationalclearancecod;
    }




}


