package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Txninitauthdatadet generated by hbm2java
 */
@Entity
@Table(name="TXNINITAUTHDATADET"
    ,schema="FCDBADMIN_RK"
)
public class Txninitauthdatadet  implements java.io.Serializable {


     private TxninitauthdatadetId id;
     private String namservice;
     private BigDecimal versionservice;
     private Blob requestdata;

    public Txninitauthdatadet() {
    }

	
    public Txninitauthdatadet(TxninitauthdatadetId id) {
        this.id = id;
    }
    public Txninitauthdatadet(TxninitauthdatadetId id, String namservice, BigDecimal versionservice, Blob requestdata) {
       this.id = id;
       this.namservice = namservice;
       this.versionservice = versionservice;
       this.requestdata = requestdata;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="parenttxninitrefno", column=@Column(name="PARENTTXNINITREFNO", nullable=false, length=25) ), 
        @AttributeOverride(name="idseq", column=@Column(name="IDSEQ", nullable=false, precision=22, scale=0) ) } )
    public TxninitauthdatadetId getId() {
        return this.id;
    }
    
    public void setId(TxninitauthdatadetId id) {
        this.id = id;
    }

    
    @Column(name="NAMSERVICE", length=4000)
    public String getNamservice() {
        return this.namservice;
    }
    
    public void setNamservice(String namservice) {
        this.namservice = namservice;
    }

    
    @Column(name="VERSIONSERVICE", precision=22, scale=0)
    public BigDecimal getVersionservice() {
        return this.versionservice;
    }
    
    public void setVersionservice(BigDecimal versionservice) {
        this.versionservice = versionservice;
    }

    
    @Column(name="REQUESTDATA")
    public Blob getRequestdata() {
        return this.requestdata;
    }
    
    public void setRequestdata(Blob requestdata) {
        this.requestdata = requestdata;
    }




}


