package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Txnreport generated by hbm2java
 */
@Entity
@Table(name="TXNREPORT"
    ,schema="FCDBADMIN_RK"
)
public class Txnreport  implements java.io.Serializable {


     private String idfcatref;
     private Mstreport mstreport;
     private Txntasks txntasks;
     private String iduser;
     private String idformat;
     private Date executiondate;
     private String execcode;
     private String errordesc;
     private Blob reportdata;

    public Txnreport() {
    }

	
    public Txnreport(String idfcatref) {
        this.idfcatref = idfcatref;
    }
    public Txnreport(String idfcatref, Mstreport mstreport, Txntasks txntasks, String iduser, String idformat, Date executiondate, String execcode, String errordesc, Blob reportdata) {
       this.idfcatref = idfcatref;
       this.mstreport = mstreport;
       this.txntasks = txntasks;
       this.iduser = iduser;
       this.idformat = idformat;
       this.executiondate = executiondate;
       this.execcode = execcode;
       this.errordesc = errordesc;
       this.reportdata = reportdata;
    }
   
     @Id 

    
    @Column(name="IDFCATREF", unique=true, nullable=false, length=20)
    public String getIdfcatref() {
        return this.idfcatref;
    }
    
    public void setIdfcatref(String idfcatref) {
        this.idfcatref = idfcatref;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREPORT")
    public Mstreport getMstreport() {
        return this.mstreport;
    }
    
    public void setMstreport(Mstreport mstreport) {
        this.mstreport = mstreport;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTASKREF")
    public Txntasks getTxntasks() {
        return this.txntasks;
    }
    
    public void setTxntasks(Txntasks txntasks) {
        this.txntasks = txntasks;
    }

    
    @Column(name="IDUSER", length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="IDFORMAT", length=10)
    public String getIdformat() {
        return this.idformat;
    }
    
    public void setIdformat(String idformat) {
        this.idformat = idformat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXECUTIONDATE", length=7)
    public Date getExecutiondate() {
        return this.executiondate;
    }
    
    public void setExecutiondate(Date executiondate) {
        this.executiondate = executiondate;
    }

    
    @Column(name="EXECCODE", length=10)
    public String getExeccode() {
        return this.execcode;
    }
    
    public void setExeccode(String execcode) {
        this.execcode = execcode;
    }

    
    @Column(name="ERRORDESC", length=100)
    public String getErrordesc() {
        return this.errordesc;
    }
    
    public void setErrordesc(String errordesc) {
        this.errordesc = errordesc;
    }

    
    @Column(name="REPORTDATA")
    public Blob getReportdata() {
        return this.reportdata;
    }
    
    public void setReportdata(Blob reportdata) {
        this.reportdata = reportdata;
    }




}


