package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TxnRptMailattachments generated by hbm2java
 */
@Entity
@Table(name="TXN_RPT_MAILATTACHMENTS"
    ,schema="FCDBADMIN_RK"
)
public class TxnRptMailattachments  implements java.io.Serializable {


     private TxnRptMailattachmentsId id;
     private Date reportGenerationDate;
     private String emailId;
     private Character status;

    public TxnRptMailattachments() {
    }

	
    public TxnRptMailattachments(TxnRptMailattachmentsId id) {
        this.id = id;
    }
    public TxnRptMailattachments(TxnRptMailattachmentsId id, Date reportGenerationDate, String emailId, Character status) {
       this.id = id;
       this.reportGenerationDate = reportGenerationDate;
       this.emailId = emailId;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=10) ), 
        @AttributeOverride(name="reportName", column=@Column(name="REPORT_NAME", nullable=false, length=100) ) } )
    public TxnRptMailattachmentsId getId() {
        return this.id;
    }
    
    public void setId(TxnRptMailattachmentsId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REPORT_GENERATION_DATE", length=7)
    public Date getReportGenerationDate() {
        return this.reportGenerationDate;
    }
    
    public void setReportGenerationDate(Date reportGenerationDate) {
        this.reportGenerationDate = reportGenerationDate;
    }

    
    @Column(name="EMAIL_ID", length=50)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }




}


