package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UdfgrouptemplatemapId generated by hbm2java
 */
@Embeddable
public class UdfgrouptemplatemapId  implements java.io.Serializable {


     private String idgroup;
     private String idtemplate;
     private String idlang;
     private String iddevice;

    public UdfgrouptemplatemapId() {
    }

    public UdfgrouptemplatemapId(String idgroup, String idtemplate, String idlang, String iddevice) {
       this.idgroup = idgroup;
       this.idtemplate = idtemplate;
       this.idlang = idlang;
       this.iddevice = iddevice;
    }
   


    @Column(name="IDGROUP", nullable=false, length=40)
    public String getIdgroup() {
        return this.idgroup;
    }
    
    public void setIdgroup(String idgroup) {
        this.idgroup = idgroup;
    }


    @Column(name="IDTEMPLATE", nullable=false, length=60)
    public String getIdtemplate() {
        return this.idtemplate;
    }
    
    public void setIdtemplate(String idtemplate) {
        this.idtemplate = idtemplate;
    }


    @Column(name="IDLANG", nullable=false, length=3)
    public String getIdlang() {
        return this.idlang;
    }
    
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }


    @Column(name="IDDEVICE", nullable=false, length=2)
    public String getIddevice() {
        return this.iddevice;
    }
    
    public void setIddevice(String iddevice) {
        this.iddevice = iddevice;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UdfgrouptemplatemapId) ) return false;
		 UdfgrouptemplatemapId castOther = ( UdfgrouptemplatemapId ) other; 
         
		 return ( (this.getIdgroup()==castOther.getIdgroup()) || ( this.getIdgroup()!=null && castOther.getIdgroup()!=null && this.getIdgroup().equals(castOther.getIdgroup()) ) )
 && ( (this.getIdtemplate()==castOther.getIdtemplate()) || ( this.getIdtemplate()!=null && castOther.getIdtemplate()!=null && this.getIdtemplate().equals(castOther.getIdtemplate()) ) )
 && ( (this.getIdlang()==castOther.getIdlang()) || ( this.getIdlang()!=null && castOther.getIdlang()!=null && this.getIdlang().equals(castOther.getIdlang()) ) )
 && ( (this.getIddevice()==castOther.getIddevice()) || ( this.getIddevice()!=null && castOther.getIddevice()!=null && this.getIddevice().equals(castOther.getIddevice()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdgroup() == null ? 0 : this.getIdgroup().hashCode() );
         result = 37 * result + ( getIdtemplate() == null ? 0 : this.getIdtemplate().hashCode() );
         result = 37 * result + ( getIdlang() == null ? 0 : this.getIdlang().hashCode() );
         result = 37 * result + ( getIddevice() == null ? 0 : this.getIddevice().hashCode() );
         return result;
   }   


}


