package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Useraddismisslist generated by hbm2java
 */
@Entity
@Table(name="USERADDISMISSLIST"
    ,schema="FCDBADMIN_RK"
)
public class Useraddismisslist  implements java.io.Serializable {


     private UseraddismisslistId id;

    public Useraddismisslist() {
    }

    public Useraddismisslist(UseraddismisslistId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="adcode", column=@Column(name="ADCODE", nullable=false, length=20) ) } )
    public UseraddismisslistId getId() {
        return this.id;
    }
    
    public void setId(UseraddismisslistId id) {
        this.id = id;
    }




}


