package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Usercustrel generated by hbm2java
 */
@Entity
@Table(name="USERCUSTREL"
    ,schema="FCDBADMIN_RK"
)
public class Usercustrel  implements java.io.Serializable {


     private UsercustrelId id;
     private String isprimary;
     private String typecust;
     private String namcust;

    public Usercustrel() {
    }

	
    public Usercustrel(UsercustrelId id) {
        this.id = id;
    }
    public Usercustrel(UsercustrelId id, String isprimary, String typecust, String namcust) {
       this.id = id;
       this.isprimary = isprimary;
       this.typecust = typecust;
       this.namcust = namcust;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idcust", column=@Column(name="IDCUST", nullable=false, length=30) ), 
        @AttributeOverride(name="refIdEntity", column=@Column(name="REF_ID_ENTITY", nullable=false, length=4) ) } )
    public UsercustrelId getId() {
        return this.id;
    }
    
    public void setId(UsercustrelId id) {
        this.id = id;
    }

    
    @Column(name="ISPRIMARY", length=1)
    public String getIsprimary() {
        return this.isprimary;
    }
    
    public void setIsprimary(String isprimary) {
        this.isprimary = isprimary;
    }

    
    @Column(name="TYPECUST", length=3)
    public String getTypecust() {
        return this.typecust;
    }
    
    public void setTypecust(String typecust) {
        this.typecust = typecust;
    }

    
    @Column(name="NAMCUST", length=762)
    public String getNamcust() {
        return this.namcust;
    }
    
    public void setNamcust(String namcust) {
        this.namcust = namcust;
    }




}


