package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usercontact generated by hbm2java
 */
@Entity
@Table(name="USERCONTACT"
    ,schema="FCDBADMIN_RK"
)
public class Usercontact  implements java.io.Serializable {


     private UsercontactId id;
     private Mstuser mstuser;
     private String contactdetails;
     private Character verifystatus;
     private String displayname;
     private Date updationdate;

    public Usercontact() {
    }

	
    public Usercontact(UsercontactId id, Mstuser mstuser) {
        this.id = id;
        this.mstuser = mstuser;
    }
    public Usercontact(UsercontactId id, Mstuser mstuser, String contactdetails, Character verifystatus, String displayname, Date updationdate) {
       this.id = id;
       this.mstuser = mstuser;
       this.contactdetails = contactdetails;
       this.verifystatus = verifystatus;
       this.displayname = displayname;
       this.updationdate = updationdate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="typecontact", column=@Column(name="TYPECONTACT", nullable=false, length=2) ) } )
    public UsercontactId getId() {
        return this.id;
    }
    
    public void setId(UsercontactId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSER", nullable=false, insertable=false, updatable=false)
    public Mstuser getMstuser() {
        return this.mstuser;
    }
    
    public void setMstuser(Mstuser mstuser) {
        this.mstuser = mstuser;
    }

    
    @Column(name="CONTACTDETAILS")
    public String getContactdetails() {
        return this.contactdetails;
    }
    
    public void setContactdetails(String contactdetails) {
        this.contactdetails = contactdetails;
    }

    
    @Column(name="VERIFYSTATUS", length=1)
    public Character getVerifystatus() {
        return this.verifystatus;
    }
    
    public void setVerifystatus(Character verifystatus) {
        this.verifystatus = verifystatus;
    }

    
    @Column(name="DISPLAYNAME")
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATIONDATE", length=7)
    public Date getUpdationdate() {
        return this.updationdate;
    }
    
    public void setUpdationdate(Date updationdate) {
        this.updationdate = updationdate;
    }




}


