package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userreportmap generated by hbm2java
 */
@Entity
@Table(name="USERREPORTMAP"
    ,schema="FCDBADMIN_RK"
)
public class Userreportmap  implements java.io.Serializable {


     private UserreportmapId id;
     private Mstuser mstuser;
     private String descreport;
     private Date datmapped;
     private Character status;

    public Userreportmap() {
    }

	
    public Userreportmap(UserreportmapId id, Mstuser mstuser) {
        this.id = id;
        this.mstuser = mstuser;
    }
    public Userreportmap(UserreportmapId id, Mstuser mstuser, String descreport, Date datmapped, Character status) {
       this.id = id;
       this.mstuser = mstuser;
       this.descreport = descreport;
       this.datmapped = datmapped;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idreport", column=@Column(name="IDREPORT", nullable=false, length=50) ) } )
    public UserreportmapId getId() {
        return this.id;
    }
    
    public void setId(UserreportmapId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSER", nullable=false, insertable=false, updatable=false)
    public Mstuser getMstuser() {
        return this.mstuser;
    }
    
    public void setMstuser(Mstuser mstuser) {
        this.mstuser = mstuser;
    }

    
    @Column(name="DESCREPORT", length=40)
    public String getDescreport() {
        return this.descreport;
    }
    
    public void setDescreport(String descreport) {
        this.descreport = descreport;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATMAPPED", length=7)
    public Date getDatmapped() {
        return this.datmapped;
    }
    
    public void setDatmapped(Date datmapped) {
        this.datmapped = datmapped;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }




}


