package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usermenu generated by hbm2java
 */
@Entity
@Table(name="USERMENU"
    ,schema="FCDBADMIN_RK"
)
public class Usermenu  implements java.io.Serializable {


     private UsermenuId id;
     private Application application;
     private Mstserver mstserver;
     private String menuresult;

    public Usermenu() {
    }

	
    public Usermenu(UsermenuId id, Application application) {
        this.id = id;
        this.application = application;
    }
    public Usermenu(UsermenuId id, Application application, Mstserver mstserver, String menuresult) {
       this.id = id;
       this.application = application;
       this.mstserver = mstserver;
       this.menuresult = menuresult;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idsession", column=@Column(name="IDSESSION", nullable=false, length=50) ), 
        @AttributeOverride(name="idapp", column=@Column(name="IDAPP", nullable=false, length=2) ), 
        @AttributeOverride(name="numsequence", column=@Column(name="NUMSEQUENCE", nullable=false, precision=2, scale=0) ) } )
    public UsermenuId getId() {
        return this.id;
    }
    
    public void setId(UsermenuId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAPP", nullable=false, insertable=false, updatable=false)
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WEBSERVERID")
    public Mstserver getMstserver() {
        return this.mstserver;
    }
    
    public void setMstserver(Mstserver mstserver) {
        this.mstserver = mstserver;
    }

    
    @Column(name="MENURESULT", length=4000)
    public String getMenuresult() {
        return this.menuresult;
    }
    
    public void setMenuresult(String menuresult) {
        this.menuresult = menuresult;
    }




}


