package com.jmr.obdx.domain;

import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserSessionData generated by hbm2java
 */
@Entity
@Table(name = "USER_SESSION_DATA", schema = "JMR_OBDX", uniqueConstraints = @UniqueConstraint(columnNames = "IDSESSION"))
public class UserSessionData implements java.io.Serializable {

	private long id;
	private Login login;
	private String idsession;
	private String iddata;
	private Blob data;

	public UserSessionData() {
	}

	public UserSessionData(long id, Login login, String idsession, String iddata, Blob data) {
		this.id = id;
		this.login = login;
		this.idsession = idsession;
		this.iddata = iddata;
		this.data = data;
	}

	
	public UserSessionData(Login login, String idsession) {
		this.login = login;
		this.idsession = idsession;
		//this.iddata = iddata;
		//this.data = data;
	}
	
	
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGIN_REF_ID", nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "IDSESSION", unique = true, nullable = false, length = 50)
	public String getIdsession() {
		return this.idsession;
	}

	public void setIdsession(String idsession) {
		this.idsession = idsession;
	}

	@Column(name = "IDDATA", nullable = false, length = 50)
	public String getIddata() {
		return this.iddata;
	}

	public void setIddata(String iddata) {
		this.iddata = iddata;
	}

	@Column(name = "DATA", nullable = false)
	public Blob getData() {
		return this.data;
	}

	public void setData(Blob data) {
		this.data = data;
	}

}
