package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userhttpsession generated by hbm2java
 */
@Entity
@Table(name="USERHTTPSESSION"
    ,schema="FCDBADMIN_RK"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDUSER", "IDSESSION"}) 
)
public class Userhttpsession  implements java.io.Serializable {


     private String iduser;
     private String idsession;
     private Boolean validflag;
     private String proxyid;

    public Userhttpsession() {
    }

	
    public Userhttpsession(String iduser) {
        this.iduser = iduser;
    }
    public Userhttpsession(String iduser, String idsession, Boolean validflag, String proxyid) {
       this.iduser = iduser;
       this.idsession = idsession;
       this.validflag = validflag;
       this.proxyid = proxyid;
    }
   
     @Id 

    
    @Column(name="IDUSER", unique=true, nullable=false, length=20)
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="IDSESSION", length=50)
    public String getIdsession() {
        return this.idsession;
    }
    
    public void setIdsession(String idsession) {
        this.idsession = idsession;
    }

    
    @Column(name="VALIDFLAG", precision=1, scale=0)
    public Boolean getValidflag() {
        return this.validflag;
    }
    
    public void setValidflag(Boolean validflag) {
        this.validflag = validflag;
    }

    
    @Column(name="PROXYID", length=20)
    public String getProxyid() {
        return this.proxyid;
    }
    
    public void setProxyid(String proxyid) {
        this.proxyid = proxyid;
    }




}


