package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userpasswordprint generated by hbm2java
 */
@Entity
@Table(name="USERPASSWORDPRINT"
    ,schema="FCDBADMIN_RK"
)
public class Userpasswordprint  implements java.io.Serializable {


     private UserpasswordprintId id;
     private String idchannel;
     private String userpassword;
     private Date datchange;

    public Userpasswordprint() {
    }

	
    public Userpasswordprint(UserpasswordprintId id) {
        this.id = id;
    }
    public Userpasswordprint(UserpasswordprintId id, String idchannel, String userpassword, Date datchange) {
       this.id = id;
       this.idchannel = idchannel;
       this.userpassword = userpassword;
       this.datchange = datchange;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ), 
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="idchanneluser", column=@Column(name="IDCHANNELUSER", nullable=false) ), 
        @AttributeOverride(name="idtxn", column=@Column(name="IDTXN", nullable=false, length=3) ), 
        @AttributeOverride(name="idgroup", column=@Column(name="IDGROUP", nullable=false, length=5) ) } )
    public UserpasswordprintId getId() {
        return this.id;
    }
    
    public void setId(UserpasswordprintId id) {
        this.id = id;
    }

    
    @Column(name="IDCHANNEL", length=2)
    public String getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    
    @Column(name="USERPASSWORD", length=2000)
    public String getUserpassword() {
        return this.userpassword;
    }
    
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATCHANGE", length=7)
    public Date getDatchange() {
        return this.datchange;
    }
    
    public void setDatchange(Date datchange) {
        this.datchange = datchange;
    }




}


