package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserExternalAccount generated by hbm2java
 */
@Entity
@Table(name="USER_EXTERNAL_ACCOUNT"
    ,schema="FCDBADMIN_RK"
)
public class UserExternalAccount  implements java.io.Serializable {


     private UserExternalAccountId id;
     private String clgType;
     private String clgCode;
     private Character status;
     private String pennyAmt;
     private BigDecimal retryCount;
     private String origin;
     private String refNo;
     private String debitcust;
     private String debitsrcaccount;
     private String debitcurr;
     private String debitbranch;
     private String token1;
     private String token2;

    public UserExternalAccount() {
    }

	
    public UserExternalAccount(UserExternalAccountId id) {
        this.id = id;
    }
    public UserExternalAccount(UserExternalAccountId id, String clgType, String clgCode, Character status, String pennyAmt, BigDecimal retryCount, String origin, String refNo, String debitcust, String debitsrcaccount, String debitcurr, String debitbranch, String token1, String token2) {
       this.id = id;
       this.clgType = clgType;
       this.clgCode = clgCode;
       this.status = status;
       this.pennyAmt = pennyAmt;
       this.retryCount = retryCount;
       this.origin = origin;
       this.refNo = refNo;
       this.debitcust = debitcust;
       this.debitsrcaccount = debitsrcaccount;
       this.debitcurr = debitcurr;
       this.debitbranch = debitbranch;
       this.token1 = token1;
       this.token2 = token2;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="IDUSER", nullable=false, length=20) ), 
        @AttributeOverride(name="extAcctNo", column=@Column(name="EXT_ACCT_NO", nullable=false, length=35) ), 
        @AttributeOverride(name="idEntity", column=@Column(name="ID_ENTITY", nullable=false, length=5) ) } )
    public UserExternalAccountId getId() {
        return this.id;
    }
    
    public void setId(UserExternalAccountId id) {
        this.id = id;
    }

    
    @Column(name="CLG_TYPE", length=20)
    public String getClgType() {
        return this.clgType;
    }
    
    public void setClgType(String clgType) {
        this.clgType = clgType;
    }

    
    @Column(name="CLG_CODE", length=20)
    public String getClgCode() {
        return this.clgCode;
    }
    
    public void setClgCode(String clgCode) {
        this.clgCode = clgCode;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="PENNY_AMT", length=6)
    public String getPennyAmt() {
        return this.pennyAmt;
    }
    
    public void setPennyAmt(String pennyAmt) {
        this.pennyAmt = pennyAmt;
    }

    
    @Column(name="RETRY_COUNT", precision=22, scale=0)
    public BigDecimal getRetryCount() {
        return this.retryCount;
    }
    
    public void setRetryCount(BigDecimal retryCount) {
        this.retryCount = retryCount;
    }

    
    @Column(name="ORIGIN", length=10)
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    
    @Column(name="REF_NO", length=25)
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    
    @Column(name="DEBITCUST", length=20)
    public String getDebitcust() {
        return this.debitcust;
    }
    
    public void setDebitcust(String debitcust) {
        this.debitcust = debitcust;
    }

    
    @Column(name="DEBITSRCACCOUNT", length=20)
    public String getDebitsrcaccount() {
        return this.debitsrcaccount;
    }
    
    public void setDebitsrcaccount(String debitsrcaccount) {
        this.debitsrcaccount = debitsrcaccount;
    }

    
    @Column(name="DEBITCURR", length=3)
    public String getDebitcurr() {
        return this.debitcurr;
    }
    
    public void setDebitcurr(String debitcurr) {
        this.debitcurr = debitcurr;
    }

    
    @Column(name="DEBITBRANCH", length=4)
    public String getDebitbranch() {
        return this.debitbranch;
    }
    
    public void setDebitbranch(String debitbranch) {
        this.debitbranch = debitbranch;
    }

    
    @Column(name="TOKEN1", length=20)
    public String getToken1() {
        return this.token1;
    }
    
    public void setToken1(String token1) {
        this.token1 = token1;
    }

    
    @Column(name="TOKEN2", length=20)
    public String getToken2() {
        return this.token2;
    }
    
    public void setToken2(String token2) {
        this.token2 = token2;
    }




}


