package com.jmr.obdx.domain;
// Generated Jan 12, 2017 11:08:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usersessionsummary generated by hbm2java
 */
@Entity
@Table(name="USERSESSIONSUMMARY"
    ,schema="FCDBADMIN_RK"
)
public class Usersessionsummary  implements java.io.Serializable {


     private UsersessionsummaryId id;
     private Date datactivity;
     private String actdesc;
     private Set<Usersessionsumdtls> usersessionsumdtlses = new HashSet<Usersessionsumdtls>(0);

    public Usersessionsummary() {
    }

	
    public Usersessionsummary(UsersessionsummaryId id) {
        this.id = id;
    }
    public Usersessionsummary(UsersessionsummaryId id, Date datactivity, String actdesc, Set<Usersessionsumdtls> usersessionsumdtlses) {
       this.id = id;
       this.datactivity = datactivity;
       this.actdesc = actdesc;
       this.usersessionsumdtlses = usersessionsumdtlses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idsession", column=@Column(name="IDSESSION", nullable=false, length=50) ), 
        @AttributeOverride(name="seqnbr", column=@Column(name="SEQNBR", nullable=false, precision=4, scale=0) ) } )
    public UsersessionsummaryId getId() {
        return this.id;
    }
    
    public void setId(UsersessionsummaryId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATACTIVITY", length=7)
    public Date getDatactivity() {
        return this.datactivity;
    }
    
    public void setDatactivity(Date datactivity) {
        this.datactivity = datactivity;
    }

    
    @Column(name="ACTDESC")
    public String getActdesc() {
        return this.actdesc;
    }
    
    public void setActdesc(String actdesc) {
        this.actdesc = actdesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersessionsummary")
    public Set<Usersessionsumdtls> getUsersessionsumdtlses() {
        return this.usersessionsumdtlses;
    }
    
    public void setUsersessionsumdtlses(Set<Usersessionsumdtls> usersessionsumdtlses) {
        this.usersessionsumdtlses = usersessionsumdtlses;
    }




}


